force-app/main/default/objects/VisMed_Objetivo__c/VisMed_Objetivo__c.object-meta.xml
<CustomObject>
    <description>Objeto en el que se cargarán los objetivos que deberán cumplir los APM.</description>
    <label>Objetivo</label>
    <nameField>
        <label>Nombre de Objetivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objetivos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Objetivo__c/fields/VisMed_FechaFin__c.field-meta.xml
<CustomField>
    <fullName>VisMed_FechaFin__c</fullName>
    <label>Fecha de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_Objetivo__c/fields/VisMed_FechaInicio__c.field-meta.xml
<CustomField>
    <fullName>VisMed_FechaInicio__c</fullName>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_ObjetivoPorCuenta__c/VisMed_ObjetivoPorCuenta__c.object-meta.xml
<CustomObject>
    <description>Objeto que relacionará el profesional o la institución con el objetivo.</description>
    <label>Objetivo por cuenta</label>
    <nameField>
        <displayFormat>ObjXCue-{0000}</displayFormat>
        <label>Nombre de Objetivo por cuenta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objetivos por cuenta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_ObjetivoPorCuenta__c/fields/VisMed_FechaFin__c.field-meta.xml
<CustomField>
    <fullName>VisMed_FechaFin__c</fullName>
    <formula>VisMed_Objetivo__r.VisMed_FechaFin__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_ObjetivoPorCuenta__c/fields/VisMed_FechaInicio__c.field-meta.xml
<CustomField>
    <fullName>VisMed_FechaInicio__c</fullName>
    <formula>VisMed_Objetivo__r.VisMed_FechaInicio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_ObjetivoPorCuenta__c/fields/VisMed_Objetivo__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Objetivo__c</fullName>
    <label>Objetivo</label>
    <referenceTo>VisMed_Objetivo__c</referenceTo>
    <relationshipLabel>Objetivos por cuenta</relationshipLabel>
    <relationshipName>Objetivos_por_cuenta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ObjetivoTriggerHelper.cls
public class ObjetivoTriggerHelper {
    public static void activarObjetivoPorCuenta(List<VisMed_Objetivo__c> objetivos){        
        Set<Id> objetivoIds = new Set<Id>{};
        List<VisMed_ObjetivoPorCuenta__c> objetivosPorCuentaActivar = new List<VisMed_ObjetivoPorCuenta__c>();

        for (VisMed_Objetivo__c objetivo : objetivos) {
            if (objetivo.Estado__c == 'Activo') {
                objetivoIds.add(objetivo.Id);
            }
        }

        List<VisMed_ObjetivoPorCuenta__c> objetivosPorCuenta =  [
            SELECT Id, Name, VisMed_Objetivo__c, Estado__c
            FROM VisMed_ObjetivoPorCuenta__c
            WHERE VisMed_Objetivo__c IN :objetivoIds
        ];
       
        if(!objetivosPorCuenta.isEmpty()){
            for (VisMed_ObjetivoPorCuenta__c aObjetivoPorCuenta : objetivosPorCuenta) {
                aObjetivoPorCuenta.Estado__c = 'Activo';
                objetivosPorCuentaActivar.add(aObjetivoPorCuenta);
            }
            update objetivosPorCuentaActivar;
        }
    }

    public static void desactivarObjetivoPorCuenta(List<VisMed_Objetivo__c> objetivos){        
        Set<Id> objetivoIds = new Set<Id>{};
        List<VisMed_ObjetivoPorCuenta__c> objetivosPorCuentaDesactivar = new List<VisMed_ObjetivoPorCuenta__c>();

        for (VisMed_Objetivo__c objetivo : objetivos) {
            if (objetivo.Estado__c == 'Inactivo') {
                objetivoIds.add(objetivo.Id);
            }
        }

        List<VisMed_ObjetivoPorCuenta__c> objetivosPorCuenta =  [
            SELECT Id, Name, VisMed_Objetivo__c, Estado__c
            FROM VisMed_ObjetivoPorCuenta__c
            WHERE VisMed_Objetivo__c IN :objetivoIds
        ];
       
        if(!objetivosPorCuenta.isEmpty()){
            for (VisMed_ObjetivoPorCuenta__c aObjetivoPorCuenta : objetivosPorCuenta) {
                aObjetivoPorCuenta.Estado__c = 'Inactivo';
                objetivosPorCuentaDesactivar.add(aObjetivoPorCuenta);
            }
            update objetivosPorCuentaDesactivar;
        }
    }
    public static void activarODesactivarObjetivo(List<VisMed_Objetivo__c> objetivos){
        Date today = Date.today();  
        System.debug(Today);     
        for (VisMed_Objetivo__c objetivo : objetivos) {
            if (objetivo.VisMed_FechaInicio__c <= today && objetivo.VisMed_FechaFin__c >= today) {
                objetivo.Estado__c = 'Activo';
            }else {
                objetivo.Estado__c = 'Inactivo';
            }  
            System.debug('objetivo: '+ objetivo);         
            System.debug('objetivo estado: '+ objetivo.Estado__c);         
        }         
    }
}