force-app/main/default/objects/Dan360_Efectividad__c/Dan360_Efectividad__c.object-meta.xml
<CustomObject>
    <description>Objeto creado para el registro y calculo de las efectividades del APM por mes.</description>
    <label>Efectividad</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Efectividad Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Efectividades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Dias_de_Licencia_Transcurridos__c.field-meta.xml
<CustomField>
    <fullName>Dias_de_Licencia_Transcurridos__c</fullName>
    <description>almacena los dias de licencias NO Festivos que ya transcurrieron</description>
    <label>Días de Licencia</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Dias_feriados_Transcurridos__c.field-meta.xml
<CustomField>
    <fullName>Dias_feriados_Transcurridos__c</fullName>
    <label>Días feriados Transcurridos</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/VisMed_Dias_de_Licencia_Unicos__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Dias_de_Licencia_Unicos__c</fullName>
    <description>Almacena los dias de licencias que ya transcurrieron.</description>
    <label>Días de Licencia Unicos</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/Dan360_Licencia__c.object-meta.xml
<CustomObject>
    <description>Objeto para registrar las licencias y dias no promocionables del APM</description>
    <label>Licencia</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Licencia Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Licencia__c/fields/Efectividad__c.field-meta.xml
<CustomField>
    <fullName>Efectividad__c</fullName>
    <label>Efectividad</label>
    <referenceTo>Dan360_Efectividad__c</referenceTo>
    <relationshipLabel>Licencias</relationshipLabel>
    <relationshipName>Licencias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Estado de la licencia.</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Aprobada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <description>Fecha de finalizacion del la licencia/tiempo no promocional</description>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <description>Fecha de inicio desde que se tomo la licencia/tiempo no promocional</description>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/fields/Motivo__c.field-meta.xml
<CustomField>
    <fullName>Motivo__c</fullName>
    <description>Tipo de licencia/tiempo no promocional por el que se ausento el APM</description>
    <inlineHelpText>Motivo de ausencia</inlineHelpText>
    <label>Motivo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vacaciones</fullName>
            </value>
            <value>
                <fullName>Enfermedad</fullName>
            </value>
            <value>
                <fullName>Día de estudio</fullName>
            </value>
            <value>
                <fullName>Festivo</fullName>
            </value>
            <value>
                <fullName>Maternidad</fullName>
            </value>
            <value>
                <fullName>Reunión con jefe</fullName>
            </value>
            <value>
                <fullName>Reunión de equipo</fullName>
            </value>
            <value>
                <fullName>Congreso</fullName>
            </value>
            <value>
                <fullName>Otro</fullName>
            </value>
            <value>
                <fullName>Compensatorios</fullName>
            </value>
            <value>
                <fullName>Feriado provincial</fullName>
            </value>
            <value>
                <fullName>Tiempos de traslado por gira</fullName>
            </value>
            <value>
                <fullName>Capacitacion equipo promocional (TA/EXTERNO)</fullName>
            </value>
            <value>
                <fullName>Relevamiento de datos / Actividad de Fichero</fullName>
            </value>
            <value>
                <fullName>Tareas comerciales</fullName>
            </value>
            <value>
                <fullName>Reunion por temas de acceso/BC</fullName>
            </value>
            <value>
                <fullName>Reunion de seguimiento con la TA</fullName>
            </value>
            <value>
                <fullName>Reunion con KAE/KAM</fullName>
            </value>
            <value>
                <fullName>Convención</fullName>
            </value>
            <value>
                <fullName>Capacitaciones</fullName>
            </value>
            <value>
                <fullName>Congresos</fullName>
            </value>
            <value>
                <fullName>Lanzamientos</fullName>
            </value>
            <value>
                <fullName>Reunion con Auditores</fullName>
            </value>
            <value>
                <fullName>Averiguacion licitaciones</fullName>
            </value>
            <value>
                <fullName>Reunion de ciclo</fullName>
            </value>
            <value>
                <fullName>Workshops de las diferentres TAs (Webinar, ateneos)</fullName>
            </value>
            <value>
                <fullName>Towhall</fullName>
            </value>
            <value>
                <fullName>Cumpleaños</fullName>
            </value>
            <value>
                <fullName>Reunión con HCPS</fullName>
            </value>
            <value>
                <fullName>Convecion</fullName>
                <isActive>false</isActive>
                <label>Convecion</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/recordTypes/Licencia.recordType-meta.xml
<RecordType>
    <fullName>Licencia</fullName>
    <active>true</active>
    <description>Tipo de registro para las licencias de tipo Vacaciones, Enfermedad, Día de estudio, Festivo y Maternidad</description>
    <label>Licencia</label>
</RecordType>

force-app/main/default/classes/BatchCountLicencias.cls
public with sharing class BatchCountLicencias implements Database.Batchable<sObject>, Database.Stateful {

     // Atributo para mantener el estado del mapa entre los lotes
    private Map<Id, List<Dan360_Licencia__c>> licenciasPorEfectividadStateful = new Map<Id, List<Dan360_Licencia__c>>();

    public Database.QueryLocator start(Database.BatchableContext bc) {
        Id recordTypeLicencia = Schema.SObjectType.Dan360_Licencia__c.getRecordTypeInfosByDeveloperName().get('Licencia').getRecordTypeId();
        Date fechaActual = System.today();        
        Date fechaInicio = fechaActual.addMonths(-1).toStartOfMonth();
        
        return Database.getQueryLocator([
            SELECT Id, Name, Fecha_de_inicio__c, Fecha_de_Fin__c, Efectividad__c, Motivo__c, Estado__c
            FROM Dan360_Licencia__c
            WHERE Estado__c = 'Aprobada'
            AND Fecha_de_inicio__c >= :fechaInicio
            AND Fecha_de_inicio__c <= :fechaActual
            AND RecordTypeId = :recordTypeLicencia
            order by Efectividad__c ASC
        ]);
    }

    public void execute(Database.BatchableContext BC, list<Dan360_Licencia__c> licencias) {
        System.debug('****licencias: ' + licencias);
        //Map<Id, List<Dan360_Licencia__c>> licenciasPorEfectividad = New Map<Id, List<Dan360_Licencia__c>>();

        for (Dan360_Licencia__c licencia : licencias) {
            List<Dan360_Licencia__c> listLicencias;
            listLicencias = licenciasPorEfectividadStateful.containsKey(licencia.Efectividad__c) ? licenciasPorEfectividadStateful.get(licencia.Efectividad__c) : New List<Dan360_Licencia__c>();
            if (licencia.Estado__c == 'Aprobada') {
                listLicencias.add(licencia);
                licenciasPorEfectividadStateful.put(licencia.Efectividad__c, listLicencias);
            }
        }

        
    }

    public void finish (Database.BatchableContext BC) {
        List<Dan360_Efectividad__c> efectividadesToUpdate = [
            SELECT Id, Name, Dias_de_Licencia_Transcurridos__c, VisMed_Dias_de_Licencia_Unicos__c
            FROM Dan360_Efectividad__c
            WHERE Id IN :licenciasPorEfectividadStateful.keySet()
        ];

        for (Dan360_Efectividad__c efectividad : efectividadesToUpdate) {
            //Cuenta solo las licencias que NO sean Festivos.
            Map<Date, Dan360_Licencia__c> diasPorLicenciaNoFestivo = new Map<Date, Dan360_Licencia__c>();
            //Cuenta solo las licencias que sean Festivos.
            Map<Date, Dan360_Licencia__c> diasPorLicenciaFestivos = new Map<Date, Dan360_Licencia__c>();
            //Cuenta todas las licencias.
            Map<Date, Dan360_Licencia__c> diasPorLicenciaUnicos = new Map<Date, Dan360_Licencia__c>();

            for (Dan360_Licencia__c licencia : licenciasPorEfectividadStateful.get(efectividad.Id)) {
                Integer daysBetweenNew;
                if (licencia.Fecha_de_Fin__c > System.today()) {
                    daysBetweenNew = licencia.Fecha_de_inicio__c.daysBetween(System.today());
                } else {
                    daysBetweenNew = licencia.Fecha_de_inicio__c.daysBetween(licencia.Fecha_de_Fin__c);
                }

                Date auxFechaNew = licencia.Fecha_de_inicio__c;
                for (Integer i = 0; i <= daysBetweenNew; i++) {
                    Datetime dt = (Datetime) auxFechaNew;
                    //Salesforce me toma la zona horaria defasada por 3 horas, asi que los dias se defasaban.
                    String dayOfWeek = dt.format('EEEE', 'Europe/Jersey');

                    if (dayOfWeek != 'Saturday' && dayOfWeek != 'Sunday') {
                        if (licencia.Motivo__c != 'Festivo') {
                            diasPorLicenciaNoFestivo.put(auxFechaNew, licencia);
                        } else {
                            diasPorLicenciaFestivos.put(auxFechaNew, licencia);
                        }
                        diasPorLicenciaUnicos.put(auxFechaNew, licencia);
                    }
                    auxFechaNew = auxFechaNew.addDays(1);
                }
            }

            efectividad.Dias_de_Licencia_Transcurridos__c = diasPorLicenciaNoFestivo.keySet().size();
            efectividad.Dias_feriados_Transcurridos__c = diasPorLicenciaFestivos.keySet().size();
            efectividad.VisMed_Dias_de_Licencia_Unicos__c = diasPorLicenciaUnicos.keySet().size();
        }

        update efectividadesToUpdate;
    }
}