force-app/main/default/objects/Dan360_Efectividad__c/Dan360_Efectividad__c.object-meta.xml
<CustomObject>
    <description>Objeto creado para el registro y calculo de las efectividades del APM por mes.</description>
    <label>Efectividad</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Efectividad Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Efectividades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Dias_de_campo_efectivo__c.field-meta.xml
<CustomField>
    <fullName>Dias_de_campo_efectivo__c</fullName>
    <description>Cantidad de dias habiles en los que el APM trabaja (se descuentan las licencias). Se vuelven a sumar los feriados para que no reste dos veces esa cantidad (los dias habiles transcurridos ya las descuenta)</description>
    <formula>IF( TODAY() &lt; Fecha_de_Fin__c,
CASE(MOD( Fecha_de_inicio__c - DATE(1985,6,24),7),
0 , CASE( MOD( TODAY() - Fecha_de_inicio__c ,7),1,2,2,3,3,4,4,5,5,5,6,5,1),
1 , CASE( MOD( TODAY() - Fecha_de_inicio__c ,7),1,2,2,3,3,4,4,4,5,4,6,5,1),
2 , CASE( MOD( TODAY() - Fecha_de_inicio__c ,7),1,2,2,3,3,3,4,3,5,4,6,5,1),
3 , CASE( MOD( TODAY() - Fecha_de_inicio__c ,7),1,2,2,2,3,2,4,3,5,4,6,5,1),
4 , CASE( MOD( TODAY() - Fecha_de_inicio__c ,7),1,1,2,1,3,2,4,3,5,4,6,5,1),
5 , CASE( MOD( TODAY() - Fecha_de_inicio__c ,7),1,0,2,1,3,2,4,3,5,4,6,5,0),
6 , CASE( MOD( TODAY() - Fecha_de_inicio__c ,7),1,1,2,2,3,3,4,4,5,5,6,5,0),
999)
+
(FLOOR(( TODAY() - Fecha_de_inicio__c )/7)*5)
-
Tiempo_no_promocional__c
-
VisMed_Dias_de_Licencia_Unicos__c,
CASE(MOD( Fecha_de_inicio__c - DATE(1985,6,24),7),
0 , CASE( MOD( Fecha_de_Fin__c - Fecha_de_inicio__c ,7),1,2,2,3,3,4,4,5,5,5,6,5,1),
1 , CASE( MOD( Fecha_de_Fin__c - Fecha_de_inicio__c ,7),1,2,2,3,3,4,4,4,5,4,6,5,1),
2 , CASE( MOD( Fecha_de_Fin__c - Fecha_de_inicio__c ,7),1,2,2,3,3,3,4,3,5,4,6,5,1),
3 , CASE( MOD( Fecha_de_Fin__c - Fecha_de_inicio__c ,7),1,2,2,2,3,2,4,3,5,4,6,5,1),
4 , CASE( MOD( Fecha_de_Fin__c - Fecha_de_inicio__c ,7),1,1,2,1,3,2,4,3,5,4,6,5,1),
5 , CASE( MOD( Fecha_de_Fin__c - Fecha_de_inicio__c ,7),1,0,2,1,3,2,4,3,5,4,6,5,0),
6 , CASE( MOD( Fecha_de_Fin__c - Fecha_de_inicio__c ,7),1,1,2,2,3,3,4,4,5,5,6,5,0),
999)
+
(FLOOR(( Fecha_de_Fin__c - Fecha_de_inicio__c )/7)*5)
-
Tiempo_no_promocional__c
-
VisMed_Dias_de_Licencia_Unicos__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Días de campo efectivo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Dias_feriados__c.field-meta.xml
<CustomField>
    <fullName>Dias_feriados__c</fullName>
    <label>Días feriados</label>
    <summarizedField>Dan360_Licencia__c.Cantidad_de_Dias__c</summarizedField>
    <summaryFilterItems>
        <field>Dan360_Licencia__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Licencia</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Dan360_Licencia__c.Estado__c</field>
        <operation>equals</operation>
        <value>Aprobada</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Dan360_Licencia__c.Motivo__c</field>
        <operation>equals</operation>
        <value>Festivo</value>
    </summaryFilterItems>
    <summaryForeignKey>Dan360_Licencia__c.Efectividad__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Dias_habiles_del_ciclo__c.field-meta.xml
<CustomField>
    <fullName>Dias_habiles_del_ciclo__c</fullName>
    <formula>Dias_Totales_del_Ciclo__c 
-
Dias_feriados_Transcurridos__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Días habiles del ciclo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Dias_habiles_transcurridos__c.field-meta.xml
<CustomField>
    <fullName>Dias_habiles_transcurridos__c</fullName>
    <description>Cantidad de dias habiles trancurridos hasta la fecha de hoy.</description>
    <formula>IF(TODAY() &lt; Fecha_de_inicio__c, 0, 
    IF(TODAY() &gt; Fecha_de_Fin__c,
       Dias_habiles_del_ciclo__c,
							CASE(MOD( Fecha_de_inicio__c - DATE(1985,6,24),7),
            0 , CASE( MOD( TODAY() - Fecha_de_inicio__c ,7),1,2,2,3,3,4,4,5,5,5,6,5,1),
            1 , CASE( MOD( TODAY() - Fecha_de_inicio__c ,7),1,2,2,3,3,4,4,4,5,4,6,5,1),
            2 , CASE( MOD( TODAY() - Fecha_de_inicio__c ,7),1,2,2,3,3,3,4,3,5,4,6,5,1),
            3 , CASE( MOD( TODAY() - Fecha_de_inicio__c ,7),1,2,2,2,3,2,4,3,5,4,6,5,1),
            4 , CASE( MOD( TODAY() - Fecha_de_inicio__c ,7),1,1,2,1,3,2,4,3,5,4,6,5,1),
            5 , CASE( MOD( TODAY() - Fecha_de_inicio__c ,7),1,0,2,1,3,2,4,3,5,4,6,5,0),
            6 , CASE( MOD( TODAY() - Fecha_de_inicio__c ,7),1,1,2,2,3,3,4,4,5,5,6,5,0),
            999)
        +
        (FLOOR(( TODAY() - Fecha_de_inicio__c )/7)*5)
						 	-
							 Dias_feriados_Transcurridos__c
				    )
			)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Días hábiles transcurridos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Tiempo_no_promocional__c.field-meta.xml
<CustomField>
    <fullName>Tiempo_no_promocional__c</fullName>
    <label>Tiempo no promocional (días)</label>
    <summarizedField>Dan360_Licencia__c.Cantidad_de_Horas_Valor__c</summarizedField>
    <summaryFilterItems>
        <field>Dan360_Licencia__c.Estado__c</field>
        <operation>equals</operation>
        <value>Aprobada</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Dan360_Licencia__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Tiempo no Promocional</value>
    </summaryFilterItems>
    <summaryForeignKey>Dan360_Licencia__c.Efectividad__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/VisMed_APM__c.field-meta.xml
<CustomField>
    <fullName>VisMed_APM__c</fullName>
    <label>APM</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Efectividades</relationshipLabel>
    <relationshipName>Efectividades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/VisMed_Ciclo__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Ciclo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciclo</label>
    <referenceTo>VisMed_Ciclo__c</referenceTo>
    <relationshipLabel>Efectividades</relationshipLabel>
    <relationshipName>Efectividades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/VisMed_Cmpt_Tiempo_no_promocional__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Cmpt_Tiempo_no_promocional__c</fullName>
    <formula>VisMed_Ciclo__r.VisMed_Cmpt_Tiempo_no_promocional__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Compensatorio Tiempo no Promocional</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/VisMed_Efectividad__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Efectividad__c</fullName>
    <label>Efectividad</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/VisMed_Target_Diario__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Target_Diario__c</fullName>
    <label>Target Diario</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/VisMed_Visitas_realizadas__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Visitas_realizadas__c</fullName>
    <label>Visitas realizadas</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/VisMed_Visitas_restantes__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Visitas_restantes__c</fullName>
    <label>Visitas restantes</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/Dan360_Licencia__c.object-meta.xml
<CustomObject>
    <description>Objeto para registrar las licencias y dias no promocionables del APM</description>
    <label>Licencia</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Licencia Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Licencia__c/fields/Efectividad__c.field-meta.xml
<CustomField>
    <fullName>Efectividad__c</fullName>
    <label>Efectividad</label>
    <referenceTo>Dan360_Efectividad__c</referenceTo>
    <relationshipLabel>Licencias</relationshipLabel>
    <relationshipName>Licencias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <description>Fecha de finalizacion del la licencia/tiempo no promocional</description>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <description>Fecha de inicio desde que se tomo la licencia/tiempo no promocional</description>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/fields/VisMed_APM__c.field-meta.xml
<CustomField>
    <fullName>VisMed_APM__c</fullName>
    <label>APM</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licencias</relationshipLabel>
    <relationshipName>Licencias</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/recordTypes/Licencia.recordType-meta.xml
<RecordType>
    <fullName>Licencia</fullName>
    <active>true</active>
    <description>Tipo de registro para las licencias de tipo Vacaciones, Enfermedad, Día de estudio, Festivo y Maternidad</description>
    <label>Licencia</label>
</RecordType>

force-app/main/default/objects/User/fields/VisMed_Es_un_Visitador_Medico__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Es_un_Visitador_Medico__c</fullName>
    <defaultValue>false</defaultValue>
    <description>field booleano para indicar si el usuario pertenece a la familia de visitadores y saber si debe contar en las querys.</description>
    <label>Es un Visitador Medico</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VisMed_Ciclo__c/VisMed_Ciclo__c.object-meta.xml
<CustomObject>
    <label>Ciclo</label>
    <nameField>
        <label>Ciclo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Ciclo__c/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_Ciclo__c/fields/VisMed_Cmpt_Tiempo_no_promocional__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Cmpt_Tiempo_no_promocional__c</fullName>
    <defaultValue>$CustomMetadata.Compensatorio_Tiempo_no_Promocional__mdt.Compensatorio_General.Compensatorio__c</defaultValue>
    <label>Compensatorio Tiempo no Promocional</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Feriado__c/VisMed_Feriado__c.object-meta.xml
<CustomObject>
    <description>Objeto para registrar los feriados de tipo nacional.</description>
    <label>Feriado</label>
    <nameField>
        <label>Feriado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feriados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Feriado__c/fields/VisMed_Fecha__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Fecha__c</fullName>
    <label>Fecha</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchFeriados.cls
public class BatchFeriados implements Database.Batchable<sObject>{
   
    public Database.QueryLocator start (Database.BatchableContext bc) {
        Date fechaAuctual = System.today();
        return Database.getQueryLocator([SELECT Id, Name, VisMed_Fecha__C FROM VisMed_Feriado__c WHERE VisMed_Fecha__c = :fechaAuctual]);
    }

    public void execute (Database.BatchableContext BC, list<VisMed_Feriado__c> feriados) {
        Date fechaAuctual = System.today();
        List<User> apms = [
            SELECT Id, Name, ContactId, Contact.Name, IsActive, IsPortalEnabled
            FROM User
            WHERE IsActive = true 
            AND IsPortalEnabled = true
            AND ContactId != null
            AND VisMed_Es_un_Visitador_Medico__c = true
        ];  
        
        List<Id> contactoDeLosAPMs = new List<Id>();
        for (User usuario : apms) {
            contactoDeLosAPMs.add(usuario.ContactId);
        }
        List<Dan360_Efectividad__c> efectividades = [SELECT Id, Name, Tiempo_no_promocional__c, Dias_feriados__c, Fecha_de_inicio__c, Fecha_de_Fin__c, Dias_de_campo_efectivo__c, 
                                                            Dias_habiles_transcurridos__c, VisMed_Visitas_restantes__c, VisMed_APM__c, VisMed_Target_Diario__c, 
                                                            Dias_habiles_del_ciclo__c, VisMed_Visitas_realizadas__c, VisMed_Ciclo__c, VisMed_Efectividad__c, VisMed_Cmpt_Tiempo_no_promocional__c
                                                     FROM Dan360_Efectividad__c
                                                     WHERE VisMed_APM__c IN :contactoDeLosAPMs AND Fecha_de_inicio__c <= :fechaAuctual AND Fecha_de_Fin__c >= :fechaAuctual];
        //Map<Id, Map<Dan360_Efectividad__c, List<Dan360_Licencia__c>>> licenciasPorEfectividadesPorAPM = New Map<Id, Map<Dan360_Efectividad__c, List<Dan360_Licencia__c>>>();
        List<Dan360_Licencia__c> newLicencias = New List<Dan360_Licencia__c>();
        for (User apm : apms) {
            for (Dan360_Efectividad__c efectividad : efectividades){
                for (VisMed_Feriado__c feriado : feriados) {
                    if (apm.ContactId == efectividad.VisMed_APM__c && (feriado.VisMed_Fecha__c >= efectividad.Fecha_de_inicio__c && feriado.VisMed_Fecha__c <= efectividad.Fecha_de_Fin__c)) {
                        Dan360_Licencia__c newLicencia = New Dan360_Licencia__c(
                        RecordTypeId = Schema.SObjectType.Dan360_Licencia__c.getRecordTypeInfosByDeveloperName().get('Licencia').getRecordTypeId(),
                        Motivo__c = 'Festivo',
                        VisMed_APM__c = apm.ContactId,
                        Efectividad__c = efectividad.Id,
                        Estado__c = 'Aprobada',
                        Fecha_de_inicio__c = feriado.VisMed_Fecha__c,
                        Fecha_de_Fin__c = feriado.VisMed_Fecha__c,
                        Comentarios__c = feriado.Name
                    );
                    newLicencias.add(newLicencia);
                    }
                }
            }
        }
        insert newLicencias;
    }

    public void finish (Database.BatchableContext BC) {
        // execute any post-processing operations
    }

}