force-app/main/default/objects/Formulario__c/Formulario__c.object-meta.xml
<CustomObject>
    <label>Historia Clínica</label>
    <nameField>
        <label>Nombre de Formulario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historias Clínicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Formulario__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Formularios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Nombre_y_Apellido_del_Paciente__c.field-meta.xml
<CustomField>
    <fullName>Nombre_y_Apellido_del_Paciente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>No debe completarse</inlineHelpText>
    <label>Nombre y apellido del paciente</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Best Care</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Regular</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Historias Clínicas</relationshipLabel>
    <relationshipName>Formularios3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HistoriaClinicaHelper.cls
public class HistoriaClinicaHelper {
    
    public static void makeAttachedPdf(Id recordId){
        Pagereference reportPage = Page.HistoriaClinica;
        reportPage.getParameters().put('id', recordId);
        
        
        List<Formulario__c> historiaClinica = [
            SELECT Id,Name
            FROM Formulario__c
            WHERE Id =:recordId
        ];
        
        Blob reportPdf;
        if(!Test.isRunningTest()){
            reportPdf = reportPage.getContentAsPDF();
        }
        else{
            reportPdf = Blob.valueOf('Test');
        }
        
        ContentVersion cv = new ContentVersion();
        cv.VersionData = reportPdf;
        cv.Title = historiaClinica.get(0).Name;
        cv.PathOnClient = historiaClinica.get(0).Name+'.pdf';
        
        insert cv;
        
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [
            SELECT ContentDocumentId 
            FROM ContentVersion 
            WHERE Id =: cv.Id
        ].ContentDocumentId;
        cdl.LinkedEntityId = recordId;
        // ShareType is either 'V', 'C', or 'I'
        // V = Viewer, C = Collaborator, I = Inferred
        cdl.ShareType = 'V';
        
        insert cdl;
    }
    
    public static void linkPdfHistoriaClinicaToAccountAndCase(Id recordId){
        
        List<ContentDocumentLink> links = [
            SELECT ID,ContentDocumentId
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :recordId
            
        ];
        
        if(!links.isEmpty()){
            
            Formulario__c historiaClinica = [
                SELECT ID,Nombre_y_Apellido_del_Paciente__c,Caso__c
                FROM Formulario__c
                WHERE Id = : recordId
                LIMIT 1
            ];
            
            List<Case> relatedCase = [
                select id 
                from case 
                where id = :historiaClinica.Caso__c
            ];
            
            
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = links[0].ContentDocumentId;
            cdl.LinkedEntityId = historiaClinica.Nombre_y_Apellido_del_Paciente__c;
            // ShareType is either 'V', 'C', or 'I'
            // V = Viewer, C = Collaborator, I = Inferred
            cdl.ShareType = 'V';
            insert cdl;
            
            if(!relatedCase.isEmpty()){
                ContentDocumentLink cdlCase = new ContentDocumentLink();
                cdlCase.ContentDocumentId = links[0].ContentDocumentId;
                cdlCase.LinkedEntityId = relatedCase.get(0).id;
                cdlCase.ShareType = 'V';
                
                insert cdlCase;
            }
           
            
        }
    }
    
    public static Boolean noTienePdfHistoriaClinica(Id recordId,String title){
        system.debug(recordId);
        system.debug('title: '+title);
        String query = 'SELECT ID '+
            'FROM ContentDocumentLink '+
            'WHERE LinkedEntityId = :recordId';
        if(String.isNotBlank(title)){
            query +=' AND ContentDocument.Title = :title';
        }
        List<ContentDocumentLink> links = database.query(query);
        if(links.isEmpty()){
            return true;
        }
        return false;
    }
}