force-app/main/default/objects/Formulario__c/Formulario__c.object-meta.xml
<CustomObject>
    <label>Historia Clínica</label>
    <nameField>
        <label>Nombre de Formulario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historias Clínicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Formulario__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Formularios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FormularioCustomField__mdt/FormularioCustomField__mdt.object-meta.xml
<CustomObject>
    <label>FormularioCustomField</label>
    <pluralLabel>FormularioCustomField</pluralLabel>
</CustomObject>

force-app/main/default/objects/FormularioCustomField__mdt/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FormularioCustomField__mdt/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FormularioCustomField__mdt/fields/ObjectId__c.field-meta.xml
<CustomField>
    <fullName>ObjectId__c</fullName>
    <label>ObjectId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateFormFromCaseController.cls
public class CreateFormFromCaseController  {
	
	public String caseId;
	public CreateFormFromCaseController(ApexPages.StandardController controller) {	
		caseId = controller.getId();
	}

	public PageReference redirectToCreateForm() {
		Case[] caseList = [
			SELECT AccountId, Account.Name,
				CaseNumber 
			FROM Case 
			WHERE Id = :caseId 
		];  		
		if(caseList.isEmpty()) return null;		

		FormularioCustomField__mdt mdt = [ 
			SELECT  Cuenta__c, Caso__c, ObjectId__c 
			FROM FormularioCustomField__mdt
			WHERE MasterLabel = 'Formulario'
		]; 
		Schema.DescribeSObjectResult describeSObject = Formulario__c.SObjectType.getDescribe();		

		PageReference pageRef = new PageReference(
			'/setup/ui/recordtypeselect.jsp?ent='+mdt.ObjectId__c+'&retURL=%2F'+caseId+'&'+
			'save_new_url=%2F'+describeSObject.getKeyPrefix()+'%2Fe%3F'+mdt.Caso__c+'%3D'+
			caseList[0].CaseNumber+'%26'+mdt.Caso__c+'_lkid%3D'+caseId+'%26retURL%3D%252F'+caseId+'&'+
			mdt.Cuenta__c+'='+caseList[0].Account.Name+'&'+mdt.Cuenta__c+'_lkid='+caseList[0].AccountId
		);
			
		return pageRef;
	}
}