force-app/main/default/objects/Formulario__c/Formulario__c.object-meta.xml
<CustomObject>
    <label>Historia Clínica</label>
    <nameField>
        <label>Nombre de Formulario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historias Clínicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Formulario__c/fields/Complicacion_actual__c.field-meta.xml
<CustomField>
    <fullName>Complicacion_actual__c</fullName>
    <label>Complicaciones del acceso</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ninguna</fullName>
            </value>
            <value>
                <fullName>Desplazamiento / salida accidental</fullName>
            </value>
            <value>
                <fullName>Fuga periostoma</fullName>
            </value>
            <value>
                <fullName>Incorrecta localización en tubo digestivo</fullName>
            </value>
            <value>
                <fullName>Incorrecta localización en pulmón</fullName>
            </value>
            <value>
                <fullName>Infección periostoma</fullName>
            </value>
            <value>
                <fullName>Lesión periostoma</fullName>
            </value>
            <value>
                <fullName>Lesión por decúbito</fullName>
            </value>
            <value>
                <fullName>Obstruccion</fullName>
                <label>Obstrucción</label>
            </value>
            <value>
                <fullName>Perdida periostoma</fullName>
                <label>Pérdida periostoma</label>
            </value>
            <value>
                <fullName>Ruptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Complicaciones_metabolicas__c.field-meta.xml
<CustomField>
    <fullName>Complicaciones_metabolicas__c</fullName>
    <label>Complicaciones metabólicas</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ninguna</fullName>
            </value>
            <value>
                <fullName>Hipertrigliceridemia</fullName>
            </value>
            <value>
                <fullName>Hiperglucemia</fullName>
            </value>
            <value>
                <fullName>Hipofosfatemia</fullName>
            </value>
            <value>
                <fullName>Hiperfosfatemia</fullName>
            </value>
            <value>
                <fullName>Hipermagnesemia</fullName>
            </value>
            <value>
                <fullName>Hipomagnesemia</fullName>
            </value>
            <value>
                <fullName>Hipocalcemia</fullName>
            </value>
            <value>
                <fullName>Hipercalcemia</fullName>
            </value>
            <value>
                <fullName>Hipokalemia</fullName>
            </value>
            <value>
                <fullName>Hiperkalemia</fullName>
            </value>
            <value>
                <fullName>Hiponatremia</fullName>
            </value>
            <value>
                <fullName>Hipernatremia</fullName>
            </value>
            <value>
                <fullName>Hipercolesterolemia</fullName>
            </value>
            <value>
                <fullName>Hipoglucemia</fullName>
            </value>
            <value>
                <fullName>Hipercloremia</fullName>
            </value>
            <value>
                <fullName>Hipocloremia</fullName>
            </value>
            <value>
                <fullName>Hipercalemia</fullName>
                <isActive>false</isActive>
                <label>Hipercalemia</label>
            </value>
            <value>
                <fullName>Hiperfofatemia</fullName>
                <isActive>false</isActive>
                <label>Hiperfofatemia</label>
            </value>
            <value>
                <fullName>Hipertriglicerimia</fullName>
                <isActive>false</isActive>
                <label>Hipertriglicerimia</label>
            </value>
            <value>
                <fullName>Hipocalemia</fullName>
                <isActive>false</isActive>
                <label>Hipocalemia</label>
            </value>
            <value>
                <fullName>Hipofofotemia</fullName>
                <isActive>false</isActive>
                <label>Hipofofotemia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Fecha_de_la_visita__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_la_visita__c</fullName>
    <label>Fecha de la visita</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Fecha_ultimo_recambio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_ultimo_recambio__c</fullName>
    <label>Fecha último recambio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Modalidad__c.field-meta.xml
<CustomField>
    <fullName>Modalidad__c</fullName>
    <label>Modalidad</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dieta oral</fullName>
            </value>
            <value>
                <fullName>Suplementos orales</fullName>
            </value>
            <value>
                <fullName>Nutrición enteral</fullName>
            </value>
            <value>
                <fullName>Transición de enteral a oral</fullName>
            </value>
            <value>
                <fullName>Transición de oral a enteral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Nombre_y_Apellido_del_Paciente__c.field-meta.xml
<CustomField>
    <fullName>Nombre_y_Apellido_del_Paciente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>No debe completarse</inlineHelpText>
    <label>Nombre y apellido del paciente</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Best Care</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Regular</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Historias Clínicas</relationshipLabel>
    <relationshipName>Formularios3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Requerimiento_Proteico__c.field-meta.xml
<CustomField>
    <fullName>Requerimiento_Proteico__c</fullName>
    <label>Requerimiento proteico (g/día)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Femenino</fullName>
            </value>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Otro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Sistema_digestivo__c.field-meta.xml
<CustomField>
    <fullName>Sistema_digestivo__c</fullName>
    <label>Complicaciones sistema digestivo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ninguna</fullName>
            </value>
            <value>
                <fullName>Broncoaspiración</fullName>
            </value>
            <value>
                <fullName>Constipación</fullName>
            </value>
            <value>
                <fullName>Dolor abdominal</fullName>
            </value>
            <value>
                <fullName>Diarrea</fullName>
            </value>
            <value>
                <fullName>Distensión</fullName>
            </value>
            <value>
                <fullName>Metabólicas</fullName>
            </value>
            <value>
                <fullName>Meteorismo</fullName>
            </value>
            <value>
                <fullName>Náuseas / vómitos</fullName>
                <label>Náuseas</label>
            </value>
            <value>
                <fullName>Regurgitación</fullName>
            </value>
            <value>
                <fullName>vómitos</fullName>
                <label>Vómitos</label>
            </value>
            <value>
                <fullName>Otras</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Via_de_acceso__c.field-meta.xml
<CustomField>
    <fullName>Via_de_acceso__c</fullName>
    <label>Tipo de acceso</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sonda nasogástrica</fullName>
            </value>
            <value>
                <fullName>Sonda nasoduodenal</fullName>
            </value>
            <value>
                <fullName>Sonda nasoyeyunal</fullName>
            </value>
            <value>
                <fullName>Gastroyeyunostomia</fullName>
                <label>Gastro-yeyunostomía</label>
            </value>
            <value>
                <fullName>Gastrostomía</fullName>
            </value>
            <value>
                <fullName>Yeyunostomía</fullName>
            </value>
            <value>
                <fullName>Botón gástrico</fullName>
            </value>
            <value>
                <fullName>Vía oral</fullName>
                <default>true</default>
                <label>Vía oral</label>
            </value>
            <value>
                <fullName>Esofagostomía</fullName>
                <isActive>false</isActive>
                <label>Esofagostomía</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HCReportTest.cls
@isTest
public with sharing class HCReportTest {
    
    @isTest
    public static void testHCReportPageController(){
        
        Formulario__c historiaClinica = [
            SELECT id,Nombre_y_Apellido_del_Paciente__c
            FROM Formulario__c
        ];
        
        PageReference page = Page.HCReportPage;
        Test.setCurrentPage(page);
        Apexpages.currentPage().getParameters().put('hcid',historiaClinica.id);
        HCReportPageController controller = new HCReportPageController();
        
        Test.startTest();
        Test.stopTest();
        
        System.assertEquals(120, controller.historiaClinica.Requerimiento_Proteico__c);
        System.assertEquals('Hipofosfatemia', controller.historiaClinica.Complicaciones_metabolicas__c);
    }
    
    
    @isTest
    public static void testHCReportPageForPDF(){
        
        Formulario__c historiaClinica = [
            SELECT id,Nombre_y_Apellido_del_Paciente__c
            FROM Formulario__c
        ];
        
        PageReference page = Page.HCReportPageForPDF;
        Test.setCurrentPage(page);
        Apexpages.currentPage().getParameters().put('hcid',historiaClinica.id);
        HCReportPageForPDFController controller = new HCReportPageForPDFController();
        
        Test.startTest();
        controller.armaryAdjuntarPdf();
        Test.stopTest();
        
        ContentVersion contentVersion= [
            SELECT id,title,ContentDocumentId,contentSize,Description
            FROM ContentVersion 
            LIMIT 1
        ];
        Map<integer,String>  monthNameMap = new Map<integer, String> {
            1=>'Enero', 2=>'Febrero', 3=>'Marzo', 4=>'Abril', 5=>'Mayo', 6=>'Junio',
                7=>'Julio', 8=>'Agosto', 9=>'Septiembre',10=>'Octubre', 11=>'Noviembre', 12=>'Diciembre'
                };
                    System.assertEquals('Test Nut - Historia Clínica de Enfermería - '+monthNameMap.get(System.now().month())+' 2022', contentVersion.title);
    }
    
    
    @testSetup 
    static void setup() {
        Account testAcc1 = Build.anAccount().withLastName('Test Nut')
            .withDNI('1234567')
            .withRecordTypeId(XappiaHelper.getRecordType('Account', 'Paciente Best Care').Id)
            .withCanalParaConsumidorBaby('Farmacias')
            .build();
        
        insert testAcc1;
        
        Formulario__c historiaClinica = Build.anHistoriaClinicaDeEnfermeria().withName('Nombre de formulario')
            .withPaciente(testAcc1)
            .build();
        historiaClinica.Requerimiento_Proteico__c=120;
        historiaClinica.Complicaciones_metabolicas__c='Hipofosfatemia';
        historiaClinica.Sistema_digestivo__c='Constipación; Distensión';
        historiaClinica.Modalidad__c='Nutrición enteral';
        historiaClinica.Via_de_acceso__c='Gastrostomía';
        historiaClinica.Complicacion_actual__c='Lesión por decúbito';
        historiaClinica.Fecha_ultimo_recambio__c = System.today();
        historiaClinica.Fecha__c=System.today();
        historiaClinica.Fecha_de_la_visita__c = System.today();
        historiaClinica.Sexo__c= 'Masculino';
        
        insert historiaClinica; 
    }
}