force-app/main/default/objects/Formulario__c/Formulario__c.object-meta.xml
<CustomObject>
    <label>Historia Clínica</label>
    <nameField>
        <label>Nombre de Formulario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historias Clínicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Formulario__c/fields/Fecha_de_la_visita__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_la_visita__c</fullName>
    <label>Fecha de la visita</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Nombre_y_Apellido_del_Paciente__c.field-meta.xml
<CustomField>
    <fullName>Nombre_y_Apellido_del_Paciente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>No debe completarse</inlineHelpText>
    <label>Nombre y apellido del paciente</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Best Care</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Regular</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Historias Clínicas</relationshipLabel>
    <relationshipName>Formularios3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CommunityPrintPDFControllerTest.cls
@isTest
private class CommunityPrintPDFControllerTest {
	@isTest
    static void whenThe(){

        Account paciente = Build.anAccountCuentacommunity()
            .withFirstName('Nombre')
            .withLastName('Apellido')
            .withEmail('nombreapellido@testdanone.com')
            .withTelefono('12345678')
            .build();
        paciente.RecordTypeId = XappiaHelper.getRecordType('Account', 'Paciente Regular').Id;
        insert paciente;

		Formulario__c form = new Formulario__c();
        form.Nombre_y_Apellido_del_Paciente__c = paciente.Id;
        form.Fecha_de_la_visita__c = System.today();
        insert form;
        
        Formulario__c formulario = [
            SELECT Id, Name
            FROM Formulario__c
            LIMIT 1
        ];
        
        Test.startTest();
        CommunityPrintPDFController.WrapperPDF infoPDF = CommunityPrintPDFController.getPDFInfo(formulario.Id);
        Test.stopTest();

        System.assertEquals('Los métodos definidos como TestMethod no admiten llamadas a getContent', infoPDF.pdfInfoBase64);
        System.assertEquals(formulario.Name, infoPDF.formularioName);
        
    }
}