force-app/main/default/objects/Case/fields/Dan360_OrderedDate__c.field-meta.xml
<CustomField>
    <fullName>Dan360_OrderedDate__c</fullName>
    <label>Ordered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_OrderGetEnd__c.field-meta.xml
<CustomField>
    <fullName>Dan360_OrderGetEnd__c</fullName>
    <label>Order Get End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_OrderGetStart__c.field-meta.xml
<CustomField>
    <fullName>Dan360_OrderGetStart__c</fullName>
    <label>Order Get Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_ReclamoAprobado__c.field-meta.xml
<CustomField>
    <fullName>Dan360_ReclamoAprobado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que se marcara cuando el reclamo sea aprobado por el o los roles correspondientes</description>
    <label>Reclamo Aprobado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Dan360_Devoluciones.recordType-meta.xml
<RecordType>
    <fullName>Dan360_Devoluciones</fullName>
    <active>true</active>
    <businessProcess>Dan360_ReclamosDevolucion</businessProcess>
    <description>Devoluciones de productos relacionado a un pedido procesado.</description>
    <label>Devoluciones</label>
</RecordType>

force-app/main/default/classes/CaseTriggerHelper.cls
public class CaseTriggerHelper {
    public static void updateCaseFields(List<String> aCaseIds){
        List<Case> casesToUpdate = new List<Case>();
        Id devolucionRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Dan360_Devoluciones').getRecordTypeId();
        for(Case caseToUpdate : [SELECT Id,RecordTypeId, Dan360_ReclamoAprobado__c, Dan360_OrderGetStart__c, Status, Dan360_OrderedDate__c, Dan360_OrderGetEnd__c, CreatedDate 
                                    FROM Case 
                                    WHERE Id IN :aCaseIds]){            
            caseToUpdate.Dan360_OrderGetStart__c = Date.today();
            Date createdDateCase = date.newinstance(caseToUpdate.CreatedDate.year(), caseToUpdate.CreatedDate.month(), caseToUpdate.CreatedDate.day());
            caseToUpdate.Dan360_OrderedDate__c = createdDateCase;
            caseToUpdate.Dan360_OrderGetEnd__c = Date.today();
            caseToUpdate.Status = caseToUpdate.RecordTypeId == devolucionRecordTypeId ? 'Autorizado' : 'Cerrado';
            casesToUpdate.add(caseToUpdate);
        }
        if(!casesToUpdate.isEmpty()){
            Database.update(casesToUpdate);
        }
    }
}