force-app/main/default/objects/Case/fields/Dan360_EnviadoSAP__c.field-meta.xml
<CustomField>
    <fullName>Dan360_EnviadoSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviado SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_Factura__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Factura__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Factura relacionada al reclamo generado.</description>
    <label>Factura</label>
    <referenceTo>Dan360_Factura__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_MotivoDeReclamo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_MotivoDeReclamo__c</fullName>
    <description>Especifica el porqué se está realizando la devolución del producto.</description>
    <label>Motivo de reclamo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEVCVEN</fullName>
                <label>Corto vencimiento</label>
            </value>
            <value>
                <fullName>Error facturación impuesto a las ventas</fullName>
            </value>
            <value>
                <fullName>Error ingreso admin pedido</fullName>
            </value>
            <value>
                <fullName>Exento de Impuestos</fullName>
            </value>
            <value>
                <fullName>Faltante producto por abasto</fullName>
                <label>Faltante de producto</label>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>NOSOLIC</fullName>
                <label>No pedido</label>
            </value>
            <value>
                <fullName>No se ingresó motivo para Nota de Crédito</fullName>
            </value>
            <value>
                <fullName>PRODA</fullName>
                <label>Producto Dañado</label>
            </value>
            <value>
                <fullName>Producto Incorrecto</fullName>
            </value>
            <value>
                <fullName>PROVEN</fullName>
                <label>Producto vencido</label>
            </value>
            <value>
                <fullName>Se usó tasa impositiva incorrecta en la factura original</fullName>
            </value>
            <value>
                <fullName>Demora en la entrega</fullName>
            </value>
            <value>
                <fullName>Entrega fuera del horario/día acordado</fullName>
            </value>
            <value>
                <fullName>Malos tratos del chofer</fullName>
            </value>
            <value>
                <fullName>Dan360_PorNoPedido</fullName>
                <isActive>false</isActive>
                <label>Dan360_PorNoPedido</label>
            </value>
            <value>
                <fullName>Dan360_PorProductoDañado</fullName>
                <isActive>false</isActive>
                <label>Dan360_PorProductoDañado</label>
            </value>
            <value>
                <fullName>Dan360_PorProductoVencido</fullName>
                <isActive>false</isActive>
                <label>Dan360_PorProductoVencido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_OrderedDate__c.field-meta.xml
<CustomField>
    <fullName>Dan360_OrderedDate__c</fullName>
    <label>Ordered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_OrderGetEnd__c.field-meta.xml
<CustomField>
    <fullName>Dan360_OrderGetEnd__c</fullName>
    <label>Order Get End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_OrderGetStart__c.field-meta.xml
<CustomField>
    <fullName>Dan360_OrderGetStart__c</fullName>
    <label>Order Get Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Pedido__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Número de pedido por el cual se está generando el reclamo.</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remito relacionado a un pedido.</description>
    <label>Remito</label>
    <referenceTo>Dan360_Remito__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_RequiredDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>Dan360_RequiredDeliveryDate__c</fullName>
    <label>Required Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Reclamo.recordType-meta.xml
<RecordType>
    <fullName>Reclamo</fullName>
    <active>true</active>
    <businessProcess>General</businessProcess>
    <label>Reclamo</label>
</RecordType>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/Dan360_CustomerSalesArea__c.object-meta.xml
<CustomObject>
    <description>Customer Sales Area</description>
    <label>Customer Sales Area</label>
    <nameField>
        <label>Nombre de Customer Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Sales Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Factura__c/Dan360_Factura__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los documentos de cuentas corrientes de los clientes que se relacionan a un pedido.</description>
    <label>Factura</label>
    <nameField>
        <displayFormat>Fact-{0000}</displayFormat>
        <label>Nombre de Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Delivery__c</fullName>
    <formula>Dan360_Remito__r.Dan360_Delivery__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Pedido__c</fullName>
    <description>Pedido al cual se relaciona la factura.</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipName>Facturas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remito al cual está relacionada una factura.</description>
    <label>Remito</label>
    <referenceTo>Dan360_Remito__c</referenceTo>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Remito__c/Dan360_Remito__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los remitos que se relacionan a un pedido</description>
    <label>Remito</label>
    <nameField>
        <displayFormat>Rem{0000}</displayFormat>
        <label>Nombre de Remito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Remito__c/fields/Dan360_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Delivery__c</fullName>
    <externalId>true</externalId>
    <label>Delivery</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Dan360_Remito__c/fields/Dan360_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Pedido__c</fullName>
    <description>Pedido al cual está relacionado el remito.</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Remitos</relationshipLabel>
    <relationshipName>Remitos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Remito__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <label>Remito</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_CustomerSalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CustomerSalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Sales Area relacionado al pedido</description>
    <label>Customer Sales Area</label>
    <referenceTo>Dan360_CustomerSalesArea__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_FechaCierreCarrito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_FechaCierreCarrito__c</fullName>
    <description>Fecha-hora de cierre de carrito</description>
    <label>Fecha Cierre Carrito</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_FechaInicioCarrito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_FechaInicioCarrito__c</fullName>
    <description>Fecha-hora de inicio carrito</description>
    <label>Fecha Inicio Carrito</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Id_Externo__c</fullName>
    <description>Id Externo de la órdenes. Se diligenciará a través de una automatización para replicar el número de la orden de Salesforce.</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_OrderReason__c.field-meta.xml
<CustomField>
    <fullName>Dan360_OrderReason__c</fullName>
    <description>Razón por la cuál se genera un pedido sin cargo.</description>
    <label>Razón del pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AT3</fullName>
                <label>Beneficios Empleados</label>
            </value>
            <value>
                <fullName>AF7</fullName>
                <label>Donaciones</label>
            </value>
            <value>
                <fullName>SMA</fullName>
                <label>Marketing Adultos</label>
            </value>
            <value>
                <fullName>SMC</fullName>
                <label>Marketing Consumer</label>
            </value>
            <value>
                <fullName>SMP</fullName>
                <label>Marketing Pediátrico</label>
            </value>
            <value>
                <fullName>APP</fullName>
                <label>Promoción Farmacias</label>
            </value>
            <value>
                <fullName>APN</fullName>
                <label>Reclamo de Calidad-Arg</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_UnidadNegocio__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadNegocio__c</fullName>
    <description>Se refiere al negocio donde se generará una transacción, en donde impactará la venta de un producto.</description>
    <label>Unidad de negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_UnidadDeNegocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Orden_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_compra__c</fullName>
    <label>Orden de compra</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Status_SAP__c.field-meta.xml
<CustomField>
    <fullName>Status_SAP__c</fullName>
    <label>Status SAP</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Dan360_UnidadDeNegocio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5800</fullName>
        <label>AMN</label>
    </customValue>
    <customValue>
        <fullName>5771</fullName>
        <label>NuBa</label>
    </customValue>
    <description>Determina a qué unidad de negocio se genera un pedido.</description>
    <masterLabel>Unidad de Negocio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/sendOrderToSapController.cls
public with sharing class sendOrderToSapController {
    @AuraEnabled
    public static void sendOrderToSap(string recordId){
        Order orden = [
            SELECT id, Orden_de_compra__c,OrderNumber, Dan360_UnidadNegocio__c, RecordType.Name ,
                EndDate, EffectiveDate, Dan360_FechaInicioCarrito__c, Dan360_FechaCierreCarrito__c,
                AccountId, Description, Status, Dan360_CustomerSalesArea__c,Status_SAP__c, Dan360_OrderReason__c
            FROM Order 
            WHERE Id = :recordId
        ];

        System.debug('orden.Status ---->'+orden.Status);

        if(orden.Status == 'Confirmado'){
            Map<String,Order> orderMap = new Map<String,Order>();
            orderMap.put(orden.Id, orden);
            String typeObj = 'Order';
            BatchSendOrdersToSap orderBatch = new BatchSendOrdersToSap(orderMap, typeObj);
            ID batchId = Database.executeBatch(orderBatch);
        } else {
            throw new applicationException('Error: La Orden no esta Confirmada');
        }
        
    }

    @InvocableMethod(label='Send Order To SAP' description='Send order to sap')
    public static void sendOrderToSapFlow(List<string> recordId){

        // List<String> errorMensaje = new List<String>{'Hola'};
        // String orderId = recordId[0];
        
        // Order orden = [
        //     SELECT id, Orden_de_compra__c,OrderNumber, Dan360_UnidadNegocio__c, RecordType.Name ,
        //         EndDate, EffectiveDate, Dan360_FechaInicioCarrito__c, Dan360_FechaCierreCarrito__c,
        //         AccountId, Description, Status, Dan360_CustomerSalesArea__c,Status_SAP__c, Dan360_OrderReason__c
        //     FROM Order 
        //     WHERE Id = :orderId
        // ];
        
        // Map<String,Order> orderMap = new Map<String,Order>();
        // orderMap.put(orden.Id, orden);
        // List<sendOrdersToSapHelper.OrderSAP> orderToSAP = new sendOrdersToSapHelper().getMapWithProducts(orderMap, 'Order');
        // System.debug(orderToSAP[0].MapOrderBody);
        // String body = JSON.serialize(orderToSAP[0].MapOrderBody);
        // System.debug(body);
        // String typeObj = 'Order';
        // String recordName = orderToSAP[0].recordName;
        // sendOrderToSapFuture(body, typeObj, recordName, orden.Id);
        sendOrderToSapFuture(recordId);
       
    }

    @AuraEnabled
    public static void sendCaseToSap(string recordId){
        System.debug('recordId ---------->'+recordId);
        
        Case reclamo = [
            SELECT Id, CaseNumber, Dan360_MotivoDeReclamo__c, RecordType.Name, Dan360_Pedido__c,Dan360_EnviadoSAP__c, Description, 
            Dan360_RequiredDeliveryDate__c, Dan360_OrderedDate__c, Dan360_OrderGetStart__c,Dan360_OrderGetEnd__c,
            Dan360_Remito__r.Dan360_Delivery__c, Dan360_Factura__r.Dan360_Id_Externo__c,CreatedDate
            FROM Case 
            WHERE iD = :recordId
        ];

        System.debug('reclamo ---------->'+reclamo);

            Map<String,Case> caseMap = new Map<String,Case>();
            caseMap.put(reclamo.Id, reclamo);
            String typeObj = 'Case';

            BatchSendOrdersToSap caseBatch = new BatchSendOrdersToSap(caseMap, typeObj);
            ID batchId = Database.executeBatch(caseBatch);  
    }
	
    @testVisible
    private static void sendEmail (WebServiceSap.SendAlta respuesta){
        System.debug('sendEmail');
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'leonardo.jimenez@globant.com'};
        mail.setToAddresses(toAddresses);
        mail.setSubject('La orden no pudo ser enviada a SAP');
        mail.setPlainTextBody('La orden no se envio a sap, Codigo: ' + respuesta.response.getStatusCode() +', ' + respuesta.response.getStatus());
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }

    public static void updateOrderSAP (Id orderId, String sapStatus){
        Order orden = [
            SELECT id, Status_SAP__c
            FROM Order 
            WHERE Id = :orderId
        ];
        if(sapStatus.length() < 40 ){
            orden.Status_SAP__c = sapStatus;
        }else{
            orden.Status_SAP__c =  sapStatus.substring(0, 39);
        }
        update orden;
    }

    // @future(callout=true)
    // public static void sendOrderToSapFuture(String body, String typeObj, String recordName, Id pedido)
    // {   
    //     WebServiceSap.SendAlta respuesta = WebServiceSap.sendAltaToSap(body, typeObj, recordName);
    //     System.debug('respuesta --->'+respuesta);
    //     System.debug(!(respuesta.response.getStatusCode() == 200));
    //     System.debug(respuesta.response.getStatusCode());
    //     updateOrderSAP(pedido,respuesta.response.getBody());
    //     if(!(respuesta.response.getStatusCode() == 200)){
    //         sendEmail(respuesta);
    //     }
    // }
    @future(callout=true)
    public static void sendOrderToSapFuture(List<string> recordId)
    {   

        List<String> errorMensaje = new List<String>{'Hola'};
        String orderId = recordId[0];
        
        Order orden = [
            SELECT id, Orden_de_compra__c,OrderNumber, Dan360_UnidadNegocio__c, RecordType.Name ,
                EndDate, EffectiveDate, Dan360_FechaInicioCarrito__c, Dan360_FechaCierreCarrito__c,
                AccountId, Description, Status, Dan360_CustomerSalesArea__c,Status_SAP__c, Dan360_OrderReason__c
            FROM Order 
            WHERE Id = :orderId
        ];
        
        Map<String,Order> orderMap = new Map<String,Order>();
        orderMap.put(orden.Id, orden);
        List<sendOrdersToSapHelper.OrderSAP> orderToSAP = new sendOrdersToSapHelper().getMapWithProducts(orderMap, 'Order');
        System.debug(orderToSAP[0].MapOrderBody);
        String body = JSON.serialize(orderToSAP[0].MapOrderBody);
        System.debug(body);
        String typeObj = 'Order';
        String recordName = orderToSAP[0].recordName;

        WebServiceSap.SendAlta respuesta = WebServiceSap.sendAltaToSap(body, typeObj, recordName);
        System.debug('respuesta --->'+respuesta);
        System.debug(!(respuesta.response.getStatusCode() == 200));
        System.debug(respuesta.response.getStatusCode());
        updateOrderSAP(orden.Id,respuesta.response.getBody());
        if(!(respuesta.response.getStatusCode() == 200)){
            sendEmail(respuesta);
        }
    }

    public class applicationException extends Exception {}

    
    

}