force-app/main/default/objects/Case/fields/Dan360_EnviadoSAP__c.field-meta.xml
<CustomField>
    <fullName>Dan360_EnviadoSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviado SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_Factura__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Factura__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Factura relacionada al reclamo generado.</description>
    <label>Factura</label>
    <referenceTo>Dan360_Factura__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_MotivoDeReclamo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_MotivoDeReclamo__c</fullName>
    <description>Especifica el porqué se está realizando la devolución del producto.</description>
    <label>Motivo de reclamo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEVCVEN</fullName>
                <label>Corto vencimiento</label>
            </value>
            <value>
                <fullName>Error facturación impuesto a las ventas</fullName>
            </value>
            <value>
                <fullName>Error ingreso admin pedido</fullName>
            </value>
            <value>
                <fullName>Exento de Impuestos</fullName>
            </value>
            <value>
                <fullName>Faltante producto por abasto</fullName>
                <label>Faltante de producto</label>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>NOSOLIC</fullName>
                <label>No pedido</label>
            </value>
            <value>
                <fullName>No se ingresó motivo para Nota de Crédito</fullName>
            </value>
            <value>
                <fullName>PRODA</fullName>
                <label>Producto Dañado</label>
            </value>
            <value>
                <fullName>Producto Incorrecto</fullName>
            </value>
            <value>
                <fullName>PROVEN</fullName>
                <label>Producto vencido</label>
            </value>
            <value>
                <fullName>Se usó tasa impositiva incorrecta en la factura original</fullName>
            </value>
            <value>
                <fullName>Demora en la entrega</fullName>
            </value>
            <value>
                <fullName>Entrega fuera del horario/día acordado</fullName>
            </value>
            <value>
                <fullName>Malos tratos del chofer</fullName>
            </value>
            <value>
                <fullName>Dan360_PorNoPedido</fullName>
                <isActive>false</isActive>
                <label>Dan360_PorNoPedido</label>
            </value>
            <value>
                <fullName>Dan360_PorProductoDañado</fullName>
                <isActive>false</isActive>
                <label>Dan360_PorProductoDañado</label>
            </value>
            <value>
                <fullName>Dan360_PorProductoVencido</fullName>
                <isActive>false</isActive>
                <label>Dan360_PorProductoVencido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_OrderedDate__c.field-meta.xml
<CustomField>
    <fullName>Dan360_OrderedDate__c</fullName>
    <label>Ordered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_OrderGetEnd__c.field-meta.xml
<CustomField>
    <fullName>Dan360_OrderGetEnd__c</fullName>
    <label>Order Get End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_OrderGetStart__c.field-meta.xml
<CustomField>
    <fullName>Dan360_OrderGetStart__c</fullName>
    <label>Order Get Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Pedido__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Número de pedido por el cual se está generando el reclamo.</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remito relacionado a un pedido.</description>
    <label>Remito</label>
    <referenceTo>Dan360_Remito__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_RequiredDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>Dan360_RequiredDeliveryDate__c</fullName>
    <label>Required Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Reclamo.recordType-meta.xml
<RecordType>
    <fullName>Reclamo</fullName>
    <active>true</active>
    <businessProcess>General</businessProcess>
    <label>Reclamo</label>
</RecordType>

force-app/main/default/objects/Dan360_Factura__c/Dan360_Factura__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los documentos de cuentas corrientes de los clientes que se relacionan a un pedido.</description>
    <label>Factura</label>
    <nameField>
        <displayFormat>Fact-{0000}</displayFormat>
        <label>Nombre de Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Delivery__c</fullName>
    <formula>Dan360_Remito__r.Dan360_Delivery__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Pedido__c</fullName>
    <description>Pedido al cual se relaciona la factura.</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipName>Facturas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remito al cual está relacionada una factura.</description>
    <label>Remito</label>
    <referenceTo>Dan360_Remito__c</referenceTo>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Remito__c/Dan360_Remito__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los remitos que se relacionan a un pedido</description>
    <label>Remito</label>
    <nameField>
        <displayFormat>Rem{0000}</displayFormat>
        <label>Nombre de Remito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Remito__c/fields/Dan360_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Delivery__c</fullName>
    <externalId>true</externalId>
    <label>Delivery</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Dan360_Remito__c/fields/Dan360_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Pedido__c</fullName>
    <description>Pedido al cual está relacionado el remito.</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Remitos</relationshipLabel>
    <relationshipName>Remitos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Remito__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <label>Remito</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendCaseToSap.cls
public with sharing class SendCaseToSap {
    @InvocableMethod(label='Send Case To SAP' description='Send case to sap')
    public static void sendCaseToSapFlow(List<string> recordId){
        System.debug('Entro');
        String caseId = recordId[0];
        Case reclamo = [
            SELECT Id, CaseNumber, Dan360_MotivoDeReclamo__c, RecordType.Name, Dan360_Pedido__c,Dan360_EnviadoSAP__c, Description, 
            Dan360_RequiredDeliveryDate__c, Dan360_OrderedDate__c, Dan360_OrderGetStart__c,Dan360_OrderGetEnd__c,
            Dan360_Remito__r.Dan360_Delivery__c, Dan360_Factura__r.Dan360_Id_Externo__c, CreatedDate
            FROM Case 
            WHERE iD = :caseId
        ];

        Map<String,Case> caseMap = new Map<String,Case>();
        caseMap.put(reclamo.Id, reclamo);
        String typeObj = 'Case';
        BatchSendOrdersToSap caseBatch = new BatchSendOrdersToSap(caseMap, typeObj);
        ID batchId = Database.executeBatch(caseBatch); 
    }
}