force-app/main/default/objects/Case/fields/Dan360_Factura__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Factura__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Factura relacionada al reclamo generado.</description>
    <label>Factura</label>
    <referenceTo>Dan360_Factura__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Pedido__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Número de pedido por el cual se está generando el reclamo.</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remito relacionado a un pedido.</description>
    <label>Remito</label>
    <referenceTo>Dan360_Remito__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Dan360_Devoluciones.recordType-meta.xml
<RecordType>
    <fullName>Dan360_Devoluciones</fullName>
    <active>true</active>
    <businessProcess>Dan360_ReclamosDevolucion</businessProcess>
    <description>Devoluciones de productos relacionado a un pedido procesado.</description>
    <label>Devoluciones</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Reclamo.recordType-meta.xml
<RecordType>
    <fullName>Reclamo</fullName>
    <active>true</active>
    <businessProcess>General</businessProcess>
    <label>Reclamo</label>
</RecordType>

force-app/main/default/objects/Dan360_Factura__c/Dan360_Factura__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los documentos de cuentas corrientes de los clientes que se relacionan a un pedido.</description>
    <label>Factura</label>
    <nameField>
        <displayFormat>Fact-{0000}</displayFormat>
        <label>Nombre de Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Pedido__c</fullName>
    <description>Pedido al cual se relaciona la factura.</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipName>Facturas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remito al cual está relacionada una factura.</description>
    <label>Remito</label>
    <referenceTo>Dan360_Remito__c</referenceTo>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductoDeFactura__c/Dan360_ProductoDeFactura__c.object-meta.xml
<CustomObject>
    <description>Productos que se relacionan a una factura.</description>
    <label>Producto de factura</label>
    <nameField>
        <displayFormat>PrdXFact-{0000}</displayFormat>
        <label>Nombre de Producto de factura</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dan360_ProductoDeFactura</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_ProductoDeFactura__c/fields/Dan360_Factura__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Factura__c</fullName>
    <description>Factura a la cual se relaciona el producto.</description>
    <label>Factura</label>
    <referenceTo>Dan360_Factura__c</referenceTo>
    <relationshipLabel>Producto de factura</relationshipLabel>
    <relationshipName>Dan360_ProductoDeFactura</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductoDeRemito__c/Dan360_ProductoDeRemito__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los productos asociados a un remito.</description>
    <label>Producto de remito</label>
    <nameField>
        <displayFormat>PrdXRem-{0000}</displayFormat>
        <label>Nombre de Producto de remito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos de remito</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_ProductoDeRemito__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <description>Remito al que se asocia el producto.</description>
    <label>Remito</label>
    <referenceTo>Dan360_Remito__c</referenceTo>
    <relationshipLabel>Productos de remito</relationshipLabel>
    <relationshipName>Productos_de_remito</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductosDeReclamo__c/Dan360_ProductosDeReclamo__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los productos que se relacionan aun reclamo.</description>
    <label>Producto de Reclamo</label>
    <nameField>
        <label>Nombre de Productos de Reclamo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos de reclamo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Remito__c/Dan360_Remito__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los remitos que se relacionan a un pedido</description>
    <label>Remito</label>
    <nameField>
        <displayFormat>Rem{0000}</displayFormat>
        <label>Nombre de Remito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Remito__c/fields/Dan360_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Pedido__c</fullName>
    <description>Pedido al cual está relacionado el remito.</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Remitos</relationshipLabel>
    <relationshipName>Remitos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Remito__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <label>Remito</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseControllerTest.cls
@IsTest
public with sharing class CaseControllerTest {
	@TestSetup
	static void makeData(){
		Id pricebookId = Test.getStandardPricebookId();

		Account account = Build.anAccount()
			.withPriceBook(pricebookId)
			.withName('Account Test Name')
			.build();
		insert account;

		Product2 productOne = Build.aProduct()
			.withName('Test N ' + Math.random() * 100)
			.withProductCode('0001')
			.withIdSap('0001')
			.withIsActive(true)
			.build();
		insert productOne;

		Product2 productTwo = Build.aProduct()
			.withName('Test N ' + Math.random() * 100)
			.withProductCode('0002')
			.withIdSap('0002')
			.withIsActive(true)
			.build();
		insert productTwo;

		List<PricebookEntry> pricebooksEntries = [
										SELECT  IsActive,
												Pricebook2Id,
												Product2Id,
												UnitPrice
										FROM PricebookEntry
										WHERE Pricebook2Id = :pricebookId
		];

		
		PricebookEntry pricebookEntryOne = pricebooksEntries[0];		
		PricebookEntry pricebookEntryTwo = pricebooksEntries[1];

		Order order = Build.anOrder()
			.withAccount(account)
			.withStatus('Borrador')
			.withEffectiveDate(Date.today())
			.withPricebook(pricebookId)
			.withPurchaseOrder('')
			.withBusinessUnit('5771')
			.withIdExterno('1234')
			.build();
		insert order;

		OrderItem orderItemOne = Build.anOrderItem()
			.withOrder(order)
			.withProduct2Id(pricebookEntryOne.Product2Id)
			.withListPrice(100)
			.withUnitPrice(100)
			.withQuantity(1000)
			.withPricebookEntryId(pricebookEntryOne)
			.build();
		insert orderItemOne;

		OrderItem orderItemTwo = Build.anOrderItem()
			.withOrder(order)
			.withProduct2Id(pricebookEntryTwo.Product2Id)
			.withListPrice(100)
			.withUnitPrice(100)
			.withQuantity(1000)
			.withPricebookEntryId(pricebookEntryTwo)
			.build();
		insert orderItemTwo;

		Dan360_Remito__c deliveryNote = Build.aRemito()
			.withPedido(order)
			.withSucursal(account)
			.build();
		insert deliveryNote;

		Dan360_Factura__c invoice = Build.aFactura()
			.withPedido(order)
			.withRemito(deliveryNote)
			.build();
		insert invoice;


		Dan360_ProductoDeFactura__c invoiceProduct = Build.aProductoDeFactura()
			.withCantidadProductoFacturado(orderItemOne.Quantity)
			.withFactura(invoice)
			.withProducto(productOne)
			.withPrecioUnitario(100)
			.build();
		insert invoiceProduct;

		Dan360_ProductoDeRemito__c deliveryNoteProduct = Build.aProductoDeRemito()
			.withCantidadProducto(50)
			.withProducto(productOne)
			.withRemito(deliveryNote)
			.build();
		insert deliveryNoteProduct;
	}

	@IsTest
	private static void cuandoConsultoProductosDeFacturaDeberiaObtenerListado() {
		Id invoiceId = [
			SELECT  Id
			FROM    Dan360_Factura__c
			LIMIT   1
		].Id;

		Test.startTest();
			List<CaseController.WrapperProductComplaint> productsToComplaint = CaseController.getInvoiceProducts(invoiceId, 'Dan360_Factura__c');
		Test.stopTest();

		System.assertNotEquals(0, productsToComplaint.size(), 'No se encontraron productos de esta factura.');
	}

	@IsTest
	private static void cuandoConsultoProductosDeRemitoDeberiaObtenerListado() {
		Id deliveryNoteId = [
			SELECT  Id
			FROM    Dan360_Remito__c
			LIMIT   1
		].Id;

		Test.startTest();
			List<CaseController.WrapperProductComplaint> productsToComplaint = CaseController.getInvoiceProducts(deliveryNoteId, 'Dan360_Remito__c');
		Test.stopTest();

		System.assertNotEquals(0, productsToComplaint.size(), 'No se encontraron productos de este remito.');
	}

	@IsTest
	private static void cuandoEnvioTipoDeReclamoDeberiaObtenerFieldSetAsociado() {
		Test.startTest();
			String fieldSet = CaseController.getFieldSet('Dan360_ReclamoDevolucion');
		Test.stopTest();

		System.assertNotEquals(null, fieldSet, 'No se obtuvo el fieldSet para devoluciones.');
	}

	@IsTest
	private static void deberiaGuardarReclamo() {
		Dan360_Factura__c invoice = [
			SELECT  Id,
					Dan360_Pedido__c,
					Dan360_Remito__c
			FROM    Dan360_Factura__c
			LIMIT   1
		];

		Account account = [SELECT Id FROM Account LIMIT 1];

		Id recordType = CaseController.getRecordTypeId('Dan360_Devoluciones');

		Case complaint = Build.aReclamo()
			.withAccount(account)
			.withCantidadADevolver('20 unidades de PKU ANAMIX INFANT 6X400G MLL 3')
			.withFactura(invoice)
			.withMotivoDeReclamo('DEVCVEN')
			.withPedido(invoice.Dan360_Pedido__c)
			.withRemito(invoice.Dan360_Remito__c)
			.withSucursal(account)
			.withRecordType(recordType)
			.build();

		List<Dan360_ProductosDeReclamo__c> complaintProducts = new List<Dan360_ProductosDeReclamo__c>();
		complaintProducts.add(
			Build.aProductoDeReclamo()
				.withCantidadDevolver('5 unidades de Producto 2')
				.withProducto([SELECT Id FROM Product2 LIMIT 1])
				.withRecordType(complaint.RecordType)
				.build()
		);

		Test.startTest();
			ServerResponse response = CaseController.saveComplaint(complaint, complaintProducts, true);
		Test.stopTest();

		System.assertEquals('SUCCESS', response.state, 'No se registró reclamo.');
	}

	@IsTest
	private static void cuandoListaDeProductosVaciaNoDeberiaRegistrarReclamo() {
		Dan360_Factura__c invoice = [
			SELECT  Id,
					Dan360_Pedido__c,
					Dan360_Remito__c
			FROM    Dan360_Factura__c
			LIMIT   1
		];

		Account account = [SELECT Id FROM Account LIMIT 1];

		Case complaint = Build.aReclamo()
			.withAccount(account)
			.withCantidadADevolver('20 unidades de PKU ANAMIX INFANT 6X400G MLL 3')
			.withFactura(invoice)
			.withMotivoDeReclamo('DEVCVEN')
			.withPedido(invoice.Dan360_Pedido__c)
			.withRemito(invoice.Dan360_Remito__c)
			.withSucursal(account)
			.withRecordType('0124C000000LddeQAC')
			.build();

		List<Dan360_ProductosDeReclamo__c> complaintProducts = new List<Dan360_ProductosDeReclamo__c>();

		Test.startTest();
			ServerResponse response = CaseController.saveComplaint(complaint, complaintProducts, true);
		Test.stopTest();

		System.assertEquals('ERROR', response.state, 'Reclamo registrado.');
	}

	@IsTest
	private static void deberiaObtenerDatosDeFactura() {
		Dan360_Factura__c invoice = [
			SELECT  Id,
					Dan360_Pedido__c
			FROM    Dan360_Factura__c
			LIMIT   1
		];

		Test.startTest();
			Object invoiceToValidate = CaseController.getInvoiceOrDeliveryNoteData(invoice.Id, 'Dan360_Factura__c');
		Test.stopTest();

		System.assertNotEquals(null, invoiceToValidate, 'No fue posible obtener datos de factura.');
	}

	@IsTest
	private static void deberiaObtenerDatosDeRemito() {
		Dan360_Factura__c invoice = [
			SELECT  Id,
					Dan360_Remito__c
			FROM    Dan360_Factura__c
			LIMIT   1
		];

		Test.startTest();
			Object invoiceToValidate = CaseController.getInvoiceOrDeliveryNoteData(invoice.Dan360_Remito__c, 'Dan360_Remito__c');
		Test.stopTest();

		System.assertNotEquals(null, invoiceToValidate, 'No fue posible obtener datos de remito.');
	}

	@IsTest
	private static void deberiaObtenerRecordTypeId() {
		Test.startTest();
			Id recordTypeId = CaseController.getRecordTypeId('Dan360_Devoluciones');
		Test.stopTest();

		System.assertNotEquals('', recordTypeId, 'No fue posible obtener RecordTypeId.');
	}

	@IsTest
	private static void cuandoConsultoProductosDeFacturaDeberiaObtenerListadoConLasCantidadesYaReclamadas() {
		Dan360_Factura__c invoice = [
			SELECT  Id,
					Dan360_Pedido__c,
					Dan360_Remito__c
			FROM    Dan360_Factura__c
			LIMIT   1
		];

		Account account = [SELECT Id FROM Account LIMIT 1];

		Id recordType = CaseController.getRecordTypeId('Dan360_Devoluciones');

		Case complaint = Build.aReclamo()
			.withAccount(account)
			.withCantidadADevolver('20 unidades de PKU ANAMIX INFANT 6X400G MLL 3')
			.withFactura(invoice)
			.withMotivoDeReclamo('DEVCVEN')
			.withPedido(invoice.Dan360_Pedido__c)
			.withRemito(invoice.Dan360_Remito__c)
			.withSucursal(account)
			.withRecordType(recordType)
			.build();

		List<Dan360_ProductosDeReclamo__c> complaintProducts = new List<Dan360_ProductosDeReclamo__c>();
		complaintProducts.add(
			Build.aProductoDeReclamo()
				.withCantidadDevolver('5')
				.withProducto([SELECT Id FROM Product2 WHERE ProductCode = '0001'])
				.withRecordType(complaint.RecordType)
				.build()
		);

		Case complaint2 = Build.aReclamo()
			.withAccount(account)
			.withCantidadADevolver('20 unidades de PKU ANAMIX INFANT 6X400G MLL 3')
			.withFactura(invoice)
			.withMotivoDeReclamo('DEVCVEN')
			.withPedido(invoice.Dan360_Pedido__c)
			.withRemito(invoice.Dan360_Remito__c)
			.withSucursal(account)
			.withRecordType(recordType)
			.build();

		List<Dan360_ProductosDeReclamo__c> complaintProducts2 = new List<Dan360_ProductosDeReclamo__c>();
		complaintProducts2.add(
			Build.aProductoDeReclamo()
				.withCantidadProductosFaltantes('15')
				.withProducto([SELECT Id FROM Product2 WHERE ProductCode = '0001'])
				.withRecordType(complaint.RecordType)
				.build()
		);

		Test.startTest();
			ServerResponse response = CaseController.saveComplaint(complaint, complaintProducts, true);
			ServerResponse response2 = CaseController.saveComplaint(complaint2, complaintProducts2, true);
			List<CaseController.WrapperProductComplaint> productsToComplaint = CaseController.getInvoiceProducts(invoice.Id, 'Dan360_Factura__c');
		Test.stopTest();


		System.assertEquals('SUCCESS', response.state, response.message);
		System.assertEquals('SUCCESS', response2.state, response2.message);
		System.assertNotEquals(0, productsToComplaint.size(), 'No se encontraron productos de esta factura.');
		System.assertEquals(20, productsToComplaint[0].productQuantityClaimed, 'No se encontro la cantidad reclamada consolidada para el producto.');
	}
	@IsTest
	private static void deberiaGuardarReclamoSinProductos(){
		Dan360_Factura__c invoice = [
			SELECT  Id,
					Dan360_Pedido__c,
					Dan360_Remito__c
			FROM    Dan360_Factura__c
			LIMIT   1
		];

		Account account = [SELECT Id FROM Account LIMIT 1];

		Id recordType = CaseController.getRecordTypeId('Dan360_Devoluciones');

		Case complaint = Build.aReclamo()
			.withAccount(account)
			.withCantidadADevolver('20 unidades de PKU ANAMIX INFANT 6X400G MLL 3')
			.withFactura(invoice)
			.withMotivoDeReclamo('DEVCVEN')
			.withPedido(invoice.Dan360_Pedido__c)
			.withRemito(invoice.Dan360_Remito__c)
			.withSucursal(account)
			.withRecordType(recordType)
			.build();

		Test.startTest();
			ServerResponse response = CaseController.saveComplaint(complaint, null, false);
		Test.stopTest();

		System.assertEquals('SUCCESS', response.state, response.message);
	}

	@IsTest
	private static void noDeberiaGuardarReclamoConProductos(){
		Dan360_Factura__c invoice = [
			SELECT  Id,
					Dan360_Pedido__c,
					Dan360_Remito__c
			FROM    Dan360_Factura__c
			LIMIT   1
		];

		Account account = [SELECT Id FROM Account LIMIT 1];

		Id recordType = CaseController.getRecordTypeId('Dan360_Devoluciones');

		Case complaint = Build.aReclamo()
			.withAccount(account)
			.withCantidadADevolver('20 unidades de PKU ANAMIX INFANT 6X400G MLL 3')
			.withFactura(invoice)
			.withMotivoDeReclamo('DEVCVEN')
			.withPedido(invoice.Dan360_Pedido__c)
			.withRemito(invoice.Dan360_Remito__c)
			.withSucursal(account)
			.withRecordType(recordType)
			.build();

		List<Dan360_ProductosDeReclamo__c> complaintProducts = new List<Dan360_ProductosDeReclamo__c>();
		complaintProducts.add(
			Build.aProductoDeReclamo()
				.withCantidadProductosFaltantes('15')
				.withProducto([SELECT Id FROM Product2 WHERE ProductCode = '0001'])
				.withRecordType(complaint.RecordType)
				.build()
		);

		Test.startTest();
			ServerResponse response = CaseController.saveComplaint(null, complaintProducts, true);
		Test.stopTest();

		System.assertEquals('ERROR', response.state, response.message);
	}
	@IsTest
	private static void deberiaObtenerElApiName(){
		Dan360_Factura__c invoice = [
			SELECT  Id					
			FROM    Dan360_Factura__c
			LIMIT   1
		];
		
		Test.startTest();
			String apiName = CaseController.getObjApiName(invoice.id);
		Test.stopTest();

		System.assertEquals('Dan360_Factura__c', apiName, 'Error al obtener el api name');
	}
	@IsTest
	private static void deberiaObtenerLaFacturaDelPedido(){
		Id pricebookId = Test.getStandardPricebookId();

		Account account = [
			SELECT id
			FROM Account
			LIMIT 1
		];
		
		Order order = Build.anOrder()
			.withAccount(account)
			.withStatus('Borrador')
			.withEffectiveDate(Date.today())
			.withPricebook(pricebookId)
			.withPurchaseOrder('')
			.withBusinessUnit('5771')
			.withIdExterno('77777')
			.build();
		insert order;

		Dan360_Factura__c invoice = Build.aFactura()
			.withPedido(order)			
			.build();
		insert invoice;
		
		Test.startTest();
		Object invoiceToCompare = CaseController.getFacturaByOrder(order.id);
		Test.stopTest();
		List<Object> invoiceList = new List<Object>();
		invoiceList.add(invoiceToCompare);
		
		System.assertEquals(1, invoiceList.size(), 'Error al obtener la factura por Id del pedido');
	}

	@IsTest
	private static void remitoFromNotChargeOrder(){		

		List<Dan360_Remito__c> remito = [SELECT Id FROM Dan360_Remito__c];
		
		Test.startTest();
		Boolean isNotCharge = CaseController.isDevliveryFromNotCharge(remito[0].id,'Dan360_Remito__c');
		Test.stopTest();
		System.debug(isNotCharge);
		System.assertEquals(false, isNotCharge);
	}
}