force-app/main/default/objects/Dan360_ConfiguracionesGenerales__mdt/Dan360_ConfiguracionesGenerales__mdt.object-meta.xml
<CustomObject>
    <description>Metadata que contiene ID o configuraciones personalizadas que se requieren en alguna parte de los procesos para evitar hardcodeo.</description>
    <label>Configuraciones Generales</label>
    <pluralLabel>Configuraciones Generales</pluralLabel>
</CustomObject>

force-app/main/default/objects/Dan360_ConfiguracionesGenerales__mdt/fields/Dan360_PerfilesOMSComunidad__c.field-meta.xml
<CustomField>
    <fullName>Dan360_PerfilesOMSComunidad__c</fullName>
    <label>Perfiles OMS Comunidad</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/VisMed_Es_un_Visitador_Medico__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Es_un_Visitador_Medico__c</fullName>
    <defaultValue>false</defaultValue>
    <description>field booleano para indicar si el usuario pertenece a la familia de visitadores y saber si debe contar en las querys.</description>
    <label>Es un Visitador Medico</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/userHelper.cls
public with sharing class userHelper {
    public static void sendEmailToUserCommunity(List<User> users){
        String profileToSend = Dan360_ConfiguracionesGenerales__mdt.getInstance('Dan360_ConfiguracionesGenerales').Dan360_PerfilesOMSComunidad__c;
        System.debug(profileToSend);
        List<String> profilesToSend = profileToSend.split(', ');

        List<String> usersProfilesIds = new List<String>();

        
        
        for(User usuario : users){
            usersProfilesIds.add(usuario.ProfileId);
        }

        Map<Id,Profile> mapIdProfile = new Map<Id,Profile>([SELECT Id, Name FROM PROFILE WHERE Id IN : usersProfilesIds]);
        System.debug(mapIdProfile);

        for(User usuario : users){
            if(usuario.VisMed_Es_un_Visitador_Medico__c == false && profilesToSend.contains(mapIdProfile.get(usuario.ProfileId).Name)){
                System.debug('Enviar Mail');
                System.resetPassword(usuario.Id, true);
            }
        }

    }
}