force-app/main/default/objects/Order/fields/Dan360_FechasConfirmado__c.field-meta.xml
<CustomField>
    <fullName>Dan360_FechasConfirmado__c</fullName>
    <label>Fecha Confirmado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_PedidoConfirmado__c.field-meta.xml
<CustomField>
    <fullName>Dan360_PedidoConfirmado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Casilla para notificación de pedido confirmado</description>
    <label>Pedido confirmado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Async_ActualizarOrden_Helper.cls
public class Async_ActualizarOrden_Helper implements Queueable {

    public String orderId {get;set;}

    public Async_ActualizarOrden_Helper(String OrderId){
        this.orderId = OrderId;
    } 

    public void execute(QueueableContext context) {

        actualizarEstado();

    }

    public void actualizarEstado(){
        
        Order a = new Order(
            Id = orderId,
            Status = 'Confirmado',
            Dan360_PedidoConfirmado__c = true,
            Dan360_FechasConfirmado__c = Date.today()
        );

        UPDATE a;

        System.debug('Se actualizo el registro >>> '+ a);
    }

}