force-app/main/default/objects/Order/fields/Dan360_UnidadNegocio__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadNegocio__c</fullName>
    <description>Se refiere al negocio donde se generará una transacción, en donde impactará la venta de un producto.</description>
    <label>Unidad de negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_UnidadDeNegocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Dan360_UnidadDeNegocio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5800</fullName>
        <label>AMN</label>
    </customValue>
    <customValue>
        <fullName>5771</fullName>
        <label>NuBa</label>
    </customValue>
    <description>Determina a qué unidad de negocio se genera un pedido.</description>
    <masterLabel>Unidad de Negocio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PicklistInputTypeControllerTest.cls
@IsTest
private with sharing class PicklistInputTypeControllerTest {
	@TestSetup
	static void makeData(){

	}

	@IsTest
	private static void cuandoRequieroPicklistDeberiaDevolverListadoConValores() {
		Test.startTest();
			List<Object> fieldValues = PicklistInputTypeController.getPicklistFieldsValues('Order', 'Dan360_UnidadNegocio__c');
		Test.stopTest();

		System.assertNotEquals(null, fieldValues, 'No existen picklist.');
		System.assertNotEquals(0, fieldValues.size(), 'No se encontraron valores de la picklist seleccionada.');
	}

	@IsTest
	private static void deberiaDevolverSObjectReferenceDelApiIngresado() {
		Test.startTest();
			String reference = PicklistInputTypeController.getSObjectFieldReference('Dan360_Sucursal__c');
		Test.stopTest();

		System.assertNotEquals('', reference, 'No se encontró referencia.');
	}
}