force-app/main/default/objects/Cambio_de_Contrasena_App_User__c/Cambio_de_Contrasena_App_User__c.object-meta.xml
<CustomObject>
    <description>Objeto para disparar un proceso de aprobacion de cambio de contraseña</description>
    <label>Cambio de Contraseña App User</label>
    <nameField>
        <displayFormat>CPUA-{00000}</displayFormat>
        <label>Cambio de Contraseña Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cambio de Contraseña App User</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cambio_de_Contrasena_App_User__c/fields/Pass__c.field-meta.xml
<CustomField>
    <fullName>Pass__c</fullName>
    <label>Pass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cambio_de_Contrasena_App_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cambio_de_Contrase_a_App_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/VisMed_ContrasenaApp__c.field-meta.xml
<CustomField>
    <fullName>VisMed_ContrasenaApp__c</fullName>
    <label>Contraseña App</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/CambioDeContrasenaAppUserTriggerHelper.cls
public with sharing class CambioDeContrasenaAppUserTriggerHelper {
    
    public static void updateUserPass (List<Cambio_de_Contrasena_App_User__c> procesos) {
        Map<Id, String> usuariosXPass = new Map<Id, String>();
        for (Cambio_de_Contrasena_App_User__c proceso : procesos){
            usuariosXPass.put(proceso.User__c, proceso.Pass__c);
        }
        List<User> usuariosToUpdatePass = [
            SELECT Id, VisMed_ContrasenaApp__c
            FROM User
            WHERE Id IN :usuariosXPass.keySet()
        ];

        for (User usuario : usuariosToUpdatePass) {
            usuario.VisMed_ContrasenaApp__c = usuariosXPass.get(usuario.Id);
        }

        if(!usuariosToUpdatePass.isEmpty()){
            UpdateUser(JSON.serialize(usuariosToUpdatePass));
        }
    }

    @Future
    public static void UpdateUser(String usersToUpdate){
        List<User> usuarios = (List<User>)Json.deserialize(usersToUpdate, List<User>.Class);

        update usuarios;
    }
}