force-app/main/default/objects/Cambio_de_Contrasena_App_User__c/Cambio_de_Contrasena_App_User__c.object-meta.xml
<CustomObject>
    <description>Objeto para disparar un proceso de aprobacion de cambio de contraseña</description>
    <label>Cambio de Contraseña App User</label>
    <nameField>
        <displayFormat>CPUA-{00000}</displayFormat>
        <label>Cambio de Contraseña Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cambio de Contraseña App User</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cambio_de_Contrasena_App_User__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Aprobada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cambio_de_Contrasena_App_User__c/fields/Pass__c.field-meta.xml
<CustomField>
    <fullName>Pass__c</fullName>
    <label>Pass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cambio_de_Contrasena_App_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cambio_de_Contrase_a_App_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/VisMed_ContrasenaApp__c.field-meta.xml
<CustomField>
    <fullName>VisMed_ContrasenaApp__c</fullName>
    <label>Contraseña App</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/User/fields/VisMed_Es_un_Visitador_Medico__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Es_un_Visitador_Medico__c</fullName>
    <defaultValue>false</defaultValue>
    <description>field booleano para indicar si el usuario pertenece a la familia de visitadores y saber si debe contar en las querys.</description>
    <label>Es un Visitador Medico</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/WSResetPasswordTest.cls
@IsTest
public class WSResetPasswordTest {
    @TestSetup
    static void makeData(){
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile profile1 = [Select Id from Profile where Name = 'System Administrator' or name = 'Administrador del sistema' ];

        User userOwner = Build.aUser()
            .withUsername(
                'newuser'+String.valueOf(System.now().getTime() + (Math.random() * 10))+'@testorg.com'
            )               
            .withEmail('owner@xappia.com')
            .withAlias('owner')
            .withLastName('Owner')
            .withTimeZoneSidKey('America/Argentina/Buenos_Aires')
            .withLocaleSidKey('es_AR')
            .withCommunityNickname('prueba2.xappia')
            .withEmailEncodingKey('ISO-8859-1')
            .withProfileId(profile1.Id)
            .withUserRoleId(portalRole)				
            .withLanguageLocaleKey('es')
            .build();           
        userOwner.ManagerId = UserInfo.getUserId();
        userOwner.IsActive = true;
        userOwner.VisMed_Es_un_Visitador_Medico__c = true;
        userOwner.VisMed_ContrasenaApp__c = 'TestOwner';
        insert userOwner;
    }

    @IsTest
    public static void ValidateCorrectUpdateOfPass(){
       
        RestRequest req = new RestRequest();
        req.addHeader('newpassword','NewPassword');
        req.addHeader('username','owner@xappia.com');
        req.addHeader('currentpassword','TestOwner');
        
        req.requestURI = '/services/apexrest/resetUserPassword/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        
        Test.startTest();
        WSResetPassword.Respuesta resp = WSResetPassword.resetPassword();
        Test.stopTest();

        List<user> userToChagePass = [
            SELECT Id,VisMed_ContrasenaApp__c
            FROM User
            WHERE CommunityNickname = 'prueba2.xappia'
        ];

        system.assertEquals(200, resp.status);
        system.assertEquals('Contraseña cambiada exitosamente', resp.message);
        system.assertEquals('NewPassword',userToChagePass.get(0).VisMed_ContrasenaApp__c);

    }

    @IsTest
    public static void ValidateErrorWhenUpdatePass(){
       
        RestRequest req = new RestRequest();
        req.addHeader('newpassword','NewPassword');
        req.addHeader('username','owner@xappia.com');
        req.addHeader('currentpassword','TestOwnerFailed');
        
        req.requestURI = '/services/apexrest/resetUserPassword/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        
        Test.startTest();
        WSResetPassword.Respuesta resp = WSResetPassword.resetPassword();
        Test.stopTest();

        system.assertEquals(401, resp.status);
        system.assertEquals('El usuario y/o contraseña no existen.', resp.message);
    }
    
    @IsTest
    public static void ValidateCurrentPassNull(){
       
        RestRequest req = new RestRequest();
        req.addHeader('newpassword','NewPassword');
        req.addHeader('username','owner@xappia.com');
        req.addHeader('currentpassword','');
        
        req.requestURI = '/services/apexrest/resetUserPassword/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        
        Test.startTest();
        WSResetPassword.Respuesta resp = WSResetPassword.resetPassword();
        Test.stopTest();

        List<Cambio_de_Contrasena_App_User__c> listChangePass = [
            SELECT Id,Estado__c,User__c,Pass__c,OwnerId
            FROM Cambio_de_Contrasena_App_User__c
        ];

        List<user> userToChagePass = [
            SELECT Id,VisMed_ContrasenaApp__c
            FROM User
            WHERE CommunityNickname = 'prueba2.xappia'
        ];

        system.assertEquals(200, resp.status);
        system.assertEquals('Solicitud de cambio enviada al correo electronico', resp.message);
        system.assertEquals('Pendiente',listChangePass.get(0).Estado__c);
        system.assertEquals(userToChagePass.get(0).Id,listChangePass.get(0).User__c);
        system.assertEquals('NewPassword',listChangePass.get(0).Pass__c);
        system.assertEquals(userToChagePass.get(0).Id,listChangePass.get(0).OwnerId);
    }
}