force-app/main/default/objects/VisMed_ConfigApp__c/VisMed_ConfigApp__c.object-meta.xml
<CustomObject>
    <label>ConfigApp</label>
    <nameField>
        <label>ConfigApp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ConfigApp</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_ConfigApp__c/fields/Objeto_Principal__c.field-meta.xml
<CustomField>
    <fullName>Objeto_Principal__c</fullName>
    <label>Objeto Principal</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VisMed_ConfigApp__c/fields/VisMed_Activa__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Activa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VisMed_ConfigApp__c/fields/VisMed_Vista_Compacta__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Vista_Compacta__c</fullName>
    <label>Vista Compacta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VisMed_ConfigApp__c/fields/VisMed_Vista_Detalle__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Vista_Detalle__c</fullName>
    <label>Vista Detalle</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VisMed_ConfigApp__c/fields/VisMed_Vista_Formulario__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Vista_Formulario__c</fullName>
    <label>Vista Formulario</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VisMed_ConfigApp__c/recordTypes/Funcionalidad.recordType-meta.xml
<RecordType>
    <fullName>Funcionalidad</fullName>
    <active>true</active>
    <description>RecordType para registrar las distintas funcionalidades de la app.</description>
    <label>Funcionalidad</label>
</RecordType>

force-app/main/default/objects/VisMed_ConfigApp__c/recordTypes/Objeto.recordType-meta.xml
<RecordType>
    <fullName>Objeto</fullName>
    <active>true</active>
    <description>RecordType para registrar los distintos objetos de la app.</description>
    <label>Objeto</label>
</RecordType>

force-app/main/default/classes/WSMetadataAppTest.cls
@IsTest
public class WSMetadataAppTest {
    private static final Id recordTypeFuncionalidad = Schema.SObjectType.VisMed_ConfigApp__c.getRecordTypeInfosByDeveloperName().get('Funcionalidad').getRecordTypeId();
    private static final Id recordTypeObjeto = Schema.SObjectType.VisMed_ConfigApp__c.getRecordTypeInfosByDeveloperName().get('Objeto').getRecordTypeId();
    @TestSetup
    static void makeData(){
        List<VisMed_ConfigApp__c> listToInsert = new List<VisMed_ConfigApp__c>();
        VisMed_ConfigApp__c visMedFuncionalActivo = Build.aVisMedConfigAppFuncionalidad()
            .withName('Ciclo')
            .withVisMedActiva(true)
            .build();     
        visMedFuncionalActivo.Objeto_Principal__c = 'objetoPrincipalFuncional';
        visMedFuncionalActivo.VisMed_Vista_Compacta__c = 'vistaCompactaFuncional';
        visMedFuncionalActivo.VisMed_Vista_Detalle__c = 'vistaDetalleFuncional';
        visMedFuncionalActivo.VisMed_Vista_Formulario__c = 'vistaFormularioFuncional';
        listToInsert.add(visMedFuncionalActivo);

        VisMed_ConfigApp__c visMedFuncionalDesactivado = Build.aVisMedConfigAppFuncionalidad()
            .withName('Ciclo Desactivado')
            .withVisMedActiva(false)
            .build();     
        visMedFuncionalDesactivado.Objeto_Principal__c = 'objetoPrincipalFuncional';
        visMedFuncionalDesactivado.VisMed_Vista_Compacta__c = 'vistaCompactaFuncional';
        visMedFuncionalDesactivado.VisMed_Vista_Detalle__c = 'vistaDetalleFuncional';
        visMedFuncionalDesactivado.VisMed_Vista_Formulario__c = 'vistaFormularioFuncional';
        listToInsert.add(visMedFuncionalDesactivado);

        VisMed_ConfigApp__c visMedObjetoActivo = Build.aVisMedConfigAppObjeto()
            .withName('MedConf2')
            .withVisMedActiva(true)
            .build();     
        visMedObjetoActivo.Objeto_Principal__c = 'objetoPrincipalObjeto';
        visMedObjetoActivo.VisMed_Vista_Compacta__c = 'vistaCompactaObjeto';
        visMedObjetoActivo.VisMed_Vista_Detalle__c = 'vistaDetalleObjeto';
        visMedObjetoActivo.VisMed_Vista_Formulario__c = 'vistaFormularioObjeto';
        listToInsert.add(visMedObjetoActivo);

        VisMed_ConfigApp__c visMedObjetoDesactivo = Build.aVisMedConfigAppObjeto()
            .withName('MedConf2 desactivo')
            .withVisMedActiva(false)
            .build();     
        visMedObjetoDesactivo.Objeto_Principal__c = 'objetoPrincipalObjeto';
        visMedObjetoDesactivo.VisMed_Vista_Compacta__c = 'vistaCompactaObjeto';
        visMedObjetoDesactivo.VisMed_Vista_Detalle__c = 'vistaDetalleObjeto';
        visMedObjetoDesactivo.VisMed_Vista_Formulario__c = 'vistaFormularioObjeto';
        listToInsert.add(visMedObjetoDesactivo);

        insert listToInsert;
    }
    
    @IsTest
    public static void ValidateMethodForRecordTypeFuncional(){
        RestRequest req = new RestRequest();
        req.addHeader('recordtype','Funcionalidad');
        req.requestURI = '/services/apexrest/metadata/';
        req.httpMethod = 'GET';
        RestContext.request = req;
        
        Test.startTest();
        WSMetadataApp.Respuesta resp = WSMetadataApp.doGet();
        Test.stopTest();

        List<VisMed_ConfigApp__c> listOnSalesforce = [
            SELECT id, Name, Objeto_Principal__c, VisMed_Vista_Compacta__c, VisMed_Vista_Detalle__c,VisMed_Vista_Formulario__c 
            FROM VisMed_ConfigApp__c
            WHERE VisMed_Activa__c = true 
            AND RecordTypeId = :recordTypeFuncionalidad
        ];

        system.assertEquals(resp.status, 200, 'Error en el consumo del WS');
        system.assertEquals(resp.forms.size(),1,'Error en los datos');
        system.assertEquals(resp.forms.get(0).nombre,listOnSalesforce.get(0).Name,'Error en los datos');
        system.assertEquals(resp.forms.get(0).id,listOnSalesforce.get(0).Id,'Error en los datos');
        system.assertEquals(resp.forms.get(0).objetoPrincipal,listOnSalesforce.get(0).Objeto_Principal__c,'Error en los datos');
        system.assertEquals(resp.forms.get(0).vistaCompacta,listOnSalesforce.get(0).VisMed_Vista_Compacta__c,'Error en los datos');
        system.assertEquals(resp.forms.get(0).vistaDetalle,listOnSalesforce.get(0).VisMed_Vista_Detalle__c,'Error en los datos');
        system.assertEquals(resp.forms.get(0).vistaFormulario,listOnSalesforce.get(0).VisMed_Vista_Formulario__c,'Error en los datos');
    }

    @IsTest
    public static void ValidateMethodForRecordTypeObjeto(){
        RestRequest req = new RestRequest();
        req.addHeader('recordtype','Objeto');
        req.requestURI = '/services/apexrest/metadata/';
        req.httpMethod = 'GET';
        RestContext.request = req;
        
        Test.startTest();
        WSMetadataApp.Respuesta resp = WSMetadataApp.doGet();
        Test.stopTest();

        List<VisMed_ConfigApp__c> listOnSalesforce = [
            SELECT id, Name, Objeto_Principal__c, VisMed_Vista_Compacta__c, VisMed_Vista_Detalle__c,VisMed_Vista_Formulario__c 
            FROM VisMed_ConfigApp__c
            WHERE VisMed_Activa__c = true 
            AND RecordTypeId = :recordTypeObjeto
        ];

        system.assertEquals(resp.status, 200, 'Error en el consumo del WS');
        system.assertEquals(resp.forms.size(),1,'Error en los datos');
        system.assertEquals(resp.forms.get(0).nombre,listOnSalesforce.get(0).Name,'Error en los datos');
        system.assertEquals(resp.forms.get(0).id,listOnSalesforce.get(0).Id,'Error en los datos');
        system.assertEquals(resp.forms.get(0).objetoPrincipal,listOnSalesforce.get(0).Objeto_Principal__c,'Error en los datos');
        system.assertEquals(resp.forms.get(0).vistaCompacta,listOnSalesforce.get(0).VisMed_Vista_Compacta__c,'Error en los datos');
        system.assertEquals(resp.forms.get(0).vistaDetalle,listOnSalesforce.get(0).VisMed_Vista_Detalle__c,'Error en los datos');
        system.assertEquals(resp.forms.get(0).vistaFormulario,listOnSalesforce.get(0).VisMed_Vista_Formulario__c,'Error en los datos');
    }

    @IsTest
    public static void ValidateMethodForRecordTypeNull(){
        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/metadata/';
        req.httpMethod = 'GET';
        RestContext.request = req;
        
        Test.startTest();
        WSMetadataApp.Respuesta resp = WSMetadataApp.doGet();
        Test.stopTest();
       
        system.assertEquals(resp.status, 200, 'Error en el consumo del WS');
        system.assertEquals(resp.forms.size(),0,'Error en los datos');       
    }
}