force-app/main/default/objects/Account/recordTypes/Institucion.recordType-meta.xml
<RecordType>
    <fullName>Institucion</fullName>
    <active>true</active>
    <label>Institución</label>
</RecordType>

force-app/main/default/objects/Ciclo__c/Ciclo__c.object-meta.xml
<CustomObject>
    <label>Ciclo</label>
    <nameField>
        <label>Nombre de Ciclo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Sub_Equipo__c.field-meta.xml
<CustomField>
    <fullName>Sub_Equipo__c</fullName>
    <label>Sub Equipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Equipo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/VisMed_DNI__c.field-meta.xml
<CustomField>
    <fullName>VisMed_DNI__c</fullName>
    <label>DNI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Visitador_medico.recordType-meta.xml
<RecordType>
    <fullName>Visitador_medico</fullName>
    <active>true</active>
    <label>Visitador médico</label>
</RecordType>

force-app/main/default/objects/Stock_x_Ciclo__c/Stock_x_Ciclo__c.object-meta.xml
<CustomObject>
    <label>Stock x Ciclo</label>
    <nameField>
        <displayFormat>SXC-{0000}</displayFormat>
        <label>Stock x Ciclo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock x Ciclo</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_x_Ciclo__c/fields/APM__c.field-meta.xml
<CustomField>
    <fullName>APM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>APM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Visitador Medico</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Stock x Ciclo</relationshipLabel>
    <relationshipName>Stock_x_Ciclo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_x_Ciclo__c/fields/Ciclo__c.field-meta.xml
<CustomField>
    <fullName>Ciclo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciclo</label>
    <referenceTo>VisMed_Ciclo__c</referenceTo>
    <relationshipLabel>Stock x Ciclo</relationshipLabel>
    <relationshipName>Stock_x_Ciclo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_x_MM__c/Stock_x_MM__c.object-meta.xml
<CustomObject>
    <label>Stock x MM</label>
    <nameField>
        <displayFormat>SXM-{0000}</displayFormat>
        <label>Stock x MM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock x MM</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_x_MM__c/fields/APM__c.field-meta.xml
<CustomField>
    <fullName>APM__c</fullName>
    <formula>Stock_x_Ciclo__r.APM__r.FirstName + &quot; &quot; + Stock_x_Ciclo__r.APM__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_x_MM__c/fields/Ciclo__c.field-meta.xml
<CustomField>
    <fullName>Ciclo__c</fullName>
    <formula>Stock_x_Ciclo__r.Ciclo__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ciclo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_x_MM__c/fields/Muestra_Medica__c.field-meta.xml
<CustomField>
    <fullName>Muestra_Medica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Muestra Medica</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stock x MM</relationshipLabel>
    <relationshipName>Stock_x_MM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_x_MM__c/fields/Stock_x_Ciclo__c.field-meta.xml
<CustomField>
    <fullName>Stock_x_Ciclo__c</fullName>
    <label>Stock x Ciclo</label>
    <referenceTo>Stock_x_Ciclo__c</referenceTo>
    <relationshipLabel>Stock x MM</relationshipLabel>
    <relationshipName>Stock_x_MM</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VisMed_Ciclo__c/VisMed_Ciclo__c.object-meta.xml
<CustomObject>
    <label>Ciclo</label>
    <nameField>
        <label>Ciclo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Sub_Equipo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Adultos Interior</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos Oncologia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos</fullName>
    </customValue>
    <customValue>
        <fullName>Dieta</fullName>
    </customValue>
    <customValue>
        <fullName>Pediatricos General</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos AMBA</fullName>
    </customValue>
    <customValue>
        <fullName>Metabólicos y Dieta</fullName>
    </customValue>
    <customValue>
        <fullName>Nicho MSL</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos General</fullName>
        <isActive>false</isActive>
        <label>Adultos General</label>
    </customValue>
    <masterLabel>Sub Equipo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/StockDataLoaderControllerTest.cls
@IsTest
public class StockDataLoaderControllerTest {
    @TestSetup
    static void makeData(){
        Product2 product = Build.aProduct()
        .withName('Producto Test')
        .withUnidadesBulto(15)            
        .withIsActive(true)
        .withIdSap('106959')
        .build();
        insert product;

        Account institucion = Build.anAccount()
            .withName('InstitucionTest')
            .build();
        insert institucion;

        Id recordTypeVisitadorMedico = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Visitador_Medico').getRecordTypeId();
        Contact apm = Build.aContactVisitadorMedico()
            .withAccount(institucion)            
            .build();
        apm.VisMed_DNI__c = '22222333';
        apm.RecordTypeId = recordTypeVisitadorMedico;
        apm.Sub_Equipo__c = 'Metabólicos y Dieta';
        insert apm;

        Date today = Date.today();
            VisMed_Ciclo__c ciclo = Build.aCiclo()
            .withFechaInicio(today.toStartOfMonth())
            .withFechaFin(today.toStartOfMonth().addMonths(1).addDays(-1))
            .build();
            insert ciclo;

        Stock_x_Ciclo__c stockXCiclo = Build.aStockXCiclo()
            .withAPM(apm)
            .withCiclo(ciclo)
            .build();
        insert stockXCiclo;

        Stock_x_MM__c stockMM = Build.aStockMMCiclo()
            .withCiclo(stockXCiclo)
            .withProduct(product)
            .withQuantity(50)
            .build();
        insert stockMM;
    }

    @IsTest
    public static void ValidateCicloHeaderError(){
        Stock_x_MM__c stocXMM = [
            SELECT id,Stock_x_Ciclo__r.APM__c,
             Stock_x_Ciclo__r.Ciclo__c, Muestra_Medica__c 
            FROM Stock_x_MM__c
            limit 1
        ];
        String data = 'hola,Producto,APM,Cantidad\r\n'+stocXMM.Stock_x_Ciclo__r.Ciclo__c+','+stocXMM.Muestra_Medica__c+','+stocXMM.Stock_x_Ciclo__r.APM__c+',4';
        Test.startTest();
        ServerResponse response = StockDataLoaderController.saveData(data);
        Test.stopTest();

        system.assertEquals(true, response.errors.containsKey('[Ln: 0, Col: 0]'));
        system.assertEquals('Cabecero no válido [Esperado: Ciclo, Actual: hola].',response.errors.get('[Ln: 0, Col: 0]'));
    }

    @IsTest
    public static void ValidateProductoHeaderError(){
        Stock_x_MM__c stocXMM = [
            SELECT id,Stock_x_Ciclo__r.APM__c,
             Stock_x_Ciclo__r.Ciclo__c, Muestra_Medica__c 
            FROM Stock_x_MM__c
            limit 1
        ];
        String data = 'Ciclo,hola,APM,Cantidad\r\n'+stocXMM.Stock_x_Ciclo__r.Ciclo__c+','+stocXMM.Muestra_Medica__c+','+stocXMM.Stock_x_Ciclo__r.APM__c+',4';
        Test.startTest();
        ServerResponse response = StockDataLoaderController.saveData(data);
        Test.stopTest();

        system.assertEquals(true, response.errors.containsKey('[Ln: 0, Col: 1]'));
        system.assertEquals('Cabecero no válido [Esperado: Producto, Actual: hola].',response.errors.get('[Ln: 0, Col: 1]'));
    }

    @IsTest
    public static void ValidateAPMHeaderError(){
        Stock_x_MM__c stocXMM = [
            SELECT id,Stock_x_Ciclo__r.APM__c,
             Stock_x_Ciclo__r.Ciclo__c, Muestra_Medica__c 
            FROM Stock_x_MM__c
            limit 1
        ];
        String data = 'Ciclo,Producto,hola,Cantidad\r\n'+stocXMM.Stock_x_Ciclo__r.Ciclo__c+','+stocXMM.Muestra_Medica__c+','+stocXMM.Stock_x_Ciclo__r.APM__c+',4';
        Test.startTest();
        ServerResponse response = StockDataLoaderController.saveData(data);
        Test.stopTest();

        system.assertEquals(true, response.errors.containsKey('[Ln: 0, Col: 2]'));
        system.assertEquals('Cabecero no válido [Esperado: APM, Actual: hola].',response.errors.get('[Ln: 0, Col: 2]'));
    }

    @IsTest
    public static void ValidateCantidadHeaderError(){
        Stock_x_MM__c stocXMM = [
            SELECT id,Stock_x_Ciclo__r.APM__c,
             Stock_x_Ciclo__r.Ciclo__c, Muestra_Medica__c 
            FROM Stock_x_MM__c
            limit 1
        ];
        String data = 'Ciclo,Producto,APM,hola\r\n'+stocXMM.Stock_x_Ciclo__r.Ciclo__c+','+stocXMM.Muestra_Medica__c+','+stocXMM.Stock_x_Ciclo__r.APM__c+',4';
        Test.startTest();
        ServerResponse response = StockDataLoaderController.saveData(data);
        Test.stopTest();

        system.assertEquals(true, response.errors.containsKey('[Ln: 0, Col: 3]'));
        system.assertEquals('Cabecero no válido [Esperado: Cantidad, Actual: hola].',response.errors.get('[Ln: 0, Col: 3]'));
    }

    @IsTest
    public static void ValidateDataEmptyError(){
        Stock_x_MM__c stocXMM = [
            SELECT id,Stock_x_Ciclo__r.APM__c,
             Stock_x_Ciclo__r.Ciclo__c, Muestra_Medica__c 
            FROM Stock_x_MM__c
            limit 1
        ];
        String data = '';
        Test.startTest();
        ServerResponse response = StockDataLoaderController.saveData(data);
        Test.stopTest();

        system.assertEquals(true, response.errors.containsKey('[Ln: 0, Col: 0]'));
        system.assertEquals('Contenido vacío.',response.errors.get('[Ln: 0, Col: 0]'));
    }

    @IsTest
    public static void ValidateCorrectData(){
        Stock_x_MM__c stocXMM = [
            SELECT id,Stock_x_Ciclo__r.APM__c,
             Stock_x_Ciclo__r.Ciclo__c, Muestra_Medica__c 
            FROM Stock_x_MM__c
            limit 1
        ];
        String data = 'Ciclo,Producto,APM,Cantidad\r\n'+stocXMM.Stock_x_Ciclo__r.Ciclo__c+','+stocXMM.Muestra_Medica__c+','+stocXMM.Stock_x_Ciclo__r.APM__c+',4';
        Test.startTest();
        ServerResponse response = StockDataLoaderController.saveData(data);
        Test.stopTest();

        List<StockDataLoaderController.StockWrapper> sw = (List<StockDataLoaderController.StockWrapper>)response.data;
        system.debug(sw);
        System.assertEquals(stocXMM.Stock_x_Ciclo__r.APM__c ,sw.get(0).contactId,'Error en la data');
        System.assertEquals(stocXMM.Stock_x_Ciclo__r.Ciclo__c ,sw.get(0).cycleId,'Error en la data');
        System.assertEquals(stocXMM.Muestra_Medica__c ,sw.get(0).productId,'Error en la data');
        System.assertEquals('4' ,sw.get(0).quantity,'Error en la data');
    }
    @IsTest
    public static void ValidateCorrectDataWithoutCycle(){
        Product2 product = Build.aProduct()
        .withName('Producto Test')
        .withUnidadesBulto(15)            
        .withIsActive(true)
        .withIdSap('106958')
        .build();
        insert product;

        Account institucion = Build.anAccount()
            .withName('InstitucionTest')
            .build();
        insert institucion;

        Id recordTypeVisitadorMedico = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Visitador_Medico').getRecordTypeId();
        Contact apm = Build.aContactVisitadorMedico()
            .withAccount(institucion)            
            .build();
        apm.VisMed_DNI__c = '22222333';
        apm.RecordTypeId = recordTypeVisitadorMedico;
        apm.Sub_Equipo__c = 'Metabólicos y Dieta';
        insert apm;

        Date today = Date.today();
            VisMed_Ciclo__c ciclo = Build.aCiclo()
            .withFechaInicio(today.toStartOfMonth().addMonths(1))
            .withFechaFin(today.toStartOfMonth().addMonths(2).addDays(-1))
            .build();
            insert ciclo;
        String data = 'Ciclo,Producto,APM,Cantidad\r\n'+ciclo.Id+','+product.Id+','+apm.Id+',4';
        Test.startTest();
        ServerResponse response = StockDataLoaderController.saveData(data);
        Test.stopTest();

        List<StockDataLoaderController.StockWrapper> sw = (List<StockDataLoaderController.StockWrapper>)response.data;
        system.debug(sw);
        System.assertEquals(apm.Id,sw.get(0).contactId,'Error en la data');
        System.assertEquals(ciclo.Id ,sw.get(0).cycleId,'Error en la data');
        System.assertEquals(product.Id,sw.get(0).productId,'Error en la data');
        System.assertEquals('4' ,sw.get(0).quantity,'Error en la data');
    }

    @IsTest
    public static void ValidateCorrectWIthoutstocXMMData(){
        Stock_x_MM__c stocXMM = [
            SELECT id,Stock_x_Ciclo__r.APM__c,
             Stock_x_Ciclo__r.Ciclo__c, Muestra_Medica__c 
            FROM Stock_x_MM__c
            limit 1
        ];
        String data = 'Ciclo,Producto,APM,Cantidad\r\n'+stocXMM.Stock_x_Ciclo__r.Ciclo__c+','+stocXMM.Muestra_Medica__c+','+stocXMM.Stock_x_Ciclo__r.APM__c+',4';
        
        delete stocXMM;
        Test.startTest();
        ServerResponse response = StockDataLoaderController.saveData(data);
        Test.stopTest();

        List<StockDataLoaderController.StockWrapper> sw = (List<StockDataLoaderController.StockWrapper>)response.data;
        system.debug(sw);
        System.assertEquals(stocXMM.Stock_x_Ciclo__r.APM__c ,sw.get(0).contactId,'Error en la data');
        System.assertEquals(stocXMM.Stock_x_Ciclo__r.Ciclo__c ,sw.get(0).cycleId,'Error en la data');
        System.assertEquals(stocXMM.Muestra_Medica__c ,sw.get(0).productId,'Error en la data');
        System.assertEquals('4' ,sw.get(0).quantity,'Error en la data');
    }


    /*@IsTest
    public static void ValidateCicloEmpty(){
        Stock_x_MM__c stocXMM = [
            SELECT id,Stock_x_Ciclo__r.APM__c,
             Stock_x_Ciclo__r.Ciclo__c, Muestra_Medica__c 
            FROM Stock_x_MM__c
            limit 1
        ];
        String data = 'Ciclo,Producto,APM,Cantidad\r\n,'+stocXMM.Muestra_Medica__c+','+stocXMM.Stock_x_Ciclo__r.APM__c+',4';
        Test.startTest();
        ServerResponse response = StockDataLoaderController.saveData(data);
        Test.stopTest();

        system.debug(response);
    }*/
}