force-app/main/default/objects/Account/recordTypes/Institucion.recordType-meta.xml
<RecordType>
    <fullName>Institucion</fullName>
    <active>true</active>
    <label>Institución</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Sub_Equipo__c.field-meta.xml
<CustomField>
    <fullName>Sub_Equipo__c</fullName>
    <label>Sub Equipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Equipo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/VisMed_DNI__c.field-meta.xml
<CustomField>
    <fullName>VisMed_DNI__c</fullName>
    <label>DNI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Visitador_medico.recordType-meta.xml
<RecordType>
    <fullName>Visitador_medico</fullName>
    <active>true</active>
    <label>Visitador médico</label>
</RecordType>

force-app/main/default/objects/User/fields/Segmenta_Por__c.field-meta.xml
<CustomField>
    <fullName>Segmenta_Por__c</fullName>
    <label>Segmenta Por</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Metabolicos</fullName>
            </value>
            <value>
                <fullName>Epilepsia</fullName>
            </value>
            <value>
                <fullName>Metabolicos y Epilepsia</fullName>
            </value>
            <value>
                <fullName>Pediatricos</fullName>
            </value>
            <value>
                <fullName>Alergia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sub_Equipo__c.field-meta.xml
<CustomField>
    <fullName>Sub_Equipo__c</fullName>
    <label>Sub Equipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Equipo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/VisMed_ContrasenaApp__c.field-meta.xml
<CustomField>
    <fullName>VisMed_ContrasenaApp__c</fullName>
    <label>Contraseña App</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/VisMed_Ciclo__c/VisMed_Ciclo__c.object-meta.xml
<CustomObject>
    <label>Ciclo</label>
    <nameField>
        <label>Ciclo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/VisMed_Contacto_Cuenta_Usuario__c.object-meta.xml
<CustomObject>
    <description>Relacion de APM con el profesional y su lugar de trabajo</description>
    <label>Fichero</label>
    <nameField>
        <displayFormat>SEG-{0000}</displayFormat>
        <label>Seguimiento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ficheros</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Seguimientos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Segmenta_Por__c.field-meta.xml
<CustomField>
    <fullName>Segmenta_Por__c</fullName>
    <label>Segmenta Por</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Segmenta_Por</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/VisMed_Segmentacion__c.object-meta.xml
<CustomObject>
    <label>Segmentación</label>
    <nameField>
        <displayFormat>Segmentacion-{0000}</displayFormat>
        <label>Segmentación Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <formula>IF(
  OR(
    RecordType.Name =&apos;Metabolicos&apos;,
    RecordType.Name =&apos;Epilepsia&apos;,
    RecordType.Name =&apos;Metabolicos_y_Epilepsia&apos;
  ),
  Categoria_Nicho__c,
  IF(
    OR(
      RecordType.Name =&apos;Alergia&apos;,
      RecordType.Name =&apos;Pediatricos&apos;,
      RecordType.Name =&apos;Pediatricos General&apos;
    ),
    Categoria_Ped_Aler__c,
    Categoria_Nicho__c
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Categoria</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profesional de la Salud, Otro Profesional</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segmentaciones</relationshipLabel>
    <relationshipName>Segmentaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/recordTypes/Metabolicos.recordType-meta.xml
<RecordType>
    <fullName>Metabolicos</fullName>
    <active>true</active>
    <label>Metabolicos</label>
</RecordType>

force-app/main/default/objects/VisMed_Segmentacion__c/recordTypes/Pediatricos.recordType-meta.xml
<RecordType>
    <fullName>Pediatricos</fullName>
    <active>true</active>
    <label>Pediatricos</label>
</RecordType>

force-app/main/default/objects/VisMed_Segmentacion__c/recordTypes/Pediatricos_General.recordType-meta.xml
<RecordType>
    <fullName>Pediatricos_General</fullName>
    <active>true</active>
    <label>Pediatricos General</label>
</RecordType>

force-app/main/default/globalValueSets/Segmenta_Por.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Adultos General Institucion</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos General Comunidad</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos Oncologia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos y Epilepsia</fullName>
    </customValue>
    <customValue>
        <fullName>Pediatricos General</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia</fullName>
    </customValue>
    <masterLabel>Segmenta Por</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sub_Equipo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Adultos Interior</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos Oncologia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos</fullName>
    </customValue>
    <customValue>
        <fullName>Dieta</fullName>
    </customValue>
    <customValue>
        <fullName>Pediatricos General</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos AMBA</fullName>
    </customValue>
    <customValue>
        <fullName>Metabólicos y Dieta</fullName>
    </customValue>
    <customValue>
        <fullName>Nicho MSL</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos General</fullName>
        <isActive>false</isActive>
        <label>Adultos General</label>
    </customValue>
    <masterLabel>Sub Equipo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchUpdateFicheroCategoryTest.cls
@isTest
public class BatchUpdateFicheroCategoryTest {
    @TestSetup
    static void makeData(){
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile profile1 = [Select Id from Profile where Name = 'System Administrator' or name = 'Administrador del sistema' ];
    
        User userOwner = Build.aUser()
                .withUsername(
                    'newuser'+String.valueOf(System.now().getTime() + (Math.random() * 10))+'@testorg.com'
                )               
                .withEmail('owner@xappia.com')
                .withAlias('owner')
                .withLastName('Owner')
                .withTimeZoneSidKey('America/Argentina/Buenos_Aires')
                .withLocaleSidKey('es_AR')
                .withCommunityNickname('prueba2.xappia')
                .withEmailEncodingKey('ISO-8859-1')
                .withProfileId(profile1.Id)
                .withUserRoleId(portalRole)				
                .withLanguageLocaleKey('es')
                .build();           
        userOwner.ManagerId = UserInfo.getUserId();
        userOwner.IsActive = true;
        userOwner.VisMed_ContrasenaApp__c = 'TestOwner';
        insert userOwner;
    
        System.runAs(userOwner){
            Account institucion = Build.anAccount()
                .withName('InstitucionTest')
                .build();
            insert institucion;
        
            Id recordTypeVisitadorMedico = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Visitador_Medico').getRecordTypeId();
            Contact apm = Build.aContactVisitadorMedico()
            .withAccount(institucion)            
            .build();
            apm.VisMed_DNI__c = '22222333';
            apm.RecordTypeId = recordTypeVisitadorMedico;
            apm.Sub_Equipo__c = 'Metabolicos';
            insert apm;
            
            Profile perfilApm = [SELECT Id FROM Profile WHERE Name = 'APM' LIMIT 1];

            User userTest = Build.aUser()
            .withUsername(
                'newuser'+String.valueOf(System.now().getTime() + (Math.random() * 10))+'@testorg.com'
            )
            .withContactId(apm)
            .withLastName('Contacto1')
            .withEmail('contacto1@xappia.com')
            .withAlias('contact1')
            .withTimeZoneSidKey('America/Argentina/Buenos_Aires')
            .withLocaleSidKey('es_AR')
            .withCommunityNickname('prueba1.xappia')
            .withEmailEncodingKey('ISO-8859-1')
            .withProfileId(perfilApm.Id)
            .withLanguageLocaleKey('es')
            .build();

            userTest.IsActive = true;
            userTest.VisMed_ContrasenaApp__c = 'Test';
            userTest.ManagerId = userOwner.Id;
            userTest.DelegatedApproverId = userOwner.Id;

            insert userTest;


            Date today = Date.today();
            VisMed_Ciclo__c ciclo = Build.aCiclo()
            .withFechaInicio(today.toStartOfMonth())
            .withFechaFin(today.toStartOfMonth().addMonths(1).addDays(-1))
            .build();
            insert ciclo;

            Id recordTypeProfesional = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Profesional_de_la_Salud').getRecordTypeId();
            Account aPersonAccount = Build.aPersonalAccount()
            .withFirstName('Profesional')
            .withProfesionalActivo(true)
            .build();
            aPersonAccount.LastName = 'Test';
            aPersonAccount.RecordTypeId = recordTypeProfesional;
            insert aPersonAccount;

            VisMed_Contacto_Cuenta_Usuario__c seg = Build.aVisMedContactCuentaUsuarioBuilder()
                .withAPM(apm)
                .withInstitucion(institucion)
                .withProfesional(aPersonAccount)
                .withSegmentaPor('Pediatricos General')
                .withEstado('Activo')
                .build();
            seg.Categoria__c = 'C';
            insert seg;

            Id recordTypPediatricosGeneral = Schema.SObjectType.VisMed_Segmentacion__c.getRecordTypeInfosByDeveloperName().get('Pediatricos_General').getRecordTypeId();
            VisMed_Segmentacion__c segmentacion = new VisMed_Segmentacion__c(
                Profesional__c = aPersonAccount.Id,
                RecordTypeId = recordTypPediatricosGeneral
            );
            insert segmentacion; 
        }
    }

    @isTest
    public static void ifProfesionalCategoryChangeFicheroMustUpdate(){
        List<VisMed_Segmentacion__c> segmentacion = [SELECT ID, Categoria__c, Profesional__c, Frecuencia__c FROM VisMed_Segmentacion__c];
        List<VisMed_Contacto_Cuenta_Usuario__c> fichero = [SELECT ID, Categoria__c, Profesional__c, Segmenta_Por__c FROM VisMed_Contacto_Cuenta_Usuario__c];
        String categoriaAnterior = fichero[0].Categoria__c;
        System.debug('categoriaAnterior');
        System.debug(categoriaAnterior);
        System.debug('segmentacion');
        System.debug(segmentacion);
        System.debug('fichero');
        System.debug(fichero);
        Test.startTest();
            BatchUpdateFicheroCategory batch = new BatchUpdateFicheroCategory();
            Database.executeBatch(batch);
        Test.stopTest();

        List<VisMed_Contacto_Cuenta_Usuario__c> ficheroUpdateado = [SELECT ID, Categoria__c, Profesional__c, Segmenta_Por__c FROM VisMed_Contacto_Cuenta_Usuario__c];
        System.assertEquals('D', ficheroUpdateado[0].Categoria__c, 'No se actualizo la categoria.');
    }
}