force-app/main/default/objects/Account/recordTypes/Institucion.recordType-meta.xml
<RecordType>
    <fullName>Institucion</fullName>
    <active>true</active>
    <label>Institución</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Sub_Equipo__c.field-meta.xml
<CustomField>
    <fullName>Sub_Equipo__c</fullName>
    <label>Sub Equipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Equipo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/VisMed_DNI__c.field-meta.xml
<CustomField>
    <fullName>VisMed_DNI__c</fullName>
    <label>DNI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Visitador_medico.recordType-meta.xml
<RecordType>
    <fullName>Visitador_medico</fullName>
    <active>true</active>
    <label>Visitador médico</label>
</RecordType>

force-app/main/default/objects/User/fields/Sub_Equipo__c.field-meta.xml
<CustomField>
    <fullName>Sub_Equipo__c</fullName>
    <label>Sub Equipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Equipo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/VisMed_ContrasenaApp__c.field-meta.xml
<CustomField>
    <fullName>VisMed_ContrasenaApp__c</fullName>
    <label>Contraseña App</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/VisMed_Accion__c/VisMed_Accion__c.object-meta.xml
<CustomObject>
    <description>Objeto que contendrá las acciones que se cargan a cada objeto.</description>
    <label>Acción</label>
    <nameField>
        <label>Nombre de Acción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Accion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Accion__c/fields/VisMed_FechaInicio__c.field-meta.xml
<CustomField>
    <fullName>VisMed_FechaInicio__c</fullName>
    <description>Campo que determina cuando debería empezar a trabajarse la acción.</description>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_Accion__c/fields/VisMed_Objetivo__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Objetivo__c</fullName>
    <description>Objetivo al que se relaciona la acción.</description>
    <label>Objetivo</label>
    <referenceTo>VisMed_Objetivo__c</referenceTo>
    <relationshipLabel>Acciones</relationshipLabel>
    <relationshipName>Acciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VisMed_AccionPorCuenta__c/VisMed_AccionPorCuenta__c.object-meta.xml
<CustomObject>
    <description>Objeto que contendrá las acciones correspondientes a un objetivo, relacionadas a un profesional o Institución.</description>
    <label>Acción por cuenta</label>
    <nameField>
        <displayFormat>AccXObj-{0000}</displayFormat>
        <label>Nombre de Acción por profesional</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acciones por cuenta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_AccionPorCuenta__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_AccionPorCuenta__c/fields/VisMed_Accion__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Accion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Acción</label>
    <referenceTo>VisMed_Accion__c</referenceTo>
    <relationshipLabel>Acciones por cuenta</relationshipLabel>
    <relationshipName>Acciones_por_cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_AccionPorCuenta__c/fields/VisMed_Objetivo__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Objetivo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objetivo</label>
    <referenceTo>VisMed_Objetivo__c</referenceTo>
    <relationshipLabel>Acciones por cuenta</relationshipLabel>
    <relationshipName>Acciones_por_cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_AccionPorCuenta__c/fields/VisMed_ObjetivoPorCuenta__c.field-meta.xml
<CustomField>
    <fullName>VisMed_ObjetivoPorCuenta__c</fullName>
    <label>Objetivo por cuenta</label>
    <referenceTo>VisMed_ObjetivoPorCuenta__c</referenceTo>
    <relationshipLabel>Acciones por cuenta</relationshipLabel>
    <relationshipName>Acciones_por_cuenta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VisMed_Objetivo__c/VisMed_Objetivo__c.object-meta.xml
<CustomObject>
    <description>Objeto en el que se cargarán los objetivos que deberán cumplir los APM.</description>
    <label>Objetivo</label>
    <nameField>
        <label>Nombre de Objetivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objetivos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Objetivo__c/fields/VisMed_FechaInicio__c.field-meta.xml
<CustomField>
    <fullName>VisMed_FechaInicio__c</fullName>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_ObjetivoPorCuenta__c/VisMed_ObjetivoPorCuenta__c.object-meta.xml
<CustomObject>
    <description>Objeto que relacionará el profesional o la institución con el objetivo.</description>
    <label>Objetivo por cuenta</label>
    <nameField>
        <displayFormat>ObjXCue-{0000}</displayFormat>
        <label>Nombre de Objetivo por cuenta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objetivos por cuenta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_ObjetivoPorCuenta__c/fields/VisMed_FechaInicio__c.field-meta.xml
<CustomField>
    <fullName>VisMed_FechaInicio__c</fullName>
    <formula>VisMed_Objetivo__r.VisMed_FechaInicio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_ObjetivoPorCuenta__c/fields/VisMed_Objetivo__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Objetivo__c</fullName>
    <label>Objetivo</label>
    <referenceTo>VisMed_Objetivo__c</referenceTo>
    <relationshipLabel>Objetivos por cuenta</relationshipLabel>
    <relationshipName>Objetivos_por_cuenta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Sub_Equipo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Adultos Interior</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos Oncologia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos</fullName>
    </customValue>
    <customValue>
        <fullName>Dieta</fullName>
    </customValue>
    <customValue>
        <fullName>Pediatricos General</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos AMBA</fullName>
    </customValue>
    <customValue>
        <fullName>Metabólicos y Dieta</fullName>
    </customValue>
    <customValue>
        <fullName>Nicho MSL</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos General</fullName>
        <isActive>false</isActive>
        <label>Adultos General</label>
    </customValue>
    <masterLabel>Sub Equipo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccionTriggerHelperTest.cls
@IsTest 
public class AccionTriggerHelperTest {
   @testSetup
   public static void testSetup() {
    UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile profile1 = [Select Id from Profile where Name = 'System Administrator' or name = 'Administrador del sistema' ];
    
        User userOwner = Build.aUser()
                .withUsername(
                    'newuser'+String.valueOf(System.now().getTime() + (Math.random() * 10))+'@testorg.com'
                )               
                .withEmail('owner@xappia.com')
                .withAlias('owner')
                .withLastName('Owner')
                .withTimeZoneSidKey('America/Argentina/Buenos_Aires')
                .withLocaleSidKey('es_AR')
                .withCommunityNickname('prueba2.xappia')
                .withEmailEncodingKey('ISO-8859-1')
                .withProfileId(profile1.Id)
                .withUserRoleId(portalRole)				
                .withLanguageLocaleKey('es')
                .build();           
        userOwner.ManagerId = UserInfo.getUserId();
        userOwner.IsActive = true;
        userOwner.VisMed_ContrasenaApp__c = 'TestOwner';
        insert userOwner;
    
        System.runAs(userOwner){
            Account institucion = Build.anAccount()
                .withName('InstitucionTest')
                .build();
            insert institucion;
        
            Id recordTypeVisitadorMedico = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Visitador_Medico').getRecordTypeId();
            Contact apm = Build.aContactVisitadorMedico()
            .withAccount(institucion)            
            .build();
            apm.VisMed_DNI__c = '22222333';
            apm.RecordTypeId = recordTypeVisitadorMedico;
            apm.Sub_Equipo__c = 'Metabólicos y Dieta';
            insert apm;

            VisMed_Objetivo__c obj = Build.aVisMedObjetivo()
                .withName('Objetivo Test')
                .withVisMedFechaInicio(Date.today().toStartOfMonth())
                .withVisMedFechaFin(Date.Today().addMonths(3))
                .build();
            insert obj;

            VisMed_Accion__c accion = Build.aVisMedAccion()
                .withVisMedObjetivo(obj)
                .withVisMedFechaInicio(Date.today().addDays(4))
                .withVisMedFechaFin(Date.today().addDays(30))        
                .build();
            insert accion;
            
            VisMed_ObjetivoPorCuenta__c objXCuenta = Build.aVisMedObjetivoPorCuenta()
                .withVisMedObjetivo(obj)
                .withVisMedAPM(userOwner)
                .build();
            insert objXCuenta;

            VisMed_AccionPorCuenta__c accionPorCuenta = Build.aVisMedAccionPorCuenta()
                .withVisMedObjetivo(obj)
                .withVisMedObjetivoPorCuenta(objXCuenta)
                .withVisMedAccion(accion)
                .withVisMedAPM(userOwner)
                .build();
            insert accionPorCuenta;
        }
   }

   @IsTest
   public static void cuandoSeCreaAccionSeDebeSetearElCampoEstadoSegunLasFechasEnActivo(){
    
    VisMed_Objetivo__c obj = Build.aVisMedObjetivo()
        .withName('Objetivo Test')
        .withVisMedFechaInicio(Date.today().toStartOfMonth())
        .withVisMedFechaFin(Date.Today().addMonths(3))
        .build();
    insert obj;
        
    VisMed_Accion__c accion = Build.aVisMedAccion()
        .withVisMedObjetivo(obj)
        .withVisMedFechaInicio(Date.today())
        .withVisMedFechaFin(Date.today().addDays(30))        
        .build();
    
    Test.startTest();    
    insert accion;
    Test.stopTest();
    VisMed_Accion__c accToCompare = [
        SELECT Id, Estado__c
        FROM VisMed_Accion__c
        WHERE Id = :accion.Id
    ];
    System.assertEquals('Activo', accToCompare.Estado__c, 'Error al activar accion');
   }
    @IsTest
   public static void cuandoSeModificaAccionSeDebeSetearElCampoEstadoSegunLasFechasEnActivo(){
    
    VisMed_Accion__c accion = [
        SELECT Id, VisMed_FechaInicio__c, Estado__c
        FROM VisMed_Accion__c
        WHERE VisMed_FechaInicio__c = :Date.today().addDays(4)
    ];

    accion.VisMed_FechaInicio__c = Date.Today();
        
    Test.startTest();    
    update accion;
    Test.stopTest();
    VisMed_Accion__c accToCompare = [
        SELECT Id, Estado__c
        FROM VisMed_Accion__c
        WHERE Id = :accion.Id
    ];
    System.assertEquals('Activo', accToCompare.Estado__c, 'Error al activar accion');
   }
    @IsTest
   public static void cuandoSeCreaAccionSeDebeSetearElCampoEstadoSegunLasFechasEnInactivo(){
    
    VisMed_Objetivo__c obj = Build.aVisMedObjetivo()
        .withName('Objetivo Test')
        .withVisMedFechaInicio(Date.today().toStartOfMonth())
        .withVisMedFechaFin(Date.Today().addMonths(3))
        .build();
    insert obj;
        
    VisMed_Accion__c accion = Build.aVisMedAccion()
        .withVisMedObjetivo(obj)
        .withVisMedFechaInicio(Date.today().addDays(3))
        .withVisMedFechaFin(Date.today().addDays(30))        
        .build();
    
    Test.startTest();    
    insert accion;
    Test.stopTest();
    VisMed_Accion__c accToCompare = [
        SELECT Id, Estado__c
        FROM VisMed_Accion__c
        WHERE Id = :accion.Id
    ];
    System.assertEquals('Inactivo', accToCompare.Estado__c, 'Error al activar accion');
   }
    @IsTest
   public static void cuandoSeModificaAccionSeDebeSetearElCampoEstadoSegunLasFechasEnInactivo(){
    
    VisMed_Accion__c accion = [
        SELECT Id, VisMed_FechaInicio__c, Estado__c
        FROM VisMed_Accion__c
        WHERE VisMed_FechaInicio__c = :Date.today().addDays(4)
    ];

    accion.VisMed_FechaInicio__c = Date.Today().addDays(1);
        
    Test.startTest();    
    update accion;
    Test.stopTest();
    VisMed_Accion__c accToCompare = [
        SELECT Id, Estado__c
        FROM VisMed_Accion__c
        WHERE Id = :accion.Id
    ];
    System.assertEquals('Inactivo', accToCompare.Estado__c, 'Error al activar accion');
   }
    @IsTest
   public static void cuandoSeModificaAccionSiEstadoEsActivoDebeActivarElObjetivoXCuenta(){
    
    VisMed_Objetivo__c obj = [
        SELECT Id, Estado__c
        FROM VisMed_Objetivo__c
        WHERE VisMed_FechaInicio__c = :Date.today().toStartOfMonth()
    ];    
    obj.Estado__c = 'Activo';
    
    Test.startTest();
    update obj;
    Test.stopTest();
    VisMed_ObjetivoPorCuenta__c objXCuenta = [
        SELECT Id, Estado__c
        FROM VisMed_ObjetivoPorCuenta__c
        WHERE VisMed_Objetivo__c = :obj.Id
    ];
    System.assertEquals('Activo', objXCuenta.Estado__c, 'Error al activar objetivo por cuenta');
   }

   @IsTest
   public static void cuandoSeModificaAccionSiEstadoEsActivoDebeActivarLaAccionXCuenta(){
    
    VisMed_Accion__c accion = [
        SELECT Id, VisMed_FechaInicio__c, Estado__c
        FROM VisMed_Accion__c
        WHERE VisMed_FechaInicio__c = :Date.today().addDays(4)
    ];

    accion.VisMed_FechaInicio__c = Date.today();
    accion.Estado__c = 'Activo';
    
    Test.startTest();
    update accion;
    Test.stopTest();
    List<VisMed_AccionPorCuenta__c> accionXCuenta = [
        SELECT Id, Estado__c
        FROM VisMed_AccionPorCuenta__c
        WHERE VisMed_Accion__c = :accion.Id
    ];
    System.assertEquals('Activo', accionXCuenta.get(0).Estado__c, 'Error al activar accion');
   }
   @IsTest
   public static void cuandoSeModificaAccionSiEstadoEsInactivoDebeInactivarLaAccionXCuenta(){
    
    VisMed_Accion__c accion = [
        SELECT Id, VisMed_FechaInicio__c, Estado__c
        FROM VisMed_Accion__c
        WHERE VisMed_FechaInicio__c = :Date.today().addDays(4)
    ];

    accion.VisMed_FechaInicio__c = Date.today().addDays(6);
    accion.Estado__c = 'Inactivo';
    
    Test.startTest();
    update accion;
    Test.stopTest();
    List<VisMed_AccionPorCuenta__c> accionXCuenta = [
        SELECT Id, Estado__c
        FROM VisMed_AccionPorCuenta__c
        WHERE VisMed_Accion__c = :accion.Id
    ];

    system.debug(accionXCuenta);
    System.assertEquals('Inactivo', accionXCuenta.get(0).Estado__c, 'Error al activar accion');
   }


    @IsTest
    public static void validateWhenInsert(){

        VisMed_Objetivo__c obj = [
            SELECT id
            FROM VisMed_Objetivo__c
            LIMIT 1
        ];

        VisMed_Accion__c accion = Build.aVisMedAccion()
            .withVisMedObjetivo(obj)
            .withVisMedFechaInicio(Date.today().addDays(4))
            .withVisMedFechaFin(Date.today().addDays(30))        
            .build();
        
        test.startTest();
        insert accion;
        test.stopTest();

        List<VisMed_AccionPorCuenta__c> listAccionXCuenta = [
            SELECT Id
            FROM VisMed_AccionPorCuenta__c
            WHERE VisMed_Accion__c = :accion.Id
        ];

        system.assertEquals(1, listAccionXCuenta.size());

    }
}