force-app/main/default/objects/Dan360_Account_Team_Management__c/Dan360_Account_Team_Management__c.object-meta.xml
<CustomObject>
    <description>Objeto creado para poder dar de alta usuarios en Account Team Members y que pase por un proceso de aprobacion.</description>
    <label>Account Team Management</label>
    <nameField>
        <label>Dan360 Account Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Team Management</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Account_Team_Management__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Profesional el cual se pidio visitar por el APM</description>
    <label>Profesional</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team Management</relationshipLabel>
    <relationshipName>Account_Team_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Account_Team_Management__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
                <isActive>false</isActive>
                <label>Aprovado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Account_Team_Management__c/fields/TeamMemberRole__c.field-meta.xml
<CustomField>
    <fullName>TeamMemberRole__c</fullName>
    <label>TeamMemberRole</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Lead Qualifier</fullName>
            </value>
            <value>
                <fullName>Pre-Sales Consultant</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Account_Team_Management__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>APM que pidio el alta para poder visitar al profesional.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Team_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountTeamManagementTriggerHelper.cls
public class AccountTeamManagementTriggerHelper {

    public static void insertAccountTeamMember(List<Dan360_Account_Team_Management__c> atms) {
        List<AccountTeamMember> members = New List<AccountTeamMember>();
        for (Dan360_Account_Team_Management__c atm : atms) {            
            if (atm.Estado__c == 'Aprobado') {
                AccountTeamMember member = new AccountTeamMember(
                    AccountId = atm.Account__c,
                    UserId = atm.User__c,
                    TeamMemberRole = atm.TeamMemberRole__c
                );
                members.add(member);
            }            
        }
        insert members;
    }

}