force-app/main/default/objects/LVC_Delivery__c/LVC_Delivery__c.object-meta.xml
<CustomObject>
    <label>Fletero</label>
    <nameField>
        <label>Fletero</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleteros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_Delivery__c/fields/Friday__c.field-meta.xml
<CustomField>
    <fullName>Friday__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Viernes</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LVC_Delivery__c/fields/Monday__c.field-meta.xml
<CustomField>
    <fullName>Monday__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lunes</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LVC_Delivery__c/fields/Saturday__c.field-meta.xml
<CustomField>
    <fullName>Saturday__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sabado</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LVC_Delivery__c/fields/Sunday__c.field-meta.xml
<CustomField>
    <fullName>Sunday__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Domingo</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LVC_Delivery__c/fields/Thursday__c.field-meta.xml
<CustomField>
    <fullName>Thursday__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Jueves</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LVC_Delivery__c/fields/Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Tuesday__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Martes</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LVC_Delivery__c/fields/Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Wednesday__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Miercoles</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/LVC_DeliveryRoute__c.object-meta.xml
<CustomObject>
    <label>Ruta de Reparto</label>
    <nameField>
        <displayFormat>DR-{00000000}</displayFormat>
        <label>LVC_DeliveryRoute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ruta de Reparto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fletero Id</label>
    <referenceTo>LVC_Delivery__c</referenceTo>
    <relationshipLabel>Ruta de Reparto</relationshipLabel>
    <relationshipName>DeliveryRoutes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/DeliveryRouteExternalId__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRouteExternalId__c</fullName>
    <label>Delivery Route External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/DeliverySchedule__c.field-meta.xml
<CustomField>
    <fullName>DeliverySchedule__c</fullName>
    <label>Horario Entrega</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Mañana 08:00 a 13:00</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Día 09:00 a 16:00</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Mañana 08:00 a 11:00</label>
            </value>
            <value>
                <fullName>T</fullName>
                <isActive>false</isActive>
                <label>Tarde 14:00 a 18:00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/Friday__c.field-meta.xml
<CustomField>
    <fullName>Friday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Viernes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/Monday__c.field-meta.xml
<CustomField>
    <fullName>Monday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lunes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/Saturday__c.field-meta.xml
<CustomField>
    <fullName>Saturday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sabado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/Sunday__c.field-meta.xml
<CustomField>
    <fullName>Sunday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Domingo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/Thursday__c.field-meta.xml
<CustomField>
    <fullName>Thursday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jueves</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Tuesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Martes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Wednesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Miercoles</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DistributionCenter__c/LVC_DistributionCenter__c.object-meta.xml
<CustomObject>
    <label>Centro De Distribución</label>
    <nameField>
        <label>Centro De Distribucion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros De Distribución</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_DistributionCenter__c/fields/CDExternalId__c.field-meta.xml
<CustomField>
    <fullName>CDExternalId__c</fullName>
    <externalId>true</externalId>
    <label>CD External Id</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/LVC_DistributionCenter__c/fields/Friday__c.field-meta.xml
<CustomField>
    <fullName>Friday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Viernes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DistributionCenter__c/fields/Monday__c.field-meta.xml
<CustomField>
    <fullName>Monday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lunes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DistributionCenter__c/fields/Saturday__c.field-meta.xml
<CustomField>
    <fullName>Saturday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sabado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DistributionCenter__c/fields/Sunday__c.field-meta.xml
<CustomField>
    <fullName>Sunday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Domingo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DistributionCenter__c/fields/Thursday__c.field-meta.xml
<CustomField>
    <fullName>Thursday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jueves</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DistributionCenter__c/fields/Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Tuesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Martes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DistributionCenter__c/fields/Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Wednesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Miercoles</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_Order__c/LVC_Order__c.object-meta.xml
<CustomObject>
    <label>Pedido</label>
    <nameField>
        <displayFormat>PED-{0000000000}</displayFormat>
        <label>Pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_Order__c/fields/DeliveryRouteExternalId__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRouteExternalId__c</fullName>
    <label>Delivery Route External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LVC_OrderQuantityDate__c/LVC_OrderQuantityDate__c.object-meta.xml
<CustomObject>
    <label>Cantidad del Pedido Fecha</label>
    <nameField>
        <displayFormat>CANT-{0000000000}</displayFormat>
        <label>Cantidad del Pedido Fecha</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cantidades del Pedido Fecha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_OrderQuantityDate__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Fletero Id</label>
    <referenceTo>LVC_Delivery__c</referenceTo>
    <relationshipLabel>Cantidades del Pedido Fecha</relationshipLabel>
    <relationshipName>OrderQuantitiesDate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LVC_Polygon__c/LVC_Polygon__c.object-meta.xml
<CustomObject>
    <label>Polígono</label>
    <nameField>
        <label>Polígono</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Polígonos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_Polygon__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro De Distribución</label>
    <referenceTo>LVC_DistributionCenter__c</referenceTo>
    <relationshipLabel>Polígonos</relationshipLabel>
    <relationshipName>Polygons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LVC_Polygon__c/fields/PolygonExternalId__c.field-meta.xml
<CustomField>
    <fullName>PolygonExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Poligono External Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/LVC_Polygon__c/fields/TownId__c.field-meta.xml
<CustomField>
    <fullName>TownId__c</fullName>
    <label>TownId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LVC_Polygon__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T2</fullName>
                <default>true</default>
                <label>T2</label>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LVC_PolygonRoute__c/LVC_PolygonRoute__c.object-meta.xml
<CustomObject>
    <label>Poligono Ruta</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>LVC_PolygonRoute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Poligono Rutas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_PolygonRoute__c/fields/DeliveryRoute__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRoute__c</fullName>
    <label>Delivery Route</label>
    <referenceTo>LVC_DeliveryRoute__c</referenceTo>
    <relationshipLabel>Poligono Rutas</relationshipLabel>
    <relationshipName>Polygon_Route</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LVC_PolygonRoute__c/fields/Polygon__c.field-meta.xml
<CustomField>
    <fullName>Polygon__c</fullName>
    <label>Polígono</label>
    <referenceTo>LVC_Polygon__c</referenceTo>
    <relationshipLabel>Poligono Rutas</relationshipLabel>
    <relationshipName>Polygon_Route</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LVC_ProductStockDate__c/LVC_ProductStockDate__c.object-meta.xml
<CustomObject>
    <label>Producto en Stock Fecha</label>
    <nameField>
        <displayFormat>STOCK-{0000000000}</displayFormat>
        <label>Producto en Stock Fecha</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos en Stock Fecha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_ProductStockDate__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <label>Centro De Distribución</label>
    <referenceTo>LVC_DistributionCenter__c</referenceTo>
    <relationshipLabel>Productos en Stock Fecha</relationshipLabel>
    <relationshipName>Product_Stock_Date</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SFCCCapacityHelper_Test.cls
/**
 * Company:      CloudGaia
 * Description:  Test class for REST Resource for Capacity.
 * Test Class:   SFCCCapacityHelper_Test
 */
@isTest
public class SFCCCapacityHelper_Test {
    @isTest static void parseRequest(){
        Test.startTest();
        SFCCCapacityRequestWrapper.parse(requestContentBody_T2());
        Test.stopTest();
    }

    @isTest static void parseResponse(){
        Test.startTest();
        SFCCCapacityResponseWrapper.parse(responseContentBody());
        Test.stopTest();
    }

    @TestSetup static void generateData(){
        LVC_DistributionCenter__c distributionCenter = new LVC_DistributionCenter__c(
            Name = 'CD General Rodriguez',    
            CDExternalId__c = '1',
            Monday__c = true,
            Tuesday__c = true,
            Wednesday__c = true,
            Thursday__c = true,
            Friday__c = true,
            Saturday__c = false,
            Sunday__c = false
        );
        insert distributionCenter;
        LVC_Polygon__c polygon = new LVC_Polygon__c(
            Name = '12341234',
            PolygonExternalId__c = '12341234', 
            Type__c = 'T2', 
            DistributionCenter__c = distributionCenter.Id, 
            TownId__c = '14'
        );
        insert polygon;
        LVC_Polygon__c polygonClosedNeighborhood = new LVC_Polygon__c(
            Name = '12344321',
            PolygonExternalId__c = '12344321', 
            Type__c = 'T3', 
            DistributionCenter__c = distributionCenter.Id, 
            TownId__c = '10'
        );
        insert polygonClosedNeighborhood;

        LVC_Delivery__c deliveryT2 = new LVC_Delivery__c(
            Monday__c = 30,
            Tuesday__c = 30,
            Wednesday__c = 30,
            Thursday__c = 30,
            Friday__c = 30,
            Saturday__c = 10,
            Sunday__c = 10,
            Active__c = true
        );
        insert deliveryT2;

        LVC_DeliveryRoute__c deliveryRoute_T2 = new LVC_DeliveryRoute__c(
            Delivery__c = deliveryT2.Id,
            DeliverySchedule__c = 'D',
            Monday__c = true,
            Tuesday__c = true,
            Wednesday__c = true,
            Thursday__c = true,
            Friday__c = true,
            Saturday__c = false,
            Sunday__c = false,
            Active__c = true,
            DeliveryRouteExternalId__c = '00010001',
            RouteId__c = '1'
        );
        insert deliveryRoute_T2;

        LVC_PolygonRoute__c polygonRoute_T2 = new LVC_PolygonRoute__c(
            Polygon__c = polygon.Id,
            DeliveryRoute__c = deliveryRoute_T2.Id
        );
        insert polygonRoute_T2;

        LVC_Delivery__c deliveryT3 = new LVC_Delivery__c(
            Monday__c = 10,
            Tuesday__c = 10,
            Wednesday__c = 10,
            Thursday__c = 10,
            Friday__c = 10,
            Saturday__c = 5,
            Sunday__c = 0,
            Active__c = true
        );
        insert deliveryT3;

        LVC_DeliveryRoute__c deliveryRoute_T3 = new LVC_DeliveryRoute__c(
            Delivery__c = deliveryT3.Id,
            DeliverySchedule__c = 'M',
            Monday__c = false,
            Tuesday__c = false,
            Wednesday__c = false,
            Thursday__c = false,
            Friday__c = true,
            Saturday__c = true,
            Sunday__c = true,
            Active__c = true,
            DeliveryRouteExternalId__c = '00020001',
            RouteId__c = '1'
        );
        insert deliveryRoute_T3;

        LVC_PolygonRoute__c polygonRoute_T3 = new LVC_PolygonRoute__c(
            Polygon__c = polygon.Id,
            DeliveryRoute__c = deliveryRoute_T3.Id
        );
        insert polygonRoute_T3;

        List<LVC_ProductStockDate__c> productStockDate = new List<LVC_ProductStockDate__c>();
        for(integer i = 0; i<8; i++){
            LVC_ProductStockDate__c product = new LVC_ProductStockDate__c(
                DistributionCenter__c = distributionCenter.Id,
                StockDate__c = Date.today().addDays(i),
                Sku__c = '4771',
                Stock__c = 1000
            );
            productStockDate.add(product);
        }
        insert productStockDate;

        LVC_OrderQuantityDate__c orderQuantityDate_T2 = new LVC_OrderQuantityDate__c(
            Date__c = Date.today().addDays(2), 
            Delivery__c = deliveryT2.Id
        );
        insert orderQuantityDate_T2;
        LVC_Order__c order_T2 = new LVC_Order__c(
            OrderExternalId__c = 'DAN-0001', 
            OrderQuantityDate__c = orderQuantityDate_T2.Id, 
            DNI__c = '123', 
            Address__c = 'test', 
            Date__c = Date.today().addDays(2)
        );
        insert order_T2;

        LVC_OrderQuantityDate__c orderQuantityDate_T3 = new LVC_OrderQuantityDate__c(
            Date__c = Date.today().addDays(2),
            Delivery__c = deliveryT3.Id
        );
        insert orderQuantityDate_T3;
        LVC_Order__c order_T3 = new LVC_Order__c(
            OrderExternalId__c = 'DAN-0005', 
            OrderQuantityDate__c = orderQuantityDate_T3.Id, 
            DNI__c = '48678429', 
            Address__c = 'Main ST 11202', 
            Date__c = Date.today().addDays(2)
        );
        insert order_T3;
        LVC_OrderProduct__c orderProduct_T2 = new LVC_OrderProduct__c(
            Quantity__c = 5,
            Order__c = order_T2.Id, 
            ProductStockDate__c = productStockDate[0].Id,
            Sku__c = productStockDate[0].Sku__c
        );
        insert orderProduct_T2;
        LVC_OrderProduct__c orderProduct_T3 = new LVC_OrderProduct__c(
            Quantity__c = 10,
            Order__c = order_T3.Id, 
            ProductStockDate__c = productStockDate[0].Id,
            Sku__c = productStockDate[0].Sku__c
        );
        insert orderProduct_T3;
    }

    @isTest static void doPostT2(){
        //given
        RestRequest request = new RestRequest(); 
        RestResponse restResponse = new RestResponse(); 
        String contentData = requestContentBody_T2();
		
        //when
        Test.startTest();
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(contentData);
        RestContext.request = request;
        RestContext.response = restResponse;

        RESTCapacity.doPost();
        Blob responseBody = RestContext.response.responseBody;
        Test.stopTest();
    }

    @isTest static void doPostT3(){
        //given
        RestRequest request = new RestRequest(); 
        RestResponse restResponse = new RestResponse(); 
        String contentData = requestContentBody_T3();
		
        //when
        Test.startTest();
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(contentData);
        RestContext.request = request;
        RestContext.response = restResponse;

        RESTCapacity.doPost();
        Blob responseBody = RestContext.response.responseBody;
        Test.stopTest();
    }

    private static String requestContentBody_T2(){
        return '{\"completeAddress\": \"Martina Cespedes 2008, Villa Adelina,Buenos Aires\",\"customerNationalId\": 33123123,   \"cutoverTime\": \"03:14:15.926Z\",\"isClosedNeighborhood\":false,\"poligons\": [\"12341234\", \r\n    \"12344321\"],\"products\": [{\"sku\":\"4771\",\"quantity\":5}]}';
    }

    private static String requestContentBody_T3(){
        return '{\"completeAddress\": \"Martina Cespedes 2008, Villa Adelina,Buenos Aires\",\"customerNationalId\": 33123123,   \"cutoverTime\": \"03:14:15.926Z\",\"isClosedNeighborhood\":true,\"poligons\": [\"12341234\", \r\n    \"12344321\"],\"products\": [{\"sku\":\"4771\",\"quantity\":5}]}';
    }

    private static String responseContentBody(){
        return '{\"storeId\":\"1\",\"dates\":[{\"times\":{\"T\":\"Tarde 14:00 a 18:00\",\"M\":\"Mañana 09:00 a 13:00\"},\"suggestedDate\":\"2022-06-09\",\"polygonId\":\"12341234\",\"loadDate\":\"2022-06-08\"}]}';
    }
}