force-app/main/default/objects/LVC_Delivery__c/LVC_Delivery__c.object-meta.xml
<CustomObject>
    <label>Fletero</label>
    <nameField>
        <label>Fletero</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleteros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_Delivery__c/fields/Monday__c.field-meta.xml
<CustomField>
    <fullName>Monday__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lunes</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LVC_Delivery__c/fields/Thursday__c.field-meta.xml
<CustomField>
    <fullName>Thursday__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Jueves</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LVC_Delivery__c/fields/Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Tuesday__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Martes</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LVC_Delivery__c/fields/Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Wednesday__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Miercoles</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/LVC_DeliveryRoute__c.object-meta.xml
<CustomObject>
    <label>Ruta de Reparto</label>
    <nameField>
        <displayFormat>DR-{00000000}</displayFormat>
        <label>LVC_DeliveryRoute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ruta de Reparto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fletero Id</label>
    <referenceTo>LVC_Delivery__c</referenceTo>
    <relationshipLabel>Ruta de Reparto</relationshipLabel>
    <relationshipName>DeliveryRoutes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/DeliverySchedule__c.field-meta.xml
<CustomField>
    <fullName>DeliverySchedule__c</fullName>
    <label>Horario Entrega</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Mañana 08:00 a 13:00</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Día 09:00 a 16:00</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Mañana 08:00 a 11:00</label>
            </value>
            <value>
                <fullName>T</fullName>
                <isActive>false</isActive>
                <label>Tarde 14:00 a 18:00</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/Monday__c.field-meta.xml
<CustomField>
    <fullName>Monday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lunes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/Thursday__c.field-meta.xml
<CustomField>
    <fullName>Thursday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jueves</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Tuesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Martes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DeliveryRoute__c/fields/Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Wednesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Miercoles</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DistributionCenter__c/LVC_DistributionCenter__c.object-meta.xml
<CustomObject>
    <label>Centro De Distribución</label>
    <nameField>
        <label>Centro De Distribucion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros De Distribución</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_DistributionCenter__c/fields/CDExternalId__c.field-meta.xml
<CustomField>
    <fullName>CDExternalId__c</fullName>
    <externalId>true</externalId>
    <label>CD External Id</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/LVC_DistributionCenter__c/fields/Monday__c.field-meta.xml
<CustomField>
    <fullName>Monday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lunes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DistributionCenter__c/fields/Thursday__c.field-meta.xml
<CustomField>
    <fullName>Thursday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jueves</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DistributionCenter__c/fields/Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Tuesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Martes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_DistributionCenter__c/fields/Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Wednesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Miercoles</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LVC_Holidays__c/LVC_Holidays__c.object-meta.xml
<CustomObject>
    <label>Días No Hábiles</label>
    <nameField>
        <displayFormat>DNH-{0000}</displayFormat>
        <label>Día No Hábil</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Días No Hábiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_Holidays__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <label>Centro De Distribución</label>
    <referenceTo>LVC_DistributionCenter__c</referenceTo>
    <relationshipLabel>Días No Hábiles</relationshipLabel>
    <relationshipName>Holidays</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LVC_Order__c/LVC_Order__c.object-meta.xml
<CustomObject>
    <label>Pedido</label>
    <nameField>
        <displayFormat>PED-{0000000000}</displayFormat>
        <label>Pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_Order__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Dirección</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LVC_Order__c/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <label>DNI</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LVC_Order__c/fields/OrderQuantityDate__c.field-meta.xml
<CustomField>
    <fullName>OrderQuantityDate__c</fullName>
    <label>Cantidad del Pedido Fecha</label>
    <referenceTo>LVC_OrderQuantityDate__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LVC_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Confirmado</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Cancelado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LVC_OrderQuantityDate__c/LVC_OrderQuantityDate__c.object-meta.xml
<CustomObject>
    <label>Cantidad del Pedido Fecha</label>
    <nameField>
        <displayFormat>CANT-{0000000000}</displayFormat>
        <label>Cantidad del Pedido Fecha</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cantidades del Pedido Fecha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_OrderQuantityDate__c/fields/ConsumedOrdersQuantity__c.field-meta.xml
<CustomField>
    <fullName>ConsumedOrdersQuantity__c</fullName>
    <label>Cantidad de Pedidos Consumidos</label>
    <summaryFilterItems>
        <field>LVC_Order__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmado</value>
    </summaryFilterItems>
    <summaryForeignKey>LVC_Order__c.OrderQuantityDate__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/LVC_OrderQuantityDate__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Fletero Id</label>
    <referenceTo>LVC_Delivery__c</referenceTo>
    <relationshipLabel>Cantidades del Pedido Fecha</relationshipLabel>
    <relationshipName>OrderQuantitiesDate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LVC_Polygon__c/LVC_Polygon__c.object-meta.xml
<CustomObject>
    <label>Polígono</label>
    <nameField>
        <label>Polígono</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Polígonos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_Polygon__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro De Distribución</label>
    <referenceTo>LVC_DistributionCenter__c</referenceTo>
    <relationshipLabel>Polígonos</relationshipLabel>
    <relationshipName>Polygons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LVC_Polygon__c/fields/PolygonExternalId__c.field-meta.xml
<CustomField>
    <fullName>PolygonExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Poligono External Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/LVC_PolygonRoute__c/LVC_PolygonRoute__c.object-meta.xml
<CustomObject>
    <label>Poligono Ruta</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>LVC_PolygonRoute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Poligono Rutas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_PolygonRoute__c/fields/DeliveryRoute__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRoute__c</fullName>
    <label>Delivery Route</label>
    <referenceTo>LVC_DeliveryRoute__c</referenceTo>
    <relationshipLabel>Poligono Rutas</relationshipLabel>
    <relationshipName>Polygon_Route</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LVC_PolygonRoute__c/fields/Polygon__c.field-meta.xml
<CustomField>
    <fullName>Polygon__c</fullName>
    <label>Polígono</label>
    <referenceTo>LVC_Polygon__c</referenceTo>
    <relationshipLabel>Poligono Rutas</relationshipLabel>
    <relationshipName>Polygon_Route</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LVC_ProductStockDate__c/LVC_ProductStockDate__c.object-meta.xml
<CustomObject>
    <label>Producto en Stock Fecha</label>
    <nameField>
        <displayFormat>STOCK-{0000000000}</displayFormat>
        <label>Producto en Stock Fecha</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos en Stock Fecha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_ProductStockDate__c/fields/ConsumedStock__c.field-meta.xml
<CustomField>
    <fullName>ConsumedStock__c</fullName>
    <label>Stock Consumido</label>
    <summarizedField>LVC_OrderProduct__c.Quantity__c</summarizedField>
    <summaryForeignKey>LVC_OrderProduct__c.ProductStockDate__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/LVC_ProductStockDate__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <label>Centro De Distribución</label>
    <referenceTo>LVC_DistributionCenter__c</referenceTo>
    <relationshipLabel>Productos en Stock Fecha</relationshipLabel>
    <relationshipName>Product_Stock_Date</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LVC_ProductStockDate__c/fields/Sku__c.field-meta.xml
<CustomField>
    <fullName>Sku__c</fullName>
    <label>Sku de Producto</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LVC_ProductStockDate__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <label>Stock</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LVC_ProductStockDate__c/fields/StockDate__c.field-meta.xml
<CustomField>
    <fullName>StockDate__c</fullName>
    <label>Fecha de Stock</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SFCCQueriesHelper.cls
/**
 * Company:      CloudGaia
 * Description:  Helper class for making queries.
 * Test Class:   SFCCCapacityHelper_Test
 */
public with sharing class SFCCQueriesHelper {
    public static List<Date> getHolidays(String CDId){
        List<Date> holidays = new List<Date>();
        List<LVC_Holidays__c> hlist = [SELECT Date__c
                                   FROM LVC_Holidays__c
                                   WHERE DistributionCenter__r.CDExternalId__c =: CDId
                                   AND Date__c >=: Date.today()
                                   AND Date__c <=: Date.today().addDays(20)];
        for(LVC_Holidays__c holiday:hlist){
            holidays.add(holiday.Date__c);
        }
        return holidays;     
    }
    
    public static List<LVC_Order__c> getOrdersData(List<Date> possibleDates, String customerNationalId, String customerAddress, String status){
        return [SELECT DNI__c, Address__c, Date__c 
                FROM LVC_Order__c 
                WHERE Date__c IN: possibleDates 
                AND DNI__c =: customerNationalId 
                AND Address__c =: customerAddress
                AND Status__c =: status];
    }
    
    public static List<LVC_OrderQuantityDate__c> getQuantitiesDate(Set<String> deliveryIds, Set<Date> possibleDates){
        return [SELECT ConsumedOrdersQuantity__c, Date__c, Id, Delivery__c 
                FROM LVC_OrderQuantityDate__c 
                WHERE Delivery__c =: deliveryIds
                AND Date__c =: possibleDates];
    }

    public static List<LVC_ProductStockDate__c> getStockProductsDates(List<Date> dateInput, String cdId, Set<String> stSkus){
        return [SELECT Id, DistributionCenter__r.CDExternalId__c, StockDate__c, Sku__c, Stock__c, ConsumedStock__c 
                FROM LVC_ProductStockDate__c 
                WHERE DistributionCenter__r.CDExternalId__c =: cdId 
                AND StockDate__c IN: dateInput 
                AND Sku__c IN: stSkus];
    }

    public static List<LVC_PolygonRoute__c> getPossibleRoutsWithPolygons(Set<String> polygonIds){
        return [SELECT DeliveryRoute__c, Polygon__c, Polygon__r.PolygonExternalId__c 
                FROM LVC_PolygonRoute__c 
                WHERE Polygon__r.PolygonExternalId__c =: polygonIds];
    }

    public static List<LVC_DeliveryRoute__c> getDeliveryRoutesById(Set<String> deliveryRouteIds){
        return [SELECT DeliverySchedule__c, Active__c, Monday__c, Tuesday__c, Wednesday__c, 
                       Thursday__c, Friday__c, Saturday__c, Sunday__c, DeliveryRouteExternalId__c,
                       RouteId__c, Delivery__c 
                FROM LVC_DeliveryRoute__c 
                WHERE Id =: deliveryRouteIds 
                AND Active__c = true];
    }

    public static List<LVC_Delivery__c> getDeliveryCapacities(Set<String> deliveryIds){
        return [SELECT Monday__c, Tuesday__c, Wednesday__c, Thursday__c, Friday__c, Saturday__c, Sunday__c, Active__c 
                FROM LVC_Delivery__c 
                WHERE Id =: deliveryIds
                AND Active__c = true];
    }

    public static List<LVC_Order__c> getExistingOrders(Set<Date> possibleDates, String status){
        return [SELECT DNI__c, Address__c, Date__c, Status__c, OrderExternalId__c, OrderQuantityDate__c
                FROM LVC_Order__c 
                WHERE Date__c =: possibleDates
                AND Status__c =: status];
    }
}