force-app/main/default/objects/Account/fields/Actividad_para_ObraSocial_del__c.field-meta.xml
<CustomField>
    <fullName>Actividad_para_ObraSocial_del__c</fullName>
    <defaultValue>IF($RecordType.Name= &apos;Paciente Regular&apos;, &apos;M1&apos;,&apos;&apos;)</defaultValue>
    <label>Actividad</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Area_terapeutica__c.field-meta.xml
<CustomField>
    <fullName>Area_terapeutica__c</fullName>
    <label>Área terapéutica</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adultos Comunidad</fullName>
            </value>
            <value>
                <fullName>Alergia</fullName>
            </value>
            <value>
                <fullName>Dieta Cetogénica</fullName>
            </value>
            <value>
                <fullName>Farmacia</fullName>
            </value>
            <value>
                <fullName>Institución</fullName>
            </value>
            <value>
                <fullName>Metabólicos</fullName>
            </value>
            <value>
                <fullName>Metabólicos - Dieta Cetogénica</fullName>
            </value>
            <value>
                <fullName>Ministerio</fullName>
            </value>
            <value>
                <fullName>NEG</fullName>
                <label>Nutrición General</label>
            </value>
            <value>
                <fullName>Oncología</fullName>
            </value>
            <value>
                <fullName>Tailored Nutrition</fullName>
            </value>
            <value>
                <fullName>Adultos (UTI-STROKE)</fullName>
            </value>
            <value>
                <fullName>Adultos (Oncologia)</fullName>
            </value>
            <value>
                <fullName>Adultos (IISS + Onco)</fullName>
            </value>
            <value>
                <fullName>Adultos (Instituciones)</fullName>
            </value>
            <value>
                <fullName>Adultos (Comunidad)</fullName>
            </value>
            <value>
                <fullName>Adultos (IISS + Comunidad)</fullName>
            </value>
            <value>
                <fullName>Digestivos</fullName>
            </value>
            <value>
                <fullName>Desafíos del crecimiento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Canal_para_Consumidor_Baby__c.field-meta.xml
<CustomField>
    <fullName>Canal_para_Consumidor_Baby__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Almacen</fullName>
            </value>
            <value>
                <fullName>Farmacias</fullName>
            </value>
            <value>
                <fullName>Farmacity</fullName>
            </value>
            <value>
                <fullName>Hipermarket</fullName>
            </value>
            <value>
                <fullName>MercadoLibre</fullName>
            </value>
            <value>
                <fullName>Nutrilon4</fullName>
            </value>
            <value>
                <fullName>Proximity</fullName>
            </value>
            <value>
                <fullName>Simplicity</fullName>
            </value>
            <value>
                <fullName>Supermercado</fullName>
            </value>
            <value>
                <fullName>Vital4</fullName>
            </value>
            <value>
                <fullName>La Sere va a tu casa</fullName>
            </value>
            <value>
                <fullName>Particular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_postal__c</fullName>
    <label>Codigo postal</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion_entrega__c.field-meta.xml
<CustomField>
    <fullName>Direccion_entrega__c</fullName>
    <label>Dirección de entrega</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domicilio particular</fullName>
            </value>
            <value>
                <fullName>Farmacia</fullName>
            </value>
            <value>
                <fullName>Delegación Obra Social</fullName>
            </value>
            <value>
                <fullName>Instituciones</fullName>
            </value>
            <value>
                <fullName>Geriátrico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <label>DNI</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Estado_de_paciente__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_paciente__c</fullName>
    <label>Estado de paciente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inicio</fullName>
                <default>true</default>
                <label>Inicio</label>
            </value>
            <value>
                <fullName>En Seguimiento</fullName>
            </value>
            <value>
                <fullName>En tratamiento</fullName>
            </value>
            <value>
                <fullName>No tratamiento</fullName>
            </value>
            <value>
                <fullName>Fin de tratamiento</fullName>
            </value>
            <value>
                <fullName>Excluido</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Modulo_hasta__c.field-meta.xml
<CustomField>
    <fullName>Modulo_hasta__c</fullName>
    <label>Modulo hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Obra_social__c.field-meta.xml
<CustomField>
    <fullName>Obra_social__c</fullName>
    <label>Nombre de la obra social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SalesGroup__c.field-meta.xml
<CustomField>
    <fullName>SalesGroup__c</fullName>
    <label>SalesGroup</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SalesOffice_ObraSocial__c.field-meta.xml
<CustomField>
    <fullName>SalesOffice_ObraSocial__c</fullName>
    <label>SalesOffice</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_Obra_Social__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Obra_Social__c</fullName>
    <label>Tipo de Obra Social</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prepaga</fullName>
            </value>
            <value>
                <fullName>Obra Social Nacional</fullName>
            </value>
            <value>
                <fullName>Obra Social Provincial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ubicacion__c.field-meta.xml
<CustomField>
    <fullName>Ubicacion__c</fullName>
    <label>Ubicacion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mendoza</fullName>
                <default>true</default>
                <label>Mendoza</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Codigo_Postal__c/Codigo_Postal__c.object-meta.xml
<CustomObject>
    <label>Código Postal</label>
    <nameField>
        <label>Código Postal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Códigos Postales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Modulo_de_paciente__c/Modulo_de_paciente__c.object-meta.xml
<CustomObject>
    <label>Modulo de paciente</label>
    <nameField>
        <displayFormat>MDP-{0000}</displayFormat>
        <label>Nro de Modulo de paciente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modulos de paciente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_postal__c</fullName>
    <formula>Cuenta__r.PersonContact.Obra_social__r.Codigo_postal__c</formula>
    <label>Código postal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>El módulo solo es válido para pacientes Best Care</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Best Care</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Modulos de paciente (Solo Best Care)</relationshipLabel>
    <relationshipName>Modulos_de_paciente</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Duracion_modulo__c.field-meta.xml
<CustomField>
    <fullName>Duracion_modulo__c</fullName>
    <inlineHelpText>En días</inlineHelpText>
    <label>Duracion modulo</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado de Servicio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Modulo_desde__c.field-meta.xml
<CustomField>
    <fullName>Modulo_desde__c</fullName>
    <label>Modulo desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Modulo_hasta__c.field-meta.xml
<CustomField>
    <fullName>Modulo_hasta__c</fullName>
    <label>Modulo hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Renovacion__c.field-meta.xml
<CustomField>
    <fullName>Renovacion__c</fullName>
    <label>Renovación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Renovacion</fullName>
            </value>
            <value>
                <fullName>alta</fullName>
                <label>Alta</label>
            </value>
            <value>
                <fullName>Recupero</fullName>
            </value>
            <value>
                <fullName>Sí</fullName>
                <isActive>false</isActive>
                <label>Sí</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Valor_total_pesos__c.field-meta.xml
<CustomField>
    <fullName>Valor_total_pesos__c</fullName>
    <label>Valor total</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BatchUpdateEstadoMdpTest.cls
@isTest
public with sharing class BatchUpdateEstadoMdpTest {

    @testSetup
    static void setup() {
        List<Modulo_de_paciente__c> mdps = new List<Modulo_de_paciente__c>();

        Account obraSocial = new Account(
            Name = 'Obra Social 1',
            SalesOffice_ObraSocial__c = 'Pruebas 1',
            SalesGroup__c = ' Grupo pruebas 1',
            Actividad_para_ObraSocial_del__c	= 'Economica 1',
            Canal_para_Consumidor_Baby__c = 'Almacen',
            Ubicacion__c = 'Mendoza'
        );
        insert obraSocial;

        Account cuenta2 = new Account(
            LastName = 'Pruebas Danone 1',
            RecordTypeId = '0121I000001BtZPQA0',
            Area_terapeutica__c = 'Oncología',
            DNI__c = '6397302',
            Estado_de_paciente__c = 'Inicio',
            Phone = '5491112345678',
            Canal_para_Consumidor_Baby__c = 'Almacen',
            Direccion_entrega__c = 'Farmacia',
            // Obra_social__c = '001M000001CnCp9IAF',
            Obra_social__c = obraSocial.Id,
            Tipo_de_Obra_Social__c = 'Prepaga',
            Codigo_postal__c = '1834'
        );

        insert cuenta2;
        
        // insert 10 accounts
        
        
            Modulo_de_paciente__c insertarMDP =  new Modulo_de_paciente__c(
                    Renovacion__c	= 'Alta',
                    Duracion_modulo__c = 6,
                    Modulo_desde__c = date.parse('8/10/2023'),
                    Modulo_hasta__c = Date.today(),
                    Valor_total_pesos__c = 1000.00,
                    Estado__c = 'Activo',
                    Cuenta__c = cuenta2.Id
                );    
            
        
        INSERT insertarMDP;

    }

    @isTest static void test() {

        List<Modulo_de_paciente__c> mdps = [SELECT Id FROM Modulo_de_paciente__c];

        List<Modulo_de_paciente__c> mdpsToUpdate = new List<Modulo_de_paciente__c>();

        for(Modulo_de_paciente__c mdp : mdps){

            Modulo_de_paciente__c newmdp = new Modulo_de_paciente__c(
                Id = mdp.Id,
                Modulo_hasta__c =  System.today().addDays(-1)
                // Estado__c = 'Activo'
            );
            
            mdpsToUpdate.add(newmdp);
        }
        update mdpsToUpdate;

        Test.startTest();
        BatchUpdateEstadoMdp uca = new BatchUpdateEstadoMdp();
        Id batchId = Database.executeBatch(uca);
        Test.stopTest();
        Date fechaFutura = System.today().addDays(1);

        // after the testing stops, assert records were updated properly
        System.assertEquals(0, [SELECT count() FROM Modulo_de_paciente__c WHERE Modulo_hasta__c < TODAY AND Estado__c = 'Activo']);
    }
}