force-app/main/default/objects/Account/fields/Area_terapeutica__c.field-meta.xml
<CustomField>
    <fullName>Area_terapeutica__c</fullName>
    <label>Área terapéutica</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adultos Comunidad</fullName>
            </value>
            <value>
                <fullName>Alergia</fullName>
            </value>
            <value>
                <fullName>Dieta Cetogénica</fullName>
            </value>
            <value>
                <fullName>Farmacia</fullName>
            </value>
            <value>
                <fullName>Institución</fullName>
            </value>
            <value>
                <fullName>Metabólicos</fullName>
            </value>
            <value>
                <fullName>Metabólicos - Dieta Cetogénica</fullName>
            </value>
            <value>
                <fullName>Ministerio</fullName>
            </value>
            <value>
                <fullName>NEG</fullName>
                <label>Nutrición General</label>
            </value>
            <value>
                <fullName>Oncología</fullName>
            </value>
            <value>
                <fullName>Tailored Nutrition</fullName>
            </value>
            <value>
                <fullName>Adultos (UTI-STROKE)</fullName>
            </value>
            <value>
                <fullName>Adultos (Oncologia)</fullName>
            </value>
            <value>
                <fullName>Adultos (IISS + Onco)</fullName>
            </value>
            <value>
                <fullName>Adultos (Instituciones)</fullName>
            </value>
            <value>
                <fullName>Adultos (Comunidad)</fullName>
            </value>
            <value>
                <fullName>Adultos (IISS + Comunidad)</fullName>
            </value>
            <value>
                <fullName>Digestivos</fullName>
            </value>
            <value>
                <fullName>Desafíos del crecimiento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Canal_para_Consumidor_Baby__c.field-meta.xml
<CustomField>
    <fullName>Canal_para_Consumidor_Baby__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Almacen</fullName>
            </value>
            <value>
                <fullName>Farmacias</fullName>
            </value>
            <value>
                <fullName>Farmacity</fullName>
            </value>
            <value>
                <fullName>Hipermarket</fullName>
            </value>
            <value>
                <fullName>MercadoLibre</fullName>
            </value>
            <value>
                <fullName>Nutrilon4</fullName>
            </value>
            <value>
                <fullName>Proximity</fullName>
            </value>
            <value>
                <fullName>Simplicity</fullName>
            </value>
            <value>
                <fullName>Supermercado</fullName>
            </value>
            <value>
                <fullName>Vital4</fullName>
            </value>
            <value>
                <fullName>La Sere va a tu casa</fullName>
            </value>
            <value>
                <fullName>Particular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_postal__c</fullName>
    <label>Codigo postal</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dias_en_este_estado__c.field-meta.xml
<CustomField>
    <fullName>Dias_en_este_estado__c</fullName>
    <formula>TODAY()- Fecha_de_cambio_de_estado__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Días en este estado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <label>DNI</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Estado_de_paciente__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_paciente__c</fullName>
    <label>Estado de paciente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inicio</fullName>
                <default>true</default>
                <label>Inicio</label>
            </value>
            <value>
                <fullName>En Seguimiento</fullName>
            </value>
            <value>
                <fullName>En tratamiento</fullName>
            </value>
            <value>
                <fullName>No tratamiento</fullName>
            </value>
            <value>
                <fullName>Fin de tratamiento</fullName>
            </value>
            <value>
                <fullName>Excluido</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_de_cambio_de_estado__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_cambio_de_estado__c</fullName>
    <label>Fecha de cambio de estado</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Servicio_Activo_Aux__c.field-meta.xml
<CustomField>
    <fullName>Servicio_Activo_Aux__c</fullName>
    <label>Servicio Activo Aux</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Subestado_del_paciente__c.field-meta.xml
<CustomField>
    <fullName>Subestado_del_paciente__c</fullName>
    <label>Subestado del paciente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Estado_de_paciente__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tratamiento Efectivo</fullName>
            </value>
            <value>
                <fullName>Cobertura parcial con Consumo</fullName>
            </value>
            <value>
                <fullName>Negativa de la OS con Consumo</fullName>
            </value>
            <value>
                <fullName>Próximo a desafío</fullName>
            </value>
            <value>
                <fullName>Con otro laboratorio</fullName>
            </value>
            <value>
                <fullName>No tolera</fullName>
            </value>
            <value>
                <fullName>Se Rehúsa</fullName>
            </value>
            <value>
                <fullName>Negativa de la OS Sin consumo</fullName>
            </value>
            <value>
                <fullName>Alta de tratamiento</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Con otro laboratorio x OOSS</fullName>
            </value>
            <value>
                <fullName>Con otro laboratorio x Profesional</fullName>
            </value>
            <value>
                <fullName>Excluido</fullName>
            </value>
            <value>
                <fullName>En Seguimiento de ONG</fullName>
            </value>
            <value>
                <fullName>Imposible de contactar</fullName>
            </value>
            <value>
                <fullName>Cambio de indicación</fullName>
            </value>
            <value>
                <fullName>Migrado erroneamente</fullName>
            </value>
            <value>
                <fullName>No contactar Solicitud del paciente</fullName>
            </value>
            <value>
                <fullName>No contactar Solicitud del profesional</fullName>
            </value>
            <value>
                <fullName>Cambio de fórmula</fullName>
            </value>
            <value>
                <fullName>No renovó por negativa negociación OOSS</fullName>
            </value>
            <value>
                <fullName>No renovó cambio de indicación</fullName>
            </value>
            <value>
                <fullName>No renovó por cambio de empresa de internación domiciliaria</fullName>
            </value>
            <value>
                <fullName>No renovó por stock adicional</fullName>
            </value>
            <value>
                <fullName>Stock remanente</fullName>
            </value>
            <value>
                <fullName>Tramite iniciado</fullName>
            </value>
            <value>
                <fullName>Internado</fullName>
            </value>
            <value>
                <fullName>Modulo Inactivo</fullName>
            </value>
            <value>
                <fullName>Sin documentación</fullName>
            </value>
            <value>
                <fullName>Tramite no iniciado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_Obra_Social__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Obra_Social__c</fullName>
    <label>Tipo de Obra Social</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prepaga</fullName>
            </value>
            <value>
                <fullName>Obra Social Nacional</fullName>
            </value>
            <value>
                <fullName>Obra Social Provincial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Usuario_KAM_obra_social__c.field-meta.xml
<CustomField>
    <fullName>Usuario_KAM_obra_social__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario KAM obra social</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UsuarioKAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Area_Terapeutica__c.field-meta.xml
<CustomField>
    <fullName>Area_Terapeutica__c</fullName>
    <label>Área Terapéutica</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_Terapeutica</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_postal__c</fullName>
    <label>Código postal</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <label>DNI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Calidad.recordType-meta.xml
<RecordType>
    <fullName>Calidad</fullName>
    <active>false</active>
    <businessProcess>Calidad</businessProcess>
    <label>Calidad</label>
</RecordType>

force-app/main/default/objects/Codigo_Postal__c/Codigo_Postal__c.object-meta.xml
<CustomObject>
    <label>Código Postal</label>
    <nameField>
        <label>Código Postal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Códigos Postales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Area_Terapeutica.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dieta Cetogénica</fullName>
    </customValue>
    <customValue>
        <fullName>Metabólicos</fullName>
    </customValue>
    <customValue>
        <fullName>Malnutrición</fullName>
    </customValue>
    <customValue>
        <fullName>Disfagia</fullName>
    </customValue>
    <customValue>
        <fullName>Oncología</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia</fullName>
    </customValue>
    <customValue>
        <fullName>Digestivos</fullName>
    </customValue>
    <customValue>
        <fullName>Desafíos del crecimiento</fullName>
    </customValue>
    <customValue>
        <fullName>Terapia Cetogénica</fullName>
        <isActive>false</isActive>
        <label>Terapia Cetogénica</label>
    </customValue>
    <masterLabel>Áreas Terapéuticas</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchCrearCasoNoRenovTest.cls
@isTest
private class BatchCrearCasoNoRenovTest {

    @TestSetup
    static void makeData(){
        
          Profile profileIdTest = [
            SELECT Id 
            FROM Profile 
            WHERE Name = 'Gerente Best Care/Calidad' 
            LIMIT 1
            ];

        User user1 = Build.aUser()
        .withUsername('testKAMAlert@gmailK.com')
        .withEmail('testkam@gmail.com')
        .withAlias('tKAM')
        .withTimeZoneSidKey('GMT')
        .withLocaleSidKey('en_US')
        .withLastName('test KAM')
        .withCommunityNickname('testKAM')
        .withEmailEncodingKey('UTF-8')
        .withProfileId(profileIdTest.id)
        .withLanguageLocaleKey('en_US')
        .Build();
        insert user1;
        
		User user2 = Build.aUser()
        .withUsername('testKAMAlert2@gmailK.com')
        .withEmail('testkam2@gmail.com')
        .withAlias('tKAM2')
        .withTimeZoneSidKey('GMT')
        .withLocaleSidKey('en_US')
        .withLastName('test KAM2')
        .withCommunityNickname('testKAM2')
        .withEmailEncodingKey('UTF-8')
        .withProfileId(profileIdTest.id)
        .withLanguageLocaleKey('en_US')
        .Build();
        insert user2;

        Account accObraSocial = Build.anAccountObrasocial()
        .withName('Prueba Obra social')
        .build();
        
		Account accObraSocial2 = Build.anAccountObrasocial()
        .withName('Prueba Obra social2')
        .build();
        
        accObraSocial.Usuario_KAM_obra_social__c = user1.id;
        accObraSocial2.Usuario_KAM_obra_social__c = user1.id;
        insert accObraSocial;
        insert accObraSocial2;

        RecordType recordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Paciente_Best_Care'];
        
		//Date fechaHace5Dias = date.newinstance(2024,3,30);
        Date fechaHace5Dias = Date.today().addDays(-5);
            
        Account cuenta = new Account(
            LastName = 'Pruebas 3',
            RecordTypeId = recordType.Id,
            DNI__c = '111111111111',
            Area_terapeutica__c = 'Dieta Cetogénica',
            Estado_de_paciente__c = 'En Seguimiento',
            Subestado_del_paciente__c = 'Modulo Inactivo',
            Phone = '111111111',
            Canal_para_Consumidor_Baby__c = 'Farmacias',
            //Dias_en_este_estado__c = 5,
            Tipo_de_Obra_Social__c = 'Prepaga',
            Obra_social__pc = accObraSocial.Id,
            Codigo_postal__c = 'B1228',
            Fecha_de_cambio_de_estado__c = fechaHace5Dias,
            Servicio_Activo_Aux__c = 'AUTOCUIDADO.'
        );
        
            Account cuenta2 = new Account(
            LastName = 'Pruebas 4',
            RecordTypeId = recordType.Id,
            DNI__c = '111111111112',
            Area_terapeutica__c = 'Dieta Cetogénica',
            Estado_de_paciente__c = 'En Seguimiento',
            Subestado_del_paciente__c = 'Modulo Inactivo',
            Phone = '111111112',
            Canal_para_Consumidor_Baby__c = 'Farmacias',
            //Dias_en_este_estado__c = 5,
            Tipo_de_Obra_Social__c = 'Prepaga',
            Obra_social__pc = accObraSocial2.Id,
            Codigo_postal__c = 'B1228',
            Fecha_de_cambio_de_estado__c = fechaHace5Dias,
            Servicio_Activo_Aux__c = 'AUTOCUIDADO.'
        );
        
        	INSERT cuenta;  
        	INSERT cuenta2;
        
        Case caso = new Case(
            Subject = 'Nuevo seguimiento no renovación',
            AccountId = cuenta2.Id
        );
            INSERT caso;
    }

    @isTest
    static void verificarQueSeCrearonLosCasos() {

        Date fechaHace5Dias = Date.today().addDays(-5);
        Account cuentaTest = [SELECT Id FROM Account Where LastName = 'Pruebas 3'];
        cuentaTest.Fecha_de_cambio_de_estado__c = fechaHace5Dias;
        update cuentaTest;

        Test.startTest();
            BatchCrearCasoNoRenovacion batch = new BatchCrearCasoNoRenovacion();
            Database.executeBatch(batch);
        Test.stopTest();
		
        List<Case> casogeneradoDeRelleno = [SELECT Id FROM Case WHERE Subject = 'Nuevo seguimiento no renovación' ORDER BY CreatedDate ASC LIMIT 1 ];
        delete casogeneradoDeRelleno;
        List<Case> casosGenerados = [SELECT Id FROM Case WHERE Subject = 'Nuevo seguimiento no renovación'];

        // System.assertEquals(expected, actual)
        System.assertEquals(1, casosGenerados.size(), 'Prueba 1');
    }
}