force-app/main/default/objects/Account/fields/Area_terapeutica__c.field-meta.xml
<CustomField>
    <fullName>Area_terapeutica__c</fullName>
    <label>Área terapéutica</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adultos Comunidad</fullName>
            </value>
            <value>
                <fullName>Alergia</fullName>
            </value>
            <value>
                <fullName>Dieta Cetogénica</fullName>
            </value>
            <value>
                <fullName>Farmacia</fullName>
            </value>
            <value>
                <fullName>Institución</fullName>
            </value>
            <value>
                <fullName>Metabólicos</fullName>
            </value>
            <value>
                <fullName>Metabólicos - Dieta Cetogénica</fullName>
            </value>
            <value>
                <fullName>Ministerio</fullName>
            </value>
            <value>
                <fullName>NEG</fullName>
                <label>Nutrición General</label>
            </value>
            <value>
                <fullName>Oncología</fullName>
            </value>
            <value>
                <fullName>Tailored Nutrition</fullName>
            </value>
            <value>
                <fullName>Adultos (UTI-STROKE)</fullName>
            </value>
            <value>
                <fullName>Adultos (Oncologia)</fullName>
            </value>
            <value>
                <fullName>Adultos (IISS + Onco)</fullName>
            </value>
            <value>
                <fullName>Adultos (Instituciones)</fullName>
            </value>
            <value>
                <fullName>Adultos (Comunidad)</fullName>
            </value>
            <value>
                <fullName>Adultos (IISS + Comunidad)</fullName>
            </value>
            <value>
                <fullName>Digestivos</fullName>
            </value>
            <value>
                <fullName>Desafíos del crecimiento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Módulo</label>
    <referenceTo>Modulo__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/N_SHIP_TO__c.field-meta.xml
<CustomField>
    <fullName>N_SHIP_TO__c</fullName>
    <label>N° SHIP-TO</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/N_SOLD_TO__c.field-meta.xml
<CustomField>
    <fullName>N_SOLD_TO__c</fullName>
    <label>N° SOLD-TO</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Modulo__c/Modulo__c.object-meta.xml
<CustomObject>
    <label>Módulo</label>
    <nameField>
        <label>Nombre de Modulo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Módulos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Modulo__c/fields/N_de_Material__c.field-meta.xml
<CustomField>
    <fullName>N_de_Material__c</fullName>
    <label>N° de Material</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/Modulo_de_paciente__c.object-meta.xml
<CustomObject>
    <label>Modulo de paciente</label>
    <nameField>
        <displayFormat>MDP-{0000}</displayFormat>
        <label>Nro de Modulo de paciente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modulos de paciente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Fecha_de_despacho__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_despacho__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <inlineHelpText>Fecha en la cual le debe llegar el pedido al operador logístico.</inlineHelpText>
    <label>Fecha de despacho</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modulo</label>
    <referenceTo>Modulo__c</referenceTo>
    <relationshipLabel>Modulos de paciente</relationshipLabel>
    <relationshipName>Modulos_de_paciente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/N_de_Material__c.field-meta.xml
<CustomField>
    <fullName>N_de_Material__c</fullName>
    <formula>TEXT(Modulo__r.N_de_Material__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>N° de Material</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/N_SHIP_TO__c.field-meta.xml
<CustomField>
    <fullName>N_SHIP_TO__c</fullName>
    <formula>Cuenta__r.N_SHIP_TO__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>N° SHIP-TO</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/N_SOLD_TO__c.field-meta.xml
<CustomField>
    <fullName>N_SOLD_TO__c</fullName>
    <formula>Cuenta__r.PersonContact.Obra_social__r.N_SOLD_TO__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>N° SOLD-TO</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Nro_de_autorizacion__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_autorizacion__c</fullName>
    <label>Nro de autorización</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Obra_Social_Tratamiento__c.field-meta.xml
<CustomField>
    <fullName>Obra_Social_Tratamiento__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Trae la obra social del tratamiento asociado al modulo</description>
    <inlineHelpText>Este campo se autocompleta con la información del tratamiento.</inlineHelpText>
    <label>Obra Social Tratamiento</label>
    <referenceTo>Tratamiento__c</referenceTo>
    <relationshipLabel>Modulos de paciente</relationshipLabel>
    <relationshipName>Modulos_de_paciente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Valor_total_pesos__c.field-meta.xml
<CustomField>
    <fullName>Valor_total_pesos__c</fullName>
    <label>Valor total</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Modulo_Jitterbit__c/Modulo_Jitterbit__c.object-meta.xml
<CustomObject>
    <label>Modulo Jitterbit</label>
    <nameField>
        <label>Nombre de Modulo Jitterbit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modulos Jitterbit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Modulo_Jitterbit__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <label>Material</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Modulo_Jitterbit__c/fields/Modulo_de_paciente__c.field-meta.xml
<CustomField>
    <fullName>Modulo_de_paciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modulo de paciente</label>
    <referenceTo>Modulo_de_paciente__c</referenceTo>
    <relationshipLabel>Modulos Jitterbit</relationshipLabel>
    <relationshipName>Modulos_Jitterbit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Area_Terapeutica__c.field-meta.xml
<CustomField>
    <fullName>Area_Terapeutica__c</fullName>
    <description>Área Terapéutica a la cual pertenece el producto</description>
    <inlineHelpText>Área Terapéutica a la cual pertenece el producto</inlineHelpText>
    <label>Área Terapéutica</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_Terapeutica</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Modulo</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Patologia__c.field-meta.xml
<CustomField>
    <fullName>Patologia__c</fullName>
    <label>Patología</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Producto_de_modulo__c/Producto_de_modulo__c.object-meta.xml
<CustomObject>
    <label>Producto de módulo</label>
    <nameField>
        <displayFormat>PDM-{0000}</displayFormat>
        <label>Nro de Producto de módulo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos de módulo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Producto_de_modulo__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <label>Cantidad</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Producto_de_modulo__c/fields/Modulo_de_paciente__c.field-meta.xml
<CustomField>
    <fullName>Modulo_de_paciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Módulo de paciente</label>
    <referenceTo>Modulo_de_paciente__c</referenceTo>
    <relationshipName>Planes_de_cuidado</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tratamiento__c/Tratamiento__c.object-meta.xml
<CustomObject>
    <label>Tratamiento</label>
    <nameField>
        <displayFormat>TRAT-{0000}</displayFormat>
        <label>Nro de Tratamiento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tratamientos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tratamiento__c/fields/Area_terapeutica__c.field-meta.xml
<CustomField>
    <fullName>Area_terapeutica__c</fullName>
    <label>Área terapéutica</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alergia</fullName>
            </value>
            <value>
                <fullName>Desafíos del crecimiento</fullName>
            </value>
            <value>
                <fullName>Dieta Cetogénica</fullName>
            </value>
            <value>
                <fullName>Digestivos</fullName>
            </value>
            <value>
                <fullName>Disfagia</fullName>
            </value>
            <value>
                <fullName>Malnutrición</fullName>
            </value>
            <value>
                <fullName>Metabólicos</fullName>
            </value>
            <value>
                <fullName>NEG</fullName>
            </value>
            <value>
                <fullName>Oncología</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tratamiento__c/fields/Patologia__c.field-meta.xml
<CustomField>
    <fullName>Patologia__c</fullName>
    <label>Patología</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Area_terapeutica__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abetalipoproteinemia</fullName>
            </value>
            <value>
                <fullName>Acidemia metilmalonica/propionica</fullName>
            </value>
            <value>
                <fullName>Aciduria Arginosucinica</fullName>
            </value>
            <value>
                <fullName>Aciduria Glutarica</fullName>
            </value>
            <value>
                <fullName>ACV Hemorragíco (Accidente cerebrovascular)</fullName>
            </value>
            <value>
                <fullName>ACV Isquemico (Accidente cerebrovascular)</fullName>
            </value>
            <value>
                <fullName>Adrenoleucodistrofia</fullName>
            </value>
            <value>
                <fullName>Alergia a la Proteina de leche de vaca (APLV)</fullName>
            </value>
            <value>
                <fullName>Alzheimer</fullName>
            </value>
            <value>
                <fullName>Anorexia</fullName>
            </value>
            <value>
                <fullName>Asma</fullName>
            </value>
            <value>
                <fullName>Bajo peso</fullName>
            </value>
            <value>
                <fullName>Bulimia</fullName>
            </value>
            <value>
                <fullName>Cáncer de origen primario desconocido</fullName>
            </value>
            <value>
                <fullName>Cardiopatía congénita</fullName>
            </value>
            <value>
                <fullName>Cirrosis Hepatica</fullName>
            </value>
            <value>
                <fullName>Cirugía Aparato genitourinario</fullName>
            </value>
            <value>
                <fullName>Cirugía de cabeza y cuello</fullName>
            </value>
            <value>
                <fullName>Cirugía Gastrointestinal</fullName>
            </value>
            <value>
                <fullName>Cólicos/Constipación</fullName>
            </value>
            <value>
                <fullName>Complejos Mitocondriales tipo 1</fullName>
            </value>
            <value>
                <fullName>Deficiencia del transportador de Glucosa (GLUT 1)</fullName>
            </value>
            <value>
                <fullName>Deficiencia de piruvato deshidrogenasa (PDH)</fullName>
            </value>
            <value>
                <fullName>Demencia otros tipos</fullName>
            </value>
            <value>
                <fullName>Demencia senil</fullName>
            </value>
            <value>
                <fullName>Desnutrición</fullName>
            </value>
            <value>
                <fullName>Desnutrición Asociada a enfermedad</fullName>
            </value>
            <value>
                <fullName>Deterioro cognitivo crónico</fullName>
            </value>
            <value>
                <fullName>DGG (Deficiencia de Glucosa/Galactosa)</fullName>
            </value>
            <value>
                <fullName>Diabetes (DBT)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Area_Terapeutica.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dieta Cetogénica</fullName>
    </customValue>
    <customValue>
        <fullName>Metabólicos</fullName>
    </customValue>
    <customValue>
        <fullName>Malnutrición</fullName>
    </customValue>
    <customValue>
        <fullName>Disfagia</fullName>
    </customValue>
    <customValue>
        <fullName>Oncología</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia</fullName>
    </customValue>
    <customValue>
        <fullName>Digestivos</fullName>
    </customValue>
    <customValue>
        <fullName>Desafíos del crecimiento</fullName>
    </customValue>
    <customValue>
        <fullName>Terapia Cetogénica</fullName>
        <isActive>false</isActive>
        <label>Terapia Cetogénica</label>
    </customValue>
    <masterLabel>Áreas Terapéuticas</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GenerateXmlModuloController_test.cls
@isTest
public class GenerateXmlModuloController_test {
    
    @isTest
    static void siSeGeneraUnXMLSeActualizaElEstadoDelModuloDePaciente(){
        
        Account accTest = Build.anAccountPacienteBestCare()
            .withLastName('BestCare')
            .withAreaTerapeutica('Alergia')
            .withEstadoDePaciente('En tratamiento')
            .withSubestadoDePaciente('Tratamiento Efectivo')
            .build();
        accTest.N_SHIP_TO__c = '456789';
        
        insert accTest;
        
        Account accObraSocial = Build.anAccountObrasocial()
            .withName('Name Test')
            .withDNI('12346789')
            .withCanalParaConsumidorBaby('Farmacias')
            .build();
        accObraSocial.N_SOLD_TO__c = '789456';       
        insert accObraSocial;
        
        Tratamiento__c Tratamiento = Build.aTratamientoTratamientoBestCare()
            .withObraSocial(accObraSocial)
            .withAccount(accTest)
            .build();
            Tratamiento.Area_terapeutica__c = 'Alergia';
        Tratamiento.Patologia__c = 'Asma';
        insert tratamiento;
        
        Modulo__c testModulo = new modulo__c();
        testModulo.Name = 'Alergia';
        testModulo.N_de_Material__c = 123456;
        insert testModulo;
        
        Product2 prdTest = new Product2();
        prdTest.Name = 'Producto prueba';
        
        insert PrdTest;
        
        
        Modulo_de_paciente__c mdpTest= Build.aModulodepaciente()
            .withDuracion(5)
            .withModulodesde(Date.newInstance(2020, 2, 13))
            .withEstado('Activo')
            .withCuenta(accTest)
            .build();
        mdpTest.Modulo__c= testModulo.id;
        mdpTest.Obra_Social_Tratamiento__c=tratamiento.id;
        mdpTest.Fecha_de_despacho__c = System.today();
        mdpTest.Valor_total_pesos__c = 4500;
        mdpTest.Nro_de_autorizacion__c = '12346578';
        
        insert mdpTest;
        
        Producto_de_modulo__c pdmTest = new Producto_de_modulo__c();
        pdmTest.Cantidad__c = '2';
        pdmTest.Formula__c = prdTest.id;
        pdmTest.Modulo_de_paciente__c = mdpTest.id;
        
        insert pdmTest;
        
        PageReference pageRef = Page.GenerateCsvFromModuloDePaciente;
        Test.setCurrentPage(pageRef);
        
        pageRef.getParameters().put('Id', String.valueOf(mdpTest.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(mdpTest);
        
        Test.startTest();
        GenerateXmlModuloController gXml= new GenerateXmlModuloController(sc);
        gXml.insertXml();
        Test.stopTest();
        
        Modulo_de_paciente__c mdpDb = [
            SELECT id,Estado_de_modulo__c
            FROM Modulo_de_paciente__c
            WHERE id =:mdpTest.id];
        
        System.assertEquals('Reservado', mdpDb.Estado_de_modulo__c);
    }    
    
    
    @isTest
    static void siSeGeneraUnXMLperoFaltaAlgunoDeLosCamposObligatorios(){
        
        Account accTest = Build.anAccountPacienteBestCare()
            .withLastName('BestCare')
            .withAreaTerapeutica('Alergia')
            .withEstadoDePaciente('En tratamiento')
            .withSubestadoDePaciente('Tratamiento Efectivo')
            .build();
        
        insert accTest;
        
        Account accObraSocial = Build.anAccountObrasocial()
            .withName('Name Test')
            .withDNI('12346789')
            .withCanalParaConsumidorBaby('Farmacias')
            .build();
        
        insert accObraSocial;
        
        Tratamiento__c Tratamiento = Build.aTratamientoTratamientoBestCare()
            .withObraSocial(accObraSocial)
            .withAccount(accTest)
            .build();
            Tratamiento.Area_terapeutica__c = 'Alergia';
            Tratamiento.Patologia__c = 'Asma';
        insert tratamiento;
        
        Modulo__c testModulo = new modulo__c();
        testModulo.Name = 'Alergia';
        insert testModulo;
        
        Product2 prdTest = new Product2();
        prdTest.Name = 'Producto prueba';
        
        insert PrdTest;
        
        
        Modulo_de_paciente__c mdpTest= Build.aModulodepaciente()
            .withDuracion(5)
            .withModulodesde(Date.newInstance(2020, 2, 13))
            .withEstado('Activo')
            .withCuenta(accTest)
            .build();
        mdpTest.Modulo__c= testModulo.id;
        mdpTest.Obra_Social_Tratamiento__c=tratamiento.id;
        mdpTest.Fecha_de_despacho__c = System.today();
        
        insert mdpTest;
        
        Producto_de_modulo__c pdmTest = new Producto_de_modulo__c();
        pdmTest.Cantidad__c = '2';
        pdmTest.Formula__c = prdTest.id;
        pdmTest.Modulo_de_paciente__c = mdpTest.id;
        
        insert pdmTest;
        
        PageReference pageRef = Page.GenerateCsvFromModuloDePaciente;
        Test.setCurrentPage(pageRef);
        
        pageRef.getParameters().put('Id', String.valueOf(mdpTest.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(mdpTest);
        
        Test.startTest();
        GenerateXmlModuloController gXml= new GenerateXmlModuloController(sc);
        gXml.insertXml();
        Test.stopTest();
        
        Modulo_de_paciente__c mdpDb = [
            SELECT id,Estado_de_modulo__c
            FROM Modulo_de_paciente__c
            WHERE id =:mdpTest.id];
        
        System.assertNotEquals('Reservado', mdpDb.Estado_de_modulo__c);
    }    
    
    @isTest
    static void siSeIntentaGeneraUnXMLDuplicado(){
        
        Account accTest = Build.anAccountPacienteBestCare()
            .withLastName('BestCare')
            .withAreaTerapeutica('Alergia')
            .withEstadoDePaciente('En tratamiento')
            .withSubestadoDePaciente('Tratamiento Efectivo')
            .build();
        accTest.N_SHIP_TO__c = '456789';
        
        insert accTest;
        
        Account accObraSocial = Build.anAccountObrasocial()
            .withName('Name Test')
            .withDNI('12346789')
            .withCanalParaConsumidorBaby('Farmacias')
            .build();
        accObraSocial.N_SOLD_TO__c = '789456';       
        insert accObraSocial;
        
        Tratamiento__c Tratamiento = Build.aTratamientoTratamientoBestCare()
            .withObraSocial(accObraSocial)
            .withAccount(accTest)
            .build();
            Tratamiento.Area_terapeutica__c = 'Alergia';
            Tratamiento.Patologia__c = 'Asma';
        insert tratamiento;
        
        Modulo__c testModulo = new modulo__c();
        testModulo.Name = 'Alergia';
        testModulo.N_de_Material__c = 123456;
        insert testModulo;
        
        Product2 prdTest = new Product2();
        prdTest.Name = 'Producto prueba';
        
        insert PrdTest;
        
        
        Modulo_de_paciente__c mdpTest= Build.aModulodepaciente()
            .withDuracion(5)
            .withModulodesde(Date.newInstance(2020, 2, 13))
            .withEstado('Activo')
            .withCuenta(accTest)
            .build();
        mdpTest.Modulo__c= testModulo.id;
        mdpTest.Obra_Social_Tratamiento__c=tratamiento.id;
        mdpTest.Fecha_de_despacho__c = System.today();
        mdpTest.Valor_total_pesos__c = 4500;
        mdpTest.Nro_de_autorizacion__c = '12346578';
        
        insert mdpTest;
        
        Producto_de_modulo__c pdmTest = new Producto_de_modulo__c();
        pdmTest.Cantidad__c = '2';
        pdmTest.Formula__c = prdTest.id;
        pdmTest.Modulo_de_paciente__c = mdpTest.id;
        
        insert pdmTest;
        
        Modulo_Jitterbit__c newModulo1 = new Modulo_Jitterbit__c();
        newModulo1.Modulo_de_paciente__c = mdpTest.id;
        newModulo1.Name = 'MDP - Producto test';
        newModulo1.Material__c = pdmTest.Id_de_SAP__c;
        
        insert newmodulo1;
        
        PageReference pageRef = Page.GenerateCsvFromModuloDePaciente;
        Test.setCurrentPage(pageRef);
        
        pageRef.getParameters().put('Id', String.valueOf(mdpTest.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(mdpTest);
        
        Test.startTest();
        GenerateXmlModuloController gXml= new GenerateXmlModuloController(sc);
        gXml.insertXml();
        Test.stopTest();
        
        Modulo_de_paciente__c mdpDb = [
            SELECT id,Estado_de_modulo__c
            FROM Modulo_de_paciente__c
            WHERE id =:mdpTest.id];
        
        System.assertNotEquals('Reservado', mdpDb.Estado_de_modulo__c);
    }      
}