force-app/main/default/objects/Account/fields/Bloqueo__c.field-meta.xml
<CustomField>
    <fullName>Bloqueo__c</fullName>
    <label>Bloqueo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z2</fullName>
            </value>
            <value>
                <fullName>Vacio</fullName>
                <isActive>false</isActive>
                <label>Vacio</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Campo donde se especifica la organización de ventas perteneciente.</description>
    <label>Sales organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_PlantillaDeProductos__c/Dan360_PlantillaDeProductos__c.object-meta.xml
<CustomObject>
    <description>Objetos en donde se almacenarán las plantillas de los productos.</description>
    <label>Plantilla de Productos</label>
    <nameField>
        <label>Plantilla</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantillas de Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_PlantillaDeProductos__c/fields/Dan360_UnidadNegocio__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadNegocio__c</fullName>
    <description>Se refiere al negocio donde se generará una transacción, en donde impactará la venta de un producto.</description>
    <label>Unidad de Negocio</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_UnidadDeNegocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/Dan360_ProductoPorPlantilla__c.object-meta.xml
<CustomObject>
    <label>Producto por Plantilla</label>
    <nameField>
        <displayFormat>PrdXPla-{0000}</displayFormat>
        <label>Producto por plantilla</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos por Plantillas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/fields/Dan360_PlantillaProductos__c.field-meta.xml
<CustomField>
    <fullName>Dan360_PlantillaProductos__c</fullName>
    <description>Nombre o código de la plantilla creada para el cliente, en donde están registrados los productos que puede adquirir.</description>
    <label>Plantilla de Productos</label>
    <referenceTo>Dan360_PlantillaDeProductos__c</referenceTo>
    <relationshipLabel>Productos por Plantillas</relationshipLabel>
    <relationshipName>Productos_por_Plantillas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/fields/Dan360_Producto__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nombre o código del artículo que podrá ser adquirido por los clientes.</description>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Productos por Plantillas</relationshipLabel>
    <relationshipName>Productos_por_Plantillas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/fields/Dan360_UnidadDeMedida__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadDeMedida__c</fullName>
    <description>Se refiere al negocio donde se generará una transacción, en donde impactará la venta de un producto.</description>
    <label>Unidad de Medida</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trade Unit</fullName>
            </value>
            <value>
                <fullName>Unidad</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/fields/Dan360_Vigencia__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Vigencia__c</fullName>
    <description>Rango de fecha en el que un producto puede ser adquirido.</description>
    <label>Vigencia hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/fields/Dan360_VigenciaDesde__c.field-meta.xml
<CustomField>
    <fullName>Dan360_VigenciaDesde__c</fullName>
    <description>Vigencia a partír de la cual estará el producto en la plantilla.</description>
    <label>Vigencia desde</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductSalesArea__c/Dan360_ProductSalesArea__c.object-meta.xml
<CustomObject>
    <label>Product Sales Area</label>
    <nameField>
        <label>Nombre de Product Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sales Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_ProductSalesArea__c/fields/Bloqueo__c.field-meta.xml
<CustomField>
    <fullName>Bloqueo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bloqueo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductSalesArea__c/fields/Dan360_Producto__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Sales Area</relationshipLabel>
    <relationshipName>Product_Sales_Area</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductSalesArea__c/fields/Dan360_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesArea__c</fullName>
    <label>Sales Area</label>
    <referenceTo>Dan360_SalesArea__c</referenceTo>
    <relationshipLabel>Product Sales Area</relationshipLabel>
    <relationshipName>Product_Sales_Area</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/Dan360_SalesArea__c.object-meta.xml
<CustomObject>
    <description>Sales Area</description>
    <label>Sales Area</label>
    <nameField>
        <label>Nombre de Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Sales Organization</description>
    <label>Sales Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Dan360_UnidadDeNegocio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5800</fullName>
        <label>AMN</label>
    </customValue>
    <customValue>
        <fullName>5771</fullName>
        <label>NuBa</label>
    </customValue>
    <description>Determina a qué unidad de negocio se genera un pedido.</description>
    <masterLabel>Unidad de Negocio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddProductsToTemplateController.cls
public with sharing class AddProductsToTemplateController {
    @AuraEnabled
    public static List<WrapProduct> getProducts(String recordId) {
        List<WrapProduct> listProducts = new List<WrapProduct>();

        List<String> salesAreaIds = new List<String>();
        List<String> productSalesAreaRecordIds = new List<String>();
        Set<String> productsToFilter = new Set<String>();        
                
        List<Dan360_PlantillaDeProductos__c> plantillaDeProductos = [
            SELECT Id, Dan360_UnidadNegocio__c
            FROM Dan360_PlantillaDeProductos__c
            WHERE Id = :recordId
            LIMIT 1
        ];


        String unidadDeNegocio = 'Random value';
        for (Dan360_PlantillaDeProductos__c aplantillaDeProductos : plantillaDeProductos) {
            unidadDeNegocio = plantillaDeProductos[0].Dan360_UnidadNegocio__c;
        }
        //Get all Sales Area records where Sales Organization = Unidad de Negocio
        List<Dan360_SalesArea__c> salesAreaRecords = [
            SELECT Id
            FROM Dan360_SalesArea__c
            WHERE Dan360_SalesOrganization__c = :unidadDeNegocio
        ];
        for(Dan360_SalesArea__c salesArea : salesAreaRecords){
            salesAreaIds.add(salesArea.Id);
        }

        //Get Product Sales Area records related to the Sales Area records we queried and Bloqueo = false
        List<Dan360_ProductSalesArea__c> productSalesAreaRecords = [
            SELECT Id, Dan360_Producto__c
            FROM Dan360_ProductSalesArea__c
            WHERE Bloqueo__c = false
                AND Dan360_SalesArea__c IN :salesAreaIds
        ];

        for(Dan360_ProductSalesArea__c productSalesArea : productSalesAreaRecords){
            productSalesAreaRecordIds.add(productSalesArea.Dan360_Producto__c);
        }

        List<Product2> productsToAddToListOfLists = [
            SELECT Id, Name, ProductCode
            FROM Product2
            WHERE Id IN :productSalesAreaRecordIds
        ];
       
        // get products already exist in template
        List<Dan360_ProductoPorPlantilla__c> productsAlreadyExist = [
            SELECT ID, Dan360_Producto__c 
            FROM Dan360_ProductoPorPlantilla__c
            WHERE Dan360_PlantillaProductos__c = :recordId
        ];
       
        
        
        for (Dan360_ProductoPorPlantilla__c aProduct : productsAlreadyExist) {
            productsToFilter.add(aProduct.Dan360_Producto__c);
        }

        
        // filter products alraedy exist in template
        for (Product2 aProduct : productsToAddToListOfLists) {           
            if (!productsToFilter.contains(aProduct.Id)) {                
                
                WrapProduct product = new WrapProduct();
                product.name = aProduct.Name;
                product.productoId = aProduct.Id;
                product.productCode = aProduct.ProductCode;
                product.unidadMedida = '';
                product.vigenciaDesde = null;
                product.vigenciaHasta = null;
                
                
                listProducts.add(product);
            }
        }      
        
                
        return listProducts;        
    }
    @AuraEnabled
    public static List<Object> getPicklistValues() {
        // get unidad de medida picklist values
        Schema.DescribeFieldResult objFieldDescribe = Dan360_ProductoPorPlantilla__c.Dan360_UnidadDeMedida__c.getDescribe();
        List<Schema.PicklistEntry> lstPickListValues = objFieldDescribe.getPickListValues();
        List<Map<String,String>> optiosValuesList = new List<Map<String,String>>();
        for (Schema.PicklistEntry objPickList : lstPickListValues) {
            Map<String,String> option = new Map<String,String>();
            option.put('label', objPickList.getLabel() );
            option.put('value', objPickList.getValue() );
                
            optiosValuesList.add(option);
            System.debug(option);
        }
       
        return optiosValuesList;
    }

    @AuraEnabled
    public static String saveProducts(string listProducts, String recordId){
        System.debug('listProducts: '+listProducts);
        System.debug('recordId: '+recordId);
        List<Dan360_ProductoPorPlantilla__c> listNewProductPerTemplate = new List<Dan360_ProductoPorPlantilla__c>();
        List<AddProductsToTemplateController.WrapProduct> productos =
            (List<AddProductsToTemplateController.WrapProduct>) JSON.deserialize(
                listProducts,
                List<AddProductsToTemplateController.WrapProduct>.class
        );


        for(AddProductsToTemplateController.WrapProduct product : productos){
           
            Dan360_ProductoPorPlantilla__c aNewProducPerTemplate = new Dan360_ProductoPorPlantilla__c(
                Dan360_PlantillaProductos__c = recordId,
                Dan360_Producto__c = product.productoId,
                Dan360_UnidadDeMedida__c = product.unidadMedida,
                Dan360_VigenciaDesde__c = product.vigenciaDesde,
                Dan360_Vigencia__c = product.vigenciaHasta
            );
            
            listNewProductPerTemplate.add(aNewProducPerTemplate);
        }
        String estado;
        Database.SaveResult[] saveResultList = Database.insert(listNewProductPerTemplate, true);
        for (Database.SaveResult sr : saveResultList) {
            if (sr.isSuccess()) {
                String exito = 'Los productos seleccionados se han agregado correctamente';
                estado = exito;
            }
            else {
                String errorList;
                for(Database.Error err : sr.getErrors()) {
                    System.debug('The following error has occurred.');
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Account fields that affected this error: ' + err.getFields());
                    errorList += err.getStatusCode() + ': ' + err.getMessage() + '/br';
                }
                estado = errorList;
            }
        }

        return estado;
    }

    public class WrapProduct{
        @AuraEnabled
        public String name { get;set;}      
        @AuraEnabled
        public String unidadMedida { get;set;}        
        @AuraEnabled
        public String productoId { get;set;}
        @AuraEnabled
        public String productCode { get;set;}
        @AuraEnabled
        public Date vigenciaDesde { get;set;}
        @AuraEnabled
        public Date vigenciaHasta { get;set;}
        // public WrapProduct(String name, String unidadMedida, String productoId, String productCode, Date vigenciaDesde,  Date vigenciaHasta){
        //     this.name = name;
        //     this.unidadMedida = '';
        //     this.productoId = productoId;
        //     this.productCode = productCode;
        //     this.vigenciaDesde = null;
        //     this.vigenciaHasta = null;
        // }
    }
    
}