force-app/main/default/objects/Account/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <label>Calle</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_postal__c</fullName>
    <label>Codigo postal</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <label>DNI</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <formula>Codigo_postal_service__r.Localidad__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Localidad</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Número</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Piso__c.field-meta.xml
<CustomField>
    <fullName>Piso__c</fullName>
    <label>Piso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primera_especialidad__c.field-meta.xml
<CustomField>
    <fullName>Primera_especialidad__c</fullName>
    <label>1era especialidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Especialidades</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <formula>Codigo_postal_service__r.Provincia__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provincia</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segunda_especialidad__c.field-meta.xml
<CustomField>
    <fullName>Segunda_especialidad__c</fullName>
    <label>2da Especialidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Especialidades</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tercera_especialidad__c.field-meta.xml
<CustomField>
    <fullName>Tercera_especialidad__c</fullName>
    <label>3era Especialidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Especialidades</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Dan360_Institucion.recordType-meta.xml
<RecordType>
    <fullName>Dan360_Institucion</fullName>
    <active>true</active>
    <label>Institución</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Institucion.recordType-meta.xml
<RecordType>
    <fullName>Institucion</fullName>
    <active>true</active>
    <label>Institución</label>
</RecordType>

force-app/main/default/objects/Codigo_Postal__c/Codigo_Postal__c.object-meta.xml
<CustomObject>
    <label>Código Postal</label>
    <nameField>
        <label>Código Postal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Códigos Postales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Codigo_Postal__c/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <label>Localidad</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Codigo_Postal__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_Matricula__c/Dan360_Matricula__c.object-meta.xml
<CustomObject>
    <description>Objeto que guarda las matrículas de los profesionales de la salud.</description>
    <label>Matrícula</label>
    <nameField>
        <displayFormat>MAT-{00000}</displayFormat>
        <label>Matricula Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matrículas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Matricula__c/fields/Numero_de_matricula__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_matricula__c</fullName>
    <label>Numero de matricula</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_Matricula__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profesional de la Salud</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Otro Profesional</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Matrículas</relationshipLabel>
    <relationshipName>Matriculas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Matricula__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Provincias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Localidad__c/Localidad__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <label>Nombre de Localidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Localidad__c/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <label>Codigo Postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Localidad__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <formula>TEXT(Municipio__r.Descripcion_Provincia__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provincia</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Especialidades.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administración</fullName>
    </customValue>
    <customValue>
        <fullName>Administrativo de Farmacia</fullName>
    </customValue>
    <customValue>
        <fullName>Alergista</fullName>
    </customValue>
    <customValue>
        <fullName>Auditor</fullName>
    </customValue>
    <customValue>
        <fullName>Bioquímico</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiólogo</fullName>
    </customValue>
    <customValue>
        <fullName>Cirugía</fullName>
    </customValue>
    <customValue>
        <fullName>Comprador</fullName>
    </customValue>
    <customValue>
        <fullName>Contratador</fullName>
    </customValue>
    <customValue>
        <fullName>Contratos y Prestaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Convenios</fullName>
    </customValue>
    <customValue>
        <fullName>Coord. Internación Domiciliaria</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetólogo</fullName>
    </customValue>
    <customValue>
        <fullName>Director</fullName>
    </customValue>
    <customValue>
        <fullName>Endocrinólogo</fullName>
    </customValue>
    <customValue>
        <fullName>Enfermero</fullName>
    </customValue>
    <customValue>
        <fullName>Farmaceútico</fullName>
    </customValue>
    <customValue>
        <fullName>Fisiatra</fullName>
    </customValue>
    <customValue>
        <fullName>Fonoaudiólogo</fullName>
    </customValue>
    <customValue>
        <fullName>Gastroenterólogo</fullName>
    </customValue>
    <customValue>
        <fullName>Genetista</fullName>
    </customValue>
    <customValue>
        <fullName>Gerente Comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Gerontólogo/Geriatra</fullName>
    </customValue>
    <customValue>
        <fullName>Inmunología</fullName>
    </customValue>
    <customValue>
        <fullName>Jefe de Compras</fullName>
    </customValue>
    <customValue>
        <fullName>Kinesiologo</fullName>
    </customValue>
    <customValue>
        <fullName>Kinesiólogo</fullName>
    </customValue>
    <customValue>
        <fullName>Medico</fullName>
    </customValue>
    <customValue>
        <fullName>Médico Clínico</fullName>
    </customValue>
    <customValue>
        <fullName>Medico Familiar</fullName>
    </customValue>
    <masterLabel>Especialidades</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Provincias.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Buenos Aires</fullName>
    </customValue>
    <customValue>
        <fullName>CABA</fullName>
    </customValue>
    <customValue>
        <fullName>Catamarca</fullName>
    </customValue>
    <customValue>
        <fullName>Chaco</fullName>
    </customValue>
    <customValue>
        <fullName>Chubut</fullName>
    </customValue>
    <customValue>
        <fullName>Córdoba</fullName>
    </customValue>
    <customValue>
        <fullName>Corrientes</fullName>
    </customValue>
    <customValue>
        <fullName>Entre Ríos</fullName>
    </customValue>
    <customValue>
        <fullName>Formosa</fullName>
    </customValue>
    <customValue>
        <fullName>Jujuy</fullName>
    </customValue>
    <customValue>
        <fullName>La Pampa</fullName>
    </customValue>
    <customValue>
        <fullName>La Rioja</fullName>
    </customValue>
    <customValue>
        <fullName>Mendoza</fullName>
    </customValue>
    <customValue>
        <fullName>Misiones</fullName>
    </customValue>
    <customValue>
        <fullName>Neuquén</fullName>
    </customValue>
    <customValue>
        <fullName>Río Negro</fullName>
    </customValue>
    <customValue>
        <fullName>Salta</fullName>
    </customValue>
    <customValue>
        <fullName>San Juan</fullName>
    </customValue>
    <customValue>
        <fullName>San Luis</fullName>
    </customValue>
    <customValue>
        <fullName>Santa Cruz</fullName>
    </customValue>
    <customValue>
        <fullName>Santa Fe</fullName>
    </customValue>
    <customValue>
        <fullName>Santiago del Estero</fullName>
    </customValue>
    <customValue>
        <fullName>Tierra del Fuego</fullName>
    </customValue>
    <customValue>
        <fullName>Tucumán</fullName>
    </customValue>
    <masterLabel>Provincias</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WSValidateData.cls
@RestResource(urlMapping='/info/*')
    global with sharing class WSValidateData {
        
        @HttpGet
        global static Respuesta doGet(){
            RestRequest req = RestContext.request;
            Respuesta respuesta = new Respuesta();
            Map<String, String> headers = new Map<String, String>();

            for(String header : req.headers.keySet()){
                headers.put(header.toLowerCase(),req.headers.get(header));
            }
            
            String sObjeto = headers.containsKey('objeto') ? headers.get('objeto') : null;
            String sName = headers.containsKey('name') ? headers.get('name') : null;
            String sCalle = headers.containsKey('calle') ? headers.get('calle') : null;
            String sLocalidad = headers.containsKey('localidad') ? headers.get('localidad') : null; 
            String sCP = headers.containsKey('codigoPostal') ? headers.get('codigoPostal') : null; 
            String sProvincia = headers.containsKey('provincia') ? headers.get('provincia') : null; 
            String sNumeroDeMatricula = headers.containsKey('matricula') ? headers.get('matricula') : null; 
            String sDni = headers.containsKey('dni') ? headers.get('dni') : null; 
            //comentarios para borrar
            System.debug('sObjeto::: ' + sObjeto);
            System.debug('sName::: ' + sName);
            System.debug('sCalle::: ' + sCalle);
            System.debug('sLocalidad::: ' + sLocalidad);
            System.debug('sNumeroDeMatricula::: ' + sNumeroDeMatricula);
            System.debug('sDni::: ' + sDni);

            if (sObjeto == 'institucion') {
                Id recordTypeInstitucion = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Dan360_Institucion').getRecordTypeId();
                String condicion = 'RecordTypeId = \'' + recordTypeInstitucion + '\''; 
                condicion += (String.isNotBlank(sName) ? ' AND Name = \'' + sName + '\'' : '');
                condicion += (String.isNotBlank(sCalle) ? ' AND BillingStreet = \'' + sCalle + '\'' : ''); //BillingStreet
                condicion += (String.isNotBlank(sLocalidad) ? ' AND BillingCity = \'' + sLocalidad + '\'' : '');//BillingCity
                condicion += (String.isNotBlank(sCP) ? ' AND BillingPostalCode = \'' + sCP + '\'' : '');//BillingPostalCode
                condicion += (String.isNotBlank(sProvincia) ? ' AND BillingState = \'' + sProvincia + '\'' : '');//BillingState

                String query = 'SELECT Id, LastName, FirstName, Name, OwnerId, Calle__c, Codigo_postal__c, Numero__c, Piso__c, Departamento__c, Localidad__c, Provincia__c, Phone, RecordType.Name, BillingStreet, BillingCity, BillingPostalCode, BillingState FROM Account WHERE ' +
                condicion;
                System.debug('query:::' + query);
                List<Account> accounts  = Database.query(query);
                if (accounts.size()>0) {
                    respuesta.rObject = accounts.get(0);
                    respuesta.status = 200;
                } else {
                    respuesta.status = 401;
                }
            }  else if (sObjeto == 'profesional de la salud') {
                Id recordTypeProfesional = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Profesional_de_la_Salud').getRecordTypeId(); 
                List<Dan360_Matricula__c> professionals = [SELECT Profesional__r.LastName, Profesional__r.FirstName, Profesional__r.Primera_especialidad__c, Profesional__r.Segunda_especialidad__c, Profesional__r.Tercera_especialidad__c 
                            FROM Dan360_Matricula__c 
                            WHERE Numero_de_matricula__c = :sNumeroDeMatricula AND Profesional__r.RecordTypeId = :recordTypeProfesional];
                if (professionals.size()>0) {
                    respuesta.rObject = professionals.get(0);
                    respuesta.status = 200;
                } else {
                    respuesta.status = 401;
                }
            } 
            else if (sObjeto == 'otro profesional') {
                Id recordTypeOtroProfesional = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Otro_Profesional').getRecordTypeId(); 
                List<Account> accounts = [SELECT Id, LastName, FirstName, Name, OwnerId, Primera_especialidad__c, Segunda_especialidad__c, Tercera_especialidad__c, VisMed_Areas_Terap_uticas__pc
                            FROM Account
                            WHERE DNI__c =: sDni AND RecordTypeId = :recordTypeOtroProfesional];
                if (accounts.size()>0) {
                    respuesta.rObject = accounts.get(0);
                    respuesta.status = 200;
                } else {
                    respuesta.status = 401;
                }
            } 
        return respuesta;
    }
    
    global class Respuesta {
        public Integer status {get; set;}
        public SObject rObject {get; set;}
    }
    
}