force-app/main/default/objects/Account/fields/Canal_para_Consumidor_Baby__c.field-meta.xml
<CustomField>
    <fullName>Canal_para_Consumidor_Baby__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Almacen</fullName>
            </value>
            <value>
                <fullName>Farmacias</fullName>
            </value>
            <value>
                <fullName>Farmacity</fullName>
            </value>
            <value>
                <fullName>Hipermarket</fullName>
            </value>
            <value>
                <fullName>MercadoLibre</fullName>
            </value>
            <value>
                <fullName>Nutrilon4</fullName>
            </value>
            <value>
                <fullName>Proximity</fullName>
            </value>
            <value>
                <fullName>Simplicity</fullName>
            </value>
            <value>
                <fullName>Supermercado</fullName>
            </value>
            <value>
                <fullName>Vital4</fullName>
            </value>
            <value>
                <fullName>La Sere va a tu casa</fullName>
            </value>
            <value>
                <fullName>Particular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EYN__c.field-meta.xml
<CustomField>
    <fullName>EYN__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Si pertenece a Enrich your nutrition</description>
    <label>EYN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_customer_oracle__c.field-meta.xml
<CustomField>
    <fullName>Id_customer_oracle__c</fullName>
    <externalId>true</externalId>
    <label>Id customer oracle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Institucion__c.field-meta.xml
<CustomField>
    <fullName>Institucion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Institución</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Institución</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Profesionales de la salud</relationshipLabel>
    <relationshipName>Profesionales_de_la_salud2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <formula>Codigo_postal_service__r.Localidad__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Localidad</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Localidad_look__c.field-meta.xml
<CustomField>
    <fullName>Localidad_look__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Localidad__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Propietario_3__c.field-meta.xml
<CustomField>
    <fullName>Propietario_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propietario 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuentas4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Propietario_adulto__c.field-meta.xml
<CustomField>
    <fullName>Propietario_adulto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup que se actualiza con el valor del accountTeamMember user.id</description>
    <label>Propietario 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuentas3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Propietario_Nicho__c.field-meta.xml
<CustomField>
    <fullName>Propietario_Nicho__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propietario 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuentas2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Cliente.recordType-meta.xml
<RecordType>
    <fullName>Cliente</fullName>
    <active>true</active>
    <description>Tipo de registro de cuenta para Danone Sales</description>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Institucion.recordType-meta.xml
<RecordType>
    <fullName>Institucion</fullName>
    <active>true</active>
    <label>Institución</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <formula>Codigo_Postal__r.Localidad__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Localidad</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Paciente__c.field-meta.xml
<CustomField>
    <fullName>Paciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paciente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contactos</relationshipLabel>
    <relationshipName>Contactos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Envio_sin_Cargo__c/Envio_sin_Cargo__c.object-meta.xml
<CustomObject>
    <label>Envío sin cargo</label>
    <nameField>
        <displayFormat>KIT-{00000}</displayFormat>
        <label>Nombre de Envio sin Cargo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Envíos sin cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Envio_sin_Cargo__c/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <formula>Paciente__r.Localidad_look__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Localidad</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Envio_sin_Cargo__c/fields/Paciente__c.field-meta.xml
<CustomField>
    <fullName>Paciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paciente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Envios_sin_Cargo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Localidad__c/Localidad__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <label>Nombre de Localidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Localidad__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Localidades</relationshipLabel>
    <relationshipName>Localidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Municipio__c/fields/Descripcion_Provincia__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Provincia__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MISIONES</fullName>
            </value>
            <value>
                <fullName>ENTRE RIOS</fullName>
            </value>
            <value>
                <fullName>BUENOS AIRES</fullName>
            </value>
            <value>
                <fullName>MENDOZA</fullName>
            </value>
            <value>
                <fullName>FORMOSA</fullName>
            </value>
            <value>
                <fullName>CORRIENTES</fullName>
            </value>
            <value>
                <fullName>CHACO</fullName>
            </value>
            <value>
                <fullName>SAN LUIS</fullName>
            </value>
            <value>
                <fullName>SALTA</fullName>
            </value>
            <value>
                <fullName>SANTA FÉ</fullName>
            </value>
            <value>
                <fullName>JUJUY</fullName>
            </value>
            <value>
                <fullName>SANTIAGO DEL ESTERO</fullName>
            </value>
            <value>
                <fullName>TUCUMÁN</fullName>
            </value>
            <value>
                <fullName>LA PAMPA</fullName>
            </value>
            <value>
                <fullName>CHUBUT</fullName>
            </value>
            <value>
                <fullName>SANTA CRUZ</fullName>
            </value>
            <value>
                <fullName>RIO NEGRO</fullName>
            </value>
            <value>
                <fullName>SAN JUAN</fullName>
            </value>
            <value>
                <fullName>CÓRDOBA</fullName>
            </value>
            <value>
                <fullName>LA RIOJA</fullName>
            </value>
            <value>
                <fullName>CATAMARCA</fullName>
            </value>
            <value>
                <fullName>NEUQUEN</fullName>
            </value>
            <value>
                <fullName>TIERRA DEL FUEGO</fullName>
            </value>
            <value>
                <fullName>CAPITAL FEDERAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Producto_de_envio__c/Producto_de_envio__c.object-meta.xml
<CustomObject>
    <label>Producto de envío</label>
    <nameField>
        <displayFormat>PDE-{0000}</displayFormat>
        <label>Nro de Producto de Envío</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos de envío</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Producto_de_envio__c/fields/Envio_sin_cargo__c.field-meta.xml
<CustomField>
    <fullName>Envio_sin_cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Envío sin cargo</label>
    <referenceTo>Envio_sin_Cargo__c</referenceTo>
    <relationshipLabel>Productos de envío</relationshipLabel>
    <relationshipName>Productos_de_envio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Producto_de_envio__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Formula</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El valor no existe o no coinciden los criterios de filtro.</errorMessage>
        <filterItems>
            <field>Product2.Producto_SAP__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Productos de envío</relationshipLabel>
    <relationshipName>Productos_de_envio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountTest.cls
@isTest
public class AccountTest {
    
    @isTest
    Public static void creoCuentaTipoShipTo() {
        
        Account cuenta = Build.anAccountSucursaldeenvio()
            .withIdSucursalOracle('idTest')
            .withName('Name Test')
            .withTipoDeSucursal('SHIP_TO')
            .build();
        cuenta.Canal_para_Consumidor_Baby__c = 'Farmacias';
        test.startTest();
        insert cuenta;
        test.stopTest();
        
        Id sucursalEnvioRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Sucursal de envío').getRecordTypeId();
        
        Account nuevaCuenta = [SELECT RecordTypeId FROM Account WHERE Id = :cuenta.Id];
        
        System.assertEquals(sucursalEnvioRecTypeId, nuevaCuenta.RecordTypeId);
        
        
    }
    
    @isTest
    Public static void creoCuentaTipoBillTo() {
        
        Account cuenta = Build.anAccountSucursaldefacturacion()
            .withIdSucursalOracle('idTest')
            .withName('Name Test')
            .withTipoDeSucursal('BILL_TO')
            .build();
        cuenta.Canal_para_Consumidor_Baby__c = 'Farmacias';
        test.startTest();
        insert cuenta;
        test.stopTest();
        
        Id sucursalFactRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Sucursal de facturación').getRecordTypeId();
        
        Account nuevaCuenta = [SELECT RecordTypeId FROM Account WHERE Id = :cuenta.Id];
        
        System.assertEquals(sucursalFactRecTypeId, nuevaCuenta.RecordTypeId);
        
        
    }
    
    @isTest
    Public static void creoCuentaTipoCustomer() {
        
        Account cuenta = New Account();
        cuenta.Name = 'Prueba cuenta pedido';
        cuenta.Id_customer_oracle__c = 'aaa';
        cuenta.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Sucursal de envío').getRecordTypeId();
        cuenta.Canal_para_Consumidor_Baby__c = 'Farmacias';
        
        test.startTest();
        
        insert cuenta;
        
        test.stopTest();
        
        Id clienteRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente').getRecordTypeId();
        
        Account nuevaCuenta = [SELECT RecordTypeId FROM Account WHERE Id = :cuenta.Id];
        
        System.assertEquals(clienteRecTypeId, nuevaCuenta.RecordTypeId);
        
        
    }
    
    
    
    @isTest
    Public static void noDebeHaberDuplicadosEnLosPropietariosDeLaCUenta() {
        String status;
        Profile profileIdTest = [SELECT Id FROM Profile WHERE Name = 'Usuario de Platform estándar' LIMIT 1];
        
        User user1 = Build.aUser()
            .withUsername('test1test1@gmail.com')
            .withEmail('test1test1@gmail.com')
            .withAlias('Ts')
            .withTimeZoneSidKey('GMT')
            .withLocaleSidKey('en_US')
            .withLastName('test apellido')
            .withCommunityNickname('test123')
            .withEmailEncodingKey('UTF-8')
            .withProfileId(profileIdTest.id)
            .withLanguageLocaleKey('en_US')
            .Build();
        
        insert user1;
        
        User user2 = Build.aUser()
            .withUsername('test2test2@gmail.com')
            .withEmail('test2test2@gmail.com')
            .withAlias('Ts2')
            .withTimeZoneSidKey('GMT')
            .withLocaleSidKey('en_US')
            .withLastName('test apellido2')
            .withCommunityNickname('test1232')
            .withEmailEncodingKey('UTF-8')
            .withProfileId(profileIdTest.id)
            .withLanguageLocaleKey('en_US')
            .Build();
        insert user2;
        
        User user3 = Build.aUser()
            .withUsername('test3test2@gmail.com')
            .withEmail('test2te33t2@gmail.com')
            .withAlias('Ts3332')
            .withTimeZoneSidKey('GMT')
            .withLocaleSidKey('en_US')
            .withLastName('te3st apellido2')
            .withCommunityNickname('te3st1232')
            .withEmailEncodingKey('UTF-8')
            .withProfileId(profileIdTest.id)
            .withLanguageLocaleKey('en_US')
            .Build();
        
        insert user3;
        
        Account testAcc1 = new Account();
        testAcc1.Name = 'cuenta 1';
        testAcc1.Canal_para_Consumidor_Baby__c = 'Farmacias';
        testAcc1.Propietario_Nicho__c = user1.id;
        testAcc1.Propietario_adulto__c = null;
        testAcc1.Propietario_3__c = null;
        insert testAcc1;
        
        test.startTest();
        
        testAcc1.Propietario_adulto__c = user2.Id;
        testAcc1.Propietario_3__c = user3.Id;
        
        Database.SaveResult result = Database.update(testAcc1, false);
        
        
        test.stopTest();
        
        System.assert(result.isSuccess() == true);
    }
    @isTest
    Public static void siAgregoUnPropietarioTieneQueaparecerEnLaRelacionadaTambien() {
        String status;
        
        Profile profileIdTest = [SELECT Id FROM Profile WHERE Name = 'Usuario de Platform estándar' LIMIT 1];
        
        User user1 = Build.aUser()
            .withUsername('test1test1@gmail.com')
            .withEmail('test1test1@gmail.com')
            .withAlias('Ts')
            .withTimeZoneSidKey('GMT')
            .withLocaleSidKey('en_US')
            .withLastName('test apellido')
            .withCommunityNickname('test123')
            .withEmailEncodingKey('UTF-8')
            .withProfileId(profileIdTest.id)
            .withLanguageLocaleKey('en_US')
            .Build();
        
        insert user1;
        
        
        Account testAcc3 = new Account();
        testAcc3.Name = 'cuenta 3';
        testAcc3.Canal_para_Consumidor_Baby__c = 'Farmacias';
        
        
        insert testAcc3;
        
        test.startTest();
        
        testAcc3.Propietario_Nicho__c = user1.id;
        update testAcc3;
        
        
        test.stopTest();
        
        AccountTeamMember accountteamDb = [SELECT userID FROM AccountTeamMember where accountId = :testAcc3.id];
        
        
        System.assertEquals(testAcc3.Propietario_Nicho__c, accountteamDb.userId);
        
    }
    
    @isTest
    Public static void siEliminoUnPropietarioTieneQueeliminarseEnLaRelacionadaTambien() {
        String status;
        
        Profile profileIdTest = [SELECT Id FROM Profile WHERE Name = 'Usuario de Platform estándar' LIMIT 1];
        
        User user1 = Build.aUser()
            .withUsername('test1test1@gmail.com')
            .withEmail('test1test1@gmail.com')
            .withAlias('Ts')
            .withTimeZoneSidKey('GMT')
            .withLocaleSidKey('en_US')
            .withLastName('test apellido')
            .withCommunityNickname('test123')
            .withEmailEncodingKey('UTF-8')
            .withProfileId(profileIdTest.id)
            .withLanguageLocaleKey('en_US')
            .Build();
        
        insert user1;
        
        Account testAcc3 = new Account();
        testAcc3.Name = 'cuenta 3';
        testAcc3.Canal_para_Consumidor_Baby__c = 'Farmacias';
        testAcc3.Propietario_Nicho__c = user1.id;
        insert testAcc3;
        
        
        test.startTest();
        
        testAcc3.Propietario_Nicho__c = null;
        update testAcc3;
        
        test.stopTest();
        
        List<AccountTeamMember> accountteamDb = [SELECT userID FROM AccountTeamMember where accountId = :testAcc3.id];
        
        System.assertEquals(0, accountteamDb.size());
        
    }
    
    @isTest
    Public static void cargarUnPropietarioyDespuesCambiarlo() {
        List<User> usuarios = [
            SELECT Id
            FROM User
            WHERE Username LIKE '%testaccount@gmail.com'
        ];
        
        Account testAcc = new Account();
        testAcc.Name = 'cuenta actualizada';
        testAcc.Canal_para_Consumidor_Baby__c = 'Farmacias';
        testAcc.Propietario_Nicho__c = usuarios.get(0).id;
        insert testAcc;
        
        Test.startTest();
        testAcc.Propietario_Nicho__c = usuarios.get(1).id;
        update testAcc;
        Test.stopTest();
        
        
        List<AccountTeamMember> accountteamDb = [SELECT Id, userID FROM AccountTeamMember where accountId = :testAcc.id];
        List<Account> cuenta = [
            SELECT Id, Propietario_Nicho__c
            FROM Account
            WHERE Id = :testAcc.Id
        ];
        
        System.assertEquals(1, accountteamDb.size());
        
        System.assertEquals(usuarios.get(1).Id, cuenta.get(0).Propietario_Nicho__c);
        
    }
    
    /*@isTest
    Public static void siUnOperadorPartnerIntentaCargarUnaObraSocialQueNoEsDeMendozaDebeLanzarUnError() {
        String status;
        Municipio__c municipio = new Municipio__c();
        municipio.Descripcion_Provincia__c = 'MISIONES';
        Municipio.Name = 'MISIONES';
        insert municipio;
        
        Localidad__c localidad = new Localidad__c();
        Localidad.name='MISIONES';
        localidad.Municipio__c = municipio.id;
        insert localidad;

        Contact contacto = new Contact();
        contacto.LastName = 'Contacto';
        
        insert contacto;
        
        Account accObraSocial = Build.anAccountObrasocial()
            .withName('OB prueba')
            .withDNI('333')
            .withCanalParaConsumidorBaby('Farmacias')
            .build();
        accObraSocial.Localidad_look__c = localidad.id;
        
        insert accObraSocial;
        
        Profile profile = [
            SELECT Id,Name 
            FROM Profile 
            WHERE Name = 'Operador Partner'
        ].get(0);

        Id userRole = [
            SELECT Id, DeveloperName 
            FROM UserRole 
            WHERE DeveloperName = 'Operador_PSP' 
            LIMIT 1
            ].id;

        User partnerUser = new User(Alias = 'testU', Email='testU@danone.com',
                                    EmailEncodingKey='UTF-8', LastName='TestingU', LanguageLocaleKey='en_US',
                                    LocaleSidKey='en_US', ProfileId = profile.Id, UserRoleId = userRole,                                   
                                    TimeZoneSidKey='America/Los_Angeles', UserName='testU@danone.com', contactId=contacto.id);
        insert partnerUser;
        
        integer counter=0;
        List<Account> accList = new List<Account>();
        for(integer i =0;i<30;i++){
            Account testCuenta = Build.anAccountPacienteBestCare()
                .withLastName('Name Test prueba'+counter)
                .withRegimenDeInternacionDomiciliaria('Sí')
                .withEmpresadeinternaciondomiciliaria('Best care')		
                .withDNI('425452222'+counter)
                .withCanalParaConsumidorBaby('Farmacias')
                .build();
            testcuenta.OwnerId = partnerUser.id;
            testCuenta.Obra_social__pc = accObraSocial.id;
            
            accList.add(testCuenta);
            counter++;
        }
        
        insert accList;
        System.runAs(partnerUser){
            test.startTest();
            try{
                for(Account acc: accList){
                    acc.Obra_social__pc = accObraSocial.id;
                }
                update accList;
            }catch(Exception ex){
                Boolean expectedExceptionThrown =  ex.getMessage().contains('El operador partner solo puede cargar') ? true : false;
                System.assertEquals(expectedExceptionThrown, true);
            }
        }
        test.stopTest(); 
    }*/
    @isTest
    Public static void SiElEynPasaAtrueYcumpleLasCOndicionesSeDebenGenerarLosKits() {
        List<Product2> productos = new List<Product2>();
        
        for(integer i=0;i<5 ;i++){
            Product2 product = Build.aProduct2()
                .withProductoPara('Best Care')
                .withName('AMNoNUBA ' + i)
                .withDescription('Producto'+ i)
                .build();
                
            productos.add(product);
        }
        productos[0].ProductCode = '11593222';
        productos[1].ProductCode = '11265822';    
        productos[2].ProductCode = '11266022';    
        productos[3].ProductCode = '11265622';    
        productos[4].ProductCode = '11415722';    
        productos[4].Name = 'LP Drink';
        
        insert productos;
        
        Account testCuenta = Build.anAccountPacienteBestCare()
            .withLastName('Prueba Met')	
            .withDNI('425452222')
            .withAreaTerapeutica('Metabólicos')
            .withEstadoDePaciente('En tratamiento')
            .build();
        
        insert testCuenta;
        
        Test.startTest();
        testCuenta.EYN__c = true;
        update testCuenta;
        Test.stopTest();
        
        List<Envio_Sin_Cargo__c> kits = [
            SELECT id,Paciente__c
            FROM Envio_Sin_Cargo__c
            WHERE  Paciente__c = :testCuenta.id
        ];
        Set<Id> kitsID = new Set<Id>();
        for(Envio_Sin_Cargo__c aKit: kits){
            kitsID.add(aKit.id);
        }
        List<Producto_de_envio__c> productosDB = [
            SELECT id, Envio_sin_cargo__c,Formula__r.Name
            FROM Producto_de_envio__c
            WHERE Formula__r.Name LIKE '%AMNoNUBA%'
        ];
        List<Task> tareasEYN = [
            SELECT id,What.id
            FROM Task
            WHERE What.id IN :kitsID
        ];

        for(Producto_de_envio__c p : productosDB){
            System.debug(p.Formula__r.Name );
        }
        System.assertEquals(2, kits.size());
        System.assertEquals(4, productosDB.size()); 
        System.assertEquals(2, tareasEYN.size());
        
    }
    
    /*@isTest
    Public static void siUnOperadorPartnerIntentaCargarUnaInstitucionQueNoEsDeMendozaEnUNProfesionalDebeLanzarUnError() {
        String status;
        
        Profile profile = [
            SELECT Id,Name 
            FROM Profile 
            WHERE Name = 'Operador Partner'
        ];
        Municipio__c municipio = new Municipio__c();
        municipio.Descripcion_Provincia__c = 'MISIONES';
        Municipio.Name = 'MISIONES';
        insert municipio;
        
        Localidad__c localidad = new Localidad__c();
        Localidad.name='MISIONES';
        localidad.Municipio__c = municipio.id;
        insert localidad;
        
        Contact contacto = new Contact();
        contacto.LastName = 'Contacto';
        
        insert contacto;
        
        User user1 = Build.aUser()
            .withUsername('test1test7@gmail.com')
            .withEmail('test1test7@gmail.com')
            .withAlias('Ts')
            .withTimeZoneSidKey('GMT')
            .withLocaleSidKey('en_US')
            .withLastName('test apellido 3')
            .withCommunityNickname('test12345')
            .withEmailEncodingKey('UTF-8')
            .withProfileId(profile.id)
            .withLanguageLocaleKey('en_US')
            .Build();
        user1.ContactId = contacto.id;
        insert user1;
        
        integer counter=0;
        List<Account> accList = new List<Account>();
        for(integer i =0;i<30;i++){
            Account testCuenta = Build.anAccountProfesionaldelasalud()
                .withLastName('Name Test prueba'+counter)
                .withRegimenDeInternacionDomiciliaria('Sí')
                .withEmpresadeinternaciondomiciliaria('Best care')		
                .withDNI('425452222'+counter)
                .withCanalParaConsumidorBaby('Farmacias')
                .build();
            testCuenta.OwnerId = user1.id;
            accList.add(testCuenta);
            counter++;
        }
        
        insert accList;
        
        Account institucion = Build.anAccountInstitucion()
            .withDNI('425452222')
            .build();
        institucion.Name='institucion';
        institucion.Localidad_look__c = localidad.id;
        institucion.OwnerId = user1.id;
        insert institucion;
        
        System.runAs(user1){
            test.startTest();
            try{
                for(Account acc: accList){
                    acc.Institucion__c = institucion.id;
                }
                update accList;
                
            }catch(Exception ex){
                Boolean expectedExceptionThrown =  ex.getMessage().contains('El operador') ? true : false;
                System.assertEquals(expectedExceptionThrown, true);
            }
            
            test.stopTest();
        }
    }*/
    @TestSetup
    public static void SetupMethod() {
        
        Profile profileIdTest = [
            SELECT Id 
            FROM Profile 
            WHERE Name = 'Usuario de Platform estándar' 
            LIMIT 1
        ];
        
        List<User> usersToInsert = new List<User> ();
        
        User user1 = Build.aUser()
            .withUsername('usuario1testaccount@gmail.com')
            .withEmail('usuario1testaccount@gmail.com')
            .withAlias('u1ta')
            .withTimeZoneSidKey('GMT')
            .withLocaleSidKey('en_US')
            .withLastName('test apellido')
            .withCommunityNickname('usuario1testaccount')
            .withEmailEncodingKey('UTF-8')
            .withProfileId(profileIdTest.id)
            .withLanguageLocaleKey('en_US')
            .Build();
        
        usersToInsert.add(user1);
        
        User user2 = Build.aUser()
            .withUsername('usuario2testaccount@gmail.com')
            .withEmail('usuario2testaccount@gmail.com')
            .withAlias('u2ta')
            .withTimeZoneSidKey('GMT')
            .withLocaleSidKey('en_US')
            .withLastName('test apellido')
            .withCommunityNickname('usuario2testaccount')
            .withEmailEncodingKey('UTF-8')
            .withProfileId(profileIdTest.id)
            .withLanguageLocaleKey('en_US')
            .Build();
        
        usersToInsert.add(user2);
        
        User user3 = Build.aUser()
            .withUsername('usuario3testaccount@gmail.com')
            .withEmail('usuario3testaccount@gmail.com')
            .withAlias('u3ta')
            .withTimeZoneSidKey('GMT')
            .withLocaleSidKey('en_US')
            .withLastName('test apellido')
            .withCommunityNickname('usuario3testaccount')
            .withEmailEncodingKey('UTF-8')
            .withProfileId(profileIdTest.id)
            .withLanguageLocaleKey('en_US')
            .Build();
        
        usersToInsert.add(user3);
        
        User user4 = Build.aUser()
            .withUsername('usuario4testaccount@gmail.com')
            .withEmail('usuario4testaccount@gmail.com')
            .withAlias('u4ta')
            .withTimeZoneSidKey('GMT')
            .withLocaleSidKey('en_US')
            .withLastName('test apellido')
            .withCommunityNickname('usuario4testaccount')
            .withEmailEncodingKey('UTF-8')
            .withProfileId(profileIdTest.id)
            .withLanguageLocaleKey('en_US')
            .Build();
        
        usersToInsert.add(user4);
        
        User user5 = Build.aUser()
            .withUsername('usuario5testaccount@gmail.com')
            .withEmail('usuario5testaccount@gmail.com')
            .withAlias('u5ta')
            .withTimeZoneSidKey('GMT')
            .withLocaleSidKey('en_US')
            .withLastName('test apellido')
            .withCommunityNickname('usuario5testaccount')
            .withEmailEncodingKey('UTF-8')
            .withProfileId(profileIdTest.id)
            .withLanguageLocaleKey('en_US')
            .Build();
        
        usersToInsert.add(user5);
        
        
        insert usersToInsert;
    }
    
    
}