force-app/main/default/objects/Account/fields/Canal_para_Consumidor_Baby__c.field-meta.xml
<CustomField>
    <fullName>Canal_para_Consumidor_Baby__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Almacen</fullName>
            </value>
            <value>
                <fullName>Farmacias</fullName>
            </value>
            <value>
                <fullName>Farmacity</fullName>
            </value>
            <value>
                <fullName>Hipermarket</fullName>
            </value>
            <value>
                <fullName>MercadoLibre</fullName>
            </value>
            <value>
                <fullName>Nutrilon4</fullName>
            </value>
            <value>
                <fullName>Proximity</fullName>
            </value>
            <value>
                <fullName>Simplicity</fullName>
            </value>
            <value>
                <fullName>Supermercado</fullName>
            </value>
            <value>
                <fullName>Vital4</fullName>
            </value>
            <value>
                <fullName>La Sere va a tu casa</fullName>
            </value>
            <value>
                <fullName>Particular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <label>DNI</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ID_de_paciente__c.field-meta.xml
<CustomField>
    <fullName>ID_de_paciente__c</fullName>
    <displayFormat>P-{000000}</displayFormat>
    <externalId>true</externalId>
    <label>ID de paciente</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Modulo_hasta__c.field-meta.xml
<CustomField>
    <fullName>Modulo_hasta__c</fullName>
    <label>Modulo hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RenovationOSPECONControllerTest.cls
@isTest
public class RenovationOSPECONControllerTest {
    public static String str =JSON.serialize('ID_de_paciente__c,DNI\nP-039359,16656\nP-039190,321324');


    @TestSetup
    static void makeData(){

        Account acc1 = Build.anAccountPacienteBestCare()
            .withFirstName('test4')
            .withLastName('Names Test1')
            .withRegimenDeInternacionDomiciliaria('Sí')
            .withEmpresadeinternaciondomiciliaria('Best care')				   
            .build();
            acc1.DNI__c= '321324';
            acc1.Canal_para_Consumidor_Baby__c ='Farmacias';

        Account acc2 = Build.anAccountPacienteBestCare()
            .withFirstName('test4')
            .withLastName('Name Test2')
            .withRegimenDeInternacionDomiciliaria('Sí')
            .withEmpresadeinternaciondomiciliaria('Best care')				   
            .build();
            acc2.Modulo_hasta__c = System.today();
            acc2.DNI__c= '16656';
            acc2.Canal_para_Consumidor_Baby__c ='Farmacias';

        insert new List<Account>{acc1,acc2};
    }


    @isTest
    public static void testCSVLoad(){

        Test.startTest();
            List<Account> accs= RenovationOSPECONController.updateAccounts(str);
        Test.stopTest();

        System.assertEquals(2,accs.size());
      }
}