force-app/main/default/objects/Account/fields/Cantidad_de_casos_de_retiro_de_activos__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_casos_de_retiro_de_activos__c</fullName>
    <description>Funciona como rollup para casos con: 
Type = &apos;Gestión&apos;
Subtipo__c = &apos;Retiro de Activos&apos;
Motivo__c = &apos;Alta/Fin de tratamiento&apos; o &apos;Fallecimiento&apos; o &apos;No renueva servicios&apos;
Isclosed = true</description>
    <label>Cantidad de casos de retiro de activos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Motivo__c.field-meta.xml
<CustomField>
    <fullName>Motivo__c</fullName>
    <label>Motivo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Evaluación de inicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motivo__c.field-meta.xml
<CustomField>
    <fullName>Motivo__c</fullName>
    <description>Se crea un campo Motivo personalizado porque el estándar no puede ser dependiente de otro campo.</description>
    <label>Motivo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Subtipo__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Abandono de persona</fullName>
            </value>
            <value>
                <fullName>Abuso/ acoso/ violencia</fullName>
            </value>
            <value>
                <fullName>Acceso a recursos varios</fullName>
            </value>
            <value>
                <fullName>Actualización estado del pedido</fullName>
            </value>
            <value>
                <fullName>Adicionales a autorizado por OOSS</fullName>
            </value>
            <value>
                <fullName>Administración y preparación de fórmula</fullName>
            </value>
            <value>
                <fullName>Almacenamiento de productos</fullName>
            </value>
            <value>
                <fullName>ALTA</fullName>
            </value>
            <value>
                <fullName>Alta/Fin de tratamiento</fullName>
            </value>
            <value>
                <fullName>Alta Paciente BC</fullName>
            </value>
            <value>
                <fullName>Amenaza de denuncia/ publicacion en redes</fullName>
            </value>
            <value>
                <fullName>Asegurar entrega</fullName>
            </value>
            <value>
                <fullName>Asesoramiento sobre Organismos</fullName>
            </value>
            <value>
                <fullName>Autoridades/ Personas publicas/ Bromatologia/ ONG</fullName>
            </value>
            <value>
                <fullName>Baja del servicio sin módulo</fullName>
            </value>
            <value>
                <fullName>Baja de Paciente</fullName>
            </value>
            <value>
                <fullName>Becas</fullName>
            </value>
            <value>
                <fullName>Cambio de dirección</fullName>
            </value>
            <value>
                <fullName>Cambio de indicación</fullName>
            </value>
            <value>
                <fullName>Cambio de OOSS</fullName>
            </value>
            <value>
                <fullName>Cantidad</fullName>
            </value>
            <value>
                <fullName>Capacitaciones</fullName>
            </value>
            <value>
                <fullName>Capacitación Presencial</fullName>
            </value>
            <value>
                <fullName>Capacitación Telefónica</fullName>
            </value>
            <value>
                <fullName>Cobranza</fullName>
            </value>
            <value>
                <fullName>Cobranzas</fullName>
            </value>
            <value>
                <fullName>Comodato</fullName>
            </value>
            <value>
                <fullName>Comodatos, encuestas, varios</fullName>
            </value>
            <value>
                <fullName>Complicaciones enterales</fullName>
            </value>
            <value>
                <fullName>Condición de salud del pcte</fullName>
            </value>
            <value>
                <fullName>Fallecimiento</fullName>
            </value>
            <value>
                <fullName>No renueva servicios</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Subtipo__c.field-meta.xml
<CustomField>
    <fullName>Subtipo__c</fullName>
    <label>Subtipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activos</fullName>
            </value>
            <value>
                <fullName>Actualización de datos</fullName>
            </value>
            <value>
                <fullName>Actualización de Módulo</fullName>
            </value>
            <value>
                <fullName>Alta</fullName>
            </value>
            <value>
                <fullName>Alta con evaluación Medica</fullName>
            </value>
            <value>
                <fullName>Alta en bloque</fullName>
            </value>
            <value>
                <fullName>Calidad</fullName>
            </value>
            <value>
                <fullName>Cancelacion de Envio</fullName>
            </value>
            <value>
                <fullName>Compras en NEC</fullName>
            </value>
            <value>
                <fullName>Documentacion</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Envio de Activos</fullName>
            </value>
            <value>
                <fullName>Envio de Insumos</fullName>
            </value>
            <value>
                <fullName>Envio de Productos</fullName>
            </value>
            <value>
                <fullName>Estado de Envíos</fullName>
            </value>
            <value>
                <fullName>Modulo BC</fullName>
            </value>
            <value>
                <fullName>Nuevo Paciente</fullName>
            </value>
            <value>
                <fullName>ONG Acceso</fullName>
            </value>
            <value>
                <fullName>Productos</fullName>
            </value>
            <value>
                <fullName>Profesionales BC</fullName>
            </value>
            <value>
                <fullName>Profesionales de la salud</fullName>
            </value>
            <value>
                <fullName>Renovación</fullName>
            </value>
            <value>
                <fullName>Renovación en bloque</fullName>
            </value>
            <value>
                <fullName>Reporte de Crisis</fullName>
            </value>
            <value>
                <fullName>Reporte de Incidencia</fullName>
            </value>
            <value>
                <fullName>Respuestas WhatsApp</fullName>
            </value>
            <value>
                <fullName>Retiro de Activos</fullName>
            </value>
            <value>
                <fullName>Seguimiento</fullName>
            </value>
            <value>
                <fullName>Seguimiento no renovación</fullName>
            </value>
            <value>
                <fullName>Servicios Profesionales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulario_de_Calidad__c/Formulario_de_Calidad__c.object-meta.xml
<CustomObject>
    <label>Formulario de Calidad</label>
    <nameField>
        <displayFormat>FC-{00000}</displayFormat>
        <label>Numero de Formulario de calidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Formularios de Calidad</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Formulario_de_Calidad__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) AND (3 OR 4 OR 5)</booleanFilter>
        <errorMessage>Los formularios de calidad solo están disponibles para casos de tipo &quot;Reclamo&quot; y Subtipo &quot;Calidad&quot;, y de tipo de registro Paciente Best care, Regular o Consumidor Baby.</errorMessage>
        <filterItems>
            <field>Case.RecordType.Name</field>
            <operation>equals</operation>
            <value>Reclamo</value>
        </filterItems>
        <filterItems>
            <field>Case.Subtipo__c</field>
            <operation>equals</operation>
            <value>Calidad</value>
        </filterItems>
        <filterItems>
            <field>Case.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Best Care</value>
        </filterItems>
        <filterItems>
            <field>Case.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Regular</value>
        </filterItems>
        <filterItems>
            <field>Case.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Consumidor Baby</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Formulario de calidad</relationshipLabel>
    <relationshipName>Formulario_de_calidad</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseHelper.cls
public class CaseHelper  {
    
    public static Boolean isCaseToCountInAccount(Case newCase, Case oldCase) {
        Boolean isChanged = newCase.Status != oldCase.Status || newCase.Type != oldCase.Type || 
            newCase.Subtipo__c != oldCase.Subtipo__c || newCase.Motivo__c != oldCase.Motivo__c;
        
        return isChanged && isCaseToCountInAccount(newCase);
    }
    
    public static Boolean isCaseToCountInAccount(Case aCase) {
        Boolean isCaseToCountInAccount = aCase.IsClosed && aCase.Type == 'Gestión' && aCase.Subtipo__c == 'Retiro de Activos' && 
            (aCase.Motivo__c  == 'Alta/Fin de tratamiento' || aCase.Motivo__c == 'Fallecimiento' || aCase.Motivo__c == 'No renueva servicios');
        return isCaseToCountInAccount;
    }
    
    public static Boolean isCaseToCountInAccountDelete(Case aCase) {
        Boolean isCaseToCountInAccount = aCase.IsClosed && aCase.Type == 'Gestión' && aCase.Subtipo__c == 'Retiro de Activos' && 
            (aCase.Motivo__c  == 'Alta/Fin de tratamiento' || aCase.Motivo__c == 'Fallecimiento' || aCase.Motivo__c == 'No renueva servicios'
             || aCase.Motivo__c == 'Otro');
        return isCaseToCountInAccount;
    }
    
    public static Case getCaseWithAccount(Case newCase, Case oldCase) {
        if(newCase.AccountId != null) return newCase;
        return oldCase;
    }
    
    public static void countCasesInAccount(List<Case> caseList) {
        LREngine.Context contexto = new LREngine.Context(
            Account.SObjectType,
            Case.SObjectType,
            Schema.SObjectType.Case.fields.AccountId,
            '(Type = \'Gestión\' AND Subtipo__c = \'Retiro de Activos\''+
            ' AND (Motivo__c  = \'Alta/Fin de tratamiento\' OR Motivo__c = \'Fallecimiento\' OR Motivo__c = \'No renueva servicios\')'+
            ' AND Isclosed = true)'
        );
        
        contexto.add(new LREngine.RollupSummaryField(
            Schema.SObjectType.Account.fields.Cantidad_de_casos_de_retiro_de_activos__c,
            Schema.SObjectType.Case.fields.Id,
            LREngine.RollupOperation.Count
        ));
        
        List<Account> accountsToUpdate = (List<Account>) LREngine.rollUp(contexto, caseList);
        
        if(!accountsToUpdate.isEmpty()) update accountsToUpdate;
    }
    public static void validateFormularioDeCalidad(Case aCase) {
        
        List<Formulario_de_Calidad__c> formularioList = [
            SELECT ID, Caso__c 
            FROM Formulario_de_Calidad__c
            WHERE Caso__c = :aCase.id
        ];
        if(formularioList.isEmpty()){
            aCase.addError(Label.Error_en_formulario_de_calidad);
        }
    }
}