force-app/main/default/objects/Account/fields/Cliente_EDI__c.field-meta.xml
<CustomField>
    <fullName>Cliente_EDI__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para saber si es cliente EDI</description>
    <label>Cliente EDI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Canal de Distribución</description>
    <label>Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Campo donde se especifica la organización de ventas perteneciente.</description>
    <label>Sales organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Cliente.recordType-meta.xml
<RecordType>
    <fullName>Cliente</fullName>
    <active>true</active>
    <description>Tipo de registro de cuenta para Danone Sales</description>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/ApiDanone__c/ApiDanone__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuración para guardar datos de conexión a la api danone</description>
    <label>Api Danone</label>
</CustomObject>

force-app/main/default/objects/ApiDanone__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>endpoint</description>
    <label>URL</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlClaimExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlClaimExtension__c</fullName>
    <description>Extension para enviar reclamos de tipo Manejo de dinero. Ej: Diferencia de precios</description>
    <label>UrlClaimExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlCreateOrderExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlCreateOrderExtension__c</fullName>
    <description>Extension usada para enviar ordenes</description>
    <label>UrlCreateOrderExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/urlMatPrices__c.field-meta.xml
<CustomField>
    <fullName>urlMatPrices__c</fullName>
    <description>Url test para pedir precios de materiales para un cliente.</description>
    <label>urlMatPrices</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlreturnExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlreturnExtension__c</fullName>
    <description>Extension usada para enviar reclamos del tipo Manejo de inventario. Ej : Devoluciones</description>
    <label>UrlreturnExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/User_Key__c.field-meta.xml
<CustomField>
    <fullName>User_Key__c</fullName>
    <label>User Key</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/User_Key_Price__c.field-meta.xml
<CustomField>
    <fullName>User_Key_Price__c</fullName>
    <description>Key used for price callout</description>
    <label>User Key Price</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AppLog__c/AppLog__c.object-meta.xml
<CustomObject>
    <label>AppLog</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>AppLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AppLog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppLog__c/fields/Tipo_de_Errores__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Errores__c</fullName>
    <label>Tipo de Errores</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente - No es cliente EDI</fullName>
            </value>
            <value>
                <fullName>Cliente - Sucursal inexistente</fullName>
            </value>
            <value>
                <fullName>Cliente - Sin marca EDI</fullName>
            </value>
            <value>
                <fullName>Cliente - Cliente con Bloqueo</fullName>
            </value>
            <value>
                <fullName>Producto - Error en Producto</fullName>
            </value>
            <value>
                <fullName>Pedido - Sin orden de compra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AppLog__c/recordTypes/EDI.recordType-meta.xml
<RecordType>
    <fullName>EDI</fullName>
    <active>true</active>
    <description>Errores de ordens EDI</description>
    <label>EDI</label>
</RecordType>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/Dan360_CustomerSalesArea__c.object-meta.xml
<CustomObject>
    <description>Customer Sales Area</description>
    <label>Customer Sales Area</label>
    <nameField>
        <label>Nombre de Customer Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Sales Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/fields/Dan360_Block__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Block__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que indica si se pueden generar pedidos para el cliente.</description>
    <label>Block</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/fields/Dan360_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesArea__c</fullName>
    <description>Unidad de negocio que se asocia al cliente.</description>
    <label>Unidad de negocio</label>
    <referenceTo>Dan360_SalesArea__c</referenceTo>
    <relationshipLabel>Customer Sales Area</relationshipLabel>
    <relationshipName>Customer_Sales_Area</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_PlantillaDeProductos__c/Dan360_PlantillaDeProductos__c.object-meta.xml
<CustomObject>
    <description>Objetos en donde se almacenarán las plantillas de los productos.</description>
    <label>Plantilla de Productos</label>
    <nameField>
        <label>Plantilla</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantillas de Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/Dan360_ProductoPorPlantilla__c.object-meta.xml
<CustomObject>
    <label>Producto por Plantilla</label>
    <nameField>
        <displayFormat>PrdXPla-{0000}</displayFormat>
        <label>Producto por plantilla</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos por Plantillas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_SalesArea__c/Dan360_SalesArea__c.object-meta.xml
<CustomObject>
    <description>Sales Area</description>
    <label>Sales Area</label>
    <nameField>
        <label>Nombre de Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Distribution channel</description>
    <label>Distribution channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_Division__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Division__c</fullName>
    <description>División</description>
    <label>División</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Sales Organization</description>
    <label>Sales Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_CustomerSalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CustomerSalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Sales Area relacionado al pedido</description>
    <label>Customer Sales Area</label>
    <referenceTo>Dan360_CustomerSalesArea__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plantillas__c/Plantillas__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Plantillas</label>
</CustomObject>

force-app/main/default/objects/Plantillas__c/fields/NuBa_00__c.field-meta.xml
<CustomField>
    <fullName>NuBa_00__c</fullName>
    <label>NuBa Canal 00</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Dan360_CustomerSalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CustomerSalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Area</label>
    <referenceTo>Dan360_CustomerSalesArea__c</referenceTo>
    <relationshipLabel>Listas de precios</relationshipLabel>
    <relationshipName>Listas_de_precios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/ID_SAP__c.field-meta.xml
<CustomField>
    <fullName>ID_SAP__c</fullName>
    <description>Es el customer ID.</description>
    <externalId>true</externalId>
    <label>ID SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ID_SAP__c.field-meta.xml
<CustomField>
    <fullName>ID_SAP__c</fullName>
    <externalId>true</externalId>
    <label>ID SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Id_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/WSEdiTest.cls
@isTest
public with sharing class WSEdiTest {
    static XHttpCalloutMock getResponse;
    static string datee;
    static{

        insert new Plantillas__c(NuBa_00__c='Plantilla BULTOS - NUBA');
        insert new ApiDanone__c(URL__c = 'https://www.danapi.com.ar',User_Key__c = 'c3366a9f16190d9efda328ecec6f6833', User_Key_Price__c = 'c3366a9f16190d9efda328ecec6f6833',UrlClaimExtension__c = '/testing/sales/claim/v1',
            UrlreturnExtension__c = '/testing/sales/return/v1', UrlCreateOrderExtension__c = '/testing/sales/orders/v1', urlMatPrices__c = '/testing/masterdata/price/');

        List<OrderItem> orderItems = new List<OrderItem>();

		RecordType pedidoVentaDirecta = [SELECT id 
										FROM RecordType 
										WHERE sObjectType='Order' 
										AND Name = 'Pedido de Venta Directa'];

		Id pricebookId = Test.getStandardPricebookId();
		Date todayDate = Date.Today();

		Account account = Build.anAccount()
			.withPricebook(pricebookId)
			.withCanalComercial('E-Commerce')
			.withName('Account Test')
			.withIdSap('550071632')
            .withGLN(550071632)
			.withSalesDistric('E-Commerce')
			.withDistributionChannel('00')
			.build();
		insert account;

		Product2 producto = Build.aProduct()
			.withName('Product for Test')
			.withUnidadesBulto(15)			
			.withIdSap('106959')
            .withEan('106959')
			.withIsActive(true)
			.build();
		insert producto;

		Product2 productoTwo = Build.aProduct()
			.withName('Producto Test2')
			.withUnidadesBulto(15)
			.withIdSap('123')
            .withEan('123')
			.withIsActive(true)
			.build();
		insert productoTwo;

        Product2 productoThree = Build.aProduct()
			.withName('Producto Test2 Sin precio')
			.withUnidadesBulto(15)
			.withIdSap('166578')
            .withEan('166578')
			.withIsActive(true)
			.build();
		insert productoThree;

        Dan360_SalesArea__c salesArea = Build.aSalesArea()
                .withName('NUBA-00-00')
                .withIdExterno('5771-00-00')
                .withDistributionChannel('00')
                .withDivision('00')
                .withSalesOrganization('5771')
                .build();
            insert salesArea;

       /*  Dan360_SalesArea__c salesAreaBlock = Build.aSalesArea()
            .withName('AMN-00-00')
            .withIdExterno('5800-00-00')
            .withDistributionChannel('00')
            .withDivision('00')
            .withSalesOrganization('5800')
            .build();
        insert salesAreaBlock; */

        Dan360_PlantillaDeProductos__c productsTemplate = Build.aPlantillaDeProductos()
            .withName('Plantilla BULTOS - NUBA')
            .withBusinessUnit('5771')
            .build();
        insert productsTemplate;

        /* Dan360_PlantillaDeProductos__c productsTemplateBlock = Build.aPlantillaDeProductos()
            .withName('Plantilla BULTOS - NUBA')
            .withBusinessUnit('5771')
            .build();
        insert productsTemplateBlock; */

        Dan360_CustomerSalesArea__c customerSalesArea = Build.aCustomerSalesArea()
                .withName('Nuba 00')
                .withClient(account)
                .withUnidadNegocio(salesArea)
                .withIdExterno('5678-5771-00-00')
                .build();
            insert customerSalesArea;

        Pricebook2 pricebookCustomer = Build.aPricebook().withName('CustomerPriceBook').withCustomerSalesArea(customerSalesArea).isActive(true).build();
        insert pricebookCustomer;

        /* Dan360_CustomerSalesArea__c customerSalesAreaBlock = Build.aCustomerSalesArea()
                .withName('Nuba 00')
                .withClient(account)
                .withUnidadNegocio(salesAreaBlock)
                .withIdExterno('5678-5800-00-00')
                .withBlock(true)
                .build();
        insert customerSalesAreaBlock; */

        //Pricebook2 pricebookCustomerBlock = Build.aPricebook().withName('CustomerPriceBookBlock').withCustomerSalesArea(customerSalesAreaBlock).isActive(true).build();

        PricebookEntry pricebookPriceDefault = Build.aPricebookEntry()
            .withPricebook2Id(pricebookCustomer.id)
            .withProduct2Id(producto)
            .withUnitPrice(100)
            .withIsActive(true)
            .withDiscount(0.5)
            .build();
        insert pricebookPriceDefault;
        
        PricebookEntry pricebookPriceDefault3 = Build.aPricebookEntry()
            .withPricebook2Id(pricebookCustomer.id)
            .withProduct2Id(productoThree)
            .withUnitPrice(100)
            .withIsActive(true)
            .withDiscount(0)
            .build();
        insert pricebookPriceDefault3;

        PricebookEntry pricebookPriceDefault2 = Build.aPricebookEntry()
            .withPricebook2Id(pricebookCustomer.id)
            .withProduct2Id(productoTwo)
            .withUnitPrice(50)
            .withIsActive(true)
            .withDiscount(0.5)
            .build();
        insert pricebookPriceDefault2;

        
    
            Dan360_ProductoPorPlantilla__c productPerTemplate = Build.aProductoPorPlantilla()
                .withProduct(producto)
                .withProductTemplate(productsTemplate)
                .withUnitMeasure('Unidad')
                .withVigenciaDesde(Date.Today().AddDays(-1))
                .withVigencia(Date.Today().AddDays(1))
                .withIsActive(false)
                .build();
            insert productPerTemplate;
            Dan360_ProductoPorPlantilla__c productPerTemplate3 = Build.aProductoPorPlantilla()
                .withProduct(productoThree)
                .withProductTemplate(productsTemplate)
                .withUnitMeasure('Unidad')
                .withVigenciaDesde(Date.Today().AddDays(-1))
                .withVigencia(Date.Today().AddDays(1))
                .withIsActive(false)
                .build();
            insert productPerTemplate3;
            Dan360_ProductoPorPlantilla__c productPerTemplateTwo = Build.aProductoPorPlantilla()
                .withProduct(productoTwo)
                .withProductTemplate(productsTemplate)
                .withUnitMeasure('Unidad')
                .withVigenciaDesde(Date.Today())
                .withVigencia(Date.Today().AddDays(5))
                .withIsActive(true)
                .build();
            insert productPerTemplateTwo;

            datee = String.valueOf(Date.today().year())+'-'+Date.today().month().format()+'-'+Date.today().day().format();
            getResponse = new XHttpCalloutMock();
            getResponse.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(SapPricesMock.getSucess())
                .addForAddress(WebServiceSap.SERVICE_CONFIG.URL__c + WebServiceSap.SERVICE_CONFIG.urlMatPrices__c + 'sn?date='+datee+'&organizationId='+salesArea.Dan360_SalesOrganization__c+'&channelId='+salesArea.Dan360_DistributionChannel__c+'&divisionId='+salesArea.Dan360_Division__c+'&customer='+account.Id_SAP__c);
    }

    @isTest
    public static void ifClientExistInMetadataDoNothing(){
        Test.setMock(HttpCalloutMock.class, getResponse);
        RestRequest req = new RestRequest();
        String body = '{' +
            '"source": "EDI",' +
            '"businessModel": "B2B",'+
            '"companyCode": "5771",' +
            '"organizationId": "5771",' +
            '"channelId": "00",' +
            '"poNumber": "123456",' +
            '"soldTo": "0002",' +
            '"shipTo": "7798130250114",' +
            '"orderDate": "2021-11-01T00:00:00",' +
            '"reqDelDate": "2021-11-01T00:00:00",' +
            '"items": [' +
                '{' +
                '"matNumber": "7795323001324",' +
                '"orderedQuantity": 24.00,' +
                '"lotQuantity": 2.00,' +
                '"quantityByLot": 12.00' +
                '}' +
            ']' +
        '}';
        req.requestURI = '/services/apexrest/edi'; 
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(body);

        RestContext.request = req;

        Test.startTest();
        WSEdi.Respuesta resp = WSEdi.doPost();
        Test.stopTest();

        System.assertEquals('Sucursal inexistente', resp.message,'Error al comprar GLN de la tabla');
        System.debug(resp);
    }

    @isTest
    public static void ifClientDontExistInSFCreateALog(){
        Test.setMock(HttpCalloutMock.class, getResponse);
        RestRequest req = new RestRequest();
        String body = '{' +
            '"source": "EDI",' +
            '"businessModel": "B2B",'+
            '"companyCode": "5771",' +
            '"organizationId": "5771",' +
            '"channelId": "00",' +
            '"poNumber": "123456",' +
            '"soldTo": "00021",' +
            '"shipTo": "5500716322",' +
            '"orderDate": "2021-11-01T00:00:00",' +
            '"reqDelDate": "2021-11-01T00:00:00",' +
            '"items": [' +
                '{' +
                '"matNumber": "7795323001324",' +
                '"orderedQuantity": 24.00,' +
                '"lotQuantity": 2.00,' +
                '"quantityByLot": 12.00' +
                '}' +
            ']' +
        '}';
        req.requestURI = '/services/apexrest/edi'; 
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(body);

        RestContext.request = req;

        Test.startTest();
        WSEdi.Respuesta resp = WSEdi.doPost();
        Test.stopTest();

        AppLog__c logError = [SELECT id, Tipo_de_Errores__c FROM AppLog__c];

        System.assertEquals('Sucursal inexistente', resp.message,'Error al buscar el cliente en SF');
        System.assertEquals('Cliente - Sucursal inexistente', logError.Tipo_de_Errores__c,'Error al crear el log de error');
    }

    @isTest
    public static void ifClientDontExistButCheckFalseCreateALog(){
        Test.setMock(HttpCalloutMock.class, getResponse);
        RestRequest req = new RestRequest();
        String body = '{' +
            '"source": "EDI",' +
            '"businessModel": "B2B",'+
            '"companyCode": "5771",' +
            '"organizationId": "5771",' +
            '"channelId": "00",' +
            '"poNumber": "123456",' +
            '"soldTo": "00021",' +
            '"shipTo": "550071632",' +
            '"orderDate": "2021-11-01T00:00:00",' +
            '"reqDelDate": "2021-11-01T00:00:00",' +
            '"items": [' +
                '{' +
                '"matNumber": "106959",' +
                '"orderedQuantity": 24.00,' +
                '"lotQuantity": 2.00,' +
                '"quantityByLot": 12.00' +
                '}' +
            ']' +
        '}';
        req.requestURI = '/services/apexrest/edi'; 
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(body);

        RestContext.request = req;

        Test.startTest();
        WSEdi.Respuesta resp = WSEdi.doPost();
        Test.stopTest();

        AppLog__c logError = [SELECT id, Tipo_de_Errores__c FROM AppLog__c];
        List<Order> pedido = [SELECT Id, Status FROM Order];

        System.assertEquals('Cliente - Sin marca EDI', logError.Tipo_de_Errores__c,'Error al crear el log de error');
        System.assertEquals('Error', pedido[0].Status,'Error al crear la orden en estado de Error');
    }

    @isTest
    public static void ifClientDontHavePriceInSapCreateLog(){
        Test.setMock(HttpCalloutMock.class, getResponse);
        RestRequest req = new RestRequest();
        String body = '{' +
            '"source": "EDI",' +
            '"businessModel": "B2B",'+
            '"companyCode": "5771",' +
            '"organizationId": "5771",' +
            '"channelId": "00",' +
            '"poNumber": "123456",' +
            '"soldTo": "00021",' +
            '"shipTo": "550071632",' +
            '"orderDate": "2021-11-01T00:00:00",' +
            '"reqDelDate": "2021-11-01T00:00:00",' +
            '"items": [' +
                '{' +
                '"matNumber": "123",' +
                '"orderedQuantity": 24.00,' +
                '"lotQuantity": 2.00,' +
                '"quantityByLot": 12.00' +
                '}' +
            ']' +
        '}';
        req.requestURI = '/services/apexrest/edi'; 
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(body);

        RestContext.request = req;

        Test.startTest();
        WSEdi.Respuesta resp = WSEdi.doPost();
        Test.stopTest();

        AppLog__c logError = [SELECT id, Tipo_de_Errores__c FROM AppLog__c];
        List<Order> pedido = [SELECT Id, Status FROM Order];

        System.assertEquals('Cliente - Sin marca EDI;Producto - Error en Producto', logError.Tipo_de_Errores__c,'Error al crear el log de error');
        System.assertEquals('Error', pedido[0].Status,'Error al crear la orden en estado de Error');
    }

    @isTest
    public static void ifClientDontHaveErrorConfirmOrder(){
        List<Account> cuenta = [SELECT ID,Id_SAP__c, Cliente_EDI__c FROM Account];
        cuenta[0].Cliente_EDI__c = true;
        update cuenta;

        Test.setMock(HttpCalloutMock.class, getResponse);
        RestRequest req = new RestRequest();
        String body = '{' +
            '"source": "EDI",' +
            '"businessModel": "B2B",'+
            '"companyCode": "5771",' +
            '"organizationId": "5771",' +
            '"channelId": "00",' +
            '"poNumber": "123456",' +
            '"soldTo": "00021",' +
            '"shipTo": "550071632",' +
            '"orderDate": "2021-11-01T00:00:00",' +
            '"reqDelDate": "2021-11-01T00:00:00",' +
            '"items": [' +
                '{' +
                '"matNumber": "106959",' +
                '"orderedQuantity": 24.00,' +
                '"lotQuantity": 2.00,' +
                '"quantityByLot": 12.00' +
                '} , ' +
                '{' +
                '"matNumber": "166578",' +
                '"orderedQuantity": 24.00,' +
                '"lotQuantity": 2.00,' +
                '"quantityByLot": 12.00' +
                '}' +
            ']' +
        '}';
        req.requestURI = '/services/apexrest/edi'; 
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(body);

        RestContext.request = req;

        Test.startTest();
        WSEdi.Respuesta resp = WSEdi.doPost();
        Test.stopTest();

        List<Order> pedido = [SELECT Id, Status FROM Order];

        System.assertEquals('Confirmado', pedido[0].Status,'Error al crear la orden en estado de Error');
    }

    @isTest
    public static void ifClientHaveCustomerSalesAreaBlockCreateAppLog(){
       
        List<Dan360_CustomerSalesArea__c> customerSalesArea = [SELECT Id, Dan360_Block__c FROM Dan360_CustomerSalesArea__c];
        customerSalesArea[0].Dan360_Block__c = true;
        update customerSalesArea;

        Test.setMock(HttpCalloutMock.class, getResponse);
        RestRequest req = new RestRequest();
        String body = '{' +
            '"source": "EDI",' +
            '"businessModel": "B2B",'+
            '"companyCode": "5771",' +
            '"organizationId": "5771",' +
            '"channelId": "00",' +
            '"poNumber": "",' +
            '"soldTo": "00021",' +
            '"shipTo": "550071632",' +
            '"orderDate": "2021-11-01T00:00:00",' +
            '"reqDelDate": "2021-11-01T00:00:00",' +
            '"items": [' +
                '{' +
                '"matNumber": "106959",' +
                '"orderedQuantity": 24.00,' +
                '"lotQuantity": 2.00,' +
                '"quantityByLot": 12.00' +
                '}' +
            ']' +
        '}';
        req.requestURI = '/services/apexrest/edi'; 
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(body);

        RestContext.request = req;

        Test.startTest();
        WSEdi.Respuesta resp = WSEdi.doPost();
        Test.stopTest();

        List<Order> pedido = [SELECT Id, Status FROM Order];

        System.assertEquals('Error', pedido[0].Status,'Error al crear la orden en estado de Error');
    }
}