force-app/main/default/objects/Account/fields/Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_postal__c</fullName>
    <label>Codigo postal</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Codigo_Postal__c/Codigo_Postal__c.object-meta.xml
<CustomObject>
    <label>Código Postal</label>
    <nameField>
        <label>Código Postal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Códigos Postales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Código Postal</label>
    <referenceTo>Codigo_Postal__c</referenceTo>
    <relationshipLabel>Contactos</relationshipLabel>
    <relationshipName>Contactos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Principal__c.field-meta.xml
<CustomField>
    <fullName>Principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Relacion__c.field-meta.xml
<CustomField>
    <fullName>Relacion__c</fullName>
    <label>Relación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Madre</fullName>
            </value>
            <value>
                <fullName>Padre</fullName>
            </value>
            <value>
                <fullName>Tutor</fullName>
            </value>
            <value>
                <fullName>Cuidador</fullName>
            </value>
            <value>
                <fullName>Otro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/CreateContactAccountControllerTest.cls
@isTest
public class CreateContactAccountControllerTest {

	@isTest
	Public static void mostrarMensajeDeErrorCuandoNoCargaIdDelPaciente(){
	
		Test.startTest();
		CreateContactAccountController controller = new CreateContactAccountController();
		Test.stopTest();
        
		List<ApexPages.Message> ListaMensaje = ApexPages.getMessages();
		System.assertNotEquals(0, ListaMensaje.size());
		for(ApexPages.Message msg :  ListaMensaje) {
			System.assertEquals('¡Error al cargar datos del paciente!', msg.getSummary());
			System.assertEquals(ApexPages.Severity.ERROR, msg.getSeverity()); 
		}
    }

	@isTest
	Public static void mostrarMensajeDeErrorCuandoNoGuardaCorrectamenteElContactoDePaciente(){
		
		PageReference pagina = new PageReference('/apex/CreateContactAccount');
		pagina.getParameters().put('id', cuenta.Id);
		Test.setCurrentPage(pagina);
        
		CreateContactAccountController controller = new CreateContactAccountController();
		controller.contactoDePaciente.Principal__c = True;
		controller.contactoDePaciente.Relacion__c = 'Padre';

		Test.startTest();
		controller.guardar();
		Test.stopTest();
        
		List<ApexPages.Message> ListaMensaje = ApexPages.getMessages();
		System.assertNotEquals(0, ListaMensaje.size());
		for(ApexPages.Message msg :  ListaMensaje) {
			System.assertEquals(ApexPages.Severity.ERROR, msg.getSeverity()); 
		}
    }

	@isTest
	Public static void mostrarMensajeDeGuardadoCorrectoCuandoSeCreaElContactoDePaciente(){
  
		PageReference pagina = new PageReference('/apex/CreateContactAccount');
		pagina.getParameters().put('id', cuenta.Id);
		Test.setCurrentPage(pagina);
		CreateContactAccountController controller = new CreateContactAccountController();
		controller.contactoDePaciente.Contacto__c = contacto.Id;
		controller.contactoDePaciente.Principal__c = True;
		controller.contactoDePaciente.Relacion__c = 'Padre';

		Test.startTest();
		controller.guardar();
		Test.stopTest();

		List<ApexPages.Message> ListaMensaje = ApexPages.getMessages();
		System.assertNotEquals(0, ListaMensaje.size());
		for(ApexPages.Message msg :  ListaMensaje) {
			System.assertEquals('¡Se insertaron los datos correctamente!', msg.getSummary());
			System.assertEquals(ApexPages.Severity.CONFIRM, msg.getSeverity()); 
		}
    }


	static Account cuenta;
	static Contact contacto;
	static {
	
		cuenta = Build.anAccountPacienteBestCare()
            .withEmpresadeinternaciondomiciliaria('Best Care')
            .withRegimenDeInternacionDomiciliaria('Sí')
			.withLastName('Apellido')
            .build();
        insert cuenta;
		
		Codigo_Postal__c codigoPostal = Build.aCodigoPostal()
			.withName('B2700AAG')
			.withProvincia('BUENOS AIRES')
			.withLocalidad('PERGAMINO')
			.withCalles('AV ALSINA 601-699')
            .build();
        insert codigoPostal;

		contacto = Build.aContactContactodepaciente()
			.withLastName('Test'+String.valueOf(System.now().getTime() + (Math.random() * 10)))
			.withDepartamento('D')
			.withPiso('5')
			.withCalle('Santa Fe 897')
			.withPais('Argentina')
			.withCodigoPostal(codigoPostal)
			.withReferencia('al lado del Dia')
			.build();
        insert contacto;
	}
}