force-app/main/default/objects/Account/fields/Consentimiento_ya_registrado__c.field-meta.xml
<CustomField>
    <fullName>Consentimiento_ya_registrado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consentimiento ya registrado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <inlineHelpText>Ingrese CALLE ALTURA PISO DPTO</inlineHelpText>
    <label>Direccion</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <label>DNI</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Estado_del_consentimiento__c.field-meta.xml
<CustomField>
    <fullName>Estado_del_consentimiento__c</fullName>
    <label>Estado del consentimiento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En curso</fullName>
            </value>
            <value>
                <fullName>Aceptado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Provincia_localidad__c.field-meta.xml
<CustomField>
    <fullName>Provincia_localidad__c</fullName>
    <formula>TEXT(Localidad_look__r.Municipio__r.Descripcion_Provincia__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provincia</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Firmante_de_Consentimiento__c/Firmante_de_Consentimiento__c.object-meta.xml
<CustomObject>
    <label>Firmante de Consentimiento</label>
    <nameField>
        <label>Nombre de Firmante de Consentimiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firmantes de Consentimiento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Firmante_de_Consentimiento__c/fields/Correo_electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_electronico__c</fullName>
    <label>Correo electronico</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Firmante_de_Consentimiento__c/fields/Documento_del_firmante__c.field-meta.xml
<CustomField>
    <fullName>Documento_del_firmante__c</fullName>
    <label>Documento del firmante</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Firmante_de_Consentimiento__c/fields/Domicilio__c.field-meta.xml
<CustomField>
    <fullName>Domicilio__c</fullName>
    <label>Domicilio</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Firmante_de_Consentimiento__c/fields/Historia_clinica__c.field-meta.xml
<CustomField>
    <fullName>Historia_clinica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Historia Clínica</label>
    <referenceTo>Formulario__c</referenceTo>
    <relationshipLabel>Firmantes de Consentimiento</relationshipLabel>
    <relationshipName>Firmantes_de_Consentimiento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Firmante_de_Consentimiento__c/fields/Nombre_y_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Nombre_y_Apellido__c</fullName>
    <label>Nombre y Apellido</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Firmante_de_Consentimiento__c/fields/Paciente__c.field-meta.xml
<CustomField>
    <fullName>Paciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Firmantes de Consentimiento</relationshipLabel>
    <relationshipName>Firmantes_de_Consentimiento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Firmante_de_Consentimiento__c/fields/Relacion_con_el_paciente__c.field-meta.xml
<CustomField>
    <fullName>Relacion_con_el_paciente__c</fullName>
    <label>Relacion con el paciente</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Formulario__c/Formulario__c.object-meta.xml
<CustomObject>
    <label>Historia Clínica</label>
    <nameField>
        <label>Nombre de Formulario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historias Clínicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Formulario__c/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <formula>Nombre_y_Apellido_del_Paciente__r.DNI__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DNI</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Domicilio__c.field-meta.xml
<CustomField>
    <fullName>Domicilio__c</fullName>
    <label>Domicilio</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Estado_del_consentimiento__c.field-meta.xml
<CustomField>
    <fullName>Estado_del_consentimiento__c</fullName>
    <defaultValue>&apos;Pendiente&apos;</defaultValue>
    <label>Estado del consentimiento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En curso</fullName>
                <default>true</default>
                <label>En curso</label>
            </value>
            <value>
                <fullName>Acepto</fullName>
                <label>Aceptó</label>
            </value>
            <value>
                <fullName>Rechazo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Nombre_y_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Nombre_y_Apellido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre y Apellido</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Formularios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Nombre_y_Apellido_del_Paciente__c.field-meta.xml
<CustomField>
    <fullName>Nombre_y_Apellido_del_Paciente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>No debe completarse</inlineHelpText>
    <label>Nombre y apellido del paciente</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Best Care</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Regular</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Historias Clínicas</relationshipLabel>
    <relationshipName>Formularios3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Patologia__c.field-meta.xml
<CustomField>
    <fullName>Patologia__c</fullName>
    <label>Patología</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Patologias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Via_de_acceso__c.field-meta.xml
<CustomField>
    <fullName>Via_de_acceso__c</fullName>
    <label>Tipo de acceso</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sonda nasogástrica</fullName>
            </value>
            <value>
                <fullName>Sonda nasoduodenal</fullName>
            </value>
            <value>
                <fullName>Sonda nasoyeyunal</fullName>
            </value>
            <value>
                <fullName>Gastroyeyunostomia</fullName>
                <label>Gastro-yeyunostomía</label>
            </value>
            <value>
                <fullName>Gastrostomía</fullName>
            </value>
            <value>
                <fullName>Yeyunostomía</fullName>
            </value>
            <value>
                <fullName>Botón gástrico</fullName>
            </value>
            <value>
                <fullName>Vía oral</fullName>
                <default>true</default>
                <label>Vía oral</label>
            </value>
            <value>
                <fullName>Esofagostomía</fullName>
                <isActive>false</isActive>
                <label>Esofagostomía</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Patologias.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acidemia metilmalonica/propionica</fullName>
    </customValue>
    <customValue>
        <fullName>Aciduria Arginosucinica</fullName>
    </customValue>
    <customValue>
        <fullName>Aciduria Glutarica</fullName>
    </customValue>
    <customValue>
        <fullName>ACV Hemorragíco (Accidente cerebrovascular)</fullName>
    </customValue>
    <customValue>
        <fullName>ACV Isquemico (Accidente cerebrovascular)</fullName>
    </customValue>
    <customValue>
        <fullName>Adrenoleucodistrofia</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia a la Proteina de leche de vaca (APLV)</fullName>
    </customValue>
    <customValue>
        <fullName>Alzheirmer</fullName>
    </customValue>
    <customValue>
        <fullName>Anorexia</fullName>
    </customValue>
    <customValue>
        <fullName>Asma</fullName>
    </customValue>
    <customValue>
        <fullName>Bulimia</fullName>
    </customValue>
    <customValue>
        <fullName>Cirrosis Hepatica</fullName>
    </customValue>
    <customValue>
        <fullName>cirugía Aparato genitourinario</fullName>
    </customValue>
    <customValue>
        <fullName>Cirugía de cabeza y cuello</fullName>
    </customValue>
    <customValue>
        <fullName>Cirugía Gastrointestinal</fullName>
    </customValue>
    <customValue>
        <fullName>Demencia otros tipos</fullName>
    </customValue>
    <customValue>
        <fullName>Demencia senil</fullName>
    </customValue>
    <customValue>
        <fullName>Desnutrición</fullName>
    </customValue>
    <customValue>
        <fullName>Desnutrición Asociada a enfermedad</fullName>
    </customValue>
    <customValue>
        <fullName>Deterioro cognitivo crónico</fullName>
    </customValue>
    <customValue>
        <fullName>DGG (Deficiencia de Glucosa/Galactosa)</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes (DBT)</fullName>
    </customValue>
    <customValue>
        <fullName>Encefalitis</fullName>
    </customValue>
    <customValue>
        <fullName>Encefalopatía crónica no evolutiva (ECNE)</fullName>
    </customValue>
    <customValue>
        <fullName>Enfermedad obstructiva Crónica (EPOC)</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsia Refractaria</fullName>
    </customValue>
    <customValue>
        <fullName>Esclerosis lateral amiotrófica (ELA)</fullName>
    </customValue>
    <customValue>
        <fullName>Esofagitis Eosinofílica</fullName>
    </customValue>
    <customValue>
        <fullName>Fenilcetonuria</fullName>
    </customValue>
    <customValue>
        <fullName>Fibrosis Quistica</fullName>
    </customValue>
    <masterLabel>Patologías</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConfirmacionDeConsentimientoController.cls
public class ConfirmacionDeConsentimientoController{
    Formulario__c hc{ get; set; }
    
    public boolean yaSeleccionado{ get; set; }
    
    public boolean agradecimiento{ get; set; }
    
    public String HCid{ get; set; }
    
    public String fecha{ get; set; }
    
    public String nombreCompleto{ get; set; }
    
    public String dni{ get; set; }
    
    public String direccion{ get; set; }
    
    public String provincia{ get; set; }
    
    public String medico{ get; set; }
    
    public String emailPaciente{ get; set; }
    
    public String celularPaciente{ get; set; }
    
    public String patologia{ get; set; }
    
    public String tipoDeacceso{ get; set; }
    
    public String nombreFirmante{ get; set; }
    
    public String dniFirmante{ get; set; }
    
    public String domicilioFirmante{ get; set; }
    
    public String emailFirmante{ get; set; }
    
    public String relacion{ get; set; }
    
    public String celularFirmante{ get; set; }
    
    public boolean checkRechazo{ get; set; }
    
    public boolean agradecimientoSinLink{ get; set; }
    
    public boolean respuestaYaRegistrada{ get; set; }
    
    public boolean esFirmante{ get; set; }
    
    public boolean acepto{ get; set; }
    
    public boolean error{ get; set; }
    
    public ConfirmacionDeConsentimientoController(){
        
        error = false;
        esFirmante = false;
        yaSeleccionado = true;
        agradecimiento = false;
        fecha = getFechaActual();
        HCid = Apexpages.currentPage().getParameters().get('hcid');
        if (HCid != null){
            hc = getHistoriaClinica(HCid);
            if (hc.Nombre_y_Apellido_del_Paciente__r.Consentimiento_ya_registrado__c){
                respuestaYaRegistrada = true;
            } else{
                respuestaYaRegistrada = false;
            }
            if (hc != null){
                nombreCompleto = hc.Nombre_y_Apellido_del_Paciente__r.name;
                dni = hc.Nombre_y_Apellido_del_Paciente__r.dni__c;
                direccion = hc.Nombre_y_Apellido_del_Paciente__r.direccion__c;
                provincia = hc.Nombre_y_Apellido_del_Paciente__r.Provincia_localidad__c;
                medico = hc.owner.name;
                emailPaciente = hc.Nombre_y_Apellido_del_Paciente__r.personEmail;
                celularPaciente = hc.Nombre_y_Apellido__r.phone;
                tipodeAcceso = hc.Via_de_acceso__c;
                patologia = hc.Patologia__c;
            }
            
        } else if(respuestaYaRegistrada==null){
            respuestaYaRegistrada = true;
        }
    }
    
    public void confirmacionDeFirma(){
        
        if (HCid != null){
            yaSeleccionado = false;
            agradecimiento = true;
            Account relatedAccount = [SELECT id, Estado_del_consentimiento__c
                                      FROM Account
                                      WHERE id = :hc.Nombre_y_Apellido_del_Paciente__c
                                      LIMIT 1];
            relatedAccount.Estado_del_consentimiento__c = 'Aceptado';
            relatedAccount.Consentimiento_ya_registrado__c = true;
            if (esFirmante && nombreFirmante != '' && dniFirmante != ''){
                insertFirmante(hc);
            }
            acepto = true;
            
            update relatedAccount;
            insertPDF();
        }
    }
    
    public void rechazoDeConsentimiento(){
        
        if (checkRechazo && HCid != null){
            yaSeleccionado = false;
            agradecimientoSinLink = true;
            Account relatedAccount = [SELECT id, Estado_del_consentimiento__c
                                      FROM Account
                                      WHERE id = :hc.Nombre_y_Apellido_del_Paciente__c
                                      LIMIT 1];
            relatedAccount.Estado_del_consentimiento__c = 'Rechazado';
            relatedAccount.Consentimiento_ya_registrado__c = true;
            if (esFirmante){
                insertFirmante(hc);
            }
            acepto= false;
            
            update relatedAccount;
            insertPDF();
        }
    }
    
    public Formulario__c getHistoriaClinica(String hcid){
        return [SELECT id, Nombre_y_Apellido_del_Paciente__c,Nombre_y_Apellido_del_Paciente__r.Consentimiento_ya_registrado__c, Nombre_y_Apellido_del_Paciente__r.name, Nombre_y_Apellido_del_Paciente__r.dni__c, Nombre_y_Apellido_del_Paciente__r.direccion__c, Nombre_y_Apellido_del_Paciente__r.Provincia_localidad__c, owner.name, Nombre_y_Apellido_del_Paciente__r.personEmail, Nombre_y_Apellido__r.phone, Via_de_acceso__c, Patologia__c
                FROM Formulario__c
                WHERE id = :HCid
                ORDER BY createdDate DESC
                LIMIT 1];
    }
    
    public PageReference descargarFormulario(){
        PageReference formularioDeConcentimiento = new PageReference('/apex/FormularioConsentimiento');
        formularioDeConcentimiento.setRedirect(true);		
        formularioDeConcentimiento.getParameters().put('name', nombreFirmante);
        formularioDeConcentimiento.getParameters().put('dn', dniFirmante);
        formularioDeConcentimiento.getParameters().put('dom', domicilioFirmante);
        formularioDeConcentimiento.getParameters().put('em', emailFirmante);
        formularioDeConcentimiento.getParameters().put('ace', String.valueOf(acepto));
        formularioDeConcentimiento.getParameters().put('ce', celularFirmante);
        formularioDeConcentimiento.getParameters().put('hcid', HCid);
        
        
        return formularioDeConcentimiento;
    }
    
    public String getFechaActual(){
        Datetime todayDateTime = System.today();
        String mes = getMonth(todayDateTime.month());
        
        return System.today().day()+' de ' + mes + ' del ' + System.today().year();
    }
    
    public void insertPDF(){
        
        Pagereference reportPage = Page.FormularioConsentimiento;
        reportPage.getParameters().put('hcid', HCid);
        reportPage.getParameters().put('name', nombreFirmante);
        reportPage.getParameters().put('dn', dniFirmante);
        reportPage.getParameters().put('dom', domicilioFirmante);
        reportPage.getParameters().put('em', emailFirmante);
        reportPage.getParameters().put('ce', celularFirmante);
        reportPage.getParameters().put('ace', String.valueOf(acepto));
        
        
        Blob reportPdf;
        if(!Test.isRunningTest()){ //Necesario ya que las clases de test no permiten: getContent()
            reportPdf = reportPage.getContentAsPDF();
        }
        else{
            reportPdf = Blob.valueOf('Test');
        }
        
        ContentVersion cv = new ContentVersion();
        cv.VersionData = reportPdf;
        cv.Title = hc.Nombre_y_Apellido_del_Paciente__r.Name + 
            ' - Consentimiento informado de tratamiento - ' + System.now();
        cv.PathOnClient = hc.Nombre_y_Apellido_del_Paciente__r.Name + 
            ' - Consentimiento informado de tratamiento - ' + System.now()+'.pdf';
        
        insert cv;
        
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [SELECT ContentDocumentId
                                 FROM ContentVersion
                                 WHERE Id = :cv.Id].ContentDocumentId;
        cdl.LinkedEntityId = hc.Nombre_y_Apellido_del_Paciente__c;
        cdl.ShareType = 'V';
        
        insert cdl;
    }
    
    public void insertFirmante(Formulario__c hc){
        
        Firmante_de_Consentimiento__c firmante = new Firmante_de_Consentimiento__c();
        firmante.Name = nombreFirmante;
        firmante.Celular__c = celularFirmante;
        firmante.Correo_electronico__c = emailFirmante;
        firmante.Domicilio__c = domicilioFirmante;
        firmante.Documento_del_firmante__c = dniFirmante;
        firmante.Historia_clinica__c = hc.id;
        firmante.Paciente__c = hc.Nombre_y_Apellido_del_Paciente__c;
        firmante.Relacion_con_el_paciente__c = relacion;
        insert firmante;
    }
    public String getMonth(Integer monthNumber){
        Map<String,String>  monthNameMap = new Map<String, String> {
            '1'=>'Enero', '2'=>'Febrero', '3'=>'Marzo', '4'=>'Abril', '5'=>'Mayo', '6'=>'Junio',
                '7'=>'Julio', '8'=>'Agosto', '9'=>'Septiembre','10'=>'Octubre', '11'=>'Noviembre', '12'=>'Diciembre'
                };
                    return monthNameMap.get(String.valueOf(monthNumber));
    }
}