force-app/main/default/objects/Account/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Canal de Distribución</description>
    <label>Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Campo donde se especifica la organización de ventas perteneciente.</description>
    <label>Sales organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/Dan360_CustomerSalesArea__c.object-meta.xml
<CustomObject>
    <description>Customer Sales Area</description>
    <label>Customer Sales Area</label>
    <nameField>
        <label>Nombre de Customer Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Sales Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/fields/Dan360_Customer__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Customer__c</fullName>
    <description>Cliente relacionado a la Sales Area.</description>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Sales Area</relationshipLabel>
    <relationshipName>Customer_Sales_Area</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/fields/Dan360_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesArea__c</fullName>
    <description>Unidad de negocio que se asocia al cliente.</description>
    <label>Unidad de negocio</label>
    <referenceTo>Dan360_SalesArea__c</referenceTo>
    <relationshipLabel>Customer Sales Area</relationshipLabel>
    <relationshipName>Customer_Sales_Area</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/Dan360_SalesArea__c.object-meta.xml
<CustomObject>
    <description>Sales Area</description>
    <label>Sales Area</label>
    <nameField>
        <label>Nombre de Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Distribution channel</description>
    <label>Distribution channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_Division__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Division__c</fullName>
    <description>División</description>
    <label>División</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Sales Organization</description>
    <label>Sales Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Dan360_CustomerSalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CustomerSalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Area</label>
    <referenceTo>Dan360_CustomerSalesArea__c</referenceTo>
    <relationshipLabel>Listas de precios</relationshipLabel>
    <relationshipName>Listas_de_precios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Dan360_LastModSap__c.field-meta.xml
<CustomField>
    <fullName>Dan360_LastModSap__c</fullName>
    <description>Fecha de la ultima actualización de los precios.</description>
    <label>Dan360_LastModSap</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/ID_SAP__c.field-meta.xml
<CustomField>
    <fullName>ID_SAP__c</fullName>
    <description>Es el customer ID.</description>
    <externalId>true</externalId>
    <label>ID SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Dan360_Descuento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Descuento__c</fullName>
    <description>Campo que indica el descuento que aplica para un producto para un cliente.</description>
    <label>Descuento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Dan360_IDExterno__c.field-meta.xml
<CustomField>
    <fullName>Dan360_IDExterno__c</fullName>
    <description>ID que representa el customer area y Id Material.</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ID_SAP__c.field-meta.xml
<CustomField>
    <fullName>ID_SAP__c</fullName>
    <externalId>true</externalId>
    <label>ID SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Id_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchCustomerSalesAreaPricebook.cls
public with sharing class BatchCustomerSalesAreaPricebook implements Database.Batchable<sObject>,Database.AllowsCallouts, Database.Stateful{
    String customerSalesAreaId;
    
    public BatchCustomerSalesAreaPricebook(String customerSalesAreaIdP){
        customerSalesAreaId = customerSalesAreaIdP;
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 
            'SELECT Id, Name, Dan360_SalesArea__c, Dan360_Customer__r.Id_SAP__c, Dan360_Id_Externo__c,' +
            'Dan360_SalesArea__r.Dan360_Division__c,Dan360_SalesArea__r.Dan360_DistributionChannel__c,Dan360_SalesArea__r.Dan360_SalesOrganization__c ' +
            'FROM Dan360_CustomerSalesArea__c ' +
            'WHERE Id = :customerSalesAreaId';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Dan360_CustomerSalesArea__c> customerSalesAreas) {
        
        Dan360_CustomerSalesArea__c customerSalesArea = customerSalesAreas[0];

        String fechaPedido = String.valueOf(Date.today().year())+'-'+Date.today().month().format()+'-'+Date.today().day().format();
        WebServiceSap.matPricesResponse response = WebServiceSap.askMaterialPricesSAP(fechaPedido, customerSalesArea.Dan360_SalesArea__r.Dan360_SalesOrganization__c, 
        customerSalesArea.Dan360_SalesArea__r.Dan360_DistributionChannel__c, customerSalesArea.Dan360_SalesArea__r.Dan360_Division__c,
                                                                                    customerSalesArea.Dan360_Customer__r.Id_SAP__c);
        
        List<Pricebook2> listnewPriceBook = new List<PriceBook2>();
        System.debug(response);
        Pricebook2 newPriceBook = new Pricebook2(
            Name = 'Lista '+ customerSalesArea.Name,
            Dan360_CustomerSalesArea__c = customerSalesArea.Id,
            isActive = true, 
            Dan360_LastModSap__c = Datetime.now()
        );
            try {
                Database.insert(newPriceBook,true);
            } catch (Exception e) {
                System.debug(e.getMessage());
            }
        

        if(response.response.getStatusCode() != 200){
            System.debug(response.response.getStatusCode());
        } else{
            List<PriceBookEntry> pbToInsert = new List<PriceBookEntry>();
            List<MatPriceUtilityJson.Prices> listPrices = response.matPricesResponseObj.prices;
            for(MatPriceUtilityJson.Prices price : listPrices){
                Product2 prodRefference = new Product2(
                    Id_SAP__c = price.materialId
                );
                PriceBookEntry pbEntry = new PriceBookEntry(
                    Dan360_IDExterno__c = customerSalesArea.Dan360_Id_Externo__c+'-'+price.materialId,
                    Product2 = prodRefference,
                    Pricebook2Id = newPriceBook.Id,
                    UnitPrice = price.price,
                    IsActive = true, 
                    Dan360_Descuento__c = price.discount
                );
                System.debug(pbEntry);
                pbToInsert.add(pbEntry);
            }
            
            Schema.SObjectField externalIdPB = PricebookEntry.Fields.Dan360_IDExterno__c;
            Database.UpsertResult[] upResult = Database.upsert(pbToInsert,externalIdPB,false);
            for (Database.UpsertResult sr : upResult) {
                if (sr.isSuccess()) {
                   
                    System.debug('Exito');
                }
                else {             
                    for(Database.Error err : sr.getErrors()) {
                       
                        System.debug('error has occurred.' + err.getStatusCode() + ': ' + err.getMessage());                    
                        System.debug('fields that affected this error: ' + err.getFields());
                        
                    }
                }
            }
        }
    }

    public void finish(Database.BatchableContext BC) {
        // execute any post-processing operations
    }
}