force-app/main/default/objects/Account/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Canal de Distribución</description>
    <label>Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Campo donde se especifica la organización de ventas perteneciente.</description>
    <label>Sales organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ApiDanone__c/ApiDanone__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuración para guardar datos de conexión a la api danone</description>
    <label>Api Danone</label>
</CustomObject>

force-app/main/default/objects/ApiDanone__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>endpoint</description>
    <label>URL</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlClaimExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlClaimExtension__c</fullName>
    <description>Extension para enviar reclamos de tipo Manejo de dinero. Ej: Diferencia de precios</description>
    <label>UrlClaimExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlCreateOrderExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlCreateOrderExtension__c</fullName>
    <description>Extension usada para enviar ordenes</description>
    <label>UrlCreateOrderExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/urlMatPrices__c.field-meta.xml
<CustomField>
    <fullName>urlMatPrices__c</fullName>
    <description>Url test para pedir precios de materiales para un cliente.</description>
    <label>urlMatPrices</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlreturnExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlreturnExtension__c</fullName>
    <description>Extension usada para enviar reclamos del tipo Manejo de inventario. Ej : Devoluciones</description>
    <label>UrlreturnExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/User_Key__c.field-meta.xml
<CustomField>
    <fullName>User_Key__c</fullName>
    <label>User Key</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/User_Key_Price__c.field-meta.xml
<CustomField>
    <fullName>User_Key_Price__c</fullName>
    <description>Key used for price callout</description>
    <label>User Key Price</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/Dan360_CustomerSalesArea__c.object-meta.xml
<CustomObject>
    <description>Customer Sales Area</description>
    <label>Customer Sales Area</label>
    <nameField>
        <label>Nombre de Customer Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Sales Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/fields/Dan360_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesArea__c</fullName>
    <description>Unidad de negocio que se asocia al cliente.</description>
    <label>Unidad de negocio</label>
    <referenceTo>Dan360_SalesArea__c</referenceTo>
    <relationshipLabel>Customer Sales Area</relationshipLabel>
    <relationshipName>Customer_Sales_Area</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_PlantillaDeProductos__c/Dan360_PlantillaDeProductos__c.object-meta.xml
<CustomObject>
    <description>Objetos en donde se almacenarán las plantillas de los productos.</description>
    <label>Plantilla de Productos</label>
    <nameField>
        <label>Plantilla</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantillas de Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_SalesArea__c/Dan360_SalesArea__c.object-meta.xml
<CustomObject>
    <description>Sales Area</description>
    <label>Sales Area</label>
    <nameField>
        <label>Nombre de Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Distribution channel</description>
    <label>Distribution channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_Division__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Division__c</fullName>
    <description>División</description>
    <label>División</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Sales Organization</description>
    <label>Sales Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_CustomerSalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CustomerSalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Sales Area relacionado al pedido</description>
    <label>Customer Sales Area</label>
    <referenceTo>Dan360_CustomerSalesArea__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_PedidoConfirmado__c.field-meta.xml
<CustomField>
    <fullName>Dan360_PedidoConfirmado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Casilla para notificación de pedido confirmado</description>
    <label>Pedido confirmado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plantillas__c/Plantillas__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Plantillas</label>
</CustomObject>

force-app/main/default/objects/Plantillas__c/fields/AMN_00__c.field-meta.xml
<CustomField>
    <fullName>AMN_00__c</fullName>
    <label>AMN Canal 00</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Dan360_CustomerSalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CustomerSalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Area</label>
    <referenceTo>Dan360_CustomerSalesArea__c</referenceTo>
    <relationshipLabel>Listas de precios</relationshipLabel>
    <relationshipName>Listas_de_precios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/ID_SAP__c.field-meta.xml
<CustomField>
    <fullName>ID_SAP__c</fullName>
    <description>Es el customer ID.</description>
    <externalId>true</externalId>
    <label>ID SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ID_SAP__c.field-meta.xml
<CustomField>
    <fullName>ID_SAP__c</fullName>
    <externalId>true</externalId>
    <label>ID SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Id_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OrderItemTriggerHandlerTest.cls
@IsTest
public class OrderItemTriggerHandlerTest {
    static XHttpCalloutMock getPriceResponse;
    static string datee;

    static{
        insert new ApiDanone__c(URL__c = 'https://www.danapi.com.ar',User_Key__c = 'c3366a9f16190d9efda328ecec6f6833', User_Key_Price__c = 'c3366a9f16190d9efda328ecec6f6833',UrlClaimExtension__c = '/testing/sales/claim/v1',
        UrlreturnExtension__c = '/testing/sales/return/v1', UrlCreateOrderExtension__c = '/testing/sales/orders/v1', urlMatPrices__c = '/testing/masterdata/price/	');
        RecordType pedidoVentaDirecta = [SELECT id FROM RecordType where sObjectType='Order' and Name = 'Pedido de Venta Directa'];
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Date todayDate = Date.Today();

        Account account = Build.anAccount()
            .withName('Cuenta Prueba')
            .withIdSap('000012')
            .withSalesDistric('Licitaciones;E-Commerce;Others')
			.withDistributionChannel('00')
            .build();
        insert account;

        Dan360_SalesArea__c salesArea = Build.aSalesArea()
            .withName('AMN-01-01')
            .withIdExterno('5800-01-01')
            .withDistributionChannel('00')
            .withDivision('01')
            .withSalesOrganization('5800')
            .build();
        insert salesArea;

        Dan360_PlantillaDeProductos__c templateProducts = Build.aPlantillaDeProductos()
            .withName('AMN Canal 00')
            .withBusinessUnit('5800')
            .build();
        insert templateProducts;

        insert new Plantillas__c(AMN_00__c = 'AMN Canal 00');

        Dan360_CustomerSalesArea__c customerSalesArea = Build.aCustomerSalesArea()
            .withName('AMN 00')
            .withClient(account)
            .withUnidadNegocio(salesArea)
            .withIdExterno('5678-5800-01-01')
            .build();
        insert customerSalesArea;

        Pricebook2 pricebook = Build.aPricebook()
            .withName('Lista Precios Customer')
            .withCustomerSalesArea(customerSalesArea)
            .isActive(true)
            .build();
        insert pricebook;

        Product2 producto = Build.aProduct()
            .withName('Producto Test')
            .withUnidadesBulto(6)
            .withProductCode('0000012')
            .withIsActive(true)
            .withIdSap('106959')
            .build();
        insert producto;
        
        Product2 producto2 = Build.aProduct()
            .withName('Producto Test 2')
            .withUnidadesBulto(12)
            .withProductCode('0000013')
            .withIsActive(true)
            .withIdSap('166578')
            .build();
        insert producto2;

        PricebookEntry pricebookEntry = Build.aPricebookEntry()
            .withPricebook2Id(pricebook.Id)
            .withProduct2Id(producto)
            .withUnitPrice(100)
            .withIsActive(true)
            .withExternalId('5678-5800-00-01-106959')
            .withDiscount(0.5)
            .withUnitOfMeasure('Unidad')
            .build();
        insert pricebookEntry;

        PricebookEntry pricebookEntry2 = Build.aPricebookEntry()
            .withPricebook2Id(pricebook.Id)
            .withProduct2Id(producto2)
            .withUnitPrice(100)
            .withIsActive(true)
            .withExternalId('5678-5800-00-01-166578')
            .withDiscount(0.5)
            .withUnitOfMeasure('Unidad')
            .build();
        insert pricebookEntry2;
        
        Order order = Build.anOrder()
            .withAccount(account)
            .withEffectiveDate(Date.today())
            .withEndDate(Date.today())
            .withFechaCierreCarrito(DateTime.now().addDays(5))
            .withFechaInicioCarrito(DateTime.now().addDays(1))
            .withStatus('Borrador')
            .withPurchaseOrder('00000742')
            .withBusinessUnit('5800')
            .withRecordType(pedidoVentaDirecta.Id)
            .withDescription('test')
            .withCustomerSalesArea(customerSalesArea)
            .withPricebook(pricebook.Id)
            .withIdExterno('9876')
            .withProductsTemplate(templateProducts)
            .build();
        insert order;

        OrderItem orderItem = Build.anOrderItem()
            .withOrder(order)
            .withPricebookEntryId(pricebookEntry)
            .withProduct2Id(pricebookEntry.Product2Id)
            .withProduct2Id(producto)
            .withListPrice(pricebookEntry.UnitPrice)
            .withUnitPrice(pricebookEntry.UnitPrice)
            .withQuantity(2)
            .withDiscount(0.5)
            .withUnidadMedida('Trade Unit')
            .build();
        insert orderItem;

        OrderItem orderItem2 = Build.anOrderItem()
            .withOrder(order)
            .withPricebookEntryId(pricebookEntry2)
            .withProduct2Id(pricebookEntry2.Product2Id)
            .withProduct2Id(producto2)
            .withListPrice(pricebookEntry2.UnitPrice)
            .withUnitPrice(pricebookEntry2.UnitPrice)
            .withQuantity(2)
            .withDiscount(0.5)
            .withUnidadMedida('Trade Unit')
            .build();
        insert orderItem2;
        
        datee = String.valueOf(Date.today().year())+'-'+Date.today().month().format()+'-'+Date.today().day().format();
        getPriceResponse = new XHttpCalloutMock();
        getPriceResponse.buildResponse()
            .withStatus('OK')
            .withStatusCode(200)
            .withBody(SapPricesMock.getSucess())
            .addForAddress(WebServiceSap.SERVICE_CONFIG.URL__c + WebServiceSap.SERVICE_CONFIG.urlMatPrices__c + 'sn?date='+datee+'&organizationId='+salesArea.Dan360_SalesOrganization__c+'&channelId='+salesArea.Dan360_DistributionChannel__c+'&divisionId='+salesArea.Dan360_Division__c+'&customer='+account.Id_SAP__c);
    }
    @IsTest
    static void cuandoSeActualizaLaCantidadDeUnOrderItemConUnidadDeMedidaTradeUnitSeHaceUnCalculoDeRedondeo(){
        Test.setMock(HttpCalloutMock.class, getPriceResponse);
        List<OrderItem> orderItemTest = [SELECT Quantity FROM OrderItem];
        orderItemTest[0].Quantity = 8;
        orderItemTest[1].Quantity = 20;

        Test.startTest();
           update orderItemTest;
        Test.stopTest();

        List<OrderItem> orderItemAfterUpdate = [SELECT Quantity FROM OrderItem];
        
        System.assertEquals(12, orderItemAfterUpdate[0].Quantity, 'La cantidad no se actualizó correctamente.');
        System.assertEquals(24, orderItemAfterUpdate[1].Quantity, 'La cantidad no se actualizó correctamente.');
    }

    @IsTest
    static void cuandoSeConfirmaUnPedidoYLaCantidadDelOrderItemNoCambiaNoSeDebeActualizarLaCantidad(){
        Test.setMock(HttpCalloutMock.class, getPriceResponse);
        Order orderTest = [SELECT Id,Status FROM Order LIMIT 1];
        orderTest.Status = 'Confirmado';
		orderTest.Dan360_PedidoConfirmado__c = true;

        List<OrderItem> orderItemBeforeUpdate = [SELECT Quantity FROM OrderItem];

        Test.startTest();
        update orderTest;
        Test.stopTest();

        List<OrderItem> orderItemAfterUpdate = [SELECT Quantity FROM OrderItem];
        
        System.assertEquals(true, orderItemAfterUpdate[0].Quantity == orderItemBeforeUpdate[0].Quantity, 'Se actualizó la cantidad aun cuando no debería');
        System.assertEquals(true, orderItemAfterUpdate[1].Quantity == orderItemBeforeUpdate[1].Quantity, 'Se actualizó la cantidad aun cuando no debería');
    }
}