force-app/main/default/objects/Account/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Canal de Distribución</description>
    <label>Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Campo donde se especifica la organización de ventas perteneciente.</description>
    <label>Sales organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ApiDanone__c/ApiDanone__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuración para guardar datos de conexión a la api danone</description>
    <label>Api Danone</label>
</CustomObject>

force-app/main/default/objects/ApiDanone__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>endpoint</description>
    <label>URL</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlCreateOrderExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlCreateOrderExtension__c</fullName>
    <description>Extension usada para enviar ordenes</description>
    <label>UrlCreateOrderExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/urlMatPrices__c.field-meta.xml
<CustomField>
    <fullName>urlMatPrices__c</fullName>
    <description>Url test para pedir precios de materiales para un cliente.</description>
    <label>urlMatPrices</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/User_Key__c.field-meta.xml
<CustomField>
    <fullName>User_Key__c</fullName>
    <label>User Key</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/User_Key_Price__c.field-meta.xml
<CustomField>
    <fullName>User_Key_Price__c</fullName>
    <description>Key used for price callout</description>
    <label>User Key Price</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_EnviadoSAP__c.field-meta.xml
<CustomField>
    <fullName>Dan360_EnviadoSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviado SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_Factura__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Factura__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Factura relacionada al reclamo generado.</description>
    <label>Factura</label>
    <referenceTo>Dan360_Factura__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_MotivoDeReclamo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_MotivoDeReclamo__c</fullName>
    <description>Especifica el porqué se está realizando la devolución del producto.</description>
    <label>Motivo de reclamo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEVCVEN</fullName>
                <label>Corto vencimiento</label>
            </value>
            <value>
                <fullName>Error facturación impuesto a las ventas</fullName>
            </value>
            <value>
                <fullName>Error ingreso admin pedido</fullName>
            </value>
            <value>
                <fullName>Exento de Impuestos</fullName>
            </value>
            <value>
                <fullName>Faltante producto por abasto</fullName>
                <label>Faltante de producto</label>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>NOSOLIC</fullName>
                <label>No pedido</label>
            </value>
            <value>
                <fullName>No se ingresó motivo para Nota de Crédito</fullName>
            </value>
            <value>
                <fullName>PRODA</fullName>
                <label>Producto Dañado</label>
            </value>
            <value>
                <fullName>Producto Incorrecto</fullName>
            </value>
            <value>
                <fullName>PROVEN</fullName>
                <label>Producto vencido</label>
            </value>
            <value>
                <fullName>Se usó tasa impositiva incorrecta en la factura original</fullName>
            </value>
            <value>
                <fullName>Demora en la entrega</fullName>
            </value>
            <value>
                <fullName>Entrega fuera del horario/día acordado</fullName>
            </value>
            <value>
                <fullName>Malos tratos del chofer</fullName>
            </value>
            <value>
                <fullName>Dan360_PorNoPedido</fullName>
                <isActive>false</isActive>
                <label>Dan360_PorNoPedido</label>
            </value>
            <value>
                <fullName>Dan360_PorProductoDañado</fullName>
                <isActive>false</isActive>
                <label>Dan360_PorProductoDañado</label>
            </value>
            <value>
                <fullName>Dan360_PorProductoVencido</fullName>
                <isActive>false</isActive>
                <label>Dan360_PorProductoVencido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_OrderedDate__c.field-meta.xml
<CustomField>
    <fullName>Dan360_OrderedDate__c</fullName>
    <label>Ordered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_OrderGetEnd__c.field-meta.xml
<CustomField>
    <fullName>Dan360_OrderGetEnd__c</fullName>
    <label>Order Get End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_OrderGetStart__c.field-meta.xml
<CustomField>
    <fullName>Dan360_OrderGetStart__c</fullName>
    <label>Order Get Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Pedido__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Número de pedido por el cual se está generando el reclamo.</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remito relacionado a un pedido.</description>
    <label>Remito</label>
    <referenceTo>Dan360_Remito__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_RequiredDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>Dan360_RequiredDeliveryDate__c</fullName>
    <label>Required Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Acceso.recordType-meta.xml
<RecordType>
    <fullName>Acceso</fullName>
    <active>false</active>
    <businessProcess>Acceso</businessProcess>
    <label>Acceso</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Diferencia.recordType-meta.xml
<RecordType>
    <fullName>Diferencia</fullName>
    <active>true</active>
    <businessProcess>Diferencia</businessProcess>
    <description>Para Danone Sales</description>
    <label>Diferencia</label>
</RecordType>

force-app/main/default/objects/Dan360_Cuota__c/Dan360_Cuota__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacenará las cuotas que se aplicán a los pedidos, para controlar las cantidades de producto que se pueden procesar en cada pedido y las cantidades que quedarán &quot;Retenidas por cuota&quot;.</description>
    <label>Cuota</label>
    <nameField>
        <displayFormat>Cuo-{0000}</displayFormat>
        <label>Nombre de Cuota</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_Cuota__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Cuota__c</fullName>
    <description>Cuota asignada al producto.</description>
    <label>Cuota</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/Dan360_CustomerSalesArea__c.object-meta.xml
<CustomObject>
    <description>Customer Sales Area</description>
    <label>Customer Sales Area</label>
    <nameField>
        <label>Nombre de Customer Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Sales Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/fields/Dan360_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesArea__c</fullName>
    <description>Unidad de negocio que se asocia al cliente.</description>
    <label>Unidad de negocio</label>
    <referenceTo>Dan360_SalesArea__c</referenceTo>
    <relationshipLabel>Customer Sales Area</relationshipLabel>
    <relationshipName>Customer_Sales_Area</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/Dan360_Factura__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los documentos de cuentas corrientes de los clientes que se relacionan a un pedido.</description>
    <label>Factura</label>
    <nameField>
        <displayFormat>Fact-{0000}</displayFormat>
        <label>Nombre de Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Pedido__c</fullName>
    <description>Pedido al cual se relaciona la factura.</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipName>Facturas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Partner__c/Dan360_Partner__c.object-meta.xml
<CustomObject>
    <description>Partner</description>
    <label>Partner</label>
    <nameField>
        <label>Nombre de Partner</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Partner__c/fields/Dan360_CustomerSalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CustomerSalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Area</label>
    <referenceTo>Dan360_CustomerSalesArea__c</referenceTo>
    <relationshipLabel>Parners</relationshipLabel>
    <relationshipName>Parners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Remito__c/Dan360_Remito__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los remitos que se relacionan a un pedido</description>
    <label>Remito</label>
    <nameField>
        <displayFormat>Rem{0000}</displayFormat>
        <label>Nombre de Remito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Remito__c/fields/Dan360_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Pedido__c</fullName>
    <description>Pedido al cual está relacionado el remito.</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Remitos</relationshipLabel>
    <relationshipName>Remitos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/Dan360_SalesArea__c.object-meta.xml
<CustomObject>
    <description>Sales Area</description>
    <label>Sales Area</label>
    <nameField>
        <label>Nombre de Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Distribution channel</description>
    <label>Distribution channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_Division__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Division__c</fullName>
    <description>División</description>
    <label>División</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Sales Organization</description>
    <label>Sales Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_CustomerSalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CustomerSalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Sales Area relacionado al pedido</description>
    <label>Customer Sales Area</label>
    <referenceTo>Dan360_CustomerSalesArea__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_PedidoConfirmado__c.field-meta.xml
<CustomField>
    <fullName>Dan360_PedidoConfirmado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Casilla para notificación de pedido confirmado</description>
    <label>Pedido confirmado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Orden_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_compra__c</fullName>
    <label>Orden de compra</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ID_SAP__c.field-meta.xml
<CustomField>
    <fullName>ID_SAP__c</fullName>
    <externalId>true</externalId>
    <label>ID SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Id_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/sendOrderToSapControllerTest.cls
@isTest
public with sharing class sendOrderToSapControllerTest {
	static XHttpCalloutMock getResponse;
	static XHttpCalloutMock getBadResponse;
	static{
		
		List<OrderItem> orderItems = new List<OrderItem>();

		RecordType pedidoVentaDirecta = [SELECT id 
										FROM RecordType 
										WHERE sObjectType='Order' 
										AND Name = 'Pedido de Venta Directa'];

		Id pricebookId = Test.getStandardPricebookId();
		Date todayDate = Date.Today();

		Account account = Build.anAccount()
			.withPricebook(pricebookId)
			.withCanalComercial('E-Commerce')
			.withName('Account Test')
			.withIdSap('550071632')
			.withSalesDistric('E-Commerce')
			.withDistributionChannel('00')
			.build();
		insert account;

		Product2 producto = Build.aProduct()
			.withName('Product for Test')
			.withUnidadesBulto(15)			
			.withIdSap('106959')
			.withIsActive(true)
			.build();
		insert producto;

		Product2 productoTwo = Build.aProduct()
			.withName('Producto Test2')
			.withUnidadesBulto(15)
			.withIdSap('166578')
			.withIsActive(true)
			.build();
		insert productoTwo;

		Dan360_Cuota__c cuotaOne = Build.aCuota()
			.withProducto(producto)
			.withCanalComercial('Acceso')
			.withVigenciaDesde(todayDate)
			.withVigenciaHasta(todayDate.addDays(6))
			.build();
		insert cuotaOne;

		Dan360_Cuota__c cuotaTwo = Build.aCuota()
			.withProducto(productoTwo)
			.withCanalComercial('Acceso')
			.withVigenciaDesde(todayDate)
			.withVigenciaHasta(todayDate.addDays(6))
			.build();
		insert cuotaTwo;

		List<PricebookEntry> pricebooksEntries = [
										SELECT  IsActive,Pricebook2Id,Product2Id,UnitPrice
										FROM PricebookEntry
										WHERE Pricebook2Id = :pricebookId];

		Dan360_SalesArea__c salesArea = Build.aSalesArea()
            .withName('AMN-01-01')
            .withIdExterno('5800-01-01')
            .withDistributionChannel('01')
            .withDivision('00')
            .withSalesOrganization('5800')
            .build();
        insert salesArea;

        Dan360_CustomerSalesArea__c customerSalesArea = Build.aCustomerSalesArea()
            .withName('AMN 00')
            .withClient(account)
            .withUnidadNegocio(salesArea)
            .withIdExterno('5678-5800-01-01')
            .build();
        insert customerSalesArea;

		Order orderTestAMN = Build.anOrder()
			.withAccount(account)
			.withEffectiveDate(Date.today())
			.withEndDate(Date.today())
			.withFechaCierreCarrito(DateTime.now().addDays(5))
			.withFechaInicioCarrito(DateTime.now().addDays(1))
			.withStatus('Borrador')
			.withPurchaseOrder('00000742')
			.withPricebook(pricebookId)
			.withBusinessUnit('5800')
			.withRecordType(pedidoVentaDirecta.Id)
			.withDescription('test')
			.withCustomerSalesArea(customerSalesArea)
			.build();
		insert orderTestAMN;

		for(PricebookEntry pricebookEntry : pricebooksEntries) {
			orderItems.add(
				Build.anOrderItem()
					.withOrder(orderTestAMN)
					.withProduct2Id(pricebookEntry.Product2Id)
					.withListPrice(100)
					.withUnitPrice(100)
					.withQuantity(1)
					.withPricebookEntryId(pricebookEntry)
					.withDiscount(0.5)
					.build()
			);
		}

		insert orderItems;
	
        Dan360_Partner__c shipt = Build.aPartner()
            .withIdExterno('0')
            .withRol('WE')
            .withClient(account)
            .withName('Ship to')
			.withCustomerSalesArea(customerSalesArea)
            .build();
        insert shipt;

        Dan360_Partner__c sold = Build.aPartner()
            .withIdExterno('3814320001')
            .withRol('AG')
            .withClient(account)
            .withName('Sold to')
			.withCustomerSalesArea(customerSalesArea)
            .build();
        insert sold;

		Dan360_Factura__c factura = Build.aFactura()
            .withPedido(orderTestAMN)
            .withSucursal(account)
            .withClient(account)
            .build();
        insert factura;


        Id rtReturnCase = Schema.SObjectType.case.getRecordTypeInfosByName().get('Devoluciones').getRecordTypeId();
        Id rtClaimCase = Schema.SObjectType.case.getRecordTypeInfosByName().get('Diferencia de precios y descuentos').getRecordTypeId();

        Case returnCase = Build.aReclamo()
            .withAccount(account)
            .withFactura(factura)
            .withPedido(orderTestAMN.Id)
            .withMotivoDeReclamo('PRODA')
            .withRecordType(rtReturnCase)
            .build();
        insert returnCase;

        Case claimCase = Build.aReclamo()
            .withAccount(account)
            .withFactura(factura)
            .withPedido(orderTestAMN.Id)
            .withRecordType(rtClaimCase)
            .build();
        insert claimCase;

        Dan360_ProductosDeReclamo__c productReturnCase = Build.aProductoDeReclamo()
            .withUnidadMedida('PCE')
            .withIdLinea('00010')
            .withCantidadDevolver('10')
            .withProducto(producto)
            .withReclamo(returnCase.Id)
            .build();
        insert productReturnCase;

        Dan360_ProductosDeReclamo__c productClaimCase = Build.aProductoDeReclamo()
            .withUnidadMedida('PCE')
            .withIdLinea('00010')
            .withCantidadDevolver('10')
            .withProducto(producto)
            .withReclamo(claimCase.Id)
            .build();
        insert productClaimCase;


		
		insert new ApiDanone__c(URL__c = 'https://www.danapi.com.ar',User_Key__c = 'c3366a9f16190d9efda328ecec6f6833', User_Key_Price__c = 'c3366a9f16190d9efda328ecec6f6833', urlMatPrices__c = '/testing/masterdata/price/',UrlCreateOrderExtension__c = '/testing/sales/orders/v2' );

		String datee = String.valueOf(Date.today().year())+'-'+Date.today().month().format()+'-'+Date.today().day().format();
		getResponse = new XHttpCalloutMock();
        getResponse.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(SapPricesMock.getSucess())
			.addForAddress(WebServiceSap.SERVICE_CONFIG.URL__c + WebServiceSap.SERVICE_CONFIG.urlMatPrices__c + 'sn?date='+datee+'&organizationId='+salesArea.Dan360_SalesOrganization__c+'&channelId='+salesArea.Dan360_DistributionChannel__c+'&divisionId='+salesArea.Dan360_Division__c+'&customer='+account.Id_SAP__c);
			//.addForAddress('https://www.danapi.com.ar/testing/masterdata/price/sn?date='+datee+'&organizationId=5800&channelId=01&divisionId=01&customer=550071632');
		
		getResponse.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WebServiceSapMock.getAltaSuccess())
			.addForAddress(WebServiceSap.SERVICE_CONFIG.URL__c + WebServiceSap.SERVICE_CONFIG.UrlCreateOrderExtension__c);

		
	}

	@isTest
	public static void enqueBatchJobSendOrderSap() {
		Test.setMock(HttpCalloutMock.class, getResponse);
		Order anOrder = [
						SELECT id,Status,Dan360_PedidoConfirmado__c
						FROM Order 
						LIMIT 1
		];
		anOrder.Status = 'Confirmado';
		anOrder.Dan360_PedidoConfirmado__c = true;
		update anOrder;

		Test.startTest();
		sendOrderToSapController.sendOrderToSap(anOrder.Id);
		Test.stopTest();

		AsyncApexJob AAJ = [SELECT id, Status, CompletedDate,
								CreatedBy.Email, CreatedBy.Name,
								NumberOfErrors
							FROM AsyncApexJob
							LIMIT 1
		];

		System.debug(' AAJ.Status ------>'+ AAJ.Status);

		System.assertEquals('Completed',  AAJ.Status, 'El batch no fue encolado');
	}
	@isTest
	public static void enqueBatchJobSendOrderSapFlow() {
		Test.setMock(HttpCalloutMock.class, getResponse);
		List<String> orders = new List<String>();
		Order anOrder = [
						SELECT id 
						FROM Order
						WHERE Orden_de_compra__c = '00000742' 
						LIMIT 1
		];
		anOrder.Status = 'Confirmado';
		anOrder.Dan360_PedidoConfirmado__c = true;
		update anOrder;

		orders.add(anOrder.id);

		
		String errorMensaje;
		try {
			System.debug('testtry');
            Test.startTest();
            	sendOrderToSapController.sendOrderToSapFlow(orders);
            Test.stopTest(); 
        } catch (Exception err) {
			System.debug('testcatch');
           errorMensaje = err.getMessage();
        }
        System.assertEquals(null,  errorMensaje, 'El batch no fue encolado');
	}

    @isTest
    public static void notEnqueBatchJobSendOrderSapIfDraft() {
		Test.setMock(HttpCalloutMock.class, getResponse);
		Order anOrder = [
						SELECT id 
						FROM Order 
						LIMIT 1
		];
		anOrder.Status = 'Borrador';
		update anOrder;
        
        String errorMensaje;
        try {
            Test.startTest();
		    sendOrderToSapController.sendOrderToSap(anOrder.Id);
		    Test.stopTest(); 
        } catch (Exception err) {
           errorMensaje = err.getMessage();
        }

		System.assertEquals('Error: La Orden no esta Confirmada',  errorMensaje, 'El Batch fue encolado');
	}

	@isTest
	public static void enqueBatchJobSendCaseSap() {
		Test.setMock(HttpCalloutMock.class, getResponse);
		Case caso = [
						SELECT Id, CaseNumber, Dan360_MotivoDeReclamo__c, RecordType.Name, Dan360_Pedido__c,Dan360_EnviadoSAP__c, Description,
						Dan360_RequiredDeliveryDate__c, Dan360_OrderedDate__c, Dan360_OrderGetStart__c,Dan360_OrderGetEnd__c,
						Dan360_Remito__r.Dan360_Delivery__c, Dan360_Factura__r.Dan360_Id_Externo__c,CreatedDate
						FROM Case 
						LIMIT 1
		];
        
        String errorMensaje;
        try {
            Test.StartTest();
		    	sendOrderToSapController.sendCaseToSap(caso.Id);
			Test.stopTest();
        } catch (Exception err) {
           errorMensaje = err.getMessage();
        }

		System.assertEquals(null,  errorMensaje, 'El Batch fue encolado');
	}

	@isTest
	public static void sendOrderToSapFutureSendEmailWhenHaveABadResponse() {
		Test.setMock(HttpCalloutMock.class, getResponse);		
		String body = '{"items":[{"um":"Unidad","orderedQuantity":1.00,"matNumber":"","itemNumber":1},{"um":"Unidad","orderedQuantity":1.00,"matNumber":"","itemNumber":2}],"note":"test","poNumber":"00000742","poType":"","orderGetFinal":"2022-08-03T16:02:41.000Z","orderGetStart":"2022-07-30T16:02:41.000Z","orderDate":"2022-07-29T00:00:00.000Z","reqDelDate":"2022-07-29T00:00:00.000Z","isFreeOfCharge":false,"channelId":"01","organizationId":"5800","companyCode":"5800","businessModel":"B2B","shipTo":"550071632","soldTo":"550071632","orderNumber":"00102282","source":"SAFO"}';
		String typeObj = 'Order';
		String recordName = 'Pedido de Venta Directa';

		Test.startTest();
        	WebServiceSap.SendAlta respuesta = WebServiceSap.sendAltaToSap(body, typeObj, recordName);			
		Test.stopTest();
        sendOrderToSapController.sendEmail(respuesta);
		system.assertEquals(1, Limits.getEmailInvocations(), 'El mail no fue enviado');
		
	}

}