force-app/main/default/objects/Account/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Canal de Distribución</description>
    <label>Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Campo donde se especifica la organización de ventas perteneciente.</description>
    <label>Sales organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ApiDanone__c/ApiDanone__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuración para guardar datos de conexión a la api danone</description>
    <label>Api Danone</label>
</CustomObject>

force-app/main/default/objects/ApiDanone__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>endpoint</description>
    <label>URL</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlClaimExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlClaimExtension__c</fullName>
    <description>Extension para enviar reclamos de tipo Manejo de dinero. Ej: Diferencia de precios</description>
    <label>UrlClaimExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlCreateOrderExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlCreateOrderExtension__c</fullName>
    <description>Extension usada para enviar ordenes</description>
    <label>UrlCreateOrderExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/urlMatPrices__c.field-meta.xml
<CustomField>
    <fullName>urlMatPrices__c</fullName>
    <description>Url test para pedir precios de materiales para un cliente.</description>
    <label>urlMatPrices</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlreturnExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlreturnExtension__c</fullName>
    <description>Extension usada para enviar reclamos del tipo Manejo de inventario. Ej : Devoluciones</description>
    <label>UrlreturnExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/User_Key__c.field-meta.xml
<CustomField>
    <fullName>User_Key__c</fullName>
    <label>User Key</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/User_Key_Price__c.field-meta.xml
<CustomField>
    <fullName>User_Key_Price__c</fullName>
    <description>Key used for price callout</description>
    <label>User Key Price</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_Factura__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Factura__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Factura relacionada al reclamo generado.</description>
    <label>Factura</label>
    <referenceTo>Dan360_Factura__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dan360_ReclamoAprobado__c.field-meta.xml
<CustomField>
    <fullName>Dan360_ReclamoAprobado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que se marcara cuando el reclamo sea aprobado por el o los roles correspondientes</description>
    <label>Reclamo Aprobado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Acceso.recordType-meta.xml
<RecordType>
    <fullName>Acceso</fullName>
    <active>false</active>
    <businessProcess>Acceso</businessProcess>
    <label>Acceso</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Diferencia.recordType-meta.xml
<RecordType>
    <fullName>Diferencia</fullName>
    <active>true</active>
    <businessProcess>Diferencia</businessProcess>
    <description>Para Danone Sales</description>
    <label>Diferencia</label>
</RecordType>

force-app/main/default/objects/Dan360_Cuota__c/Dan360_Cuota__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacenará las cuotas que se aplicán a los pedidos, para controlar las cantidades de producto que se pueden procesar en cada pedido y las cantidades que quedarán &quot;Retenidas por cuota&quot;.</description>
    <label>Cuota</label>
    <nameField>
        <displayFormat>Cuo-{0000}</displayFormat>
        <label>Nombre de Cuota</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_Cuota__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Cuota__c</fullName>
    <description>Cuota asignada al producto.</description>
    <label>Cuota</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/Dan360_CustomerSalesArea__c.object-meta.xml
<CustomObject>
    <description>Customer Sales Area</description>
    <label>Customer Sales Area</label>
    <nameField>
        <label>Nombre de Customer Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Sales Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/fields/Dan360_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesArea__c</fullName>
    <description>Unidad de negocio que se asocia al cliente.</description>
    <label>Unidad de negocio</label>
    <referenceTo>Dan360_SalesArea__c</referenceTo>
    <relationshipLabel>Customer Sales Area</relationshipLabel>
    <relationshipName>Customer_Sales_Area</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/Dan360_Factura__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los documentos de cuentas corrientes de los clientes que se relacionan a un pedido.</description>
    <label>Factura</label>
    <nameField>
        <displayFormat>Fact-{0000}</displayFormat>
        <label>Nombre de Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Partner__c/Dan360_Partner__c.object-meta.xml
<CustomObject>
    <description>Partner</description>
    <label>Partner</label>
    <nameField>
        <label>Nombre de Partner</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Partner__c/fields/Dan360_CustomerSalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CustomerSalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Area</label>
    <referenceTo>Dan360_CustomerSalesArea__c</referenceTo>
    <relationshipLabel>Parners</relationshipLabel>
    <relationshipName>Parners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductosDeReclamo__c/Dan360_ProductosDeReclamo__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los productos que se relacionan aun reclamo.</description>
    <label>Producto de Reclamo</label>
    <nameField>
        <label>Nombre de Productos de Reclamo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos de reclamo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_SalesArea__c/Dan360_SalesArea__c.object-meta.xml
<CustomObject>
    <description>Sales Area</description>
    <label>Sales Area</label>
    <nameField>
        <label>Nombre de Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Distribution channel</description>
    <label>Distribution channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_Division__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Division__c</fullName>
    <description>División</description>
    <label>División</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Sales Organization</description>
    <label>Sales Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_CustomerSalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CustomerSalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Sales Area relacionado al pedido</description>
    <label>Customer Sales Area</label>
    <referenceTo>Dan360_CustomerSalesArea__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ID_SAP__c.field-meta.xml
<CustomField>
    <fullName>ID_SAP__c</fullName>
    <externalId>true</externalId>
    <label>ID SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Id_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CaseTriggerHelperTest.cls
@isTest
public with sharing class CaseTriggerHelperTest {
    static XHttpCalloutMock getResponse;    
    static string datee;

	static {
        List<OrderItem> orderItems = new List<OrderItem>();

        insert new ApiDanone__c(URL__c = 'https://www.danapi.com.ar',User_Key__c = 'c3366a9f16190d9efda328ecec6f6833', User_Key_Price__c = 'c3366a9f16190d9efda328ecec6f6833',UrlClaimExtension__c = '/testing/sales/claim/v1',
        UrlreturnExtension__c = '/testing/sales/return/v1', UrlCreateOrderExtension__c = '/testing/sales/orders/v1', urlMatPrices__c = '/testing/masterdata/price/');
		               
        RecordType pedidoVentaDirecta = [SELECT id FROM RecordType where sObjectType='Order' and Name = 'Pedido de Venta Directa'];
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Date todayDate = Date.Today();

        Account account = Build.anAccount()
            .withPricebook(pricebookId)
            .withCanalComercial('E-Commerce')
            .withName('Cuenta Prueba')
            .withIdSap('12345')
            .withSalesDistric('Modern Trade')
            .build();
        
        insert account;

        Product2 producto = Build.aProduct()
            .withName('Producto Test')
            .withUnidadesBulto(15)
            .withProductCode('00012')
            .withIdSap('106959')
            .withIsActive(true)
            .build();

        insert producto;

        Product2 productoTwo = Build.aProduct()
            .withName('Producto Test2')
            .withUnidadesBulto(15)
            .withProductCode('00015')
            .withIdSap('166578')
            .withIsActive(true)
            .build();

        insert productoTwo;

        Dan360_Cuota__c cuotaOne = Build.aCuota()
            .withProducto(producto)
            .withCanalComercial('Acceso')
            .withVigenciaDesde(todayDate)
            .withVigenciaHasta(todayDate.addDays(6))
            .build();
        insert cuotaOne;

        Dan360_Cuota__c cuotaTwo = Build.aCuota()
            .withProducto(productoTwo)
            .withCanalComercial('Acceso')
            .withVigenciaDesde(todayDate)
            .withVigenciaHasta(todayDate.addDays(6))
            .build();
        insert cuotaTwo;

        List<PricebookEntry> pricebooksEntries = [
                                    SELECT  IsActive,Pricebook2Id,Product2Id,UnitPrice
                                    FROM PricebookEntry
                                    WHERE Pricebook2Id = :pricebookId];
           
        Dan360_SalesArea__c salesArea = Build.aSalesArea()
            .withName('AMN-01-01')
            .withIdExterno('5800-01-01')
            .withDistributionChannel('01')
            .withDivision('01')
            .withSalesOrganization('5800')
            .build();

        insert salesArea;

        Dan360_CustomerSalesArea__c customerSalesArea = Build.aCustomerSalesArea()
            .withName('AMN 00')
            .withClient(account)
            .withUnidadNegocio(salesArea)
            .withIdExterno('5678-5800-01-01')
            .build();
        insert customerSalesArea;
        
       
        Order orderTestAMN = Build.anOrder()
            .withAccount(account)
            .withEffectiveDate(Date.today())
            .withEndDate(Date.today())
            .withFechaCierreCarrito(DateTime.now().addDays(5))
            .withFechaInicioCarrito(DateTime.now().addDays(1))
            .withStatus('Borrador')
            .withPurchaseOrder('00000742')
            .withBusinessUnit('5800')
            .withRecordType(pedidoVentaDirecta.Id)
            .withDescription('test')
            .withCustomerSalesArea(customerSalesArea)
            .withPricebook(pricebookId)
            .build();

        insert orderTestAMN;

        for(PricebookEntry pricebookEntry : pricebooksEntries) {
            orderItems.add(
            		Build.anOrderItem()
            			.withOrder(orderTestAMN)
            			.withProduct2Id(pricebookEntry.Product2Id)
            			.withListPrice(PricebookEntry.UnitPrice)
            			.withUnitPrice(PricebookEntry.UnitPrice)
            			.withQuantity(1)
            			.withPricebookEntryId(pricebookEntry)
            			.withDiscount(0.5)
            			.build()
            	);
            }
        
        insert orderItems;

        

        Dan360_Partner__c shipt = Build.aPartner()
            .withIdExterno('0')
            .withRol('WE')
            .withClient(account)
            .withCustomerSalesArea(customerSalesArea)
            .withName('Ship to')
            .build();

        insert shipt;

        Dan360_Partner__c sold = Build.aPartner()
            .withIdExterno('3814320001')
            .withRol('AG')
            .withClient(account)
            .withCustomerSalesArea(customerSalesArea)
            .withName('Sold to')
            .build();

        insert sold;

        Dan360_Factura__c factura = Build.aFactura()
            .withPedido(orderTestAMN)
            .withSucursal(account)
            .withClient(account)
            .build();

        insert factura;

        Id rtReturnCase = Schema.SObjectType.case.getRecordTypeInfosByName().get('Devoluciones').getRecordTypeId();
                
        Case returnCase = Build.aReclamo()
            .withAccount(account)
            .withFactura(factura)
            .withPedido(orderTestAMN.Id)
            .withMotivoDeReclamo('PRODA')
            .withRecordType(rtReturnCase)
            .build();

        insert returnCase;
       
        Dan360_ProductosDeReclamo__c productReturnCase = Build.aProductoDeReclamo()
            .withUnidadMedida('PCE')
            .withIdLinea('00010')
            .withCantidadDevolver('10')
            .withProducto(producto)
            .withReclamo(returnCase.Id)
            .build();

        insert productReturnCase;

        Id rtDifferenceCase = Schema.SObjectType.case.getRecordTypeInfosByName().get('Diferencia de precios y descuentos').getRecordTypeId();
                
        Case DifferenceCase = Build.aReclamo()
            .withAccount(account)
            .withFactura(factura)
            .withPedido(orderTestAMN.Id)
            .withMotivoDeReclamo('PRODA')
            .withRecordType(rtDifferenceCase)
            .build();

        insert DifferenceCase;
       
        Dan360_ProductosDeReclamo__c productDifferenceCase = Build.aProductoDeReclamo()
            .withUnidadMedida('PCE')
            .withIdLinea('00010')
            .withCantidadDevolver('10')
            .withProducto(producto)
            .withReclamo(DifferenceCase.Id)
            .build();

        insert productDifferenceCase;
              
        datee = String.valueOf(Date.today().year())+'-'+Date.today().month().format()+'-'+Date.today().day().format();
        getResponse = new XHttpCalloutMock();
        getResponse.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(SapPricesMock.getSucess())
			.addForAddress(WebServiceSap.SERVICE_CONFIG.URL__c + WebServiceSap.SERVICE_CONFIG.urlMatPrices__c + 'sn?date='+datee+'&organizationId='+salesArea.Dan360_SalesOrganization__c+'&channelId='+salesArea.Dan360_DistributionChannel__c+'&divisionId='+salesArea.Dan360_Division__c+'&customer='+account.Id_SAP__c);
			//.addForAddress('https://www.danapi.com.ar/testing/masterdata/price/sn?date='+datee+'&organizationId=5800&channelId=01&divisionId=01&customer=550071632');
		
		getResponse.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WebServiceSapMock.getAltaSuccess())
			.addForAddress(WebServiceSap.SERVICE_CONFIG.URL__c + WebServiceSap.SERVICE_CONFIG.UrlCreateOrderExtension__c);
	}
    @isTest
    private static void whendUpdateReturnCaseMustUpdateStatusToAuthorized() {
        // Test data setup
        Test.setMock(HttpCalloutMock.class, getResponse);

        Id rtReturnCase = Schema.SObjectType.case.getRecordTypeInfosByName().get('Devoluciones').getRecordTypeId();
        Case returnCase = [
            SELECT Id, Status, Dan360_ReclamoAprobado__c
            FROM Case
            WHERE RecordTypeId = :rtReturnCase
        ];
        returnCase.Dan360_ReclamoAprobado__c = true;
        // firts approve

        List<Approval.ProcessWorkitemRequest> approvalRequests = new List<Approval.ProcessWorkitemRequest>();

        // Query the ProcessInstanceWorkitem object to get the approval process work items
        List<ProcessInstanceWorkitem> workItems = [SELECT Id FROM ProcessInstanceWorkitem WHERE ProcessInstance.Status = 'Pending' AND ProcessInstance.TargetObjectId =:returnCase.Id];

        for (ProcessInstanceWorkitem workItem : workItems) {
            Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
            req.setComments('Auto-approved through Apex');
            req.setAction('Approve');
            req.setWorkitemId(workItem.Id);
            approvalRequests.add(req);
        }

        if (!approvalRequests.isEmpty()) {
            List<Approval.ProcessResult> results = Approval.process(approvalRequests);        
        }        
        
        // Actual test
        Test.startTest();
            //update returnCase;
        Test.stopTest();        
        List<Approval.ProcessWorkitemRequest> approvalRequestsTwo = new List<Approval.ProcessWorkitemRequest>();

        // Query the ProcessInstanceWorkitem object to get the approval process work items
        List<ProcessInstanceWorkitem> workItemsTwo = [SELECT Id FROM ProcessInstanceWorkitem WHERE ProcessInstance.Status = 'Pending' AND ProcessInstance.TargetObjectId =:returnCase.Id];

        for (ProcessInstanceWorkitem workItem : workItemsTwo) {
            Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
            req.setComments('Auto-approved through Apex');
            req.setAction('Approve');
            req.setWorkitemId(workItem.Id);
            approvalRequestsTwo.add(req);
        }

        if (!approvalRequestsTwo.isEmpty()) {
            List<Approval.ProcessResult> results = Approval.process(approvalRequestsTwo);        
        }
        
        Case returnCaseToCompare = [
            SELECT Id, Status, Dan360_ReclamoAprobado__c
            FROM Case
            WHERE RecordTypeId = :rtReturnCase
        ];
        // Asserts
        System.assertEquals('Autorizado', returnCaseToCompare.Status, 'Error to update status');
    }
    
}