force-app/main/default/objects/Account/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Canal de Distribución</description>
    <label>Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Campo donde se especifica la organización de ventas perteneciente.</description>
    <label>Sales organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ApiDanone__c/ApiDanone__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuración para guardar datos de conexión a la api danone</description>
    <label>Api Danone</label>
</CustomObject>

force-app/main/default/objects/ApiDanone__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>endpoint</description>
    <label>URL</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlCreateOrderExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlCreateOrderExtension__c</fullName>
    <description>Extension usada para enviar ordenes</description>
    <label>UrlCreateOrderExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/urlMatPrices__c.field-meta.xml
<CustomField>
    <fullName>urlMatPrices__c</fullName>
    <description>Url test para pedir precios de materiales para un cliente.</description>
    <label>urlMatPrices</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/User_Key__c.field-meta.xml
<CustomField>
    <fullName>User_Key__c</fullName>
    <label>User Key</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/User_Key_Price__c.field-meta.xml
<CustomField>
    <fullName>User_Key_Price__c</fullName>
    <description>Key used for price callout</description>
    <label>User Key Price</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Reclamo.recordType-meta.xml
<RecordType>
    <fullName>Reclamo</fullName>
    <active>true</active>
    <businessProcess>General</businessProcess>
    <label>Reclamo</label>
</RecordType>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/Dan360_CustomerSalesArea__c.object-meta.xml
<CustomObject>
    <description>Customer Sales Area</description>
    <label>Customer Sales Area</label>
    <nameField>
        <label>Nombre de Customer Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Sales Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/fields/Dan360_District__c.field-meta.xml
<CustomField>
    <fullName>Dan360_District__c</fullName>
    <label>Distrito</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
            </value>
            <value>
                <fullName>AR3MTR</fullName>
            </value>
            <value>
                <fullName>AR3INS</fullName>
            </value>
            <value>
                <fullName>AR3DIS</fullName>
            </value>
            <value>
                <fullName>AR3ACC</fullName>
            </value>
            <value>
                <fullName>AR3MAR</fullName>
            </value>
            <value>
                <fullName>AR3FAR</fullName>
            </value>
            <value>
                <fullName>AR3RES</fullName>
            </value>
            <value>
                <fullName>AR3TEN</fullName>
            </value>
            <value>
                <fullName>AR3PRO</fullName>
            </value>
            <value>
                <fullName>AR3PHA</fullName>
            </value>
            <value>
                <fullName>AR3INT</fullName>
            </value>
            <value>
                <fullName>AR3HOM</fullName>
            </value>
            <value>
                <fullName>AR3DPF</fullName>
            </value>
            <value>
                <fullName>#</fullName>
            </value>
            <value>
                <fullName>AR3ECO</fullName>
            </value>
            <value>
                <fullName>AR3OTH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/fields/Dan360_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesArea__c</fullName>
    <description>Unidad de negocio que se asocia al cliente.</description>
    <label>Unidad de negocio</label>
    <referenceTo>Dan360_SalesArea__c</referenceTo>
    <relationshipLabel>Customer Sales Area</relationshipLabel>
    <relationshipName>Customer_Sales_Area</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Partner__c/Dan360_Partner__c.object-meta.xml
<CustomObject>
    <description>Partner</description>
    <label>Partner</label>
    <nameField>
        <label>Nombre de Partner</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Partner__c/fields/Dan360_CustomerSalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CustomerSalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Area</label>
    <referenceTo>Dan360_CustomerSalesArea__c</referenceTo>
    <relationshipLabel>Parners</relationshipLabel>
    <relationshipName>Parners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_PlantillaDeProductos__c/Dan360_PlantillaDeProductos__c.object-meta.xml
<CustomObject>
    <description>Objetos en donde se almacenarán las plantillas de los productos.</description>
    <label>Plantilla de Productos</label>
    <nameField>
        <label>Plantilla</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantillas de Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_PlantillaDeProductos__c/fields/Dan360_UnidadNegocio__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadNegocio__c</fullName>
    <description>Se refiere al negocio donde se generará una transacción, en donde impactará la venta de un producto.</description>
    <label>Unidad de Negocio</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_UnidadDeNegocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/Dan360_SalesArea__c.object-meta.xml
<CustomObject>
    <description>Sales Area</description>
    <label>Sales Area</label>
    <nameField>
        <label>Nombre de Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Distribution channel</description>
    <label>Distribution channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_Division__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Division__c</fullName>
    <description>División</description>
    <label>División</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Sales Organization</description>
    <label>Sales Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_CustomerSalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CustomerSalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Sales Area relacionado al pedido</description>
    <label>Customer Sales Area</label>
    <referenceTo>Dan360_CustomerSalesArea__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_UnidadNegocio__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadNegocio__c</fullName>
    <description>Se refiere al negocio donde se generará una transacción, en donde impactará la venta de un producto.</description>
    <label>Unidad de negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_UnidadDeNegocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ID_SAP__c.field-meta.xml
<CustomField>
    <fullName>ID_SAP__c</fullName>
    <externalId>true</externalId>
    <label>ID SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Id_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Dan360_UnidadDeNegocio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5800</fullName>
        <label>AMN</label>
    </customValue>
    <customValue>
        <fullName>5771</fullName>
        <label>NuBa</label>
    </customValue>
    <description>Determina a qué unidad de negocio se genera un pedido.</description>
    <masterLabel>Unidad de Negocio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Async_ActualizarEstadoOrdenTest.cls
@isTest
public class Async_ActualizarEstadoOrdenTest {
    
    static XHttpCalloutMock getResponse;
    static XHttpCalloutMock getPriceResponse;
    static {
        List<OrderItem> orderItems = new List<OrderItem>();

        RecordType pedidoVentaDirecta = [
            SELECT id 
            FROM RecordType
            WHERE sObjectType='Order' and Name = 'Pedido de Venta Directa'
        ]; 

        Id pricebookId = Test.getStandardPricebookId();

        Account account = Build.anAccount()
            .withPricebook(pricebookId)
            .withName('Account Test')
            .withIdSap('550071632')
			.build();
		insert account;

        Product2 producto = Build.aProduct()
            .withName('Product for Test')
            .withUnidadesBulto(15)
            .withProductCode('00012')
            .withIsActive(true)
            .build();
        insert producto;

        List<PricebookEntry> pricebooksEntries = [
										SELECT  IsActive,Pricebook2Id,Product2Id,UnitPrice
										FROM PricebookEntry
										WHERE Pricebook2Id = :pricebookId];
        
        Dan360_SalesArea__c salesAreaVentaEstandar = Build.aSalesArea()
        .withName('AMN-01-01')
        .withIdExterno('5800-01-01')
        .withDistributionChannel('00')
        .withDivision('01')
        .withSalesOrganization('5800')
        .build();
        insert salesAreaVentaEstandar;

        Dan360_PlantillaDeProductos__c templateProducts = Build.aPlantillaDeProductos()
        .withName('AMN Canal 00')
        .withBusinessUnit('5800')
        .build();
        insert templateProducts;

        Dan360_PlantillaDeProductos__c templateProductsNuBa = Build.aPlantillaDeProductos()
        .withName('NuBa Canal 00')
        .withBusinessUnit('5771')
        .build();
        insert templateProductsNuBa;  

        Dan360_CustomerSalesArea__c customerSalesArea = Build.aCustomerSalesArea()
        .withName('Nuba 00')
        .withClient(account)
        .withUnidadNegocio(salesAreaVentaEstandar)
        .withIdExterno('5667-5771-01-01')
        .build();
        customerSalesArea.Dan360_District__c = 'AR3INS';
        
        Order orderTestNuBa = Build.anOrder()
            .withAccount(account)
            .withEffectiveDate(Date.today())
            .withEndDate(Date.today())
            .withFechaCierreCarrito(DateTime.now().addDays(5))
            .withFechaInicioCarrito(DateTime.now().addDays(1))
            .withStatus('Borrador')
            .withPurchaseOrder('00000743')
            .withPricebook(pricebookId)
            //.withBusinessUnit('5771')
            .withRecordType(pedidoVentaDirecta.Id)
            .withDescription('test')
            .withCustomerSalesArea(customerSalesArea)
            .build();

        orderTestNuBa.Dan360_UnidadNegocio__c = '5771';
        insert orderTestNuBa;

        for (PricebookEntry pricebookEntry : pricebooksEntries) {
            orderItems.add(
                Build.anOrderItem()
                    // .withOrder(orderTestAMN)
                    .withOrder(orderTestNuBa)
                    .withProduct2Id(pricebookEntry.Product2Id)
                    .withListPrice(100)
                    .withUnitPrice(100)
                    .withQuantity(1)
                    .withPricebookEntryId(pricebookEntry)
                    .withDiscount(0.5)
                    .build()
            );
        }
    
        insert orderItems;

        Dan360_Partner__c partnetShiptTo = Build.aPartner()
            .withName('Partner Shipt To')
            .withIdExterno('0')
            .withRol('WE')
            .withClient(account)
            .withCustomerSalesArea(customerSalesArea)
            .build();        

        insert partnetShiptTo;

        Dan360_Partner__c partnetSoldTo = Build.aPartner()
            .withName('Partner Sold To')
            .withIdExterno('3814320001')
            .withRol('AG')
            .withClient(account)
            .withCustomerSalesArea(customerSalesArea)
            .build();        
        
        insert partnetSoldTo;

        Id rtReturnCase = Schema.SObjectType.case.getRecordTypeInfosByName().get('Devoluciones').getRecordTypeId();
        Id rtReturnForMissing = Schema.SObjectType.case.getRecordTypeInfosByName().get('Reclamo por faltantes').getRecordTypeId();

        insert new ApiDanone__c(URL__c = 'https://www.danapi.com.ar',User_Key__c = 'c3366a9f16190d9efda328ecec6f6833', User_Key_Price__c = 'c3366a9f16190d9efda328ecec6f6833', urlMatPrices__c = '/testing/masterdata/price/',UrlCreateOrderExtension__c = '/testing/sales/orders/v1' );

		String datee = String.valueOf(Date.today().year())+'-'+Date.today().month().format()+'-'+Date.today().day().format();

            getPriceResponse = new XHttpCalloutMock();
            getPriceResponse.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(SapPricesMock.getSucess())
                .addForAddress(WebServiceSap.SERVICE_CONFIG.URL__c + WebServiceSap.SERVICE_CONFIG.urlMatPrices__c + 'sn?date='+datee+'&organizationId='+salesAreaVentaEstandar.Dan360_SalesOrganization__c+'&channelId='+salesAreaVentaEstandar.Dan360_DistributionChannel__c+'&divisionId='+salesAreaVentaEstandar.Dan360_Division__c+'&customer='+account.Id_SAP__c);
            
    }

    @IsTest
    static void pruebaSimple(){

    Test.setMock(HttpCalloutMock.class, getPriceResponse);

    Id OrderId = [SELECT Id FROM Order Limit 1].Id;
      ID jobID;

        Test.startTest();        
            Async_ActualizarOrden_Helper encolable  = new Async_ActualizarOrden_Helper(OrderId);
            jobID = System.enqueueJob(encolable);
        Test.stopTest();

      System.assertEquals(true, jobID <> null ? true : false, 'Async_ActualizarEstadoOrden_Helper' );
    }

    @IsTest
    static void testEncolable(){

    Order orders = [SELECT Id FROM Order Limit 1];
    List<String> orderId = new List<string>();
    orderId.add(orders.Id);

      ID jobID;

        Test.startTest();        
            Async_ActualizarEstadoOrden.Async_ActualizarEstadoOrden(orderId);
        Test.stopTest();

      System.assertEquals(1, orderId.size(), 'Async_ActualizarEstadoOrden' );
    }
}