force-app/main/default/objects/Account/fields/Dan360_CanalComercial__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CanalComercial__c</fullName>
    <description>Canal comercial de la cuenta</description>
    <label>Canal Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_CanalComercial</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Canal de Distribución</description>
    <label>Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_SalesDistric1__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesDistric1__c</fullName>
    <label>Sales District</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acceso</fullName>
            </value>
            <value>
                <fullName>Disprofarma</fullName>
            </value>
            <value>
                <fullName>Distribuidores</fullName>
            </value>
            <value>
                <fullName>DistribuidoresLicitaciones</fullName>
                <isActive>false</isActive>
                <label>DistribuidoresLicitaciones</label>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>Farmacias</fullName>
            </value>
            <value>
                <fullName>Farmacity</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Instituciones</fullName>
            </value>
            <value>
                <fullName>INTERCO</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Licitaciones</fullName>
            </value>
            <value>
                <fullName>LicitacionesDistribuidores</fullName>
                <isActive>false</isActive>
                <label>LicitacionesDistribuidores</label>
            </value>
            <value>
                <fullName>LicitacionesDistribuidoresLicitacionesDistribuidores</fullName>
                <isActive>false</isActive>
                <label>LicitacionesDistribuidoresLicitacionesDistribuidores</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Modern Trade</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Proximity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/Dan360_Cuota__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacenará las cuotas que se aplicán a los pedidos, para controlar las cantidades de producto que se pueden procesar en cada pedido y las cantidades que quedarán &quot;Retenidas por cuota&quot;.</description>
    <label>Cuota</label>
    <nameField>
        <displayFormat>Cuo-{0000}</displayFormat>
        <label>Nombre de Cuota</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_CanalComercial__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CanalComercial__c</fullName>
    <description>Canal comercial para el que aplicará la cuota.</description>
    <label>Canal Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_CanalComercial</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_CanalDistribucion__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CanalDistribucion__c</fullName>
    <description>Campo que señala el canal de distribución para una cuota.</description>
    <label>Canal de distribución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Venta Estándar</fullName>
            </value>
            <value>
                <fullName>Sin Cargo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Si la cuota aplica para un cliente en específico</description>
    <label>Cliente</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Id_SAP__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuotas</relationshipLabel>
    <relationshipName>Cuotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_Cuota__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Cuota__c</fullName>
    <description>Cuota asignada al producto.</description>
    <label>Cuota</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_EstadoCuota__c.field-meta.xml
<CustomField>
    <fullName>Dan360_EstadoCuota__c</fullName>
    <description>Indica el estado en el que se encuentra una cuota.</description>
    <label>Estado de cuota</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activa</fullName>
            </value>
            <value>
                <fullName>Inactiva</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_Producto__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Producto para el cual aplicará la cuota.</description>
    <label>Producto</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cuotas</relationshipLabel>
    <relationshipName>Cuotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_Saldo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Saldo__c</fullName>
    <description>Saldo que va quedando para la cuota cada vez que aplica para un pedido.</description>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_VigenciaDesde__c.field-meta.xml
<CustomField>
    <fullName>Dan360_VigenciaDesde__c</fullName>
    <description>Campo que indica el momento desde el cual una cuota empieza a ser vigente.</description>
    <label>Vigencia desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_VigenciaHasta__c.field-meta.xml
<CustomField>
    <fullName>Dan360_VigenciaHasta__c</fullName>
    <description>Fecha que indica el momento en que una cuota deja de ser vigente.</description>
    <label>Vigencia hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_SemaforoPicklist__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SemaforoPicklist__c</fullName>
    <description>Señala el color del semáforo (Verde, amarillo o rojo) dependiendo de la cuota disponible para el pedido.</description>
    <label>SemaforoPicklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rojo</fullName>
            </value>
            <value>
                <fullName>Amarillo</fullName>
            </value>
            <value>
                <fullName>Verde</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Dan360_CanalComercial.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acceso</fullName>
    </customValue>
    <customValue>
        <fullName>Disprofarma</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidores</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Farmacias</fullName>
    </customValue>
    <customValue>
        <fullName>Farmacity</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care</fullName>
    </customValue>
    <customValue>
        <fullName>Instituciones</fullName>
    </customValue>
    <customValue>
        <fullName>INTERCO</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Licitaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Modern Trade</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Proximity</fullName>
    </customValue>
    <customValue>
        <fullName>Tender management</fullName>
        <isActive>false</isActive>
        <label>Tender management</label>
    </customValue>
    <customValue>
        <fullName>Pharmacy</fullName>
        <isActive>false</isActive>
        <label>Pharmacy</label>
    </customValue>
    <customValue>
        <fullName>MeLi</fullName>
        <isActive>false</isActive>
        <label>MeLi</label>
    </customValue>
    <customValue>
        <fullName>Health Care</fullName>
        <isActive>false</isActive>
        <label>Health Care</label>
    </customValue>
    <customValue>
        <fullName>Export</fullName>
        <isActive>false</isActive>
        <label>Export</label>
    </customValue>
    <customValue>
        <fullName>Employees</fullName>
        <isActive>false</isActive>
        <label>Employees</label>
    </customValue>
    <masterLabel>Canal comercial</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/CuotaTriggerHelper.cls
public with sharing class CuotaTriggerHelper {

	public static void processDuplicatedLogic(List<Dan360_Cuota__c> cuotaList) {

		List<String> productId = new List<String>();
		List<String> productCanal = new List<String>();
		List<Dan360_Cuota__c> mapCuotasToInsert = new List<Dan360_Cuota__c>();
		Map<String, Map< String, List<Dan360_Cuota__c>>> mapCuotasSalesForce = new Map<String, Map< String, List<Dan360_Cuota__c>>>();

		for(Dan360_Cuota__c cuota : cuotaList) {
			productId.add(cuota.Dan360_Producto__c);
			productCanal.add(cuota.Dan360_CanalComercial__c);
		}

		for(Dan360_Cuota__c cuotaSF : [
			SELECT Name, Dan360_CanalComercial__c, Dan360_VigenciaDesde__c, Dan360_VigenciaHasta__c, 
				Dan360_Producto__c, Dan360_CanalDistribucion__c, Dan360_Cliente__c
			FROM Dan360_Cuota__c
			WHERE (Dan360_Producto__c IN :productId) AND (Dan360_CanalComercial__c IN :productCanal)
			WITH SECURITY_ENFORCED
		]){

			if(!mapCuotasSalesForce.containsKey(cuotaSF.Dan360_Producto__c)){
				mapCuotasSalesForce.put(cuotaSF.Dan360_Producto__c, new Map< String, List<Dan360_Cuota__c>>());
			}

			if(!mapCuotasSalesForce.get(cuotaSF.Dan360_Producto__c).containsKey(cuotaSF.Dan360_CanalComercial__c)){
				mapCuotasSalesForce.get(cuotaSF.Dan360_Producto__c).put(cuotaSF.Dan360_CanalComercial__c, new List<Dan360_Cuota__c>());
			}
			mapCuotasSalesForce.get(cuotaSF.Dan360_Producto__c).get(cuotaSF.Dan360_CanalComercial__c).add(cuotaSF);
		}

		for(Dan360_Cuota__c cuotaToInsert : cuotaList){

			if(mapCuotasSalesForce.containsKey(cuotaToInsert.Dan360_Producto__c)){
				if(mapCuotasSalesForce.get(cuotaToInsert.Dan360_Producto__c).containsKey(cuotaToInsert.Dan360_CanalComercial__c)){
					for(Dan360_Cuota__c cuotaToCompare : mapCuotasSalesForce.get(cuotaToInsert.Dan360_Producto__c).get(cuotaToInsert.Dan360_CanalComercial__c)){
						if(
							(
								(cuotaToInsert.Dan360_VigenciaDesde__c >= cuotaToCompare.Dan360_VigenciaDesde__c) && (cuotaToInsert.Dan360_VigenciaDesde__c < cuotaToCompare.Dan360_VigenciaHasta__c) ||
								(cuotaToInsert.Dan360_VigenciaDesde__c < cuotaToCompare.Dan360_VigenciaDesde__c) && (cuotaToInsert.Dan360_VigenciaHasta__c > cuotaToCompare.Dan360_VigenciaDesde__c)
							)
							&& 
							(
								cuotaToInsert.Dan360_CanalDistribucion__c == cuotaToCompare.Dan360_CanalDistribucion__c
								&& cuotaToInsert.Dan360_CanalComercial__c == cuotaToCompare.Dan360_CanalComercial__c
								&& cuotaToInsert.Dan360_Cliente__c == cuotaToCompare.Dan360_Cliente__c
							)
						){
							cuotaToInsert.addError(System.Label.Errores + ', Cuota: '+cuotaToCompare.Name);
						}
					}
				}
			}
		}
	}

	public static void validateTrafficLightInOrders(List<Dan360_Cuota__c> dues) {
		Map<Id, Map<String, String>> ordersDues = new Map<Id, Map<String, String>>();
		Map<Id, List<OrderItem>> orderItems = new Map<Id, List<OrderItem>>();
		Map<String, Dan360_Cuota__c> productDues = new Map<String, Dan360_Cuota__c>();
		Map<String, List<Dan360_Cuota__c>> allDues = new Map<String, List<Dan360_Cuota__c>>();
		List<Order> ordersToUpdate = new List<Order>();
		Set<Id> productsId = new Set<Id>();
		Set<Id> ordersId = new Set<Id>();

		// Get products id from dues
		for (Dan360_Cuota__c quota : [
			SELECT  Dan360_Producto__c
			FROM    Dan360_Cuota__c
			WHERE   Id IN :dues
		]) {
			productsId.add(quota.Dan360_Producto__c);
		}

		// Get order items with related order by status [Retenido por cuota]
		orderItems = getOrderItems(productsId);

		if (!orderItems.isEmpty()) {
			ordersId = orderItems.keySet();

			ordersDues = getDuesThatApplyByOrder(ordersId);

			if (!ordersId.isEmpty()) {
				allDues = getDuesByType(productsId);

				if (!allDues.isEmpty()) {
					ordersToUpdate = setTrafficLightToOrders(ordersId, ordersDues, orderItems, allDues);
					
					Id profileId=userinfo.getProfileId();
					String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
					System.debug('ProfileName'+profileName);
					update ordersToUpdate;
				}
			}

		}
	}

	private static Map<Id, Map<String, String>> getDuesThatApplyByOrder(Set<Id> ordersId) {
		Map<Id, Map<String, String>> ordersDues = new Map<Id, Map<String, String>>();

		for (Order order : [
			SELECT  Id,
					AccountId,
					Account.ParentId,
					Account.Dan360_SalesDistric1__c,
					Account.Dan360_DistributionChannel__c,
					Account.RecordType.Name
			FROM    Order
			WHERE   Id IN :ordersId
		]) {
			Map<String, String> duesThatApply = new Map<String, String>();

			if (order.Account.RecordType.Name == 'Sucursal') {
				duesThatApply.put('Subsidiary', order.AccountId);
			} else {
				duesThatApply.put('Client', order.AccountId);
			}

			if (!String.isEmpty(order.Account.Dan360_SalesDistric1__c)) {
				duesThatApply.put('CommercialChannel', order.Account.Dan360_SalesDistric1__c);
			}

			if (!String.isEmpty(order.Account.Dan360_DistributionChannel__c)) {
				duesThatApply.put('DistributionChannel', order.Account.Dan360_DistributionChannel__c);
			}
			ordersDues.put(order.Id, duesThatApply);
		}

		return ordersDues;
	}

	private static Map<Id, List<OrderItem>> getOrderItems(Set<Id> productsId) {
		Map<Id, List<OrderItem>> orderItems = new Map<Id, List<OrderItem>>();

		for (OrderItem item : [
			SELECT  Product2Id,
					OrderId,
					Quantity
			FROM    OrderItem
			WHERE   Product2Id IN :productsId
				AND Order.Status = 'Retenido por cuota'
		]) {
			if (!orderItems.containsKey(item.OrderId)) {
				orderItems.put(item.OrderId, new List<OrderItem>());
			}
			orderItems.get(item.OrderId).add(item);
		}

		return orderItems;
	}

	private static Map<String, List<Dan360_Cuota__c>> getDuesByType(Set<Id> productsId) {
		Map<String, List<Dan360_Cuota__c>> dues = new Map<String, List<Dan360_Cuota__c>>();

		for (Dan360_Cuota__c quota : [
			SELECT  Id,
					Dan360_Saldo__c,
					Dan360_Producto__c,
					Dan360_Cliente__c,
					Dan360_CanalComercial__c,
					Dan360_CanalDistribucion__c,
					Dan360_EstadoCuota__c
			FROM    Dan360_Cuota__c
			WHERE   Dan360_Producto__c IN :productsId
		]) {
			if (!String.isEmpty(quota.Dan360_CanalDistribucion__c)) {
				if (!dues.containsKey('DistributionChannel')) {
					dues.put('DistributionChannel', new List<Dan360_Cuota__c>());
				}
				dues.get('DistributionChannel').add(quota);
			}

			if (String.isEmpty(quota.Dan360_CanalDistribucion__c) &&
				String.isEmpty(quota.Dan360_Cliente__c) &&
				!String.isEmpty(quota.Dan360_CanalComercial__c)
			) {
				if (!dues.containsKey('CommercialChannel')) {
					dues.put('CommercialChannel', new List<Dan360_Cuota__c>());
				}
				dues.get('CommercialChannel').add(quota);
			}

			if (String.isEmpty(quota.Dan360_CanalDistribucion__c) &&
				String.isEmpty(quota.Dan360_CanalComercial__c) &&
				!String.isEmpty(quota.Dan360_Cliente__c)
			) {
				if (!dues.containsKey('Client')) {
					dues.put('Client', new List<Dan360_Cuota__c>());
				}
				dues.get('Client').add(quota);
			}

			if (String.isEmpty(quota.Dan360_Cliente__c) &&
				String.isEmpty(quota.Dan360_CanalComercial__c) &&
				String.isEmpty(quota.Dan360_CanalDistribucion__c)
			) {
				if (!dues.containsKey('Product')) {
					dues.put('Product', new List<Dan360_Cuota__c>());
				}
				dues.get('Product').add(quota);
			}
		}
		return dues;
	}

	private static List<Order> setTrafficLightToOrders(
		Set<Id> ordersId,
		Map<Id, Map<String, String>> ordersDues,
		Map<Id, List<OrderItem>> orderItems,
		Map<String, List<Dan360_Cuota__c>> dues
	) {
		Boolean flagByClient = false; 
		Boolean flagBySubsidiary = false; 
		List<Order> ordersToUpdate = new List<Order>();

		for (Order order : [
			SELECT  Id,
					Dan360_SemaforoPicklist__c,
					Status
			FROM    Order
			WHERE   Id IN :ordersId
		]) {
			System.debug('order.Status Antes');
			System.debug(order.Status);
			List<OrderItem> orderItemsWithStock = new List<OrderItem>();
			List<OrderItem> orderItemsWithStockButNotEnough = new List<OrderItem>();
			List<OrderItem> orderItemsWithoutStock = new List<OrderItem>();
			List<OrderItem> orderItemsWithInactiveQuota = new List<OrderItem>();
			Map<String, String> orderDues = ordersDues.get(order.Id);
			Boolean hasItemsWithStock;
			Boolean hasItemsWithStockButNotEnough;
			Boolean hasItemsWithoutStock;

			for (OrderItem item : orderItems.get(order.Id)) {
				if (orderDues.containsKey('Subsidiary')) {
					if (dues.get('Client') != null && !dues.get('Client').isEmpty()) {
						for (Dan360_Cuota__c quota : dues.get('Client')) {
							if (quota.Dan360_Cliente__c == orderDues.get('Subsidiary')) {
								flagBySubsidiary = true;
								if (quota.Dan360_Producto__c == item.Product2Id) {
									if (quota.Dan360_EstadoCuota__c == 'Activa') {
										if (quota.Dan360_Saldo__c > 0 &&
											quota.Dan360_Saldo__c >= item.Quantity
										) {
											orderItemsWithStock.add(item);
										} else if (quota.Dan360_Saldo__c > 0 &&
											quota.Dan360_Saldo__c < item.Quantity
										) {
											orderItemsWithStockButNotEnough.add(item);
										} else if (quota.Dan360_Saldo__c == 0) {
											orderItemsWithoutStock.add(item);
										}
									} else {
										orderItemsWithInactiveQuota.add(item);
									}
								}
							}
						}
					} else if (dues.get('CommercialChannel') != null && !dues.get('CommercialChannel').isEmpty()) {
						for (Dan360_Cuota__c quota : dues.get('CommercialChannel')) {
							String[] listSalesDistrict = orderDues.get('CommercialChannel').split(';');
							if (!listSalesDistrict.isEmpty()) {
								if (listSalesDistrict.contains(quota.Dan360_CanalComercial__c)) {
									flagBySubsidiary = true;
									if (quota.Dan360_Producto__c == item.Product2Id) {
										if (quota.Dan360_EstadoCuota__c == 'Activa') {
											if (quota.Dan360_Saldo__c > 0 &&
												quota.Dan360_Saldo__c >= item.Quantity
											) {
												orderItemsWithStock.add(item);
											} else if (quota.Dan360_Saldo__c > 0 &&
												quota.Dan360_Saldo__c < item.Quantity
											) {
												orderItemsWithStockButNotEnough.add(item);
											} else if (quota.Dan360_Saldo__c == 0) {
												orderItemsWithoutStock.add(item);
											}
										} else {
											orderItemsWithInactiveQuota.add(item);
										}
									}
								}
							}
						}
					} else if (dues.get('DistributionChannel') != null && !dues.get('DistributionChannel').isEmpty()) {
						for (Dan360_Cuota__c quota : dues.get('DistributionChannel')) {
							String[] listDistributionChannel = orderDues.get('DistributionChannel').split(';');
							if (!listDistributionChannel.isEmpty()) {
								if (listDistributionChannel.contains(quota.Dan360_CanalDistribucion__c)) {
									flagBySubsidiary = true;
									if (quota.Dan360_Producto__c == item.Product2Id) {
										if (quota.Dan360_EstadoCuota__c == 'Activa') {
											if (quota.Dan360_Saldo__c > 0 &&
											quota.Dan360_Saldo__c >= item.Quantity
											) {
												orderItemsWithStock.add(item);
											} else if (quota.Dan360_Saldo__c > 0 &&
											quota.Dan360_Saldo__c < item.Quantity
											) {
												orderItemsWithStockButNotEnough.add(item);
											} else if (quota.Dan360_Saldo__c == 0) {
												orderItemsWithoutStock.add(item);
											}
										} else {
											orderItemsWithInactiveQuota.add(item);
										}
									}
								}
							}
						}
					} 
					if (!flagBySubsidiary) {
						if (dues.get('Product') != null && !dues.get('Product').isEmpty()) {
							for (Dan360_Cuota__c quota : dues.get('Product')) {
								if (quota.Dan360_Producto__c == item.Product2Id) {
									if (quota.Dan360_EstadoCuota__c == 'Activa') {
										if (quota.Dan360_Saldo__c > 0 &&
											quota.Dan360_Saldo__c >= item.Quantity
										) {
											orderItemsWithStock.add(item);
										} else if (quota.Dan360_Saldo__c > 0 &&
											quota.Dan360_Saldo__c < item.Quantity
										) {
											orderItemsWithStockButNotEnough.add(item);
										} else if (quota.Dan360_Saldo__c == 0) {
											orderItemsWithoutStock.add(item);
										}
									} else {
										orderItemsWithInactiveQuota.add(item);
									}
								}
							}
						}
					}
				} else if (orderDues.containsKey('Client')) {
					if (dues.get('Client') != null && !dues.get('Client').isEmpty()) {
						for (Dan360_Cuota__c quota : dues.get('Client')) {
							if (quota.Dan360_Cliente__c == orderDues.get('Client')) {
								flagByClient = true; 
								if (quota.Dan360_Producto__c == item.Product2Id) {
									if (quota.Dan360_EstadoCuota__c == 'Activa') {
										if (quota.Dan360_Saldo__c > 0 &&
											quota.Dan360_Saldo__c >= item.Quantity
										) {
											orderItemsWithStock.add(item);
										} else if (quota.Dan360_Saldo__c > 0 &&
											quota.Dan360_Saldo__c < item.Quantity
										) {
											orderItemsWithStockButNotEnough.add(item);
										} else if (quota.Dan360_Saldo__c == 0) {
											orderItemsWithoutStock.add(item);
										}
									} else {
										orderItemsWithInactiveQuota.add(item);
									}
								}
							} 
						}
					} else if (dues.get('CommercialChannel') != null && !dues.get('CommercialChannel').isEmpty()) {
						for (Dan360_Cuota__c quota : dues.get('CommercialChannel')) {
							String[] listSalesDistrict = orderDues.get('CommercialChannel').split(';');
							if (!listSalesDistrict.isEmpty()) {
								if (listSalesDistrict.contains(quota.Dan360_CanalComercial__c)) {
									flagByClient = true; 
									if (quota.Dan360_Producto__c == item.Product2Id) {
										if (quota.Dan360_EstadoCuota__c == 'Activa') {
											if (quota.Dan360_Saldo__c > 0 &&
												quota.Dan360_Saldo__c >= item.Quantity
											) {
												orderItemsWithStock.add(item);
											} else if (quota.Dan360_Saldo__c > 0 &&
												quota.Dan360_Saldo__c < item.Quantity
											) {
												orderItemsWithStockButNotEnough.add(item);
											} else if (quota.Dan360_Saldo__c == 0) {
												orderItemsWithoutStock.add(item);
											}
										} else {
											orderItemsWithInactiveQuota.add(item);
										}
									}
								}
							}
						}
					} else if (dues.get('DistributionChannel') != null && !dues.get('DistributionChannel').isEmpty()) {
						String[] listDistributionChannel; 	
						for (Dan360_Cuota__c quota : dues.get('DistributionChannel')) {
							if (orderDues.get('DistributionChannel') != null) {
								listDistributionChannel = orderDues.get('DistributionChannel').split(';');
								if (!listDistributionChannel.isEmpty()) {
									if (listDistributionChannel.contains(quota.Dan360_CanalDistribucion__c)) {
										flagByClient = true; 
										if (quota.Dan360_Producto__c == item.Product2Id) {
											if (quota.Dan360_EstadoCuota__c == 'Activa') {
												if (quota.Dan360_Saldo__c > 0 &&
												quota.Dan360_Saldo__c >= item.Quantity
												) {
													orderItemsWithStock.add(item);
												} else if (quota.Dan360_Saldo__c > 0 &&
												quota.Dan360_Saldo__c < item.Quantity
												) {
													orderItemsWithStockButNotEnough.add(item);
												} else if (quota.Dan360_Saldo__c == 0) {
													orderItemsWithoutStock.add(item);
												}
											} else {
												orderItemsWithInactiveQuota.add(item);
											}
										}
									}
								}
							} 
						}
					} 
					if (!flagByClient) {
						if (dues.get('Product') != null && !dues.get('Product').isEmpty()) {
							for (Dan360_Cuota__c quota : dues.get('Product')) {
								if (quota.Dan360_Producto__c == item.Product2Id) {
									if (quota.Dan360_EstadoCuota__c == 'Activa') {
										if (quota.Dan360_Saldo__c > 0 &&
											quota.Dan360_Saldo__c >= item.Quantity
										) {
											orderItemsWithStock.add(item);
										} else if (quota.Dan360_Saldo__c > 0 &&
											quota.Dan360_Saldo__c < item.Quantity
										) {
											orderItemsWithStockButNotEnough.add(item);
										} else if (quota.Dan360_Saldo__c == 0) {
											orderItemsWithoutStock.add(item);
										}
									} else {
										orderItemsWithInactiveQuota.add(item);
									}
								}
							}
						}
					}
				}
			}

			hasItemsWithStock = !orderItemsWithStock.isEmpty();
			hasItemsWithStockButNotEnough = !orderItemsWithStockButNotEnough.isEmpty();
			hasItemsWithoutStock = !orderItemsWithoutStock.isEmpty();

			// Si todos los items de la orden tienen cuota activa o todos se encuentran con cuota inactiva
			if (!orderItemsWithInactiveQuota.isEmpty() && orderItemsWithInactiveQuota.size() == orderItems.get(order.Id).size()) {
				order.Dan360_SemaforoPicklist__c = 'Verde';
			} else if (!orderItemsWithInactiveQuota.isEmpty()) {
				order.Dan360_SemaforoPicklist__c = getTrafficLight(hasItemsWithStock, hasItemsWithStockButNotEnough, hasItemsWithoutStock, true);
			} else {
				order.Dan360_SemaforoPicklist__c = getTrafficLight(hasItemsWithStock, hasItemsWithStockButNotEnough, hasItemsWithoutStock, false);
			}

			ordersToUpdate.add(order);
			System.debug('order.Status Despues');
			System.debug(order.Status);
		}

		return ordersToUpdate;
	}

	private static String getTrafficLight(
		Boolean hasItemsWithStock,
		Boolean hasItemsWithStockButNotEnough,
		Boolean hasItemsWithoutStock,
		Boolean hasInactiveItems
	) {
		String trafficLight;

		if (hasItemsWithStockButNotEnough || (hasItemsWithoutStock && hasItemsWithStock)) {
			trafficLight = 'Amarillo';
		} else if (hasItemsWithStock && (!hasItemsWithStockButNotEnough && !hasItemsWithoutStock)) {
			trafficLight = 'Verde';
		} else if (hasItemsWithoutStock && (!hasItemsWithStockButNotEnough && !hasItemsWithStock)) {
			if (hasInactiveItems) {
				trafficLight = 'Amarillo';
			} else {
				trafficLight = 'Rojo';
			}
		} else {
			trafficLight = 'Verde';
		}

		return trafficLight;
	}
}