force-app/main/default/objects/Account/fields/Dan360_CanalComercial__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CanalComercial__c</fullName>
    <description>Canal comercial de la cuenta</description>
    <label>Canal Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_CanalComercial</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Canal de Distribución</description>
    <label>Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_SalesDistric1__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesDistric1__c</fullName>
    <label>Sales District</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acceso</fullName>
            </value>
            <value>
                <fullName>Disprofarma</fullName>
            </value>
            <value>
                <fullName>Distribuidores</fullName>
            </value>
            <value>
                <fullName>DistribuidoresLicitaciones</fullName>
                <isActive>false</isActive>
                <label>DistribuidoresLicitaciones</label>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>Farmacias</fullName>
            </value>
            <value>
                <fullName>Farmacity</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Instituciones</fullName>
            </value>
            <value>
                <fullName>INTERCO</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Licitaciones</fullName>
            </value>
            <value>
                <fullName>LicitacionesDistribuidores</fullName>
                <isActive>false</isActive>
                <label>LicitacionesDistribuidores</label>
            </value>
            <value>
                <fullName>LicitacionesDistribuidoresLicitacionesDistribuidores</fullName>
                <isActive>false</isActive>
                <label>LicitacionesDistribuidoresLicitacionesDistribuidores</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Modern Trade</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Proximity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Campo donde se especifica la organización de ventas perteneciente.</description>
    <label>Sales organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ApiDanone__c/ApiDanone__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuración para guardar datos de conexión a la api danone</description>
    <label>Api Danone</label>
</CustomObject>

force-app/main/default/objects/ApiDanone__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>endpoint</description>
    <label>URL</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlClaimExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlClaimExtension__c</fullName>
    <description>Extension para enviar reclamos de tipo Manejo de dinero. Ej: Diferencia de precios</description>
    <label>UrlClaimExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlCreateOrderExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlCreateOrderExtension__c</fullName>
    <description>Extension usada para enviar ordenes</description>
    <label>UrlCreateOrderExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/urlMatPrices__c.field-meta.xml
<CustomField>
    <fullName>urlMatPrices__c</fullName>
    <description>Url test para pedir precios de materiales para un cliente.</description>
    <label>urlMatPrices</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlreturnExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlreturnExtension__c</fullName>
    <description>Extension usada para enviar reclamos del tipo Manejo de inventario. Ej : Devoluciones</description>
    <label>UrlreturnExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/User_Key__c.field-meta.xml
<CustomField>
    <fullName>User_Key__c</fullName>
    <label>User Key</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/User_Key_Price__c.field-meta.xml
<CustomField>
    <fullName>User_Key_Price__c</fullName>
    <description>Key used for price callout</description>
    <label>User Key Price</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/Dan360_Cuota__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacenará las cuotas que se aplicán a los pedidos, para controlar las cantidades de producto que se pueden procesar en cada pedido y las cantidades que quedarán &quot;Retenidas por cuota&quot;.</description>
    <label>Cuota</label>
    <nameField>
        <displayFormat>Cuo-{0000}</displayFormat>
        <label>Nombre de Cuota</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_CanalComercial__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CanalComercial__c</fullName>
    <description>Canal comercial para el que aplicará la cuota.</description>
    <label>Canal Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_CanalComercial</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_Cuota__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Cuota__c</fullName>
    <description>Cuota asignada al producto.</description>
    <label>Cuota</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/Dan360_CustomerSalesArea__c.object-meta.xml
<CustomObject>
    <description>Customer Sales Area</description>
    <label>Customer Sales Area</label>
    <nameField>
        <label>Nombre de Customer Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Sales Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/fields/Dan360_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesArea__c</fullName>
    <description>Unidad de negocio que se asocia al cliente.</description>
    <label>Unidad de negocio</label>
    <referenceTo>Dan360_SalesArea__c</referenceTo>
    <relationshipLabel>Customer Sales Area</relationshipLabel>
    <relationshipName>Customer_Sales_Area</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_PlantillaDeProductos__c/Dan360_PlantillaDeProductos__c.object-meta.xml
<CustomObject>
    <description>Objetos en donde se almacenarán las plantillas de los productos.</description>
    <label>Plantilla de Productos</label>
    <nameField>
        <label>Plantilla</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantillas de Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_SalesArea__c/Dan360_SalesArea__c.object-meta.xml
<CustomObject>
    <description>Sales Area</description>
    <label>Sales Area</label>
    <nameField>
        <label>Nombre de Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Distribution channel</description>
    <label>Distribution channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_Division__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Division__c</fullName>
    <description>División</description>
    <label>División</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Sales Organization</description>
    <label>Sales Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_CustomerSalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CustomerSalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Sales Area relacionado al pedido</description>
    <label>Customer Sales Area</label>
    <referenceTo>Dan360_CustomerSalesArea__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Id_Externo__c</fullName>
    <description>Id Externo de la órdenes. Se diligenciará a través de una automatización para replicar el número de la orden de Salesforce.</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_PlantillaProductos__c.field-meta.xml
<CustomField>
    <fullName>Dan360_PlantillaProductos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que se va a llenar con desarrollo para conocer la plantilla que se relaciona al pedido.</description>
    <label>Plantilla de Productos</label>
    <referenceTo>Dan360_PlantillaDeProductos__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Dan360_PedidoVentaDirecta.recordType-meta.xml
<RecordType>
    <fullName>Dan360_PedidoVentaDirecta</fullName>
    <active>true</active>
    <label>Pedido de Venta Directa</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/Dan360_UnidadMedida__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadMedida__c</fullName>
    <label>Unidad de medida</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plantillas__c/Plantillas__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Plantillas</label>
</CustomObject>

force-app/main/default/objects/Plantillas__c/fields/NuBa_00__c.field-meta.xml
<CustomField>
    <fullName>NuBa_00__c</fullName>
    <label>NuBa Canal 00</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Dan360_CustomerSalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CustomerSalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Sales Area</label>
    <referenceTo>Dan360_CustomerSalesArea__c</referenceTo>
    <relationshipLabel>Listas de precios</relationshipLabel>
    <relationshipName>Listas_de_precios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/ID_SAP__c.field-meta.xml
<CustomField>
    <fullName>ID_SAP__c</fullName>
    <description>Es el customer ID.</description>
    <externalId>true</externalId>
    <label>ID SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Dan360_UnidadMedida__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadMedida__c</fullName>
    <label>Unidad de medida</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unidad</fullName>
            </value>
            <value>
                <fullName>Bulto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ID_SAP__c.field-meta.xml
<CustomField>
    <fullName>ID_SAP__c</fullName>
    <externalId>true</externalId>
    <label>ID SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Dan360_UnidadesPorBulto__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadesPorBulto__c</fullName>
    <label>Unidades por bulto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Id_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Dan360_CanalComercial.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acceso</fullName>
    </customValue>
    <customValue>
        <fullName>Disprofarma</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidores</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Farmacias</fullName>
    </customValue>
    <customValue>
        <fullName>Farmacity</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care</fullName>
    </customValue>
    <customValue>
        <fullName>Instituciones</fullName>
    </customValue>
    <customValue>
        <fullName>INTERCO</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Licitaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Modern Trade</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Proximity</fullName>
    </customValue>
    <customValue>
        <fullName>Tender management</fullName>
        <isActive>false</isActive>
        <label>Tender management</label>
    </customValue>
    <customValue>
        <fullName>Pharmacy</fullName>
        <isActive>false</isActive>
        <label>Pharmacy</label>
    </customValue>
    <customValue>
        <fullName>MeLi</fullName>
        <isActive>false</isActive>
        <label>MeLi</label>
    </customValue>
    <customValue>
        <fullName>Health Care</fullName>
        <isActive>false</isActive>
        <label>Health Care</label>
    </customValue>
    <customValue>
        <fullName>Export</fullName>
        <isActive>false</isActive>
        <label>Export</label>
    </customValue>
    <customValue>
        <fullName>Employees</fullName>
        <isActive>false</isActive>
        <label>Employees</label>
    </customValue>
    <masterLabel>Canal comercial</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/ConfirmOrderTradeUnitTest.cls
@isTest
public with sharing class ConfirmOrderTradeUnitTest {
    @TestSetup
    static void makeData(){
        Plantillas__c metadataPlantilla = new Plantillas__c(NuBa_00__c = 'Plantilla BULTOS - NUBA');
        insert metadataPlantilla;

        ApiDanone__c api = new ApiDanone__c(URL__c = 'https://www.danapi.com.ar',User_Key__c = 'c3366a9f16190d9efda328ecec6f6833',UrlClaimExtension__c = '/testing/sales/claim/v1',
        UrlreturnExtension__c = '/testing/sales/return/v1', UrlCreateOrderExtension__c = '/testing/sales/orders/v1', urlMatPrices__c = '/testing/masterdata/price/', User_Key_Price__c='c3366a9f16190d9efda328ecec6f6833');
        insert api;

        RecordType pedidoVentaDirecta = [SELECT id FROM RecordType where sObjectType='Order' and Name = 'Pedido de Venta Directa'];

        String datee = String.valueOf(Date.today().year())+'-'+Date.today().month().format()+'-'+Date.today().day().format();
		
        List<Order> orders = new List<Order>();
		List<OrderItem> orderItems = new List<OrderItem>();
		List<Product2> products = new List<Product2>();

		Id pricebookId = Test.getStandardPricebookId();

		Account account = Build.anAccount()
			.withName('Test Account')
			.withPriceBook(pricebookId)
            .withIdSap('550071632')
			.build();
            account.Dan360_SalesDistric1__c = 'Instituciones';
		insert account;

        Product2 producto1 = Build.aProduct()
            .withName('Producto 106959')
            .withIdSap('106959')
            .withUnidadesBulto(5)
            .withIsActive(true)
            .build();
        insert producto1;

        Product2 producto2 = Build.aProduct()
            .withName('Producto 166578')
            .withIdSap('166578')
            .withUnidadesBulto(10)
            .withIsActive(true)
            .build();
        insert producto2;
         
        Dan360_SalesArea__c salesArea = Build.aSalesArea()
                                                .withName('5771-00-00')
                                                .withDistributionChannel('00')
                                                .withDivision('00')
                                                .withSalesOrganization('5771')
                                                .withIdExterno('5771-00-00')
                                                .build();
        insert salesArea;

        Dan360_PlantillaDeProductos__c plantilla = Build.aPlantillaDeProductos()
                                                        .withName('Plantilla BULTOS - NUBA')
                                                        .withBusinessUnit('5771')
                                                        .build();
        insert plantilla;

        Dan360_Cuota__c cuota = Build.aCuota()
            .withProducto(producto1)
            .withCuota(1)
            .withCuotaActiva('Activa')
            .withVigenciaDesde(Date.today())
            .withVigenciaHasta(Date.today().addDays(2))
            .build();
            cuota.Dan360_CanalComercial__c = 'Instituciones';
        insert cuota;
	}

    @isTest
    public static void ifAOrderHave2ProductsWith1CuotaSplitInto2Orders(){
        Test.setMock(HttpCalloutMock.class, new priceMockCallout());
        String recordTypeVentaDirecta = [SELECT ID FROM RecordType WHERE developerName = 'Dan360_PedidoVentaDirecta'].id;

        Account cuenta = [SELECT id, Name, Id_SAP__c FROM Account LIMIT 1];
        Dan360_SalesArea__c salesArea = [SELECT Name, Dan360_DistributionChannel__c, Dan360_Division__c, Dan360_Id_Externo__c, Dan360_SalesOrganization__c FROM Dan360_SalesArea__c LIMIT 1];
        List<Product2> products = [SELECT Name, Id_SAP__c, ProductCode, Dan360_UnidadesPorBulto__c FROM Product2];

        Dan360_CustomerSalesArea__c customerSalesArea1 = Build.aCustomerSalesArea()
                                                            .withName('550071632-5771-00-00')
                                                            .withClient(cuenta)
                                                            .withUnidadNegocio(salesArea)
                                                            .withIdExterno('550071632-5771-00-00')
                                                            .build();
        Order orderTOInsert = Build.anOrder()
            .withAccount(cuenta)
            .withStatus('Borrador')
            .withRecordType(recordTypeVentaDirecta)
            .withEffectiveDate(Date.today())
            .withPurchaseOrder('')
            .withBusinessUnit('5771')
            .build();
        insert customerSalesArea1;
        insert orderTOInsert;
    
        Test.startTest();
        Test.stopTest();

        Id listaPrecioId = [SELECT Id, Name FROM Pricebook2 WHERE Name = 'Lista 550071632-5771-00-00'].Id;
        List<PricebookEntry> entradaListaPrecios = [SELECT Id, Product2Id,UnitPrice FROM PricebookEntry WHERE Pricebook2Id = :listaPrecioId];
        
        Order pedido = [SELECT OrderNumber,Pricebook2Id,Dan360_CustomerSalesArea__c,Dan360_PlantillaProductos__c FROM Order LIMIT 1];
        pedido.Pricebook2Id = listaPrecioId;
        update pedido;
        List<OrderItem> orderItems = new List<OrderItem>();
        for(PricebookEntry pbe : entradaListaPrecios){
            OrderItem productoPedido = Build.anOrderItem()
                .withOrder(pedido)
                .withProduct2Id(pbe.Product2Id)
                .withUnitPrice(pbe.UnitPrice)
                .withQuantity(2)
                .withPricebookEntryId(pbe)
                .withUnidadMedida('Trade Unit')
                .build();   
            orderItems.add(productoPedido);
        }
        insert orderItems;

        //Empieza el test
        List<OrderItem> orderItems2 = [SELECT id, Product2Id, UnitPrice, Dan360_UnidadMedida__c,OrderId,PricebookEntryId, Quantity FROM OrderItem];
        
        List<List<OrderItem>> orderitemsToPass = new List<List<OrderItem>>();
        orderitemsToPass.add(orderItems2);
       
        List<ConfirmOrderTradeUnit.FlowOutputs> confirmTradeUnit = ConfirmOrderTradeUnit.checkCuotasTradeUnit(orderitemsToPass);
        //simulo el borrado del orderitem creado en el metodo que se corre en el flow de pantalla
        delete confirmTradeUnit[0].orderItem;
        //Termina el test
        Map<String, Order> mapOrderIdOrder = new Map<String, Order>();
        for(Order ordersToTest : [SELECT Id FROM Order]){
            if(!mapOrderIdOrder.containsKey(ordersToTest.Id)){
                mapOrderIdOrder.put(ordersToTest.Id, ordersToTest);
            }
        }
        
        Map<String, List<OrderItem>> mapOrderIdOrderItems = new Map<String, List<OrderItem>>();
        for(OrderItem oderiten : [SELECT id, OrderId, Product2Id FROM OrderItem]){
            if(!mapOrderIdOrderItems.containsKey(oderiten.OrderId)){
                mapOrderIdOrderItems.put(oderiten.OrderId, new List<OrderItem>());
            }
            mapOrderIdOrderItems.get(oderiten.OrderId).add(oderiten);
        }
        Map<Order, List<OrderItem>> mapOrderOrderItems = new Map<Order, List<OrderItem>>();
        for(String orderId : mapOrderIdOrder.keySet()){
            if(mapOrderIdOrderItems.containsKey(orderId)){
                mapOrderOrderItems.put(mapOrderIdOrder.get(orderId),mapOrderIdOrderItems.get(orderId));
            }
        }
        System.assertEquals(mapOrderOrderItems.keySet().size(), 2);
        // System.assertEquals(mapOrderOrderItems.keySet().size(), 1);
        for(Order orderTest : mapOrderOrderItems.keySet()){
            System.assertEquals(mapOrderOrderItems.get(orderTest).size(), 1);
            // System.assertEquals(mapOrderOrderItems.get(orderTest).size(), 2);
        }
    }

    @isTest
    public static void ifAOrderHave2ProductsWith2CuotaUpdateSameOrder(){
        Test.setMock(HttpCalloutMock.class, new priceMockCallout());
        String recordTypeVentaDirecta = [SELECT ID FROM RecordType WHERE developerName = 'Dan360_PedidoVentaDirecta'].id;

        Account cuenta = [SELECT id, Name, Id_SAP__c FROM Account LIMIT 1];
        Dan360_SalesArea__c salesArea = [SELECT Name, Dan360_DistributionChannel__c, Dan360_Division__c, Dan360_Id_Externo__c, Dan360_SalesOrganization__c FROM Dan360_SalesArea__c LIMIT 1];
        List<Product2> products = [SELECT Name, Id_SAP__c, ProductCode, Dan360_UnidadesPorBulto__c FROM Product2];

        Dan360_CustomerSalesArea__c customerSalesArea1 = Build.aCustomerSalesArea()
                                                            .withName('550071632-5771-00-00')
                                                            .withClient(cuenta)
                                                            .withUnidadNegocio(salesArea)
                                                            .withIdExterno('550071632-5771-00-00')
                                                            .build();
        Order orderTOInsert = Build.anOrder()
            .withAccount(cuenta)
            .withStatus('Borrador')
            .withRecordType(recordTypeVentaDirecta)
            .withEffectiveDate(Date.today())
            .withPurchaseOrder('')
            .withBusinessUnit('5771')
            .build();
        insert customerSalesArea1;
        insert orderTOInsert;
    
        Test.startTest();
        Test.stopTest();

        Id listaPrecioId = [SELECT Id, Name FROM Pricebook2 WHERE Name = 'Lista 550071632-5771-00-00'].Id;
        
        PricebookEntry entradaListaPrecios = [SELECT Id, Product2Id,UnitPrice FROM PricebookEntry WHERE Pricebook2Id = :listaPrecioId AND Product2.Name ='Producto 106959'];
        
        Order pedido = [SELECT OrderNumber,Pricebook2Id,Dan360_CustomerSalesArea__c,Dan360_PlantillaProductos__c FROM Order LIMIT 1];
        pedido.Pricebook2Id = listaPrecioId;
        update pedido;
        List<OrderItem> orderItems = new List<OrderItem>();
        

        OrderItem productoPedido = Build.anOrderItem()
            .withOrder(pedido)
            .withProduct2Id(entradaListaPrecios.Product2Id)
            .withUnitPrice(entradaListaPrecios.UnitPrice)
            .withQuantity(2)
            .withPricebookEntryId(entradaListaPrecios)
            .withUnidadMedida('Trade Unit')
            .build();   
        insert productoPedido;

        //Empieza el test
        List<OrderItem> orderItems2 = [SELECT id, Product2Id, UnitPrice, Dan360_UnidadMedida__c,OrderId,PricebookEntryId, Quantity FROM OrderItem];
        System.debug('orderItems2');
        System.debug(orderItems2);
        List<List<OrderItem>> orderitemsToPass = new List<List<OrderItem>>();
        orderitemsToPass.add(orderItems2);
        System.debug('orderitemsToPass');
        System.debug(orderitemsToPass);
        List<ConfirmOrderTradeUnit.FlowOutputs> confirmTradeUnit = ConfirmOrderTradeUnit.checkCuotasTradeUnit(orderitemsToPass);
        System.debug(confirmTradeUnit);
        //simulo el borrado del orderitem creado en el metodo que se corre en el flow de pantalla
        delete confirmTradeUnit[0].orderItem;
        //Termina el test
        Order pedido2 = [SELECT OrderNumber,Pricebook2Id,Dan360_CustomerSalesArea__c,Dan360_PlantillaProductos__c, Status FROM Order LIMIT 1];
        System.debug('pedido2');
        System.debug(pedido2);
        System.assertEquals(confirmTradeUnit[0].updateSameOrder, true);
        // System.assertEquals(confirmTradeUnit[0].updateSameOrder, false);
    }
}