force-app/main/default/objects/Account/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Canal de Distribución</description>
    <label>Distribution Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_SalesDistric1__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesDistric1__c</fullName>
    <label>Sales District</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acceso</fullName>
            </value>
            <value>
                <fullName>Disprofarma</fullName>
            </value>
            <value>
                <fullName>Distribuidores</fullName>
            </value>
            <value>
                <fullName>DistribuidoresLicitaciones</fullName>
                <isActive>false</isActive>
                <label>DistribuidoresLicitaciones</label>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>Farmacias</fullName>
            </value>
            <value>
                <fullName>Farmacity</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Instituciones</fullName>
            </value>
            <value>
                <fullName>INTERCO</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Licitaciones</fullName>
            </value>
            <value>
                <fullName>LicitacionesDistribuidores</fullName>
                <isActive>false</isActive>
                <label>LicitacionesDistribuidores</label>
            </value>
            <value>
                <fullName>LicitacionesDistribuidoresLicitacionesDistribuidores</fullName>
                <isActive>false</isActive>
                <label>LicitacionesDistribuidoresLicitacionesDistribuidores</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Modern Trade</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Proximity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_SalesDistrictColaborationRule__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesDistrictColaborationRule__c</fullName>
    <description>Campo que sera utilizado para las reglas de colaboración</description>
    <label>Sales District Colaboration Rule</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Campo donde se especifica la organización de ventas perteneciente.</description>
    <label>Sales organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Id_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id SAP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ApiDanone__c/ApiDanone__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuración para guardar datos de conexión a la api danone</description>
    <label>Api Danone</label>
</CustomObject>

force-app/main/default/objects/ApiDanone__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>endpoint</description>
    <label>URL</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlClaimExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlClaimExtension__c</fullName>
    <description>Extension para enviar reclamos de tipo Manejo de dinero. Ej: Diferencia de precios</description>
    <label>UrlClaimExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlCreateOrderExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlCreateOrderExtension__c</fullName>
    <description>Extension usada para enviar ordenes</description>
    <label>UrlCreateOrderExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/urlMatPrices__c.field-meta.xml
<CustomField>
    <fullName>urlMatPrices__c</fullName>
    <description>Url test para pedir precios de materiales para un cliente.</description>
    <label>urlMatPrices</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/UrlreturnExtension__c.field-meta.xml
<CustomField>
    <fullName>UrlreturnExtension__c</fullName>
    <description>Extension usada para enviar reclamos del tipo Manejo de inventario. Ej : Devoluciones</description>
    <label>UrlreturnExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/User_Key__c.field-meta.xml
<CustomField>
    <fullName>User_Key__c</fullName>
    <label>User Key</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ApiDanone__c/fields/User_Key_Price__c.field-meta.xml
<CustomField>
    <fullName>User_Key_Price__c</fullName>
    <description>Key used for price callout</description>
    <label>User Key Price</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/Dan360_CustomerSalesArea__c.object-meta.xml
<CustomObject>
    <description>Customer Sales Area</description>
    <label>Customer Sales Area</label>
    <nameField>
        <label>Nombre de Customer Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Sales Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/fields/Dan360_District__c.field-meta.xml
<CustomField>
    <fullName>Dan360_District__c</fullName>
    <label>Distrito</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
            </value>
            <value>
                <fullName>AR3MTR</fullName>
            </value>
            <value>
                <fullName>AR3INS</fullName>
            </value>
            <value>
                <fullName>AR3DIS</fullName>
            </value>
            <value>
                <fullName>AR3ACC</fullName>
            </value>
            <value>
                <fullName>AR3MAR</fullName>
            </value>
            <value>
                <fullName>AR3FAR</fullName>
            </value>
            <value>
                <fullName>AR3RES</fullName>
            </value>
            <value>
                <fullName>AR3TEN</fullName>
            </value>
            <value>
                <fullName>AR3PRO</fullName>
            </value>
            <value>
                <fullName>AR3PHA</fullName>
            </value>
            <value>
                <fullName>AR3INT</fullName>
            </value>
            <value>
                <fullName>AR3HOM</fullName>
            </value>
            <value>
                <fullName>AR3DPF</fullName>
            </value>
            <value>
                <fullName>#</fullName>
            </value>
            <value>
                <fullName>AR3ECO</fullName>
            </value>
            <value>
                <fullName>AR3OTH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_CustomerSalesArea__c/fields/Dan360_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesArea__c</fullName>
    <description>Unidad de negocio que se asocia al cliente.</description>
    <label>Unidad de negocio</label>
    <referenceTo>Dan360_SalesArea__c</referenceTo>
    <relationshipLabel>Customer Sales Area</relationshipLabel>
    <relationshipName>Customer_Sales_Area</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_PlantillaDeProductos__c/Dan360_PlantillaDeProductos__c.object-meta.xml
<CustomObject>
    <description>Objetos en donde se almacenarán las plantillas de los productos.</description>
    <label>Plantilla de Productos</label>
    <nameField>
        <label>Plantilla</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantillas de Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_PlantillaDeProductos__c/fields/Dan360_UnidadNegocio__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadNegocio__c</fullName>
    <description>Se refiere al negocio donde se generará una transacción, en donde impactará la venta de un producto.</description>
    <label>Unidad de Negocio</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_UnidadDeNegocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/dAN360_PlantillaporcCuenta__c/dAN360_PlantillaporcCuenta__c.object-meta.xml
<CustomObject>
    <description>Objeto Join que relacionará la cuenta con las plantillas de producto.</description>
    <label>Plantilla por cuenta</label>
    <nameField>
        <displayFormat>PlaXCta-{0000}</displayFormat>
        <label>Nombre de Plantilla por cuenta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plantillas por cuenta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/dAN360_PlantillaporcCuenta__c/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <label>Distribution channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <default>true</default>
                <label>00</label>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/dAN360_PlantillaporcCuenta__c/fields/Dan360_PlantillaDeProductos__c.field-meta.xml
<CustomField>
    <fullName>Dan360_PlantillaDeProductos__c</fullName>
    <description>Plantilla creada para el cliente, en donde están registrados los productos que puede adquirir.</description>
    <label>Plantilla de Productos</label>
    <referenceTo>Dan360_PlantillaDeProductos__c</referenceTo>
    <relationshipLabel>Plantillas por cuenta</relationshipLabel>
    <relationshipName>Plantillas_por_cuenta</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/dAN360_PlantillaporcCuenta__c/fields/Dan360_UnidadNegocio__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadNegocio__c</fullName>
    <description>Se refiere al negocio donde se generará una transacción, en donde impactará la venta de un producto.</description>
    <label>Unidad de negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_UnidadDeNegocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/Dan360_SalesArea__c.object-meta.xml
<CustomObject>
    <description>Sales Area</description>
    <label>Sales Area</label>
    <nameField>
        <label>Nombre de Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <description>Distribution channel</description>
    <label>Distribution channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_Division__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Division__c</fullName>
    <description>División</description>
    <label>División</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Sales Organization</description>
    <label>Sales Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plantillas__c/Plantillas__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Plantillas</label>
</CustomObject>

force-app/main/default/objects/Plantillas__c/fields/AMN_00__c.field-meta.xml
<CustomField>
    <fullName>AMN_00__c</fullName>
    <label>AMN Canal 00</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plantillas__c/fields/AMN_05__c.field-meta.xml
<CustomField>
    <fullName>AMN_05__c</fullName>
    <label>AMN Canal 05</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plantillas__c/fields/NuBa_00__c.field-meta.xml
<CustomField>
    <fullName>NuBa_00__c</fullName>
    <label>NuBa Canal 00</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plantillas__c/fields/NuBa_05__c.field-meta.xml
<CustomField>
    <fullName>NuBa_05__c</fullName>
    <label>NuBa Canal 05</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Dan360_UnidadDeNegocio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5800</fullName>
        <label>AMN</label>
    </customValue>
    <customValue>
        <fullName>5771</fullName>
        <label>NuBa</label>
    </customValue>
    <description>Determina a qué unidad de negocio se genera un pedido.</description>
    <masterLabel>Unidad de Negocio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AssingSalesdistrictInAccountHandlerTest.cls
@isTest
public with sharing class AssingSalesdistrictInAccountHandlerTest {
    static XHttpCalloutMock getPriceResponse;
    static string datee;

    static{
        insert new ApiDanone__c(URL__c = 'https://www.danapi.com.ar',User_Key__c = 'c3366a9f16190d9efda328ecec6f6833',User_Key_Price__c = 'c3366a9f16190d9efda328ecec6f6833',UrlClaimExtension__c = '/testing/sales/claim/v1',
        UrlreturnExtension__c = '/testing/sales/return/v1', UrlCreateOrderExtension__c = '/testing/sales/orders/v1', urlMatPrices__c = '/testing/masterdata/price/	');
        Id pricebookId = Test.getStandardPricebookId();

        Account anAccount = Build.anAccount()
            .withName('Test')
            .withPriceBook(pricebookId)
            .withIdSap('567832')
            .build();
        insert anAccount; 
        Account anAccountTwo = Build.anAccount()
            .withName('Test Two')
            .withPriceBook(pricebookId)
            .withIdSap('567777')
            .build();
        insert anAccountTwo; 
        Dan360_PlantillaDeProductos__c templateProducts = Build.aPlantillaDeProductos()
            .withName('AMN Canal 00')
            .withBusinessUnit('5800')
            .build();
        insert templateProducts;

        Dan360_PlantillaDeProductos__c templateProductsNuBa = Build.aPlantillaDeProductos()
            .withName('NuBa Canal 00')
            .withBusinessUnit('5771')
            .build();
        insert templateProductsNuBa;        
        Dan360_PlantillaDeProductos__c templateProductsAMNSinCargo = Build.aPlantillaDeProductos()
            .withName('AMN Canal 05')
            .withBusinessUnit('5800')
            .build();
        insert templateProductsAMNSinCargo;        
        Dan360_PlantillaDeProductos__c templateProductsNuBaSinCargo = Build.aPlantillaDeProductos()
            .withName('NuBa Canal 05')
            .withBusinessUnit('5771')
            .build();
        insert templateProductsNuBaSinCargo;        

        insert new Plantillas__c(AMN_00__c = 'AMN Canal 00', NuBa_00__c = 'NuBa Canal 00', AMN_05__c = 'AMN Canal 05', NuBa_05__c = 'NuBa Canal 05');
        
        dAN360_PlantillaporcCuenta__c templatePerAccount = Build.aPlantillaPorCuenta()
            .withAccount(anAccount)
            .withPlantillaDeProductos(templateProducts)
            .build();
            templatePerAccount.Dan360_UnidadNegocio__c = '5800';
            templatePerAccount.Dan360_DistributionChannel__c = '00';
        insert templatePerAccount;
        Dan360_SalesArea__c salesAreaVentaEstandar = Build.aSalesArea()
            .withName('AMN-01-01')
            .withIdExterno('5800-01-01')
            .withDistributionChannel('00')
            .withDivision('01')
            .withSalesOrganization('5800')
            .build();
        insert salesAreaVentaEstandar;
        Dan360_SalesArea__c salesAreaSinCargo = Build.aSalesArea()
            .withName('NUBA-01-01')
            .withIdExterno('5771-01-01')
            .withDistributionChannel('05')
            .withDivision('01')
            .withSalesOrganization('5771')
            .build();
        insert salesAreaSinCargo;

        datee = String.valueOf(Date.today().year())+'-'+Date.today().month().format()+'-'+Date.today().day().format();
        getPriceResponse = new XHttpCalloutMock();
        getPriceResponse.buildResponse()
            .withStatus('OK')
            .withStatusCode(200)
            .withBody(SapPricesMock.getSucess())
            .addForAddress(WebServiceSap.SERVICE_CONFIG.URL__c + WebServiceSap.SERVICE_CONFIG.urlMatPrices__c + 'sn?date='+datee+'&organizationId='+salesAreaVentaEstandar.Dan360_SalesOrganization__c+'&channelId='+salesAreaVentaEstandar.Dan360_DistributionChannel__c+'&divisionId='+salesAreaVentaEstandar.Dan360_Division__c+'&customer='+account.Id_SAP__c);
    
    }
    @isTest
    private static void whenInsertCustomerSalesAreMustAssingSalesDistrictAndDistributionChannelInAccount() {
        // Test data setup
        Test.setMock(HttpCalloutMock.class, getPriceResponse);
        Dan360_SalesArea__c salesAreaVentaEstandar = [
            SELECT Id, Dan360_DistributionChannel__c
            FROM Dan360_SalesArea__c
            WHERE Dan360_DistributionChannel__c = '00'
        ];
        Account account = [
            SELECT Id, Dan360_DistributionChannel__c,Dan360_SalesDistric1__c,Dan360_SalesDistrictColaborationRule__c
            FROM Account
            WHERE Name = 'Test'
        ];

        Dan360_CustomerSalesArea__c customerSalesArea = Build.aCustomerSalesArea()
            .withName('AMN 00')
            .withClient(account)
            .withUnidadNegocio(salesAreaVentaEstandar)
            .withIdExterno('5678-5800-01-01')
            .build();
        customerSalesArea.Dan360_District__c = 'AR3INS';
              
        // Actual test
        Test.startTest();
            insert customerSalesArea;
        Test.stopTest();

        Account accountToCompare = [
            SELECT Id, Dan360_DistributionChannel__c,Dan360_SalesDistric1__c,Dan360_SalesDistrictColaborationRule__c
            FROM Account
            WHERE Name = 'Test'
        ];
    
        // Asserts
        System.assertEquals('Venta Estándar', accountToCompare.Dan360_DistributionChannel__c, 'Error al asignar distribution channel');
        System.assertEquals('Instituciones', accountToCompare.Dan360_SalesDistric1__c, 'Error al asignar sales district');
        System.assertEquals(accountToCompare.Dan360_SalesDistric1__c, accountToCompare.Dan360_SalesDistrictColaborationRule__c, 'Error al asignar sales district colaboration rule');
        System.assertNotEquals(null, accountToCompare.Dan360_DistributionChannel__c, 'Error al asignar distribution channel');
        System.assertNotEquals(null, accountToCompare.Dan360_SalesDistric1__c, 'Error al asignar sales district');
        System.assertNotEquals(null, accountToCompare.Dan360_SalesDistrictColaborationRule__c, 'Error al asignar sales district colaboration rule');
    }
    @isTest
    private static void whenInsertTwoCustomerSalesAreaForTheSameAccountMustConcatenateTheDifferentValues() {
        Test.setMock(HttpCalloutMock.class, getPriceResponse);
        // Test data setup
        Dan360_SalesArea__c salesAreaVentaEstandar = [
            SELECT Id, Dan360_DistributionChannel__c
            FROM Dan360_SalesArea__c
            WHERE Dan360_DistributionChannel__c = '00'
        ];
        Dan360_SalesArea__c salesAreaSinCargo = [
            SELECT Id, Dan360_DistributionChannel__c
            FROM Dan360_SalesArea__c
            WHERE Dan360_DistributionChannel__c = '05'
        ];
        Account account = [
            SELECT Id, Dan360_DistributionChannel__c,Dan360_SalesDistric1__c,Dan360_SalesDistrictColaborationRule__c
            FROM Account
            WHERE Name = 'Test'
        ];

        account.Dan360_DistributionChannel__c = 'Sin Cargo';
        account.Dan360_SalesDistric1__c = 'E-commerce';

        update account;
        List<Dan360_CustomerSalesArea__c> csaList = new List<Dan360_CustomerSalesArea__c>();
        Dan360_CustomerSalesArea__c customerSalesArea = Build.aCustomerSalesArea()
            .withName('AMN 00')
            .withClient(account)
            .withUnidadNegocio(salesAreaVentaEstandar)
            .withIdExterno('5678-5800-01-01')
            .build();
        customerSalesArea.Dan360_District__c = 'AR3INS';
        csaList.add(customerSalesArea);
        Dan360_CustomerSalesArea__c customerSalesAreaTwo = Build.aCustomerSalesArea()
            .withName('Nuba 00')
            .withClient(account)
            .withUnidadNegocio(salesAreaSinCargo)
            .withIdExterno('5667-5771-01-01')
            .build();
        customerSalesAreaTwo.Dan360_District__c = 'AR3INS';
        csaList.add(customerSalesAreaTwo);
        // Actual test
        Test.startTest();
            insert csaList;
        Test.stopTest();

        Account accountToCompare = [
            SELECT Id, Dan360_DistributionChannel__c,Dan360_SalesDistric1__c,Dan360_SalesDistrictColaborationRule__c
            FROM Account
            WHERE Name = 'Test'
        ];
    
        // Asserts
        System.assertEquals('Sin Cargo; Venta Estándar', accountToCompare.Dan360_DistributionChannel__c, 'Error al asignar distribution channel');
        System.assertNotEquals(null, accountToCompare.Dan360_SalesDistric1__c, 'Error al asignar sales district');
        System.assertNotEquals(null, accountToCompare.Dan360_SalesDistrictColaborationRule__c, 'Error al asignar sales district colaboration rule');
    }
    @isTest
    private static void whenInsertCustomerSalesAreaForDifferentAccountMustConcatenateTheDifferentValuesToTheRelatedAccount() {
        Test.setMock(HttpCalloutMock.class, getPriceResponse);
        // Test data setup
        Dan360_SalesArea__c salesAreaVentaEstandar = [
            SELECT Id, Dan360_DistributionChannel__c
            FROM Dan360_SalesArea__c
            WHERE Dan360_DistributionChannel__c = '00'
        ];
        Dan360_SalesArea__c salesAreaSinCargo = [
            SELECT Id, Dan360_DistributionChannel__c
            FROM Dan360_SalesArea__c
            WHERE Dan360_DistributionChannel__c = '05'
        ];
        Account account = [
            SELECT Id, Dan360_DistributionChannel__c,Dan360_SalesDistric1__c,Dan360_SalesDistrictColaborationRule__c
            FROM Account
            WHERE Name = 'Test'
        ];
        account.Dan360_DistributionChannel__c = 'Sin Cargo';
        account.Dan360_SalesDistric1__c = 'E-commerce';

        update account;
        Account accountTwo = [
            SELECT Id, Dan360_DistributionChannel__c,Dan360_SalesDistric1__c,Dan360_SalesDistrictColaborationRule__c
            FROM Account
            WHERE Name = 'Test Two'
        ];

        accountTwo.Dan360_SalesDistric1__c = 'E-commerce;Instituciones';
        update accountTwo;

        List<Dan360_CustomerSalesArea__c> csaList = new List<Dan360_CustomerSalesArea__c>();
        Dan360_CustomerSalesArea__c customerSalesArea = Build.aCustomerSalesArea()
            .withName('AMN 00')
            .withClient(account)
            .withUnidadNegocio(salesAreaVentaEstandar)
            .withIdExterno('5678-5800-01-01')
            .build();
        customerSalesArea.Dan360_District__c = 'AR3INS';
        csaList.add(customerSalesArea);
        Dan360_CustomerSalesArea__c customerSalesAreaTwo = Build.aCustomerSalesArea()
            .withName('Nuba 00')
            .withClient(account)
            .withUnidadNegocio(salesAreaSinCargo)
            .withIdExterno('5678-5771-01-01')
            .build();
        customerSalesAreaTwo.Dan360_District__c = 'AR3INS';
        csaList.add(customerSalesAreaTwo);
        Dan360_CustomerSalesArea__c customerSalesAreaThree = Build.aCustomerSalesArea()
            .withName('AMN 00')
            .withClient(accountTwo)
            .withUnidadNegocio(salesAreaVentaEstandar)
            .withIdExterno('5688-5771-01-01')
            .build();
        customerSalesAreaThree.Dan360_District__c = 'AR3TEN';
        csaList.add(customerSalesAreaThree);
        // Actual test
        Test.startTest();
            insert csaList;
        Test.stopTest();

        Account accountToCompare = [
            SELECT Id, Dan360_DistributionChannel__c,Dan360_SalesDistric1__c,Dan360_SalesDistrictColaborationRule__c
            FROM Account
            WHERE Name = 'Test'
        ];
        Account accountToCompareTwo = [
            SELECT Id, Dan360_DistributionChannel__c,Dan360_SalesDistric1__c,Dan360_SalesDistrictColaborationRule__c
            FROM Account
            WHERE Name = 'Test Two'
        ];
        
        // Asserts
        System.assertEquals('Sin Cargo; Venta Estándar', accountToCompare.Dan360_DistributionChannel__c, 'Error al asignar distribution channel');
        System.assertNotEquals(null, accountToCompare.Dan360_SalesDistric1__c, 'Error al asignar sales district');
        System.assertNotEquals(null, accountToCompare.Dan360_SalesDistrictColaborationRule__c, 'Error al asignar sales district colaboration rule');

        System.assertEquals('Venta Estándar', accountToCompareTwo.Dan360_DistributionChannel__c, 'Error al asignar distribution channel');
        System.assertNotEquals(null, accountToCompareTwo.Dan360_SalesDistric1__c, 'Error al asignar sales district');
        System.assertNotEquals(null, accountToCompareTwo.Dan360_SalesDistrictColaborationRule__c, 'Error al asignar sales district colaboration rule');
    }
}