force-app/main/default/objects/Account/fields/Dan360_CanalComercial__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CanalComercial__c</fullName>
    <description>Canal comercial de la cuenta</description>
    <label>Canal Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_CanalComercial</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dan360_SalesDistric1__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesDistric1__c</fullName>
    <label>Sales District</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acceso</fullName>
            </value>
            <value>
                <fullName>Disprofarma</fullName>
            </value>
            <value>
                <fullName>Distribuidores</fullName>
            </value>
            <value>
                <fullName>DistribuidoresLicitaciones</fullName>
                <isActive>false</isActive>
                <label>DistribuidoresLicitaciones</label>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>Farmacias</fullName>
            </value>
            <value>
                <fullName>Farmacity</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Instituciones</fullName>
            </value>
            <value>
                <fullName>INTERCO</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Licitaciones</fullName>
            </value>
            <value>
                <fullName>LicitacionesDistribuidores</fullName>
                <isActive>false</isActive>
                <label>LicitacionesDistribuidores</label>
            </value>
            <value>
                <fullName>LicitacionesDistribuidoresLicitacionesDistribuidores</fullName>
                <isActive>false</isActive>
                <label>LicitacionesDistribuidoresLicitacionesDistribuidores</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Modern Trade</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Proximity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/Dan360_Cuota__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacenará las cuotas que se aplicán a los pedidos, para controlar las cantidades de producto que se pueden procesar en cada pedido y las cantidades que quedarán &quot;Retenidas por cuota&quot;.</description>
    <label>Cuota</label>
    <nameField>
        <displayFormat>Cuo-{0000}</displayFormat>
        <label>Nombre de Cuota</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_CanalComercial__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CanalComercial__c</fullName>
    <description>Canal comercial para el que aplicará la cuota.</description>
    <label>Canal Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_CanalComercial</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_Cuota__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Cuota__c</fullName>
    <description>Cuota asignada al producto.</description>
    <label>Cuota</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_EstadoCuota__c.field-meta.xml
<CustomField>
    <fullName>Dan360_EstadoCuota__c</fullName>
    <description>Indica el estado en el que se encuentra una cuota.</description>
    <label>Estado de cuota</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activa</fullName>
            </value>
            <value>
                <fullName>Inactiva</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_Producto__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Producto para el cual aplicará la cuota.</description>
    <label>Producto</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cuotas</relationshipLabel>
    <relationshipName>Cuotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_Saldo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Saldo__c</fullName>
    <description>Saldo que va quedando para la cuota cada vez que aplica para un pedido.</description>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_VigenciaDesde__c.field-meta.xml
<CustomField>
    <fullName>Dan360_VigenciaDesde__c</fullName>
    <description>Campo que indica el momento desde el cual una cuota empieza a ser vigente.</description>
    <label>Vigencia desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Cuota__c/fields/Dan360_VigenciaHasta__c.field-meta.xml
<CustomField>
    <fullName>Dan360_VigenciaHasta__c</fullName>
    <description>Fecha que indica el momento en que una cuota deja de ser vigente.</description>
    <label>Vigencia hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Id_Externo__c</fullName>
    <description>Id Externo de la órdenes. Se diligenciará a través de una automatización para replicar el número de la orden de Salesforce.</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_PedidoPrincipal__c.field-meta.xml
<CustomField>
    <fullName>Dan360_PedidoPrincipal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pedido principal para pedidos desdoblados por deborde.</description>
    <label>Pedido Principal</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pedidos Retenidos por cuota</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_SemaforoPicklist__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SemaforoPicklist__c</fullName>
    <description>Señala el color del semáforo (Verde, amarillo o rojo) dependiendo de la cuota disponible para el pedido.</description>
    <label>SemaforoPicklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rojo</fullName>
            </value>
            <value>
                <fullName>Amarillo</fullName>
            </value>
            <value>
                <fullName>Verde</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Dan360_UnidadMedida__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadMedida__c</fullName>
    <label>Unidad de medida</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Dan360_UnidadesPorBulto__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadesPorBulto__c</fullName>
    <label>Unidades por bulto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Dan360_CanalComercial.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acceso</fullName>
    </customValue>
    <customValue>
        <fullName>Disprofarma</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidores</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Farmacias</fullName>
    </customValue>
    <customValue>
        <fullName>Farmacity</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care</fullName>
    </customValue>
    <customValue>
        <fullName>Instituciones</fullName>
    </customValue>
    <customValue>
        <fullName>INTERCO</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Licitaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Modern Trade</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Proximity</fullName>
    </customValue>
    <customValue>
        <fullName>Tender management</fullName>
        <isActive>false</isActive>
        <label>Tender management</label>
    </customValue>
    <customValue>
        <fullName>Pharmacy</fullName>
        <isActive>false</isActive>
        <label>Pharmacy</label>
    </customValue>
    <customValue>
        <fullName>MeLi</fullName>
        <isActive>false</isActive>
        <label>MeLi</label>
    </customValue>
    <customValue>
        <fullName>Health Care</fullName>
        <isActive>false</isActive>
        <label>Health Care</label>
    </customValue>
    <customValue>
        <fullName>Export</fullName>
        <isActive>false</isActive>
        <label>Export</label>
    </customValue>
    <customValue>
        <fullName>Employees</fullName>
        <isActive>false</isActive>
        <label>Employees</label>
    </customValue>
    <masterLabel>Canal comercial</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/ConfirmOrderTradeUnit.cls
public with sharing class ConfirmOrderTradeUnit {
    
    @InvocableMethod(label='Check Cuotas in Trade Unit products' description='Check if Cuotas are enough')
    public static List<FlowOutputs> checkCuotasTradeUnit(List<List<OrderItem>> orderItems) {
        String orderId;
        String newOrderNumber = '';
        Boolean updateSameOrder = false;
        List<OrderItem> orderItemToCreate = new List<OrderItem>();
        List<String> productsWithTradeUnit = new List<String>();
        Map<String, Decimal> mapProductBulto = new Map<String, Decimal>();
        Map<String, Decimal> mapProductCuota = new Map<String, Decimal>();
        for(OrderItem orderIten : orderItems[0]){
            if(orderIten.Dan360_UnidadMedida__c == 'Trade Unit'){
                productsWithTradeUnit.add(orderIten.Product2Id);
                orderId = orderIten.OrderId;
            }
        }
        System.debug('productsWithTradeUnit');
        System.debug(productsWithTradeUnit);
        
        if(productsWithTradeUnit.size()> 0){
            String idAccount = [SELECT Id, AccountId FROM Order Where Id = :orderId].AccountId;
            List<Account> getAccountdetails = [SELECT Id, Dan360_SalesDistric1__c FROM Account WHERE Id = :idAccount];

            for(Product2 product : [SELECT id, Dan360_UnidadesPorBulto__c FROM Product2 WHERE Id IN :productsWithTradeUnit]){
                if(!mapProductBulto.containsKey(product.Id)){
                    mapProductBulto.put(product.Id, product.Dan360_UnidadesPorBulto__c);
                }
            }

            
            Date fechaActual = System.today();
            List<String> accountSalesDistricts = String.valueOf(getAccountdetails[0].Dan360_SalesDistric1__c).split(';');
            
            // System.debug('Contenido  > productsWithTradeUnit: ' + JSON.serialize(productsWithTradeUnit) );
            // System.debug('Contenido  > accountSalesDistricts: ' + JSON.serialize(accountSalesDistricts) );


            for(Dan360_Cuota__c cuota : [SELECT Id, Dan360_Producto__c, Dan360_Saldo__c FROM Dan360_Cuota__c 
            WHERE Dan360_Producto__c IN :productsWithTradeUnit 
            AND Dan360_EstadoCuota__c = 'Activa'
            AND Dan360_VigenciaDesde__c < = :fechaActual
            AND Dan360_VigenciaHasta__c > = :fechaActual
            AND Dan360_CanalComercial__c IN :accountSalesDistricts  
            ]){
                System.debug('cuota');
                System.debug('Banderilla cuotas >> '+ JSON.serialize(cuota));
                if(!mapProductCuota.containsKey(cuota.Dan360_Producto__c)){
                    mapProductCuota.put(cuota.Dan360_Producto__c, cuota.Dan360_Saldo__c);
                }
            }

            List<String> productsToCreateOrder = new List<String>();

            for(String product : mapProductBulto.keySet()){
                if(mapProductCuota.containsKey(product)){
                    if(mapProductBulto.get(product) > mapProductCuota.get(product)){
                        productsToCreateOrder.add(product);
                    }
                }
            }
            
            for(OrderItem orderIten : orderItems[0]){
                if(productsToCreateOrder.contains(orderIten.Product2Id)){
                    orderItemToCreate.add(orderIten);
                }
            }

            System.debug('orderItemToCreate');
            System.debug(orderItemToCreate);
            System.debug('orderItems[0]');
            System.debug(orderItems[0]);
            if(orderItemToCreate.size()>0){
                if(orderItemToCreate.size() != orderItems[0].size()){
                    String queryFields = DuplicateOrderExtension.getAllApiNameFields('Order');
                    String query = 'select '+queryFields+' from Order where Id=\''+orderId+'\'';
                    Order orderToClone = Database.query(query);
                    
                    Order clonedOrder = orderToClone.clone(false, true, false, false);
                    clonedOrder.Dan360_PedidoPrincipal__c = orderToClone.Id;
                    clonedOrder.Status = 'Retenido por cuota';
                    clonedOrder.Dan360_SemaforoPicklist__c = 'Rojo';
                    clonedOrder.Dan360_Id_Externo__c = null;
                    Database.insert(clonedOrder);

                    List<OrderItem> listOrderItemInsert = new List<OrderItem>();
                    for(OrderItem orderItemToClone : orderItemToCreate){
                        OrderItem orderItemCloned = orderItemToClone.clone(false, true, false, false);
                        /* if(Test.isRunningTest()){
                            OrderItem orderItemTest = [SELECT PricebookEntryId FROM OrderItem WHERE Id = :orderItemToClone.Id];
                            orderItemCloned.PricebookEntryId = orderItemTest.PricebookEntryId;
                        } */
                        //orderItemToClone.clone(false,true);
                        orderItemCloned.OrderId = clonedOrder.id;
                        System.debug('orderItemCloned.PricebookEntryId');
                        System.debug(orderItemCloned);
                        listOrderItemInsert.add(orderItemCloned);
                        //Database.insert(orderItemCloned);
                    }
                    insert listOrderItemInsert;
                    newOrderNumber = [SELECT Id, OrderNumber FROM Order WHERE Id = :clonedOrder.Id].OrderNumber;
                    System.debug('newOrder.OrderNumber');
                    System.debug(newOrderNumber);
                } else {
                    updateSameOrder = true;
                }
            }
            System.debug('orderItemToCreate');
            System.debug(orderItemToCreate);
        }
        
        
        List<FlowOutputs> outputList = new List<FlowOutputs>();
        FlowOutputs output = new FlowOutputs();
        output.orderItem = orderItemToCreate;
        output.orderId = newOrderNumber;
        output.updateSameOrder = updateSameOrder;
        outputList.add(output);
        return outputList;
    }

    public class FlowOutputs {       
        @InvocableVariable
        public List<OrderItem> orderItem;
        @InvocableVariable
        public String orderId;
        @InvocableVariable
        public Boolean updateSameOrder;
    }
}