force-app/main/default/objects/Account/fields/Enfermero_Asignado__c.field-meta.xml
<CustomField>
    <fullName>Enfermero_Asignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enfermero Asignado</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Title</field>
            <operation>contains</operation>
            <value>Enferme</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Enfermero</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Kinesiologo_asignado__c.field-meta.xml
<CustomField>
    <fullName>Kinesiologo_asignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kinesiologo Asignado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Title</field>
            <operation>contains</operation>
            <value>Kinesi</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>KinesiologosAsignados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Medico_Asignado__c.field-meta.xml
<CustomField>
    <fullName>Medico_Asignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medico Asignado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Medico_Asignado</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nutricionista_Asignado__c.field-meta.xml
<CustomField>
    <fullName>Nutricionista_Asignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nutricionista Asignado</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Title</field>
            <operation>contains</operation>
            <value>Nutri</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Nutricionista</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Obra_social__c.field-meta.xml
<CustomField>
    <fullName>Obra_social__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Obra social</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Obra social</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuenta</relationshipLabel>
    <relationshipName>Cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Paciente__c.field-meta.xml
<CustomField>
    <fullName>Paciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paciente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contactos</relationshipLabel>
    <relationshipName>Contactos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/Modulo_de_paciente__c.object-meta.xml
<CustomObject>
    <label>Modulo de paciente</label>
    <nameField>
        <displayFormat>MDP-{0000}</displayFormat>
        <label>Nro de Modulo de paciente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modulos de paciente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>El módulo solo es válido para pacientes Best Care</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Best Care</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Modulos de paciente (Solo Best Care)</relationshipLabel>
    <relationshipName>Modulos_de_paciente</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Renovacion__c.field-meta.xml
<CustomField>
    <fullName>Renovacion__c</fullName>
    <label>Renovación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Renovacion</fullName>
            </value>
            <value>
                <fullName>alta</fullName>
                <label>Alta</label>
            </value>
            <value>
                <fullName>Recupero</fullName>
            </value>
            <value>
                <fullName>Sí</fullName>
                <isActive>false</isActive>
                <label>Sí</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Servicios_del_Modulo__c/Servicios_del_Modulo__c.object-meta.xml
<CustomObject>
    <label>Servicios del Modulo</label>
    <nameField>
        <displayFormat>SDM-{00000}</displayFormat>
        <label>Nombre de Servicios del Modulo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Servicios del Modulo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Servicios_del_Modulo__c/fields/Modulo_de_paciente__c.field-meta.xml
<CustomField>
    <fullName>Modulo_de_paciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modulo de paciente</label>
    <referenceTo>Modulo_de_paciente__c</referenceTo>
    <relationshipLabel>Servicios del Modulo</relationshipLabel>
    <relationshipName>Servicios_del_Modulo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servicios_del_Modulo__c/fields/Servicios_disponibles__c.field-meta.xml
<CustomField>
    <fullName>Servicios_disponibles__c</fullName>
    <label>Servicios</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Servicio visita enfermería</fullName>
            </value>
            <value>
                <fullName>Servicio visita nutricional</fullName>
            </value>
            <value>
                <fullName>Servicio visita medica</fullName>
            </value>
            <value>
                <fullName>Servicio visita especialista en deglución</fullName>
            </value>
            <value>
                <fullName>Rehabilitación_Motora_Plus</fullName>
                <label>Rehabilitación Motora Plus</label>
            </value>
            <value>
                <fullName>Servicio de visita cuidado nutricional completo</fullName>
            </value>
            <value>
                <fullName>Rehabilitacion_Motora_Intermedio</fullName>
                <label>Rehabilitacion Motora - Intermedio</label>
            </value>
            <value>
                <fullName>Rehabilitacion_Motora_basico_Oral</fullName>
                <label>Rehabilitación Motora básico Oral</label>
            </value>
            <value>
                <fullName>Rehabilitacion_Motora_Basico_Enteral</fullName>
                <label>Rehabilitación Motora Básico Enteral</label>
            </value>
            <value>
                <fullName>CUIDADO BÁSICO</fullName>
            </value>
            <value>
                <fullName>Autocuidado</fullName>
                <isActive>false</isActive>
                <label>Autocuidado</label>
            </value>
            <value>
                <fullName>Cuidado_completo</fullName>
                <isActive>false</isActive>
                <label>Cuidado completo</label>
            </value>
            <value>
                <fullName>Ninguno</fullName>
                <isActive>false</isActive>
                <label>Ninguno</label>
            </value>
            <value>
                <fullName>Rehabilitacion_Motora_Basico</fullName>
                <isActive>false</isActive>
                <label>Rehabilitacion_Motora_Basico</label>
            </value>
            <value>
                <fullName>Rehabilitación Motora Cuidado Completo</fullName>
                <isActive>false</isActive>
                <label>Rehabilitación Motora Cuidado Completo</label>
            </value>
            <value>
                <fullName>Rehabilitación Motora Cuidado Personalizada</fullName>
                <isActive>false</isActive>
                <label>Rehabilitación Motora Cuidado Personalizada</label>
            </value>
            <value>
                <fullName>Servicio de visita profesionales cuidado nutricional completo</fullName>
                <isActive>false</isActive>
                <label>Servicio de visita profesionales cuidado nutricional completo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Servicios_generales_y_especialidades__mdt/Servicios_generales_y_especialidades__mdt.object-meta.xml
<CustomObject>
    <description>Para mapear los tipo de servicios del modulo de paciente con el tipo de servicio en &quot;Servicio de modulo&quot;</description>
    <label>Servicios de modulo</label>
    <pluralLabel>Servicios generales y especialidades</pluralLabel>
</CustomObject>

force-app/main/default/objects/Servicios_generales_y_especialidades__mdt/fields/Cantidad_de_tareas_enfermero__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_tareas_enfermero__c</fullName>
    <label>Cantidad de tareas enfermero</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Servicios_generales_y_especialidades__mdt/fields/Cantidad_de_tareas_kinesiologo__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_tareas_kinesiologo__c</fullName>
    <label>Cantidad de tareas kinesiologo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Servicios_generales_y_especialidades__mdt/fields/Cantidad_de_tareas_medica__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_tareas_medica__c</fullName>
    <label>Cantidad de tareas medica</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Servicios_generales_y_especialidades__mdt/fields/Cantidad_de_tareas_nutricionista__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_tareas_nutricionista__c</fullName>
    <label>Cantidad de tareas nutricionista</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Servicios_generales_y_especialidades__mdt/fields/Nombre_de_servicio__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_servicio__c</fullName>
    <label>Nombre de servicio</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servicios_generales_y_especialidades__mdt/fields/Numero_de_Jerarquia__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Jerarquia__c</fullName>
    <label>Numero de Jerarquía</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Servicios_generales_y_especialidades__mdt/fields/Tipo_de_servicio_en_MDP__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_servicio_en_MDP__c</fullName>
    <label>Tipo de servicio en MDP</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Visita.recordType-meta.xml
<RecordType>
    <fullName>Visita</fullName>
    <active>true</active>
    <label>Visita profesional</label>
</RecordType>

force-app/main/default/classes/ServiciosDeModuloYTareasTriggerHelper.cls
public without sharing class ServiciosDeModuloYTareasTriggerHelper {
    
    public static void insertaTareasDeServicios(List<Servicios_del_Modulo__c> nuevosServicios){
        Set<Id> idsServicios = new Set<Id>();
        
        for(Servicios_del_Modulo__c unServicio : nuevosServicios){
            idsServicios.add(unServicio.id);
        }
        List<Servicios_del_Modulo__c> servicios = [
            SELECT id, Modulo_de_paciente__r.Cuenta__c,Servicios_disponibles__c,
            Modulo_de_paciente__r.Cuenta__r.Enfermero_Asignado__c,CreatedBy.Id,
            Modulo_de_paciente__r.Cuenta__r.Enfermero_Asignado__r.Title,
            Modulo_de_paciente__r.Cuenta__r.Nutricionista_Asignado__c,
            Modulo_de_paciente__r.Cuenta__r.Nutricionista_Asignado__r.Title,
            Modulo_de_paciente__r.Cuenta__r.Kinesiologo_asignado__c,
            Modulo_de_paciente__r.Cuenta__r.Kinesiologo_asignado__r.Title,
            Modulo_de_paciente__r.Cuenta__r.Medico_Asignado__c,
            Modulo_de_paciente__r.Cuenta__r.Medico_Asignado__r.Title,Cantidad__c,Modulo_de_paciente__r.Renovacion__c
            FROM Servicios_del_Modulo__c
            WHERE id IN :idsServicios
        ];
        
        Set<Id> idCuentaEnServicios = new Set<Id>();
        Map<id, Account> idConCuentas = new Map<Id,Account>();
        Map<id, Servicios_del_Modulo__c> cuentaConServicio = new Map<Id,Servicios_del_Modulo__c>();
        Map<String, String> servicioConProfesionalMtd = new Map<String,String>();
        Map<Id, String> cuentaConProfesional = new Map<Id,String>();
        List<Task> tareasParaInsertar = new List<Task>();
        
        for(Servicios_del_Modulo__c unServicio :  servicios){
            idCuentaEnServicios.add(unServicio.Modulo_de_paciente__r.Cuenta__c);
            cuentaConServicio.put(unServicio.Modulo_de_paciente__r.Cuenta__c, unServicio);
            String profesionalAsignado = servicioConProfesionalMtd.get(unServicio.Servicios_disponibles__c);
            cuentaConProfesional.put(unServicio.Modulo_de_paciente__r.Cuenta__c, profesionalAsignado);
        }
        List<Account> cuentasDeServicios = [
            SELECT id , LastName, FirstName, Enfermero_Asignado__c, Medico_Asignado__c,Kinesiologo_asignado__c	,Nutricionista_Asignado__c
            FROM Account 
            WHERE id IN : idCuentaEnServicios
        ];
        for(Account unaCuenta :  cuentasDeServicios){
            idConCuentas.put(unaCuenta.id, unaCuenta);
        }
        
        for(Servicios_del_Modulo__c unServicio: servicios){
            tareasParaInsertar.addAll(generaTareasDeServicios(unServicio,idConCuentas));
        }
        
        if(!tareasParaInsertar.isEmpty()){
            insert tareasParaInsertar;
        }
    }
    public static List<Task> generaTareasDeServicios(Servicios_del_Modulo__c unServicio,Map<id, Account> idConCuentas){
        /**Itero dependiendo de la cantidad de servicios**/
        decimal cantidadDeServicios  = unServicio.Cantidad__c == null ? 1: unServicio.Cantidad__c;
        List<Task> tareasParaInsertar = new List<Task>();
        
        for(integer j=0;j < cantidadDeServicios ;j++){
            Servicios_generales_y_especialidades__mdt servicioSeleccionado;
            
            List<Servicios_generales_y_especialidades__mdt> serviciosMtd =[
                SELECT id,Nombre_de_servicio__c,Numero_de_Jerarquia__c,Tipo_de_servicio_en_MDP__c,
                Cantidad_de_tareas_enfermero__c,Cantidad_de_tareas_kinesiologo__c,Cantidad_de_tareas_medica__c,Cantidad_de_tareas_nutricionista__c
                FROM Servicios_generales_y_especialidades__mdt
                ORDER BY Numero_de_Jerarquia__c DESC
            ];
            
            for(Servicios_generales_y_especialidades__mdt meta : serviciosMtd){
                if(unServicio.Servicios_disponibles__c == meta.Nombre_de_servicio__c){
                    servicioSeleccionado = meta;
                }   
            }
            
            if(servicioSeleccionado!=null){
                if(servicioSeleccionado.Cantidad_de_tareas_enfermero__c>0){
                    for(integer i =0 ;i <servicioSeleccionado.Cantidad_de_tareas_enfermero__c;i++ ){               
                        tareasParaInsertar.add(generaTareaBase(unServicio, idConCuentas, 'Enfermero'));
                    }
                }
                if(servicioSeleccionado.Cantidad_de_tareas_kinesiologo__c>0 ){
                    for(integer i =0 ; i <servicioSeleccionado.Cantidad_de_tareas_kinesiologo__c;i++ ){              
                        tareasParaInsertar.add(generaTareaBase(unServicio, idConCuentas, 'Kinesiologo'));
                    }
                }
                if(servicioSeleccionado.Cantidad_de_tareas_medica__c>0 ){
                    for(integer i =0 ;i <servicioSeleccionado.Cantidad_de_tareas_medica__c;i++ ){               
                        tareasParaInsertar.add(generaTareaBase(unServicio, idConCuentas, 'Medico'));
                    }
                }
                if(servicioSeleccionado.Cantidad_de_tareas_nutricionista__c>0 ){
                    for(integer i =0 ;i <servicioSeleccionado.Cantidad_de_tareas_nutricionista__c;i++ ){              
                        tareasParaInsertar.add(generaTareaBase(unServicio, idConCuentas, 'Nutricionista'));
                    }
                }
            }
        }
        return tareasParaInsertar;
    }
    public static Task generaTareaBase(Servicios_del_Modulo__c unServicio,Map<id, Account> idConCuentas, String nombreDeEspecialidad){
        Task nuevaTarea = new Task();
        nuevaTarea.Subject = 'Visita de '+ nombreDeEspecialidad;
        nuevaTarea.Paciente__c = idConCuentas.get(unServicio.Modulo_de_paciente__r.Cuenta__c) != null ? idConCuentas.get(unServicio.Modulo_de_paciente__r.Cuenta__c).id : null;   
        nuevaTarea.WhatId = unServicio.Modulo_de_paciente__c;
        nuevaTarea.Priority = 'Normal';
        nuevaTarea.Status = 'Abierta';
        Id idDelPropietario= validarProfesionalAsignado(unServicio, nombreDeEspecialidad);
        nuevaTarea.OwnerId =  idDelPropietario != null ? idDelPropietario : unServicio.CreatedBy.Id;
        Integer hoy= System.today().day();

        if(unServicio.Modulo_de_paciente__r.Renovacion__c == 'Alta'){
            nuevaTarea.ActivityDate= excluirFinDeSemana(System.today(),3);
        }
        else if(hoy <=10){
           nuevaTarea.ActivityDate= tareaParaViernes(0); 
        }
        else{
            nuevaTarea.ActivityDate= tareaParaViernes(1); 
        }

        return nuevaTarea;
    }
    
    public static Id validarProfesionalAsignado(Servicios_del_Modulo__c unServicio,String nombreDeEspecialidad){
        
        id idDeProfesional = null;
        
        Id usuarioPorDefecto = [
            SELECT Id
            FROM User
            WHERE userName = :Label.Default_username_motora
        ]?.id;
        
        idDeProfesional = usuarioPorDefecto;
        
        if (nombreDeEspecialidad== 'Nutricionista' &&
            unServicio.Modulo_de_paciente__r.Cuenta__r.Nutricionista_Asignado__c!=null &&
            unServicio.Modulo_de_paciente__r.Cuenta__r.Nutricionista_Asignado__r.Title!=null &&
            unServicio.Modulo_de_paciente__r.Cuenta__r.Nutricionista_Asignado__r.Title.containsIgnoreCase('Nutricionis')){
                idDeProfesional =unServicio.Modulo_de_paciente__r.Cuenta__r.Nutricionista_Asignado__c;
            }
        if(nombreDeEspecialidad== 'Kinesiologo' &&
           unServicio.Modulo_de_paciente__r.Cuenta__r.Kinesiologo_asignado__c!=null &&
           unServicio.Modulo_de_paciente__r.Cuenta__r.Kinesiologo_asignado__r.Title!=null &&
           unServicio.Modulo_de_paciente__r.Cuenta__r.Kinesiologo_asignado__r.Title.containsIgnoreCase('Kinesiol')){
               idDeProfesional =unServicio.Modulo_de_paciente__r.Cuenta__r.Kinesiologo_asignado__c;
           }
        if(nombreDeEspecialidad== 'Enfermero' &&
           unServicio.Modulo_de_paciente__r.Cuenta__r.Enfermero_Asignado__c!=null &&
           unServicio.Modulo_de_paciente__r.Cuenta__r.Enfermero_Asignado__r.Title!=null &&  
           unServicio.Modulo_de_paciente__r.Cuenta__r.Enfermero_Asignado__r.Title.containsIgnoreCase('Enferme')){
               idDeProfesional =unServicio.Modulo_de_paciente__r.Cuenta__r.Enfermero_Asignado__c;
           }
        if(nombreDeEspecialidad== 'Medico' &&
           unServicio.Modulo_de_paciente__r.Cuenta__r.Medico_Asignado__c!=null &&
           unServicio.Modulo_de_paciente__r.Cuenta__r.Medico_Asignado__r.Title!=null &&
           (unServicio.Modulo_de_paciente__r.Cuenta__r.Medico_Asignado__r.Title.containsIgnoreCase('Medic')|| 
            unServicio.Modulo_de_paciente__r.Cuenta__r.Medico_Asignado__r.Title.containsIgnoreCase('Médic'))){
                idDeProfesional =unServicio.Modulo_de_paciente__r.Cuenta__r.Medico_Asignado__c;
            }
        return idDeProfesional;
        
    }
    public static Date excluirFinDeSemana( date fechaInicial, Integer cantidadDeDias){

        fechaInicial= system.today().addDays(cantidadDeDias);
        DateTime currDate = DateTime.newInstance(fechaInicial.year(), fechaInicial.month(), fechaInicial.day());  
        String todayDay = currDate.format('EEEE');  
        integer workingDays=0;

        if(todayDay == 'Saturday' )  
            {  
                workingDays = workingDays + 2;  
            } else if(todayDay =='Sunday'){
                workingDays = workingDays + 1;  
            }                   
    
        return System.today().addDays(cantidadDeDias+workingDays);
    }

    public static Date tareaParaViernes(Integer mes){

        Date last = Date.newInstance(
            System.today().year(),
            System.today().month()+mes,
            Date.daysInMonth(System.today().year(), System.today().month()+mes)
            );

       Date viernes = last.toStartOfWeek().addDays(5);
       if (viernes > last) viernes = viernes.addDays(-8);

       return viernes;
    }
}