force-app/main/default/objects/Account/fields/Enfermero_Asignado__c.field-meta.xml
<CustomField>
    <fullName>Enfermero_Asignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enfermero Asignado</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Title</field>
            <operation>contains</operation>
            <value>Enferme</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Enfermero</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Kinesiologo_asignado__c.field-meta.xml
<CustomField>
    <fullName>Kinesiologo_asignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kinesiologo Asignado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Title</field>
            <operation>contains</operation>
            <value>Kinesi</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>KinesiologosAsignados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Medico_Asignado__c.field-meta.xml
<CustomField>
    <fullName>Medico_Asignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medico Asignado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Medico_Asignado</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nutricionista_Asignado__c.field-meta.xml
<CustomField>
    <fullName>Nutricionista_Asignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nutricionista Asignado</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Title</field>
            <operation>contains</operation>
            <value>Nutri</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Nutricionista</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tareas_de_profesionales__c/Tareas_de_profesionales__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Para creación de tareas automáticas (TaskGenerator)</description>
    <label>Tareas de profesionales</label>
</CustomObject>

force-app/main/default/objects/Tareas_de_profesionales__c/fields/Asunto_de_la_visita__c.field-meta.xml
<CustomField>
    <fullName>Asunto_de_la_visita__c</fullName>
    <label>Asunto de la visita</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tareas_de_profesionales__c/fields/Tareas_del_profesional__c.field-meta.xml
<CustomField>
    <fullName>Tareas_del_profesional__c</fullName>
    <label>Tareas del profesional</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tareas_de_profesionales__c/fields/Titulo_del_profesional__c.field-meta.xml
<CustomField>
    <fullName>Titulo_del_profesional__c</fullName>
    <label>Titulo del profesional</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Visita.recordType-meta.xml
<RecordType>
    <fullName>Visita</fullName>
    <active>true</active>
    <label>Visita profesional</label>
</RecordType>

force-app/main/default/classes/TaskGeneratorTest.cls
@isTest
public with sharing class TaskGeneratorTest {

    public static Profile psp = [
        SELECT Id 
        FROM Profile 
        WHERE Name
        LIKE '%PSP%'
        LIMIT 1
    ]; 
    public static User userPSP = new User(Alias = 'psptest', Email='psptest@testorg.com', 
                                          EmailEncodingKey='UTF-8', LastName='userPSPTest', LanguageLocaleKey='en_US', 
                                          LocaleSidKey='en_US', ProfileId = psp.Id, Title='medico',
                                          TimeZoneSidKey='America/Los_Angeles', UserName='userPSPTest@testorg.com');
    
    static{
        Tareas_de_profesionales__c kinesiologo = new Tareas_de_profesionales__c();
        kinesiologo.Name='Kinesiologo';
        kinesiologo.Titulo_del_profesional__c= 'Kinesiologo';
        kinesiologo.Asunto_de_la_visita__c= 'Visita de kinesiologo';
        kinesiologo.Tareas_del_profesional__c= 12;

        Tareas_de_profesionales__c nutricionista = new Tareas_de_profesionales__c();
        nutricionista.Name='Nutricionista';
        nutricionista.Titulo_del_profesional__c= 'Nutricionista';
        nutricionista.Asunto_de_la_visita__c= 'Visita de nutricionista';
        nutricionista.Tareas_del_profesional__c= 1;

        Tareas_de_profesionales__c enfermero = new Tareas_de_profesionales__c();
        enfermero.Name='Enfermero';
        enfermero.Titulo_del_profesional__c= 'Enfermero';
        enfermero.Asunto_de_la_visita__c= 'Visita de Enfermero';
        enfermero.Tareas_del_profesional__c= 2;

        Tareas_de_profesionales__c medico = new Tareas_de_profesionales__c();
        medico.Name='Medico';
        medico.Titulo_del_profesional__c= 'Medico';
        medico.Asunto_de_la_visita__c= 'Visita de medico';
        medico.Tareas_del_profesional__c= 1;

        insert new List<Tareas_de_profesionales__c>{kinesiologo,nutricionista,enfermero,medico};
        insert userPSP;
    }

    @IsTest
    static void testTaskCreation() {
        List<Account> accounts = new List<Account>();
        
        for(integer i = 0 ;i < 5; i++){
            Account testCuenta = Build.anAccountPacienteBestCare()
                .withLastName('Name Test'+i)
                .withRegimenDeInternacionDomiciliaria('Sí')
                .withEmpresadeinternaciondomiciliaria('Best care')		
                .withDNI('12346789'+i)
                .withCanalParaConsumidorBaby('Farmacias')
                .build();
            testCuenta.Nutricionista_Asignado__c = userPSP.id;
            testCuenta.Kinesiologo_asignado__c = userPSP.id;
            testCuenta.Medico_Asignado__c = userPSP.id;
            testCuenta.Enfermero_Asignado__c = userPSP.id;
            accounts.add(testCuenta);
        }
        
        insert accounts;

        Test.startTest();
        
        TaskGeneratorController.queueTasks(accounts, System.today());
        
        Test.stopTest();
        
        List<Task> tareas = [
            SELECT id, ownerId, Subject,WhatId, paciente__c
            FROM Task
            WHERE createdDate = today
            AND Subject LIKE : '%Visita de%'
        ];
        
        System.assertEquals(80, tareas.size());    
    }

    @IsTest
    static void testGetAccountWrapper() {
        
    Account testCuenta = Build.anAccountPacienteBestCare()
                .withLastName('Name Test')
                .withRegimenDeInternacionDomiciliaria('Sí')
                .withEmpresadeinternaciondomiciliaria('Best care')		
                .withDNI('12346789')
                .withCanalParaConsumidorBaby('Farmacias')
                .build();
        testCuenta.Enfermero_Asignado__c = userPSP.id;
        insert testCuenta;

        Test.startTest();
        
        TaskGeneratorController.accWrapper wrapper = TaskGeneratorController.getAccountWrapper(new List<String>{testCuenta.Id});
        
        Test.stopTest();
        
        System.assertEquals('Name Test', wrapper.accList[0].Name);
        System.assertEquals(1, wrapper.selectedIdSet.size());
    }

    @IsTest
    static void testGetAccounts() {
        
    Account testCuenta = Build.anAccountPacienteBestCare()
                .withLastName('Name Test')
                .withRegimenDeInternacionDomiciliaria('Sí')
                .withEmpresadeinternaciondomiciliaria('Best care')		
                .withDNI('12346789')
                .withCanalParaConsumidorBaby('Farmacias')
                .build();
        testCuenta.Medico_Asignado__c = userPSP.id;
        insert testCuenta;

        Test.startTest();
        Test.setCurrentPage(Page.TaskGenerator);
        ApexPages.StandardSetController controller = new ApexPages.StandardSetController(new List<Account>{testCuenta});
        controller.setSelected(new List<Account>{testCuenta});
        TaskGeneratorController extension = new TaskGeneratorController(controller);
        
        Test.stopTest();
        
        System.assertEquals('Name Test', extension.getCuentas().get(0).Name);
    }

    @IsTest
    static void testGetFieldSet() {

        Account testCuenta = Build.anAccountPacienteBestCare()
        .withLastName('Name Test')
        .withRegimenDeInternacionDomiciliaria('Sí')
        .withEmpresadeinternaciondomiciliaria('Best care')		
        .withDNI('12346789')
        .withCanalParaConsumidorBaby('Farmacias')
        .build();

        insert testCuenta;

        Test.startTest();
        Test.setCurrentPage(Page.TaskGenerator);
        ApexPages.StandardSetController controller = new ApexPages.StandardSetController(new List<Account>{testCuenta});
        controller.setSelected(new List<Account>{testCuenta});
        TaskGeneratorController extension = new TaskGeneratorController(controller);
       
        TaskGeneratorController.FieldsWrapper wrapperFields = new TaskGeneratorController.FieldsWrapper();
        List<TaskGeneratorController.FieldsWrapper> fields = extension.getFieldsSet();
        Test.stopTest();
        
        System.assertNotEquals(0, fields.size());
    }

}