force-app/main/default/objects/Account/fields/Enfermero_Asignado__c.field-meta.xml
<CustomField>
    <fullName>Enfermero_Asignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enfermero Asignado</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Title</field>
            <operation>contains</operation>
            <value>Enferme</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Enfermero</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado_de_paciente__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_paciente__c</fullName>
    <label>Estado de paciente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inicio</fullName>
                <default>true</default>
                <label>Inicio</label>
            </value>
            <value>
                <fullName>En Seguimiento</fullName>
            </value>
            <value>
                <fullName>En tratamiento</fullName>
            </value>
            <value>
                <fullName>No tratamiento</fullName>
            </value>
            <value>
                <fullName>Fin de tratamiento</fullName>
            </value>
            <value>
                <fullName>Excluido</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Medico_Asignado__c.field-meta.xml
<CustomField>
    <fullName>Medico_Asignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medico Asignado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Medico_Asignado</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nutricionista_Asignado__c.field-meta.xml
<CustomField>
    <fullName>Nutricionista_Asignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nutricionista Asignado</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Title</field>
            <operation>contains</operation>
            <value>Nutri</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Nutricionista</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Formulario__c/Formulario__c.object-meta.xml
<CustomObject>
    <label>Historia Clínica</label>
    <nameField>
        <label>Nombre de Formulario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historias Clínicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Formulario__c/fields/area_muscular_del_brazo__c.field-meta.xml
<CustomField>
    <fullName>area_muscular_del_brazo__c</fullName>
    <label>Circunferencia muscular del brazo</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Circunferencia_del_brazo_cm__c.field-meta.xml
<CustomField>
    <fullName>Circunferencia_del_brazo_cm__c</fullName>
    <label>Circunferencia del brazo (cm)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Edemas__c.field-meta.xml
<CustomField>
    <fullName>Edemas__c</fullName>
    <label>Edemas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Enteral__c.field-meta.xml
<CustomField>
    <fullName>Enteral__c</fullName>
    <label>Enteral</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contínua</fullName>
            </value>
            <value>
                <fullName>Cíclica diurna</fullName>
            </value>
            <value>
                <fullName>Cíclica nocturna</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Escara__c.field-meta.xml
<CustomField>
    <fullName>Escara__c</fullName>
    <label>Escara</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Fecha_ultimo_recambio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_ultimo_recambio__c</fullName>
    <label>Fecha último recambio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Grado__c.field-meta.xml
<CustomField>
    <fullName>Grado__c</fullName>
    <label>Grado</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/IMC__c.field-meta.xml
<CustomField>
    <fullName>IMC__c</fullName>
    <formula>Peso__c  /  ((Talla__c/100) ^ 2)</formula>
    <label>IMC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Nombre_y_Apellido_del_Paciente__c.field-meta.xml
<CustomField>
    <fullName>Nombre_y_Apellido_del_Paciente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>No debe completarse</inlineHelpText>
    <label>Nombre y apellido del paciente</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Best Care</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Regular</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Historias Clínicas</relationshipLabel>
    <relationshipName>Formularios3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Patologia__c.field-meta.xml
<CustomField>
    <fullName>Patologia__c</fullName>
    <label>Patología</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Patologias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Percentilo_Area_Muscular_del_Brazo__c.field-meta.xml
<CustomField>
    <fullName>Percentilo_Area_Muscular_del_Brazo__c</fullName>
    <label>Percentilo CMB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>&lt; 5</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>5-10</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>10-25</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>25-50</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>50-75</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>75-90</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>90-95</fullName>
            </value>
            <value>
                <fullName>&gt;95</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Percentilo_circunferencia_del_Brazo__c.field-meta.xml
<CustomField>
    <fullName>Percentilo_circunferencia_del_Brazo__c</fullName>
    <label>Percentilo circunferencia del Brazo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>&lt; 5</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>5-10</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>10-25</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>25-50</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>50-75</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>75-90</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>90-95</fullName>
            </value>
            <value>
                <fullName>&gt;95</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Percentilo_pliegue_tricipital__c.field-meta.xml
<CustomField>
    <fullName>Percentilo_pliegue_tricipital__c</fullName>
    <label>Percentilo pliegue tricipital</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>&lt; 5</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>5-10</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>10-25</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>25-50</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>50-75</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>75-90</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>90-95</fullName>
            </value>
            <value>
                <fullName>&gt;95</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Peso_actual_Talla__c.field-meta.xml
<CustomField>
    <fullName>Peso_actual_Talla__c</fullName>
    <formula>Peso__c / Talla__c</formula>
    <label>Peso/Talla</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Peso_ajustado__c.field-meta.xml
<CustomField>
    <fullName>Peso_ajustado__c</fullName>
    <label>Peso ajustado</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Peso_Estimado__c.field-meta.xml
<CustomField>
    <fullName>Peso_Estimado__c</fullName>
    <label>Peso Estimado (Kg)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Pliegue_tricipital__c.field-meta.xml
<CustomField>
    <fullName>Pliegue_tricipital__c</fullName>
    <label>Pliegue tricipital (mm)</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Requerimiento_calorico__c.field-meta.xml
<CustomField>
    <fullName>Requerimiento_calorico__c</fullName>
    <label>Requerimiento calórico (Kcal/día)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Sarcopenia__c.field-meta.xml
<CustomField>
    <fullName>Sarcopenia__c</fullName>
    <label>Sarcopenia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/Talla__c.field-meta.xml
<CustomField>
    <fullName>Talla__c</fullName>
    <label>Talla (cm)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Formulario__c/fields/VGS__c.field-meta.xml
<CustomField>
    <fullName>VGS__c</fullName>
    <label>VGS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B sospecha</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Patologias.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acidemia metilmalonica/propionica</fullName>
    </customValue>
    <customValue>
        <fullName>Aciduria Arginosucinica</fullName>
    </customValue>
    <customValue>
        <fullName>Aciduria Glutarica</fullName>
    </customValue>
    <customValue>
        <fullName>ACV Hemorragíco (Accidente cerebrovascular)</fullName>
    </customValue>
    <customValue>
        <fullName>ACV Isquemico (Accidente cerebrovascular)</fullName>
    </customValue>
    <customValue>
        <fullName>Adrenoleucodistrofia</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia a la Proteina de leche de vaca (APLV)</fullName>
    </customValue>
    <customValue>
        <fullName>Alzheirmer</fullName>
    </customValue>
    <customValue>
        <fullName>Anorexia</fullName>
    </customValue>
    <customValue>
        <fullName>Asma</fullName>
    </customValue>
    <customValue>
        <fullName>Bulimia</fullName>
    </customValue>
    <customValue>
        <fullName>Cirrosis Hepatica</fullName>
    </customValue>
    <customValue>
        <fullName>cirugía Aparato genitourinario</fullName>
    </customValue>
    <customValue>
        <fullName>Cirugía de cabeza y cuello</fullName>
    </customValue>
    <customValue>
        <fullName>Cirugía Gastrointestinal</fullName>
    </customValue>
    <customValue>
        <fullName>Demencia otros tipos</fullName>
    </customValue>
    <customValue>
        <fullName>Demencia senil</fullName>
    </customValue>
    <customValue>
        <fullName>Desnutrición</fullName>
    </customValue>
    <customValue>
        <fullName>Desnutrición Asociada a enfermedad</fullName>
    </customValue>
    <customValue>
        <fullName>Deterioro cognitivo crónico</fullName>
    </customValue>
    <customValue>
        <fullName>DGG (Deficiencia de Glucosa/Galactosa)</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes (DBT)</fullName>
    </customValue>
    <customValue>
        <fullName>Encefalitis</fullName>
    </customValue>
    <customValue>
        <fullName>Encefalopatía crónica no evolutiva (ECNE)</fullName>
    </customValue>
    <customValue>
        <fullName>Enfermedad obstructiva Crónica (EPOC)</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsia Refractaria</fullName>
    </customValue>
    <customValue>
        <fullName>Esclerosis lateral amiotrófica (ELA)</fullName>
    </customValue>
    <customValue>
        <fullName>Esofagitis Eosinofílica</fullName>
    </customValue>
    <customValue>
        <fullName>Fenilcetonuria</fullName>
    </customValue>
    <customValue>
        <fullName>Fibrosis Quistica</fullName>
    </customValue>
    <masterLabel>Patologías</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HCReportPageForPDFController.cls
public with sharing class HCReportPageForPDFController {
    
    public Pagereference armaryAdjuntarPdf(){

        Formulario__c historiaClinica = [
            SELECT Id, Name, Peso_ajustado__c,Nombre_y_Apellido_del_Paciente__c ,Peso_Estimado__c,Nombre_y_Apellido_del_Paciente__r.Nutricionista_Asignado__r.Name,
            Nombre_y_Apellido_del_Paciente__r.Enfermero_Asignado__r.Name,Nombre_y_Apellido_del_Paciente__r.Medico_Asignado__r.Name,Patologia__c,
            Nombre_y_Apellido_del_Paciente__r.Obra_social__pc,Nombre_y_Apellido_del_Paciente__r.Estado_de_paciente__c,Peso_actual_Talla__c, Talla__c, IMC__c,
            VGS__c, Circunferencia_del_brazo_cm__c, Percentilo_circunferencia_del_Brazo__c, Pliegue_tricipital__c, Percentilo_pliegue_tricipital__c, 
            area_muscular_del_brazo__c, Percentilo_Area_Muscular_del_Brazo__c, Edemas__c, Sarcopenia__c, Escara__c, Grado__c, Fecha_ultimo_recambio__c,
            Enteral__c,Requerimiento_calorico__c, Requerimiento_Proteico__c, Meta_nutricional__c, Modalidad__c, Aporte_cal_rico_enteral_Kcal_d_a__c,Edad__c,
            Aporte_v_a_oral_Kcal__c, Producto__c, Producto2__c, Producto_nro_3__c, Sistema_digestivo__c, Complicaciones_metabolicas__c, Comentarios__c,
            Fecha__c,Via_de_acceso__c,Complicacion_actual__c,Nombre_y_Apellido_del_Paciente__r.Name
            FROM Formulario__c 
            WHERE Id = :ApexPages.currentPage().getParameters().get('hcid')
        ];

        PageReference reportPage = Page.HcReportPage;
        reportPage.setRedirect(true);	
        reportPage.getParameters().put('hcid', historiaClinica.Id);
        Blob reportPdf;
        if(Test.isRunningTest()) { 
            reportPdf = blob.valueOf('Unit.Test');
          } else {
             reportPdf = reportPage.getContentAsPDF();
          }
        ContentVersion cv = new ContentVersion();
        cv.VersionData = reportPdf;
        cv.Title = historiaClinica.Name;
        cv.PathOnClient = historiaClinica.Name+'.pdf';
        
        insert cv;
        
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [
            SELECT ContentDocumentId 
            FROM ContentVersion 
            WHERE Id =: cv.Id
        ].ContentDocumentId;
        cdl.LinkedEntityId = historiaClinica.Id;
        cdl.ShareType = 'V';
        
        insert cdl;

        return reportPage;
    }
}