force-app/main/default/objects/Account/fields/Estado_de_paciente__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_paciente__c</fullName>
    <label>Estado de paciente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inicio</fullName>
                <default>true</default>
                <label>Inicio</label>
            </value>
            <value>
                <fullName>En Seguimiento</fullName>
            </value>
            <value>
                <fullName>En tratamiento</fullName>
            </value>
            <value>
                <fullName>No tratamiento</fullName>
            </value>
            <value>
                <fullName>Fin de tratamiento</fullName>
            </value>
            <value>
                <fullName>Excluido</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_de_obito__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_obito__c</fullName>
    <label>Fecha de baja</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Subestado_del_paciente__c.field-meta.xml
<CustomField>
    <fullName>Subestado_del_paciente__c</fullName>
    <label>Subestado del paciente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Estado_de_paciente__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tratamiento Efectivo</fullName>
            </value>
            <value>
                <fullName>Cobertura parcial con Consumo</fullName>
            </value>
            <value>
                <fullName>Negativa de la OS con Consumo</fullName>
            </value>
            <value>
                <fullName>Próximo a desafío</fullName>
            </value>
            <value>
                <fullName>Con otro laboratorio</fullName>
            </value>
            <value>
                <fullName>No tolera</fullName>
            </value>
            <value>
                <fullName>Se Rehúsa</fullName>
            </value>
            <value>
                <fullName>Negativa de la OS Sin consumo</fullName>
            </value>
            <value>
                <fullName>Alta de tratamiento</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Con otro laboratorio x OOSS</fullName>
            </value>
            <value>
                <fullName>Con otro laboratorio x Profesional</fullName>
            </value>
            <value>
                <fullName>Excluido</fullName>
            </value>
            <value>
                <fullName>En Seguimiento de ONG</fullName>
            </value>
            <value>
                <fullName>Imposible de contactar</fullName>
            </value>
            <value>
                <fullName>Cambio de indicación</fullName>
            </value>
            <value>
                <fullName>Migrado erroneamente</fullName>
            </value>
            <value>
                <fullName>No contactar Solicitud del paciente</fullName>
            </value>
            <value>
                <fullName>No contactar Solicitud del profesional</fullName>
            </value>
            <value>
                <fullName>Cambio de fórmula</fullName>
            </value>
            <value>
                <fullName>No renovó por negativa negociación OOSS</fullName>
            </value>
            <value>
                <fullName>No renovó cambio de indicación</fullName>
            </value>
            <value>
                <fullName>No renovó por cambio de empresa de internación domiciliaria</fullName>
            </value>
            <value>
                <fullName>No renovó por stock adicional</fullName>
            </value>
            <value>
                <fullName>Stock remanente</fullName>
            </value>
            <value>
                <fullName>Tramite iniciado</fullName>
            </value>
            <value>
                <fullName>Internado</fullName>
            </value>
            <value>
                <fullName>Modulo Inactivo</fullName>
            </value>
            <value>
                <fullName>Sin documentación</fullName>
            </value>
            <value>
                <fullName>Tramite no iniciado</fullName>
            </value>
            <value>
                <fullName>En tratamiento</fullName>
            </value>
            <value>
                <fullName>Aguarda Internación domiciliaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Internacion__c/Internacion__c.object-meta.xml
<CustomObject>
    <label>Internacion</label>
    <nameField>
        <displayFormat>INT-{0000}</displayFormat>
        <label>Internacion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Internacion__c/fields/Estado_de_Fin_Internaci_n__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Fin_Internaci_n__c</fullName>
    <label>Estado de Fin Internación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fallecimiento</fullName>
            </value>
            <value>
                <fullName>Alta</fullName>
            </value>
            <value>
                <fullName>Internación Domiciliaria/3er nivel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Internacion__c/fields/Fecha_de_Fin_Internaci_n__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin_Internaci_n__c</fullName>
    <label>Fecha de Fin Internación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Internacion__c/fields/Paciente__c.field-meta.xml
<CustomField>
    <fullName>Paciente__c</fullName>
    <label>Paciente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Sanatorio</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Internaciones</relationshipLabel>
    <relationshipName>Internaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Internacion__c/fields/Paciente_Aguarda_Internaci_n_domiciliari__c.field-meta.xml
<CustomField>
    <fullName>Paciente_Aguarda_Internaci_n_domiciliari__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paciente Aguarda Internación domiciliari</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Producto_de_Internacion__c/Producto_de_Internacion__c.object-meta.xml
<CustomObject>
    <label>Producto de Internación</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Producto de Internacion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos de internaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Producto_de_Internacion__c/fields/Bypass_apex__c.field-meta.xml
<CustomField>
    <fullName>Bypass_apex__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass apex</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Producto_de_Internacion__c/fields/Fecha_Fin_Producto__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin_Producto__c</fullName>
    <label>Fecha Fin Producto</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Producto_de_Internacion__c/fields/Internacion__c.field-meta.xml
<CustomField>
    <fullName>Internacion__c</fullName>
    <label>Internacion</label>
    <referenceTo>Internacion__c</referenceTo>
    <relationshipLabel>Productos de internacion</relationshipLabel>
    <relationshipName>Productos_de_internaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InternacionTriggerHelper.cls
public class InternacionTriggerHelper {
    
    public static void closeProductsDate(Map<Id, Internacion__c> internaciones){
        List<Producto_de_Internacion__c> products = new List<Producto_de_Internacion__c>();
        List<Producto_de_Internacion__c> productsToUpdate = new List<Producto_de_Internacion__c>();
        products.addAll(
            [
                SELECT id,Fecha_Fin_Producto__c,Internacion__c
                FROM Producto_de_Internacion__c
                WHERE Internacion__c IN : internaciones.keySet()
                AND Fecha_Fin_Producto__c = null
            ]
        );
        for(Producto_de_Internacion__c aProd : products){
            aProd.Fecha_Fin_Producto__c = internaciones.get(aProd.Internacion__c).Fecha_de_Fin_Internaci_n__c;
            aProd.Bypass_apex__c =true;
            productsToUpdate.add(aProd);
        }
        if(!productsToUpdate.isEmpty()){
            update productsToUpdate;
        }
    }
    
    
    public static void validateActiveInternacion(List<Internacion__c> internaciones){
        Map<Id, Internacion__c> internacionesWithAccId = new  Map<Id, Internacion__c>();
        Map<Id, Internacion__c> internacionesActives = new Map<Id, Internacion__c>();
        List<Internacion__c> internacionesDB = new List<Internacion__c>();
        
        for(Internacion__c aInternacion : internaciones){
            internacionesWithAccId.put(aInternacion.Paciente__c , aInternacion);
        }
        
        internacionesDB.addAll([
            SELECT id ,Name,Paciente__c
            FROM Internacion__c
            WHERE Paciente__c IN : internacionesWithAccId.keySet()
            AND Fecha_de_Fin_Internaci_n__c= null 
        ]);
        
        for(Internacion__c aInternacion : internacionesDB){
            internacionesActives.put(aInternacion.Paciente__c , aInternacion);
        }
        
        for(Internacion__c aInt : internaciones){
            if(internacionesActives.containsKey(aInt.Paciente__c)){
                String internacionLink = URL.getSalesforceBaseUrl().toExternalForm()+'/'+internacionesActives.get(aInt.Paciente__c).Id;
                String hiperlink= '<a href='+internacionLink+'>'+internacionesActives.get(aInt.Paciente__c).Name +'</a>';
                aInt.addError('El Paciente tiene una internación activa: ' + hiperlink,false);
            }
        }
    }
    public static void updateAccountStatus(List<Internacion__c> internaciones){
        Map<Id, Internacion__c> internacionesWithAccountId = new Map<Id, Internacion__c>();
        List<Account> accounts = new List<Account>();
        
        for(Internacion__c aInt: internaciones){
            internacionesWithAccountId.put(aInt.Paciente__c, aInt);
        }
        
        List<Account> accountsToUpdateStatus = [
            SELECT id,Estado_de_paciente__c,Subestado_del_paciente__c,Fecha_de_obito__c
            FROM Account
            WHERE id IN :internacionesWithAccountId.keySet()
        ];
        
        for(Account anAccount : accountsToUpdateStatus){
            Internacion__c internacion = internacionesWithAccountId.get(anAccount.Id);
            anAccount.Subestado_del_paciente__c = internacion.Estado_de_Fin_Internaci_n__c;
            
            if(internacion.Fecha_de_Fin_Internaci_n__c==null){
                anAccount.Estado_de_paciente__c = 'En tratamiento';
                anAccount.Fecha_de_obito__c = null;
                if(internacion.Paciente_Aguarda_Internaci_n_domiciliari__c){
                    anAccount.Subestado_del_paciente__c = 'Aguarda Internación domiciliaria';
                }
            }else{
                anAccount.Estado_de_paciente__c = 'No tratamiento';
            }
            accounts.add(anAccount);
        }
        if(!accounts.isEmpty()){
            update accounts;
        }
    }

}