force-app/main/default/objects/Account/fields/Estado_de_paciente__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_paciente__c</fullName>
    <label>Estado de paciente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inicio</fullName>
                <default>true</default>
                <label>Inicio</label>
            </value>
            <value>
                <fullName>En Seguimiento</fullName>
            </value>
            <value>
                <fullName>En tratamiento</fullName>
            </value>
            <value>
                <fullName>No tratamiento</fullName>
            </value>
            <value>
                <fullName>Fin de tratamiento</fullName>
            </value>
            <value>
                <fullName>Excluido</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Estado_del_ultimo_modulo__c.field-meta.xml
<CustomField>
    <fullName>Estado_del_ultimo_modulo__c</fullName>
    <label>Estado del ultimo modulo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_de_baja__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_baja__c</fullName>
    <description>Debe ser obligatorio cuando se cambia al estado y todos los subestado de &apos;&apos;No tratamiento&apos;&apos; o &apos;&apos;Fin de tratamiento&apos;&apos; menos con el subestado &apos;&apos;Fallecido&apos;&apos;.</description>
    <label>Fecha de baja.</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_de_obito__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_obito__c</fullName>
    <label>Fecha de baja</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Formulas_actuales__c.field-meta.xml
<CustomField>
    <fullName>Formulas_actuales__c</fullName>
    <label>Fórmulas actuales</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Módulo</label>
    <referenceTo>Modulo__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Modulo_activo__c.field-meta.xml
<CustomField>
    <fullName>Modulo_activo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modulo Activo</label>
    <referenceTo>Modulo_de_paciente__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Subestado_del_paciente__c.field-meta.xml
<CustomField>
    <fullName>Subestado_del_paciente__c</fullName>
    <label>Subestado del paciente</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Estado_de_paciente__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tratamiento Efectivo</fullName>
            </value>
            <value>
                <fullName>Cobertura parcial con Consumo</fullName>
            </value>
            <value>
                <fullName>Negativa de la OS con Consumo</fullName>
            </value>
            <value>
                <fullName>Próximo a desafío</fullName>
            </value>
            <value>
                <fullName>Con otro laboratorio</fullName>
            </value>
            <value>
                <fullName>No tolera</fullName>
            </value>
            <value>
                <fullName>Se Rehúsa</fullName>
            </value>
            <value>
                <fullName>Negativa de la OS Sin consumo</fullName>
            </value>
            <value>
                <fullName>Alta de tratamiento</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Con otro laboratorio x OOSS</fullName>
            </value>
            <value>
                <fullName>Con otro laboratorio x Profesional</fullName>
            </value>
            <value>
                <fullName>Excluido</fullName>
            </value>
            <value>
                <fullName>En Seguimiento de ONG</fullName>
            </value>
            <value>
                <fullName>Imposible de contactar</fullName>
            </value>
            <value>
                <fullName>Cambio de indicación</fullName>
            </value>
            <value>
                <fullName>Migrado erroneamente</fullName>
            </value>
            <value>
                <fullName>No contactar Solicitud del paciente</fullName>
            </value>
            <value>
                <fullName>No contactar Solicitud del profesional</fullName>
            </value>
            <value>
                <fullName>Cambio de fórmula</fullName>
            </value>
            <value>
                <fullName>No renovó por negativa negociación OOSS</fullName>
            </value>
            <value>
                <fullName>No renovó cambio de indicación</fullName>
            </value>
            <value>
                <fullName>No renovó por cambio de empresa de internación domiciliaria</fullName>
            </value>
            <value>
                <fullName>No renovó por stock adicional</fullName>
            </value>
            <value>
                <fullName>Stock remanente</fullName>
            </value>
            <value>
                <fullName>Tramite iniciado</fullName>
            </value>
            <value>
                <fullName>Internado</fullName>
            </value>
            <value>
                <fullName>Modulo Inactivo</fullName>
            </value>
            <value>
                <fullName>Sin documentación</fullName>
            </value>
            <value>
                <fullName>Tramite no iniciado</fullName>
            </value>
            <value>
                <fullName>En tratamiento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ultimo_Modulo__c.field-meta.xml
<CustomField>
    <fullName>Ultimo_Modulo__c</fullName>
    <label>Tipo de servicio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Logistico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Modulo__c/Modulo__c.object-meta.xml
<CustomObject>
    <label>Módulo</label>
    <nameField>
        <label>Nombre de Modulo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Módulos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Modulo__c/fields/N_de_Material__c.field-meta.xml
<CustomField>
    <fullName>N_de_Material__c</fullName>
    <label>N° de Material</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/Modulo_de_paciente__c.object-meta.xml
<CustomObject>
    <label>Modulo de paciente</label>
    <nameField>
        <displayFormat>MDP-{0000}</displayFormat>
        <label>Nro de Modulo de paciente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modulos de paciente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado de Servicio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Estado_de_modulo__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_modulo__c</fullName>
    <label>Estado de modulo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ingresado</fullName>
                <default>true</default>
                <label>Ingresado</label>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Procesado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Ajuste Financiero</fullName>
                <isActive>false</isActive>
                <label>Ajuste Financiero</label>
            </value>
            <value>
                <fullName>Cerrado</fullName>
                <isActive>false</isActive>
                <label>Cerrado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modulo</label>
    <referenceTo>Modulo__c</referenceTo>
    <relationshipLabel>Modulos de paciente</relationshipLabel>
    <relationshipName>Modulos_de_paciente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/N_de_Material__c.field-meta.xml
<CustomField>
    <fullName>N_de_Material__c</fullName>
    <formula>TEXT(Modulo__r.N_de_Material__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>N° de Material</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo de servicio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CUIDADO PERSONALIZADO</fullName>
            </value>
            <value>
                <fullName>CUIDADO COMPLETO</fullName>
            </value>
            <value>
                <fullName>REHABILITACIÓN DEGLUTORIA</fullName>
            </value>
            <value>
                <fullName>REHABILITACIÓN MOTORA PLUS</fullName>
            </value>
            <value>
                <fullName>REHABILITACION MOTORA BASICO ENTERAL</fullName>
            </value>
            <value>
                <fullName>REHABILITACION MOTORA - INTERMEDIO</fullName>
            </value>
            <value>
                <fullName>REHABILITACION MOTORA BASICO ORAL</fullName>
            </value>
            <value>
                <fullName>AUTOCUIDADO.</fullName>
                <default>true</default>
                <label>AUTOCUIDADO.</label>
            </value>
            <value>
                <fullName>CUIDADO BÁSICO</fullName>
            </value>
            <value>
                <fullName>AUTOCUIDADO</fullName>
                <isActive>false</isActive>
                <label>AUTOCUIDADO</label>
            </value>
            <value>
                <fullName>Complejidad media</fullName>
                <isActive>false</isActive>
                <label>Complejidad media</label>
            </value>
            <value>
                <fullName>Con rehabilitacion deglutoria</fullName>
                <isActive>false</isActive>
                <label>Con rehabilitacion deglutoria</label>
            </value>
            <value>
                <fullName>Full</fullName>
                <isActive>false</isActive>
                <label>Full</label>
            </value>
            <value>
                <fullName>Logístico</fullName>
                <isActive>false</isActive>
                <label>Logístico</label>
            </value>
            <value>
                <fullName>REHABILITACIÓN MOTORA CUIDADO COMPLETO</fullName>
                <isActive>false</isActive>
                <label>REHABILITACIÓN MOTORA CUIDADO COMPLETO</label>
            </value>
            <value>
                <fullName>REHABILITACIÓN MOTORA CUIDADO PERSONALIZADA</fullName>
                <isActive>false</isActive>
                <label>REHABILITACIÓN MOTORA CUIDADO PERSONALIZADA</label>
            </value>
            <value>
                <fullName>Recuperacion nutricional (oral)</fullName>
                <isActive>false</isActive>
                <label>Recuperacion nutricional (oral)</label>
            </value>
            <value>
                <fullName>Sin rehabilitacion deglutoria</fullName>
                <isActive>false</isActive>
                <label>Sin rehabilitacion deglutoria</label>
            </value>
            <value>
                <fullName>Solo profesionales</fullName>
                <isActive>false</isActive>
                <label>Solo profesionales</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Modulo</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Producto_de_modulo__c/Producto_de_modulo__c.object-meta.xml
<CustomObject>
    <label>Producto de módulo</label>
    <nameField>
        <displayFormat>PDM-{0000}</displayFormat>
        <label>Nro de Producto de módulo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos de módulo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Producto_de_modulo__c/fields/Modulo_de_paciente__c.field-meta.xml
<CustomField>
    <fullName>Modulo_de_paciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Módulo de paciente</label>
    <referenceTo>Modulo_de_paciente__c</referenceTo>
    <relationshipName>Planes_de_cuidado</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ModuloDePacienteTriggerTest.cls
@isTest
private class ModuloDePacienteTriggerTest {

	public static List<Account> listNewAccounts = new List<Account> ();
	public static List<Product2> listNewProductos = new List<Product2> ();
	public static List<Modulo_de_paciente__c> listNewModuloPacientes = new List<Modulo_de_paciente__c> ();
	public static List<Producto_de_modulo__c> listNewProductoModulo = new List<Producto_de_modulo__c> ();
	public static String expectedResult;


 /*EL TRIGGER DE PRODUCTODEMODULO EN PRODUCCION ESTABA DESACTIVADO, LO ACTIVE NUEVAMENTE PERO COMENTE LA FUNCIONALIDAD VIEJA*/
	/*@isTest static void UpdateModuloPacienteInactivo() {

		CreateSimpleScheme();
		GetAccounts();
        
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);

		Test.startTest();
		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;
       
		Test.stopTest();

		GetAccounts();
		System.assertEquals(null, listNewAccounts[0].Formulas_actuales__c, System.label.testsmgInvalidNull);
	}


	@isTest static void UpdateModuloPacienteInactivoConVariasModulosYProductos() {

		CreateMultiScheme();

		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);

		Test.startTest();
		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;
		Test.stopTest();

		GetAccounts();
		System.assertEquals('ProductName-I512, 4 Unidades', listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);
		System.assertEquals(null, listNewAccounts[1].Formulas_actuales__c, System.label.testsmgInvalidNull);
	}

	@isTest static void UpdateModuloPacienteInactivoConVariosModulos() {

		CreateSimpleSchemeMultiModulesAccount();

		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);

		Test.startTest();
		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;
		Test.stopTest();

		GetAccounts();
		System.assertEquals('ProductName-P128, 3 Unidades' + '\r\n' + 'ProductName-P128, 4 Unidades', 
			listNewAccounts[0].Formulas_actuales__c, System.label.testmsgNotMach);
	}

	@isTest static void UpdateModuloPacienteInactivoConVariosProductos() {

		CreateSimpleSchemeMultiProducts();

		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);

		Test.startTest();
		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;
		Test.stopTest();

		GetAccounts();
		System.assertEquals(null, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testsmgInvalidNull);
	}*/

	@isTest static void UpdateModuloPacienteActivo() {

		CreateSimpleScheme();

		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;

		Test.startTest();
		listNewModuloPacientes[0].Estado__c = 'Activo';
		update listNewModuloPacientes;
		Test.stopTest();

		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);
	}

	@isTest static void UpdateModuloPacienteActivoConVariosProductosYModulos() {

		CreateMultiScheme();

		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;

		Test.startTest();
		listNewModuloPacientes[0].Estado__c = 'Activo';
		update listNewModuloPacientes;
		Test.stopTest();

		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);
		System.assertEquals(null, listNewAccounts[1].Formulas_actuales__c, 
			System.label.testsmgInvalidNull);
	}

	@isTest static void UpdateModuloPacienteActivoConVariosModulos() {

		CreateSimpleSchemeMultiModulesAccount();

		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;

		Test.startTest();
		listNewModuloPacientes[0].Estado__c = 'Activo';
		update listNewModuloPacientes;
		Test.stopTest();

		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);
	}


	@isTest static void UpdateModuloPacienteActivoConVariosProductos() {

		CreateSimpleSchemeMultiProducts();

		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;

		Test.startTest();
		listNewModuloPacientes[0].Estado__c = 'Activo';
		update listNewModuloPacientes;
		Test.stopTest();

		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);
	}

	/*@isTest static void DeleteModuloPacienteInactivo() {

		CreateSimpleScheme();
		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;

		Test.startTest();
		delete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals(null, listNewAccounts[0].Formulas_actuales__c, System.label.testsmgInvalidNull);
	}*/

	@isTest static void DeleteModuloPacienteInactivoConVariosProductosYModulos() {

		CreateMultiScheme();
		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;

		Test.startTest();
		delete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals('ProductName-I512, 4 Unidades', listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);
		System.assertEquals(null, listNewAccounts[1].Formulas_actuales__c, System.label.testsmgInvalidNull);
	}

	@isTest static void DeleteModuloPacienteInactivoConVariosModulos() {

		CreateSimpleSchemeMultiModulesAccount();
		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;

		Test.startTest();
		delete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals('ProductName-P128, 3 Unidades' + '\r\n' + 'ProductName-P128, 4 Unidades', 
			listNewAccounts[0].Formulas_actuales__c, System.label.testmsgNotMach);
	}

	@isTest static void DeleteDeTodosLosModuloPacienteInactivoConVariosModulos() {

		CreateSimpleSchemeMultiModulesAccount();
		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;

		Test.startTest();
		delete listNewModuloPacientes;
		Test.stopTest();

		GetAccounts();
		System.assertEquals(null, listNewAccounts[0].Formulas_actuales__c, System.label.testsmgInvalidNull);
	}

	@isTest static void DeleteModuloPacienteInactivoConVariosProductos() {

		CreateSimpleSchemeMultiProducts();
		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;

		Test.startTest();
		delete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals(null, listNewAccounts[0].Formulas_actuales__c, System.label.testsmgInvalidNull);
	}


	/*@isTest static void DeleteModuloPacienteActivo() {

		CreateSimpleScheme();
		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c,
			 System.label.testmsgNotMach);

		Test.startTest();
		delete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals(null, listNewAccounts[0].Formulas_actuales__c, System.label.testsmgInvalidNull);
	}*/

/*	@isTest static void DeleteModuloPacienteActivoConVariosProductosYModulos() {

		CreateMultiScheme();
		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);

		Test.startTest();
		delete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals('ProductName-I512, 4 Unidades',
			 listNewAccounts[0].Formulas_actuales__c, System.label.testmsgNotMach);
		System.assertEquals(null, listNewAccounts[1].Formulas_actuales__c, System.label.testsmgInvalidNull);
	}*/

	/*@isTest static void DeleteModuloPacienteActivoConVariosModulos() {

		CreateSimpleSchemeMultiModulesAccount();
		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c,
			 System.label.testmsgNotMach);

		Test.startTest();
		delete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals('ProductName-P128, 3 Unidades' + '\r\n' + 'ProductName-P128, 4 Unidades', 
			listNewAccounts[0].Formulas_actuales__c, System.label.testmsgNotMach);
	}
*/
/*	@isTest static void DeleteModuloPacienteActivoConVariosProductos() {

		CreateSimpleSchemeMultiProducts();
		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);

		Test.startTest();
		delete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals(null, listNewAccounts[0].Formulas_actuales__c, System.label.testsmgInvalidNull);
	}*/

	@isTest static void UnDeleteModuloPacienteInactivo() {

		CreateSimpleScheme();
		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;

		GetAccounts();
		System.assertEquals(null, listNewAccounts[0].Formulas_actuales__c, System.label.testsmgInvalidNull);
		delete listNewModuloPacientes[0];

		Test.startTest();
		undelete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals(null, listNewAccounts[0].Formulas_actuales__c, System.label.testsmgInvalidNull);
	}

	@isTest static void UnDeleteModuloPacienteInactivoConVariosProductosYModulos() {

		CreateMultiScheme();
		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;

		GetAccounts();
		System.assertEquals('ProductName-I512, 4 Unidades', 
			listNewAccounts[0].Formulas_actuales__c, System.label.testmsgNotMach);
		delete listNewModuloPacientes[0];

		Test.startTest();
		undelete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals('ProductName-I512, 4 Unidades', 
			listNewAccounts[0].Formulas_actuales__c, System.label.testmsgNotMach);
		System.assertEquals(null, listNewAccounts[1].Formulas_actuales__c, System.label.testsmgInvalidNull);
	}

	@isTest static void UnDeleteModuloPacienteInactivoConVariosModulos() {

		CreateSimpleSchemeMultiModulesAccount();
		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;

		GetAccounts();
		System.assertEquals('ProductName-P128, 3 Unidades' + '\r\n' + 'ProductName-P128, 4 Unidades', 
			listNewAccounts[0].Formulas_actuales__c, System.label.testmsgNotMach);
		delete listNewModuloPacientes[0];

		Test.startTest();
		undelete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals('ProductName-P128, 3 Unidades' + '\r\n' + 'ProductName-P128, 4 Unidades', 
			listNewAccounts[0].Formulas_actuales__c, System.label.testmsgNotMach);

		listNewModuloPacientes = [select id, Estado__c from Modulo_de_paciente__c];
		System.assertEquals('Inactivo', listNewModuloPacientes[0].Estado__c,
			 'El estado del modulo al recuperarlo no es el mismo.');
	}

	@isTest static void UnDeleteModuloPacienteInactivoConVariosProductos() {

		CreateSimpleSchemeMultiProducts();
		listNewModuloPacientes[0].Estado__c = 'Inactivo';
		update listNewModuloPacientes;

		GetAccounts();
		System.assertEquals(null, listNewAccounts[0].Formulas_actuales__c, System.label.testsmgInvalidNull);
		delete listNewModuloPacientes[0];

		Test.startTest();
		undelete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals(null, listNewAccounts[0].Formulas_actuales__c, System.label.testsmgInvalidNull);
	}

	/*@isTest static void UnDeleteModuloPacienteActivo() {

		CreateSimpleScheme();
		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);

		delete listNewModuloPacientes[0];

		Test.startTest();
		undelete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);
	}
*/
/*	@isTest static void UnDeleteModuloPacienteActivoConVariosProductosYModulos() {

		CreateMultiScheme();
		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);

		delete listNewModuloPacientes[0];

		Test.startTest();
		undelete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);
		System.assertEquals(null, listNewAccounts[1].Formulas_actuales__c, System.label.testsmgInvalidNull);
	}
*/
/*	@isTest static void UnDeleteModuloPacienteActivoConVariosModulos() {

		CreateSimpleSchemeMultiModulesAccount();
		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c,
			 System.label.testmsgNotMach);
		delete listNewModuloPacientes[0];

		Test.startTest();
		undelete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c,
			 System.label.testmsgNotMach);
	}
*/
	/*@isTest static void UnDeleteModuloPacienteActivoConVariosProductos() {

		CreateSimpleSchemeMultiProducts();
		GetAccounts();

		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c,
			 System.label.testmsgNotMach);

		delete listNewModuloPacientes[0];

		Test.startTest();
		undelete listNewModuloPacientes[0];
		Test.stopTest();

		GetAccounts();
		System.assertEquals(expectedResult, listNewAccounts[0].Formulas_actuales__c, 
			System.label.testmsgNotMach);
	}*/
	@IsTest
	static void whenInsertModuloActivoIsFull_AccountUltimoModuloFull(){
		newAccount();
		GetAccounts();
		
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').withTipo('CUIDADO COMPLETO').build());

		Test.startTest();
			insert listNewModuloPacientes;
		Test.stopTest();

		Account cuenta = [SELECT Ultimo_Modulo__c FROM account WHERE id =:listNewAccounts[0].id];
		System.assertEquals('Full', cuenta.Ultimo_Modulo__c);
		
	}
	@IsTest
	static void whenUpsertModuloActivoIsFull_AccountUltimoModuloFull(){
		newAccount();
		GetAccounts();
		
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Inactivo').withTipo('CUIDADO COMPLETO').build());
		insert listNewModuloPacientes;
		
		listNewModuloPacientes[0].Estado__c = 'Activo';

		Test.startTest();
			update listNewModuloPacientes;
		Test.stopTest();

		Account cuenta = [SELECT Ultimo_Modulo__c FROM account WHERE id =:listNewAccounts[0].id];
		System.assertEquals('Full', cuenta.Ultimo_Modulo__c);
		
	}
	@IsTest
	static void whenInsertModuloActivoIsNotFull_AccountUltimoModuloLogistico(){
		string tipo;
		newAccount();
		GetAccounts();
		
		for( Schema.PicklistEntry pickListVal : Modulo_de_paciente__c.Tipo__c.getDescribe().getPicklistValues()){
            if(pickListVal.getValue() != 'CUIDADO COMPLETO'){
				tipo = pickListVal.getValue();
				break;
			}
        } 
		
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').withTipo(tipo).build());
		
		Test.startTest();
			insert listNewModuloPacientes;
		Test.stopTest();

		Account cuenta = [SELECT Ultimo_Modulo__c FROM account WHERE id =:listNewAccounts[0].id];
		System.assertEquals('Logistico', cuenta.Ultimo_Modulo__c);
		
	}
	@IsTest
	static void whenUpdateModuloActivoIsNotFull_AccountUltimoModuloLogistico(){
		string tipo;
		newAccount();
		GetAccounts();
		
		for( Schema.PicklistEntry pickListVal : Modulo_de_paciente__c.Tipo__c.getDescribe().getPicklistValues()){
            if(pickListVal.getValue() != 'CUIDADO COMPLETO'){
				tipo = pickListVal.getValue();
				break;
			}
        } 
		
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Inactivo').withTipo(tipo).build());
		insert listNewModuloPacientes;
		
		listNewModuloPacientes[0].Estado__c = 'Activo';

		Test.startTest();
			update listNewModuloPacientes;
		Test.stopTest();

		Account cuenta = [SELECT Ultimo_Modulo__c FROM account WHERE id =:listNewAccounts[0].id];
		System.assertEquals('Logistico', cuenta.Ultimo_Modulo__c);
		
	}
	@IsTest
	static void whenInsertModuloActivoFullAndInsertModuloNotFullActivo_AccountUltimoModuloFull(){
		string tipo;
		newAccount();
		GetAccounts();
		
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').withTipo('CUIDADO COMPLETO').build());
		for( Schema.PicklistEntry pickListVal : Modulo_de_paciente__c.Tipo__c.getDescribe().getPicklistValues()){
            if(pickListVal.getValue() != 'CUIDADO COMPLETO'){
				tipo = pickListVal.getValue();
				break;
			}
        }
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').withTipo(tipo).build());

		Test.startTest();
			insert listNewModuloPacientes;
		Test.stopTest();

		Account cuenta = [SELECT Ultimo_Modulo__c FROM account WHERE id =:listNewAccounts[0].id];
		System.assertEquals('Full', cuenta.Ultimo_Modulo__c);
		
	}
	@IsTest
	static void whenInsertModuloNotFullActivoAndUpdateModuloActivoFull_AccountUltimoModuloFull(){
		string tipo;
		newAccount();
		GetAccounts();
		
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Inactivo').withTipo('CUIDADO COMPLETO').build());
		for( Schema.PicklistEntry pickListVal : Modulo_de_paciente__c.Tipo__c.getDescribe().getPicklistValues()){
            if(pickListVal.getValue() != 'CUIDADO COMPLETO'){
				tipo = pickListVal.getValue();
				break;
			}
        }
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').withTipo(tipo).build());
		insert listNewModuloPacientes;

		listNewModuloPacientes[0].Estado__c = 'Activo';
		Test.startTest();
		update listNewModuloPacientes;
		Test.stopTest();

		Account cuenta = [SELECT Ultimo_Modulo__c FROM account WHERE id =:listNewAccounts[0].id];
		System.assertEquals('Full', cuenta.Ultimo_Modulo__c);
		
		
	}
	@IsTest
	static void whenInsertModuloNotFullActivoAndModuloInactivoFull_AccountUltimoModuloLogistico(){
		string tipo;
		newAccount();
		GetAccounts();
		
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Inactivo').withTipo('CUIDADO COMPLETO').build());
		for( Schema.PicklistEntry pickListVal : Modulo_de_paciente__c.Tipo__c.getDescribe().getPicklistValues()){
            if(pickListVal.getValue() != 'CUIDADO COMPLETO'){
				tipo = pickListVal.getValue();
				break;
			}
        }
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').withTipo(tipo).build());

		Test.startTest();
			insert listNewModuloPacientes;
		Test.stopTest();

		Account cuenta = [SELECT Ultimo_Modulo__c FROM account WHERE id =:listNewAccounts[0].id];
		System.assertEquals('Logistico', cuenta.Ultimo_Modulo__c);
		
	}
	@IsTest
	static void whenModuloFullIsActive_AccountChangeToStatusEnTratamientoAndSubStatusTratamientoEfectivo(){
		newAccount();
		GetAccounts();
		
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').withTipo('CUIDADO COMPLETO').build());

		Test.startTest();
			insert listNewModuloPacientes;
		Test.stopTest();

		Account cuenta = [SELECT Estado_de_paciente__c, Subestado_del_paciente__c FROM account WHERE id =:listNewAccounts[0].id];
		System.assertEquals('En tratamiento', cuenta.Estado_de_paciente__c);
		System.assertEquals('Tratamiento Efectivo', cuenta.Subestado_del_paciente__c);
	}
	@IsTest
	static void whenModuloNotFullIsActive_AccountChangeToStatusEnTratamientoAndSubStatusTratamientoEfectivo(){
		string tipo;
		newAccount();
		GetAccounts();
		
		for( Schema.PicklistEntry pickListVal : Modulo_de_paciente__c.Tipo__c.getDescribe().getPicklistValues()){
            if(pickListVal.getValue() != 'CUIDADO COMPLETO'){
				tipo = pickListVal.getValue();
				break;
			}
        } 
		
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').withTipo(tipo).build());
		
		Test.startTest();
			insert listNewModuloPacientes;
		Test.stopTest();

		Account cuenta = [SELECT Estado_de_paciente__c, Subestado_del_paciente__c FROM account WHERE id =:listNewAccounts[0].id];
		System.assertEquals('En tratamiento', cuenta.Estado_de_paciente__c);
		System.assertEquals('Tratamiento Efectivo', cuenta.Subestado_del_paciente__c);
	}
	@IsTest
	static void whenModuloIsInactiveSubestadoInternado_AccountNotChange(){
		string tipo;
		newAccount();
		GetAccounts();
		
		for( Schema.PicklistEntry pickListVal : Modulo_de_paciente__c.Tipo__c.getDescribe().getPicklistValues()){
            if(pickListVal.getValue() != 'CUIDADO COMPLETO'){
				tipo = pickListVal.getValue();
				break;
			}
        } 
		
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').withTipo(tipo).build());
		insert listNewModuloPacientes;

		listNewAccounts[0].Estado_de_paciente__c = 'En Seguimiento';
		listNewAccounts[0].Subestado_del_paciente__c = 'Tramite iniciado';
		update listNewAccounts;

		listNewModuloPacientes[0].Estado__c = 'Inactivo';

		Test.startTest();
			update listNewModuloPacientes;
		Test.stopTest();

		Account cuenta = [SELECT Estado_de_paciente__c, Subestado_del_paciente__c FROM account WHERE id =:listNewAccounts[0].id];
		System.assertEquals('En Seguimiento', cuenta.Estado_de_paciente__c);
		System.assertEquals('Tramite iniciado', cuenta.Subestado_del_paciente__c);
	}
	@IsTest
	static void whenModuloIsInactiveAccountEstadoNotratamiento_AccountNotChange(){
		string tipo;
		newAccount();
		GetAccounts();
		
		for( Schema.PicklistEntry pickListVal : Modulo_de_paciente__c.Tipo__c.getDescribe().getPicklistValues()){
            if(pickListVal.getValue() != 'CUIDADO COMPLETO'){
				tipo = pickListVal.getValue();
				break;
			}
        } 
		
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').withTipo(tipo).build());
		insert listNewModuloPacientes;

		listNewAccounts[0].Estado_de_paciente__c = 'No tratamiento';
		listNewAccounts[0].Subestado_del_paciente__c = 'No tolera';
		listNewAccounts[0].Fecha_de_baja__c = date.today();
        listNewAccounts[0].Fecha_de_obito__c = date.today();
        system.debug('-------------------Fecha de baja '+listNewAccounts[0].Fecha_de_baja__c);
		update listNewAccounts;

		listNewModuloPacientes[0].Estado__c = 'Inactivo';

		Test.startTest();
			update listNewModuloPacientes;
		Test.stopTest();

		Account cuenta = [SELECT Estado_de_paciente__c, Subestado_del_paciente__c FROM account WHERE id =:listNewAccounts[0].id];
		System.assertEquals('No tratamiento', cuenta.Estado_de_paciente__c);
		System.assertEquals('No tolera', cuenta.Subestado_del_paciente__c);
	}
	@IsTest
	static void whenModuloIsInactiveAccountEstadoFindetratamiento_AccountNotChange(){
		string tipo;
		newAccount();
		GetAccounts();
		
		for( Schema.PicklistEntry pickListVal : Modulo_de_paciente__c.Tipo__c.getDescribe().getPicklistValues()){
            if(pickListVal.getValue() != 'CUIDADO COMPLETO'){
				tipo = pickListVal.getValue();
				break;
			}
        } 
		
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').withTipo(tipo).build());
		insert listNewModuloPacientes;

		listNewAccounts[0].Estado_de_paciente__c = 'Fin de tratamiento';
		listNewAccounts[0].Subestado_del_paciente__c = 'Fallecido';
		listNewAccounts[0].Fecha_de_obito__c = date.today();
		update listNewAccounts;

		listNewModuloPacientes[0].Estado__c = 'Inactivo';

		Test.startTest();
			update listNewModuloPacientes;
		Test.stopTest();

		Account cuenta = [SELECT Estado_de_paciente__c, Subestado_del_paciente__c FROM account WHERE id =:listNewAccounts[0].id];
		System.assertEquals('Fin de tratamiento', cuenta.Estado_de_paciente__c);
		System.assertEquals('Fallecido', cuenta.Subestado_del_paciente__c);
	}
	
	@IsTest
	static void whenModuloIsInactiveButOtherModuloActive_AccountNotChange(){
		string tipo;
		newAccount();
		GetAccounts();
		
		for( Schema.PicklistEntry pickListVal : Modulo_de_paciente__c.Tipo__c.getDescribe().getPicklistValues()){
            if(pickListVal.getValue() != 'CUIDADO COMPLETO'){
				tipo = pickListVal.getValue();
				break;
			}
        } 
		
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').withTipo(tipo).build());
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').withTipo('CUIDADO COMPLETO').build());
		insert listNewModuloPacientes;
		
		listNewModuloPacientes[0].Estado__c = 'Inactivo';

		Test.startTest();
		update listNewModuloPacientes;
		Test.stopTest();

		Account cuenta = [SELECT Estado_de_paciente__c, Subestado_del_paciente__c FROM account WHERE id =:listNewAccounts[0].id];
		System.assertEquals('En tratamiento', cuenta.Estado_de_paciente__c);
		System.assertEquals('Tratamiento Efectivo', cuenta.Subestado_del_paciente__c);
	}

	@IsTest
	static void whenMDPIsInsertAccountIsUpdate(){
		newAccount();
		GetAccounts();

		Modulo__c testModulo = new modulo__c();
        testModulo.Name = 'Alergia';
        testModulo.N_de_Material__c = 123456;
        insert testModulo;

		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').withTipo('CUIDADO PERSONALIZADO').build());
		
		listNewModuloPacientes[0].Estado_de_modulo__c = 'Ingresado';
		listNewModuloPacientes[0].modulo__c= testModulo.id;

		Test.startTest();
		insert listNewModuloPacientes;
		Test.stopTest();

		Account cuenta = [
			SELECT Estado_de_paciente__c, Subestado_del_paciente__c ,Estado_del_ultimo_modulo__c,Modulo_activo__c,Modulo__c
			FROM account 
			WHERE id =:listNewAccounts[0].id
			LIMIT 1
			];

		System.assertEquals('Ingresado', cuenta.Estado_del_ultimo_modulo__c);
		System.assertEquals(listNewModuloPacientes[0].id, cuenta.Modulo_activo__c);
		System.assertEquals(testModulo.id, cuenta.Modulo__c);
	}



	static public void GetAccounts() {
		listNewAccounts = [SELECT id, Formulas_actuales__c FROM Account];
	}
	static public void newAccount(){
		listNewAccounts.add(Build.anAccountPacienteBestCare().withLastName('CuentaLastName').withCanalParaConsumidorBaby('Farmacias').withDNI('123456').build());
		insert listNewAccounts;
	}


	static public void CreateSimpleScheme() {

		listNewAccounts.add(Build.anAccountPacienteBestCare().withLastName('CuentaLastName').withCanalParaConsumidorBaby('Farmacias').withDNI('123456').build());
		insert listNewAccounts;

		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').build());
		insert listNewModuloPacientes;

		listNewProductos.add(Build.aProduct2().withName('ProductName-P128').withhProductoSAP(true).withProductoPara('Best Care').build());
		insert listNewProductos;

		listNewProductoModulo.add(
			Build.aProductodemodulo()
		    .withFormula(listNewProductos[0])
		    .withCantidad('1 Unidad')
		    .withModulodepaciente(listNewModuloPacientes[0]).build()
		);
		insert listNewProductoModulo;
        

		expectedResult = 'ProductName-P128, 1 Unidad';
	}

	static public void CreateSimpleSchemeMultiProducts() {

		listNewAccounts.add(Build.anAccountPacienteBestCare().withLastName('CuentaLastName').withCanalParaConsumidorBaby('Farmacias').withDNI('123456').build());
		insert listNewAccounts;

		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').build());
		insert listNewModuloPacientes;

		listNewProductos.add(Build.aProduct2().withName('ProductName-P128').withhProductoSAP(true).withProductoPara('Best Care').build());
		listNewProductos.add(Build.aProduct2().withName('ProductName-O256').withhProductoSAP(true).withProductoPara('Best Care').build());
		listNewProductos.add(Build.aProduct2().withName('ProductName-I512').withhProductoSAP(true).withProductoPara('Best Care').build());
		insert listNewProductos;

		listNewProductoModulo.add(
			Build.aProductodemodulo()
		    .withFormula(listNewProductos[0])
		    .withCantidad('2 Unidades')
		    .withModulodepaciente(listNewModuloPacientes[0]).build()
		);

		listNewProductoModulo.add(
			Build.aProductodemodulo()
		    .withFormula(listNewProductos[1])
		    .withCantidad('3 Unidades')
		    .withModulodepaciente(listNewModuloPacientes[0]).build()
		);

		listNewProductoModulo.add(
			Build.aProductodemodulo()
		    .withFormula(listNewProductos[2])
		    .withCantidad('4 Unidades')
		    .withModulodepaciente(listNewModuloPacientes[0]).build()
		);

		insert listNewProductoModulo;
		expectedResult = 'ProductName-P128, 2 Unidades' + '\r\n' + 'ProductName-O256, 3 Unidades' + '\r\n' + 'ProductName-I512, 4 Unidades';
	}

	static public void CreateSimpleSchemeMultiModulesAccount() {

		listNewAccounts.add(Build.anAccountPacienteBestCare().withLastName('CuentaLastName').withCanalParaConsumidorBaby('Farmacias').withDNI('123456').build());
		insert listNewAccounts;

		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').build());
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').build());
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').build());
		insert listNewModuloPacientes;

		listNewProductos.add(Build.aProduct2().withName('ProductName-P128').withhProductoSAP(true).withProductoPara('Best Care').build());
		insert listNewProductos;

		listNewProductoModulo.add(
			Build.aProductodemodulo()
		    .withFormula(listNewProductos[0])
		    .withCantidad('2 Unidades')
		    .withModulodepaciente(listNewModuloPacientes[0]).build()
		);

		listNewProductoModulo.add(
			Build.aProductodemodulo()
		    .withFormula(listNewProductos[0])
		    .withCantidad('3 Unidades')
		    .withModulodepaciente(listNewModuloPacientes[1]).build()
		);

		listNewProductoModulo.add(
			Build.aProductodemodulo()
		    .withFormula(listNewProductos[0])
		    .withCantidad('4 Unidades')
		    .withModulodepaciente(listNewModuloPacientes[2]).build()
		);

		insert listNewProductoModulo;
		expectedResult = 'ProductName-P128, 2 Unidades' + '\r\n' + 'ProductName-P128, 3 Unidades' + '\r\n' + 'ProductName-P128, 4 Unidades';
	}

	static public void CreateMultiScheme() {

		listNewAccounts.add(Build.anAccountPacienteBestCare().withLastName('CuentaLastName').withCanalParaConsumidorBaby('Farmacias').withDNI('123452436').build());
		listNewAccounts.add(Build.anAccountPacienteBestCare().withLastName('CuentaLastNameClear').withCanalParaConsumidorBaby('Farmacias').withDNI('12345644').build());
		insert listNewAccounts;

		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').build());
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[0]).withEstado('Activo').build());
		listNewModuloPacientes.add(Build.aModulodepaciente().withCuenta(listNewAccounts[1]).withEstado('Activo').build());
		insert listNewModuloPacientes;

		listNewProductos.add(Build.aProduct2().withName('ProductName-P128').withhProductoSAP(true).withProductoPara('Best Care').build());
		listNewProductos.add(Build.aProduct2().withName('ProductName-O256').withhProductoSAP(true).withProductoPara('Best Care').build());
		listNewProductos.add(Build.aProduct2().withName('ProductName-I512').withhProductoSAP(true).withProductoPara('Best Care').build());
		insert listNewProductos;

		listNewProductoModulo.add(
			Build.aProductodemodulo()
		    .withFormula(listNewProductos[0])
		    .withCantidad('2 Unidades')
		    .withModulodepaciente(listNewModuloPacientes[0]).build()
		);

		listNewProductoModulo.add(
			Build.aProductodemodulo()
		    .withFormula(listNewProductos[1])
		    .withCantidad('3 Unidades')
		    .withModulodepaciente(listNewModuloPacientes[0]).build()
		);

		listNewProductoModulo.add(
			Build.aProductodemodulo()
		    .withFormula(listNewProductos[2])
		    .withCantidad('4 Unidades')
		    .withModulodepaciente(listNewModuloPacientes[1]).build()
		);

		insert listNewProductoModulo;
		expectedResult = 'ProductName-O256, 3 Unidades' + '\r\n' + 'ProductName-P128, 2 Unidades' + '\r\n' + 'ProductName-I512, 4 Unidades';
	}
}