force-app/main/default/objects/Account/fields/Fecha_de_cambio_de_estado__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_cambio_de_estado__c</fullName>
    <label>Fecha de cambio de estado</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Subtipo__c.field-meta.xml
<CustomField>
    <fullName>Subtipo__c</fullName>
    <label>Subtipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activos</fullName>
            </value>
            <value>
                <fullName>Actualización de datos</fullName>
            </value>
            <value>
                <fullName>Actualización de Módulo</fullName>
            </value>
            <value>
                <fullName>Alta</fullName>
            </value>
            <value>
                <fullName>Alta con evaluación Medica</fullName>
            </value>
            <value>
                <fullName>Alta en bloque</fullName>
            </value>
            <value>
                <fullName>Calidad</fullName>
            </value>
            <value>
                <fullName>Cancelacion de Envio</fullName>
            </value>
            <value>
                <fullName>Compras en NEC</fullName>
            </value>
            <value>
                <fullName>Documentacion</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Envio de Activos</fullName>
            </value>
            <value>
                <fullName>Envio de Insumos</fullName>
            </value>
            <value>
                <fullName>Envio de Productos</fullName>
            </value>
            <value>
                <fullName>Estado de Envíos</fullName>
            </value>
            <value>
                <fullName>Modulo BC</fullName>
            </value>
            <value>
                <fullName>Nuevo Paciente</fullName>
            </value>
            <value>
                <fullName>ONG Acceso</fullName>
            </value>
            <value>
                <fullName>Productos</fullName>
            </value>
            <value>
                <fullName>Profesionales BC</fullName>
            </value>
            <value>
                <fullName>Profesionales de la salud</fullName>
            </value>
            <value>
                <fullName>Renovación</fullName>
            </value>
            <value>
                <fullName>Renovación en bloque</fullName>
            </value>
            <value>
                <fullName>Reporte de Crisis</fullName>
            </value>
            <value>
                <fullName>Reporte de Incidencia</fullName>
            </value>
            <value>
                <fullName>Respuestas WhatsApp</fullName>
            </value>
            <value>
                <fullName>Retiro de Activos</fullName>
            </value>
            <value>
                <fullName>Seguimiento</fullName>
            </value>
            <value>
                <fullName>Seguimiento no renovación</fullName>
            </value>
            <value>
                <fullName>Servicios Profesionales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Consulta.recordType-meta.xml
<RecordType>
    <fullName>Consulta</fullName>
    <active>true</active>
    <businessProcess>General</businessProcess>
    <label>Consulta</label>
</RecordType>

force-app/main/default/classes/BatchCrearCasosDeSeguimiento_Test.cls
@isTest
public class BatchCrearCasosDeSeguimiento_Test {

    
    @isTest
    static void SiSeCumplenLasCondicionesEnCuentaSeDebeInsertarUnCasoDeSeguimiento() {   
                List<Account> accList = new List<Account>();
        for (Integer i=0;i<5;i++) {
            accList.add(Build.anAccountPacienteBestCare()
                        .withLastName('BestCare '+i)
                        .withAreaTerapeutica('Alergia')
                        .withEstadoDePaciente('En seguimiento')
                        .withRelacionamiento('Alto')
                        .build()
                       );
        }
        insert accList;

        for(Account acc : accList){
            acc.Fecha_de_cambio_de_estado__c = System.today().addDays(-5);
        }
        update accList;
        
  		Test.startTest();
        BatchCrearCasosDeSeguimiento batchToExecute = new BatchCrearCasosDeSeguimiento();
        Id batchId = Database.executeBatch(batchToExecute);
        Test.stopTest();
        
        List<Case> casesDb =[
            SELECT id,Subtipo__c
            FROM Case
        ];
        
        System.assertEquals(5, casesDb.size());
        System.assertEquals('Seguimiento no renovacion', casesDb[0].Subtipo__c);
    }
    @isTest
    static void SiyaTieneUnCasoDeSeguimientoNoDebeGenerarleOtro() {
        
        Account anAccount = Build.anAccountPacienteBestCare()
            .withLastName('BestCare')
            .withAreaTerapeutica('Alergia')
            .withEstadoDePaciente('En seguimiento')
            .withRelacionamiento('Alto')
            .build();
        
        insert anAccount;
        
        Case aCase = Build.aCase()
            .forAccount(anAccount)
            .withType('Consulta')
            .withStatus('Abierto')
            .withSubtipo('Seguimiento no renovacion')
            .build();

        insert aCase;
        
        Test.startTest();
        anAccount.Fecha_de_cambio_de_estado__c = System.today().addDays(-5);
        
        update anAccount;
        BatchCrearCasosDeSeguimiento batchToExecute = new BatchCrearCasosDeSeguimiento();
        Id batchId = Database.executeBatch(batchToExecute);
        Test.stopTest();
        
        List<Case> casesDb =[
            SELECT id,Subtipo__c
            FROM Case
        ];

        System.assertEquals(1, casesDb.size());
    }
}