force-app/main/default/objects/Account/fields/ID_de_paciente__c.field-meta.xml
<CustomField>
    <fullName>ID_de_paciente__c</fullName>
    <displayFormat>P-{000000}</displayFormat>
    <externalId>true</externalId>
    <label>ID de paciente</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/NIC_Envio__c/NIC_Envio__c.object-meta.xml
<CustomObject>
    <label>NIC Envío</label>
    <nameField>
        <displayFormat>ENV - {0000000}</displayFormat>
        <label>Nombre de Envío</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIC Envíos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NIC_Envio__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NIC Envíos</relationshipLabel>
    <relationshipName>NIC_Envios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NIC_Envio__c/fields/Id_de_cuenta_SAP__c.field-meta.xml
<CustomField>
    <fullName>Id_de_cuenta_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Id de cuenta SAP</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NICTriggerHelper.cls
public without sharing class NICTriggerHelper {
    
    public static void relateNICWithAccount(List<NIC_Envio__c> nics){
        List<String> nicSAPIds = new List<String>();
        Map<String,Id> sapIdWhitAccounts = new Map<String,Id>();
        List<NIC_Envio__c> nicsToUpdate = new List<NIC_Envio__c>();
        
        for(NIC_Envio__c aNic : nics){
            if(aNic.Id_de_cuenta_SAP__c != null && aNic.Id_de_cuenta_SAP__c.length()>=8 && aNic.Id_de_cuenta_SAP__c.substring(0, 2) == 'P-'){
                String splitedId =aNic.Id_de_cuenta_SAP__c.substring(0, 8);
                nicSAPIds.add(splitedId);
            }
        }
        List<Account> accounts = [ 
            SELECT Id,ID_de_paciente__c
            FROM Account
            WHERE ID_de_paciente__c IN :nicSAPIds 
        ];
        
        for(Account anAccount : accounts){
            sapIdWhitAccounts.put(anAccount.ID_de_paciente__c, anAccount.id);
        }
        if(!accounts.isEmpty()){
            for(NIC_Envio__c aNic : nics){
                if(aNic.Id_de_cuenta_SAP__c.length()>=8 && aNic.Id_de_cuenta_SAP__c.substring(0, 2) == 'P-'){
                    String splitedId =aNic.Id_de_cuenta_SAP__c.substring(0, 8);
                    Id relatedAccountId = sapIdWhitAccounts.get(splitedId);
                    if(relatedAccountId!=null){
                        aNic.Cuenta__c= relatedAccountId;
                        nicsToUpdate.add(aNic);
                    }
                }
            }
        }
    }
}