force-app/main/default/objects/Account/fields/Institucion__c.field-meta.xml
<CustomField>
    <fullName>Institucion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Institución</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Institución</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Profesionales de la salud</relationshipLabel>
    <relationshipName>Profesionales_de_la_salud2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Institucion.recordType-meta.xml
<RecordType>
    <fullName>Institucion</fullName>
    <active>true</active>
    <label>Institución</label>
</RecordType>

force-app/main/default/objects/Contact/fields/VisMed_DNI__c.field-meta.xml
<CustomField>
    <fullName>VisMed_DNI__c</fullName>
    <label>DNI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/User/fields/VisMed_ContrasenaApp__c.field-meta.xml
<CustomField>
    <fullName>VisMed_ContrasenaApp__c</fullName>
    <label>Contraseña App</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/VisMed_Contacto_Cuenta_Usuario__c.object-meta.xml
<CustomObject>
    <description>Relacion de APM con el profesional y su lugar de trabajo</description>
    <label>Fichero</label>
    <nameField>
        <displayFormat>SEG-{0000}</displayFormat>
        <label>Seguimiento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ficheros</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Aprobador_Final__c.field-meta.xml
<CustomField>
    <fullName>Aprobador_Final__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aprobador Final</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ficheros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Baja Temporal</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Institucion__c.field-meta.xml
<CustomField>
    <fullName>Institucion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Institución</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Institución, Consultorio, Farmacia, Institución</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ficheros (Institución)</relationshipLabel>
    <relationshipName>Contacto_Cuenta_Usuario</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Seguimientos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/VisMed_Segmentacion__c.object-meta.xml
<CustomObject>
    <label>Segmentación</label>
    <nameField>
        <displayFormat>Segmentacion-{0000}</displayFormat>
        <label>Segmentación Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Institucion__c.field-meta.xml
<CustomField>
    <fullName>Institucion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Institucion</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segmentaciones (Institucion)</relationshipLabel>
    <relationshipName>Segmentacion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profesional de la Salud, Otro Profesional</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segmentaciones</relationshipLabel>
    <relationshipName>Segmentaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/recordTypes/Adultos.recordType-meta.xml
<RecordType>
    <fullName>Adultos</fullName>
    <active>false</active>
    <label>Adultos</label>
</RecordType>

force-app/main/default/objects/VisMed_Segmentacion__c/recordTypes/Adultos_General_Institucion.recordType-meta.xml
<RecordType>
    <fullName>Adultos_General_Institucion</fullName>
    <active>true</active>
    <label>Adultos General Institucion</label>
</RecordType>

force-app/main/default/classes/SubmitApproSeguimientoTriggerHelperTest.cls
@isTest public with sharing class SubmitApproSeguimientoTriggerHelperTest {
    @testSetup
    private static void testSetup() {
    
        Account account = Build.anAccount()
        .withName('Institucion')					
        .build();
    
        insert account;
        
        Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Visitador Medico').getRecordTypeId();
        Contact aContactOne = Build.aContact()
            .withAccount(account)
            .withFirstName('NameOne')
            .withLastName('LastnameOne')
            .build();
        
        aContactOne.RecordTypeId = recordTypeId;
        aContactOne.VisMed_DNI__c = '23555777';
        insert aContactOne;
        Contact aContactTwo = Build.aContact()
            .withAccount(account)
            .withFirstName('NameTwo')
            .withLastName('LastnameTwo')
            .build();
        
        
        aContactTwo.RecordTypeId = recordTypeId;
        aContactTwo.VisMed_DNI__c = '23234324';
        insert aContactTwo;
    
        Profile perfil = [
            SELECT Id 
            FROM Profile 
            WHERE Name = 'APM' 
            LIMIT 1
        ];
    
        User userApproval = Build.aUser()
            .withUsername(
                'newuser'+String.valueOf(System.now().getTime() + (Math.random() * 10))+'@testorg.com'
            )
            .withContactId(aContactOne)
            .withLastName('Approval')
            .withEmail('approval@xappia.com')
            .withAlias('appro')
            .withTimeZoneSidKey('America/Argentina/Buenos_Aires')
            .withLocaleSidKey('es_AR')
            .withCommunityNickname('approval.xappia')
            .withEmailEncodingKey('ISO-8859-1')
            .withProfileId(perfil.Id)
            .withLanguageLocaleKey('es')
            .build();
    
        userApproval.IsActive = true;
        userApproval.VisMed_ContrasenaApp__c = 'appro';
    
        insert userApproval;
        User userTest = Build.aUser()
            .withUsername(
                'newuser'+String.valueOf(System.now().getTime() + (Math.random() * 10))+'@testorg.com'
            )
            .withContactId(aContactTwo)
            .withLastName('Contacto2')
            .withEmail('contacto1@xappia.com')
            .withAlias('contact2')
            .withTimeZoneSidKey('America/Argentina/Buenos_Aires')
            .withLocaleSidKey('es_AR')
            .withCommunityNickname('prueba1.xappia')
            .withEmailEncodingKey('ISO-8859-1')
            .withProfileId(perfil.Id)
            .withLanguageLocaleKey('es')
            .build();
    
        userTest.IsActive = true;
        userTest.VisMed_ContrasenaApp__c = 'Test';
        userTest.ManagerId = userApproval.Id;
        userTest.DelegatedApproverId = userApproval.Id;
    
        insert userTest;
    
        Id recordTypeProfesional = [SELECT Id, Name, SobjectType,IsPersonType 
        FROM RecordType 
        WHERE SobjectType='Account' AND IsPersonType=True AND Name = 'Profesional de la Salud'].Id;
        Account aPersonAccount = Build.aPersonalAccount()
            .withFirstName('Profesional')
            .withProfesionalActivo(false)
            .build();
        aPersonAccount.RecordTypeId = recordTypeProfesional;
        insert aPersonAccount;
        Id recordTypeAlergia = Schema.SObjectType.VisMed_Segmentacion__c.getRecordTypeInfosByDeveloperName().get('Adultos_General_Institucion').getRecordTypeId();
        VisMed_Segmentacion__c segmentacion = new VisMed_Segmentacion__c(
            Profesional__c = aPersonAccount.id,
            Institucion__c = account.id,
            Frecuencia__c = 1.00,            
            RecordTypeId = recordTypeAlergia
        );
        insert segmentacion;
        VisMed_Contacto_Cuenta_Usuario__c seguimiento = Build.aVisMedContactCuentaUsuarioBuilder()
            .withAPM(aContactTwo)
            .withProfesional(aPersonAccount)
            .withInstitucion(account)
            .withEstado('Pendiente')
            .withSegmentaPor('Adultos General Institucion')
            .build();
        seguimiento.Aprobador_Final__c = userTest.Id;    
        insert seguimiento;
    }
   @IsTest
   static void whenSeguimientoIsInsertedMustSubmitApprovalProcess(){        
        VisMed_Contacto_Cuenta_Usuario__c seg = [
            SELECT Id, Estado__c 
            FROM VisMed_Contacto_Cuenta_Usuario__c
            WHERE Estado__c = 'Pendiente'
        ];
        Test.startTest();
            Boolean locked = Approval.isLocked(seg.Id);
        Test.stopTest();
        System.assertEquals(true, locked, 'Error al crear la aprobacion');
   }
   @IsTest
   static void whenSeguimientoIsInsertedMustSubmitApprovalProcessWithStatusPending(){
        Contact contact = [
            SELECT Id
            FROM Contact
            WHERE FirstName = 'NameTwo'
        ];
        Account aPersonAccount = [
            SELECT Id
            FROM Account
            WHERE FirstName = 'Profesional'
        ];
        Account account = [
            SELECT Id
            FROM Account
            WHERE Name = 'Institucion'
        ];

        User userTest = [
            SELECT Id
            FROM User
            WHERE Alias = 'contact2'
        ];

        VisMed_Contacto_Cuenta_Usuario__c seguimiento = Build.aVisMedContactCuentaUsuarioBuilder()
            .withAPM(contact)
            .withProfesional(aPersonAccount)
            .withInstitucion(account)           
            .withSegmentaPor('Adultos General Institucion')
            .build();
        seguimiento.Aprobador_Final__c = userTest.Id;    
        insert seguimiento;

        seguimiento.Estado__c = 'Pendiente';
        Test.startTest();
            Update seguimiento;            
        Test.stopTest();

        ProcessInstance existingApprovals = [SELECT Id, TargetObjectId
                                                FROM ProcessInstance 
                                                WHERE TargetObjectId = :seguimiento.Id
                                                AND Status = 'Pending'];
        System.debug(existingApprovals);
        System.assertEquals(seguimiento.Id, existingApprovals.TargetObjectId, 'Error al crear la aprobacion');
   }
}