force-app/main/default/objects/Account/fields/Institucion__c.field-meta.xml
<CustomField>
    <fullName>Institucion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Institución</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Institución</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Profesionales de la salud</relationshipLabel>
    <relationshipName>Profesionales_de_la_salud2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Motivo_de_la_Baja__c.field-meta.xml
<CustomField>
    <fullName>Motivo_de_la_Baja__c</fullName>
    <label>Motivo de la Baja</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Profesional_Activo__c.field-meta.xml
<CustomField>
    <fullName>Profesional_Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Profesional Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VisMed_Bajas__c/VisMed_Bajas__c.object-meta.xml
<CustomObject>
    <description>Objeto para gestionar las bajas de registros</description>
    <label>Bajas</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bajas Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bajas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Bajas__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Aprobada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Bajas__c/fields/Fecha_de_Desactivacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Desactivacion__c</fullName>
    <label>Fecha de Desactivacion</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_Bajas__c/fields/Fecha_de_Reactivacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Reactivacion__c</fullName>
    <label>Fecha de Reactivación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_Bajas__c/fields/Institucion__c.field-meta.xml
<CustomField>
    <fullName>Institucion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Institucion</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Consultorio, Farmacia, Institución</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bajas (Institucion)</relationshipLabel>
    <relationshipName>Baja_de_Domicilio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Bajas__c/fields/Motivo_de_la_Baja__c.field-meta.xml
<CustomField>
    <fullName>Motivo_de_la_Baja__c</fullName>
    <label>Motivo de la Baja</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No ejerce más la profesión</fullName>
            </value>
            <value>
                <fullName>Fallecimiento</fullName>
            </value>
            <value>
                <fullName>Bajo Potencial</fullName>
            </value>
            <value>
                <fullName>No recibe APM</fullName>
            </value>
            <value>
                <fullName>Enfermedad</fullName>
            </value>
            <value>
                <fullName>Maternidad</fullName>
            </value>
            <value>
                <fullName>Viaje</fullName>
            </value>
            <value>
                <fullName>Transferido a otro Visitador</fullName>
            </value>
            <value>
                <fullName>No trabaja más en la institución</fullName>
            </value>
            <value>
                <fullName>Baja Temporal</fullName>
                <isActive>false</isActive>
                <label>Baja Temporal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Bajas__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bajas</relationshipLabel>
    <relationshipName>Bajas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Bajas__c/fields/VisMed_APM__c.field-meta.xml
<CustomField>
    <fullName>VisMed_APM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>APM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Visitador Medico</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bajas Registradas</relationshipLabel>
    <relationshipName>Bajas_Registradas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchVisMedBaja.cls
public class BatchVisMedBaja implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Date hoy = Date.today();
        String query = 
            'SELECT Id, Fecha_de_Reactivacion__c, Fecha_de_Desactivacion__c, Profesional__c, Motivo_de_la_Baja__c, VisMed_APM__c, Institucion__c  ' +
            'FROM VisMed_Bajas__c ' +
            'WHERE (Fecha_de_Reactivacion__c = :hoy OR Fecha_de_Desactivacion__c = :hoy) AND Estado__c = \'Aprobada\'';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<VisMed_Bajas__c> visitasMedBajas) {
        List<VisMed_Bajas__c> visitasMedBajasToDeactivate = new List<VisMed_Bajas__c>();
        List<Id> accountsToReactivateIds = new List<Id>();
        List<Id> apmsFicheros = new List<Id>();
        List<VisMed_Bajas__c> bajasToActivate = new List<VisMed_Bajas__c>();
        Date hoy = date.today();

        for (VisMed_Bajas__c visitaMedBajas : visitasMedBajas) {
            //Reactivation
            if (visitaMedBajas.Fecha_de_Reactivacion__c == hoy) {
                accountsToReactivateIds.add(visitaMedBajas.Profesional__c);
                apmsFicheros.add(visitaMedBajas.VisMed_APM__c);
                bajasToActivate.add(visitaMedBajas);
            }
            //Deactivation
            if (visitaMedBajas.Fecha_de_Desactivacion__c == hoy) {
                visitasMedBajasToDeactivate.add(visitaMedBajas); 
            }
        }

        //Deactivation
        if (visitasMedBajasToDeactivate.size() > 0) {
            BajasTriggerHelper.desvincularProfesional(visitasMedBajasToDeactivate);
        }
        //Reactivation
        System.debug('Activar');
        System.debug(accountsToReactivateIds);
        if (accountsToReactivateIds.size() > 0) {
            List<Account> accountsToUpdate = [
                SELECT Id, Profesional_Activo__c
                FROM Account
                WHERE Id IN :accountsToReactivateIds
            ];
            
            for (Account account : accountsToUpdate) {
                account.Profesional_Activo__c = true;
            }

            update accountsToUpdate;
            BajasTriggerHelper.actualizarSeguimiento(bajasToActivate,'Activo', false);
        }
    }

    public void finish(Database.BatchableContext BC) {
        // execute any post-processing operationsjaja
    }
}