force-app/main/default/objects/Account/fields/KOL__c.field-meta.xml
<CustomField>
    <fullName>KOL__c</fullName>
    <label>KOL</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sin Asignar</fullName>
            </value>
            <value>
                <fullName>KOL Ped</fullName>
            </value>
            <value>
                <fullName>KOL Nicho</fullName>
            </value>
            <value>
                <fullName>Rising Star</fullName>
            </value>
            <value>
                <fullName>Profesional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Promedio_de_pacientes_Nicho__c.field-meta.xml
<CustomField>
    <fullName>Promedio_de_pacientes_Nicho__c</fullName>
    <label>Promedio de pacientes Nicho</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sin Asignar</fullName>
                <default>true</default>
                <label>Sin Asignar</label>
            </value>
            <value>
                <fullName>0 pacientes</fullName>
            </value>
            <value>
                <fullName>Entre 1 y 5</fullName>
            </value>
            <value>
                <fullName>Más de 5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/VisMed_Segmentacion__c.object-meta.xml
<CustomObject>
    <label>Segmentación</label>
    <nameField>
        <displayFormat>Segmentacion-{0000}</displayFormat>
        <label>Segmentación Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <formula>IF(
  OR(
    RecordType.Name =&apos;Metabolicos&apos;,
    RecordType.Name =&apos;Epilepsia&apos;,
    RecordType.Name =&apos;Metabolicos_y_Epilepsia&apos;
  ),
  Categoria_Nicho__c,
  IF(
    OR(
      RecordType.Name =&apos;Alergia&apos;,
      RecordType.Name =&apos;Pediatricos&apos;,
      RecordType.Name =&apos;Pediatricos General&apos;
    ),
    Categoria_Ped_Aler__c,
    Categoria_Nicho__c
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Categoria</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profesional de la Salud, Otro Profesional</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segmentaciones</relationshipLabel>
    <relationshipName>Segmentaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/recordTypes/Metabolicos.recordType-meta.xml
<RecordType>
    <fullName>Metabolicos</fullName>
    <active>true</active>
    <label>Metabolicos</label>
</RecordType>

force-app/main/default/objects/VisMed_Segmentacion__c/recordTypes/Pediatricos.recordType-meta.xml
<RecordType>
    <fullName>Pediatricos</fullName>
    <active>true</active>
    <label>Pediatricos</label>
</RecordType>

force-app/main/default/classes/SegmentacionTriggerHelperTest.cls
@isTest public with sharing class SegmentacionTriggerHelperTest {
   @testSetup
   private static void testSetup() {
    Id recordTypeProfesional = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Profesional_de_la_Salud').getRecordTypeId();
    Account profesional = Build.aPersonalAccount()
    .withFirstName('Profesional')
    .withProfesionalActivo(true)
    .build();
    profesional.RecordTypeId = recordTypeProfesional;

    insert profesional;
   }
   
   @isTest
   private static void cuandoSeCreaSegmentacionMetabolicosSeDebeSetearLaCategoriaYLaFrecuencia() {
    // Test data setup
    Account profesional = [ 
        SELECT Id, KOL__c
        FROM Account
        WHERE FirstName = 'Profesional'
        LIMIT 1
    ]; 

    profesional.KOL__c = 'KOL Nicho	';
    profesional.Promedio_de_pacientes_Nicho__c = 'Más de 5';
    update profesional;
    Id tipoSegmentacion = Schema.SObjectType.VisMed_Segmentacion__c.getRecordTypeInfosByName().get('Metabolicos').getRecordTypeId();
    VisMed_Segmentacion__c segmentacionNueva = new VisMed_Segmentacion__c(
            recordTypeId = tipoSegmentacion,
            Profesional__c = profesional.Id
        );
    // Actual test
    Test.startTest();
    insert segmentacionNueva;
    Test.stopTest();
    
    // Asserts
    VisMed_Segmentacion__c segmentacionToCompare = [
        SELECT Id, Frecuencia__c, Categoria__c
        FROM VisMed_Segmentacion__c
        WHERE Id = :segmentacionNueva.Id
    ];
    System.assertEquals('KOL', segmentacionToCompare.Categoria__c, 'Error al crear categoria');
    System.assertEquals(2.50, segmentacionToCompare.Frecuencia__c, 'Error al crear frecuencia');
   }
   @isTest
   private static void cuandoSeCreaSegmentacionPediatricosGeneralSeDebeSetearLaCategoriaYLaFrecuencia() {
    // Test data setup
    Account profesional = [ 
        SELECT Id 
        FROM Account
        WHERE FirstName = 'Profesional'
        LIMIT 1
    ]; 
    
    Id tipoSegmentacion = Schema.SObjectType.VisMed_Segmentacion__c.getRecordTypeInfosByName().get('Pediatricos General').getRecordTypeId();
    VisMed_Segmentacion__c segmentacionNueva = new VisMed_Segmentacion__c(
            recordTypeId = tipoSegmentacion,
            Profesional__c = profesional.Id
        );
    // Actual test
    Test.startTest();
    insert segmentacionNueva;
    Test.stopTest();
    
    // Asserts
    VisMed_Segmentacion__c segmentacionToCompare = [
        SELECT Id, Frecuencia__c, Categoria__c
        FROM VisMed_Segmentacion__c
        WHERE Id = :segmentacionNueva.Id
    ];
    System.assertEquals('D', segmentacionToCompare.Categoria__c, 'Error al crear categoria');
    System.assertEquals(0.50, segmentacionToCompare.Frecuencia__c, 'Error al crear frecuencia');
   }
}