force-app/main/default/objects/Account/fields/KOL__c.field-meta.xml
<CustomField>
    <fullName>KOL__c</fullName>
    <label>KOL</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sin Asignar</fullName>
            </value>
            <value>
                <fullName>KOL Ped</fullName>
            </value>
            <value>
                <fullName>KOL Nicho</fullName>
            </value>
            <value>
                <fullName>Rising Star</fullName>
            </value>
            <value>
                <fullName>Profesional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Institucion.recordType-meta.xml
<RecordType>
    <fullName>Institucion</fullName>
    <active>true</active>
    <label>Institución</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Sub_Equipo__c.field-meta.xml
<CustomField>
    <fullName>Sub_Equipo__c</fullName>
    <label>Sub Equipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Equipo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/VisMed_DNI__c.field-meta.xml
<CustomField>
    <fullName>VisMed_DNI__c</fullName>
    <label>DNI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Visitador_medico.recordType-meta.xml
<RecordType>
    <fullName>Visitador_medico</fullName>
    <active>true</active>
    <label>Visitador médico</label>
</RecordType>

force-app/main/default/objects/Dan360_Efectividad__c/Dan360_Efectividad__c.object-meta.xml
<CustomObject>
    <description>Objeto creado para el registro y calculo de las efectividades del APM por mes.</description>
    <label>Efectividad</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Efectividad Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Efectividades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/VisMed_Ciclo__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Ciclo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciclo</label>
    <referenceTo>VisMed_Ciclo__c</referenceTo>
    <relationshipLabel>Efectividades</relationshipLabel>
    <relationshipName>Efectividades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Segmenta_Por__c.field-meta.xml
<CustomField>
    <fullName>Segmenta_Por__c</fullName>
    <label>Segmenta Por</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Metabolicos</fullName>
            </value>
            <value>
                <fullName>Epilepsia</fullName>
            </value>
            <value>
                <fullName>Metabolicos y Epilepsia</fullName>
            </value>
            <value>
                <fullName>Pediatricos</fullName>
            </value>
            <value>
                <fullName>Alergia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sub_Equipo__c.field-meta.xml
<CustomField>
    <fullName>Sub_Equipo__c</fullName>
    <label>Sub Equipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Equipo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/VisMed_ContrasenaApp__c.field-meta.xml
<CustomField>
    <fullName>VisMed_ContrasenaApp__c</fullName>
    <label>Contraseña App</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/VisMed_Ciclo__c/VisMed_Ciclo__c.object-meta.xml
<CustomObject>
    <label>Ciclo</label>
    <nameField>
        <label>Ciclo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Ciclo__c/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/VisMed_Contacto_Cuenta_Usuario__c.object-meta.xml
<CustomObject>
    <description>Relacion de APM con el profesional y su lugar de trabajo</description>
    <label>Fichero</label>
    <nameField>
        <displayFormat>SEG-{0000}</displayFormat>
        <label>Seguimiento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ficheros</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Actualizar_Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Actualizar_Frecuencia__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo utilizado por el batch : BatchSetFrecuencia. Indica si hay que actualizar la frencuencia el ciclo siguiente.</description>
    <label>Actualizar Frecuencia</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Baja Temporal</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Estado_de_aprobacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_aprobacion__c</fullName>
    <label>Estado de aprobacion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprobada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Fecha_de_Aprobacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Aprobacion__c</fullName>
    <label>Fecha de Aprobación</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Predeterminada__c.field-meta.xml
<CustomField>
    <fullName>Predeterminada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Segmenta_Anterior__c.field-meta.xml
<CustomField>
    <fullName>Segmenta_Anterior__c</fullName>
    <label>Segmenta Anterior</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Segmenta_Por__c.field-meta.xml
<CustomField>
    <fullName>Segmenta_Por__c</fullName>
    <label>Segmenta Por</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Segmenta_Por</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Segmenta_Por.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Adultos General Institucion</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos General Comunidad</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos Oncologia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos y Epilepsia</fullName>
    </customValue>
    <customValue>
        <fullName>Pediatricos General</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia</fullName>
    </customValue>
    <masterLabel>Segmenta Por</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sub_Equipo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Adultos Interior</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos Oncologia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos</fullName>
    </customValue>
    <customValue>
        <fullName>Dieta</fullName>
    </customValue>
    <customValue>
        <fullName>Pediatricos General</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos AMBA</fullName>
    </customValue>
    <customValue>
        <fullName>Metabólicos y Dieta</fullName>
    </customValue>
    <customValue>
        <fullName>Nicho MSL</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos General</fullName>
        <isActive>false</isActive>
        <label>Adultos General</label>
    </customValue>
    <masterLabel>Sub Equipo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchSetFrecuenciaTest.cls
@isTest public with sharing class BatchSetFrecuenciaTest {
    @TestSetup
	public static void makeData() {
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile profile1 = [Select Id from Profile where Name = 'System Administrator' or name = 'Administrador del sistema' ];
    
        User userOwner = Build.aUser()
                .withUsername(
                    'newuser'+String.valueOf(System.now().getTime() + (Math.random() * 10))+'@testorg.com'
                )               
                .withEmail('owner@xappia.com')
                .withAlias('owner')
                .withLastName('Owner')
                .withTimeZoneSidKey('America/Argentina/Buenos_Aires')
                .withLocaleSidKey('es_AR')
                .withCommunityNickname('prueba2.xappia')
                .withEmailEncodingKey('ISO-8859-1')
                .withProfileId(profile1.Id)
                .withUserRoleId(portalRole)				
                .withLanguageLocaleKey('es')
                .build();           
        userOwner.ManagerId = UserInfo.getUserId();
        userOwner.IsActive = true;
        userOwner.VisMed_ContrasenaApp__c = 'TestOwner';
        insert userOwner;
    
        System.runAs(userOwner){
            Account institucion = Build.anAccount()
                .withName('InstitucionTest')
                .build();
            insert institucion;

            Account institucion2 = Build.anAccount()
            .withName('InstitucionTest2')
            .build();
            insert institucion2;
                   
            Id recordTypeVisitadorMedico = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Visitador_Medico').getRecordTypeId();
            Contact apm = Build.aContactVisitadorMedico()
            .withAccount(institucion)            
            .build();
            apm.VisMed_DNI__c = '22222333';
            apm.RecordTypeId = recordTypeVisitadorMedico;
            apm.Sub_Equipo__c = 'Metabolicos';
            insert apm;
                
            Profile perfilApm = [
            SELECT Id 
            FROM Profile 
            WHERE Name = 'APM' 
            LIMIT 1
            ];
            User userTest = Build.aUser()
            .withUsername(
                'newuser'+String.valueOf(System.now().getTime() + (Math.random() * 10))+'@testorg.com'
            )
            .withContactId(apm)
            .withLastName('Contacto1')
            .withEmail('contacto1@xappia.com')
            .withAlias('contact1')
            .withTimeZoneSidKey('America/Argentina/Buenos_Aires')
            .withLocaleSidKey('es_AR')
            .withCommunityNickname('prueba1.xappia')
            .withEmailEncodingKey('ISO-8859-1')
            .withProfileId(perfilApm.Id)
            .withLanguageLocaleKey('es')
            .build();

            userTest.IsActive = true;
            userTest.VisMed_ContrasenaApp__c = 'Test';
            userTest.ManagerId = userOwner.Id;
            userTest.DelegatedApproverId = userOwner.Id;

            insert userTest;
                
            Date today = Date.today();
            VisMed_Ciclo__c ciclo = Build.aCiclo()
            .withFechaInicio(today.toStartOfMonth())
            .withFechaFin(today.toStartOfMonth().addMonths(1).addDays(-1))
            .build();
            insert ciclo;

            Id recordTypeProfesional = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Profesional_de_la_Salud').getRecordTypeId();
            System.debug(recordTypeProfesional);
                        
            Account profesional = Build.aPersonalAccount()
            .withFirstName('Profesional')           
            .build();
            profesional.LastName = 'Test';
            profesional.RecordTypeId = recordTypeProfesional;
            insert profesional;
            Account profesional2 = Build.aPersonalAccount()
            .withFirstName('Profesional2')           
            .build();
            profesional2.LastName = 'Test2';
            Profesional2.KOL__c = 'KOL Nicho';
            profesional2.RecordTypeId = recordTypeProfesional;
            insert profesional2;
        
            Dan360_Efectividad__c efectividad = Build.aDan360Efectividad()
            .withVisMedAPM(apm)
            .withVisMedCiclo(ciclo)
            .build();
            efectividad.Fecha_de_inicio__c = Date.today().toStartOfMonth();
            efectividad.Fecha_de_Fin__c = Date.today().toStartOfMonth().addMonths(1).addDays(-1);
            insert efectividad;

            VisMed_Contacto_Cuenta_Usuario__c seg = Build.aVisMedContactCuentaUsuarioBuilder()
                .withAPM(apm)
                .withInstitucion(institucion)
                .withProfesional(profesional) 
                .withSegmentaPor('Alergia')               
                .build();
            seg.Predeterminada__c = true;            
            seg.Estado__c = 'Activo';
            seg.Actualizar_Frecuencia__c = true;         
            insert seg;

            VisMed_Contacto_Cuenta_Usuario__c seg2 = Build.aVisMedContactCuentaUsuarioBuilder()
                .withAPM(apm)
                .withInstitucion(institucion2)
                .withProfesional(profesional2)
                .withSegmentaPor('Metabolicos')                
                .build();
            seg2.Estado_de_aprobacion__c = 'Aprobada';
            seg2.Estado__c = 'Activo';
            seg2.Actualizar_Frecuencia__c = true;      
            insert seg2;
        }
    }
    @isTest
    private static void whenExecuteBatchSetFrecuenciaMustUpdateFrecuenciaAndCategiriaOfFicherosUpdatedTheLastMonth() {
        // Test data setup
        List<VisMed_Contacto_Cuenta_Usuario__c> ficherosToUpdate = new List<VisMed_Contacto_Cuenta_Usuario__c>();
        List<VisMed_Contacto_Cuenta_Usuario__c> ficheros = [
            SELECT ID, Segmenta_Por__c, Fecha_de_Aprobacion__c
            FROM VisMed_Contacto_Cuenta_Usuario__c
            ];
        Set<Id> ficheroId = new Set<Id>();
        System.debug(ficheros.size());
        DateTime fechaAprobacion = DateTime.now().addMonths(-1);
        for (VisMed_Contacto_Cuenta_Usuario__c fichero : ficheros) {
            fichero.Segmenta_Por__c = 'Pediatricos General';            
            Test.setCreatedDate(fichero.Id, fechaAprobacion);
            ficherosToUpdate.add(fichero);
            ficheroId.add(fichero.Id);

        }
        update ficherosToUpdate;
        // Actual test
        Test.startTest();
        BatchSetFrecuencia batch = new BatchSetFrecuencia();
        Database.executeBatch(batch);
        Test.stopTest();
        
        List<VisMed_Contacto_Cuenta_Usuario__c> ficherosToCompare = [
            SELECT ID, Segmenta_Por__c, Segmenta_Anterior__c, Frecuencia__c, Categoria__c, Fecha_de_Aprobacion__c, Actualizar_Frecuencia__c
            FROM VisMed_Contacto_Cuenta_Usuario__c
            WHERE id in :ficheroId
            ];
        System.debug(ficherosToCompare);
        // Asserts
        System.assertEquals(0.5, ficherosToCompare[0].Frecuencia__c, 'Error al  obtener frecuencia');
        System.assertEquals('D', ficherosToCompare[0].Categoria__c, 'Error al  obtener categoria');
        System.assertEquals('Pediatricos General', ficherosToCompare[0].Segmenta_Anterior__c, 'Error al  setear segmenta anterior');
        System.assertEquals(false, ficherosToCompare[0].Actualizar_Frecuencia__c, 'Error al  setear Actualizar Frecuencia');
    }
}