force-app/main/default/objects/Account/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <formula>Codigo_postal_service__r.Localidad__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Localidad</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Localidad__c/Localidad__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <label>Nombre de Localidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Localidad__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Localidades</relationshipLabel>
    <relationshipName>Localidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LookupComponentController.cls
public without sharing class LookupComponentController {

    @AuraEnabled(cacheable=true)
    public static List<Localidad__c> getLocalidades(String idMunicipio) {
        List<Localidad__c> lista = [
            SELECT      Id, Name
            FROM        Localidad__c
            WHERE       Municipio__c =: idMunicipio
            ORDER BY    Name
        ];

        return lista;
    }

    @AuraEnabled(cacheable=true)
    public static List<Account> getProfesionales() {
        List<Account> profesionales = [
            SELECT  Id, Name
            FROM    Account
            WHERE   RecordType.Name =: 'Profesional de la salud'
                OR  RecordType.Name =: 'Otro profesional'
        ];

        return profesionales;
    }

    @AuraEnabled(cacheable=true)
    public static List<Account> getInstituciones() {
        List<Account> instituciones = [
            SELECT  Id, Name
            FROM    Account
            WHERE   RecordType.Name =: 'Institución'
            ORDER BY Name
        ];

        return instituciones;
    }

    @AuraEnabled(cacheable=true)
    public static List<Account> getObrasSociales() {
        List<Account> obraSociales = [
            SELECT  Id, Name
            FROM    Account
            WHERE   RecordType.Name =: 'Obra social'
            ORDER BY Name
        ];

        return obraSociales;
    }

}