force-app/main/default/objects/Account/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Módulo</label>
    <referenceTo>Modulo__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Modulo_hasta__c.field-meta.xml
<CustomField>
    <fullName>Modulo_hasta__c</fullName>
    <label>Modulo hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Modulo__c/Modulo__c.object-meta.xml
<CustomObject>
    <label>Módulo</label>
    <nameField>
        <label>Nombre de Modulo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Módulos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Modulo_de_paciente__c/Modulo_de_paciente__c.object-meta.xml
<CustomObject>
    <label>Modulo de paciente</label>
    <nameField>
        <displayFormat>MDP-{0000}</displayFormat>
        <label>Nro de Modulo de paciente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modulos de paciente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>El módulo solo es válido para pacientes Best Care</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Best Care</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Modulos de paciente (Solo Best Care)</relationshipLabel>
    <relationshipName>Modulos_de_paciente</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Duracion_modulo__c.field-meta.xml
<CustomField>
    <fullName>Duracion_modulo__c</fullName>
    <inlineHelpText>En días</inlineHelpText>
    <label>Duracion modulo</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado de Servicio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modulo</label>
    <referenceTo>Modulo__c</referenceTo>
    <relationshipLabel>Modulos de paciente</relationshipLabel>
    <relationshipName>Modulos_de_paciente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Modulo_desde__c.field-meta.xml
<CustomField>
    <fullName>Modulo_desde__c</fullName>
    <label>Modulo desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Modulo_hasta__c.field-meta.xml
<CustomField>
    <fullName>Modulo_hasta__c</fullName>
    <label>Modulo hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Renovacion__c.field-meta.xml
<CustomField>
    <fullName>Renovacion__c</fullName>
    <label>Renovación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Renovacion</fullName>
            </value>
            <value>
                <fullName>alta</fullName>
                <label>Alta</label>
            </value>
            <value>
                <fullName>Recupero</fullName>
            </value>
            <value>
                <fullName>Sí</fullName>
                <isActive>false</isActive>
                <label>Sí</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Modulo</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Producto_de_modulo__c/Producto_de_modulo__c.object-meta.xml
<CustomObject>
    <label>Producto de módulo</label>
    <nameField>
        <displayFormat>PDM-{0000}</displayFormat>
        <label>Nro de Producto de módulo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos de módulo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Producto_de_modulo__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <label>Cantidad</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Producto_de_modulo__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fórmula</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Producto_para__c</field>
            <operation>equals</operation>
            <value>Best Care</value>
        </filterItems>
        <filterItems>
            <field>Product2.Producto_SAP__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Productos de módulo</relationshipLabel>
    <relationshipName>Planes_de_cuidado</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Producto_de_modulo__c/fields/Modulo_de_paciente__c.field-meta.xml
<CustomField>
    <fullName>Modulo_de_paciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Módulo de paciente</label>
    <referenceTo>Modulo_de_paciente__c</referenceTo>
    <relationshipName>Planes_de_cuidado</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servicios_del_Modulo__c/Servicios_del_Modulo__c.object-meta.xml
<CustomObject>
    <label>Servicios del Modulo</label>
    <nameField>
        <displayFormat>SDM-{00000}</displayFormat>
        <label>Nombre de Servicios del Modulo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Servicios del Modulo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Servicios_del_Modulo__c/fields/Modulo_de_paciente__c.field-meta.xml
<CustomField>
    <fullName>Modulo_de_paciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modulo de paciente</label>
    <referenceTo>Modulo_de_paciente__c</referenceTo>
    <relationshipLabel>Servicios del Modulo</relationshipLabel>
    <relationshipName>Servicios_del_Modulo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servicios_del_Modulo__c/fields/Servicios_disponibles__c.field-meta.xml
<CustomField>
    <fullName>Servicios_disponibles__c</fullName>
    <label>Servicios</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Servicio visita enfermería</fullName>
            </value>
            <value>
                <fullName>Servicio visita nutricional</fullName>
            </value>
            <value>
                <fullName>Servicio visita medica</fullName>
            </value>
            <value>
                <fullName>Servicio visita especialista en deglución</fullName>
            </value>
            <value>
                <fullName>Rehabilitación_Motora_Plus</fullName>
                <label>Rehabilitación Motora Plus</label>
            </value>
            <value>
                <fullName>Servicio de visita cuidado nutricional completo</fullName>
            </value>
            <value>
                <fullName>Rehabilitacion_Motora_Intermedio</fullName>
                <label>Rehabilitacion Motora - Intermedio</label>
            </value>
            <value>
                <fullName>Rehabilitacion_Motora_basico_Oral</fullName>
                <label>Rehabilitación Motora básico Oral</label>
            </value>
            <value>
                <fullName>Rehabilitacion_Motora_Basico_Enteral</fullName>
                <label>Rehabilitación Motora Básico Enteral</label>
            </value>
            <value>
                <fullName>CUIDADO BÁSICO</fullName>
            </value>
            <value>
                <fullName>Autocuidado</fullName>
                <isActive>false</isActive>
                <label>Autocuidado</label>
            </value>
            <value>
                <fullName>Cuidado_completo</fullName>
                <isActive>false</isActive>
                <label>Cuidado completo</label>
            </value>
            <value>
                <fullName>Ninguno</fullName>
                <isActive>false</isActive>
                <label>Ninguno</label>
            </value>
            <value>
                <fullName>Rehabilitacion_Motora_Basico</fullName>
                <isActive>false</isActive>
                <label>Rehabilitacion_Motora_Basico</label>
            </value>
            <value>
                <fullName>Rehabilitación Motora Cuidado Completo</fullName>
                <isActive>false</isActive>
                <label>Rehabilitación Motora Cuidado Completo</label>
            </value>
            <value>
                <fullName>Rehabilitación Motora Cuidado Personalizada</fullName>
                <isActive>false</isActive>
                <label>Rehabilitación Motora Cuidado Personalizada</label>
            </value>
            <value>
                <fullName>Servicio de visita profesionales cuidado nutricional completo</fullName>
                <isActive>false</isActive>
                <label>Servicio de visita profesionales cuidado nutricional completo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RenovarModuloDePacienteCtrlTest.cls
@IsTest
public class RenovarModuloDePacienteCtrlTest {

	@IsTest
	static void inTheView_renewModuloDePacienteAndReleatedProducts_SearchProductEmpty_RenewModuloDePacienteDesdeEqualsOriginModuloDePacienteHasta() {
		stdController = new ApexPages.StandardController(moduloDePacienteToTest);
		controller = new RenovarModuloDePacienteCtrl(stdController);
		Test.startTest();
		controller.renewModuloDePaciente();
		Test.stopTest();

		System.assertEquals(true, controller.searchProducts.isEmpty());

		String renewModuloDePacienteId = controller.renewModuloUrl.substringAfter('/');
		Modulo_de_paciente__c moduloDePacienteToAssert = [
            SELECT Id,
            Modulo_desde__c,
            Modulo__c,
            Duracion_modulo__c,
            Renovacion__c,
            Cuenta__c,
            Estado__c
            FROM Modulo_de_paciente__c
            WHERE Id = :renewModuloDePacienteId
		                                                 ];

		System.assertEquals(accountToTest.Id, moduloDePacienteToAssert.Cuenta__c);
		System.assertEquals(moduloDePacienteToTest.Modulo__c, moduloDePacienteToAssert.Modulo__c);
		System.assertEquals(moduloDePacienteToTest.Duracion_modulo__c, moduloDePacienteToAssert.Duracion_modulo__c);
		System.assertEquals('Renovacion', moduloDePacienteToAssert.Renovacion__c);
		System.assertEquals(Date.today(), moduloDePacienteToAssert.Modulo_desde__c);
		System.assertEquals('Activo', moduloDePacienteToAssert.Estado__c);

		List<Producto_de_modulo__c> productosDeModuloToAssert = [
		                                                         SELECT Id,
		                                                         Modulo_de_paciente__c
		                                                         FROM Producto_de_modulo__c
		                                                         WHERE Modulo_de_paciente__c = :renewModuloDePacienteId
		                                                        ];

		System.assertEquals(5, productosDeModuloToAssert.size());
	}

	@IsTest
	static void inTheView_renewModuloDePaciente_DeSelectOriginModuloDePacienteReleatedProducts_SelectAllNewProduct() {

		List<Product2> newProductOfModuloDePacienteToTest = new List<Product2> ();
		for (Integer i = 5; i< 10; i++) {
			newProductOfModuloDePacienteToTest.add(
			                                       Build.aProduct2()
			                                       .withProductoPara('Best Care')
			                                       .withName('Product Test' + i)
			                                       .withDescription('To Testing' + i)
                								   .withhProductoSAP(true)
			                                       .build()
			);
		}
		insert newProductOfModuloDePacienteToTest;

		stdController = new ApexPages.StandardController(moduloDePacienteToTest);
		controller = new RenovarModuloDePacienteCtrl(stdController);

		controller.existProductSelectAll = false;
		controller.doExistProductSelectAll();

		controller.searchSelectAll = true;
		controller.doSearchProductsSelectAll();

		Test.startTest();
		controller.renewModuloDePaciente();
		Test.stopTest();

		System.assertEquals(false, controller.searchProducts.isEmpty());
		System.assertEquals(5, controller.searchProducts.size());

		String renewModuloDePacienteId = controller.renewModuloUrl.substringAfter('/');
		Modulo_de_paciente__c moduloDePacienteToAssert = [
		                                                  SELECT Id,
		                                                  Modulo_desde__c,
		                                                  Modulo__c,
		                                                  Duracion_modulo__c,
		                                                  Renovacion__c,
		                                                  Cuenta__c,
		                                                  Estado__c
		                                                  FROM Modulo_de_paciente__c
		                                                  WHERE Id = :renewModuloDePacienteId
		                                                 ];

		System.assertEquals(accountToTest.Id, moduloDePacienteToAssert.Cuenta__c);
		System.assertEquals(moduloDePacienteToTest.Modulo__c, moduloDePacienteToAssert.Modulo__c);
		System.assertEquals(moduloDePacienteToTest.Duracion_modulo__c, moduloDePacienteToAssert.Duracion_modulo__c);
		System.assertEquals('Renovacion', moduloDePacienteToAssert.Renovacion__c);
		System.assertEquals(Date.today(), moduloDePacienteToAssert.Modulo_desde__c);
		System.assertEquals('Activo', moduloDePacienteToAssert.Estado__c);

		List<Producto_de_modulo__c> productosDeModuloToAssert = [
		                                                         SELECT Id,
		                                                         Modulo_de_paciente__c
		                                                         FROM Producto_de_modulo__c
		                                                         WHERE Modulo_de_paciente__c = :renewModuloDePacienteId
		                                                        ];

		System.assertEquals(5, productosDeModuloToAssert.size());
	}

	@IsTest
	static void inTheView_renewModuloDePaciente_DeselectOriginModuloDePacienteReleatedProducts_SelectOneNewProductOnly() {

		List<Product2> newProductOfModuloDePacienteToTest = new List<Product2> ();
		for (Integer i = 5; i< 10; i++) {
			newProductOfModuloDePacienteToTest.add(
			                                       Build.aProduct2()
			                                       .withProductoPara('Best Care')
			                                       .withName('Product Test' + i)
			                                       .withDescription('To Testing' + i)
                								   .withhProductoSAP(true)
			                                       .build()
			);
		}
		insert newProductOfModuloDePacienteToTest;

		stdController = new ApexPages.StandardController(moduloDePacienteToTest);
		controller = new RenovarModuloDePacienteCtrl(stdController);

		controller.existProductSelectAll = false;
		controller.doExistProductSelectAll();

		RenovarModuloDePacienteCtrl.WrapperProduct newProductSelected = controller.actualSearchProductsPage.values() [0];
		ApexPages.currentPage().getParameters().put('searchProductIdSelect', newProductSelected.product.Id);
		newProductSelected.isSelected = true;
		controller.setProductsToConfirmThruSelectedSearchedProducts();

		Test.startTest();
		controller.renewModuloDePaciente();
		Test.stopTest();

		String renewModuloDePacienteId = controller.renewModuloUrl.substringAfter('/');
		Modulo_de_paciente__c moduloDePacienteToAssert = [
		                                                  SELECT Id,
		                                                  Modulo_desde__c,
		                                                  Modulo__c,
		                                                  Duracion_modulo__c,
		                                                  Renovacion__c,
		                                                  Cuenta__c,
		                                                  Estado__c
		                                                  FROM Modulo_de_paciente__c
		                                                  WHERE Id = :renewModuloDePacienteId
		                                                 ];

		System.assertEquals(accountToTest.Id, moduloDePacienteToAssert.Cuenta__c);
		System.assertEquals(moduloDePacienteToTest.Modulo__c, moduloDePacienteToAssert.Modulo__c);
		System.assertEquals(moduloDePacienteToTest.Duracion_modulo__c, moduloDePacienteToAssert.Duracion_modulo__c);
		System.assertEquals('Renovacion', moduloDePacienteToAssert.Renovacion__c);
		System.assertEquals(Date.today(), moduloDePacienteToAssert.Modulo_desde__c);
		System.assertEquals('Activo', moduloDePacienteToAssert.Estado__c);

		List<Producto_de_modulo__c> productosDeModuloToAssert = [
		                                                         SELECT Id,
		                                                         Modulo_de_paciente__c
		                                                         FROM Producto_de_modulo__c
		                                                         WHERE Modulo_de_paciente__c = :renewModuloDePacienteId
		                                                        ];

		System.assertEquals(1, productosDeModuloToAssert.size());
	}

	@IsTest
	static void givenACriterion_itShouldBePossibleToObtainProductsThatContainIt() {
		Product2 product = Build.aProduct2()
		.withProductoPara('Best Care')
		.withName('Name')
		.withDescription('Producto')
        .withhProductoSAP(true)
		.build();
		insert product;

		Id[] fixedSearchResults = new Id[] { product.Id };
		Test.setFixedSearchResults(fixedSearchResults);

		stdController = new ApexPages.StandardController(moduloDePacienteToTest);
		controller = new RenovarModuloDePacienteCtrl(stdController);

		controller.criteria = 'Prod';

		Test.startTest();
		controller.findProducts();
		Test.stopTest();

		System.assertEquals(1, controller.actualSearchProductsPage.size());
	}

	@IsTest
	static void ifThereAreElevenProductsAndThePageSizeIsTen_theLastPageShouldBeHaveOneItems() {
		List<Product2> productsToTest = new List<Product2> ();
		for (Integer i = 0; i< 11; i++) {
			productsToTest.add(
			                   Build.aProduct2()
			                   .withProductoPara('Best Care')
			                   .withName('Name' + i)
			                   .withDescription('Producto' + i)
                			   .withhProductoSAP(true)
			                   .build()
			);
		}
		insert productsToTest;

		stdController = new ApexPages.StandardController(moduloDePacienteToTest);
		controller = new RenovarModuloDePacienteCtrl(stdController);

		Test.startTest();
		controller.lastPage();
		Test.stopTest();

		System.assertEquals(1, controller.actualSearchProductsPage.size());
		System.assertEquals(11, controller.searchProducts.size());
	}

	@IsTest
	static void inTheView_setCantidadDeRegistrosMostradosIn25_navegateWithNextButtonToTheLastPage_theLastPageShouldBeHave10Items() {
		List<Product2> productsToTest = new List<Product2> ();
		for (Integer i = 0; i< 60; i++) {
			productsToTest.add(
			                   Build.aProduct2()
			                   .withProductoPara('Best Care')
			                   .withName('Name' + i)
			                   .withDescription('Producto' + i)
                			   .withhProductoSAP(true)
			                   .build()
			);
		}
		insert productsToTest;

		stdController = new ApexPages.StandardController(moduloDePacienteToTest);
		controller = new RenovarModuloDePacienteCtrl(stdController);

		SelectOption pageSizeViewOptionSelected = controller.getItems() [1];
		String pageSizeView = pageSizeViewOptionSelected.getValue();
		controller.pageSizeStr = pageSizeView;

		Test.startTest();
		controller.changePageSize();
		controller.next();
		controller.next();
		Test.stopTest();

		System.assertEquals(10, controller.actualSearchProductsPage.size());
		System.assertEquals(60, controller.searchProducts.size());
		System.assertEquals(3, controller.actualPageNumber);
		System.assertEquals(3, controller.numPages);
	}

	@IsTest
	static void givenACriterion_NavegateTheResult_searchAgainByTheSameCriterionShouldGoToTheFirstPage() {
		List<Product2> productsToTest = new List<Product2> ();
		for (Integer i = 0; i< 60; i++) {
			productsToTest.add(
			                   Build.aProduct2()
			                   .withProductoPara('Best Care')
			                   .withName('Name' + i)
			                   .withDescription('Producto' + i)
                			   .withhProductoSAP(true)
			                   .build()
			);
		}
		insert productsToTest;

		stdController = new ApexPages.StandardController(moduloDePacienteToTest);
		controller = new RenovarModuloDePacienteCtrl(stdController);

		controller.criteria = 'Prod';
		controller.findProducts();
		controller.next();
		controller.next();
		controller.previous();

		Test.startTest();
		controller.criteria = 'Prod';
		controller.findProducts();
		Test.stopTest();

		System.assertEquals(10, controller.actualSearchProductsPage.size());
		System.assertEquals(60, controller.searchProducts.size());
		System.assertEquals(1, controller.actualPageNumber);
		System.assertEquals(7, controller.numPages);
	}

	@IsTest
	static void whenAModuloHaveExistProduct_DeselectOneProduct_confirmProductNotHaveTheDeselectedProduct() {
		stdController = new ApexPages.StandardController(moduloDePacienteToTest);
		controller = new RenovarModuloDePacienteCtrl(stdController);
		RenovarModuloDePacienteCtrl.WrapperProduct wrapperProductToTest =
		controller.existProductsById.values() [0];

		wrapperProductToTest.isSelected = false;

		PageReference pageRef = Page.RenovarModuloDePaciente;
		Test.setCurrentPage(pageRef);
		Test.startTest();
		ApexPages.currentPage().getParameters().put(
		                                            'existProductIdSelect',
		                                            wrapperProductToTest.product.Id
		);
		ApexPages.currentPage().getParameters().put(
		                                            'existProductQuantity',
		                                            String.valueOf(wrapperProductToTest.quantity)
		);
		controller.setProductsToConfirmThruExistSelected();
		Test.stopTest();

		System.assertEquals(5, controller.existProductsById.size());
		System.assertEquals(4, controller.productsToConfirm.size());
	}

	@IsTest
	static void whenAModuloHaveExistProduct_ChangeQuantityOfOneProduct_confirmProductHaveTheProductQuantityChangedToo() {
		stdController = new ApexPages.StandardController(moduloDePacienteToTest);
		controller = new RenovarModuloDePacienteCtrl(stdController);
		RenovarModuloDePacienteCtrl.WrapperProduct wrapperProductToTest =
		controller.existProductsById.values() [0];

		PageReference pageRef = Page.RenovarModuloDePaciente;
		Test.setCurrentPage(pageRef);
		Test.startTest();
		wrapperProductToTest.quantity = 50;
		ApexPages.currentPage().getParameters().put(
		                                            'existProductIdSelect',
		                                            wrapperProductToTest.product.Id
		);
		ApexPages.currentPage().getParameters().put(
		                                            'existProductQuantity',
		                                            String.valueOf(wrapperProductToTest.quantity)
		);
		controller.setProductsToConfirmThruExistSelected();
		Test.stopTest();

		System.assertEquals(wrapperProductToTest.quantity, controller.existProductsById.get(wrapperProductToTest.product.Id).quantity);
	}

	@IsTest
	static void inTheView_selectAllSearchedProduct_ThenDeselectAll_ProductToConfirmHaveOnlyExistingProducts() {
		List<Product2> productsToTest = new List<Product2> ();
		for (Integer i = 0; i< 60; i++) {
			productsToTest.add(
			                   Build.aProduct2()
			                   .withProductoPara('Best Care')
			                   .withName('Name' + i)
			                   .withDescription('Producto' + i)
                			   .withhProductoSAP(true)
			                   .build()
			);
		}
		insert productsToTest;

		stdController = new ApexPages.StandardController(moduloDePacienteToTest);
		controller = new RenovarModuloDePacienteCtrl(stdController);

		RenovarModuloDePacienteCtrl.WrapperProduct wrapperProductToTest = controller.actualSearchProductsPage.values() [0];

		PageReference pageRef = Page.RenovarModuloDePaciente;
		Test.setCurrentPage(pageRef);
		Test.startTest();
		ApexPages.currentPage().getParameters().put(
		                                            'searchProductIdSelect',
		                                            wrapperProductToTest.product.Id
		);
		ApexPages.currentPage().getParameters().put(
		                                            'searchProductQuantity',
		                                            String.valueOf(wrapperProductToTest.quantity)
		);
		controller.doSearchProductsSelectAll();
		controller.doSearchedDeselectAll();
		Test.stopTest();

		System.assertEquals(controller.existProductsById.size(), controller.productsToConfirm.size());
	}

	@IsTest
	static void whenAModuloDePaciente_SelectSearchedProduct_ThenChangeTheQuantity_confirmProductHaveProductAndTheProductQuantityChangedToo() {
		List<Product2> productsToTest = new List<Product2> ();
		for (Integer i = 0; i< 60; i++) {
			productsToTest.add(
			                   Build.aProduct2()
			                   .withProductoPara('Best Care')
			                   .withName('Name' + i)
			                   .withDescription('Producto' + i)
                			   .withhProductoSAP(true)
			                   .build()
			);
		}
		insert productsToTest;

		stdController = new ApexPages.StandardController(moduloDePacienteToTest);
		controller = new RenovarModuloDePacienteCtrl(stdController);

		RenovarModuloDePacienteCtrl.WrapperProduct wrapperProductToTest = controller.actualSearchProductsPage.values() [0];

		PageReference pageRef = Page.RenovarModuloDePaciente;
		Test.setCurrentPage(pageRef);
		Test.startTest();
		//Select the searched product
		wrapperProductToTest.isSelected = true;
		ApexPages.currentPage().getParameters().put(
		                                            'searchProductIdSelect',
		                                            wrapperProductToTest.product.Id
		);
		ApexPages.currentPage().getParameters().put(
		                                            'searchProductQuantity',
		                                            String.valueOf(wrapperProductToTest.quantity)
		);
		controller.setProductsToConfirmThruSelectedSearchedProducts();
		//Change quantity in searched product
		wrapperProductToTest.quantity = 50;
		ApexPages.currentPage().getParameters().put(
		                                            'searchProductIdSelect',
		                                            wrapperProductToTest.product.Id
		);
		ApexPages.currentPage().getParameters().put(
		                                            'searchProductQuantity',
		                                            String.valueOf(wrapperProductToTest.quantity)
		);
		controller.setProductsToConfirmThruSelectedSearchedProducts();
		Test.stopTest();

		System.assertEquals(50, controller.productsToConfirm.get(wrapperProductToTest.product.Id).quantity);
	}

	@IsTest
	static void inTheView_renewModuloDePaciente_SelectAllNewProduct() {

		List<Product2> newProductOfModuloDePacienteToTest = new List<Product2> ();
		for (Integer i = 0; i< 500; i++) {
			newProductOfModuloDePacienteToTest.add(
			                                       Build.aProduct2()
			                                       .withProductoPara('Best Care')
			                                       .withName('Product Test' + i)
			                                       .withDescription('To Testing' + i)
                								   .withhProductoSAP(true)
			                                       .build()
			);
		}
		insert newProductOfModuloDePacienteToTest;

		stdController = new ApexPages.StandardController(moduloDePacienteToTest);
		controller = new RenovarModuloDePacienteCtrl(stdController);

		Test.startTest();
		//deselect all exist products
		controller.existProductSelectAll = false;
		controller.doExistProductSelectAll();

		//select all searchedProducts
		//First page
		controller.searchSelectAll = true;
		controller.doSearchProductsSelectAll();

		for (Integer i = 1; i< 50; i++) {
			controller.next();
			controller.searchSelectAll = true;
			controller.doSearchProductsSelectAll();
		}
		//click Renovar button
		controller.renewModuloDePaciente();
		Test.stopTest();

		System.assertEquals(false, controller.searchProducts.isEmpty());
		System.assertEquals(500, controller.searchProducts.size());

		String renewModuloDePacienteId = controller.renewModuloUrl.substringAfter('/');
		Modulo_de_paciente__c moduloDePacienteToAssert = [
		                                                  SELECT Id,
		                                                  Modulo_desde__c,
		                                                  Modulo__c,
		                                                  Duracion_modulo__c,
		                                                  Renovacion__c,
		                                                  Cuenta__c,
		                                                  Estado__c
		                                                  FROM Modulo_de_paciente__c
		                                                  WHERE Id = :renewModuloDePacienteId
		                                                 ];

		System.assertEquals(accountToTest.Id, moduloDePacienteToAssert.Cuenta__c);
		System.assertEquals(moduloDePacienteToTest.Modulo__c, moduloDePacienteToAssert.Modulo__c);
		System.assertEquals(moduloDePacienteToTest.Duracion_modulo__c, moduloDePacienteToAssert.Duracion_modulo__c);
		System.assertEquals('Renovacion', moduloDePacienteToAssert.Renovacion__c);
		System.assertEquals(Date.today(), moduloDePacienteToAssert.Modulo_desde__c);
		System.assertEquals('Activo', moduloDePacienteToAssert.Estado__c);

		List<Producto_de_modulo__c> productosDeModuloToAssert = [
		                                                         SELECT Id,
		                                                         Modulo_de_paciente__c
		                                                         FROM Producto_de_modulo__c
		                                                         WHERE Modulo_de_paciente__c = :renewModuloDePacienteId
		                                                        ];

		System.assertEquals(500, productosDeModuloToAssert.size());
	}


	@IsTest
	static void verifyThatModuloDesdeSameThatModuloHasta() {

		moduloDePacienteToTest.Modulo_hasta__c = System.today().addDays(2);
		update moduloDePacienteToTest;

		List<Product2> newProductOfModuloDePacienteToTest = new List<Product2> ();
		for (Integer i = 0; i< 500; i++) {
			newProductOfModuloDePacienteToTest.add(
			                                       Build.aProduct2()
			                                       .withProductoPara('Best Care')
			                                       .withName('Product Test' + i)
			                                       .withDescription('To Testing' + i)
                								   .withhProductoSAP(true)
			                                       .build()
			);
		}
		insert newProductOfModuloDePacienteToTest;

		stdController = new ApexPages.StandardController(moduloDePacienteToTest);
		controller = new RenovarModuloDePacienteCtrl(stdController);

		Test.startTest();
		//deselect all exist products
		controller.existProductSelectAll = false;
		controller.doExistProductSelectAll();

		//select all searchedProducts
		//First page
		controller.searchSelectAll = true;
		controller.doSearchProductsSelectAll();

		for (Integer i = 1; i< 50; i++) {
			controller.next();
			controller.searchSelectAll = true;
			controller.doSearchProductsSelectAll();
		}
		controller.renewModuloDePaciente();
		Test.stopTest();


		String renewModuloDePacienteId = controller.renewModuloUrl.substringAfter('/');
		Modulo_de_paciente__c moduloDePacienteToAssert = [
		                                                  SELECT Id,
		                                                  Modulo_desde__c,
		                                                  Modulo__c,
		                                                  Duracion_modulo__c,
		                                                  Renovacion__c,
		                                                  Cuenta__c,
		                                                  Estado__c
		                                                  FROM Modulo_de_paciente__c
		                                                  WHERE Id = :renewModuloDePacienteId
		                                                 ];

		System.assertEquals(accountToTest.Id, moduloDePacienteToAssert.Cuenta__c);
		System.assertEquals(moduloDePacienteToTest.Modulo__c, moduloDePacienteToAssert.Modulo__c);
		System.assertEquals(moduloDePacienteToTest.Duracion_modulo__c, moduloDePacienteToAssert.Duracion_modulo__c);
		System.assertEquals('Renovacion', moduloDePacienteToAssert.Renovacion__c);
		System.assertEquals(moduloDePacienteToTest.Modulo_hasta__c, moduloDePacienteToAssert.Modulo_desde__c);
		System.assertEquals('Activo', moduloDePacienteToAssert.Estado__c);
	}
    
    
    

	static ApexPages.StandardController stdController;
	static RenovarModuloDePacienteCtrl controller;
	static Account accountToTest;
	static Modulo__c moduloToTest;
	static Modulo_de_paciente__c moduloDePacienteToTest;
	static List<Product2> productOfModuloDePacienteToTest;
	static List<Producto_de_modulo__c> productosDeModuloToTest;

	static {
		accountToTest = Build.anAccountPacienteBestCare()
		.withLastName('Name Test')
		.withRegimenDeInternacionDomiciliaria('Sí')
		.withEmpresadeinternaciondomiciliaria('Best care')
		.withCanalParaConsumidorBaby('Almacen')
		.build();
		insert accountToTest;

		moduloToTest = Build.aModulo()
		.withName('A-Care 1.10')
		.withDescripcion('Despacho de productos para terapia nutricional: APLV/Alergias alimentarias múltiples Gold- oral h/10')
		.build();
		insert moduloToTest;

		moduloDePacienteToTest = Build.aModulodepaciente()
		.withModulodesde(Date.newInstance(2019, 5, 11))
		.withModulo(moduloToTest)
		.withDuracion(20)
		.withCuenta(accountToTest)
		.withModulohasta(Date.newInstance(2019, 5, 31))
		.build();
		insert moduloDePacienteToTest;
        
        Servicios_del_Modulo__c servicioToTest = new Servicios_del_Modulo__c();
        servicioToTest.Modulo_de_paciente__c = moduloDePacienteToTest.id;
        servicioToTest.Servicios_disponibles__c = 'Servicio visita nutricional';
        servicioToTest.Cantidad__c = 5;
		
        insert servicioToTest;
        
		productOfModuloDePacienteToTest = new List<Product2> ();
		for (Integer i = 0; i< 5; i++) {
			productOfModuloDePacienteToTest.add(
			                                    Build.aProduct2()
			                                    .withProductoPara('Best Care')
			                                    .withName('Test' + i)
			                                    .withDescription('To Testing' + i)
                								.withhProductoSAP(true)
			                                    .build()
			);
		}
		insert productOfModuloDePacienteToTest;

		productosDeModuloToTest = new List<Producto_de_modulo__c> ();
		for (Product2 product : productOfModuloDePacienteToTest) {
			Producto_de_modulo__c productoDeModuloToTest = new Producto_de_modulo__c();
			productoDeModuloToTest.Formula__c = product.Id;
			productoDeModuloToTest.Cantidad__c = '10';
			productoDeModuloToTest.Modulo_de_paciente__c = moduloDePacienteToTest.Id;
			productosDeModuloToTest.add(productoDeModuloToTest);
		}
		insert productosDeModuloToTest;
	}
}