force-app/main/default/objects/Account/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Módulo</label>
    <referenceTo>Modulo__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_servicio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_servicio__c</fullName>
    <label>Tipo de servicio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internacion__c/Internacion__c.object-meta.xml
<CustomObject>
    <label>Internacion</label>
    <nameField>
        <displayFormat>INT-{0000}</displayFormat>
        <label>Internacion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Internacion__c/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Módulo</label>
    <referenceTo>Modulo__c</referenceTo>
    <relationshipLabel>Internaciones</relationshipLabel>
    <relationshipName>Internaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Internacion__c/fields/Paciente__c.field-meta.xml
<CustomField>
    <fullName>Paciente__c</fullName>
    <label>Paciente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Sanatorio</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Internaciones</relationshipLabel>
    <relationshipName>Internaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Internacion__c/fields/Tipo_de_Servicio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Servicio__c</fullName>
    <label>Tipo de Servicio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cuidado completo</fullName>
            </value>
            <value>
                <fullName>Cuidado personalizado</fullName>
                <isActive>false</isActive>
                <label>Cuidado personalizado</label>
            </value>
            <value>
                <fullName>Rehabilitación deglutoria</fullName>
                <isActive>false</isActive>
                <label>Rehabilitación deglutoria</label>
            </value>
            <value>
                <fullName>Rehabilitación motora - intermedio</fullName>
                <isActive>false</isActive>
                <label>Rehabilitación motora - intermedio</label>
            </value>
            <value>
                <fullName>Rehabilitación motora básico enteral</fullName>
                <isActive>false</isActive>
                <label>Rehabilitación motora básico enteral</label>
            </value>
            <value>
                <fullName>Rehabilitación motora básico oral</fullName>
                <isActive>false</isActive>
                <label>Rehabilitación motora básico oral</label>
            </value>
            <value>
                <fullName>Rehabilitación motora plus</fullName>
                <isActive>false</isActive>
                <label>Rehabilitación motora plus</label>
            </value>
            <value>
                <fullName>autocuidado</fullName>
                <isActive>false</isActive>
                <label>autocuidado</label>
            </value>
            <value>
                <fullName>cuidado básico</fullName>
                <isActive>false</isActive>
                <label>cuidado básico</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Modulo__c/Modulo__c.object-meta.xml
<CustomObject>
    <label>Módulo</label>
    <nameField>
        <label>Nombre de Modulo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Módulos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Modulo</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Producto_SAP__c.field-meta.xml
<CustomField>
    <fullName>Producto_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Producto SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Producto__c/Producto__c.object-meta.xml
<CustomObject>
    <label>Producto</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Nro de Producto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Producto_de_Internacion__c/Producto_de_Internacion__c.object-meta.xml
<CustomObject>
    <label>Producto de Internación</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Producto de Internacion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos de internaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Producto_de_Internacion__c/fields/Internacion__c.field-meta.xml
<CustomField>
    <fullName>Internacion__c</fullName>
    <label>Internacion</label>
    <referenceTo>Internacion__c</referenceTo>
    <relationshipLabel>Productos de internacion</relationshipLabel>
    <relationshipName>Productos_de_internaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Producto_de_Internacion__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Productos de internaciones</relationshipLabel>
    <relationshipName>Productos_de_internaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Producto_de_Internacion__c/fields/Tipo_de_servicio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_servicio__c</fullName>
    <label>Tipo de servicio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cuidado completo</fullName>
                <default>true</default>
                <label>Cuidado completo</label>
            </value>
            <value>
                <fullName>Cuidado personalizado</fullName>
                <isActive>false</isActive>
                <label>Cuidado personalizado</label>
            </value>
            <value>
                <fullName>Rehabilitación deglutoria</fullName>
                <isActive>false</isActive>
                <label>Rehabilitación deglutoria</label>
            </value>
            <value>
                <fullName>Rehabilitación motora - intermedio</fullName>
                <isActive>false</isActive>
                <label>Rehabilitación motora - intermedio</label>
            </value>
            <value>
                <fullName>Rehabilitación motora básico enteral</fullName>
                <isActive>false</isActive>
                <label>Rehabilitación motora básico enteral</label>
            </value>
            <value>
                <fullName>Rehabilitación motora básico oral</fullName>
                <isActive>false</isActive>
                <label>Rehabilitación motora básico oral</label>
            </value>
            <value>
                <fullName>Rehabilitación motora plus</fullName>
                <isActive>false</isActive>
                <label>Rehabilitación motora plus</label>
            </value>
            <value>
                <fullName>autocuidado</fullName>
                <isActive>false</isActive>
                <label>autocuidado</label>
            </value>
            <value>
                <fullName>cuidado básico</fullName>
                <isActive>false</isActive>
                <label>cuidado básico</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductoDeInternacionTriggerTest.cls
@isTest
public with sharing class ProductoDeInternacionTriggerTest {
    @TestSetup
    static void makeData(){
        Account accountTest = new Account();
        accountTest.LastName = 'Test acc';
        accountTest.recordTypeId = XappiaHelper.getRecordType('Account', 'Paciente Sanatorio').Id;
        insert accountTest;
        
        Internacion__c internacionTest = new Internacion__c();
        internacionTest.Paciente__c = accountTest.Id;
        
        insert internacionTest;
        
        Modulo__c moduloToTest = Build.aModulo()
            .withName('Alergia')
            .withDescripcion('Test')
            .build();
        insert moduloToTest;
        
        Modulo__c moduloEnteral = Build.aModulo()
            .withName('Enteral Advanced')
            .withDescripcion('Test')
            .build();
        insert moduloEnteral;
        
        
        Product2 product = Build.aProduct2().build();
        product.Producto_SAP__c = true;
        product.Modulo__c = 'Alergia';
        insert product;
        
        Product2 productEnteral = Build.aProduct2().build();
        productEnteral.Producto_SAP__c = true;
        productEnteral.Modulo__c = 'Enteral Advanced';
        insert productEnteral;
    }
    
    @isTest
    public static void siSeInsertaUnNuevoProductoSeDebenCompletarLostiposDeServicioEnLAInternacion() {
        
        Producto_de_Internacion__c productTest = new Producto_de_Internacion__c();
        productTest.Internacion__c= getInternacion().Id;
        productTest.Tipo_de_servicio__c = 'Cuidado completo';
        productTest.Producto__c = getProduct2()[1].Id;
        
        insert productTest;
        
        System.assertEquals('Cuidado completo', getInternacion().Tipo_de_Servicio__c);
        System.assertEquals('Enteral Advanced',getInternacion().Modulo__r.Name);
    }
    
    @isTest
    public static void siSeInsertaUnNuevoProductoDeMayorJerarquiaSeDebenCompletarLostiposDeServicioEnLAInternacion() {
        
        Producto_de_Internacion__c productTest = new Producto_de_Internacion__c();
        productTest.Internacion__c= getInternacion().Id;
        productTest.Tipo_de_servicio__c = 'Cuidado completo';
        productTest.Producto__c = getProduct2()[0].Id;
        insert productTest;
        
        Producto_de_Internacion__c productTest2 = new Producto_de_Internacion__c();
        productTest2.Internacion__c= getInternacion().Id;
        productTest2.Tipo_de_servicio__c = 'Cuidado completo';
        productTest2.Producto__c = getProduct2()[1].Id;
        
        Test.startTest();
        insert productTest2;
        
        Test.stopTest();
        System.assertEquals( 'Enteral Advanced', getInternacion().Modulo__r.Name);
    }
    
    @isTest
    public static void siSeEliminaUnNuevoProductoSeDebenCompletarLostiposDeServicioEnLAInternacion() {
        
        Producto_de_Internacion__c productTest = new Producto_de_Internacion__c();
        productTest.Internacion__c= getInternacion().Id;
        productTest.Tipo_de_servicio__c = 'Cuidado completo';
        productTest.Producto__c = getProduct2()[0].Id;
        
        insert productTest;
        
        Producto_de_Internacion__c productTest2 = new Producto_de_Internacion__c();
        productTest2.Internacion__c= getInternacion().Id;
        productTest2.Producto__c = getProduct2()[1].Id;
        
        insert productTest2;
        
        Test.startTest();
        
        Producto_de_Internacion__c prod = 
            [
                SELECT id
                FROM Producto_de_Internacion__c
                WHERE id = :productTest2.Id
            ];
        
        delete prod;
        
        Test.stopTest();
        
        System.assertEquals( 'Alergia', getInternacion().Modulo__r.Name);
        
        
    }
    
    public static Internacion__c getInternacion(){
        return [
            SELECT id,Tipo_de_Servicio__c,Modulo__c,Modulo__r.Name
            FROM Internacion__c
            LIMIT 1
        ];
    }
    public static List<Product2> getProduct2(){
        return [
            SELECT id,Modulo__c
            FROM Product2
        ];
    }
    public static List<Modulo__c> getModulo(){
        return [
            SELECT id,Name
            FROM Modulo__c
        ];
    }
    
}