force-app/main/default/objects/Account/fields/Motivo__c.field-meta.xml
<CustomField>
    <fullName>Motivo__c</fullName>
    <label>Motivo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Evaluación de inicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Institucion.recordType-meta.xml
<RecordType>
    <fullName>Institucion</fullName>
    <active>true</active>
    <label>Institución</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Sub_Equipo__c.field-meta.xml
<CustomField>
    <fullName>Sub_Equipo__c</fullName>
    <label>Sub Equipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Equipo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/VisMed_DNI__c.field-meta.xml
<CustomField>
    <fullName>VisMed_DNI__c</fullName>
    <label>DNI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Dan360_Efectividad__c/Dan360_Efectividad__c.object-meta.xml
<CustomObject>
    <description>Objeto creado para el registro y calculo de las efectividades del APM por mes.</description>
    <label>Efectividad</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Efectividad Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Efectividades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/VisMed_Ciclo__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Ciclo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciclo</label>
    <referenceTo>VisMed_Ciclo__c</referenceTo>
    <relationshipLabel>Efectividades</relationshipLabel>
    <relationshipName>Efectividades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Interacciones__c/Dan360_Interacciones__c.object-meta.xml
<CustomObject>
    <description>Objeto para registrar las interacciones/visitas realizadas</description>
    <label>Interacción</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Interacciones Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interacciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Interacciones__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Aprobada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Interacciones__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interacciones (Profesional)</relationshipLabel>
    <relationshipName>Interacciones1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/Dan360_Licencia__c.object-meta.xml
<CustomObject>
    <description>Objeto para registrar las licencias y dias no promocionables del APM</description>
    <label>Licencia</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Licencia Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Licencia__c/fields/Efectividad__c.field-meta.xml
<CustomField>
    <fullName>Efectividad__c</fullName>
    <label>Efectividad</label>
    <referenceTo>Dan360_Efectividad__c</referenceTo>
    <relationshipLabel>Licencias</relationshipLabel>
    <relationshipName>Licencias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Estado de la licencia.</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Aprobada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <description>Fecha de finalizacion del la licencia/tiempo no promocional</description>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <description>Fecha de inicio desde que se tomo la licencia/tiempo no promocional</description>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/fields/Motivo__c.field-meta.xml
<CustomField>
    <fullName>Motivo__c</fullName>
    <description>Tipo de licencia/tiempo no promocional por el que se ausento el APM</description>
    <inlineHelpText>Motivo de ausencia</inlineHelpText>
    <label>Motivo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vacaciones</fullName>
            </value>
            <value>
                <fullName>Enfermedad</fullName>
            </value>
            <value>
                <fullName>Día de estudio</fullName>
            </value>
            <value>
                <fullName>Festivo</fullName>
            </value>
            <value>
                <fullName>Maternidad</fullName>
            </value>
            <value>
                <fullName>Reunión con jefe</fullName>
            </value>
            <value>
                <fullName>Reunión de equipo</fullName>
            </value>
            <value>
                <fullName>Congreso</fullName>
            </value>
            <value>
                <fullName>Otro</fullName>
            </value>
            <value>
                <fullName>Compensatorios</fullName>
            </value>
            <value>
                <fullName>Feriado provincial</fullName>
            </value>
            <value>
                <fullName>Tiempos de traslado por gira</fullName>
            </value>
            <value>
                <fullName>Capacitacion equipo promocional (TA/EXTERNO)</fullName>
            </value>
            <value>
                <fullName>Relevamiento de datos / Actividad de Fichero</fullName>
            </value>
            <value>
                <fullName>Tareas comerciales</fullName>
            </value>
            <value>
                <fullName>Reunion por temas de acceso/BC</fullName>
            </value>
            <value>
                <fullName>Reunion de seguimiento con la TA</fullName>
            </value>
            <value>
                <fullName>Reunion con KAE/KAM</fullName>
            </value>
            <value>
                <fullName>Convención</fullName>
            </value>
            <value>
                <fullName>Capacitaciones</fullName>
            </value>
            <value>
                <fullName>Congresos</fullName>
            </value>
            <value>
                <fullName>Lanzamientos</fullName>
            </value>
            <value>
                <fullName>Reunion con Auditores</fullName>
            </value>
            <value>
                <fullName>Averiguacion licitaciones</fullName>
            </value>
            <value>
                <fullName>Reunion de ciclo</fullName>
            </value>
            <value>
                <fullName>Workshops de las diferentres TAs (Webinar, ateneos)</fullName>
            </value>
            <value>
                <fullName>Towhall</fullName>
            </value>
            <value>
                <fullName>Cumpleaños</fullName>
            </value>
            <value>
                <fullName>Reunión con HCPS</fullName>
            </value>
            <value>
                <fullName>Convecion</fullName>
                <isActive>false</isActive>
                <label>Convecion</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/recordTypes/Licencia.recordType-meta.xml
<RecordType>
    <fullName>Licencia</fullName>
    <active>true</active>
    <description>Tipo de registro para las licencias de tipo Vacaciones, Enfermedad, Día de estudio, Festivo y Maternidad</description>
    <label>Licencia</label>
</RecordType>

force-app/main/default/objects/User/fields/Sub_Equipo__c.field-meta.xml
<CustomField>
    <fullName>Sub_Equipo__c</fullName>
    <label>Sub Equipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Equipo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/VisMed_ContrasenaApp__c.field-meta.xml
<CustomField>
    <fullName>VisMed_ContrasenaApp__c</fullName>
    <label>Contraseña App</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/User/fields/VisMed_Es_un_Visitador_Medico__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Es_un_Visitador_Medico__c</fullName>
    <defaultValue>false</defaultValue>
    <description>field booleano para indicar si el usuario pertenece a la familia de visitadores y saber si debe contar en las querys.</description>
    <label>Es un Visitador Medico</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VisMed_Bajas__c/VisMed_Bajas__c.object-meta.xml
<CustomObject>
    <description>Objeto para gestionar las bajas de registros</description>
    <label>Bajas</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bajas Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bajas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Bajas__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Aprobada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Bajas__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bajas</relationshipLabel>
    <relationshipName>Bajas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Bajas__c/recordTypes/Institucion.recordType-meta.xml
<RecordType>
    <fullName>Institucion</fullName>
    <active>true</active>
    <label>Institución</label>
</RecordType>

force-app/main/default/objects/VisMed_Bajas__c/recordTypes/Seguimiento.recordType-meta.xml
<RecordType>
    <fullName>Seguimiento</fullName>
    <active>true</active>
    <label>Seguimiento</label>
</RecordType>

force-app/main/default/objects/VisMed_Ciclo__c/VisMed_Ciclo__c.object-meta.xml
<CustomObject>
    <label>Ciclo</label>
    <nameField>
        <label>Ciclo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Ciclo__c/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/VisMed_Contacto_Cuenta_Usuario__c.object-meta.xml
<CustomObject>
    <description>Relacion de APM con el profesional y su lugar de trabajo</description>
    <label>Fichero</label>
    <nameField>
        <displayFormat>SEG-{0000}</displayFormat>
        <label>Seguimiento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ficheros</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Seguimientos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/VisMed_Segmentacion__c.object-meta.xml
<CustomObject>
    <label>Segmentación</label>
    <nameField>
        <displayFormat>Segmentacion-{0000}</displayFormat>
        <label>Segmentación Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profesional de la Salud, Otro Profesional</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segmentaciones</relationshipLabel>
    <relationshipName>Segmentaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/recordTypes/Adultos.recordType-meta.xml
<RecordType>
    <fullName>Adultos</fullName>
    <active>false</active>
    <label>Adultos</label>
</RecordType>

force-app/main/default/objects/VisMed_Segmentacion__c/recordTypes/Adultos_General_Institucion.recordType-meta.xml
<RecordType>
    <fullName>Adultos_General_Institucion</fullName>
    <active>true</active>
    <label>Adultos General Institucion</label>
</RecordType>

force-app/main/default/globalValueSets/Sub_Equipo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Adultos Interior</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos Oncologia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos</fullName>
    </customValue>
    <customValue>
        <fullName>Dieta</fullName>
    </customValue>
    <customValue>
        <fullName>Pediatricos General</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos AMBA</fullName>
    </customValue>
    <customValue>
        <fullName>Metabólicos y Dieta</fullName>
    </customValue>
    <customValue>
        <fullName>Nicho MSL</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos General</fullName>
        <isActive>false</isActive>
        <label>Adultos General</label>
    </customValue>
    <masterLabel>Sub Equipo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MassApprovalComponentControllerTest.cls
@isTest public with sharing class MassApprovalComponentControllerTest {
    @testSetup
    private static void testSetup() {
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile profile1 = [Select Id from Profile where Name = 'System Administrator' or name = 'Administrador del sistema' ];

        User userOwner = Build.aUser()
                .withUsername(
                    'newuser'+String.valueOf(System.now().getTime() + (Math.random() * 10))+'@testorg.com'
                )               
                .withEmail('owner@xappia.com')
                .withAlias('owner')
                .withLastName('Owner')
                .withTimeZoneSidKey('America/Argentina/Buenos_Aires')
                .withLocaleSidKey('es_AR')
                .withCommunityNickname('prueba2.xappia')
                .withEmailEncodingKey('ISO-8859-1')
                .withProfileId(profile1.Id)
                .withUserRoleId(portalRole)				
                .withLanguageLocaleKey('es')
                .build();           
        userOwner.ManagerId = UserInfo.getUserId();
        userOwner.IsActive = true;
        userOwner.VisMed_ContrasenaApp__c = 'TestOwner';
        insert userOwner;

        System.runAs(userOwner){
            Account account = Build.anAccount()
            .withName('Institucion')					
            .build();

            insert account;
            
            Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Visitador Medico').getRecordTypeId();
            Contact aContactOne = Build.aContact()
                .withAccount(account)
                .withFirstName('NameOne')
                .withLastName('LastnameOne')
                .build();
            
            aContactOne.RecordTypeId = recordTypeId;
            aContactOne.VisMed_DNI__c = '23555777';
            insert aContactOne;
            Contact apm = Build.aContact()
                .withAccount(account)
                .withFirstName('NameTwo')
                .withLastName('LastnameTwo')
                .build();     
            
            apm.RecordTypeId = recordTypeId;
            apm.VisMed_DNI__c = '23234324';
            apm.Sub_Equipo__c = 'Metabólicos y Dieta';
            insert apm;

            Profile perfil = [
                SELECT Id 
                FROM Profile 
                WHERE Name = 'Supervisores' 
                LIMIT 1
            ];

            User userApproval = Build.aUser()
                .withUsername(
                    'newuser'+String.valueOf(System.now().getTime() + (Math.random() * 10))+'@testorg.com'
                )            
                .withLastName('Approval')
                .withEmail('approval@xappia.com')
                .withAlias('appro')
                .withTimeZoneSidKey('America/Argentina/Buenos_Aires')
                .withLocaleSidKey('es_AR')
                .withCommunityNickname('approval.xappia')
                .withEmailEncodingKey('ISO-8859-1')
                .withProfileId(perfil.Id)
                .withLanguageLocaleKey('es')
                .build();

            userApproval.IsActive = true;
            userApproval.VisMed_ContrasenaApp__c = 'appro';

            insert userApproval;

            Profile perfilApm = [
                SELECT Id 
                FROM Profile 
                WHERE Name = 'APM' 
                LIMIT 1
            ];
            User userTest = Build.aUser()
                .withUsername(
                    'newuser'+String.valueOf(System.now().getTime() + (Math.random() * 10))+'@testorg.com'
                )
                .withContactId(apm)
                .withLastName('Contacto1')
                .withEmail('contacto1@xappia.com')
                .withAlias('contact1')
                .withTimeZoneSidKey('America/Argentina/Buenos_Aires')
                .withLocaleSidKey('es_AR')
                .withCommunityNickname('prueba1.xappia')
                .withEmailEncodingKey('ISO-8859-1')
                .withProfileId(perfilApm.Id)
                .withLanguageLocaleKey('es')
                .build();

            userTest.IsActive = true;
            userTest.VisMed_Es_un_Visitador_Medico__c = true;
            //userTest.IsPortalEnabled = true;
            userTest.VisMed_ContrasenaApp__c = 'Test';
            userTest.ManagerId = userApproval.Id;
            userTest.DelegatedApproverId = userApproval.Id;

            insert userTest;

            Id recordTypeProfesional = [SELECT Id, Name, SobjectType,IsPersonType 
            FROM RecordType 
            WHERE SobjectType='Account' AND IsPersonType=True AND Name = 'Profesional de la Salud'].Id;
            Account aPersonAccount = Build.aPersonalAccount()
                .withFirstName('Profesional')                
                .build();
            aPersonAccount.RecordTypeId = recordTypeProfesional;
            insert aPersonAccount;
            Account profesional = Build.aPersonalAccount()
                .withFirstName('Profesional')                
                .build();
            aPersonAccount.RecordTypeId = recordTypeProfesional;
            insert profesional;

            Id recordTypeAlergia = Schema.SObjectType.VisMed_Segmentacion__c.getRecordTypeInfosByDeveloperName().get('Adultos_General_Institucion').getRecordTypeId();
            VisMed_Segmentacion__c segmentacion = new VisMed_Segmentacion__c(
                Profesional__c = aPersonAccount.id,                
                RecordTypeId = recordTypeAlergia
            );
            insert segmentacion;

            Date today = Date.today();
            VisMed_Ciclo__c ciclo = Build.aCiclo()
            .withFechaInicio(today.toStartOfMonth())
            .withFechaFin(today.toStartOfMonth().addMonths(1).addDays(-1))
            .build();
            insert ciclo;

            Dan360_Efectividad__c efectividad = Build.aDan360Efectividad()
            .withVisMedAPM(apm)
            .withVisMedCiclo(ciclo)
            .build();
            efectividad.Fecha_de_Fin__c = Date.today().toStartOfMonth();
            efectividad.Fecha_de_inicio__c = Date.today().toStartOfMonth().addMonths(1).addDays(-1);
            insert efectividad;
        
        Id recordTypeLicencia = Schema.SObjectType.Dan360_Licencia__c.getRecordTypeInfosByDeveloperName().get('Licencia').getRecordTypeId();
        Dan360_Licencia__c licencia = new Dan360_Licencia__c(
            Fecha_de_inicio__c = Date.Today().addDays(1),
            Fecha_de_Fin__c = Date.Today().addDays(1),
            Efectividad__c = efectividad.Id,
            Motivo__c = 'Día de estudio',
            Estado__c = 'Pendiente',
            VisMed_APM__c = apm.Id,            
            RecordTypeId = recordTypeLicencia
        );
        insert licencia;

        Id recordTypeProfesionalBaja = [SELECT Id, Name, SobjectType,IsPersonType 
            FROM RecordType 
            WHERE SobjectType='VisMed_Bajas__c' AND Name = 'Profesional de la Salud'].Id;

        VisMed_Bajas__c baja = Build.aVisMedBajasProfesionaldelaSalud()
            .withProfesional(profesional)
            .withVisMedAPM(apm)
            .build();
        baja.RecordTypeId = recordTypeProfesionalBaja;
        insert baja;

        Datetime dt = System.now().addDays(1);
        Date dateVisita;
        System.debug(dt.format('EEEE'));
        if(dt.format('EEEE')== 'Sunday' || dt.format('EEEE')== 'Saturday'){
            System.debug(dt.format('EEEE'));
            dateVisita = dt.date().addDays(2);
        }
        else{
            dateVisita = dt.date();
        }


        Dan360_Interacciones__c visita = Build.aDan360Interacciones()
            .withProfesional(aPersonAccount)
            .withAPM(apm)
            .withVisMedTipodeVisita('Presencial')
            .withVisMedEfectividad(efectividad)
            .withDomiciliodelaVisita(account)
            .withVisMedFecha(dateVisita)
            .build();

            insert visita;
            
            VisMed_Contacto_Cuenta_Usuario__c seguimiento = Build.aVisMedContactCuentaUsuarioBuilder()
                .withAPM(apm)
                .withProfesional(aPersonAccount)
                .withInstitucion(account)
                .withEstado('Pendiente')
                .withSegmentaPor('Adultos General Institucion')
                .build();
            seguimiento.Aprobador_Final__c = userTest.Id;    
            insert seguimiento;
        }
    }
    @isTest
    private static void updateSeguimientoCuandoEsAprobado() {
        // Test data setup
        String objeto = 'VisMed_Contacto_Cuenta_Usuario__c';
        String estado;
        List<String> recordsId = new List<String>();
        VisMed_Contacto_Cuenta_Usuario__c seguimientoToUpdate = [
            SELECT Id, Estado__c 
            FROM VisMed_Contacto_Cuenta_Usuario__c
            WHERE Estado__c = 'Pendiente'
        ];
        recordsId.add(seguimientoToUpdate.id);
        estado = 'Aprobada';
        // Actual test
        Test.startTest();
        List<MassApprovalComponentController.ObjectWrapper> result = MassApprovalComponentController.updateRecord(recordsId, objeto, '', estado, '');
        Test.stopTest();

        System.assertEquals(0, result.size(), 'Error al aprobar Alta');        
    }
    @isTest
    private static void updateSeguimientoCuandoEsRechazado() {
        // Test data setup
        String objeto = 'VisMed_Contacto_Cuenta_Usuario__c';
        String estado;
        List<String> recordsId = new List<String>();
        VisMed_Contacto_Cuenta_Usuario__c seguimientoToUpdate = [
            SELECT Id, Estado__c 
            FROM VisMed_Contacto_Cuenta_Usuario__c
            WHERE Estado__c = 'Pendiente'
        ];
        recordsId.add(seguimientoToUpdate.id);
        estado = 'Rechazado';
        // Actual test
        Test.startTest();
        List<MassApprovalComponentController.ObjectWrapper> result = MassApprovalComponentController.updateRecord(recordsId, objeto, '', estado, '');
        Test.stopTest();

        System.assertEquals(0, result.size(), 'Error al aprobar Alta');        
    }
    @isTest
    private static void getUserDebeDevolverUsuariosRelacionadosAlSupervisor() {
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
    system.runAs(userOwner){          
        String supervisor = [
            SELECT Id
            FROM User
            WHERE Alias = 'appro' AND Profile.Name = 'Supervisores'
        ].Id;       
        
        // Actual test
        Test.startTest();
        List<user> result = MassApprovalComponentController.getUser(supervisor);
        Test.stopTest();

        System.assertEquals(1, result.size(), 'Error al obtener usuario');  
    }      
    }
    @isTest
    private static void getDataDebeDevolverUnaListaDeFicheros() {
        // Test data setup        
        Id user = UserInfo.getUserId();
        String objeto = 'VisMed_Contacto_Cuenta_Usuario__c';
        List<String> users = new List<String>();
        users.add(user);

        Contact apm = [
            SELECT Id
            FROM Contact
            WHERE VisMed_DNI__c = '23234324'
        ];
       
        // Actual test
        Test.startTest();
        List<MassApprovalComponentController.ObjectWrapper> result = MassApprovalComponentController.getData(objeto,'','',user,users,'','');
        Test.stopTest();

        VisMed_Contacto_Cuenta_Usuario__c seguimiento = [
            SELECT Id
            FROM VisMed_Contacto_Cuenta_Usuario__c
            WHERE VisMed_APM__c = :apm.Id
        ];

        System.assertEquals(1, result.size(), 'Error al obtener data');
        System.assertEquals(seguimiento.Id, result[0].Id, 'Error al obtener seguimiento');       
    }
    @isTest
    private static void getDataDebeDevolverUnaListaDeLicencias() {
        // Test data setup        
        Id user = UserInfo.getUserId();
        String objeto = 'Dan360_Licencia__c';
        List<String> users = new List<String>();
        users.add(user);

        Contact apm = [
            SELECT Id
            FROM Contact
            WHERE VisMed_DNI__c = '23234324'
        ];
       
        // Actual test
        Test.startTest();
        List<MassApprovalComponentController.ObjectWrapper> result = MassApprovalComponentController.getData(objeto,'','',user,users,'','');
        Test.stopTest();

        Dan360_Licencia__c licencia = [
            SELECT Id
            FROM Dan360_Licencia__c
            WHERE VisMed_APM__c = :apm.Id
        ];

        System.assertEquals(1, result.size(), 'Error al obtener data');
        System.assertEquals(licencia.Id, result[0].Id, 'Error al obtener licencia');
    }
    @isTest
    private static void getDataDebeDevolverUnaListaDeVisitas() {
        // Test data setup        
        Id user = UserInfo.getUserId();
        String objeto = 'Dan360_Interacciones__c';
        List<String> users = new List<String>();
        users.add(user);
        
        Contact apm = [
            SELECT Id
            FROM Contact
            WHERE VisMed_DNI__c = '23234324'
        ];
        // Actual test
        Test.startTest();
        List<MassApprovalComponentController.ObjectWrapper> result = MassApprovalComponentController.getData(objeto,'','',user,users,'','');
        Test.stopTest();

        Dan360_Interacciones__c visita = [
            SELECT Id
            FROM Dan360_Interacciones__c
            WHERE VisMed_APM__c = :apm.Id
        ];

        System.assertEquals(1, result.size(), 'Error al obtener data'); 
        System.assertEquals(visita.Id, result[0].Id, 'Error al obtener visita');       
    }
    @isTest
    private static void getDataDebeDevolverUnaListaDeBajas() {
        // Test data setup        
        Id user = UserInfo.getUserId();
        String objeto = 'VisMed_Bajas__c';
        List<String> users = new List<String>();
        users.add(user);
        Contact apm = [
            SELECT Id
            FROM Contact
            WHERE VisMed_DNI__c = '23234324'
        ];
        // Actual test
        Test.startTest();
        List<MassApprovalComponentController.ObjectWrapper> result = MassApprovalComponentController.getData(objeto,'','',user,users,'','');
        Test.stopTest();
        VisMed_Bajas__c baja = [
            SELECT Id
            FROM VisMed_Bajas__c
            WHERE VisMed_APM__c = :apm.Id
        ];
        System.assertEquals(1, result.size(), 'Error al obtener data');
        System.assertEquals(baja.Id, result[0].Id, 'Error al obtener baja');       
    }
}