force-app/main/default/objects/Account/fields/NIC__c.field-meta.xml
<CustomField>
    <fullName>NIC__c</fullName>
    <label>Numero de NIC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Obra_social__c.field-meta.xml
<CustomField>
    <fullName>Obra_social__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Obra social</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Obra social</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuenta</relationshipLabel>
    <relationshipName>Cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Cantidad_porciones_receta__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_porciones_receta__c</fullName>
    <description>Cantidad de porciones de cada receta oncología portal pacientes</description>
    <label>Cantidad porciones receta</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Consejos__c.field-meta.xml
<CustomField>
    <fullName>Consejos__c</fullName>
    <description>Consejos de artículo (Ejercicios)</description>
    <label>Consejos</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Consejos_recetas__c.field-meta.xml
<CustomField>
    <fullName>Consejos_recetas__c</fullName>
    <description>consejos de recetas oncologia portal pacientes</description>
    <label>Consejos recetas</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <description>Descripción del articulo en Portal de Pacientes</description>
    <label>Descripción</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Ejercicio__c.field-meta.xml
<CustomField>
    <fullName>Ejercicio__c</fullName>
    <description>Nombre de ejercicio de actividad fisica</description>
    <label>Ejercicio</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Historia_tecnica_peinado__c.field-meta.xml
<CustomField>
    <fullName>Historia_tecnica_peinado__c</fullName>
    <label>Historia técnica peinado</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Imagen__c.field-meta.xml
<CustomField>
    <fullName>Imagen__c</fullName>
    <description>imagen de artículo en Portal de Pacientes</description>
    <label>Imagen</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Imagen_alergenos__c.field-meta.xml
<CustomField>
    <fullName>Imagen_alergenos__c</fullName>
    <label>Imagen alergenos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Imagen_producto__c.field-meta.xml
<CustomField>
    <fullName>Imagen_producto__c</fullName>
    <description>Imagen de producto para descripcion receta</description>
    <label>Imagen producto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Ingredientes_de_recetas__c.field-meta.xml
<CustomField>
    <fullName>Ingredientes_de_recetas__c</fullName>
    <description>Ingredientes para Recetas de Portal de Pacientes</description>
    <label>Ingredientes de recetas</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Preparacion_receta__c.field-meta.xml
<CustomField>
    <fullName>Preparacion_receta__c</fullName>
    <description>Preparación de receta</description>
    <label>Preparación receta</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tiempo_preparacion_receta__c.field-meta.xml
<CustomField>
    <fullName>Tiempo_preparacion_receta__c</fullName>
    <description>Tiempo de preparación de receta oncología portal pacientes</description>
    <label>Tiempo preparación receta</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tipo_de_articulo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_articulo__c</fullName>
    <description>Tipos de artículos para el Portal de Pacientes</description>
    <label>Tipo de Artículo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Técnicas de belleza (Oncología)</fullName>
            </value>
            <value>
                <fullName>Recetas (Oncología)</fullName>
            </value>
            <value>
                <fullName>Ejercicios (Oncología)</fullName>
            </value>
            <value>
                <fullName>Recetas (Terapia Cetogénica)</fullName>
            </value>
            <value>
                <fullName>Recetas (Disfagia)</fullName>
            </value>
            <value>
                <fullName>Recetas (Alergia)</fullName>
            </value>
            <value>
                <fullName>Videos (Terapia Cetogénca)</fullName>
            </value>
            <value>
                <fullName>Recetas</fullName>
                <isActive>false</isActive>
                <label>Recetas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tipo_de_receta__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_receta__c</fullName>
    <description>Tipos de recetas</description>
    <label>Tipo de receta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sopas</fullName>
            </value>
            <value>
                <fullName>Principales</fullName>
            </value>
            <value>
                <fullName>Bebidas</fullName>
            </value>
            <value>
                <fullName>Postres</fullName>
            </value>
            <value>
                <fullName>Desayuno</fullName>
            </value>
            <value>
                <fullName>Merienda</fullName>
            </value>
            <value>
                <fullName>Almuerzo</fullName>
            </value>
            <value>
                <fullName>Cena</fullName>
            </value>
            <value>
                <fullName>Salado</fullName>
            </value>
            <value>
                <fullName>Mayores a 6 meses</fullName>
            </value>
            <value>
                <fullName>Mayores a 12 meses</fullName>
            </value>
            <value>
                <fullName>4:1</fullName>
            </value>
            <value>
                <fullName>2.5:1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/URL_Video__c.field-meta.xml
<CustomField>
    <fullName>URL_Video__c</fullName>
    <description>Videos de recetas</description>
    <label>URL Video</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NIC_Envio__c/NIC_Envio__c.object-meta.xml
<CustomObject>
    <label>NIC Envío</label>
    <nameField>
        <displayFormat>ENV - {0000000}</displayFormat>
        <label>Nombre de Envío</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NIC Envíos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NIC_Envio__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NIC Envíos</relationshipLabel>
    <relationshipName>NIC_Envios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NIC_Envio__c/fields/Direccion_de_Envio__c.field-meta.xml
<CustomField>
    <fullName>Direccion_de_Envio__c</fullName>
    <label>Dirección de Envío</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/NIC_Envio__c/fields/Link_Seguimiento_completo__c.field-meta.xml
<CustomField>
    <fullName>Link_Seguimiento_completo__c</fullName>
    <formula>&apos;http://www.cruzdelsur.com/herramientas_seguimiento_resultado.php?nic=&apos;+ NIC__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Link Seguimiento completo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NIC_Envio__c/fields/Localidad_de_Envio__c.field-meta.xml
<CustomField>
    <fullName>Localidad_de_Envio__c</fullName>
    <label>Localidad de Envío</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NIC_Envio__c/fields/NIC__c.field-meta.xml
<CustomField>
    <fullName>NIC__c</fullName>
    <externalId>true</externalId>
    <label>NIC</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ArticulosPortalPacientesController.cls
public without sharing class ArticulosPortalPacientesController {

    @AuraEnabled(cacheable=true)
    public static List<Knowledge__kav> getTecnicasDeBellezaOncologia() {

        List<Knowledge__kav> tecnicas = [
            SELECT  Id, Title, Descripcion__c, Imagen__c, Historia_tecnica_peinado__c
            FROM    Knowledge__kav
            WHERE   Tipo_de_articulo__c = 'Técnicas de belleza (Oncología)' AND
                    PublishStatus = 'Online'
        ];

        return tecnicas;

    }

    @AuraEnabled(cacheable=true)
    public static List<Knowledge__kav> getEjercicios(String tipoEjercicio) {
        String query = 'SELECT Id, Title, Descripcion__c, Imagen__c, Consejos__c, Ejercicio__c FROM Knowledge__kav WHERE Tipo_de_articulo__c = \'Ejercicios (Oncología)\' AND PublishStatus = \'Online\' AND Ejercicio__c = \'' + String.escapeSingleQuotes(tipoEjercicio) + '\'';

        return Database.query(query);
    }

    @AuraEnabled(cacheable=true)
    public static List<Knowledge__kav> getTiposDeEjerciciosOncologia() {
        Map<String,Knowledge__kav> mapArticulos = new Map<String,Knowledge__kav>();

        List<Knowledge__kav> ejercicios = [
            SELECT  Ejercicio__c, Imagen__c
            FROM    Knowledge__kav
            WHERE   Tipo_de_articulo__c = 'Ejercicios (Oncología)' AND
                    PublishStatus = 'Online'
        ];

        for (Knowledge__kav ejercicio : ejercicios) {
            if(!mapArticulos.containsKey(ejercicio.Ejercicio__c)){
                mapArticulos.put(ejercicio.Ejercicio__c, ejercicio);
            }
        }

        return mapArticulos.values();
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getTiposDeRecetaOncologia() {
        List<String> tiposDeRecetas = new List<String>();

        List<Knowledge__kav> recetas = [
            SELECT  Tipo_de_receta__c
            FROM    Knowledge__kav
            WHERE   Tipo_de_articulo__c = 'Recetas (Oncología)' AND
                    PublishStatus = 'Online'
        ];

        for (Knowledge__kav receta : recetas) {
            if(!tiposDeRecetas.contains(receta.Tipo_de_receta__c)){
                tiposDeRecetas.add(receta.Tipo_de_receta__c);
            }
        }

        return tiposDeRecetas;
    }

    @AuraEnabled(cacheable=true)
    public static List<Knowledge__kav> getRecetasOncologia(String tipoDeReceta) {
        String tipoArticulo = 'Recetas (Oncología)';
        String publishStatus = 'Online';
        String query = 'SELECT Id, Title, Tipo_de_receta__c, Imagen__c FROM Knowledge__kav WHERE ';
        String condicion = (String.isNotBlank(tipoArticulo) ? 'Tipo_de_articulo__c = \'' + tipoArticulo + '\'' : '');
        condicion += (String.isNotBlank(publishStatus) ? ' AND PublishStatus = \'' + publishStatus + '\'' : '');
        condicion += (String.isNotBlank(tipoDeReceta) ? ' AND Tipo_de_receta__c = \'' + String.escapeSingleQuotes(tipoDeReceta) + '\'' : '');
        query += + condicion;

        return Database.query(query);
    }

    @AuraEnabled(cacheable=true)
    public static Knowledge__kav getRecetaOncologia(String tituloReceta) {
        String query = 'SELECT Title, Imagen__c, Ingredientes_de_recetas__c, Preparacion_receta__c, Tipo_de_receta__c, Consejos_recetas__c, Cantidad_porciones_receta__c, Tiempo_preparacion_receta__c FROM Knowledge__kav WHERE Tipo_de_articulo__c = \'Recetas (Oncología)\' AND PublishStatus = \'Online\' AND Title = \'' + String.escapeSingleQuotes(tituloReceta) + '\' LIMIT 1';

        return Database.query(query);
    }

    @AuraEnabled(cacheable=true)
    public static List<Knowledge__kav> getDescubriRecetasOncologia() {

        List<Knowledge__kav> recetas = [
            SELECT  Title, Imagen__c, Tipo_de_receta__c
            FROM    Knowledge__kav
            WHERE   Tipo_de_articulo__c = 'Recetas (Oncología)' AND
                    PublishStatus = 'Online'
            LIMIT 3
        ];

        return recetas;
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getTiposDeRecetaAlergia() {
        List<String> tiposDeRecetas = new List<String>();

        List<Knowledge__kav> recetas = [
            SELECT  Tipo_de_receta__c
            FROM    Knowledge__kav
            WHERE   Tipo_de_articulo__c = 'Recetas (Alergia)' AND
                    PublishStatus = 'Online'
        ];

        for (Knowledge__kav receta : recetas) {
            if(!tiposDeRecetas.contains(receta.Tipo_de_receta__c)){
                tiposDeRecetas.add(receta.Tipo_de_receta__c);
            }
        }

        return tiposDeRecetas;
    }

    @AuraEnabled(cacheable=true)
    public static List<Knowledge__kav> getRecetasDeTipoAlergia(String tipoReceta) {
        String tipoArticulo = 'Recetas (Alergia)';
        String publishStatus = 'Online';
        String query = 'SELECT Id, Title, Imagen__c FROM Knowledge__kav WHERE ';
        String condicion = (String.isNotBlank(tipoArticulo) ? 'Tipo_de_articulo__c = \'' + tipoArticulo + '\'' : '');
        condicion += (String.isNotBlank(publishStatus) ? ' AND PublishStatus = \'' + publishStatus + '\'' : '');
        condicion += (String.isNotBlank(tipoReceta) ? ' AND Tipo_de_receta__c = \'' + String.escapeSingleQuotes(tipoReceta) + '\'' : '');
        query += + condicion;
        List<Knowledge__kav> recetas = Database.query(query);

        return recetas;
    }

    @AuraEnabled(cacheable=true)
    public static Knowledge__kav getRecetaAlergia(String tituloReceta) {
        String tipoArticulo = 'Recetas (Alergia)';
        String publishStatus = 'Online';
        String query = 'SELECT  Title, Imagen__c, Ingredientes_de_recetas__c, Preparacion_receta__c, Tipo_de_receta__c, Consejos_recetas__c, Imagen_alergenos__c, Imagen_producto__c FROM Knowledge__kav WHERE ';
        String condicion = (String.isNotBlank(tipoArticulo) ? 'Tipo_de_articulo__c = \'' + tipoArticulo + '\'' : '');
        condicion += (String.isNotBlank(publishStatus) ? ' AND PublishStatus = \'' + publishStatus + '\'' : '');
        condicion += (String.isNotBlank(tituloReceta) ? ' AND Title = \'' + String.escapeSingleQuotes(tituloReceta) + '\'' : '');
        query += + condicion;
        List<Knowledge__kav> recetas = Database.query(query);

        if(!recetas.isEmpty()){
            return recetas.get(0);
        }
        else {
            return null;
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Knowledge__kav> getRecetasDisfagia() {
        List<Knowledge__kav> recetas = [
            SELECT  Id, Title, Tipo_de_receta__c, URL_Video__c
            FROM    Knowledge__kav
            WHERE   Tipo_de_articulo__c = 'Recetas (Disfagia)' AND
                    PublishStatus = 'Online'
        ];

        return recetas;
    }

    @AuraEnabled(cacheable=true)
    public static List<Knowledge__kav> getVideosTerapiaCetogenica() {
        String tipoArticulo = 'Videos (Terapia Cetogénca)';
        String publishStatus = 'Online';
        String query = 'SELECT Id, Title, URL_Video__c FROM Knowledge__kav WHERE ';
        String condicion = (String.isNotBlank(tipoArticulo) ? 'Tipo_de_articulo__c = \'' + tipoArticulo + '\'' : '');
        condicion += (String.isNotBlank(publishStatus) ? ' AND PublishStatus = \'' + publishStatus + '\'' : '');
        query += + condicion;
        List<Knowledge__kav> videos = Database.query(query);
        
        return videos;
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getTiposRecetasTerapiaCetogenica() {
        List<String> tiposDeRecetas = new List<String>();

        String tipoArticulo = 'Recetas (Terapia Cetogénica)';
        String publishStatus = 'Online';
        String query = 'SELECT Id, Tipo_de_receta__c FROM Knowledge__kav WHERE ';
        String condicion = (String.isNotBlank(tipoArticulo) ? 'Tipo_de_articulo__c = \'' + tipoArticulo + '\'' : '');
        condicion += (String.isNotBlank(publishStatus) ? ' AND PublishStatus = \'' + publishStatus + '\'' : '');
        query += + condicion;
        List<Knowledge__kav> recetas = Database.query(query);

        for (Knowledge__kav receta : recetas) {
            if(!tiposDeRecetas.contains(receta.Tipo_de_receta__c)){
                tiposDeRecetas.add(receta.Tipo_de_receta__c);
            }
        }

        return tiposDeRecetas;
    }

    @AuraEnabled(cacheable=true)
    public static List<Knowledge__kav> getRecetasTerapiaCetogenica(String tipoReceta) {
        String tipoArticulo = 'Recetas (Terapia Cetogénica)';
        String publishStatus = 'Online';
        String query = 'SELECT Id, Title, Tipo_de_receta__c, Imagen__c, URL_Video__c, Imagen_producto__c, Ingredientes_de_recetas__c, Preparacion_receta__c FROM Knowledge__kav WHERE ';
        String condicion = (String.isNotBlank(tipoArticulo) ? 'Tipo_de_articulo__c = \'' + tipoArticulo + '\'' : '');
        condicion += (String.isNotBlank(publishStatus) ? ' AND PublishStatus = \'' + publishStatus + '\'' : '');
        condicion += (String.isNotBlank(tipoReceta) ? ' AND Tipo_de_receta__c = \'' + String.escapeSingleQuotes(tipoReceta) + '\'' : '');
        query += + condicion;
        List<Knowledge__kav> recetas = Database.query(query);
        
        return recetas;
    }

    @AuraEnabled(cacheable=true)
    public static List<NIC_Envio__c> getPedidos(String userId) {
        String queryUsers = 'SELECT AccountId FROM User WHERE Id = \'' + String.escapeSingleQuotes(userId) + '\'';
        List<User> users = Database.query(queryUsers);

        if(!users.isEmpty()){
            Id accountId = users.get(0).AccountId;

            List<NIC_Envio__c> envios = [
                SELECT  Name, Link_Seguimiento_completo__c, Cuenta__r.Name, Direccion_de_Envio__c, Localidad_de_Envio__c, NIC__c, CreatedDate
                FROM    NIC_Envio__c
                WHERE   Cuenta__c =: accountId
            ];

            return envios;
        }

        return null;
    }

}