force-app/main/default/objects/Account/fields/Obra_social__c.field-meta.xml
<CustomField>
    <fullName>Obra_social__c</fullName>
    <label>Nombre de la obra social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tratamiento__c/Tratamiento__c.object-meta.xml
<CustomObject>
    <label>Tratamiento</label>
    <nameField>
        <displayFormat>TRAT-{0000}</displayFormat>
        <label>Nro de Tratamiento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tratamientos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tratamiento__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tratamiento__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tratamientos</relationshipLabel>
    <relationshipName>Tratamientos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tratamiento__c/fields/Obra_social__c.field-meta.xml
<CustomField>
    <fullName>Obra_social__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Obra social</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Obra social</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tratamientos</relationshipLabel>
    <relationshipName>Tratamientos3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TratamientoTriggerHelper.cls
public class TratamientoTriggerHelper {
    
    public static void updateAccountsAndTratamientos(List<Tratamiento__c> tratamientoList){
        
        List<id> accountsId = new List<id>();
        List<Account> accountsList = new List<Account>();   
        Map<id, Tratamiento__c> mapTratamiento= new Map<id, Tratamiento__c>();
        List<Tratamiento__c> tratListDb = new List<Tratamiento__c>();   
        
        for(Tratamiento__c trat : tratamientoList){
            
            if(trat.Obra_social__c!=null && trat.Activo__c){
                
                mapTratamiento.put(trat.Cuenta__c, trat);
                accountsId.add(trat.Cuenta__c);
                
            }
        }
        
        List<Account> accList = [
            SELECT id, Obra_social__pc
            FROM Account
            WHERE id IN :accountsId
        ];
        
        List<Tratamiento__c> tratListInAccount = [
            SELECT id, cuenta__c,Activo__c,Name
            FROM Tratamiento__c
            WHERE cuenta__c IN :accList
        ];
        
        if(tratListInAccount.size()>0){          
            for(Tratamiento__c tr: tratListInAccount){
                
                tratListDb.add(tr);
                tr.Activo__c =false;
                
            }
        }        
        
        for(Account acc: accList){
            
            Tratamiento__c trat = mapTratamiento.get(acc.id);
            
            acc.Obra_social__pc = trat.Obra_social__c;
            
            accountsList.add(acc);
        }
        if(tratListInAccount.size()>0){
            update tratListInAccount;
        }
        if(accountsList.size()>0){
            update accountsList;
        }
        
    }
    
      public static void updateAccount(List<Tratamiento__c> tratamientoList){
        
        List<id> accountsId = new List<id>();
        List<Account> accountsList = new List<Account>();   
        Map<id, Tratamiento__c> mapTratamiento= new Map<id, Tratamiento__c>();
        List<Tratamiento__c> tratListDb = new List<Tratamiento__c>();   
        
        for(Tratamiento__c trat : tratamientoList){           
            if(trat.Obra_social__c!=null && trat.Activo__c){
                mapTratamiento.put(trat.Cuenta__c,trat);
                accountsId.add(trat.Cuenta__c);
            }
        }
        
        List<Account> accList = [
            SELECT id, Obra_social__pc
            FROM Account
            WHERE id IN :accountsId
        ];
              
        for(Account acc: accList){           
            Tratamiento__c trat = mapTratamiento.get(acc.id);
            if(trat!=null){  
                acc.Obra_social__pc = trat.Obra_social__c;
            }
            accountsList.add(acc);
        }
        if(accountsList.size()>0){
            update accountsList;
        }
        
    }
    
}