force-app/main/default/objects/Account/fields/Obra_social__c.field-meta.xml
<CustomField>
    <fullName>Obra_social__c</fullName>
    <label>Nombre de la obra social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tratamiento__c/Tratamiento__c.object-meta.xml
<CustomObject>
    <label>Tratamiento</label>
    <nameField>
        <displayFormat>TRAT-{0000}</displayFormat>
        <label>Nro de Tratamiento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tratamientos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tratamiento__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tratamiento__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tratamientos</relationshipLabel>
    <relationshipName>Tratamientos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tratamiento__c/fields/Obra_social__c.field-meta.xml
<CustomField>
    <fullName>Obra_social__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Obra social</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Obra social</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tratamientos</relationshipLabel>
    <relationshipName>Tratamientos3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TratamientoTriggerTest.cls
@isTest
public class TratamientoTriggerTest {

    @isTest
    static void siSeInsertaUnNuevoTratamientoSeDesactivanLosOtrosYseSeteaLaObraSocialEnCuenta(){
        
        Account accTest = New Account();
      	accTest.LastName = 'test Name';  
      
        insert accTest;
        
        Account obraSocialTest = Build.anAccountObrasocial()
            .Build();
        obraSocialTest.name = 'test ob';
        insert obraSocialTest;
        
        Tratamiento__c tratTest1 = new Tratamiento__c();
        tratTest1.Cuenta__c = accTest.id;
        tratTest1.Activo__c = true;
        tratTest1.Obra_social__c = obraSocialTest.id;
        
        insert tratTest1;
        
        Tratamiento__c tratTest2 = new Tratamiento__c();
        tratTest2.Cuenta__c = accTest.id;
        tratTest2.Activo__c = true;
        tratTest2.Obra_social__c = obraSocialTest.id;
        
        insert tratTest2;
 
        Test.startTest();
        
        Tratamiento__c tratTest = new Tratamiento__c();
        tratTest.Cuenta__c = accTest.id;
        tratTest.Activo__c = true;
        tratTest.Obra_social__c = obraSocialTest.id;
        
        insert tratTest;
        
        Test.stopTest();
        
        Account accDB = [
            SELECT id, Obra_social__pc
            FROM Account
            WHERE id =:accTest.id
        ];
        
        List<Tratamiento__c> tratListDb = [
            SELECT id , Activo__c
            FROM Tratamiento__c
            WHERE Cuenta__c = :accTest.id
        ];

          System.assertEquals(obraSocialTest.id, accDB.Obra_social__pc);
          System.assertEquals(false, tratListDb.get(0).Activo__c);
          System.assertEquals(false, tratListDb.get(1).Activo__c);
    }
    
    
    @isTest
    static void siSeActualizaLaObraSocialDelTratamientoSeModificaElLookupEnCuenta(){
        
        Account accTest = New Account();
      	accTest.LastName = 'test Name';  
      
        insert accTest;
        
        Account obraSocialTest = Build.anAccountObrasocial()
            .Build();
        obraSocialTest.name = 'test ob';
        
        insert obraSocialTest;
        
        Account obraSocialTest2 = Build.anAccountObrasocial()
            .Build();
        obraSocialTest2.name = 'test ob2';
        
        insert obraSocialTest2;
        
        Tratamiento__c tratTest1 = new Tratamiento__c();
        tratTest1.Cuenta__c = accTest.id;
        tratTest1.Activo__c = true;
        tratTest1.Obra_social__c = obraSocialTest.id;
        
        insert tratTest1;
        
        Tratamiento__c tratTest2 = new Tratamiento__c();
        tratTest2.Cuenta__c = accTest.id;
        tratTest2.Activo__c = true;
        tratTest2.Obra_social__c = obraSocialTest.id;
        
        insert tratTest2;
 
        Test.startTest();
        
        tratTest2.Obra_social__c = obraSocialTest2.id;
		update tratTest2;
        
        Test.stopTest();
        
        Account accDB = [
            SELECT id, Obra_social__pc
            FROM Account
            WHERE id =:accTest.id
        ];
        
          System.assertEquals(obraSocialTest2.id, accDB.Obra_social__pc);

    }
    
}