force-app/main/default/objects/Account/fields/Productos_activos_compania__c.field-meta.xml
<CustomField>
    <fullName>Productos_activos_compania__c</fullName>
    <label>Productos activos compañía</label>
    <summarizedField>Modulo_de_paciente__c.Cont_Productos_Activos_Compania__c</summarizedField>
    <summaryFilterItems>
        <field>Modulo_de_paciente__c.Estado__c</field>
        <operation>equals</operation>
        <value>Activo</value>
    </summaryFilterItems>
    <summaryForeignKey>Modulo_de_paciente__c.Cuenta__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/Modulo_de_paciente__c.object-meta.xml
<CustomObject>
    <label>Modulo de paciente</label>
    <nameField>
        <displayFormat>MDP-{0000}</displayFormat>
        <label>Nro de Modulo de paciente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modulos de paciente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Cont_Productos_Activos_Compania__c.field-meta.xml
<CustomField>
    <fullName>Cont_Productos_Activos_Compania__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Productos Activos Compañia</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modulo_de_paciente__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado de Servicio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Productos_Activos_Compania__c/Productos_Activos_Compania__c.object-meta.xml
<CustomObject>
    <label>Producto Activo Compañía</label>
    <nameField>
        <label>Nombre de Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos Activos Compañía</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Productos_Activos_Compania__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Por entregar</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
                <default>true</default>
                <label>Entregado</label>
            </value>
            <value>
                <fullName>Por retirar</fullName>
            </value>
            <value>
                <fullName>Retirado</fullName>
            </value>
            <value>
                <fullName>Pedido de reposición</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Productos_Activos_Compania__c/fields/Modulo_de_paciente__c.field-meta.xml
<CustomField>
    <fullName>Modulo_de_paciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modulo de paciente</label>
    <referenceTo>Modulo_de_paciente__c</referenceTo>
    <relationshipLabel>Productos Activos Compañía</relationshipLabel>
    <relationshipName>Productos_Activos_Compania</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductosActivosCompaniaTriggerTest.cls
@isTest
private class ProductosActivosCompaniaTriggerTest {


	@isTest static void ifAProductosActivosWithStatusEntregadoOrPorRetirarAndModuloDePacienteAssociatedIsInsertedTheModuloPacienteIsUpdatedTheCountFieldOfProducts() {

		Productos_Activos_Compania__c productosActivos = Build.aProductosActivosCompania()
			.withEstado('Entregado')
			.withModulodepaciente(moduloPaciente)
			.build();
		
		Test.startTest();
		insert productosActivos;
		Test.stopTest();

		Modulo_de_paciente__c updateModuloPaciente = [
			SELECT Cont_Productos_Activos_Compania__c 
			FROM Modulo_de_paciente__c 
			WHERE Id = :moduloPaciente.Id
		];

		System.assertEquals(1, updateModuloPaciente.Cont_Productos_Activos_Compania__c);
	}

	@isTest static void whenANewProductosActivosCompaniaIsCreatedTheModuloPacienteFieldContProductosActivosCompaniaIsUpdated() {

		Productos_Activos_Compania__c productosActivos = Build.aProductosActivosCompania()
			.withEstado('Entregado')
			.withModulodepaciente(moduloPaciente)
			.build();
		insert productosActivos;

		Modulo_de_paciente__c updateModuloPaciente = [
			SELECT Cont_Productos_Activos_Compania__c 
			FROM Modulo_de_paciente__c 
			WHERE Id = :moduloPaciente.Id
		];
		
		Productos_Activos_Compania__c productosActivos2 = Build.aProductosActivosCompania()
			.withEstado('Por retirar')
			.withModulodepaciente(moduloPaciente)
			.build();

		Test.startTest();
		insert productosActivos2;
		Test.stopTest();

		Modulo_de_paciente__c updateModuloPaciente2 = [
			SELECT Cont_Productos_Activos_Compania__c 
			FROM Modulo_de_paciente__c 
			WHERE Id = :moduloPaciente.Id
		];
		
		System.assertEquals(2, updateModuloPaciente2.Cont_Productos_Activos_Compania__c);
		System.assertNotEquals(
			updateModuloPaciente.Cont_Productos_Activos_Compania__c,
			updateModuloPaciente2.Cont_Productos_Activos_Compania__c
		);
		
	}

	@isTest static void ifAProductosActivosWithoutStatusAndModuloDePacienteAssociatedIsInserted_TheModuloPacienteNotUpdatedTheFieldCountOfProducts() {

		Productos_Activos_Compania__c productosActivos = Build.aProductosActivosCompania()
			.withEstado('Retirado')
			.withModulodepaciente(moduloPaciente)
			.build();

		Test.startTest();
		insert productosActivos;
		Test.stopTest();

		Modulo_de_paciente__c updateModuloPaciente = [
			SELECT Cont_Productos_Activos_Compania__c 
			FROM Modulo_de_paciente__c 
			WHERE Id = :moduloPaciente.Id
		];

		System.assertEquals(0, updateModuloPaciente.Cont_Productos_Activos_Compania__c);
	}

	@isTest static void ifAProductosActivosWithoutModuloDePacienteAssociatedIsInserted_TheModuloPacienteNotUpdatedTheFieldCountOfProducts() {

		Productos_Activos_Compania__c productosActivos = Build.aProductosActivosCompania()
			.withEstado('Entregado')
			.build();

		Test.startTest();
		insert productosActivos;
		Test.stopTest();

		Modulo_de_paciente__c updateModuloPaciente = [
			SELECT Cont_Productos_Activos_Compania__c 
			FROM Modulo_de_paciente__c 
			WHERE Id = :moduloPaciente.Id
		];

		System.assertEquals(0, updateModuloPaciente.Cont_Productos_Activos_Compania__c);
	}

	@isTest static void whenAProductosActivosIsDeleteTheModuloPacienteFieldCountFieldCountOfProductsIsUpdated() {

		Productos_Activos_Compania__c productosActivos = Build.aProductosActivosCompania()
			.withEstado('Por retirar')
			.withModulodepaciente(moduloPaciente)
			.build();
		insert productosActivos;

		Productos_Activos_Compania__c productosActivos2 = Build.aProductosActivosCompania()
			.withEstado('Entregado')
			.withModulodepaciente(moduloPaciente)
			.build();
		insert productosActivos2;

		Test.startTest();
		delete productosActivos2;
		Test.stopTest();

		Modulo_de_paciente__c updateModuloPaciente = [
			SELECT Cont_Productos_Activos_Compania__c 
			FROM Modulo_de_paciente__c 
			WHERE Id = :moduloPaciente.Id
		];

		System.assertEquals(1, updateModuloPaciente.Cont_Productos_Activos_Compania__c);
	}

	@isTest static void whenAProductosActivosIsChangedStatusTheModuloPacienteFieldCountFieldCountOfProductsIsUpdated() {

		Productos_Activos_Compania__c productosActivos = Build.aProductosActivosCompania()
			.withEstado('Por retirar')
			.withModulodepaciente(moduloPaciente)
			.build();
		insert productosActivos;

		Modulo_de_paciente__c updateModuloPaciente = [
			SELECT Cont_Productos_Activos_Compania__c 
			FROM Modulo_de_paciente__c 
			WHERE Id = :moduloPaciente.Id
		];

		productosActivos.Estado__c = 'Retirado';
		Test.startTest();
		update productosActivos;
		Test.stopTest();

		Modulo_de_paciente__c updateModuloPaciente2 = [
			SELECT Cont_Productos_Activos_Compania__c 
			FROM Modulo_de_paciente__c 
			WHERE Id = :moduloPaciente.Id
		];

		System.assertEquals(1, updateModuloPaciente.Cont_Productos_Activos_Compania__c);
		System.assertEquals(0, updateModuloPaciente2.Cont_Productos_Activos_Compania__c);
	}

	@isTest static void whenAProductosActivosIsUndeleteTheModuloPacienteFieldCountFieldCountOfProductsIsUpdated() {

		Productos_Activos_Compania__c productosActivos = Build.aProductosActivosCompania()
			.withEstado('Por retirar')
			.withModulodepaciente(moduloPaciente)
			.build();
		insert productosActivos;
		delete productosActivos;

		Test.startTest();
		undelete productosActivos;
		Test.stopTest();

		Modulo_de_paciente__c updateModuloPaciente = [
			SELECT Cont_Productos_Activos_Compania__c 
			FROM Modulo_de_paciente__c 
			WHERE Id = :moduloPaciente.Id
		];

		System.assertEquals(1, updateModuloPaciente.Cont_Productos_Activos_Compania__c);
	}

	static Modulo_de_paciente__c moduloPaciente;
	static Account cuentaTest;
	static {

		cuentaTest = Build.anAccountPacienteBestCare()
						.withLastName('Name Test')
						.withRegimenDeInternacionDomiciliaria('Sí')
						.withEmpresadeinternaciondomiciliaria('Best care')				   
						.build();
		insert cuentaTest;

		moduloPaciente = Build.aModulodepaciente()
			.withCuenta(cuentaTest)
			.build();
		insert moduloPaciente;

	}

}