force-app/main/default/objects/VisMed_Accion__c/VisMed_Accion__c.object-meta.xml
<CustomObject>
    <description>Objeto que contendrá las acciones que se cargan a cada objeto.</description>
    <label>Acción</label>
    <nameField>
        <label>Nombre de Acción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Accion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Accion__c/fields/VisMed_Objetivo__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Objetivo__c</fullName>
    <description>Objetivo al que se relaciona la acción.</description>
    <label>Objetivo</label>
    <referenceTo>VisMed_Objetivo__c</referenceTo>
    <relationshipLabel>Acciones</relationshipLabel>
    <relationshipName>Acciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VisMed_AccionPorCuenta__c/VisMed_AccionPorCuenta__c.object-meta.xml
<CustomObject>
    <description>Objeto que contendrá las acciones correspondientes a un objetivo, relacionadas a un profesional o Institución.</description>
    <label>Acción por cuenta</label>
    <nameField>
        <displayFormat>AccXObj-{0000}</displayFormat>
        <label>Nombre de Acción por profesional</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acciones por cuenta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_AccionPorCuenta__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_AccionPorCuenta__c/fields/VisMed_Accion__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Accion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Acción</label>
    <referenceTo>VisMed_Accion__c</referenceTo>
    <relationshipLabel>Acciones por cuenta</relationshipLabel>
    <relationshipName>Acciones_por_cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_AccionPorCuenta__c/fields/VisMed_APMContacto__c.field-meta.xml
<CustomField>
    <fullName>VisMed_APMContacto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>APM</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Acciones por cuenta</relationshipLabel>
    <relationshipName>Acciones_Por_Cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_AccionPorCuenta__c/fields/VisMed_Objetivo__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Objetivo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objetivo</label>
    <referenceTo>VisMed_Objetivo__c</referenceTo>
    <relationshipLabel>Acciones por cuenta</relationshipLabel>
    <relationshipName>Acciones_por_cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_AccionPorCuenta__c/fields/VisMed_ObjetivoPorCuenta__c.field-meta.xml
<CustomField>
    <fullName>VisMed_ObjetivoPorCuenta__c</fullName>
    <label>Objetivo por cuenta</label>
    <referenceTo>VisMed_ObjetivoPorCuenta__c</referenceTo>
    <relationshipLabel>Acciones por cuenta</relationshipLabel>
    <relationshipName>Acciones_por_cuenta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VisMed_Objetivo__c/VisMed_Objetivo__c.object-meta.xml
<CustomObject>
    <description>Objeto en el que se cargarán los objetivos que deberán cumplir los APM.</description>
    <label>Objetivo</label>
    <nameField>
        <label>Nombre de Objetivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objetivos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_ObjetivoPorCuenta__c/VisMed_ObjetivoPorCuenta__c.object-meta.xml
<CustomObject>
    <description>Objeto que relacionará el profesional o la institución con el objetivo.</description>
    <label>Objetivo por cuenta</label>
    <nameField>
        <displayFormat>ObjXCue-{0000}</displayFormat>
        <label>Nombre de Objetivo por cuenta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objetivos por cuenta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_ObjetivoPorCuenta__c/fields/VisMed_APMContacto__c.field-meta.xml
<CustomField>
    <fullName>VisMed_APMContacto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>APM</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Objetivos por cuenta</relationshipLabel>
    <relationshipName>Objetivos_Por_Cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_ObjetivoPorCuenta__c/fields/VisMed_Objetivo__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Objetivo__c</fullName>
    <label>Objetivo</label>
    <referenceTo>VisMed_Objetivo__c</referenceTo>
    <relationshipLabel>Objetivos por cuenta</relationshipLabel>
    <relationshipName>Objetivos_por_cuenta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ObjetivoPorCuentaTriggerHelper.cls
public without sharing class ObjetivoPorCuentaTriggerHelper {
    
    public static void createAccionPorCuenta(List<VisMed_ObjetivoPorCuenta__c> objetivosXCuentas){
        Set<String> objetivosIds = new Set<String>();
        for(VisMed_ObjetivoPorCuenta__c objetivoXCuenta : objetivosXCuentas){
            objetivosIds.add(objetivoXCuenta.VisMed_Objetivo__c);
        }
        List<String> objetivosIdsSinDuplicados = new List<String>(objetivosIds);

        Map<String,List<VisMed_Accion__c>> mapObjIdAccions = new Map<String,List<VisMed_Accion__c>>();
        for(VisMed_Accion__c accion : [SELECT id, Estado__c,VisMed_Objetivo__c FROM VisMed_Accion__c WHERE VisMed_Objetivo__c IN :objetivosIdsSinDuplicados]){
            if(!mapObjIdAccions.containsKey(accion.VisMed_Objetivo__c)){
                mapObjIdAccions.put(accion.VisMed_Objetivo__c, new List<VisMed_Accion__c>());
            }
            mapObjIdAccions.get(accion.VisMed_Objetivo__c).add(accion);
        }
        System.debug('mapObjIdAccions');
        System.debug(mapObjIdAccions);
        if(mapObjIdAccions.size() > 0){
            List<VisMed_AccionPorCuenta__c> accionXCuentaToInsert = new List<VisMed_AccionPorCuenta__c>();
            for(VisMed_ObjetivoPorCuenta__c objetivoXCuenta : objetivosXCuentas){
                for(VisMed_Accion__c objAccion : mapObjIdAccions.get(objetivoXCuenta.VisMed_Objetivo__c)){
                    VisMed_AccionPorCuenta__c accionXCuenta = new VisMed_AccionPorCuenta__c(
                        VisMed_Accion__c = objAccion.Id,
                        VisMed_APMContacto__c = objetivoXCuenta.VisMed_APMContacto__c,
                        VisMed_ObjetivoPorCuenta__c = objetivoXCuenta.Id,
                        VisMed_Objetivo__c = objAccion.VisMed_Objetivo__c,
                        Estado__c = objAccion.Estado__c
                    );
                    accionXCuentaToInsert.add(accionXCuenta);
                }
            }
            System.debug('accionXCuentaToInsert');
            System.debug(accionXCuentaToInsert);
            Database.SaveResult[] saveResultList = Database.insert(accionXCuentaToInsert, true);
            for (Database.SaveResult sr : saveResultList) {
                if (sr.isSuccess()) {
                    System.debug('Se inserto AccionXCuenta');
                }
                else {
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('The following error has occurred.');
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Account fields that affected this error: ' + err.getFields());
                    }  
                }
            } 
        }
        
    }
}