force-app/main/default/objects/VisMed_Accion__c/VisMed_Accion__c.object-meta.xml
<CustomObject>
    <description>Objeto que contendrá las acciones que se cargan a cada objeto.</description>
    <label>Acción</label>
    <nameField>
        <label>Nombre de Acción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Accion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Accion__c/fields/VisMed_Objetivo__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Objetivo__c</fullName>
    <description>Objetivo al que se relaciona la acción.</description>
    <label>Objetivo</label>
    <referenceTo>VisMed_Objetivo__c</referenceTo>
    <relationshipLabel>Acciones</relationshipLabel>
    <relationshipName>Acciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VisMed_Objetivo__c/VisMed_Objetivo__c.object-meta.xml
<CustomObject>
    <description>Objeto en el que se cargarán los objetivos que deberán cumplir los APM.</description>
    <label>Objetivo</label>
    <nameField>
        <label>Nombre de Objetivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objetivos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchEstadoAcciones_Test.cls
@IsTest
public class BatchEstadoAcciones_Test {
 
    @TestSetup
    static void makeData(){

        VisMed_Objetivo__c obj = Build.aVisMedObjetivo()
        .withName('Objetivo Test')
        .withVisMedFechaInicio(Date.today().toStartOfMonth())
        .withVisMedFechaFin(Date.Today().addMonths(3))
        .build();
        
        insert obj;

    }

    @IsTest
    public static void testBatchEstadoAccionActivo(){
    List<VisMed_Accion__c> VisMedList = new List<VisMed_Accion__c>();

    for(Integer i=0;i<3 ;i++){
        VisMed_Accion__c accion = Build.aVisMedAccion()
        .withVisMedObjetivo(getVisMedObj())
        .withVisMedFechaInicio(Date.today())
        .withVisMedFechaFin(Date.today().addDays(1))        
        .build();

        VisMedList.add(accion);
    }
        insert VisMedList;

        Test.startTest();
            Database.executeBatch(new BatchEstadoAcciones()); 
        Test.stopTest();

        System.assertEquals('Activo', getVisMedAccion()[0].Estado__c);
        System.assertEquals(3, getVisMedAccion().size());

    }

    @IsTest
    public static void testBatchEstadoAccionInactivo(){
        
        VisMed_Accion__c accion2 = Build.aVisMedAccion()
        .withVisMedObjetivo(getVisMedObj())
        .withVisMedFechaInicio(Date.today().addDays(5))
        .withVisMedFechaFin(Date.today().addDays(7))        
        .build();

        insert accion2;

        Test.startTest();
            Database.executeBatch(new BatchEstadoAcciones()); 
        Test.stopTest();

        System.assertEquals('Inactivo', getVisMedAccion()[0].Estado__c);
    }

    public static VisMed_Objetivo__c getVisMedObj(){
        return [
            SELECT id 
            FROM VisMed_Objetivo__c
            LIMIT 1
        ];
    }
    public static List<VisMed_Accion__c> getVisMedAccion(){
        return [
            SELECT id ,Estado__c
            FROM VisMed_Accion__c
        ];
    }
}