force-app/main/default/objects/Dan360_CustomerSalesArea__c/Dan360_CustomerSalesArea__c.object-meta.xml
<CustomObject>
    <description>Customer Sales Area</description>
    <label>Customer Sales Area</label>
    <nameField>
        <label>Nombre de Customer Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Sales Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Dan360_CustomerSalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CustomerSalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Sales Area relacionado al pedido</description>
    <label>Customer Sales Area</label>
    <referenceTo>Dan360_CustomerSalesArea__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_FechaCierreCarrito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_FechaCierreCarrito__c</fullName>
    <description>Fecha-hora de cierre de carrito</description>
    <label>Fecha Cierre Carrito</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_FechaInicioCarrito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_FechaInicioCarrito__c</fullName>
    <description>Fecha-hora de inicio carrito</description>
    <label>Fecha Inicio Carrito</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_OrderReason__c.field-meta.xml
<CustomField>
    <fullName>Dan360_OrderReason__c</fullName>
    <description>Razón por la cuál se genera un pedido sin cargo.</description>
    <label>Razón del pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AT3</fullName>
                <label>Beneficios Empleados</label>
            </value>
            <value>
                <fullName>AF7</fullName>
                <label>Donaciones</label>
            </value>
            <value>
                <fullName>SMA</fullName>
                <label>Marketing Adultos</label>
            </value>
            <value>
                <fullName>SMC</fullName>
                <label>Marketing Consumer</label>
            </value>
            <value>
                <fullName>SMP</fullName>
                <label>Marketing Pediátrico</label>
            </value>
            <value>
                <fullName>APP</fullName>
                <label>Promoción Farmacias</label>
            </value>
            <value>
                <fullName>APN</fullName>
                <label>Reclamo de Calidad-Arg</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_UnidadNegocio__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadNegocio__c</fullName>
    <description>Se refiere al negocio donde se generará una transacción, en donde impactará la venta de un producto.</description>
    <label>Unidad de negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_UnidadDeNegocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Orden_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_compra__c</fullName>
    <label>Orden de compra</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Dan360_UnidadDeNegocio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5800</fullName>
        <label>AMN</label>
    </customValue>
    <customValue>
        <fullName>5771</fullName>
        <label>NuBa</label>
    </customValue>
    <description>Determina a qué unidad de negocio se genera un pedido.</description>
    <masterLabel>Unidad de Negocio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SchedulerOrderToSap.cls
global class SchedulerOrderToSap implements Schedulable {
    
    global void execute(SchedulableContext sc) {
        String typeObj = 'Order';
        Map<String,Order> orderMap = new Map<String,Order>();
        DateTime timeToUse = datetime.newInstance(2022, 1, 9); // Borrar para produccion.

        for(Order pedido : [
            SELECT id, Orden_de_compra__c,OrderNumber, Dan360_UnidadNegocio__c, RecordType.Name ,
            EndDate, EffectiveDate, Dan360_FechaInicioCarrito__c, Dan360_FechaCierreCarrito__c,
            AccountId, Description, Status, Dan360_CustomerSalesArea__c, Dan360_OrderReason__c
            FROM Order
            WHERE Status = 'Confirmado'
            AND LastModifiedDate >= :timeToUse])
            {
                if(!orderMap.containsKey(pedido.Id)){
                    orderMap.put(pedido.Id, pedido);
                }
            }
        
        for(String key : orderMap.keySet()){
            Order orderToShow = orderMap.get(key);
            System.debug('Numero de orden: ' + orderToShow.OrderNumber);
        }

        if(orderMap.size() > 0) {
            try {
                BatchSendOrdersToSap orderBatch = new BatchSendOrdersToSap(orderMap,typeObj);
                ID batchId = Database.executeBatch(orderBatch, 10);
            } catch (Exception e) {
                System.debug('Error al encolar el batch: ' + e.getMessage());
            }
        }
    }
}