force-app/main/default/objects/Dan360_PlantillaDeProductos__c/Dan360_PlantillaDeProductos__c.object-meta.xml
<CustomObject>
    <description>Objetos en donde se almacenarán las plantillas de los productos.</description>
    <label>Plantilla de Productos</label>
    <nameField>
        <label>Plantilla</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantillas de Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_PlantillaDeProductos__c/fields/Dan360_UnidadNegocio__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadNegocio__c</fullName>
    <description>Se refiere al negocio donde se generará una transacción, en donde impactará la venta de un producto.</description>
    <label>Unidad de Negocio</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_UnidadDeNegocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/dAN360_PlantillaporcCuenta__c/dAN360_PlantillaporcCuenta__c.object-meta.xml
<CustomObject>
    <description>Objeto Join que relacionará la cuenta con las plantillas de producto.</description>
    <label>Plantilla por cuenta</label>
    <nameField>
        <displayFormat>PlaXCta-{0000}</displayFormat>
        <label>Nombre de Plantilla por cuenta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plantillas por cuenta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/dAN360_PlantillaporcCuenta__c/fields/Dan360_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Cuenta__c</fullName>
    <description>Cliente</description>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plantillas por cuenta</relationshipLabel>
    <relationshipName>Plantillas_por_cuenta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/dAN360_PlantillaporcCuenta__c/fields/Dan360_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DistributionChannel__c</fullName>
    <label>Distribution channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <default>true</default>
                <label>00</label>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/dAN360_PlantillaporcCuenta__c/fields/Dan360_PlantillaDeProductos__c.field-meta.xml
<CustomField>
    <fullName>Dan360_PlantillaDeProductos__c</fullName>
    <description>Plantilla creada para el cliente, en donde están registrados los productos que puede adquirir.</description>
    <label>Plantilla de Productos</label>
    <referenceTo>Dan360_PlantillaDeProductos__c</referenceTo>
    <relationshipLabel>Plantillas por cuenta</relationshipLabel>
    <relationshipName>Plantillas_por_cuenta</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/dAN360_PlantillaporcCuenta__c/fields/Dan360_UnidadNegocio__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadNegocio__c</fullName>
    <description>Se refiere al negocio donde se generará una transacción, en donde impactará la venta de un producto.</description>
    <label>Unidad de negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_UnidadDeNegocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/Dan360_ProductoPorPlantilla__c.object-meta.xml
<CustomObject>
    <label>Producto por Plantilla</label>
    <nameField>
        <displayFormat>PrdXPla-{0000}</displayFormat>
        <label>Producto por plantilla</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos por Plantillas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/fields/Dan360_Activo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Señala si un producto está activo de acuerdo a su vigencia.</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/fields/Dan360_PlantillaProductos__c.field-meta.xml
<CustomField>
    <fullName>Dan360_PlantillaProductos__c</fullName>
    <description>Nombre o código de la plantilla creada para el cliente, en donde están registrados los productos que puede adquirir.</description>
    <label>Plantilla de Productos</label>
    <referenceTo>Dan360_PlantillaDeProductos__c</referenceTo>
    <relationshipLabel>Productos por Plantillas</relationshipLabel>
    <relationshipName>Productos_por_Plantillas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/fields/Dan360_Producto__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nombre o código del artículo que podrá ser adquirido por los clientes.</description>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Productos por Plantillas</relationshipLabel>
    <relationshipName>Productos_por_Plantillas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_PlantillaProductos__c.field-meta.xml
<CustomField>
    <fullName>Dan360_PlantillaProductos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que se va a llenar con desarrollo para conocer la plantilla que se relaciona al pedido.</description>
    <label>Plantilla de Productos</label>
    <referenceTo>Dan360_PlantillaDeProductos__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_UnidadNegocio__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadNegocio__c</fullName>
    <description>Se refiere al negocio donde se generará una transacción, en donde impactará la venta de un producto.</description>
    <label>Unidad de negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_UnidadDeNegocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Dan360_UnidadDeNegocio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5800</fullName>
        <label>AMN</label>
    </customValue>
    <customValue>
        <fullName>5771</fullName>
        <label>NuBa</label>
    </customValue>
    <description>Determina a qué unidad de negocio se genera un pedido.</description>
    <masterLabel>Unidad de Negocio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrderConfirmationFlow.cls
public with sharing class OrderConfirmationFlow {
    @InvocableMethod(label='Check if products not available' description='check If Product Is Not Available')
    public static List<List<OrderItem>> checkIfProductIsNotAvailable(List<List<OrderItem>> orderItems) {
        List<List<OrderItem>> orderItemsToReturn = new List<List<OrderItem>>();
        List<String> pbeIdsList = new List<String>();
        Set<String> productList = new Set<String>();
        Map<String, OrderItem> mapPbeOrderItem = new Map<String, OrderItem>();
        String orderId ;
        for(OrderItem orderIten : orderItems[0]){
            orderId = orderIten.OrderId;
            productList.add(orderIten.Product2Id);
            pbeIdsList.add(orderIten.PricebookEntryId);
            if(!mapPbeOrderItem.containsKey(orderIten.PricebookEntryId)){
                mapPbeOrderItem.put(orderIten.PricebookEntryId, orderIten);
            }
        }

        
        Order orden = [SELECT Dan360_UnidadNegocio__c, Dan360_PlantillaProductos__c, AccountId, RecordType.Name FROM Order WHERE Id = :orderId WITH SECURITY_ENFORCED];
        
        String distributionChannel = orden.RecordType.Name == 'Pedido de Venta Directa' ? '00' : '05';

        dAN360_PlantillaporcCuenta__c plantillaCuenta = [
            SELECT Dan360_PlantillaDeProductos__c
            FROM dAN360_PlantillaporcCuenta__c
            WHERE Dan360_Cuenta__c =:orden.AccountId
                AND 
                    (Dan360_UnidadNegocio__c = :orden.Dan360_UnidadNegocio__c AND Dan360_DistributionChannel__c = :distributionChannel)
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];


        //Dan360_PlantillaDeProductos__c plantillaProductos = [SELECT Id FROM Dan360_PlantillaDeProductos__c WHERE Id = :orden.Dan360_PlantillaProductos__c WITH SECURITY_ENFORCED];
        List<Dan360_ProductoPorPlantilla__c> productosPlantilla = [ SELECT Id, Dan360_Producto__r.Name 
                                                                    FROM Dan360_ProductoPorPlantilla__c 
                                                                    WHERE Dan360_Producto__c IN : productList
                                                                        AND Dan360_Activo__c = false
                                                                        AND Dan360_PlantillaProductos__c = :plantillaCuenta.Dan360_PlantillaDeProductos__c WITH SECURITY_ENFORCED];
        List<OrderItem> orderItemList = new List<OrderItem>();
        for(PricebookEntry pbe : [SELECT Id, isActive FROM PricebookEntry WHERE Id IN :pbeIdsList AND isActive = false WITH SECURITY_ENFORCED]){
            if(mapPbeOrderItem.containsKey(pbe.Id)){
                orderItemList.add(mapPbeOrderItem.get(pbe.Id));
            }
        }
        orderItemsToReturn.add(orderItemList);
        return orderItemsToReturn;
    }
}