force-app/main/default/objects/Dan360_PlantillaDeProductos__c/Dan360_PlantillaDeProductos__c.object-meta.xml
<CustomObject>
    <description>Objetos en donde se almacenarán las plantillas de los productos.</description>
    <label>Plantilla de Productos</label>
    <nameField>
        <label>Plantilla</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plantillas de Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_PlantillaDeProductos__c/fields/Dan360_UnidadNegocio__c.field-meta.xml
<CustomField>
    <fullName>Dan360_UnidadNegocio__c</fullName>
    <description>Se refiere al negocio donde se generará una transacción, en donde impactará la venta de un producto.</description>
    <label>Unidad de Negocio</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dan360_UnidadDeNegocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/Dan360_ProductoPorPlantilla__c.object-meta.xml
<CustomObject>
    <label>Producto por Plantilla</label>
    <nameField>
        <displayFormat>PrdXPla-{0000}</displayFormat>
        <label>Producto por plantilla</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos por Plantillas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/fields/Dan360_PlantillaProductos__c.field-meta.xml
<CustomField>
    <fullName>Dan360_PlantillaProductos__c</fullName>
    <description>Nombre o código de la plantilla creada para el cliente, en donde están registrados los productos que puede adquirir.</description>
    <label>Plantilla de Productos</label>
    <referenceTo>Dan360_PlantillaDeProductos__c</referenceTo>
    <relationshipLabel>Productos por Plantillas</relationshipLabel>
    <relationshipName>Productos_por_Plantillas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/fields/Dan360_Producto__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nombre o código del artículo que podrá ser adquirido por los clientes.</description>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Productos por Plantillas</relationshipLabel>
    <relationshipName>Productos_por_Plantillas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductSalesArea__c/Dan360_ProductSalesArea__c.object-meta.xml
<CustomObject>
    <label>Product Sales Area</label>
    <nameField>
        <label>Nombre de Product Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sales Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_ProductSalesArea__c/fields/Bloqueo__c.field-meta.xml
<CustomField>
    <fullName>Bloqueo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bloqueo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductSalesArea__c/fields/Dan360_Producto__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Sales Area</relationshipLabel>
    <relationshipName>Product_Sales_Area</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductSalesArea__c/fields/Dan360_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesArea__c</fullName>
    <label>Sales Area</label>
    <referenceTo>Dan360_SalesArea__c</referenceTo>
    <relationshipLabel>Product Sales Area</relationshipLabel>
    <relationshipName>Product_Sales_Area</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_SalesArea__c/Dan360_SalesArea__c.object-meta.xml
<CustomObject>
    <description>Sales Area</description>
    <label>Sales Area</label>
    <nameField>
        <label>Nombre de Sales Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_SalesArea__c/fields/Dan360_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>Dan360_SalesOrganization__c</fullName>
    <description>Sales Organization</description>
    <label>Sales Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Dan360_UnidadDeNegocio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5800</fullName>
        <label>AMN</label>
    </customValue>
    <customValue>
        <fullName>5771</fullName>
        <label>NuBa</label>
    </customValue>
    <description>Determina a qué unidad de negocio se genera un pedido.</description>
    <masterLabel>Unidad de Negocio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/listOfProducts.cls
/**
 * @description       : 
 * @author            : sebastian.fondovila@globant.com
 * @group             : 
 * @last modified on  : 06-08-2022
 * @last modified by  : sebastian.fondovila@globant.com
**/
public with sharing class listOfProducts {
    @InvocableMethod (label = 'SendRecordIdGet Products' description = 'returns filtered products.')
    public static List<List<Product2>> getProducts(List<String> recordId) {

        List<String> salesAreaIds = new List<String>();
        List<String> productSalesAreaRecordIds = new List<String>();
        Set<String> productsToFilter = new Set<String>();
        List<Product2> productsToAddInReturn = new List<Product2>();
                
        List<Dan360_PlantillaDeProductos__c> plantillaDeProductos = [
            SELECT Id, Dan360_UnidadNegocio__c
            FROM Dan360_PlantillaDeProductos__c
            WHERE Id = :recordId
            LIMIT 1
        ];


        String unidadDeNegocio = 'Random value';
        for (Dan360_PlantillaDeProductos__c aplantillaDeProductos : plantillaDeProductos) {
            unidadDeNegocio = plantillaDeProductos[0].Dan360_UnidadNegocio__c;
        }
        //Get all Sales Area records where Sales Organization = Unidad de Negocio
        List<Dan360_SalesArea__c> salesAreaRecords = [
            SELECT Id
            FROM Dan360_SalesArea__c
            WHERE Dan360_SalesOrganization__c = :unidadDeNegocio
        ];
        for(Dan360_SalesArea__c salesArea : salesAreaRecords){
            salesAreaIds.add(salesArea.Id);
        }

        //Get Product Sales Area records related to the Sales Area records we queried and Bloqueo = false
        List<Dan360_ProductSalesArea__c> productSalesAreaRecords = [
            SELECT Id, Dan360_Producto__c
            FROM Dan360_ProductSalesArea__c
            WHERE Bloqueo__c = false
                AND Dan360_SalesArea__c IN :salesAreaIds
        ];

        for(Dan360_ProductSalesArea__c productSalesArea : productSalesAreaRecords){
            productSalesAreaRecordIds.add(productSalesArea.Dan360_Producto__c);
        }

        List<Product2> productsToAddToListOfLists = [
            SELECT Id, Name
            FROM Product2
            WHERE Id IN :productSalesAreaRecordIds
        ];
       
        // get products already exist in template
        List<Dan360_ProductoPorPlantilla__c> productsAlreadyExist = [
            SELECT ID, Dan360_Producto__c 
            FROM Dan360_ProductoPorPlantilla__c
            WHERE Dan360_PlantillaProductos__c = :recordId
        ];
       
        for (Dan360_ProductoPorPlantilla__c aProduct : productsAlreadyExist) {
            productsToFilter.add(aProduct.Dan360_Producto__c);
        }
                
        for (Product2 aProduct : productsToAddToListOfLists) {           
            if (!productsToFilter.contains(aProduct.Id)) {                
                productsToAddInReturn.add(aProduct);
            }
        }
        
        List<List<Product2>> productsToReturn = new List<List<Product2>>();
        productsToReturn.add(productsToAddInReturn);       
        return productsToReturn;
    }
}