force-app/main/default/objects/Frecuencia_por_Categoria__mdt/Frecuencia_por_Categoria__mdt.object-meta.xml
<CustomObject>
    <label>Frecuencia por Categoria</label>
    <pluralLabel>Frecuencia por Categoria</pluralLabel>
</CustomObject>

force-app/main/default/objects/Frecuencia_por_Categoria__mdt/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KOL</fullName>
                <default>true</default>
                <label>KOL</label>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Frecuencia_por_Categoria__mdt/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Frecuencia_por_Categoria__mdt/fields/Segmenta_Por__c.field-meta.xml
<CustomField>
    <fullName>Segmenta_Por__c</fullName>
    <label>Segmenta Por</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adultos General Institucion</fullName>
                <default>true</default>
                <label>Adultos General Institucion</label>
            </value>
            <value>
                <fullName>Adultos General Comunidad</fullName>
            </value>
            <value>
                <fullName>Adultos Oncologia</fullName>
            </value>
            <value>
                <fullName>Metabolicos</fullName>
            </value>
            <value>
                <fullName>Epilepsia</fullName>
            </value>
            <value>
                <fullName>Metabolicos y Epilepsia</fullName>
            </value>
            <value>
                <fullName>Pediatricos General</fullName>
            </value>
            <value>
                <fullName>Alergia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/VisMed_Segmentacion__c.object-meta.xml
<CustomObject>
    <label>Segmentación</label>
    <nameField>
        <displayFormat>Segmentacion-{0000}</displayFormat>
        <label>Segmentación Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <formula>IF(
  OR(
    RecordType.Name =&apos;Metabolicos&apos;,
    RecordType.Name =&apos;Epilepsia&apos;,
    RecordType.Name =&apos;Metabolicos_y_Epilepsia&apos;
  ),
  Categoria_Nicho__c,
  IF(
    OR(
      RecordType.Name =&apos;Alergia&apos;,
      RecordType.Name =&apos;Pediatricos&apos;,
      RecordType.Name =&apos;Pediatricos General&apos;
    ),
    Categoria_Ped_Aler__c,
    Categoria_Nicho__c
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Categoria</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SegmentacionTriggerHelper.cls
public with sharing class SegmentacionTriggerHelper {
    
    public static void setFrecuencias (List<VisMed_Segmentacion__c> segmentaciones, Boolean isUpdate) {
        List<Frecuencia_por_Categoria__mdt> mdt;
        Map<String, Frecuencia_por_Categoria__mdt> frecuenciaParaEquipoCategoria = new Map<String,Frecuencia_por_Categoria__mdt>();
        Map<ID, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.VisMed_Segmentacion__c.getRecordTypeInfosById();
        System.debug('rtMap');
        System.debug(rtMap);
        mdt = [SELECT Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName, Categoria__c, Frecuencia__c, Segmenta_Por__c 
                FROM Frecuencia_por_Categoria__mdt];
        System.debug('mdt '+ mdt);
        for (Frecuencia_por_Categoria__mdt metadata : mdt) {
            String key = metadata.Segmenta_Por__c + '-' + metadata.Categoria__c;
            frecuenciaParaEquipoCategoria.put(key, metadata);
        }
        System.debug('frecuenciaParaEquipoCategoria');
        System.debug(frecuenciaParaEquipoCategoria);
        for(String key : frecuenciaParaEquipoCategoria.keySet()) {
            System.debug(key);
        }
        for (VisMed_Segmentacion__c segmentacion : segmentaciones) {
            String key = rtMap.get(segmentacion.RecordTypeId).getName() + '-' + segmentacion.Categoria__c;
            System.debug('Segmentacion y Categoria: ' + key);
            if (frecuenciaParaEquipoCategoria.containsKey(key)) {
                System.debug('Segmentacion y Categoria: ' + key);
                segmentacion.Frecuencia__c = frecuenciaParaEquipoCategoria.get(key).Frecuencia__c;
                System.debug('segmentacion.Frecuencia__c: ' + segmentacion.Frecuencia__c);
            }
            System.debug('Segmentacion: ' + segmentacion);
        }

        if (isUpdate) {
            update segmentaciones;
        }
    }

}