force-app/main/default/objects/Frecuencia_por_Categoria__mdt/Frecuencia_por_Categoria__mdt.object-meta.xml
<CustomObject>
    <label>Frecuencia por Categoria</label>
    <pluralLabel>Frecuencia por Categoria</pluralLabel>
</CustomObject>

force-app/main/default/objects/Frecuencia_por_Categoria__mdt/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KOL</fullName>
                <default>true</default>
                <label>KOL</label>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Frecuencia_por_Categoria__mdt/fields/Equipo__c.field-meta.xml
<CustomField>
    <fullName>Equipo__c</fullName>
    <label>Equipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Epilepsia</fullName>
                <default>true</default>
                <label>Epilepsia</label>
            </value>
            <value>
                <fullName>Metabolicos</fullName>
            </value>
            <value>
                <fullName>Metabolicos y Epilepsia</fullName>
            </value>
            <value>
                <fullName>Pediatricos</fullName>
            </value>
            <value>
                <fullName>Alergia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Frecuencia_por_Categoria__mdt/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Frecuencia_por_Categoria__mdt/fields/Segmenta_Por__c.field-meta.xml
<CustomField>
    <fullName>Segmenta_Por__c</fullName>
    <label>Segmenta Por</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adultos General Institucion</fullName>
                <default>true</default>
                <label>Adultos General Institucion</label>
            </value>
            <value>
                <fullName>Adultos General Comunidad</fullName>
            </value>
            <value>
                <fullName>Adultos Oncologia</fullName>
            </value>
            <value>
                <fullName>Metabolicos</fullName>
            </value>
            <value>
                <fullName>Epilepsia</fullName>
            </value>
            <value>
                <fullName>Metabolicos y Epilepsia</fullName>
            </value>
            <value>
                <fullName>Pediatricos General</fullName>
            </value>
            <value>
                <fullName>Alergia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Segmenta_Por__c.field-meta.xml
<CustomField>
    <fullName>Segmenta_Por__c</fullName>
    <label>Segmenta Por</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Metabolicos</fullName>
            </value>
            <value>
                <fullName>Epilepsia</fullName>
            </value>
            <value>
                <fullName>Metabolicos y Epilepsia</fullName>
            </value>
            <value>
                <fullName>Pediatricos</fullName>
            </value>
            <value>
                <fullName>Alergia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/VisMed_Segmentacion__c.object-meta.xml
<CustomObject>
    <label>Segmentación</label>
    <nameField>
        <displayFormat>Segmentacion-{0000}</displayFormat>
        <label>Segmentación Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <formula>IF(
  OR(
    RecordType.Name =&apos;Metabolicos&apos;,
    RecordType.Name =&apos;Epilepsia&apos;,
    RecordType.Name =&apos;Metabolicos_y_Epilepsia&apos;
  ),
  Categoria_Nicho__c,
  IF(
    OR(
      RecordType.Name =&apos;Alergia&apos;,
      RecordType.Name =&apos;Pediatricos&apos;,
      RecordType.Name =&apos;Pediatricos General&apos;
    ),
    Categoria_Ped_Aler__c,
    Categoria_Nicho__c
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Categoria</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profesional de la Salud, Otro Profesional</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segmentaciones</relationshipLabel>
    <relationshipName>Segmentaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchFrecuencia.cls
public with sharing class BatchFrecuencia /*implements Database.Batchable<sObject>*/ {
    /*
    public Database.QueryLocator start (Database.BatchableContext bc) {
        Id recordTypeProfesional = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Profesional_de_la_Salud').getRecordTypeId(); 
        Id recordTypeOtroProfesional = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Otro_Profesional').getRecordTypeId(); 
        return Database.getQueryLocator([SELECT Id, AccountId, UserId, User.Segmenta_Por__C, Ultima_Visita__c, Dan360_Areas_Terapeuticas__c, Frecuencia__c, Inicio_de_Frecuencia__c, Aun_Quedan_Meses__c, Visitas_Realizadas__c, Visitas_Restantes__c FROM AccountTeamMember WHERE Account.RecordTypeId = :recordTypeProfesional OR Account.RecordTypeId = :recordTypeOtroProfesional]);
    }

    public void execute (Database.BatchableContext BC, list<AccountTeamMember> accountsTeam) {
        //String recordTypeName = Schema.SObjectType.VisMed_Segmentacion__c.getRecordTypeInfosById().get(segmentacion.RecordTypeId).getName();
        Set<Id> usersId = new Set<Id>();
        Set<Id> profesionalesId = new Set<Id>();
        List<VisMed_Segmentacion__c> segmentaciones;
        List<AccounTeamWrapper> accountsTeamWrapperList = new List<AccounTeamWrapper>();
        List<Frecuencia_por_Categoria__mdt> mdtList = [SELECT Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName, Categoria__c, Frecuencia__c, Equipo__c FROM Frecuencia_por_Categoria__mdt];
        List<AccountTeamMember> accountsTeamsToUpsert = new List<AccountTeamMember>();
        Map<Id,Set<Id>> profesionalesXapm = new Map<Id,Set<Id>>();
        Map<Id,String> segmentacionDelAPM = new Map<Id,String>();
        Map<Id,AccountTeamMember> mapAccountTeam = new Map<Id,AccountTeamMember>();

        for (AccountTeamMember accountTeam : accountsTeam) {
            Set<Id> profesionalesAUX;
            usersId.add(accountTeam.UserId);
            profesionalesId.add(accountTeam.AccountId);
            profesionalesAUX = profesionalesXapm.containsKey(accountTeam.UserId) ? profesionalesXapm.get(accountTeam.UserId) : new Set<Id>();
            profesionalesAUX.add(accountTeam.AccountId);
            profesionalesXapm.put(accountTeam.UserId, profesionalesAUX);
            segmentacionDelAPM.put(accountTeam.UserId, accountTeam.User.Segmenta_Por__C);
            mapAccountTeam.put(accountTeam.Id, accountTeam);   
            AccounTeamWrapper accounTeamWraper = new AccounTeamWrapper(
                accountTeam.UserId,
                accountTeam.AccountId,
                accountTeam.User.Segmenta_Por__C,
                accountTeam
            );
            accountsTeamWrapperList.add(accounTeamWraper);
        }

        segmentaciones = [SELECT Id, Categoria__c, RecordTypeId, RecordType.Name FROM VisMed_Segmentacion__c WHERE Profesional__c IN :profesionalesId];

        for (VisMed_Segmentacion__c segmentacion : segmentaciones) {
            for (AccounTeamWrapper accountTeamWrapper : accountsTeamWrapperList) {
                if (profesionalesXapm.get(accountTeamWrapper.user).contains(segmentacion.Profesional__c)) {
                    if (accountTeamWrapper.account == segmentacion.Profesional__c && accountTeamWrapper.segmentacion == segmentacion.RecordType.Name) {
                        AccountTeamMember upsertAccountTeam = mapAccountTeam.get(accountTeamWrapper.accountTeam.Id);
                        for (Frecuencia_por_Categoria__mdt mdt : mdtList) {
                            if (accountTeamWrapper.segmentacion == mdt.Equipo__C && segmentacion.Categoria__c == mdt.Categoria__c) {
                                upsertAccountTeam.Frecuencia__c = mdt.Frecuencia__c;
                            }
                        }
                        if (string.ValueOf(upsertAccountTeam.Frecuencia__c).endsWith('.0')) {
                            upsertAccountTeam.Visitas_Realizadas__c = 0;
                            upsertAccountTeam.Aun_Quedan_Meses__c = false;
                            upsertAccountTeam.Inicio_de_Frecuencia__c = System.today().toStartOfMonth().addMonths(1);
                        } else if (upsertAccountTeam.Inicio_de_Frecuencia__c.month() == System.today().month()) {
                            upsertAccountTeam.Aun_Quedan_Meses__c = true;
                            upsertAccountTeam.Visitas_Realizadas__c = 0;
                        } else if (upsertAccountTeam.Inicio_de_Frecuencia__c.month() != System.today().month()) {
                            upsertAccountTeam.Aun_Quedan_Meses__c = false;
                            upsertAccountTeam.Inicio_de_Frecuencia__c = System.today().toStartOfMonth().addMonths(1);
                        }
                        accountsTeamsToUpsert.add(upsertAccountTeam);
                    }
                }
            }
        }
        upsert accountsTeamsToUpsert;
    }

    public void finish (Database.BatchableContext BC) {
        // execute any post-processing operations
    }

    public class AccounTeamWrapper {
        public Id user;
        public Id account;
        String segmentacion;
        public AccountTeamMember accountTeam;

        public AccounTeamWrapper (Id user, Id account, String segmentacion, AccountTeamMember accountTeam) {
            this.user = user;
            this.account = account;
            this.segmentacion = segmentacion;
            this.accountTeam = accountTeam;
        }
    }*/

}