force-app/main/default/objects/Contacto_de_paciente__c/Contacto_de_paciente__c.object-meta.xml
<CustomObject>
    <label>Contacto de paciente</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Número de Contacto de paciente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contactos de paciente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contacto_de_paciente__c/fields/Paciente__c.field-meta.xml
<CustomField>
    <fullName>Paciente__c</fullName>
    <label>Paciente</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Best Care</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Regular</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Consumidor Baby</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contactos de paciente</relationshipLabel>
    <relationshipName>Contactos_de_paciente</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CreateContactAccountController.cls
public with sharing class CreateContactAccountController {

    public Id IdAccount {get; set;}
    public Contacto_de_paciente__c contactoDePaciente {get; set;}
    
	public CreateContactAccountController() {
    	IdAccount = ApexPages.currentPage().getParameters().get('id');
        if (String.isBlank(IdAccount)) {
        	ApexPages.Message mensajeError = new ApexPages.Message(
                ApexPages.Severity.ERROR,
                '¡Error al cargar datos del paciente!'
            );
			ApexPages.addMessage(mensajeError); 
        } else {
			contactoDePaciente = new Contacto_de_paciente__c();
        	contactoDePaciente.Paciente__c = IdAccount; 
        }
        
	}

    public PageReference guardar() {

        Database.SaveResult resultado = Database.insert(contactoDePaciente, false);
        if (!resultado.isSuccess()) {
			for (Database.Error msg : resultado.getErrors()) {
				ApexPages.Message mensajeError = new ApexPages.Message(
					ApexPages.Severity.ERROR,
					msg.getMessage()
				);
				ApexPages.addMessage(mensajeError);
			}
            return null;  
        }
        
        ApexPages.Message mensaje = new ApexPages.Message(
        	ApexPages.Severity.CONFIRM,
            '¡Se insertaron los datos correctamente!'
		);
		ApexPages.addMessage(mensaje);
		PageReference pagina = new PageReference('/' + contactoDePaciente.Id);
        return pagina;
    }

}