force-app/main/default/objects/Interaccion__c/Interaccion__c.object-meta.xml
<CustomObject>
    <label>Interacción</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Nombre de Interacción</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interacciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Muestras_Entregadas__c/Muestras_Entregadas__c.object-meta.xml
<CustomObject>
    <label>Muestras Entregadas</label>
    <nameField>
        <displayFormat>MM-{0000}</displayFormat>
        <label>Muestras Entregadas Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Muestras Entregadas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Muestras_Entregadas__c/fields/Interaccion__c.field-meta.xml
<CustomField>
    <fullName>Interaccion__c</fullName>
    <label>Interacción</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dan360_Interacciones__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Visita Médica</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dan360_Interacciones__c</referenceTo>
    <relationshipLabel>Muestras Entregadas</relationshipLabel>
    <relationshipName>Muestras_Entregadas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Muestras_Entregadas__c/fields/Stock_x_MM__c.field-meta.xml
<CustomField>
    <fullName>Stock_x_MM__c</fullName>
    <label>Stock x MM</label>
    <referenceTo>Stock_x_MM__c</referenceTo>
    <relationshipLabel>Muestras Entregadas</relationshipLabel>
    <relationshipName>Muestras_Entregadas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock_x_MM__c/Stock_x_MM__c.object-meta.xml
<CustomObject>
    <label>Stock x MM</label>
    <nameField>
        <displayFormat>SXM-{0000}</displayFormat>
        <label>Stock x MM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock x MM</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/MuestrasEntregadasTriggerHelper.cls
public with sharing class MuestrasEntregadasTriggerHelper {
    
    public static void checkDuplicates(List<Muestras_Entregadas__c> muestrasMedicas){
        Map<String, List<String>> mapInteraccionStockxMMInsert = new Map<String, List<String>>(); // Guarda la interaccion de la muestra a insertar con su stockMM
        Map<String, List<String>> mapInteraccionProductNameInsert = new Map<String, List<String>>(); // Guarda la interaccion de la muestra a insertar con el nombre del producto
        List<String> stockxMMIds = new List<String>(); // Guarda los StockMM de las muestras a insertar
        List<String> interaccionesIds = new List<String>(); // Guarda las inteacciones de las muestras a insertar
        for(Muestras_Entregadas__c muestraMedica : muestrasMedicas){
            interaccionesIds.add(muestraMedica.Interaccion__c);
        }
        
        Map<String, List<String>> mapInteraccionStockMMSF = new Map<String, List<String>>();
        for(Muestras_Entregadas__c muestrasSf : [SELECT Interaccion__c, Stock_x_MM__c FROM Muestras_Entregadas__c WHERE Interaccion__c IN : interaccionesIds]){
            if(!mapInteraccionStockMMSF.containsKey(muestrasSf.Interaccion__c)){
                mapInteraccionStockMMSF.put(muestrasSf.Interaccion__c, new List<String>());
            }
            mapInteraccionStockMMSF.get(muestrasSf.Interaccion__c).add(muestrasSf.Stock_x_MM__c);
        }
        System.debug('mapInteraccionStockMMSF');
        System.debug(mapInteraccionStockMMSF);

        if(mapInteraccionStockMMSF.size()>0){
            for(Muestras_Entregadas__c muestraMedica : muestrasMedicas){
                if(mapInteraccionStockMMSF.containsKey(muestraMedica.Interaccion__c)){
                    for(String stockMMSF : mapInteraccionStockMMSF.get(muestraMedica.Interaccion__c)){
                        if(stockMMSF == muestraMedica.Stock_x_MM__c){
                            muestraMedica.addError('Muestra medica Duplicada en la interaccion: ' + muestraMedica.Interaccion__c);
                        }
                    }
                }
            }
        }
    }
}