force-app/main/default/objects/Ciclo__c/Ciclo__c.object-meta.xml
<CustomObject>
    <label>Ciclo</label>
    <nameField>
        <label>Nombre de Ciclo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ciclo__c/fields/Fecha_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_fin__c</fullName>
    <defaultValue>IF(
  MONTH(TODAY()) = 12,
  DATE( YEAR( TODAY()), 12, 31 ),
  DATE( YEAR( TODAY()), MONTH ( TODAY() ) + 1, 1 ) - 1 
)</defaultValue>
    <label>Fecha de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ciclo__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <defaultValue>TODAY()-DAY(TODAY())+1</defaultValue>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Licencia__c/Licencia__c.object-meta.xml
<CustomObject>
    <label>Licencia</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Nombre de Licencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Licencia__c/fields/Aprobado__c.field-meta.xml
<CustomField>
    <fullName>Aprobado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprobado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Ciclo__c.field-meta.xml
<CustomField>
    <fullName>Ciclo__c</fullName>
    <label>Ciclo</label>
    <referenceTo>Ciclo__c</referenceTo>
    <relationshipLabel>Licencias</relationshipLabel>
    <relationshipName>Licencias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Duracion_de_licencia__c.field-meta.xml
<CustomField>
    <fullName>Duracion_de_licencia__c</fullName>
    <label>Duración de licencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 día</fullName>
            </value>
            <value>
                <fullName>3/4 día</fullName>
            </value>
            <value>
                <fullName>1/2 día</fullName>
            </value>
            <value>
                <fullName>1/4 día</fullName>
            </value>
            <value>
                <fullName>1/5 día</fullName>
            </value>
            <value>
                <fullName>1/10 día</fullName>
            </value>
            <value>
                <fullName>1/20 día</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Fecha_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_fin__c</fullName>
    <label>Fecha de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Motivo__c.field-meta.xml
<CustomField>
    <fullName>Motivo__c</fullName>
    <label>Motivo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Participación en congresos</fullName>
            </value>
            <value>
                <fullName>Giras</fullName>
            </value>
            <value>
                <fullName>Convención de ventas</fullName>
            </value>
            <value>
                <fullName>Reuniones de equipo</fullName>
                <label>Reuniones en compañia</label>
            </value>
            <value>
                <fullName>Licencias varias</fullName>
            </value>
            <value>
                <fullName>Capacitaciones</fullName>
            </value>
            <value>
                <fullName>Reunión con Jefe</fullName>
            </value>
            <value>
                <fullName>Reunión SN</fullName>
            </value>
            <value>
                <fullName>Reuniones externas</fullName>
            </value>
            <value>
                <fullName>Reunión De Equipo</fullName>
            </value>
            <value>
                <fullName>Reunión Kae/Kam</fullName>
            </value>
            <value>
                <fullName>Traslado Por Gira</fullName>
            </value>
            <value>
                <fullName>Capacitaciones Equipo Promocional (Ta/Externo)</fullName>
            </value>
            <value>
                <fullName>Participación De Workshop Para La Ta De Stroke</fullName>
            </value>
            <value>
                <fullName>Participación De Workshop Para La Ta De Uti</fullName>
            </value>
            <value>
                <fullName>Participación De Workshop Para La Ta De Metabólicos</fullName>
            </value>
            <value>
                <fullName>Participación De Workshop Para Dieta Cetogenica</fullName>
            </value>
            <value>
                <fullName>Eventos</fullName>
            </value>
            <value>
                <fullName>Congresos</fullName>
            </value>
            <value>
                <fullName>Lanzamientos</fullName>
            </value>
            <value>
                <fullName>Reunión Con Hcp´S</fullName>
            </value>
            <value>
                <fullName>Reunión Con Auditores</fullName>
            </value>
            <value>
                <fullName>Averiguación Licitaciones</fullName>
            </value>
            <value>
                <fullName>Reunión De Ciclo</fullName>
            </value>
            <value>
                <fullName>Towhall</fullName>
            </value>
            <value>
                <fullName>Convención</fullName>
            </value>
            <value>
                <fullName>Capacitaciones Hr</fullName>
            </value>
            <value>
                <fullName>Semana adicional de vacaciones</fullName>
                <label>Vacaciones</label>
            </value>
            <value>
                <fullName>Compensatorios</fullName>
                <label>Compensatorio</label>
            </value>
            <value>
                <fullName>Enfermedad</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AprovacionLicencias_Controller.cls
public with sharing class AprovacionLicencias_Controller {
    public List<Licencia__c> licencias;
    public boolean haveRecords = false;
    public boolean todosAprobados {get;set;}
    public AprovacionLicencias_Controller(ApexPages.StandardController stdController)
    {
        String currentId = stdController.getId();
        todosAprobados = true;
        licencias = [SELECT Id, Name, 
                     Aprobado__c, Fecha_de_inicio__c,
                     Fecha_de_fin__c, Motivo__c, Duracion_de_Licencia__c 
                     FROM Licencia__c 
                     WHERE Ciclo__c =:currentId
                     ORDER BY Name];
        if(licencias.size() != null && licencias.size() > 0)
        {
            haveRecords = true;
            for(Licencia__c licencia : licencias)
            {
                if(!licencia.Aprobado__c)
                    todosAprobados = false;
            }
        }
    }
	public List<Licencia__c> getLicencias()
    {
        return licencias;
    }
   	public boolean getHaveRecords()
    {
        return haveRecords;
    }
    public void approveAll()
    {
        for(Licencia__c licencia : licencias)
        {
           	if(!licencia.Aprobado__c)
                licencia.Aprobado__c = true;
        }
      	sendApproves();
    }
    public void sendApproves()
    {
        update licencias;
    }
}