force-app/main/default/objects/Ciclo__c/Ciclo__c.object-meta.xml
<CustomObject>
    <label>Ciclo</label>
    <nameField>
        <label>Nombre de Ciclo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ciclo__c/fields/Actualizar__c.field-meta.xml
<CustomField>
    <fullName>Actualizar__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Sirve para hacer un ultimo calculo a los ciclos que ya cerraron</description>
    <label>Actualizar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ciclo__c/fields/Dias_de_campo_efectivo_transcurridos__c.field-meta.xml
<CustomField>
    <fullName>Dias_de_campo_efectivo_transcurridos__c</fullName>
    <label>Dias de campo efectivo transcurridos</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ciclo__c/fields/Fecha_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_fin__c</fullName>
    <defaultValue>IF(
  MONTH(TODAY()) = 12,
  DATE( YEAR( TODAY()), 12, 31 ),
  DATE( YEAR( TODAY()), MONTH ( TODAY() ) + 1, 1 ) - 1 
)</defaultValue>
    <label>Fecha de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ciclo__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <defaultValue>TODAY()-DAY(TODAY())+1</defaultValue>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Feriado__c/Feriado__c.object-meta.xml
<CustomObject>
    <label>Feriado</label>
    <nameField>
        <label>Nombre de Feriado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feriados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Licencia__c/Licencia__c.object-meta.xml
<CustomObject>
    <label>Licencia</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Nombre de Licencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Licencia__c/fields/Aprobado__c.field-meta.xml
<CustomField>
    <fullName>Aprobado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprobado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Ciclo__c.field-meta.xml
<CustomField>
    <fullName>Ciclo__c</fullName>
    <label>Ciclo</label>
    <referenceTo>Ciclo__c</referenceTo>
    <relationshipLabel>Licencias</relationshipLabel>
    <relationshipName>Licencias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Dia_decimal__c.field-meta.xml
<CustomField>
    <fullName>Dia_decimal__c</fullName>
    <formula>IF( Fecha_de_inicio__c &lt;&gt; Fecha_de_fin__c , Cantidad_de_dias_de_la_licencia__c,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1 día&quot;) , 1,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/2 día&quot;) , 0.5,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/4 día&quot;) , 0.25,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/5 día&quot;) , 0.20,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;3/4 día&quot;) , 0.75,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/10 día&quot;) , 0.1, 
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/20 día&quot;) , 0.05, 	0))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Día decimal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Fecha_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_fin__c</fullName>
    <label>Fecha de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DiasHabilesTranscurridosHelper.cls
public class DiasHabilesTranscurridosHelper  {
	// Esto es un remake de CycleTriggerHelper
	public static List<Ciclo__c> calcularDiasHabilesTranscurridos(List<Ciclo__c> sobjs) {
		List<Ciclo__c> resultados = new List<Ciclo__c>();
		Date fechaMinima = CycleTriggerHelper.obtenerFechaMinima(sobjs, 'fecha_de_inicio__c');
		Date fechaMaxima = CycleTriggerHelper.obtenerFechaMaxima(sobjs, 'fecha_de_fin__c');
		fechaMaxima = fechaMaxima <= System.today() ? fechaMaxima : System.today();
		fechaMinima = fechaMinima <= System.today() ? fechaMinima : null;
		if (fechaMinima == null || fechaMaxima == null) {
			return null;
		}
		//Map<Id, List<Licencia__c>> CicloLicencia = new Map<Id, List<Licencia__c>>();
		List<Feriado__c> diasFeriados = new List<Feriado__c>([
			SELECT Fecha__c
			FROM Feriado__c
			WHERE Fecha__c >= :fechaMinima
				AND Fecha__c <= :fechaMaxima
		]);
		
		Date inicioCiclosActuales = Date.newInstance(System.today().year(), System.today().month(), 1);
		for (Ciclo__c sobj : sobjs) {
			
			if((sobj.Fecha_de_inicio__c >= fechaMinima && sobj.Actualizar__c) || sobj.Fecha_de_inicio__c >= inicioCiclosActuales)
			{
				Date cicloFechaMaxima = fechaMaxima > sobj.Fecha_de_fin__c ? sobj.Fecha_de_fin__c : fechaMaxima;
				
				Decimal cantidadDeDias = CycleTriggerHelper.cantidadDeDiasNoHabiles(
					(Date) sobj.Fecha_de_inicio__c, (Date) cicloFechaMaxima, diasFeriados
				);
				
				cantidadDeDias = (Decimal) cicloFechaMaxima.day() - cantidadDeDias;
				
				if(sobj.Licencias__r != null && sobj.Licencias__r.size() > 0)
					cantidadDeDias -= calcularDiasDeLicenciaTranscurridos(sobj.Licencias__r, diasFeriados);
				if(cantidadDeDias < 0)
					cantidadDeDias = 0;
				sobj.Dias_de_campo_efectivo_transcurridos__c = cantidadDeDias;
				resultados.add(sobj);
				
				if(sobj.Fecha_de_inicio__c < inicioCiclosActuales) {
					sobj.Actualizar__c = false;
					
				}
			}
		}
		return resultados;
	}
	public static Decimal calcularDiasDeLicenciaTranscurridos(List<Licencia__c> licencias, List<Feriado__c> todosFeriados) 
	{
		Decimal diasARestar = 0;
		Date fechaMinima = CycleTriggerHelper.obtenerFechaMinima(licencias, 'fecha_de_inicio__c');
		Date fechaMaxima = CycleTriggerHelper.obtenerFechaMaxima(licencias, 'fecha_de_fin__c');
		fechaMaxima = fechaMaxima <= System.today() ? fechaMaxima : System.today();
		
		List<Feriado__c> diasFeriados = new List<Feriado__c>();
		for(Feriado__c feriado : todosFeriados)
		{
			if(feriado.Fecha__c >= fechaMinima && feriado.Fecha__c <= fechaMaxima)
				diasFeriados.add(feriado);
		}
		for (Licencia__c licencia : licencias) {
			if(licencia.Aprobado__c)
			{
				Date ultimaFecha = licencia.Fecha_de_fin__c < fechaMaxima ? licencia.Fecha_de_fin__c : fechaMaxima;

				Decimal cantDiasTranscurridos = 0;
				Decimal cantidadDeDias = 0;
				
				if(licencia.Fecha_de_inicio__c != null &&
						licencia.Fecha_de_inicio__c == licencia.Fecha_de_fin__c && 
						licencia.Dia_decimal__c != null)
				{
					cantDiasTranscurridos = licencia.Dia_decimal__c;
				}
				else if(licencia.Fecha_de_inicio__c != null)
				{
					cantDiasTranscurridos = ultimaFecha.day() - licencia.Fecha_de_inicio__c.day() + 1; // +1 porque el dia de inicio tambien cuenta
					
					cantidadDeDias = CycleTriggerHelper.cantidadDeDiasNoHabiles(licencia.Fecha_de_inicio__c, ultimaFecha, diasFeriados);
				}

				if(cantidadDeDias < 0)
					cantidadDeDias = 0;
				
				cantidadDeDias = cantDiasTranscurridos - cantidadDeDias;
				if(cantidadDeDias < 0)
					cantidadDeDias = 0;
				diasARestar += cantidadDeDias;
			}
		}
		return diasARestar;
	}
}