force-app/main/default/objects/Ciclo__c/Ciclo__c.object-meta.xml
<CustomObject>
    <label>Ciclo</label>
    <nameField>
        <label>Nombre de Ciclo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ciclo__c/fields/Actualizar__c.field-meta.xml
<CustomField>
    <fullName>Actualizar__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Sirve para hacer un ultimo calculo a los ciclos que ya cerraron</description>
    <label>Actualizar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ciclo__c/fields/Cantidad_de_dias_en_el_mes__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_dias_en_el_mes__c</fullName>
    <formula>(Fecha_de_fin__c - Fecha_de_inicio__c) + 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cantidad de días en el mes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ciclo__c/fields/Cantidad_de_dias_habiles__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_dias_habiles__c</fullName>
    <label>Cantidad de días hábiles</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ciclo__c/fields/Dias_de_campo_efectivo_transcurridos__c.field-meta.xml
<CustomField>
    <fullName>Dias_de_campo_efectivo_transcurridos__c</fullName>
    <label>Dias de campo efectivo transcurridos</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ciclo__c/fields/Fecha_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_fin__c</fullName>
    <defaultValue>IF(
  MONTH(TODAY()) = 12,
  DATE( YEAR( TODAY()), 12, 31 ),
  DATE( YEAR( TODAY()), MONTH ( TODAY() ) + 1, 1 ) - 1 
)</defaultValue>
    <label>Fecha de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ciclo__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <defaultValue>TODAY()-DAY(TODAY())+1</defaultValue>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Dan360_Licencia__c/Dan360_Licencia__c.object-meta.xml
<CustomObject>
    <description>Objeto para registrar las licencias y dias no promocionables del APM</description>
    <label>Licencia</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Licencia Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Licencia__c/fields/Cantidad_de_Dias__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Dias__c</fullName>
    <description>Devuelve la cantidad de dias HABILES que ocupara la Licencia restando la fecha de fin con la fecha de inicio</description>
    <formula>IF( Tipo_de_Registro__c = &apos;Tiempo_no_Promocional&apos;,  Cantidad_de_Horas_Valor__c,
			IF(
				Fecha_de_inicio__c == Fecha_de_Fin__c,	1,
				/*Si las Fecha_de_fin__c es sabado o domingo NO se le suma 1 a la cuenta */
				IF(OR(MOD( Fecha_de_Fin__c - DATE( 1900, 1, 1), 7) = 6, MOD( Fecha_de_Fin__c - DATE( 1900, 1, 1), 7) = 5),
							(5 * ( FLOOR( ( Fecha_de_Fin__c - DATE( 1900, 1, 8) ) / 7 ) ) + MIN( 5, MOD( Fecha_de_Fin__c - DATE( 1900, 1, 8), 7 ) ) )
							-
							(5 * ( FLOOR( ( Fecha_de_inicio__c - DATE( 1900, 1, 8) ) / 7 ) ) + MIN( 5, MOD( Fecha_de_inicio__c - DATE( 1900, 1, 8), 7 ) ) ),
							/*Si Fecha_de_fin__c es dia de semana  SI se le suma 1 a la cuenta*/
							(5 * ( FLOOR( ( Fecha_de_Fin__c - DATE( 1900, 1, 8) ) / 7 ) ) + MIN( 5, MOD( Fecha_de_Fin__c - DATE( 1900, 1, 8), 7 ) ) )
							-
							(5 * ( FLOOR( ( Fecha_de_inicio__c - DATE( 1900, 1, 8) ) / 7 ) ) + MIN( 5, MOD( Fecha_de_inicio__c - DATE( 1900, 1, 8), 7 ) ) )
							+ 1
						)

)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cantidad de Días</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <description>Fecha de finalizacion del la licencia/tiempo no promocional</description>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <description>Fecha de inicio desde que se tomo la licencia/tiempo no promocional</description>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Licencia__c/fields/VisMed_APM__c.field-meta.xml
<CustomField>
    <fullName>VisMed_APM__c</fullName>
    <label>APM</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licencias</relationshipLabel>
    <relationshipName>Licencias</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Licencia__c/Licencia__c.object-meta.xml
<CustomObject>
    <label>Licencia</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Nombre de Licencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Licencia__c/fields/Aprobado__c.field-meta.xml
<CustomField>
    <fullName>Aprobado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprobado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Cantidad_de_dias__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_dias__c</fullName>
    <formula>IF( Fecha_de_inicio__c &lt;&gt; Fecha_de_fin__c , (Fecha_de_fin__c -  Fecha_de_inicio__c) + 1, 
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1 día&quot;) , 1, 
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/2 día&quot;) , 0.5,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/4 día&quot;) , 0.25,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;3/4 día&quot;) , 0.75,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/10 día&quot;) , 0.1, 1))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cantidad de días</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Cantidad_de_dias_de_la_licencia__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_dias_de_la_licencia__c</fullName>
    <label>Cantidad de dias de la licencia</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Ciclo__c.field-meta.xml
<CustomField>
    <fullName>Ciclo__c</fullName>
    <label>Ciclo</label>
    <referenceTo>Ciclo__c</referenceTo>
    <relationshipLabel>Licencias</relationshipLabel>
    <relationshipName>Licencias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Dia_decimal__c.field-meta.xml
<CustomField>
    <fullName>Dia_decimal__c</fullName>
    <formula>IF( Fecha_de_inicio__c &lt;&gt; Fecha_de_fin__c , Cantidad_de_dias_de_la_licencia__c,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1 día&quot;) , 1,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/2 día&quot;) , 0.5,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/4 día&quot;) , 0.25,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/5 día&quot;) , 0.20,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;3/4 día&quot;) , 0.75,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/10 día&quot;) , 0.1, 
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/20 día&quot;) , 0.05, 	0))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Día decimal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Fecha_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_fin__c</fullName>
    <label>Fecha de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchUpdateCycles.cls
global class BatchUpdateCycles implements Database.Batchable<SObject> {

	global Database.QueryLocator start(Database.BatchableContext ciclosSearch) {

		Id recordTypeId = XappiaHelper.getRecordType('Contact', 'Visitador médico').Id;
		return Database.getQueryLocator(
			'SELECT Id,Cantidad_de_dias_habiles__c,Dias_de_campo_efectivo_transcurridos__c,' +
			'Fecha_de_inicio__c,Fecha_de_fin__c,Cantidad_de_dias_en_el_mes__c,Actualizar__c,' +
			'(SELECT Id,Cantidad_de_dias__C,Ciclo__c,Aprobado__c,Dia_decimal__c,' +
			'Cantidad_de_dias_de_la_licencia__c,' +
			'Fecha_de_inicio__c,Fecha_de_fin__c FROM Licencias__r) ' +
			'FROM Ciclo__c');

	}

   	global void execute(Database.BatchableContext ciclosSearch, List<Ciclo__c> scope) {

		List<Ciclo__c> results = DiasHabilesTranscurridosHelper.calcularDiasHabilesTranscurridos(scope);

		if (results != null && results.size() > 0) { 
			update results;
		}
	
	}
	
	global void finish(Database.BatchableContext ciclosSearch) {
		
	}
}