force-app/main/default/objects/Ciclo__c/Ciclo__c.object-meta.xml
<CustomObject>
    <label>Ciclo</label>
    <nameField>
        <label>Nombre de Ciclo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Feriado__c/Feriado__c.object-meta.xml
<CustomObject>
    <label>Feriado</label>
    <nameField>
        <label>Nombre de Feriado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feriados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Licencia__c/Licencia__c.object-meta.xml
<CustomObject>
    <label>Licencia</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Nombre de Licencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Licencia__c/fields/Aprobado__c.field-meta.xml
<CustomField>
    <fullName>Aprobado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprobado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Cantidad_de_dias__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_dias__c</fullName>
    <formula>IF( Fecha_de_inicio__c &lt;&gt; Fecha_de_fin__c , (Fecha_de_fin__c -  Fecha_de_inicio__c) + 1, 
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1 día&quot;) , 1, 
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/2 día&quot;) , 0.5,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/4 día&quot;) , 0.25,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;3/4 día&quot;) , 0.75,
IF( ISPICKVAL( Duracion_de_licencia__c , &quot;1/10 día&quot;) , 0.1, 1))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cantidad de días</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Cantidad_de_dias_de_la_licencia__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_dias_de_la_licencia__c</fullName>
    <label>Cantidad de dias de la licencia</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Licencia__c/fields/Ciclo__c.field-meta.xml
<CustomField>
    <fullName>Ciclo__c</fullName>
    <label>Ciclo</label>
    <referenceTo>Ciclo__c</referenceTo>
    <relationshipLabel>Licencias</relationshipLabel>
    <relationshipName>Licencias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LicenseTriggerTest.cls
@isTest
public class LicenseTriggerTest  {
    
    @IsTest public static void ShouldAddTheDailyDaysWithinASetDateRangeIfCreatedApprovedInTrue() {
        
        Licencia__c licencia = Build.aLicencia()
            .withCiclo(ciclo1)
            .withAprobado(true)
            .withFechaDeInicio(System.today())
            .withFechaDeFin(System.today().addDays(2))
            .build();
        
        Test.startTest();
        insert licencia;
        Test.stopTest();
        
        List<Licencia__c> licenciaBD = [
            SELECT Id, Cantidad_de_dias_de_la_licencia__c, Cantidad_de_dias__c
            FROM Licencia__c
        ];
        
        DateTime tomorrowDate = System.now().addDays(1);                
        String dayName = tomorrowDate.format('EEEE');
        
        if (dayName == 'Saturday' || dayName == 'Sunday'){     
            System.assertEquals(3.00, licenciaBD[0].Cantidad_de_dias__c);
            System.assertEquals(1.00, licenciaBD[0].Cantidad_de_dias_de_la_licencia__c);
        }else{
            System.assertEquals(3.00, licenciaBD[0].Cantidad_de_dias__c);
            System.assertEquals(3.00, licenciaBD[0].Cantidad_de_dias_de_la_licencia__c);
        }
    }
    
    @IsTest public static void ShouldAddTheDailyDaysWithinASetDateRangeIfCreatedApprovedInFalseAndChangeToTrue() {
        
        insert primeraLicencia;
        primeraLicencia.Aprobado__c = true;
        
        Test.startTest();
        update primeraLicencia;
        Test.stopTest();
        
        List<Licencia__c> licenciaBD = [
            SELECT Id, Cantidad_de_dias_de_la_licencia__c, Cantidad_de_dias__c
            FROM Licencia__c
        ];
        DateTime tomorrowDate = System.now().addDays(1);                
        String dayName = tomorrowDate.format('EEEE');
        
        if (dayName == 'Saturday' || dayName == 'Sunday'){     
            System.assertEquals(2, licenciaBD[0].Cantidad_de_dias__c);
            System.assertEquals(1, licenciaBD[0].Cantidad_de_dias_de_la_licencia__c);
        }else{
            System.assertEquals(2, licenciaBD[0].Cantidad_de_dias__c);
            System.assertEquals(2, licenciaBD[0].Cantidad_de_dias_de_la_licencia__c);
        }
    }
    
    @IsTest public static void ShouldAddTheDailyDaysWithinASetDateRangeIfNotApproved() {
        
        insert primeraLicencia;
        insert segundaLicencia;
        insert terceraLicencia;
        insert cuartaLicencia;
        
        segundaLicencia.Aprobado__c = true;
        terceraLicencia.Aprobado__c = true;
        cuartaLicencia.Aprobado__c = true;
        
        Test.startTest();
        update segundaLicencia;
        update terceraLicencia;
        update cuartaLicencia;
        Test.stopTest();
        
        List<Licencia__c> licenciaBD = [
            SELECT Id, Cantidad_de_dias_de_la_licencia__c, Cantidad_de_dias__c
            FROM Licencia__c
        ];
        DateTime tomorrowDate = System.now().addDays(1);                
        String dayName = tomorrowDate.format('EEEE');
        
        if (dayName == 'Saturday' || dayName == 'Sunday'){ 
            
            System.assertEquals(1.00, licenciaBD[2].Cantidad_de_dias_de_la_licencia__c);
            System.assertEquals(null, licenciaBD[0].Cantidad_de_dias_de_la_licencia__c);
            System.assertEquals(0.1, licenciaBD[1].Cantidad_de_dias_de_la_licencia__c);
            System.assertEquals(1, licenciaBD[3].Cantidad_de_dias_de_la_licencia__c);
        }else{
            System.assertEquals(null, licenciaBD[0].Cantidad_de_dias_de_la_licencia__c);
            System.assertEquals(0.1, licenciaBD[1].Cantidad_de_dias_de_la_licencia__c);
            System.assertEquals(2, licenciaBD[3].Cantidad_de_dias_de_la_licencia__c);
            System.assertEquals(3.00, licenciaBD[2].Cantidad_de_dias_de_la_licencia__c);
        }
    }
    
    @IsTest public static void ShouldEliminateLicenseDaysIfApprovedChangesFromTrueToFalse() {
        
        insert segundaLicencia;
        
        segundaLicencia.Aprobado__c = true;
        update segundaLicencia;
        
        segundaLicencia.Aprobado__c = false;
        
        Test.startTest();
        update segundaLicencia;
        Test.stopTest();
        
        List<Licencia__c> licenciaBD = [
            SELECT Id, Cantidad_de_dias_de_la_licencia__c, Cantidad_de_dias__c
            FROM Licencia__c
        ];
        
        System.assertEquals(0, licenciaBD[0].Cantidad_de_dias_de_la_licencia__c);
    }
    
    static Ciclo__c ciclo1, ciclo2;
    static Feriado__c feriado1;
    static Licencia__c primeraLicencia, segundaLicencia, terceraLicencia, cuartaLicencia;
    
    static {
        Date firstDayOfMonth = System.today().toStartOfMonth();
        Date lastDayOfMonth = firstDayOfMonth.addDays(Date.daysInMonth(firstDayOfMonth.year(), firstDayOfMonth.month()) - 1);        
        ciclo1 = Build.aCiclo()
            .withName('New Ciclo')
            .withFechaDeInicio(Date.newInstance(System.today().year(),System.today().month(),firstDayOfMonth.day()))
            .withFechaDeFin(Date.newInstance(System.today().year(),System.today().month(),lastDayOfMonth.day()))
            .build();
        insert ciclo1;
        
        ciclo2 = Build.aCiclo()
            .withName('New Ciclo')
            .withFechaDeInicio(Date.newInstance(System.today().year(),System.today().month(),firstDayOfMonth.day()))
            .withFechaDeFin(Date.newInstance(System.today().year(),System.today().month(),lastDayOfMonth.day()))
            .build();
        insert ciclo2;
        
        feriado1 = Build.aFeriado()
            .withFecha(Date.newInstance(System.today().year(),System.today().month(),16))
            .build();
        insert feriado1;
        
        primeraLicencia = Build.aLicencia()
            .withCiclo(ciclo1)
            .withAprobado(false)
            .withFechaDeInicio(Date.newInstance(System.today().year(),System.today().month(),System.today().day()))
            .withFechaDeFin(Date.newInstance(System.today().year(),System.today().month(),System.today().day()).addDays(1))
            .build();
        
        segundaLicencia = Build.aLicencia()
            .withCiclo(ciclo2)
            .withAprobado(false)
            .withDuracionDeLicencia('1/10 día')
            .withFechaDeInicio(Date.newInstance(System.today().year(),System.today().month(),System.today().day()))
            .withFechaDeFin(Date.newInstance(System.today().year(),System.today().month(),System.today().day()))
            .build();
        
        terceraLicencia = Build.aLicencia()
            .withCiclo(ciclo1)
            .withAprobado(false)
            .withFechaDeInicio(Date.newInstance(System.today().year(),System.today().month(),System.today().day()))
            .withFechaDeFin(Date.newInstance(System.today().year(),System.today().month(),System.today().day()).addDays(2))
            .build();
        
        cuartaLicencia = Build.aLicencia()
            .withCiclo(ciclo2)
            .withAprobado(false)
            .withFechaDeInicio(Date.newInstance(System.today().year(),System.today().month(),System.today().day()))
            .withFechaDeFin(Date.newInstance(System.today().year(),System.today().month(),System.today().day()).addDays(1))
            .build();
    }
    
}