force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/Dan360_DocumentosCuentaCorriente__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacenará los documentos de cuenta corriente que se relacionan a las cuentas.</description>
    <label>Documento de Cuenta Corriente</label>
    <nameField>
        <label>Nombre de Documentos de Cuenta Corriente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentos de Cuenta Corriente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_Acumulado__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Acumulado__c</fullName>
    <label>Acumulado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CodigoCliente__c</fullName>
    <formula>Dan360_Cliente__r.Id_SAP__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de cliente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_DiasDeVencido__c.field-meta.xml
<CustomField>
    <fullName>Dan360_DiasDeVencido__c</fullName>
    <formula>IF(
Dan360_Vencimiento__c &lt; today(),
TODAY() - Dan360_Vencimiento__c, 0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Días de vencido</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_FechaDocumento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_FechaDocumento__c</fullName>
    <label>Fecha de documento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_ImporteDocumento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_ImporteDocumento__c</fullName>
    <label>Importe Documento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remito</label>
    <referenceTo>Dan360_Remito__c</referenceTo>
    <relationshipName>Documentos_de_Cuenta_Corriente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_Saldo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Saldo__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_Semaforo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Semaforo__c</fullName>
    <formula>IF(
Dan360_Saldo__c = 0 ,&quot;🟢&quot;,
IF(
AND( Dan360_Saldo__c &gt; 0, TODAY() &gt; Dan360_Vencimiento__c ), &quot;🔴&quot;,
IF(
AND( Dan360_Saldo__c &gt; 0, TODAY() &lt;= Dan360_Vencimiento__c ), &quot;⚫&quot;
,&quot;&quot;
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Semáforo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_TipoDeDocumento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_TipoDeDocumento__c</fullName>
    <label>Tipo de Documento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FCNUA</fullName>
            </value>
            <value>
                <fullName>FCNUB</fullName>
            </value>
            <value>
                <fullName>FCNUE</fullName>
            </value>
            <value>
                <fullName>NCNUA</fullName>
            </value>
            <value>
                <fullName>NCNUB</fullName>
            </value>
            <value>
                <fullName>NCNUE</fullName>
            </value>
            <value>
                <fullName>NDNUA</fullName>
            </value>
            <value>
                <fullName>NDNUB</fullName>
            </value>
            <value>
                <fullName>NDNUE</fullName>
            </value>
            <value>
                <fullName>FCNUAC</fullName>
            </value>
            <value>
                <fullName>FCNUBC</fullName>
            </value>
            <value>
                <fullName>NCNUAC</fullName>
            </value>
            <value>
                <fullName>NCNUBC</fullName>
            </value>
            <value>
                <fullName>NDNUAC</fullName>
            </value>
            <value>
                <fullName>NDNUBC</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_Vencimiento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Vencimiento__c</fullName>
    <label>Fecha de vencimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Remito__c/Dan360_Remito__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los remitos que se relacionan a un pedido</description>
    <label>Remito</label>
    <nameField>
        <displayFormat>Rem{0000}</displayFormat>
        <label>Nombre de Remito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Remito__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <label>Remito</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CheckingAccountController.cls
public with sharing class CheckingAccountController {
	@AuraEnabled
	public static ServerResponse getCheckingAccountDocuments(Map<String, String> criteria) {
		ServerResponse response;
		TreeGrid grid = new TreeGrid();
		Danone360Helper helper = new Danone360Helper('Dan360_DocumentosCuentaCorriente__c');
		GridColumn.TypeAttributes typeAttributes = new GridColumn.TypeAttributes();
		GridColumn.Label label = new GridColumn.Label();
		// GridColumn.TypeAttributes typeAttributes2 = new GridColumn.TypeAttributes();
		// GridColumn.Label label2 = new GridColumn.Label();

		label.fieldName = 'ProofNumber';
		typeAttributes.label = label;
		typeAttributes.target = '_parent';
		typeAttributes.tooltip = new GridColumn.Tooltip();
		typeAttributes.tooltip.fieldName = 'ProofNumber';
		grid.GridColumns = new List<GridColumn>();
		grid.GridColumns.add(helper.getCustomColumn('ProofNumberLink', 'url', 'Número de documento', true,  typeAttributes));
		grid.GridColumns.add(helper.getColumn('Dan360_TipoDeDocumento__c', true));
		grid.GridColumns.add(helper.getColumn('Dan360_CodigoCliente__c', true));

		typeAttributes = new GridColumn.TypeAttributes();
		label = new GridColumn.Label();
		label.fieldName = 'SubsidiaryName';
		typeAttributes.label = label;
		typeAttributes.target = '_parent';
		typeAttributes.tooltip = new GridColumn.Tooltip();
		typeAttributes.tooltip.fieldName = 'SubsidiaryName';
		grid.GridColumns.add(helper.getCustomColumn('SubsidiaryName', 'text', 'Sucursal', true,  typeAttributes));

		typeAttributes = new GridColumn.TypeAttributes();
		label = new GridColumn.Label();
		label.fieldName = 'SubsidiaryBillingStreet';
		typeAttributes.label = label;
		typeAttributes.target = '_parent';
		typeAttributes.tooltip = new GridColumn.Tooltip();
		typeAttributes.tooltip.fieldName = 'SubsidiaryBillingStreet';
		grid.GridColumns.add(helper.getCustomColumn('SubsidiaryBillingStreet', 'text', 'Dirección', true,  typeAttributes));
		grid.GridColumns.add(helper.getColumn('Dan360_FechaDocumento__c', true));
		grid.GridColumns.add(helper.getColumn('Dan360_Vencimiento__c', true));
		grid.GridColumns.add(helper.getColumn('Dan360_Remito__c', true));
		grid.GridColumns.add(helper.getColumn('Dan360_DiasDeVencido__c', true));
		grid.GridColumns.add(helper.getColumn('Dan360_ImporteDocumento__c', 'currency', true));
		grid.GridColumns.add(helper.getColumn('Dan360_Saldo__c', 'currency', true));
		grid.GridColumns.add(helper.getColumn('Dan360_Acumulado__c', 'currency', true));
		grid.GridColumns.add(helper.getColumn('Dan360_Semaforo__c', true));
		// grid.GridColumns.add(helper.getCustomColumn('PDFLink', 'html', '', true,  typeAttributes2));

		grid.GridData = CheckingAccountHelper.getDocumentsData(criteria);
		response = new ServerResponse('SUCCESS', grid, '');

		if (
			grid.GridData == null ||
			((Map<String, Map<String, Object>>)grid.GridData).isEmpty() ||
			((Map<String, Map<String, Object>>)grid.GridData).size() == 0
		) {
			response.message = 'No se encontraron resultados con los datos ingresados, intente con otros criterios.';
		}

		return response;
	}

	@AuraEnabled
	public static ServerResponse getUserInfo(Id userId){
		ServerResponse response = new ServerResponse();

		response.state = 'SUCCESS';
		response.data = [SELECT AccountId FROM User WHERE Id = :userId];

		return response;
	}

	@AuraEnabled
	public static String getFieldSet(String fieldSetName) {
		Danone360Helper helper = new Danone360Helper('Dan360_DocumentosCuentaCorriente__c');
		List<Danone360Helper.FieldWrapper> fieldset = (List<Danone360Helper.FieldWrapper>)JSON.deserialize(
			JSON.serialize(helper.getFieldSetMembers(fieldSetName)),
			List<Danone360Helper.FieldWrapper>.class
		);

		for (Danone360Helper.FieldWrapper field : fieldset) {
			if (field.type == 'picklist') {
				if (field.fieldPath.indexOf('__r') > -1) {
					List<String> arr = field.fieldPath.split('\\.');
					field.sobjectName = helper.getFieldReference(arr[0].replace('__r', '__c'));
					field.picklistApiName = arr[1];
				} else {
					field.sobjectName = 'Dan360_DocumentosCuentaCorriente__c';
					field.picklistApiName = field.fieldPath;
				}
			} else if (field.type == 'reference') {
				if (field.fieldPath.indexOf('__r') > -1) {
					List<String> arr = field.fieldPath.split('\\.');
					field.sobjectName = helper.getFieldReference(arr[0].replace('__r', '__c'));
				} else {
					field.sobjectName = helper.getFieldReference(field.fieldPath);
				}
			} else if (field.type == 'date') {
				if (field.fieldPath == 'Dan360_FechaDocumento__c') {
					field.label = 'Fecha inicial';
					field.fieldPath = 'startDate';
				}
			}
		}

		return JSON.serialize(fieldset);
	}
}