force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/Dan360_DocumentosCuentaCorriente__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacenará los documentos de cuenta corriente que se relacionan a las cuentas.</description>
    <label>Documento de Cuenta Corriente</label>
    <nameField>
        <label>Nombre de Documentos de Cuenta Corriente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentos de Cuenta Corriente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_Factura__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Factura__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Factura</label>
    <referenceTo>Dan360_Factura__c</referenceTo>
    <relationshipName>Documentos_de_Cuenta_Corriente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_NroComprobante__c.field-meta.xml
<CustomField>
    <fullName>Dan360_NroComprobante__c</fullName>
    <label>Nro de Comprobante</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remito</label>
    <referenceTo>Dan360_Remito__c</referenceTo>
    <relationshipName>Documentos_de_Cuenta_Corriente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/Dan360_Factura__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los documentos de cuentas corrientes de los clientes que se relacionan a un pedido.</description>
    <label>Factura</label>
    <nameField>
        <displayFormat>Fact-{0000}</displayFormat>
        <label>Nombre de Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_NroComprobante__c.field-meta.xml
<CustomField>
    <fullName>Dan360_NroComprobante__c</fullName>
    <label>NroComprobante</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remito al cual está relacionada una factura.</description>
    <label>Remito</label>
    <referenceTo>Dan360_Remito__c</referenceTo>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Remito__c/Dan360_Remito__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los remitos que se relacionan a un pedido</description>
    <label>Remito</label>
    <nameField>
        <displayFormat>Rem{0000}</displayFormat>
        <label>Nombre de Remito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Remito__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <label>Remito</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_TablaIntermediaCuentaCorriente__c/Dan360_TablaIntermediaCuentaCorriente__c.object-meta.xml
<CustomObject>
    <description>Objeto para recibir la información del Screenshot de cuenta corriente</description>
    <label>Tabla intermedia de cuenta corriente</label>
    <nameField>
        <label>Nombre de Tabla intermedia de cuenta cor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabla intermedia de cuenta corriente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_TablaIntermediaCuentaCorriente__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <label>Remito</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Id_Externo__c</fullName>
    <description>Id Externo de la órdenes. Se diligenciará a través de una automatización para replicar el número de la orden de Salesforce.</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchCuentaCorrienteTest.cls
@isTest
public class BatchCuentaCorrienteTest {
    @testSetup
    public static void makeData(){
        Account account = Build.anAccount()
            .withName('Account 1')
            .withIdSap('000012')
			.build();
		insert account;
        System.debug(account.Id);

        Account account2 = Build.anAccount()
            .withName('Account 2')
            .withIdSap('550074147')
			.build();
		insert account2;
        System.debug(account.Id);

        Order order = Build.anOrder()
			.withAccount(account)
			.withStatus('Borrador')
            .withBusinessUnit('5771')
            .withEffectiveDate(Date.today())
			.build();
		insert order;

        Order order2 = Build.anOrder()
			.withAccount(account2)
			.withStatus('Borrador')
            .withBusinessUnit('5771')
            .withEffectiveDate(Date.today())
			.build();
		insert order2;

        Dan360_Remito__c remito = Build.aRemito()
            .withPedido(order)
            .withSucursal(account)
            .withDelivery('Rem0000')
            .build();
        insert remito;

        Dan360_Remito__c remito2 = Build.aRemito()
            .withPedido(order2)
            .withSucursal(account2)
            .withDelivery('Rem0022')
            .build();
        insert remito2;

        Dan360_Factura__c factura = Build.aFactura()
            .withClient(account)
            .withRemito(remito)
            .withPedido(order)
            .withSucursal(account)
            .build();
            factura.Dan360_Id_Externo__c = '12345';
            factura.Dan360_NroComprobante__c = '00001';
        insert factura;

        Dan360_Factura__c factura2 = Build.aFactura()
            .withClient(account2)
            .withRemito(remito2)
            .withPedido(order2)
            .withSucursal(account2)
            .build();
            factura2.Dan360_Id_Externo__c = '98765';
            factura2.Dan360_NroComprobante__c = '00002';
        insert factura2;

        Dan360_TablaIntermediaCuentaCorriente__c cuentaCorriente = Build.aTablaIntermediaCuentaCorriente()
            .withName('CC Integracion 1')
            .withCodigoCliente('000012')
            .withFechaDocumento('20210211')
            .withIdRegistro('12345')
            .withImporteDocumento('2000')
            .withMoneda('USD')
            .withOrdenAplicacion('222')
            .withRemito('Rem0000')
            .withSaldo('1500')
            .withTipoDeDocumento('CC')
            .withVencimiento('20220122')
            .build();
        insert cuentaCorriente;

        Dan360_TablaIntermediaCuentaCorriente__c cuentaCorriente2 = Build.aTablaIntermediaCuentaCorriente()
            .withName('CC Integracion 2')
            .withCodigoCliente('550074147')
            .withFechaDocumento('20210211')
            .withIdRegistro('98765')
            .withImporteDocumento('2000')
            .withMoneda('USD')
            .withOrdenAplicacion('222')
            .withRemito('Rem0022')
            .withSaldo('1500')
            .withTipoDeDocumento('CC')
            .withVencimiento('20220122')
            .build();
        insert cuentaCorriente2;
    }
    @isTest
    private Static void cuandoSeCorreElBatchSeCreanLasCuentasCorrientes(){
        List<Dan360_TablaIntermediaCuentaCorriente__c> tablaIntermediaLista = [SELECT Id,Dan360_Remito__c 
                                                                FROM Dan360_TablaIntermediaCuentaCorriente__c];
        Test.startTest();
            BatchCuentaCorriente batch = new BatchCuentaCorriente();
            Database.executeBatch(batch);
        Test.stopTest();
        
        List<Dan360_DocumentosCuentaCorriente__c> cuentasCorrientesLista = [SELECT Id 
                                                                FROM Dan360_DocumentosCuentaCorriente__c];
        
        System.assertEquals(tablaIntermediaLista.size(), cuentasCorrientesLista.size(), 'No se crearon las cuentas corrientes esperadas.');
    }
    
    /* @isTest 
    private static void cuandoSeCorreElBatchLosRegistrosDeLaTablaIntermediaSeEliminan(){
        Test.startTest();
            BatchCuentaCorriente batch = new BatchCuentaCorriente();
            Database.executeBatch(batch);
        Test.stopTest();
        
        List<Dan360_TablaIntermediaCuentaCorriente__c> tablaIntermediaDespuesDelBatch = [SELECT Id 
                                                                FROM Dan360_TablaIntermediaCuentaCorriente__c];
        
        System.assertEquals(0, tablaIntermediaDespuesDelBatch.size(), 'Los registros de la tabla intermedia no se eliminaron corectamente.');
    } */
}