force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/Dan360_DocumentosCuentaCorriente__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacenará los documentos de cuenta corriente que se relacionan a las cuentas.</description>
    <label>Documento de Cuenta Corriente</label>
    <nameField>
        <label>Nombre de Documentos de Cuenta Corriente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentos de Cuenta Corriente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CodigoCliente__c</fullName>
    <formula>Dan360_Cliente__r.Id_SAP__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de cliente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_Factura__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Factura__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Factura</label>
    <referenceTo>Dan360_Factura__c</referenceTo>
    <relationshipName>Documentos_de_Cuenta_Corriente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_FechaDocumento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_FechaDocumento__c</fullName>
    <label>Fecha de documento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_ImporteDocumento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_ImporteDocumento__c</fullName>
    <label>Importe Documento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_NroComprobante__c.field-meta.xml
<CustomField>
    <fullName>Dan360_NroComprobante__c</fullName>
    <label>Nro de Comprobante</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remito</label>
    <referenceTo>Dan360_Remito__c</referenceTo>
    <relationshipName>Documentos_de_Cuenta_Corriente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_Saldo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Saldo__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dan360_DocumentosCuentaCorriente__c/fields/Dan360_Vencimiento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Vencimiento__c</fullName>
    <label>Fecha de vencimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/Dan360_Factura__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los documentos de cuentas corrientes de los clientes que se relacionan a un pedido.</description>
    <label>Factura</label>
    <nameField>
        <displayFormat>Fact-{0000}</displayFormat>
        <label>Nombre de Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CodigoCliente__c</fullName>
    <formula>Dan360_Cliente__r.Id_SAP__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de Cliente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_FechaDocumento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_FechaDocumento__c</fullName>
    <description>Indica la fecha en que se genero el documento de la cuenta corriente del cliente.</description>
    <label>Fecha de Documento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_ImporteDocumento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_ImporteDocumento__c</fullName>
    <description>Indica el importe registrado en el documento de la cuenta corriente del cliente.</description>
    <label>Importe Documento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Moneda__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Moneda__c</fullName>
    <label>Moneda</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_NroComprobante__c.field-meta.xml
<CustomField>
    <fullName>Dan360_NroComprobante__c</fullName>
    <label>NroComprobante</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Remito al cual está relacionada una factura.</description>
    <label>Remito</label>
    <referenceTo>Dan360_Remito__c</referenceTo>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Saldo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Saldo__c</fullName>
    <description>Indica el saldo de la transacción relacionada al documento de la cuenta corriente.</description>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_TipoDocumento__c</fullName>
    <label>Tipo de documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_Factura__c/fields/Dan360_Vencimiento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Vencimiento__c</fullName>
    <description>Indica la fecha de vencimiento del documento.</description>
    <label>Vencimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Remito__c/Dan360_Remito__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene los remitos que se relacionan a un pedido</description>
    <label>Remito</label>
    <nameField>
        <displayFormat>Rem{0000}</displayFormat>
        <label>Nombre de Remito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Remito__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <label>Remito</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_TablaIntermediaCuentaCorriente__c/Dan360_TablaIntermediaCuentaCorriente__c.object-meta.xml
<CustomObject>
    <description>Objeto para recibir la información del Screenshot de cuenta corriente</description>
    <label>Tabla intermedia de cuenta corriente</label>
    <nameField>
        <label>Nombre de Tabla intermedia de cuenta cor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabla intermedia de cuenta corriente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_TablaIntermediaCuentaCorriente__c/fields/Dan360_CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CodigoCliente__c</fullName>
    <label>Código cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_TablaIntermediaCuentaCorriente__c/fields/Dan360_CodigoEmpresaGrupo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_CodigoEmpresaGrupo__c</fullName>
    <label>Código empresa grupo</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_TablaIntermediaCuentaCorriente__c/fields/Dan360_FechaDocumento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_FechaDocumento__c</fullName>
    <label>Fecha documento</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_TablaIntermediaCuentaCorriente__c/fields/Dan360_IdRegistro__c.field-meta.xml
<CustomField>
    <fullName>Dan360_IdRegistro__c</fullName>
    <label>Id registro</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_TablaIntermediaCuentaCorriente__c/fields/Dan360_ImporteDocumento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_ImporteDocumento__c</fullName>
    <label>Importe Documento</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_TablaIntermediaCuentaCorriente__c/fields/Dan360_Moneda__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Moneda__c</fullName>
    <label>Moneda</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_TablaIntermediaCuentaCorriente__c/fields/Dan360_OrdenAplicacion__c.field-meta.xml
<CustomField>
    <fullName>Dan360_OrdenAplicacion__c</fullName>
    <label>Orden aplicación</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_TablaIntermediaCuentaCorriente__c/fields/Dan360_Remito__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Remito__c</fullName>
    <label>Remito</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_TablaIntermediaCuentaCorriente__c/fields/Dan360_Saldo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Saldo__c</fullName>
    <label>Saldo</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_TablaIntermediaCuentaCorriente__c/fields/Dan360_TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_TipoDocumento__c</fullName>
    <label>Tipo documento</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dan360_TablaIntermediaCuentaCorriente__c/fields/Dan360_Vencimiento__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Vencimiento__c</fullName>
    <label>Vencimiento</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Id_Externo__c</fullName>
    <description>Id Externo de la órdenes. Se diligenciará a través de una automatización para replicar el número de la orden de Salesforce.</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchDeleteCuentaCorrienteTest.cls
@isTest
public with sharing class BatchDeleteCuentaCorrienteTest {
    @testSetup
    private static void testSetup() {
        Account account = Build.anAccount()
            .withName('Account 1')
            .withIdSap('000012')
			.build();
		insert account;
        System.debug(account.Id);

        Account account2 = Build.anAccount()
            .withName('Account 2')
            .withIdSap('550074147')
			.build();
		insert account2;
        System.debug(account.Id);

        Order order = Build.anOrder()
			.withAccount(account)
			.withStatus('Borrador')
            .withBusinessUnit('5771')
            .withEffectiveDate(Date.today())
			.build();
		insert order;

        Order order2 = Build.anOrder()
			.withAccount(account2)
			.withStatus('Borrador')
            .withBusinessUnit('5771')
            .withEffectiveDate(Date.today())
			.build();
		insert order2;

        Dan360_Remito__c remito = Build.aRemito()
            .withPedido(order)
            .withSucursal(account)
            .withDelivery('Rem0000')
            .build();
        insert remito;

        Dan360_Remito__c remito2 = Build.aRemito()
            .withPedido(order2)
            .withSucursal(account2)
            .withDelivery('Rem0022')
            .build();
        insert remito2;

        Dan360_Factura__c factura = Build.aFactura()
            .withClient(account)
            .withRemito(remito)
            .withPedido(order)
            .withSucursal(account)
            .build();
            factura.Dan360_Id_Externo__c = '12345';
            factura.Dan360_NroComprobante__c = '00001';
        insert factura;

        Dan360_Factura__c factura2 = Build.aFactura()
            .withClient(account2)
            .withRemito(remito2)
            .withPedido(order2)
            .withSucursal(account2)
            .build();
            factura2.Dan360_Id_Externo__c = '98765';
            factura2.Dan360_NroComprobante__c = '00002';
        insert factura2;

        Dan360_TablaIntermediaCuentaCorriente__c cuentaCorriente = Build.aTablaIntermediaCuentaCorriente()
            .withName('CC Integracion 1')
            .withCodigoCliente('000012')
            .withFechaDocumento('20210211')
            .withIdRegistro('12345')
            .withImporteDocumento('2000')
            .withMoneda('USD')
            .withOrdenAplicacion('222')
            .withRemito('Rem0000')
            .withSaldo('1500')
            .withTipoDeDocumento('CC')
            .withVencimiento('20220122')
            .build();
        insert cuentaCorriente;

        Dan360_TablaIntermediaCuentaCorriente__c cuentaCorriente2 = Build.aTablaIntermediaCuentaCorriente()
            .withName('CC Integracion 2')
            .withCodigoCliente('550074147')
            .withFechaDocumento('20210211')
            .withIdRegistro('98765')
            .withImporteDocumento('2000')
            .withMoneda('USD')
            .withOrdenAplicacion('222')
            .withRemito('Rem0022')
            .withSaldo('1500')
            .withTipoDeDocumento('CC')
            .withVencimiento('20220122')
            .build();
        insert cuentaCorriente2;
    }
    @isTest
    private static void deleteCuentaCorriente() {
        // Test data setup
        List<Dan360_TablaIntermediaCuentaCorriente__c> tablaIntermediaList = [
            SELECT Id, Name, Dan360_CodigoCliente__c, 
                                Dan360_CodigoEmpresaGrupo__c,
                                Dan360_FechaDocumento__c,
                                Dan360_IdRegistro__c,
                                Dan360_ImporteDocumento__c,
                                Dan360_Moneda__c,
                                Dan360_OrdenAplicacion__c,
                                Dan360_Saldo__c,
                                Dan360_TipoDocumento__c,
                                Dan360_Vencimiento__c,
                                Dan360_Remito__c
            FROM Dan360_TablaIntermediaCuentaCorriente__c];

        List<Dan360_DocumentosCuentaCorriente__c> cuentasCorrientesLista = CheckingAccountHelper.armarCuentaCorriente(tablaIntermediaList);
        insert cuentasCorrientesLista;
        System.debug('Tamaño: '+cuentasCorrientesLista.size());
        // Actual test
        Test.startTest();
        BatchDeleteCuentaCorriente batch = new BatchDeleteCuentaCorriente();
        Database.executeBatch(batch);
        Test.stopTest();
        List<Dan360_DocumentosCuentaCorriente__c> cuentasCorrientesToCompare = [
            SELECT Id
            FROM Dan360_DocumentosCuentaCorriente__c
        ];
        // Asserts
        System.assertEquals(0, cuentasCorrientesToCompare.size(), 'Error No se eliminaron las cuentas corrientes');
    }
}