force-app/main/default/objects/Envio_sin_Cargo__c/Envio_sin_Cargo__c.object-meta.xml
<CustomObject>
    <label>Envío sin cargo</label>
    <nameField>
        <displayFormat>KIT-{00000}</displayFormat>
        <label>Nombre de Envio sin Cargo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Envíos sin cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Envio_sin_Cargo__c/fields/Estado_del_envio__c.field-meta.xml
<CustomField>
    <fullName>Estado_del_envio__c</fullName>
    <label>Estado del envio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ingresado</fullName>
                <default>true</default>
                <label>Ingresado</label>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Procesado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Ajuste Financiero</fullName>
                <isActive>false</isActive>
                <label>Ajuste Financiero</label>
            </value>
            <value>
                <fullName>Cerrado</fullName>
                <isActive>false</isActive>
                <label>Cerrado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Envio_sin_Cargo__c/fields/Paciente__c.field-meta.xml
<CustomField>
    <fullName>Paciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paciente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Envios_sin_Cargo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Producto_de_envio__c/Producto_de_envio__c.object-meta.xml
<CustomObject>
    <label>Producto de envío</label>
    <nameField>
        <displayFormat>PDE-{0000}</displayFormat>
        <label>Nro de Producto de Envío</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos de envío</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Producto_de_envio__c/fields/Envio_sin_cargo__c.field-meta.xml
<CustomField>
    <fullName>Envio_sin_cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Envío sin cargo</label>
    <referenceTo>Envio_sin_Cargo__c</referenceTo>
    <relationshipLabel>Productos de envío</relationshipLabel>
    <relationshipName>Productos_de_envio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GeneradorEnvioSinCargoTest.cls
@istest
public class GeneradorEnvioSinCargoTest {
    @istest
    static void siSeQuiereGenerarUnXML(){
        
        Account testAcc1 = Build.anAccount().withLastName('test')
            .withDNI('1234567')
            .withRecordTypeId(XappiaHelper.getRecordType('Account', 'Paciente Best Care').Id)
            .build();
        
        insert testAcc1;
        
        Envio_sin_Cargo__c testEnvSCargo = new Envio_sin_Cargo__c();
        testEnvSCargo.Paciente__c = testAcc1.id;

        insert testEnvSCargo;
        
        Producto_de_envio__c prDeEnvio = new Producto_de_envio__c();
        prDeEnvio.Envio_sin_cargo__c = testEnvSCargo.id;
        
        insert prDeEnvio;
        
        Producto_de_envio__c prDeEnvio2 = new Producto_de_envio__c();
        prDeEnvio2.Envio_sin_cargo__c = testEnvSCargo.id;
        
        insert prDeEnvio2;
        
        Test.startTest();
        String respuesta = GeneradorDeEnvioSinCargoParaJitterbit.generarNuevosEnviosParaJiter(testEnvSCargo.id);
        Test.stopTest();
        
        List<Envio_sin_Cargo__c> listEnvios = [
            SELECT Id,Estado_del_envio__c,Name
            FROM Envio_sin_Cargo__c
            WHERE id =:testEnvSCargo.id
        ];
        
        System.assertEquals(1,listEnvios.size());
        System.assertEquals('Reservado',listEnvios.get(0).Estado_del_envio__c);
        system.assertEquals('XML generado para envio: '+listEnvios.get(0).name,respuesta);
    }
    
    
     @istest
    static void ErrorSiSeQuiereGenerarUnXML(){
        
        Account testAcc1 = Build.anAccount().withLastName('test')
            .withDNI('1234567')
            .withRecordTypeId(XappiaHelper.getRecordType('Account', 'Paciente Best Care').Id)
            .build();
        
        insert testAcc1;
        
        Envio_sin_Cargo__c testEnvSCargo = new Envio_sin_Cargo__c();
        testEnvSCargo.Paciente__c = testAcc1.id;

        insert testEnvSCargo;
        
        Test.startTest();
        String respuesta = GeneradorDeEnvioSinCargoParaJitterbit.generarNuevosEnviosParaJiter(testEnvSCargo.id);
        Test.stopTest();
        
        system.assertEquals('Error. No se pueden generar XML vacios',respuesta);
    }
    
    @IsTest
    static void ErrorSiYaEstaReservado(){        
        Account testAcc1 = Build.anAccount().withLastName('test')
            .withDNI('1234567')
            .withRecordTypeId(XappiaHelper.getRecordType('Account', 'Paciente Best Care').Id)
            .build();
        
        insert testAcc1;
        
        Envio_sin_Cargo__c testEnvSCargo = new Envio_sin_Cargo__c();
        testEnvSCargo.Paciente__c = testAcc1.id;

        insert testEnvSCargo;
        
        Producto_de_envio__c prDeEnvio = new Producto_de_envio__c();
        prDeEnvio.Envio_sin_cargo__c = testEnvSCargo.id;
        
        insert prDeEnvio;
        
        Producto_de_envio__c prDeEnvio2 = new Producto_de_envio__c();
        prDeEnvio2.Envio_sin_cargo__c = testEnvSCargo.id;
        
        insert prDeEnvio2;
        GeneradorDeEnvioSinCargoParaJitterbit.generarNuevosEnviosParaJiter(testEnvSCargo.id);
        
        Test.startTest();
        String respuesta = GeneradorDeEnvioSinCargoParaJitterbit.generarNuevosEnviosParaJiter(testEnvSCargo.id);
        Test.stopTest();
        
        system.assertEquals('Ya se genero un XML para este Envío sin Cargo.',respuesta);
    }
}