force-app/main/default/objects/Envio_sin_Cargo__c/Envio_sin_Cargo__c.object-meta.xml
<CustomObject>
    <label>Envío sin cargo</label>
    <nameField>
        <displayFormat>KIT-{00000}</displayFormat>
        <label>Nombre de Envio sin Cargo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Envíos sin cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Envio_sin_Cargo__c/fields/Paciente__c.field-meta.xml
<CustomField>
    <fullName>Paciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paciente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Envios_sin_Cargo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Formulario_MarketingCloud__c/Formulario_MarketingCloud__c.object-meta.xml
<CustomObject>
    <label>Formularios Marketing Cloud</label>
    <nameField>
        <displayFormat>MC-{000000}</displayFormat>
        <label>Nombre del Formulario Marketing Cloud</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Formularios MarketingCloud</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Formulario_MarketingCloud__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Nombre y apellido del paciente</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La cuenta debe ser de un paciente (filtro)</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paciente Best Care, Paciente Regular</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Formularios Marketing Cloud</relationshipLabel>
    <relationshipName>Formularios_MarketingCloud</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Formulario_MarketingCloud__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <inlineHelpText>¿Qué documentación tuvo que presentar?</inlineHelpText>
    <label>Que documentación tuvo que presentar?</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Formulario_MarketingCloud__c/fields/Formula_que_consume_vs__c.field-meta.xml
<CustomField>
    <fullName>Formula_que_consume_vs__c</fullName>
    <label>Formula que consume</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Codigo_producto_Id_externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_producto_Id_externo__c</fullName>
    <externalId>true</externalId>
    <label>Código producto Id externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Producto_SAP__c.field-meta.xml
<CustomField>
    <fullName>Producto_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Producto SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Producto_de_envio__c/Producto_de_envio__c.object-meta.xml
<CustomObject>
    <label>Producto de envío</label>
    <nameField>
        <displayFormat>PDE-{0000}</displayFormat>
        <label>Nro de Producto de Envío</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos de envío</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Producto_de_envio__c/fields/Envio_sin_cargo__c.field-meta.xml
<CustomField>
    <fullName>Envio_sin_cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Envío sin cargo</label>
    <referenceTo>Envio_sin_Cargo__c</referenceTo>
    <relationshipLabel>Productos de envío</relationshipLabel>
    <relationshipName>Productos_de_envio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Producto_de_envio__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Formula</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El valor no existe o no coinciden los criterios de filtro.</errorMessage>
        <filterItems>
            <field>Product2.Producto_SAP__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Productos de envío</relationshipLabel>
    <relationshipName>Productos_de_envio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MkCloudNutritionForm_Test.cls
@isTest
public class MkCloudNutritionForm_Test {
    
    @isTest
    public static void testInsertionOfFormMKFromVisualforcePage(){
        Account acc = Build.anAccountPacienteBestCare()
            .withLastName('BestCare 2')
            .withAreaTerapeutica('Alergia')
            .withEstadoDePaciente('En tratamiento')
            .withSubestadoDePaciente('Tratamiento Efectivo')
            .build();
        insert acc;
        PageReference page = Page.FormularioVForce;
        
        Test.setCurrentPage(page);
        Apexpages.currentPage().getParameters().put('pcid',acc.id);
              
        MkCloudNutritionFormController controller = new MkCloudNutritionFormController(null);
        Account account =controller.getPaciente(acc.id);    
        controller.insertRecords();
        
        List<Formulario_MarketingCloud__c> formMK = [
            SELECT id,Cuenta__c,Formula_que_consume_vs__c
            FROM Formulario_MarketingCloud__c
        ];
        System.assertEquals(acc.id, formMK[0].Cuenta__c);
       
        /*Segunda vez que se quiere contestar el formulario*/
        Test.setCurrentPage(page);
        Apexpages.currentPage().getParameters().put('pcid',acc.id);
        Account sameAccount =controller.getPaciente(acc.id);
        
        System.assertEquals(null, sameAccount);
    }

    @isTest
    Public static void siElpacienteCompletaElFormularioSeLeDebenGenerarSuKit() {
        List<Product2> productos = new List<Product2>();
       
        for(integer i=0;i<5 ;i++){
            Product2 product = Build.aProduct2()
                .withProductoPara('Best Care')
                .withName('AMNoNUBA ' + i)
                .withDescription('Producto'+ i)
                .build();
                product.Producto_SAP__c= true;
                product.IsActive= true;
                
            productos.add(product);
        }
        productos[0].Codigo_producto_Id_externo__c = '49636';
        productos[1].Codigo_producto_Id_externo__c = '49621';    
        productos[2].Codigo_producto_Id_externo__c = '53930';    
        productos[3].Codigo_producto_Id_externo__c = '49635';    
        productos[4].Codigo_producto_Id_externo__c = '49638';    
        productos[4].Name = 'LP Drink';
        
        insert productos;
        
        Account testCuenta = Build.anAccountPacienteBestCare()
            .withLastName('Prueba Met')	
            .withDNI('425452222')
            .withAreaTerapeutica('Metabólicos')
            .withEstadoDePaciente('En tratamiento')
            .withSubestadoDePaciente('Tratamiento Efectivo')
            .build();
        
        insert testCuenta;
        
        Test.startTest();
        MkCloudNutritionFormController_Helper.generaKitsNUBAyAMN(testCuenta.id);
        Test.stopTest();
        
        List<Envio_Sin_Cargo__c> kits = [
            SELECT id,Paciente__c
            FROM Envio_Sin_Cargo__c
            WHERE  Paciente__c = :testCuenta.id
        ];
        Set<Id> kitsID = new Set<Id>();
        for(Envio_Sin_Cargo__c aKit: kits){
            kitsID.add(aKit.id);
        }
        List<Producto_de_envio__c> productosDB = [
            SELECT id, Envio_sin_cargo__c,Formula__r.Name
            FROM Producto_de_envio__c
            WHERE Formula__r.Name LIKE '%AMNoNUBA%'
        ];
        List<Task> tareasEYN = [
            SELECT id,WhatId
            FROM Task
            WHERE WhatId = :testCuenta.id
        ];
        System.assertEquals(2, kits.size());
        System.assertEquals(4, productosDB.size()); 
        System.assertEquals(1, tareasEYN.size());  
        
    }
    
}