force-app/main/default/objects/Envio_sin_Cargo__c/Envio_sin_Cargo__c.object-meta.xml
<CustomObject>
    <label>Envío sin cargo</label>
    <nameField>
        <displayFormat>KIT-{00000}</displayFormat>
        <label>Nombre de Envio sin Cargo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Envíos sin cargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Envio_sin_Cargo__c/fields/Estado_del_envio__c.field-meta.xml
<CustomField>
    <fullName>Estado_del_envio__c</fullName>
    <label>Estado del envio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ingresado</fullName>
                <default>true</default>
                <label>Ingresado</label>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Procesado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Ajuste Financiero</fullName>
                <isActive>false</isActive>
                <label>Ajuste Financiero</label>
            </value>
            <value>
                <fullName>Cerrado</fullName>
                <isActive>false</isActive>
                <label>Cerrado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Envio_sin_Cargo__c/fields/Xml_ya_generado__c.field-meta.xml
<CustomField>
    <fullName>Xml_ya_generado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Xml ya generado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Producto_de_envio__c/Producto_de_envio__c.object-meta.xml
<CustomObject>
    <label>Producto de envío</label>
    <nameField>
        <displayFormat>PDE-{0000}</displayFormat>
        <label>Nro de Producto de Envío</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos de envío</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Producto_de_envio__c/fields/Envio_sin_cargo__c.field-meta.xml
<CustomField>
    <fullName>Envio_sin_cargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Envío sin cargo</label>
    <referenceTo>Envio_sin_Cargo__c</referenceTo>
    <relationshipLabel>Productos de envío</relationshipLabel>
    <relationshipName>Productos_de_envio</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GeneradorDeEnvioSinCargoParaJitterbit.cls
global class GeneradorDeEnvioSinCargoParaJitterbit {
    
    WebService static String generarNuevosEnviosParaJiter(id envio){
        String status;
        
        List<Producto_de_envio__c> listProdEnvio = [
            SELECT id,Envio_sin_cargo__c, Envio_sin_Cargo__r.name,Envio_sin_Cargo__r.Estado_del_envio__c,Envio_sin_Cargo__r.Xml_ya_generado__c
            FROM Producto_de_envio__c
            WHERE Envio_sin_cargo__c = :envio
        ];
        
        
        if(!listProdEnvio.isEmpty()){
            if(!listProdEnvio.get(0).Envio_sin_Cargo__r.Xml_ya_generado__c){
                Envio_sin_Cargo__c envioToUpdate = new Envio_sin_Cargo__c(
                    Id = listProdEnvio.get(0).Envio_sin_Cargo__c,
                    Estado_del_envio__c = listProdEnvio.get(0).Envio_sin_Cargo__r.Estado_del_envio__c
                );
                
                status = 'XML generado para envio: '+listProdEnvio.get(0).Envio_sin_Cargo__r.name;
                envioToUpdate.Estado_del_envio__c= 'Reservado';
                envioToUpdate.Xml_ya_generado__c = true;
                
                update envioToUpdate;
                
            }
            else{
                status = 'Ya se genero un XML para este Envío sin Cargo.';
            }
        }
        else{
            status = 'Error. No se pueden generar XML vacios';         
        }
        
        return status;
    }
    
}