force-app/main/default/objects/Contact/fields/Sub_Equipo__c.field-meta.xml
<CustomField>
    <fullName>Sub_Equipo__c</fullName>
    <label>Sub Equipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Equipo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/VisMed_DNI__c.field-meta.xml
<CustomField>
    <fullName>VisMed_DNI__c</fullName>
    <label>DNI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Visitador_medico.recordType-meta.xml
<RecordType>
    <fullName>Visitador_medico</fullName>
    <active>true</active>
    <label>Visitador médico</label>
</RecordType>

force-app/main/default/objects/User/fields/Sub_Equipo__c.field-meta.xml
<CustomField>
    <fullName>Sub_Equipo__c</fullName>
    <label>Sub Equipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Equipo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/VisMed_ContrasenaApp__c.field-meta.xml
<CustomField>
    <fullName>VisMed_ContrasenaApp__c</fullName>
    <label>Contraseña App</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/globalValueSets/Sub_Equipo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Adultos Interior</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos Oncologia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos</fullName>
    </customValue>
    <customValue>
        <fullName>Dieta</fullName>
    </customValue>
    <customValue>
        <fullName>Pediatricos General</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos AMBA</fullName>
    </customValue>
    <customValue>
        <fullName>Metabólicos y Dieta</fullName>
    </customValue>
    <customValue>
        <fullName>Nicho MSL</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos General</fullName>
        <isActive>false</isActive>
        <label>Adultos General</label>
    </customValue>
    <masterLabel>Sub Equipo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FilteredTableControllerTest.cls
@IsTest public with sharing class FilteredTableControllerTest {
    @testSetup
    private static void testSetup() {
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile profile1 = [Select Id from Profile where Name = 'System Administrator' or name = 'Administrador del sistema' ];
    
        User userOwner = Build.aUser()
                .withUsername(
                    'newuser'+String.valueOf(System.now().getTime() + (Math.random() * 10))+'@testorg.com'
                )               
                .withEmail('owner@xappia.com')
                .withAlias('owner')
                .withLastName('Owner')
                .withTimeZoneSidKey('America/Argentina/Buenos_Aires')
                .withLocaleSidKey('es_AR')
                .withCommunityNickname('prueba2.xappia')
                .withEmailEncodingKey('ISO-8859-1')
                .withProfileId(profile1.Id)
                .withUserRoleId(portalRole)				
                .withLanguageLocaleKey('es')
                .build();           
        userOwner.ManagerId = UserInfo.getUserId();
        userOwner.IsActive = true;
        userOwner.VisMed_ContrasenaApp__c = 'TestOwner';
        insert userOwner;
    
        System.runAs(userOwner){

            Account account = Build.anAccount()            
                .withCanalComercial('E-Commerce')
                .withName('Cuenta Prueba')
                .withIdSap('12345')
                .build();
            
            insert account;
            
            Id recordTypeVisitadorMedico = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Visitador_Medico').getRecordTypeId();
            Contact apm = Build.aContactVisitadorMedico()
            .withAccount(account)            
            .build();
            apm.VisMed_DNI__c = '22222333';
            apm.RecordTypeId = recordTypeVisitadorMedico;
            apm.Sub_Equipo__c = 'Metabolicos';
            insert apm;

            Case caso = Build.aReclamo()
                .withAccount(account)            
                .build();
            caso.Priority = 'Medium';
            caso.Subject = 'Prueba';
            caso.Status = 'New';        
            caso.ContactId = apm.Id;
            insert caso;
        }
    }
    @IsTest
    static void methodName(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){  
            Case caso = [
                SELECT Id, CaseNumber, Subject, Status, Priority, Account.Name, Contact.Name
                FROM Case
                WHERE Status = 'New' AND Subject = 'Prueba'
            ];
            String caseNumber = caso.CaseNumber;
            String subject = caso.Subject;
            String priority = caso.Priority;
            String status = caso.Status;
            String accountName = caso.Account.Name;
            String contactName = caso.Contact.Name;
            Test.startTest();
                List<Case> result = FilteredTableController.getCases(caseNumber, subject, priority, status, accountName, contactName);
            Test.stopTest();

            System.debug(result);
            
            System.assertEquals(caso.Id, result[0].Id, 'Error al obtener caso');
        }    
    }

    @IsTest
    static void methodNameWithEmptyConditions(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){  
            Case caso = [
                SELECT Id, CaseNumber, Subject, Status, Priority, AccountId, Contact.Name
                FROM Case
                WHERE Status = 'New' AND Subject = 'Prueba'
            ];
            String caseNumber = caso.CaseNumber;
            String subject = caso.Subject;
            String priority = caso.Priority;
            String status = caso.Status;
            String accountName = caso.AccountId;
            Test.startTest();
                List<Case> result = FilteredTableController.getCases('', '', '', '', '', '');
            Test.stopTest();

            System.debug(result);
            
            System.assertEquals(caso.Id, result[0].Id, 'Error al obtener caso');
        }    
    }
    
}