force-app/main/default/objects/Contact/fields/Sub_Equipo__c.field-meta.xml
<CustomField>
    <fullName>Sub_Equipo__c</fullName>
    <label>Sub Equipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Equipo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/VisMed_DNI__c.field-meta.xml
<CustomField>
    <fullName>VisMed_DNI__c</fullName>
    <label>DNI</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Visitador_medico.recordType-meta.xml
<RecordType>
    <fullName>Visitador_medico</fullName>
    <active>true</active>
    <label>Visitador médico</label>
</RecordType>

force-app/main/default/objects/Dan360_Efectividad__c/Dan360_Efectividad__c.object-meta.xml
<CustomObject>
    <description>Objeto creado para el registro y calculo de las efectividades del APM por mes.</description>
    <label>Efectividad</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Efectividad Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Efectividades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/VisMed_APM__c.field-meta.xml
<CustomField>
    <fullName>VisMed_APM__c</fullName>
    <label>APM</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Efectividades</relationshipLabel>
    <relationshipName>Efectividades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_Efectividad__c/fields/VisMed_Ciclo__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Ciclo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciclo</label>
    <referenceTo>VisMed_Ciclo__c</referenceTo>
    <relationshipLabel>Efectividades</relationshipLabel>
    <relationshipName>Efectividades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Interacciones__c/Dan360_Interacciones__c.object-meta.xml
<CustomObject>
    <description>Objeto para registrar las interacciones/visitas realizadas</description>
    <label>Interacción</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Interacciones Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interacciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_Interacciones__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Aprobada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dan360_Interacciones__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interacciones (Profesional)</relationshipLabel>
    <relationshipName>Interacciones1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Interacciones__c/fields/VisMed_APM__c.field-meta.xml
<CustomField>
    <fullName>VisMed_APM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>APM que realizo la interaccion.</description>
    <label>APM</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interacciones (APM)</relationshipLabel>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dan360_Interacciones__c/recordTypes/Visita_Medica.recordType-meta.xml
<RecordType>
    <fullName>Visita_Medica</fullName>
    <active>true</active>
    <label>Visita Médica</label>
</RecordType>

force-app/main/default/objects/Notificacion__c/Notificacion__c.object-meta.xml
<CustomObject>
    <label>Notificacion</label>
    <nameField>
        <label>Titulo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notificaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Notificacion__c/fields/APM__c.field-meta.xml
<CustomField>
    <fullName>APM__c</fullName>
    <label>APM</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notificaciones</relationshipLabel>
    <relationshipName>Notificaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Segmenta_Por__c.field-meta.xml
<CustomField>
    <fullName>Segmenta_Por__c</fullName>
    <label>Segmenta Por</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Metabolicos</fullName>
            </value>
            <value>
                <fullName>Epilepsia</fullName>
            </value>
            <value>
                <fullName>Metabolicos y Epilepsia</fullName>
            </value>
            <value>
                <fullName>Pediatricos</fullName>
            </value>
            <value>
                <fullName>Alergia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sub_Equipo__c.field-meta.xml
<CustomField>
    <fullName>Sub_Equipo__c</fullName>
    <label>Sub Equipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Equipo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/VisMed_ContrasenaApp__c.field-meta.xml
<CustomField>
    <fullName>VisMed_ContrasenaApp__c</fullName>
    <label>Contraseña App</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/VisMed_Ciclo__c/VisMed_Ciclo__c.object-meta.xml
<CustomObject>
    <label>Ciclo</label>
    <nameField>
        <label>Ciclo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Ciclo__c/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/VisMed_Contacto_Cuenta_Usuario__c.object-meta.xml
<CustomObject>
    <description>Relacion de APM con el profesional y su lugar de trabajo</description>
    <label>Fichero</label>
    <nameField>
        <displayFormat>SEG-{0000}</displayFormat>
        <label>Seguimiento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ficheros</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Actualizar_Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Actualizar_Frecuencia__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo utilizado por el batch : BatchSetFrecuencia. Indica si hay que actualizar la frencuencia el ciclo siguiente.</description>
    <label>Actualizar Frecuencia</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Aun_Quedan_Meses__c.field-meta.xml
<CustomField>
    <fullName>Aun_Quedan_Meses__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Meses restantes de frecuencia</inlineHelpText>
    <label>Aun Quedan Meses</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Baja Temporal</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Estado_de_aprobacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_aprobacion__c</fullName>
    <label>Estado de aprobacion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprobada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Fin_de_Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Fin_de_Frecuencia__c</fullName>
    <label>Fin de Frecuencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Inicio_de_Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Inicio_de_Frecuencia__c</fullName>
    <label>Inicio de Frecuencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Predeterminada__c.field-meta.xml
<CustomField>
    <fullName>Predeterminada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Seguimientos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Segmenta_Por__c.field-meta.xml
<CustomField>
    <fullName>Segmenta_Por__c</fullName>
    <label>Segmenta Por</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Segmenta_Por</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Visitas_Realizadas__c.field-meta.xml
<CustomField>
    <fullName>Visitas_Realizadas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Visitas Realizadas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/VisMed_APM__c.field-meta.xml
<CustomField>
    <fullName>VisMed_APM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>APM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Visitador Medico</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ficheros</relationshipLabel>
    <relationshipName>Ficheros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/VisMed_Semaforo__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Semaforo__c</fullName>
    <label>Semaforo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/VisMed_Segmentacion__c.object-meta.xml
<CustomObject>
    <label>Segmentación</label>
    <nameField>
        <displayFormat>Segmentacion-{0000}</displayFormat>
        <label>Segmentación Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <formula>IF(
  OR(
    RecordType.Name =&apos;Metabolicos&apos;,
    RecordType.Name =&apos;Epilepsia&apos;,
    RecordType.Name =&apos;Metabolicos_y_Epilepsia&apos;
  ),
  Categoria_Nicho__c,
  IF(
    OR(
      RecordType.Name =&apos;Alergia&apos;,
      RecordType.Name =&apos;Pediatricos&apos;,
      RecordType.Name =&apos;Pediatricos General&apos;
    ),
    Categoria_Ped_Aler__c,
    Categoria_Nicho__c
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Categoria</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/recordTypes/Alergia.recordType-meta.xml
<RecordType>
    <fullName>Alergia</fullName>
    <active>true</active>
    <label>Alergia</label>
</RecordType>

force-app/main/default/objects/VisMed_Segmentacion__c/recordTypes/Epilepsia.recordType-meta.xml
<RecordType>
    <fullName>Epilepsia</fullName>
    <active>true</active>
    <label>Epilepsia</label>
</RecordType>

force-app/main/default/objects/VisMed_Segmentacion__c/recordTypes/Pediatricos.recordType-meta.xml
<RecordType>
    <fullName>Pediatricos</fullName>
    <active>true</active>
    <label>Pediatricos</label>
</RecordType>

force-app/main/default/globalValueSets/Segmenta_Por.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Adultos General Institucion</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos General Comunidad</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos Oncologia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos y Epilepsia</fullName>
    </customValue>
    <customValue>
        <fullName>Pediatricos General</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia</fullName>
    </customValue>
    <masterLabel>Segmenta Por</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sub_Equipo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Adultos Interior</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos Oncologia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos</fullName>
    </customValue>
    <customValue>
        <fullName>Dieta</fullName>
    </customValue>
    <customValue>
        <fullName>Pediatricos General</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos AMBA</fullName>
    </customValue>
    <customValue>
        <fullName>Metabólicos y Dieta</fullName>
    </customValue>
    <customValue>
        <fullName>Nicho MSL</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos General</fullName>
        <isActive>false</isActive>
        <label>Adultos General</label>
    </customValue>
    <masterLabel>Sub Equipo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SeguimientoTriggerHelperTest.cls
@IsTest
public with sharing class SeguimientoTriggerHelperTest {
	@TestSetup
	public static void makeData() {
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile profile1 = [Select Id from Profile where Name = 'System Administrator' or name = 'Administrador del sistema' ];
    
        User userOwner = Build.aUser()
                .withUsername(
                    'newuser'+String.valueOf(System.now().getTime() + (Math.random() * 10))+'@testorg.com'
                )               
                .withEmail('owner@xappia.com')
                .withAlias('owner')
                .withLastName('Owner')
                .withTimeZoneSidKey('America/Argentina/Buenos_Aires')
                .withLocaleSidKey('es_AR')
                .withCommunityNickname('prueba2.xappia')
                .withEmailEncodingKey('ISO-8859-1')
                .withProfileId(profile1.Id)
                .withUserRoleId(portalRole)				
                .withLanguageLocaleKey('es')
                .build();           
        userOwner.ManagerId = UserInfo.getUserId();
        userOwner.IsActive = true;
        userOwner.VisMed_ContrasenaApp__c = 'TestOwner';
        insert userOwner;
    
        System.runAs(userOwner){
            Account institucion = Build.anAccount()
                .withName('InstitucionTest')
                .build();
            insert institucion;

            Account institucion2 = Build.anAccount()
                .withName('InstitucionTest2')
                .build();
            insert institucion2;

            Account institucion3 = Build.anAccount()
                .withName('InstitucionTest3')
                .build();
            insert institucion3;
        
            Id recordTypeVisitadorMedico = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Visitador_Medico').getRecordTypeId();
            Contact apm = Build.aContactVisitadorMedico()
            .withAccount(institucion)            
            .build();
            apm.VisMed_DNI__c = '22222333';
            apm.RecordTypeId = recordTypeVisitadorMedico;
            apm.Sub_Equipo__c = 'Metabólicos y Dieta';
            insert apm;
                
            Profile perfilApm = [
            SELECT Id 
            FROM Profile 
            WHERE Name = 'APM' 
            LIMIT 1
            ];
            User userTest = Build.aUser()
            .withUsername(
                'newuser'+String.valueOf(System.now().getTime() + (Math.random() * 10))+'@testorg.com'
            )
            .withContactId(apm)
            .withLastName('Contacto1')
            .withEmail('contacto1@xappia.com')
            .withAlias('contact1')
            .withTimeZoneSidKey('America/Argentina/Buenos_Aires')
            .withLocaleSidKey('es_AR')
            .withCommunityNickname('prueba1.xappia')
            .withEmailEncodingKey('ISO-8859-1')
            .withProfileId(perfilApm.Id)
            .withLanguageLocaleKey('es')
            .build();

            userTest.IsActive = true;
            userTest.VisMed_ContrasenaApp__c = 'Test';
            userTest.ManagerId = userOwner.Id;
            userTest.DelegatedApproverId = userOwner.Id;

            insert userTest;
            Contact apmSemaforo = Build.aContactVisitadorMedico()
            .withAccount(institucion)            
            .build();
            apmSemaforo.VisMed_DNI__c = '22222444';
            apmSemaforo.RecordTypeId = recordTypeVisitadorMedico;
            apmSemaforo.Sub_Equipo__c = 'Metabólicos y Dieta';
            insert apmSemaforo;
                       
            User userSemaforo = Build.aUser()
            .withUsername(
                'newuser'+String.valueOf(System.now().getTime() + (Math.random() * 10))+'@testorg.com'
            )
            .withContactId(apmSemaforo)
            .withLastName('ContactoSemaforo')
            .withEmail('contactoSemaforo@xappia.com')
            .withAlias('cSema')
            .withTimeZoneSidKey('America/Argentina/Buenos_Aires')
            .withLocaleSidKey('es_AR')
            .withCommunityNickname('prueba3.xappia')
            .withEmailEncodingKey('ISO-8859-1')
            .withProfileId(perfilApm.Id)
            .withLanguageLocaleKey('es')
            .build();

            userSemaforo.IsActive = true;
            userSemaforo.VisMed_ContrasenaApp__c = 'Test';
            userSemaforo.ManagerId = userOwner.Id;
            userSemaforo.DelegatedApproverId = userOwner.Id;

            insert userSemaforo;
                
            Date today = Date.today();
            VisMed_Ciclo__c ciclo = Build.aCiclo()
            .withFechaInicio(today.toStartOfMonth())
            .withFechaFin(today.toStartOfMonth().addMonths(1).addDays(-1))
            .build();
            insert ciclo;

            Id recordTypeProfesional = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Profesional_de_la_Salud').getRecordTypeId();
            System.debug(recordTypeProfesional);
            Account aPersonAccount = Build.aPersonalAccount()
            .withFirstName('Profesional')
            //.withLastName('Test')
            //.withProfesionalActivo(true)
            .build();
            aPersonAccount.LastName = 'Test';
            aPersonAccount.RecordTypeId = recordTypeProfesional;
            insert aPersonAccount;
            
            Account profesional = Build.aPersonalAccount()
            .withFirstName('Profesional2')
            //.withLastName('Test')
            //.withProfesionalActivo(true)
            .build();
            profesional.LastName = 'Test2';
            profesional.RecordTypeId = recordTypeProfesional;
            insert profesional;
            Account profesional3 = Build.aPersonalAccount()
            .withFirstName('Profesional3')
            //.withLastName('Test')
            //.withProfesionalActivo(true)
            .build();
            profesional3.LastName = 'Test3';
            profesional3.RecordTypeId = recordTypeProfesional;
            insert profesional3;
        
            Dan360_Efectividad__c efectividad = Build.aDan360Efectividad()
            .withVisMedAPM(apm)
            .withVisMedCiclo(ciclo)
            .build();
            efectividad.Fecha_de_Fin__c = Date.today().toStartOfMonth();
            efectividad.Fecha_de_inicio__c = Date.today().toStartOfMonth().addMonths(1).addDays(-1);
            insert efectividad;
            Dan360_Efectividad__c efectividadSemaforo = Build.aDan360Efectividad()
            .withVisMedAPM(apmSemaforo)
            .withVisMedCiclo(ciclo)
            .build();
            efectividadSemaforo.Fecha_de_Fin__c = Date.today().toStartOfMonth();
            efectividadSemaforo.Fecha_de_inicio__c = Date.today().toStartOfMonth().addMonths(1).addDays(-1);
            insert efectividadSemaforo;

            VisMed_Contacto_Cuenta_Usuario__c seg = Build.aVisMedContactCuentaUsuarioBuilder()
                .withAPM(apm)
                .withInstitucion(institucion)
                .withProfesional(profesional)                
                .build();
            seg.Predeterminada__c = true;            
            seg.Estado__c = 'Activo';
            insert seg;
            VisMed_Contacto_Cuenta_Usuario__c seg2 = Build.aVisMedContactCuentaUsuarioBuilder()
                .withAPM(apm)
                .withInstitucion(institucion2)
                .withProfesional(profesional)                
                .build();
            seg2.Estado_de_aprobacion__c = 'Aprobada';
            seg2.Estado__c = 'Activo';
            seg2.Predeterminada__c = false;
            insert seg2;
            VisMed_Contacto_Cuenta_Usuario__c seg3 = Build.aVisMedContactCuentaUsuarioBuilder()
                .withAPM(apm)
                .withInstitucion(institucion3)
                .withProfesional(profesional)                
                .build();            
            seg3.Estado__c = 'Pendiente';
            seg3.Predeterminada__c = false;
            insert seg3;

            VisMed_Contacto_Cuenta_Usuario__c ficheroFrecuenciaEntera = Build.aVisMedContactCuentaUsuarioBuilder()
            .withAPM(apmSemaforo)
            .withInstitucion(institucion)
            .withProfesional(profesional3)                
            .build();
            ficheroFrecuenciaEntera.Estado_de_aprobacion__c = 'Aprobada';
            ficheroFrecuenciaEntera.Estado__c = 'Activo';
            ficheroFrecuenciaEntera.Predeterminada__c = true;            
            ficheroFrecuenciaEntera.Frecuencia__c = 2.0;
            ficheroFrecuenciaEntera.Inicio_de_Frecuencia__c = Date.today().toStartOfMonth();
            ficheroFrecuenciaEntera.Fin_de_Frecuencia__c = Date.today().toStartOfMonth().addMonths(1).addDays(-1);
            insert ficheroFrecuenciaEntera;

            VisMed_Contacto_Cuenta_Usuario__c ficheroFrecuenciaDecimalMenorAUno = Build.aVisMedContactCuentaUsuarioBuilder()
            .withAPM(apmSemaforo)
            .withInstitucion(institucion2)
            .withProfesional(profesional3)                
            .build();
            ficheroFrecuenciaDecimalMenorAUno.Estado_de_aprobacion__c = 'Aprobada';
            ficheroFrecuenciaDecimalMenorAUno.Estado__c = 'Activo';
            ficheroFrecuenciaDecimalMenorAUno.Predeterminada__c = true;
            ficheroFrecuenciaDecimalMenorAUno.Frecuencia__c = 0.5;
            ficheroFrecuenciaDecimalMenorAUno.Inicio_de_Frecuencia__c = Date.today().toStartOfMonth();
            ficheroFrecuenciaDecimalMenorAUno.Fin_de_Frecuencia__c = Date.today().toStartOfMonth().addMonths(2).addDays(-1);
            insert ficheroFrecuenciaDecimalMenorAUno;

            VisMed_Contacto_Cuenta_Usuario__c ficheroFrecuenciaDecimalMayorAUno = Build.aVisMedContactCuentaUsuarioBuilder()
            .withAPM(apmSemaforo)
            .withInstitucion(institucion3)
            .withProfesional(profesional)                
            .build();
            ficheroFrecuenciaDecimalMayorAUno.Estado_de_aprobacion__c = 'Aprobada';
            ficheroFrecuenciaDecimalMayorAUno.Estado__c = 'Activo';
            ficheroFrecuenciaDecimalMayorAUno.Predeterminada__c = true;
            ficheroFrecuenciaDecimalMayorAUno.Aun_Quedan_Meses__c = true;
            ficheroFrecuenciaDecimalMayorAUno.Frecuencia__c = 1.5;            
            ficheroFrecuenciaDecimalMayorAUno.Inicio_de_Frecuencia__c = Date.today().toStartOfMonth().addMonths(-1);
            ficheroFrecuenciaDecimalMayorAUno.Fin_de_Frecuencia__c = Date.today().toStartOfMonth().addMonths(2).addDays(-1);
            insert ficheroFrecuenciaDecimalMayorAUno;

            // VisMed_Contacto_Cuenta_Usuario__c ficheroFrecuenciaDecimalMayorAUno2 = Build.aVisMedContactCuentaUsuarioBuilder()
            // .withAPM(apmSemaforo)
            // .withInstitucion(institucion3)
            // .withProfesional(profesional3)                
            // .build();
            // ficheroFrecuenciaDecimalMayorAUno2.Estado_de_aprobacion__c = 'Aprobada';
            // ficheroFrecuenciaDecimalMayorAUno2.Estado__c = 'Activo';
            // ficheroFrecuenciaDecimalMayorAUno2.Predeterminada__c = true;
            // ficheroFrecuenciaDecimalMayorAUno2.Aun_Quedan_Meses__c = true;
            // ficheroFrecuenciaDecimalMayorAUno2.Frecuencia__c = 1.5;            
            // ficheroFrecuenciaDecimalMayorAUno2.Inicio_de_Frecuencia__c = Date.today().toStartOfMonth().addMonths(-1);
            // ficheroFrecuenciaDecimalMayorAUno2.Fin_de_Frecuencia__c = Date.today().toStartOfMonth().addMonths(1).addDays(-1);
            // insert ficheroFrecuenciaDecimalMayorAUno2;

            // Id recordTypeVisitaMedica = Schema.SObjectType.Dan360_Interacciones__c.getRecordTypeInfosByDeveloperName().get('Visita_Medica').getRecordTypeId();
            // List<Dan360_Interacciones__c> visitas = new List<Dan360_Interacciones__c>();
            // Dan360_Interacciones__c visita = Build.aDan360Interacciones()
            // .withProfesional(profesional3)
            // .withAPM(apmSemaforo)
            // .withVisMedTipodeVisita('Presencial')
            // .withVisMedEfectividad(efectividad)
            // .withDomiciliodelaVisita(institucion3)
            // .withVisMedFecha(Date.today().addMonths(-1))
            // .build();
            // visita.Estado__c = 'Aprobada';
            // visita.RecordTypeId = recordTypeVisitaMedica;
            // visitas.add(visita);

            // Dan360_Interacciones__c visita2 = Build.aDan360Interacciones()
            // .withProfesional(profesional)
            // .withAPM(apm)
            // .withVisMedTipodeVisita('Presencial')
            // .withVisMedEfectividad(efectividad)
            // .withDomiciliodelaVisita(institucion)
            // .withVisMedFecha(Date.today().addMonths(-1))
            // .build();
            // visita2.Estado__c = 'Aprobada';
            // visita2.RecordTypeId = recordTypeVisitaMedica;
            // visitas.add(visita2);

            // insert visitas;

            VisMed_Contacto_Cuenta_Usuario__c ficheroFrecuenciaEnteraInactivo = Build.aVisMedContactCuentaUsuarioBuilder()
            .withAPM(apmSemaforo)
            .withInstitucion(institucion)
            .withProfesional(aPersonAccount)                
            .build();
            ficheroFrecuenciaEnteraInactivo.Estado_de_aprobacion__c = 'Aprobada';
            ficheroFrecuenciaEnteraInactivo.Estado__c = 'Inactivo';
            ficheroFrecuenciaEnteraInactivo.Predeterminada__c = false;
            ficheroFrecuenciaEnteraInactivo.Frecuencia__c = 2.0;
            ficheroFrecuenciaEnteraInactivo.Inicio_de_Frecuencia__c = Date.today().toStartOfMonth();
            ficheroFrecuenciaEnteraInactivo.Fin_de_Frecuencia__c = Date.today().toStartOfMonth().addMonths(1).addDays(-1);
            insert ficheroFrecuenciaEnteraInactivo;

        }
    }

    @isTest
    public static void cuandoUnFicheroSeVuelveAActivarDesdeAppSeBlanqueaCampos(){
        VisMed_Contacto_Cuenta_Usuario__c ficheroInactivo = [SELECT id, Frecuencia__c,Categoria__c,Aun_Quedan_Meses__c ,
                                                                    Inicio_de_Frecuencia__c,Fin_de_Frecuencia__c , Visitas_Realizadas__c 
                                                            FROM VisMed_Contacto_Cuenta_Usuario__c
                                                            WHERE Estado__c = 'Inactivo'];
        System.debug(ficheroInactivo);

        ficheroInactivo.Estado__c = 'Pendiente';
        ficheroInactivo.Actualizar_Frecuencia__c = true;
        ficheroInactivo.Segmenta_Por__c = 'Epilepsia';

        Test.startTest();
            update ficheroInactivo;
        Test.stopTest();

        VisMed_Contacto_Cuenta_Usuario__c ficheroPendiente = [SELECT id, Frecuencia__c,Categoria__c,Aun_Quedan_Meses__c ,
                                                                    Inicio_de_Frecuencia__c,Fin_de_Frecuencia__c , Visitas_Realizadas__c 
                                                            FROM VisMed_Contacto_Cuenta_Usuario__c
                                                            WHERE id = :ficheroInactivo.id];
        
        System.assertEquals(null, ficheroPendiente.Frecuencia__c, 'No se blanqueo correctamente');
        System.assertEquals(false, ficheroPendiente.Aun_Quedan_Meses__c, 'No se blanqueo correctamente');
        System.assertEquals(null, ficheroPendiente.Categoria__c, 'No se blanqueo correctamente');
        System.assertEquals(null, ficheroPendiente.Inicio_de_Frecuencia__c, 'No se blanqueo correctamente');
        System.assertEquals(null, ficheroPendiente.Fin_de_Frecuencia__c, 'No se blanqueo correctamente');
        System.assertEquals(0, ficheroPendiente.Visitas_Realizadas__c, 'No se blanqueo correctamente');
    }
    @IsTest
    public static void cuandoApmCargaVisitaYEsMayorIgualALaFrecuenciaEnteraSemaforoDebeSerVerde(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222444'
            ];
            Account profesional =[
                SELECT Id
                FROM Account
                WHERE FirstName = 'Profesional3' AND LastName = 'Test3'
            ];
            Account institucion = [
                SELECT Id
                FROM Account
                WHERE Name = 'InstitucionTest'
            ];            
            Dan360_Efectividad__c efectividad = [
                SELECT Id
                FROM Dan360_Efectividad__c
                WHERE VisMed_APM__c = :apm.Id
            ]; 

            VisMed_Contacto_Cuenta_Usuario__c fichero = [
                SELECT Id, VisMed_Semaforo__c, Aun_Quedan_Meses__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE VisMed_APM__c = :apm.Id
                AND Profesional__c = : profesional.Id
                AND Institucion__c = : institucion.Id           
            ];           
            System.debug('fichero '+fichero);
            Id recordTypeVisitaMedica = Schema.SObjectType.Dan360_Interacciones__c.getRecordTypeInfosByDeveloperName().get('Visita_Medica').getRecordTypeId();           
            List<Dan360_Interacciones__c> visitas = new List<Dan360_Interacciones__c>();
            Dan360_Interacciones__c visita = Build.aDan360Interacciones()
            .withProfesional(profesional)
            .withAPM(apm)
            .withVisMedTipodeVisita('Presencial')
            .withVisMedEfectividad(efectividad)
            .withDomiciliodelaVisita(institucion)
            .withVisMedFecha(Date.today())
            .build();
            visita.Estado__c = 'Aprobada';
            visita.RecordTypeId = recordTypeVisitaMedica;
            visitas.add(visita);
            Dan360_Interacciones__c visita2 = Build.aDan360Interacciones()
            .withProfesional(profesional)
            .withAPM(apm)
            .withVisMedTipodeVisita('Presencial')
            .withVisMedEfectividad(efectividad)
            .withDomiciliodelaVisita(institucion)
            .withVisMedFecha(Date.today())
            .build();
            visita2.Estado__c = 'Aprobada';
            visita2.RecordTypeId = recordTypeVisitaMedica;
            visitas.add(visita2);

            Test.startTest();
            insert visitas;            
            Test.stopTest();

            VisMed_Contacto_Cuenta_Usuario__c segToCompare = [
                SELECT Id, VisMed_Semaforo__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE VisMed_APM__c = :apm.Id
                AND Profesional__c = : profesional.Id
                AND Institucion__c = : institucion.Id                
            ];            

            System.assertEquals('Verde', segToCompare.VisMed_Semaforo__c, 'Error al cambiar semaforo');
        }
        
    }
    @IsTest
    public static void cuandoApmCargaVisitaYEsMenorAlTotalFrecuenciaSemaforoDebeSerAmarillo(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222444'
            ];
            
            Account institucion = [
                SELECT Id
                FROM Account
                WHERE Name = 'InstitucionTest3'
            ];            
            Dan360_Efectividad__c efectividad = [
                SELECT Id
                FROM Dan360_Efectividad__c
                WHERE VisMed_APM__c = :apm.Id
            ]; 

            VisMed_Contacto_Cuenta_Usuario__c fichero = [
                SELECT Id, VisMed_Semaforo__c,Profesional__c, VisMed_APM__c, Aun_Quedan_Meses__c, Inicio_de_Frecuencia__c, Fin_de_Frecuencia__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE VisMed_APM__c = :apm.Id
                AND Frecuencia__c = 1.5
                        
            ];
            fichero.Aun_Quedan_Meses__c = false;
            fichero.Inicio_de_Frecuencia__c = Date.today().addMonths(-1).toStartOfMonth();     
            fichero.Fin_de_Frecuencia__c = Date.today().toStartOfMonth().addMonths(1).addDays(-1);
            update fichero; 
            Account profesional =[
                SELECT Id
                FROM Account
                WHERE Id = :fichero.Profesional__c
            ];    
            System.debug('fichero '+fichero);
            Id recordTypeVisitaMedica = Schema.SObjectType.Dan360_Interacciones__c.getRecordTypeInfosByDeveloperName().get('Visita_Medica').getRecordTypeId();           
            List<Dan360_Interacciones__c> visitas = new List<Dan360_Interacciones__c>();
            Dan360_Interacciones__c visita = Build.aDan360Interacciones()
            .withProfesional(profesional)
            .withAPM(apm)
            .withVisMedTipodeVisita('Presencial')
            .withVisMedEfectividad(efectividad)
            .withDomiciliodelaVisita(institucion)
            .withVisMedFecha(Date.today().addDays(1))
            .build();
            visita.Estado__c = 'Aprobada';
            visita.RecordTypeId = recordTypeVisitaMedica;
            visitas.add(visita);
            Dan360_Interacciones__c visita2 = Build.aDan360Interacciones()
            .withProfesional(profesional)
            .withAPM(apm)
            .withVisMedTipodeVisita('Presencial')
            .withVisMedEfectividad(efectividad)
            .withDomiciliodelaVisita(institucion)
            .withVisMedFecha(Date.today())
            .build();
            visita2.Estado__c = 'Aprobada';
            visita2.RecordTypeId = recordTypeVisitaMedica;
            visitas.add(visita2);

            Test.startTest();
            insert visitas;            
            Test.stopTest();

            VisMed_Contacto_Cuenta_Usuario__c segToCompare = [
                SELECT Id, VisMed_Semaforo__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE VisMed_APM__c = :apm.Id
                AND Profesional__c = : profesional.Id
                AND Institucion__c = : institucion.Id                
            ];            

            System.assertEquals('Amarillo', segToCompare.VisMed_Semaforo__c, 'Error al cambiar semaforo');
        }
        
    }
    @IsTest
    public static void cuandoApmCargaVisitaYEsMenorALaFrecuenciaEnteraSemaforoDebeSerAmarillo(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222444'
            ];
            Account profesional =[
                SELECT Id
                FROM Account
                WHERE FirstName = 'Profesional3' AND LastName = 'Test3'
            ];
            Account institucion = [
                SELECT Id
                FROM Account
                WHERE Name = 'InstitucionTest'
            ];            
            Dan360_Efectividad__c efectividad = [
                SELECT Id
                FROM Dan360_Efectividad__c
                WHERE VisMed_APM__c = :apm.Id
            ]; 

            VisMed_Contacto_Cuenta_Usuario__c fichero = [
                SELECT Id, VisMed_Semaforo__c, Aun_Quedan_Meses__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE VisMed_APM__c = :apm.Id
                AND Profesional__c = : profesional.Id
                AND Institucion__c = : institucion.Id           
            ];           
            System.debug('fichero '+fichero);
            Id recordTypeVisitaMedica = Schema.SObjectType.Dan360_Interacciones__c.getRecordTypeInfosByDeveloperName().get('Visita_Medica').getRecordTypeId();           
            List<Dan360_Interacciones__c> visitas = new List<Dan360_Interacciones__c>();
            Dan360_Interacciones__c visita = Build.aDan360Interacciones()
            .withProfesional(profesional)
            .withAPM(apm)
            .withVisMedTipodeVisita('Presencial')
            .withVisMedEfectividad(efectividad)
            .withDomiciliodelaVisita(institucion)
            .withVisMedFecha(Date.today())
            .build();
            visita.Estado__c = 'Aprobada';
            visita.RecordTypeId = recordTypeVisitaMedica;
            visitas.add(visita);            

            Test.startTest();
            insert visitas;            
            Test.stopTest();

            VisMed_Contacto_Cuenta_Usuario__c segToCompare = [
                SELECT Id, VisMed_Semaforo__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE VisMed_APM__c = :apm.Id
                AND Profesional__c = : profesional.Id
                AND Institucion__c = : institucion.Id                
            ];            

            System.assertEquals('Amarillo', segToCompare.VisMed_Semaforo__c, 'Error al cambiar semaforo');
        }
        
    }
    @IsTest
    public static void cuandoApmCargaVisitaSeEliminaYVisitaVuelveACeroElSemaforoDebeVolverARojo(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222444'
            ];
            Account profesional =[
                SELECT Id
                FROM Account
                WHERE FirstName = 'Profesional3' AND LastName = 'Test3'
            ];
            Account institucion = [
                SELECT Id
                FROM Account
                WHERE Name = 'InstitucionTest'
            ];            
            Dan360_Efectividad__c efectividad = [
                SELECT Id
                FROM Dan360_Efectividad__c
                WHERE VisMed_APM__c = :apm.Id
            ]; 
            
            Id recordTypeVisitaMedica = Schema.SObjectType.Dan360_Interacciones__c.getRecordTypeInfosByDeveloperName().get('Visita_Medica').getRecordTypeId();           
            List<Dan360_Interacciones__c> visitas = new List<Dan360_Interacciones__c>();
            Dan360_Interacciones__c visita = Build.aDan360Interacciones()
            .withProfesional(profesional)
            .withAPM(apm)
            .withVisMedTipodeVisita('Presencial')
            .withVisMedEfectividad(efectividad)
            .withDomiciliodelaVisita(institucion)
            .withVisMedFecha(Date.today())
            .build();
            visita.Estado__c = 'Aprobada';
            visita.RecordTypeId = recordTypeVisitaMedica;
            visitas.add(visita);            
            insert visitas;  
            VisMed_Contacto_Cuenta_Usuario__c segToCompare = [
                SELECT Id, VisMed_Semaforo__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE VisMed_APM__c = :apm.Id
                AND Profesional__c = : profesional.Id
                AND Institucion__c = : institucion.Id                
            ];          
            System.assertEquals('Amarillo', segToCompare.VisMed_Semaforo__c, 'Error al cambiar semaforo a amarillo');
            Test.startTest();
            delete visita;
            Test.stopTest();

            VisMed_Contacto_Cuenta_Usuario__c segToCompare2 = [
                SELECT Id, VisMed_Semaforo__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE VisMed_APM__c = :apm.Id
                AND Profesional__c = : profesional.Id
                AND Institucion__c = : institucion.Id                
            ];            

            System.assertEquals('Rojo', segToCompare2.VisMed_Semaforo__c, 'Error al cambiar semaforo a rojo');
        }
        
    }
    @IsTest
    public static void cuandoApmCargaVisitaElSegundoMesYEsMayorIgualALaFrecuenciaDecimalMayorAUnoSemaforoDebeSerAmarillo(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222444'
            ];
            Account profesional =[
                SELECT Id
                FROM Account
                WHERE FirstName = 'Profesional2' AND LastName = 'Test2'
            ];
            Account institucion = [
                SELECT Id
                FROM Account
                WHERE Name = 'InstitucionTest3'
            ];            
            Dan360_Efectividad__c efectividad = [
                SELECT Id
                FROM Dan360_Efectividad__c
                WHERE VisMed_APM__c = :apm.Id
            ]; 
            Id recordTypeVisitaMedica = Schema.SObjectType.Dan360_Interacciones__c.getRecordTypeInfosByDeveloperName().get('Visita_Medica').getRecordTypeId();           
            List<Dan360_Interacciones__c> visitas = new List<Dan360_Interacciones__c>();
            Dan360_Interacciones__c visita = Build.aDan360Interacciones()
            .withProfesional(profesional)
            .withAPM(apm)
            .withVisMedTipodeVisita('Presencial')
            .withVisMedEfectividad(efectividad)
            .withDomiciliodelaVisita(institucion)
            .withVisMedFecha(Date.today())
            .build();
            visita.Estado__c = 'Aprobada';
            visita.RecordTypeId = recordTypeVisitaMedica;
            visitas.add(visita);
            Dan360_Interacciones__c visita2 = Build.aDan360Interacciones()
            .withProfesional(profesional)
            .withAPM(apm)
            .withVisMedTipodeVisita('Presencial')
            .withVisMedEfectividad(efectividad)
            .withDomiciliodelaVisita(institucion)
            .withVisMedFecha(Date.today().addMonths(1).addDays(-2))
            .build();
            visita2.Estado__c = 'Aprobada';
            visita2.RecordTypeId = recordTypeVisitaMedica;
            visitas.add(visita2);

            Test.startTest();
            insert visitas;            
            Test.stopTest();

            VisMed_Contacto_Cuenta_Usuario__c segToCompare = [
                SELECT Id, VisMed_Semaforo__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE VisMed_APM__c = :apm.Id
                AND Profesional__c = : profesional.Id
                AND Institucion__c = : institucion.Id
            ];            

            System.assertEquals('Amarillo', segToCompare.VisMed_Semaforo__c, 'Error al cambiar semaforo');
        }
        
    }	
    @IsTest
    public static void cuandoApmCargaVisitaElPrimerMesYEsMayorIgualALaFrecuenciaDecimalMayorAUnoSemaforoDebeSerAmarillo(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222444'
            ];
            Account profesional =[
                SELECT Id
                FROM Account
                WHERE FirstName = 'Profesional2' AND LastName = 'Test2'
            ];
            Account institucion = [
                SELECT Id
                FROM Account
                WHERE Name = 'InstitucionTest3'
            ];            
            Dan360_Efectividad__c efectividad = [
                SELECT Id
                FROM Dan360_Efectividad__c
                WHERE VisMed_APM__c = :apm.Id
            ]; 
            VisMed_Contacto_Cuenta_Usuario__c fichero = [
                SELECT Id, VisMed_Semaforo__c, Aun_Quedan_Meses__c,Inicio_de_Frecuencia__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE VisMed_APM__c = :apm.Id
                AND Profesional__c = : profesional.Id
                AND Institucion__c = : institucion.Id           
            ];           
            fichero.Inicio_de_Frecuencia__c = Date.today().toStartOfMonth();
            update fichero;
            
            Id recordTypeVisitaMedica = Schema.SObjectType.Dan360_Interacciones__c.getRecordTypeInfosByDeveloperName().get('Visita_Medica').getRecordTypeId();           
            List<Dan360_Interacciones__c> visitas = new List<Dan360_Interacciones__c>();
            Dan360_Interacciones__c visita = Build.aDan360Interacciones()
            .withProfesional(profesional)
            .withAPM(apm)
            .withVisMedTipodeVisita('Presencial')
            .withVisMedEfectividad(efectividad)
            .withDomiciliodelaVisita(institucion)
            .withVisMedFecha(Date.today())
            .build();
            visita.Estado__c = 'Aprobada';
            visita.RecordTypeId = recordTypeVisitaMedica;
            visitas.add(visita);
            Dan360_Interacciones__c visita2 = Build.aDan360Interacciones()
            .withProfesional(profesional)
            .withAPM(apm)
            .withVisMedTipodeVisita('Presencial')
            .withVisMedEfectividad(efectividad)
            .withDomiciliodelaVisita(institucion)
            .withVisMedFecha(Date.today().addMonths(1).addDays(-2))
            .build();
            visita2.Estado__c = 'Aprobada';
            visita2.RecordTypeId = recordTypeVisitaMedica;
            visitas.add(visita2);

            Test.startTest();
            insert visitas;            
            Test.stopTest();

            VisMed_Contacto_Cuenta_Usuario__c segToCompare = [
                SELECT Id, VisMed_Semaforo__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE VisMed_APM__c = :apm.Id
                AND Profesional__c = : profesional.Id
                AND Institucion__c = : institucion.Id
            ];            

            System.assertEquals('Amarillo', segToCompare.VisMed_Semaforo__c, 'Error al cambiar semaforo');
        }
        
    }	
    //@IsTest
    public static void cuandoApmCargaVisitaEnElUtimoMesYEsMayorIgualAlTotalDeFrecuenciaDecimalMayorAUnoSemaforoDebeSerVerde(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222444'
            ];
            Account profesional =[
                SELECT Id
                FROM Account
                WHERE FirstName = 'Profesional3' AND LastName = 'Test3'
            ];
            Account institucion = [
                SELECT Id
                FROM Account
                WHERE Name = 'InstitucionTest3'
            ];            
            Dan360_Efectividad__c efectividad = [
                SELECT Id
                FROM Dan360_Efectividad__c
                WHERE VisMed_APM__c = :apm.Id
            ]; 

            Id recordTypeVisitaMedica = Schema.SObjectType.Dan360_Interacciones__c.getRecordTypeInfosByDeveloperName().get('Visita_Medica').getRecordTypeId();           
            List<Dan360_Interacciones__c> visitas = new List<Dan360_Interacciones__c>();
            // Dan360_Interacciones__c visita = Build.aDan360Interacciones()
            // .withProfesional(profesional)
            // .withAPM(apm)
            // .withVisMedTipodeVisita('Presencial')
            // .withVisMedEfectividad(efectividad)
            // .withDomiciliodelaVisita(institucion)
            // .withVisMedFecha(Date.today().addMonths(-1))
            // .build();
            // visita.Estado__c = 'Aprobada';
            // visita.RecordTypeId = recordTypeVisitaMedica;
            // visitas.add(visita);

            Dan360_Interacciones__c visita2 = Build.aDan360Interacciones()
            .withProfesional(profesional)
            .withAPM(apm)
            .withVisMedTipodeVisita('Presencial')
            .withVisMedEfectividad(efectividad)
            .withDomiciliodelaVisita(institucion)
            .withVisMedFecha(Date.today())
            .build();
            visita2.Estado__c = 'Aprobada';
            visita2.RecordTypeId = recordTypeVisitaMedica;
            visitas.add(visita2);
            
            VisMed_Contacto_Cuenta_Usuario__c fichero = [
                SELECT Id, VisMed_Semaforo__c,Visitas_acumuladas__c, Aun_Quedan_Meses__c,Inicio_de_Frecuencia__c, Fin_de_Frecuencia__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE VisMed_APM__c = :apm.Id
                AND Profesional__c = : profesional.Id
                AND Institucion__c = : institucion.Id           
            ];         
            
            fichero.Aun_Quedan_Meses__c = false;
            fichero.Visitas_acumuladas__c = 2;
            update fichero;

            
            Dan360_Interacciones__c visita3 = Build.aDan360Interacciones()
            .withProfesional(profesional)
            .withAPM(apm)
            .withVisMedTipodeVisita('Presencial')
            .withVisMedEfectividad(efectividad)
            .withDomiciliodelaVisita(institucion)
            .withVisMedFecha(Date.today())
            .build();
            visita3.Estado__c = 'Aprobada';
            visita3.RecordTypeId = recordTypeVisitaMedica;            
            visitas.add(visita3);
            
            Test.startTest();
            insert visitas; 
            Test.stopTest();
            
            VisMed_Contacto_Cuenta_Usuario__c segToCompare = [
                SELECT Id, VisMed_Semaforo__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE VisMed_APM__c = :apm.Id
                AND Profesional__c = : profesional.Id
                AND Institucion__c = : institucion.Id
            ];            

            System.assertEquals('Amarillo', segToCompare.VisMed_Semaforo__c, 'Error al cambiar semaforo');
        }
        
    }	
    @IsTest
    public static void cuandoApmCargaVisitaYEsMayorIgualALaFrecuenciaDecimalMenorAUnoSemaforoDebeSerVerde(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222444'
            ];
            Account profesional =[
                SELECT Id
                FROM Account
                WHERE FirstName = 'Profesional3' AND LastName = 'Test3'
            ];
            Account institucion = [
                SELECT Id
                FROM Account
                WHERE Name = 'InstitucionTest2'
            ];            
            Dan360_Efectividad__c efectividad = [
                SELECT Id
                FROM Dan360_Efectividad__c
                WHERE VisMed_APM__c = :apm.Id
            ]; 
            Id recordTypeVisitaMedica = Schema.SObjectType.Dan360_Interacciones__c.getRecordTypeInfosByDeveloperName().get('Visita_Medica').getRecordTypeId();           
            List<Dan360_Interacciones__c> visitas = new List<Dan360_Interacciones__c>();
            Dan360_Interacciones__c visita = Build.aDan360Interacciones()
            .withProfesional(profesional)
            .withAPM(apm)
            .withVisMedTipodeVisita('Presencial')
            .withVisMedEfectividad(efectividad)
            .withDomiciliodelaVisita(institucion)
            .withVisMedFecha(Date.today())
            .build();
            visita.Estado__c = 'Aprobada';
            visita.RecordTypeId = recordTypeVisitaMedica;

            visitas.add(visita);

            Dan360_Interacciones__c visita2 = Build.aDan360Interacciones()
            .withProfesional(profesional)
            .withAPM(apm)
            .withVisMedTipodeVisita('Presencial')
            .withVisMedEfectividad(efectividad)
            .withDomiciliodelaVisita(institucion)
            .withVisMedFecha(Date.today())
            .build();
            visita2.Estado__c = 'Aprobada';
            visita2.RecordTypeId = recordTypeVisitaMedica;

            visitas.add(visita2);

            Test.startTest();
            insert visitas;            
            Test.stopTest();

            VisMed_Contacto_Cuenta_Usuario__c segToCompare = [
                SELECT Id, VisMed_Semaforo__c, Visitas_Realizadas__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE VisMed_APM__c = :apm.Id
                AND Profesional__c = : profesional.Id
                AND Institucion__c = : institucion.Id
            ];            

            System.assertEquals('Verde', segToCompare.VisMed_Semaforo__c, 'Error al cambiar semaforo');
            System.assertEquals(2, segToCompare.Visitas_Realizadas__c, 'Error al cambiar Visita');
        }
        
    }	
    @IsTest
    public static void cuandoSeCreaSeguimientoSeDebeAsignarAlAPMCorrespondiente(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222333'
            ];
            Account profesional =[
                SELECT Id
                FROM Account
                WHERE FirstName = 'Profesional' AND LastName = 'Test'
            ];
            Account institucion = [
                SELECT Id
                FROM Account
                WHERE Name = 'InstitucionTest'
            ];            

            VisMed_Contacto_Cuenta_Usuario__c seg = Build.aVisMedContactCuentaUsuarioBuilder()
                .withAPM(apm)
                .withInstitucion(institucion)
                .withProfesional(profesional)
                .build();
            Test.startTest();
            insert seg;
            Test.stopTest();

            VisMed_Contacto_Cuenta_Usuario__c segToCompare = [
                SELECT Id, OwnerId
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE Id = :seg.Id
            ];

            User userApm = [
            SELECT Id
            FROM User
            WHERE Alias = 'contact1'
        ];

            System.assertEquals(userApm.Id, segToCompare.OwnerId, 'Error al asignar seguimiento al APM');
        }
        
    }	
    @IsTest
    public static void cuandoSeCreaSeguimientoSeDebeActivarElProfesional(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222333'
            ];
            Account profesional =[
                SELECT Id, Profesional_Activo__c
                FROM Account
                WHERE FirstName = 'Profesional' AND LastName = 'Test'
            ];
            Account institucion = [
                SELECT Id
                FROM Account
                WHERE Name = 'InstitucionTest'
            ];            

            VisMed_Contacto_Cuenta_Usuario__c seg = Build.aVisMedContactCuentaUsuarioBuilder()
                .withAPM(apm)
                .withInstitucion(institucion)
                .withProfesional(profesional)
                .build();
            Test.startTest();
            insert seg;
            Test.stopTest();

            Account profesionalToCompare =[
                SELECT Id, Profesional_Activo__c
                FROM Account
                WHERE FirstName = 'Profesional' AND LastName = 'Test'
            ];
            
            System.assertEquals(true, profesionalToCompare.Profesional_Activo__c, 'Error al activar el  profesional');            
        }        
    }	
    @IsTest
    public static void cuandoSeCreaSeguimientoSeDebeAccountTeamMember(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222333'
            ];
            Account profesional =[
                SELECT Id, Profesional_Activo__c
                FROM Account
                WHERE FirstName = 'Profesional' AND LastName = 'Test'
            ];
            Account institucion = [
                SELECT Id
                FROM Account
                WHERE Name = 'InstitucionTest'
            ];            

            VisMed_Contacto_Cuenta_Usuario__c seg = Build.aVisMedContactCuentaUsuarioBuilder()
                .withAPM(apm)
                .withInstitucion(institucion)
                .withProfesional(profesional)
                .build();
            seg.Estado__c = 'Activo';
            Test.startTest();
            insert seg;
            Test.stopTest();

            User userApm = [
                SELECT Id
                FROM User
                WHERE Alias = 'contact1'
            ];

            List<AccountTeamMember> atmToCompare =[
                SELECT Id
                FROM AccountTeamMember
                WHERE UserId = :userApm.Id
            ];
            
            System.assertEquals(4, atmToCompare.size() , 'Error al crear account team Member');            
        }        
    }	
    @IsTest
    public static void cuandoSeCreaSeguimientoConSegmentaSeDebeSetearFrecuencia(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222333'
            ];
            Account profesional =[
                SELECT Id, Profesional_Activo__c
                FROM Account
                WHERE FirstName = 'Profesional' AND LastName = 'Test'
            ];
            Account institucion = [
                SELECT Id
                FROM Account
                WHERE Name = 'InstitucionTest'
            ];            

            VisMed_Contacto_Cuenta_Usuario__c seg = Build.aVisMedContactCuentaUsuarioBuilder()
                .withAPM(apm)
                .withInstitucion(institucion)
                .withProfesional(profesional)
                .withSegmentaPor('Pediatricos General')               
                .build();
            seg.Predeterminada__c = true;            
            seg.Estado__c = 'Activo';  
             
            Test.startTest();
            insert seg;
            Test.stopTest();

            

            List<VisMed_Contacto_Cuenta_Usuario__c> ficherosToCompare = [
            SELECT ID, Segmenta_Por__c, Frecuencia__c, Categoria__c, Fecha_de_Aprobacion__c
            FROM VisMed_Contacto_Cuenta_Usuario__c
            WHERE id = :seg.Id
            ];
        System.debug(ficherosToCompare);
        // Asserts
        System.assertEquals(0.5, ficherosToCompare[0].Frecuencia__c, 'Error al  obtener frecuencia');
        System.assertEquals('D', ficherosToCompare[0].Categoria__c, 'Error al  obtener categoria');            
        }        
    }	
    @IsTest
    public static void cuandoApruebaAltaDeProfesionalSeDebeCrearLaSegmentacionDelProfesionalSiNoExiste(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222333'
            ];

            Account profesional =[
                SELECT Id
                FROM Account
                WHERE FirstName = 'Profesional2' AND LastName = 'Test2'
            ];
            
            VisMed_Contacto_Cuenta_Usuario__c seg = [
                SELECT Id, Estado_de_aprobacion__c, Profesional__c, Segmenta_Por__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE Profesional__c = :profesional.Id AND Predeterminada__c = true
                AND VisMed_APM__c = : apm.Id
            ];
            seg.Estado_de_aprobacion__c = 'Aprobada';
            seg.Segmenta_Por__c = 'Alergia';
            Test.startTest();
            update seg;
            Test.stopTest();

            Id tipoSegmentacion = Schema.SObjectType.VisMed_Segmentacion__c.getRecordTypeInfosByName().get(seg.Segmenta_Por__c).getRecordTypeId();
            List<VisMed_Segmentacion__c> segmentacion = [
                SELECT Id, Profesional__c, RecordType.Name
                FROM VisMed_Segmentacion__c
                WHERE Profesional__c = :seg.Profesional__c
                    AND RecordType.Name = 'Alergia'
            ];          
            
            System.assertEquals('Alergia', segmentacion[0].RecordType.Name, 'Error al crear segmentacion');            
        }        
    }

    @IsTest
    public static void cuandoSeCargaUnValorPorPrimeraVezAlCampoSegmentaPorDebeCargarLaFrecuencia(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){

            Account profesional =[
                SELECT Id
                FROM Account
                WHERE FirstName = 'Profesional2' AND LastName = 'Test2'
            ];
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222333'
            ];
            
            VisMed_Contacto_Cuenta_Usuario__c seg = [
                SELECT Id, Estado_de_aprobacion__c, Profesional__c, Segmenta_Por__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE Profesional__c = :profesional.Id AND Predeterminada__c = true
                AND VisMed_APM__c = : apm.Id
            ];
            seg.Estado_de_aprobacion__c = 'Aprobada';
            seg.Segmenta_Por__c = 'Alergia';
            Test.startTest();
            update seg;
            Test.stopTest();

            Id tipoSegmentacion = Schema.SObjectType.VisMed_Segmentacion__c.getRecordTypeInfosByName().get(seg.Segmenta_Por__c).getRecordTypeId();
            List<VisMed_Segmentacion__c> segmentacion = [
                SELECT Id, Profesional__c, RecordType.Name, Frecuencia__c, Categoria__c
                FROM VisMed_Segmentacion__c
                WHERE Profesional__c = :seg.Profesional__c
                AND RecordType.Name = 'Alergia'
            ];          
            
            System.assertEquals('Alergia', segmentacion[0].RecordType.Name, 'Error al crear segmentacion');            
            System.assertNotEquals(null, segmentacion[0].Frecuencia__c, 'Error al crear segmentacion');            
            System.assertNotEquals(null, segmentacion[0].Categoria__c, 'Error al crear segmentacion');            
        }        
    }   
   // @IsTest
    // public static void cuandoSeActulizaFicheroPrincipalPasaLosCambiosALosFicherosRelacionados(){
    //     User userOwner = [
    //         SELECT Id
    //         FROM User
    //         WHERE Alias = 'owner'
    //     ];
    //     system.runAs(userOwner){

    //         Account profesional =[
    //             SELECT Id
    //             FROM Account
    //             WHERE FirstName = 'Profesional2' AND LastName = 'Test2'
    //         ];
    //         Contact apm = [
    //             SELECT Id
    //             FROM Contact
    //             WHERE VisMed_DNI__c = '22222333'
    //         ];
            
    //         VisMed_Contacto_Cuenta_Usuario__c seg = [
    //             SELECT Id, Frecuencia__c, Fin_de_Frecuencia__c, Inicio_de_Frecuencia__c,Visitas_acumuladas__c, Segmenta_Por__c,
    //             Categoria__c, VisMed_Semaforo__c, Ultima_Visita__c, Visitas_Realizadas__c, Plan__c, VisMed_APM__c, Profesional__c
    //             FROM VisMed_Contacto_Cuenta_Usuario__c
    //             WHERE Profesional__c = :profesional.Id AND Predeterminada__c = true
    //             AND VisMed_APM__c = : apm.Id
    //             AND Predeterminada__c = true
    //         ];
    //         seg.Estado_de_aprobacion__c = 'Aprobada';
    //         seg.Segmenta_Por__c = 'Alergia';
    //         seg.Inicio_de_Frecuencia__c = Date.today().toStartOfMonth().addDays(1);
    //         seg.Fin_de_Frecuencia__c = Date.today().toStartOfMonth().addMonths(1).addDays(-1);
    //         seg.Frecuencia__c = 2;
    //         seg.Visitas_acumuladas__c = 3;
    //         seg.Categoria__c = 'B';
    //         seg.VisMed_Semaforo__c = 'Verde';
    //         seg.Ultima_Visita__c = Date.today();
    //         seg.Visitas_Realizadas__c = 2;
    //         //seg.Plan__c = 'Alergia';
    //         Test.startTest();
    //         update seg;
    //         Test.stopTest();
            
    //         List<VisMed_Contacto_Cuenta_Usuario__c> seguimientos = [
    //             SELECT Id, Frecuencia__c, Fin_de_Frecuencia__c, Inicio_de_Frecuencia__c,Visitas_acumuladas__c, Segmenta_Por__c,
    //             Categoria__c, VisMed_Semaforo__c, Ultima_Visita__c, Visitas_Realizadas__c, Plan__c, VisMed_APM__c, Profesional__c
    //             FROM VisMed_Contacto_Cuenta_Usuario__c
    //             WHERE Profesional__c = :seg.Profesional__c
    //             AND VisMed_APM__c = : apm.Id
    //             AND Predeterminada__c = false                
    //         ];          
            
    //         System.assertEquals('Alergia', seguimientos[0].Segmenta_Por__c, 'Error al sincronizar fichero');            
    //         System.assertEquals(Date.today().toStartOfMonth().addDays(1), seguimientos[0].Inicio_de_Frecuencia__c, 'Error al sincronizar fichero');            
    //         System.assertEquals(Date.today().toStartOfMonth().addMonths(1).addDays(-1), seguimientos[0].Fin_de_Frecuencia__c, 'Error al sincronizar fichero');            
    //         System.assertEquals(2, seguimientos[0].Frecuencia__c, 'Error al sincronizar fichero');            
    //         System.assertEquals(3, seguimientos[0].Visitas_acumuladas__c, 'Error al sincronizar fichero');            
    //         System.assertEquals('B', seguimientos[0].Categoria__c, 'Error al sincronizar fichero');            
    //         System.assertEquals('Verde', seguimientos[0].VisMed_Semaforo__c, 'Error al sincronizar fichero');           
    //         System.assertEquals(Date.today(), seguimientos[0].Ultima_Visita__c, 'Error al sincronizar fichero');           
    //         System.assertEquals(2, seguimientos[0].Visitas_Realizadas__c, 'Error al sincronizar fichero');           
    //         //System.assertEquals('Alergia', seguimientos[0].Plan__c, 'Error al sincronizar fichero');           
    //     }
    // }   

    @IsTest
    public static void cuandoSeCargaApruebaAltaDebeCrearNotificacion(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){

            Account profesional =[
                SELECT Id
                FROM Account
                WHERE FirstName = 'Profesional' AND LastName = 'Test'
            ];
            
            VisMed_Contacto_Cuenta_Usuario__c seg = [
                SELECT Id, Estado_de_aprobacion__c, VisMed_APM__c, Profesional__c, Segmenta_Por__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE Estado__c = 'Pendiente' AND Predeterminada__c = false
            ];
            seg.Estado_de_aprobacion__c = 'Aprobada';
            seg.Estado__c = 'Activo';
            
            Test.startTest();
            update seg;
            Test.stopTest();
            
            List<Notificacion__c> notificacion = [
                SELECT Id, Id_del_Objeto__c,APM__c
                FROM Notificacion__c
                WHERE Id_del_Objeto__c = :seg.Id                
            ];          
            
            System.assertEquals(seg.VisMed_APM__c, notificacion[0].APM__c, 'Error al crear notificacion');            
            System.assertEquals(seg.Id, notificacion[0].Id_del_Objeto__c, 'Error al crear notificacion');            
                      
        }        
    }
    
    @IsTest
    public static void testBlankFieldMotivo(){
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222333'
            ];

            Account institucion =[
                SELECT Id
                FROM Account
                WHERE Name = 'InstitucionTest2'
            ];
            Account profesional =[
                SELECT Id
                FROM Account
                WHERE FirstName = 'Profesional2' AND LastName = 'Test2'
            ];
            VisMed_Contacto_Cuenta_Usuario__c seg = [
                SELECT Id, Estado_de_aprobacion__c, Profesional__c, Predeterminada__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE Frecuencia__c = 2.0                 
                AND Estado__c = 'Inactivo'                
            ];
            
            seg.Estado__c = 'Activo';
            seg.Motivo_de_la_Baja__c = 'Bajo Potencial';
            
            Test.startTest();            
            update seg;
            Test.stopTest();
           
            List<VisMed_Contacto_Cuenta_Usuario__c> seguimientos = [
                SELECT Id, Profesional__c, Motivo_de_la_Baja__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE Id = :seg.Id                 
            ];          
            
            System.assertEquals(null, seguimientos[0].Motivo_de_la_Baja__c, 'Error al limpiar campo');            
            
        }        
    }
    @isTest
    static void soloPuedeHaberUnSoloFicheroComoPredeterminado() {
        User userOwner = [
            SELECT Id
            FROM User
            WHERE Alias = 'owner'
        ];
        system.runAs(userOwner){
            Contact apm = [
                SELECT Id
                FROM Contact
                WHERE VisMed_DNI__c = '22222333'
            ];

            Account institucion =[
                SELECT Id
                FROM Account
                WHERE Name = 'InstitucionTest2'
            ];
            Account profesional =[
                SELECT Id
                FROM Account
                WHERE FirstName = 'Profesional2' AND LastName = 'Test2'
            ];
            VisMed_Contacto_Cuenta_Usuario__c seg = [
                SELECT Id, Estado_de_aprobacion__c, Profesional__c, Predeterminada__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE Institucion__c = :institucion.Id 
                AND Profesional__c = :profesional.Id
                AND VisMed_APM__c = :apm.Id
            ];
            seg.Estado_de_aprobacion__c = 'Aprobada';
            seg.Predeterminada__c = true;
            seg.Estado__c = 'Activo';
            Test.startTest();
            update seg;
            Test.stopTest();
           
            List<VisMed_Contacto_Cuenta_Usuario__c> seguimientos = [
                SELECT Id, Profesional__c
                FROM VisMed_Contacto_Cuenta_Usuario__c
                WHERE Profesional__c = :seg.Profesional__c 
                AND Predeterminada__c = true
                AND VisMed_APM__c = : apm.Id
            ];          
            
            System.assertEquals(1, seguimientos.size(), 'Error al dejar un solo  predeterminado');            
            System.assertEquals(seg.Id, seguimientos[0].Id, 'Error al dejar un solo predeterminado');
        }
    }
}