force-app/main/default/objects/LVC_DistributionCenter__c/LVC_DistributionCenter__c.object-meta.xml
<CustomObject>
    <label>Centro De Distribución</label>
    <nameField>
        <label>Centro De Distribucion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros De Distribución</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_DistributionCenter__c/fields/CDExternalId__c.field-meta.xml
<CustomField>
    <fullName>CDExternalId__c</fullName>
    <externalId>true</externalId>
    <label>CD External Id</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/LVC_ProductStockDate__c/LVC_ProductStockDate__c.object-meta.xml
<CustomObject>
    <label>Producto en Stock Fecha</label>
    <nameField>
        <displayFormat>STOCK-{0000000000}</displayFormat>
        <label>Producto en Stock Fecha</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos en Stock Fecha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LVC_ProductStockDate__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <label>Centro De Distribución</label>
    <referenceTo>LVC_DistributionCenter__c</referenceTo>
    <relationshipLabel>Productos en Stock Fecha</relationshipLabel>
    <relationshipName>Product_Stock_Date</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LVC_ProductStockDate__c/fields/Sku__c.field-meta.xml
<CustomField>
    <fullName>Sku__c</fullName>
    <label>Sku de Producto</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LVC_ProductStockDate__c/fields/StockDate__c.field-meta.xml
<CustomField>
    <fullName>StockDate__c</fullName>
    <label>Fecha de Stock</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LVC_ProductStockDate__c/fields/StockExternalId__c.field-meta.xml
<CustomField>
    <fullName>StockExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Stock External Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/LVC_ProductStockDateTriggerHandler.cls
public with sharing class LVC_ProductStockDateTriggerHandler {

    public static void completeStockExternalId(){
        
        List<LVC_ProductStockDate__c> stockToUpdate = new List<LVC_ProductStockDate__c>(); 
        List<LVC_ProductStockDate__c> newProducts = [SELECT Id, DistributionCenter__r.CDExternalId__c, Sku__c, StockDate__c 
                                                     FROM LVC_ProductStockDate__c
                                                     WHERE Id =: Trigger.newMap.keySet()];
        if(newProducts.size() > 0){
            for(LVC_ProductStockDate__c psd : newProducts){
                // String decomposedDate = String.valueOf(psd.StockDate__c.year()) + String.valueOf(psd.StockDate__c.month()) + String.valueOf(psd.StockDate__c.day());
                String decomposedDate = DateTime.newInstance(psd.StockDate__c.year(), psd.StockDate__c.month(), psd.StockDate__c.day()).format('yyyyMMdd');
                psd.StockExternalId__c = psd.DistributionCenter__r.CDExternalId__c + '-' + psd.Sku__c + '-' + decomposedDate;
                stockToUpdate.add(psd);
            }
        }
        
        if(stockToUpdate.size() > 0){
            update stockToUpdate;
        }
    }
}