force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Notificacion__c/Notificacion__c.object-meta.xml
<CustomObject>
    <label>Notificacion</label>
    <nameField>
        <label>Titulo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notificaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Notificacion__c/fields/APM__c.field-meta.xml
<CustomField>
    <fullName>APM__c</fullName>
    <label>APM</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notificaciones</relationshipLabel>
    <relationshipName>Notificaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Notificacion__c/fields/Cuerpo__c.field-meta.xml
<CustomField>
    <fullName>Cuerpo__c</fullName>
    <label>Cuerpo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Notificacion__c/fields/Leido__c.field-meta.xml
<CustomField>
    <fullName>Leido__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Leido</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notificacion_fin_de_Ciclo__mdt/Notificacion_fin_de_Ciclo__mdt.object-meta.xml
<CustomObject>
    <label>Notificacion fin de Ciclo</label>
    <pluralLabel>Notificacion fin de Ciclo</pluralLabel>
</CustomObject>

force-app/main/default/objects/Notificacion_fin_de_Ciclo__mdt/fields/Dias_de_antelacion__c.field-meta.xml
<CustomField>
    <fullName>Dias_de_antelacion__c</fullName>
    <label>Dias de antelacion</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Ciclo__c/VisMed_Ciclo__c.object-meta.xml
<CustomObject>
    <label>Ciclo</label>
    <nameField>
        <label>Ciclo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciclos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Ciclo__c/fields/Anio__c.field-meta.xml
<CustomField>
    <fullName>Anio__c</fullName>
    <formula>YEAR(Fecha_de_inicio__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Año</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Ciclo__c/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_Ciclo__c/fields/Numero_de_mes__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_mes__c</fullName>
    <formula>MONTH(Fecha_de_inicio__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numero de mes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Ciclo__c/fields/VisMed_Cmpt_Tiempo_no_promocional__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Cmpt_Tiempo_no_promocional__c</fullName>
    <defaultValue>$CustomMetadata.Compensatorio_Tiempo_no_Promocional__mdt.Compensatorio_General.Compensatorio__c</defaultValue>
    <label>Compensatorio Tiempo no Promocional</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchNotificacionFinDeCiclo.cls
public class BatchNotificacionFinDeCiclo implements Database.Batchable<sObject>{
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Notificacion_fin_de_Ciclo__mdt mdt = [SELECT Id, DeveloperName, Dias_de_antelacion__c FROM Notificacion_fin_de_Ciclo__mdt LIMIT 1];
        Date diaFinDelCiclo = Date.today().addDays(mdt.Dias_de_antelacion__c.intValue());
        String query = 
        'SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, LastActivityDate, LastViewedDate, LastReferencedDate, Anio__c, Fecha_de_inicio__c, Fecha_de_Fin__c, VisMed_Cmpt_Tiempo_no_promocional__c, Numero_de_mes__c  ' +
        'FROM VisMed_Ciclo__c ' +
        'WHERE Fecha_de_Fin__c = :diaFinDelCiclo ';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<VisMed_Ciclo__c> ciclosQueCierran) {
        List<Contact> APMs = [SELECT Id, Name FROM Contact WHERE Owner.VisMed_Es_un_Visitador_Medico__c = true];system.debug(apms.size());
        List<Notificacion__c> notificacionesToInsert = new List<Notificacion__c>();
        for (Contact APM : APMs) {
            Notificacion__c newNotificacion = new Notificacion__c(
                APM__c = APM.Id,
                Name = APM.Name + ' el ciclo actual está próximo a finalizar, ',
                Cuerpo__c = 'recuerde cargar su actividad pendiente.',
                Leido__c = false
            );
            notificacionesToInsert.add(newNotificacion);
        }
        insert notificacionesToInsert;
    }

    public void finish(Database.BatchableContext BC) {
        // execute any post-processing operations
    }

}