force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/Dan360_ProductoPorPlantilla__c.object-meta.xml
<CustomObject>
    <label>Producto por Plantilla</label>
    <nameField>
        <displayFormat>PrdXPla-{0000}</displayFormat>
        <label>Producto por plantilla</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos por Plantillas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/fields/Dan360_PlantillaProductos__c.field-meta.xml
<CustomField>
    <fullName>Dan360_PlantillaProductos__c</fullName>
    <description>Nombre o código de la plantilla creada para el cliente, en donde están registrados los productos que puede adquirir.</description>
    <label>Plantilla de Productos</label>
    <referenceTo>Dan360_PlantillaDeProductos__c</referenceTo>
    <relationshipLabel>Productos por Plantillas</relationshipLabel>
    <relationshipName>Productos_por_Plantillas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dan360_ProductoPorPlantilla__c/fields/Dan360_Producto__c.field-meta.xml
<CustomField>
    <fullName>Dan360_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nombre o código del artículo que podrá ser adquirido por los clientes.</description>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Productos por Plantillas</relationshipLabel>
    <relationshipName>Productos_por_Plantillas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Dan360_PlantillaProductos__c.field-meta.xml
<CustomField>
    <fullName>Dan360_PlantillaProductos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que se va a llenar con desarrollo para conocer la plantilla que se relaciona al pedido.</description>
    <label>Plantilla de Productos</label>
    <referenceTo>Dan360_PlantillaDeProductos__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductPerTemplateTriggerHandler.cls
public with sharing class ProductPerTemplateTriggerHandler {
	public static void removeInactiveProductsFromOrders(Map<Id, List<Dan360_ProductoPorPlantilla__c>> productsPerTemplate) {
		List<OrderItem> orderItemsToDelete = new List<OrderItem>();
		List<OrderItem> orderItemsToCheck = [
			SELECT  Id,
					Product2Id,
					Order.Dan360_PlantillaProductos__c
			FROM    OrderItem
			WHERE   Order.Status = 'Borrador'
				AND Order.Dan360_PlantillaProductos__c IN :productsPerTemplate.keySet()
		];
		System.debug('orderItemsToCheck');
		System.debug(orderItemsToCheck);
		for (OrderItem orderItem : orderItemsToCheck) {
			System.debug('productsPerTemplate');
			System.debug(productsPerTemplate);
			System.debug('orderItem.Order.Dan360_PlantillaProductos__c');
			System.debug(orderItem.Order.Dan360_PlantillaProductos__c);
			if (productsPerTemplate.containsKey(orderItem.Order.Dan360_PlantillaProductos__c)) {
				for (Dan360_ProductoPorPlantilla__c productPerTemplate : productsPerTemplate.get(orderItem.Order.Dan360_PlantillaProductos__c)) {
					if (productPerTemplate.Dan360_Producto__c == orderItem.Product2Id) {
						orderItemsToDelete.add(orderItem);
					}
				}
			}
		}

		delete orderItemsToDelete;
	}
}