force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/VisMed_Contacto_Cuenta_Usuario__c.object-meta.xml
<CustomObject>
    <description>Relacion de APM con el profesional y su lugar de trabajo</description>
    <label>Fichero</label>
    <nameField>
        <displayFormat>SEG-{0000}</displayFormat>
        <label>Seguimiento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ficheros</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Aun_Quedan_Meses__c.field-meta.xml
<CustomField>
    <fullName>Aun_Quedan_Meses__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Meses restantes de frecuencia</inlineHelpText>
    <label>Aun Quedan Meses</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Baja Temporal</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Fin_de_Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Fin_de_Frecuencia__c</fullName>
    <label>Fin de Frecuencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Inicio_de_Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Inicio_de_Frecuencia__c</fullName>
    <label>Inicio de Frecuencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Seguimientos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Segmenta_Anterior__c.field-meta.xml
<CustomField>
    <fullName>Segmenta_Anterior__c</fullName>
    <label>Segmenta Anterior</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Segmenta_Por__c.field-meta.xml
<CustomField>
    <fullName>Segmenta_Por__c</fullName>
    <label>Segmenta Por</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Segmenta_Por</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Visitas_acumuladas__c.field-meta.xml
<CustomField>
    <fullName>Visitas_acumuladas__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Campo para acumular visitas del pasado, es decir que no son del mes actual</description>
    <label>Visitas acumuladas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Visitas_Realizadas__c.field-meta.xml
<CustomField>
    <fullName>Visitas_Realizadas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Visitas Realizadas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/VisMed_APM__c.field-meta.xml
<CustomField>
    <fullName>VisMed_APM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>APM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Visitador Medico</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ficheros</relationshipLabel>
    <relationshipName>Ficheros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/VisMed_Semaforo__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Semaforo__c</fullName>
    <label>Semaforo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Segmenta_Por.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Adultos General Institucion</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos General Comunidad</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos Oncologia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos y Epilepsia</fullName>
    </customValue>
    <customValue>
        <fullName>Pediatricos General</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia</fullName>
    </customValue>
    <masterLabel>Segmenta Por</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchFrecuenciaSemaforo.cls
public with sharing class BatchFrecuenciaSemaforo implements Database.Batchable<sObject>{
    public static Boolean isRunningFromBatch = false;
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT	Id,';
		query += '				Frecuencia__c,';
        query += '				Aun_Quedan_Meses__c,';
        query += '				Inicio_de_Frecuencia__c,';
        query += '				Fin_de_Frecuencia__c,';
		query += '				Profesional__c,';
		query += '				VisMed_APM__c,';        
        query += '				Segmenta_Por__c,';
        query += '				VisMed_Semaforo__c,';
        query += '				Visitas_Realizadas__c,';
        query += '				Visitas_acumuladas__c,';
        query += '				Estado__c,';
        query += '				Segmenta_Anterior__c';
		query += '		FROM	VisMed_Contacto_Cuenta_Usuario__c';
		query += '		WHERE	Estado__c = \'Activo\'';	
        query += '		OR    Estado__c = \'Baja Temporal\'';
        System.debug('ficheros aprobados el mes pasado: '+query);
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<VisMed_Contacto_Cuenta_Usuario__c> scope){
        System.debug('Ficheros '+ scope);
        // Seteo de frecuencia y visitas realizadas a 0  
        isRunningFromBatch = true;      
        List<VisMed_Contacto_Cuenta_Usuario__c> updateSemaforo = new List<VisMed_Contacto_Cuenta_Usuario__c>();
        for (VisMed_Contacto_Cuenta_Usuario__c seguimiento : scope) {
            if (seguimiento.Estado__c == 'Activo') {                
                if (seguimiento.Frecuencia__c != null) {
                    System.debug('Tiene frecuencia: '+ seguimiento.Frecuencia__c);
                    System.debug('Id: '+ seguimiento.Id);
                    // frecuencia es entera 
                    if (String.ValueOf(seguimiento.Frecuencia__c).endsWith('.00') || String.ValueOf(seguimiento.Frecuencia__c).endsWith(',00') || String.ValueOf(seguimiento.Frecuencia__c).endsWith('.0') || String.ValueOf(seguimiento.Frecuencia__c).endsWith(',0')) {
                        System.debug('Frecuencia Entera: '+ seguimiento.Frecuencia__c);
                        System.debug('Id: '+ seguimiento.Id);
                        seguimiento.Aun_Quedan_Meses__c = false;
                        seguimiento.Inicio_de_Frecuencia__c = System.today().toStartOfMonth();
                        seguimiento.Fin_de_Frecuencia__c = System.today().toStartOfMonth().addMonths(1).addDays(-1);
                        seguimiento.Visitas_Realizadas__c = 0;
                        seguimiento.VisMed_Semaforo__c = 'Rojo';
                        updateSemaforo.add(seguimiento);
                    } else {  
                        //  frecuencia con decimal
                        System.debug('Frecuencia Decimal');
                        System.debug('Id: '+ seguimiento.Id);
                        Integer mesInicio = seguimiento.Inicio_de_Frecuencia__c.Month();
                        Integer mesFinal = seguimiento.Fin_de_Frecuencia__c.Month();
                        Integer mesActual = System.today().month();
                        if (mesActual == mesInicio ) {
                            System.debug('Mes Inicial');
                            System.debug('Mes Inicial= '+seguimiento.Inicio_de_Frecuencia__c);
                            System.debug('Id: '+ seguimiento.Id);
                            seguimiento.Aun_Quedan_Meses__c = true;                                        
                            seguimiento.Visitas_Realizadas__c = 0;
                            seguimiento.Visitas_acumuladas__c = 0;
                            seguimiento.VisMed_Semaforo__c = 'Rojo';
                            updateSemaforo.add(seguimiento);                    
                        }else if( mesInicio < mesActual && mesActual < mesFinal) {
                            System.debug('Mes del medio');
                            System.debug('Id: '+ seguimiento.Id);
                            seguimiento.Aun_Quedan_Meses__c = true;                    
                            seguimiento.Visitas_acumuladas__c +=  seguimiento.Visitas_Realizadas__c;
                            seguimiento.Visitas_Realizadas__c = 0;
                            updateSemaforo.add(seguimiento);
                        }else if( mesFinal == mesActual) {
                            System.debug('Mes final');
                            System.debug('Mes final= '+ seguimiento.Fin_de_Frecuencia__c);
                            System.debug('visitas totales en la frecuencia = '+ seguimiento.Visitas_acumuladas__c);
                            System.debug('Id: '+ seguimiento.Id);
                            seguimiento.Aun_Quedan_Meses__c = false;                    
                            seguimiento.Visitas_acumuladas__c +=  seguimiento.Visitas_Realizadas__c;
                            seguimiento.Visitas_Realizadas__c = 0;
                            updateSemaforo.add(seguimiento);
                        }else {
                            System.debug('Fin periodo de frecuencia se resetea todo+ '+ seguimiento.Fin_de_Frecuencia__c);
                            System.debug('Id: '+ seguimiento.Id);
                            Decimal frecuenciaDecimal = seguimiento.Frecuencia__c;
                            frecuenciaDecimal = Math.abs(frecuenciaDecimal - frecuenciaDecimal.intValue());                           
                            Decimal meses = 1/frecuenciaDecimal;
                            System.debug('frecuencia decimal: '+1/frecuenciaDecimal);
                            seguimiento.Aun_Quedan_Meses__c = true;
                            seguimiento.Visitas_acumuladas__c = 0;
                            seguimiento.Inicio_de_Frecuencia__c = System.today().toStartOfMonth();
                            seguimiento.Fin_de_Frecuencia__c = System.today().toStartOfMonth().addMonths(meses.intValue()).addDays(-1);
                            seguimiento.Visitas_Realizadas__c = 0;
                            seguimiento.VisMed_Semaforo__c = 'Rojo';
                            updateSemaforo.add(seguimiento);
                        }
                    }           
                } else {  
                    // sin frecuencia  
                    System.debug('sin frecuencia');       
                    System.debug('Id: '+ seguimiento.Id);
                    seguimiento.Aun_Quedan_Meses__c = false;
                    seguimiento.Inicio_de_Frecuencia__c = System.today().toStartOfMonth();
                    seguimiento.Fin_de_Frecuencia__c = System.today().toStartOfMonth().addMonths(1).addDays(-1);
                    seguimiento.Visitas_Realizadas__c = 0;
                    seguimiento.VisMed_Semaforo__c = 'Gris';
                    updateSemaforo.add(seguimiento);
                }            
            }
            if (seguimiento.Estado__c == 'Baja Temporal') {
                seguimiento.Visitas_Realizadas__c = 0;
                seguimiento.VisMed_Semaforo__c = 'Gris';
                updateSemaforo.add(seguimiento);
            }
        }

        System.debug(updateSemaforo);
        if (updateSemaforo.size() > 0 && !updateSemaforo.isEmpty() ) {
            System.debug('Update de ficheros');
            Database.update(updateSemaforo, false);
        }         
        
    }

    public void finish(Database.BatchableContext context) {
	}
}