force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/VisMed_Contacto_Cuenta_Usuario__c.object-meta.xml
<CustomObject>
    <description>Relacion de APM con el profesional y su lugar de trabajo</description>
    <label>Fichero</label>
    <nameField>
        <displayFormat>SEG-{0000}</displayFormat>
        <label>Seguimiento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ficheros</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Baja Temporal</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Seguimientos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/Segmenta_Por__c.field-meta.xml
<CustomField>
    <fullName>Segmenta_Por__c</fullName>
    <label>Segmenta Por</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Segmenta_Por</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/VisMed_APM__c.field-meta.xml
<CustomField>
    <fullName>VisMed_APM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>APM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Visitador Medico</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ficheros</relationshipLabel>
    <relationshipName>Ficheros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisMed_Contacto_Cuenta_Usuario__c/fields/VisMed_Semaforo__c.field-meta.xml
<CustomField>
    <fullName>VisMed_Semaforo__c</fullName>
    <label>Semaforo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/VisMed_Segmentacion__c.object-meta.xml
<CustomObject>
    <label>Segmentación</label>
    <nameField>
        <displayFormat>Segmentacion-{0000}</displayFormat>
        <label>Segmentación Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <formula>IF(
  OR(
    RecordType.Name =&apos;Metabolicos&apos;,
    RecordType.Name =&apos;Epilepsia&apos;,
    RecordType.Name =&apos;Metabolicos_y_Epilepsia&apos;
  ),
  Categoria_Nicho__c,
  IF(
    OR(
      RecordType.Name =&apos;Alergia&apos;,
      RecordType.Name =&apos;Pediatricos&apos;,
      RecordType.Name =&apos;Pediatricos General&apos;
    ),
    Categoria_Ped_Aler__c,
    Categoria_Nicho__c
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Categoria</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisMed_Segmentacion__c/fields/Profesional__c.field-meta.xml
<CustomField>
    <fullName>Profesional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profesional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Profesional de la Salud, Otro Profesional</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segmentaciones</relationshipLabel>
    <relationshipName>Segmentaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Segmenta_Por.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Adultos General Institucion</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos General Comunidad</fullName>
    </customValue>
    <customValue>
        <fullName>Adultos Oncologia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos</fullName>
    </customValue>
    <customValue>
        <fullName>Epilepsia</fullName>
    </customValue>
    <customValue>
        <fullName>Metabolicos y Epilepsia</fullName>
    </customValue>
    <customValue>
        <fullName>Pediatricos General</fullName>
    </customValue>
    <customValue>
        <fullName>Alergia</fullName>
    </customValue>
    <masterLabel>Segmenta Por</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchUpdateFicheroCategory.cls
public class BatchUpdateFicheroCategory implements Database.Batchable<sObject>{
    public Database.QueryLocator start(Database.BatchableContext context) {

		String query = 'SELECT	Id,';
		query += '				Profesional__c,';
		query += '				VisMed_APM__c,';
        query += '				Categoria__c,';
        query += '				VisMed_Semaforo__c,';
        query += '				Segmenta_Por__c';
		query += '		FROM	VisMed_Contacto_Cuenta_Usuario__c';
		query += '		WHERE	Estado__c = \'Activo\'';
        query += '		AND     Categoria__c != null';
        query += '		AND     Categoria__c != \'null\'';
		query += '		AND     Segmenta_Por__c != null';
		
		
		System.debug('query:::' + query);
		return Database.getQueryLocator(query);
	}

    public void execute(Database.BatchableContext context, List<VisMed_Contacto_Cuenta_Usuario__c> ficheros) {
		Map<String,Map<String,String>> mapProfesionalSegmentaCategoria = new Map<String,Map<String,String>>();
		Set<String> segmentaPor = new Set<String>();

		Map<String,Map<String,String>> mapProfesionalSegmentaCategoriaSegmentacion = new Map<String,Map<String,String>>();
        for(VisMed_Contacto_Cuenta_Usuario__c fichero : ficheros){
			if(!mapProfesionalSegmentaCategoria.containsKey(fichero.Profesional__c)){
				mapProfesionalSegmentaCategoria.put(fichero.Profesional__c, new Map<String,String>());
			}
			if(!mapProfesionalSegmentaCategoria.get(fichero.Profesional__c).containsKey(fichero.Segmenta_Por__c)){
				mapProfesionalSegmentaCategoria.get(fichero.Profesional__c).put(fichero.Segmenta_Por__c, fichero.Categoria__c);
			}
			segmentaPor.add(fichero.Segmenta_Por__c);
        }
		
		for(VisMed_Segmentacion__c segmentacion : [SELECT Id, Profesional__c, Categoria__c, RecordType.Name FROM VisMed_Segmentacion__c WHERE Profesional__c IN :mapProfesionalSegmentaCategoria.keySet() AND RecordType.Name IN :segmentaPor]){
			if(!mapProfesionalSegmentaCategoriaSegmentacion.containsKey(segmentacion.Profesional__c)){
				mapProfesionalSegmentaCategoriaSegmentacion.put(segmentacion.Profesional__c, new Map<String,String>());
			}
			if(!mapProfesionalSegmentaCategoriaSegmentacion.get(segmentacion.Profesional__c).containsKey(segmentacion.RecordType.Name)){
				mapProfesionalSegmentaCategoriaSegmentacion.get(segmentacion.Profesional__c).put(segmentacion.RecordType.Name,segmentacion.Categoria__c);
			}
		}
		List<VisMed_Contacto_Cuenta_Usuario__c> ficherosToUpdate = new List<VisMed_Contacto_Cuenta_Usuario__c>();
		for(VisMed_Contacto_Cuenta_Usuario__c fichero : ficheros){
			for(String segmentacion : mapProfesionalSegmentaCategoriaSegmentacion.get(fichero.Profesional__c).keySet()){
				if(fichero.Segmenta_Por__c == segmentacion){
					String categoriaToCompare = mapProfesionalSegmentaCategoriaSegmentacion.get(fichero.Profesional__c).get(segmentacion);
					if(fichero.Categoria__c != categoriaToCompare){
						ficherosToUpdate.add(fichero);
					}
				}
			}
		}
		
		SeguimientoTriggerHelper.setFrecuencia(ficherosToUpdate, true, false);
	
	}   

    public void finish(Database.BatchableContext context) {
	}
}