force-app/main/default/objects/Ciclo__mdt/Ciclo__mdt.object-meta.xml
<CustomObject>
    <description>Metadata que contendra el dia de inicio y fin de cada Ciclo</description>
    <label>Ciclo</label>
    <pluralLabel>Ciclos</pluralLabel>
</CustomObject>

force-app/main/default/objects/Ciclo__mdt/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ciclo__mdt/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Compensatorio_Tiempo_no_Promocional__mdt/Compensatorio_Tiempo_no_Promocional__mdt.object-meta.xml
<CustomObject>
    <description>Equivalente de horas de tiempo no promocional en visitas por dia</description>
    <label>Compensatorio Tiempo no Promocional</label>
    <pluralLabel>Compensatorio Tiempo no Promocional</pluralLabel>
</CustomObject>

force-app/main/default/objects/Compensatorio_Tiempo_no_Promocional__mdt/fields/Compensatorio__c.field-meta.xml
<CustomField>
    <fullName>Compensatorio__c</fullName>
    <description>Equivalente en visitas de una hora de Tiempo no Promocional.</description>
    <label>Compensatorio</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuracion_de_motivos_para_la_Baja__mdt/Configuracion_de_motivos_para_la_Baja__mdt.object-meta.xml
<CustomObject>
    <label>Configuracion de motivos para la Baja</label>
    <pluralLabel>Configuracion de motivos para la Baja</pluralLabel>
</CustomObject>

force-app/main/default/objects/Configuracion_de_motivos_para_la_Baja__mdt/fields/Baja_Temporal__c.field-meta.xml
<CustomField>
    <fullName>Baja_Temporal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Baja Temporal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuracion_de_motivos_para_la_Baja__mdt/fields/Baja_Total__c.field-meta.xml
<CustomField>
    <fullName>Baja_Total__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Baja Total</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Frecuencia_por_Categoria__mdt/Frecuencia_por_Categoria__mdt.object-meta.xml
<CustomObject>
    <label>Frecuencia por Categoria</label>
    <pluralLabel>Frecuencia por Categoria</pluralLabel>
</CustomObject>

force-app/main/default/objects/Frecuencia_por_Categoria__mdt/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KOL</fullName>
                <default>true</default>
                <label>KOL</label>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Frecuencia_por_Categoria__mdt/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <label>Frecuencia</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Frecuencia_por_Categoria__mdt/fields/Segmenta_Por__c.field-meta.xml
<CustomField>
    <fullName>Segmenta_Por__c</fullName>
    <label>Segmenta Por</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adultos General Institucion</fullName>
                <default>true</default>
                <label>Adultos General Institucion</label>
            </value>
            <value>
                <fullName>Adultos General Comunidad</fullName>
            </value>
            <value>
                <fullName>Adultos Oncologia</fullName>
            </value>
            <value>
                <fullName>Metabolicos</fullName>
            </value>
            <value>
                <fullName>Epilepsia</fullName>
            </value>
            <value>
                <fullName>Metabolicos y Epilepsia</fullName>
            </value>
            <value>
                <fullName>Pediatricos General</fullName>
            </value>
            <value>
                <fullName>Alergia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Limite_de_retraso__mdt/Limite_de_retraso__mdt.object-meta.xml
<CustomObject>
    <label>Limite de retraso</label>
    <pluralLabel>Limites de retraso</pluralLabel>
</CustomObject>

force-app/main/default/objects/Limite_de_retraso__mdt/fields/Cantidad_de_Dias_de_Retraso__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Dias_de_Retraso__c</fullName>
    <label>Cantidad de Dias de Retraso</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notificacion_fin_de_Ciclo__mdt/Notificacion_fin_de_Ciclo__mdt.object-meta.xml
<CustomObject>
    <label>Notificacion fin de Ciclo</label>
    <pluralLabel>Notificacion fin de Ciclo</pluralLabel>
</CustomObject>

force-app/main/default/objects/Notificacion_fin_de_Ciclo__mdt/fields/Dias_de_antelacion__c.field-meta.xml
<CustomField>
    <fullName>Dias_de_antelacion__c</fullName>
    <label>Dias de antelacion</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Diario__mdt/Target_Diario__mdt.object-meta.xml
<CustomObject>
    <description>Target de visitas a relaizar por el APM en un dia.</description>
    <label>Target Diario</label>
    <pluralLabel>Target Diario</pluralLabel>
</CustomObject>

force-app/main/default/objects/Target_Diario__mdt/fields/Numero_de_mes__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_mes__c</fullName>
    <label>Numero de mes</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Diario__mdt/fields/Sub_Equipo__c.field-meta.xml
<CustomField>
    <fullName>Sub_Equipo__c</fullName>
    <label>Sub Equipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adultos Interior</fullName>
                <default>true</default>
                <label>Adultos Interior</label>
            </value>
            <value>
                <fullName>Adultos Oncologia</fullName>
            </value>
            <value>
                <fullName>Metabolicos</fullName>
            </value>
            <value>
                <fullName>Dieta</fullName>
            </value>
            <value>
                <fullName>Pediatricos General</fullName>
            </value>
            <value>
                <fullName>Alergia</fullName>
            </value>
            <value>
                <fullName>Adultos AMBA</fullName>
            </value>
            <value>
                <fullName>Metabólicos y Dieta</fullName>
            </value>
            <value>
                <fullName>Nicho MSL</fullName>
            </value>
            <value>
                <fullName>Adultos General</fullName>
                <isActive>false</isActive>
                <label>Adultos General</label>
            </value>
            <value>
                <fullName>Institución y Comunidad</fullName>
                <isActive>false</isActive>
                <label>Institución y Comunidad</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Diario__mdt/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GeneralEnvironmentSettingsComponentTest.cls
@isTest
public class GeneralEnvironmentSettingsComponentTest {
    @isTest
    public static void getCicloMetadata() {
        Test.startTest();
        List<GeneralEnvironmentSettingsComponentCtrl.ObjectWrapper> obj = GeneralEnvironmentSettingsComponentCtrl.getData('ciclo__mdt','Id,DeveloperName,Label,Fecha_de_inicio__c,Fecha_de_Fin__c');
        Test.stopTest();
        System.assertEquals(obj.size(), obj.size(), 'No trajo la metadata');
    }

    @isTest
    public static void getCompensatorioTiempoNoPromocionalMetadata() {
        Test.startTest();
        List<GeneralEnvironmentSettingsComponentCtrl.ObjectWrapper> obj = GeneralEnvironmentSettingsComponentCtrl.getData('Compensatorio_Tiempo_no_Promocional__mdt','Id,DeveloperName,Label,Compensatorio__c');
        Test.stopTest();
        System.assertEquals(obj.size(), obj.size(), 'No trajo la metadata');
    }

    @isTest
    public static void getLimiteDeRetrasoMetadata() {
        Test.startTest();
        List<GeneralEnvironmentSettingsComponentCtrl.ObjectWrapper> obj = GeneralEnvironmentSettingsComponentCtrl.getData('Limite_de_retraso__mdt','Id,DeveloperName,Label,Cantidad_de_Dias_de_Retraso__c');
        Test.stopTest();
        System.assertEquals(obj.size(), obj.size(), 'No trajo la metadata');
    }

    @isTest
    public static void getTargetDiarioMetadata() {
        Test.startTest();
        List<GeneralEnvironmentSettingsComponentCtrl.ObjectWrapper> obj = GeneralEnvironmentSettingsComponentCtrl.getData('Target_Diario__mdt','Id,DeveloperName,Label,Sub_Equipo__c,Numero_de_mes__c,Target__c');
        Test.stopTest();
        System.assertEquals(obj.size(), obj.size(), 'No trajo la metadata');
    }

    @isTest
    public static void getNotificacionFinCicloMetadata() {
        Test.startTest();
        List<GeneralEnvironmentSettingsComponentCtrl.ObjectWrapper> obj = GeneralEnvironmentSettingsComponentCtrl.getData('Notificacion_fin_de_Ciclo__mdt','Id,DeveloperName,Label,Dias_de_antelacion__c');
        Test.stopTest();
        System.assertEquals(obj.size(), obj.size(), 'No trajo la metadata');
    }

    @isTest
    public static void getMotivoDeBajaMetadata() {
        Test.startTest();
        List<GeneralEnvironmentSettingsComponentCtrl.ObjectWrapper> obj = GeneralEnvironmentSettingsComponentCtrl.getData('Configuracion_de_motivos_para_la_Baja__mdt','Id,DeveloperName,Label,Baja_Total__c,Baja_Temporal__c');
        Test.stopTest();
        System.assertEquals(obj.size(), obj.size(), 'No trajo la metadata');
    }

    @isTest
    public static void getFrecuenciaPorCategoriaMetadata() {
        Test.startTest();
        List<GeneralEnvironmentSettingsComponentCtrl.ObjectWrapper> obj = GeneralEnvironmentSettingsComponentCtrl.getData('Frecuencia_por_Categoria__mdt','Id,DeveloperName,Label,Categoria__c,Segmenta_Por__c,Frecuencia__c');
        Test.stopTest();
        System.assertEquals(obj.size(), obj.size(), 'No trajo la metadata');
    }

    /* @isTest
    public static void updateMetadata() {
        GeneralEnvironmentSettingsComponentCtrl.ObjectWrapper wrapper = new GeneralEnvironmentSettingsComponentCtrl.ObjectWrapper(
        );
        wrapper.Numero_de_mes_c = 4;
        wrapper.Sub_Equipo_c = 'Alergia';
        wrapper.Target_c = 2;
        wrapper.developerName = 'Abril_2022_Alergia';
        wrapper.fullName = 'Target_Diario.Abril_2022_Alergia';
        wrapper.id = 'm04030000008S2BAAU';
        wrapper.label = 'Abril_2022_Alergia';

        Object objJson = (Object) wrapper;
        List<Object> listObjs = new List<Object>{objJson};
        System.debug(listObjs);
        //List<Object> json = '({Numero_de_mes_c=4, Sub_Equipo_c=Alergia, Target_c=2, developerName=Abril_2022_Alergia, fullName=Target_Diario.Abril_2022_Alergia, id=m04030000008S2BAAU, label=Abril_2022_Alergia})';
        Test.startTest();
        List<GeneralEnvironmentSettingsComponentCtrl.ObjectWrapper> obj = GeneralEnvironmentSettingsComponentCtrl.updateMetadata(listObjs);
        Test.stopTest();
    } */
    
}